DuggaSys/diagram.css
DuggaSys/diagram.js
DuggaSys/diagram.php

Added active class for the modes in the toolbar, this class is removed when a mode is deselected and added to the element if the mode is currently in use.

Added active class for modes in toolbar

---

DuggaSys/diagram.js
DuggaSys/diagram.php
Shared/icons/diagram_grid.svg

Replaced the current button with an appropriate svg image.

Switched out "enable grid" button

---

DuggaSys/diagram.css
DuggaSys/diagram.js
DuggaSys/diagram.php
Shared/icons/diagram_zoomin.svg
Shared/icons/diagram_zoomout.svg

Reverts HGustavs/LenaSYS#10170

Revert "Fixed: No error message for reaching line limit"

---

DuggaSys/diagram.js

Added an missing else statement and moved the error to the correct location

Added missing else statement

---

DuggaSys/templates/generic_dugga_file_receive.js
Shared/dugga.js

moved generation of hash from when save button is clicked to when the dugga is opened. Added hash to form in generic_dugga_file_receive to enable hash storage in submission table.

Update dugga.js and generic_dugga_file_receive.js

---

DuggaSys/diagram.js
DuggaSys/diagram.php
Shared/icons/diagram_ruler.svg

Switched the current button for enabling / disabling the ruler to an svg image.
Co-Authored-By: @a19aleda

Added svg image to ruler button

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Added so the "enableGrid" and "enableRuler" also toggle the class "active" on the button-elements.

Added highlighted background to grid / ruler buttons

---

Shared/SQL/alterTables.sql
Shared/SQL/init_db.sql

added hash col in submission table. Added alter to submission table include hash

updated init_db.sql and alterTables.sql

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php
Shared/css/style.css

Added functionality for selecting and deleting multiple items.
Created new button for this in the header next to FabButton2.
Created a new function to clear the marked items array when editing items or adding new ones. Otherwise this will invert the multiselect function.
Co-author: @a19danla

G2 2021 w16 issue#10079

---

DuggaSys/diagram.css
DuggaSys/diagram.js
DuggaSys/diagram.php

It also added a global variable the is used to check if the ruler is active to determine wether the code for the ruler should be running or not.

change name for enableGrid and enableRuler

---

DuggaSys/diagram.js

Added a global variable so that we can clear the timer right before we set a new one.

Make the global timer reset when a new message is pushed

---

DuggaSys/diagram.js

When creating lines between elements, it's now possible to see a line between the selected element and the mouse cursor before selecting the next element.
Co-Author:
@a19hammi

Added functionality when drawing lines between elements #10157

---

DuggaSys/diagram.js

Changed cursor style when selecting an element

Changed cursor style to default

---

DuggaSys/diagram.js

Added functionallity so if the user has selected elements before started an box-select and CTRL is pressed the elements stays selected until they are marked with the box-select.

Added previous selected elements to box-select

---

DuggaSys/diagram.js

The code has been refarctored according to the given code standard K&R.
@a19frelu

Diagram code refactored

---

DuggaSys/showDugga.php
Shared/dugga.js
Shared/hashpasswordauth.php

G1 2021 w16 #10141 v3

---

DuggaSys/showDuggaservice.php
DuggaSys/templates/generic_dugga_file_receive.js
Shared/dugga.js

Mega fix, Issue #10200 and #10053 are re-implemented on W17 branch.

G1 2021 w17 #10053

---

DuggaSys/filereceive_dugga.php
DuggaSys/showDugga.php
DuggaSys/showDuggaservice.php
DuggaSys/templates/daily-minutes.js
DuggaSys/templates/generic_dugga_file_receive.js
DuggaSys/templates/group-assignment.js
Shared/SQL/alterTables.sql
Shared/SQL/init_db.sql
Shared/dugga.js

Restored functionality from older pull requests during W16

G1 2021 w17 #10272 - Restored lost functionality

---

DuggaSys/diagram.js

Fixed the line selection while holding down cmd key on MacOS.

Fixed cmd key on MacOS

---

DuggaSys/diagram.php

Moved Grid/Ruler button from the options panel to the toolbox.

Moved Grid/Ruler button

---

DuggaSys/diagram.js

Added an return statement so the function does not generate a longer id than necessary.

Fixed so makeRandomID return on first generated ID.

---

DuggaSys/diagram.css
DuggaSys/diagram.php

Fixed the issue that arose when sliding the elements out of screen.
Also removed the horizontal scroll-bar.

Fixed sliding of elements

---

DuggaSys/showDuggaservice.php
Shared/dugga.js

fixed variant for the 6th time (today)

fixed variant for the 6th time (today)

---

DuggaSys/diagram.js

Fixed: Missing code #10269 

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Added tooltips to the new buttons.

Added: Tooltips to new buttons and changed keybinds.

---

DuggaSys/diagram.js

StateChangeFactory now includes a new method for storing deleted elements and lines together as a single state change.
fixes #10225

Store lines and elements deleted together

---

DuggaSys/showDugga.php
DuggaSys/showDuggaservice.php
Shared/dugga.js

Added password to select in query in showDuggaservice.php and to the array at the end.  Runs setPassword with the retrieved password value in dugga.js

Restored Password fetch

---

DuggaSys/diagram.js

The bug where objects gets yeeted has been fixed :D

Group3 2021 w17 #10262

---

DuggaSys/diagram.js

Keybinds have been added to the options pane, ruler and grid buttons.
Pointer mouse mode shortcut is changed back to 'm'.
@a19frelu

Added keybinds to pane, ruler and grid buttons

---

DuggaSys/diagram.css
DuggaSys/diagram.js

Grid now covers 100% of the screen and follows and grows when you scroll around.

Grid now covers 100% of the screen and follows and grows when you scroll and zoom.

---

Shared/css/style.css

Fixed issue that delete button was overlapping course text

Added restriction for delElement

---

DuggaSys/templates/diagram_dugga.html
DuggaSys/templates/diagram_dugga.js

Added a instructions and iframe for diagram-dugga.

Added instructions and iframe for diagram-dugga

---

Shared/dugga.js

Ensure Hash Uniqueness v.2.0 #10282

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Fixed the keybinding display when showing the tooltip for toggle grid and ruler.

Fixed keybinding in tooltip

---

DuggaSys/showDugga.php

2 character issue @a18osken, ty 👍 
#10311

G1 2021 w17 #10311

---

DuggaSys/diagram.js

If statement was removed from the previous pull request and are now added in this :)

"fixed" Accidental deletion of if-statements in removeElements

---

DuggaSys/diagram.css
DuggaSys/diagram.js

Custom styled the save button and added color shade to achieve some feedback.

Added custom save button

---

DuggaSys/diagram.js

StateMachine initial state stored on diagram launch

---

DuggaSys/diagram.js

Added 2 keybinds that allow copy (CTRL + C) and paste (CTRL + V). Also the functionality that copies and pastes the clipboard array.

Added: Copy and paste functionality

---

DuggaSys/filereceive.php
DuggaSys/filereceive_dugga.php
DuggaSys/showDuggaservice.php

File submissions/uploads are now saved with hash and appears in the table.

G1 2021 w17 #10146 v2

---

Shared/css/style.css

Co-Authored-By: a18willi <81558529+a18willi@users.noreply.github.com>

Fix fab button menu in landscape phone mode issue#10244

---

sh/query.php

Only the error message has been altered, the funtionality to store keywords in courekeys had already been implemented.
Co-Authored-By: Philip Karlsson <81557308+b18phika@users.noreply.github.com>

Changed the error message to be more general. Issue#10090

---

DuggaSys/showDuggaservice.php
Shared/dugga.js

The variant now loads and the function to set the time to live now works, for each time the get time expire function is loaded, it checks if the variants TTL has expired or not. When its expired, it removes the key and we get a new variant.

G1 2021 w17 #10102 v3

---

DuggaSys/diagram.js

Now all lines can be de-selected when pressing esc

Added function to de-select selected lines with esc

---

DuggaSys/diagram.js

Added key binding for selecting all elements and add function to select all elements and lines and put them into respective context array

Added key binding for selecting all elements

---

DuggaSys/diagram.js
DuggaSys/diagram.php

The box and text had no functionality in the current diagram and therefore it was removed.
Issue #10347

Removed the "now placing" box from the options-pane.

---

DuggaSys/diagram.css
DuggaSys/diagram.js
DuggaSys/diagram.php

Made som changes to the displayMessage system in the diagram.

Diagram: Updated the displayMessage system to show multiplie messages

---

DuggaSys/diagram.css

Added pointer as mouse cursor

---

DuggaSys/sectioned.js
Shared/css/style.css

Fixed the bug that made two arrows to show on initial small screens

Fixed bug concerning arrows issue#10369

---

DuggaSys/showDuggaservice.php
Shared/dugga.js

Ziparchive added to submission preview

G1 2021 w17 #9782

---

DuggaSys/filereceive_dugga.php
DuggaSys/showDugga.php
DuggaSys/showDuggaservice.php
Shared/dugga.js

Do not prompt for a password when refreshing the page for uploading a file.

G1 2021 #10361

---

DuggaSys/diagram.css

Now the timerIndicatorBar is easier to see

Fixed bar opacity

---

DuggaSys/sectioned.php

fixed so course name is more centralized in mobile view.

Centralized course text for mobile view

---

DuggaSys/diagram.js

onSetup function for loading in the pre-determined objects

Created function for loading pre-generated objects #10364

---

DuggaSys/diagram.js

remove unessassary line of code that creates multiple texts

Remove unessassary line of code that creates multiple texts

---

DuggaSys/diagram.js

This really needs some form of improvement in the future for a smoother experience. Couldn't figure out a way as it stands right now and have decided to submit this rather than nothing. If someone finds a better solution throw a new pull request!
fixes #10336

Implemented: Zoom in based on mouse position #10336 

---

DuggaSys/diagram.css
DuggaSys/diagram.php
Shared/icons/diagram_attribute.svg
Shared/icons/diagram_box_select.svg
Shared/icons/diagram_entity.svg
Shared/icons/diagram_grid.svg
Shared/icons/diagram_line.svg
Shared/icons/diagram_pointer_white.svg
Shared/icons/diagram_relation.svg
Shared/icons/diagram_ruler.svg
Shared/icons/diagram_zoomin.svg
Shared/icons/diagram_zoomout.svg

Change color scheme for toolbar to match duggasys scheme better

Change color scheme for toolbar

---

DuggaSys/diagram.js

Removed the uneccessary if statement.

Removed if statement

---

DuggaSys/diagram.js

Added so you can add values to the start and end to the line.

Added cardinality to the diagram

---

DuggaSys/diagram.js

Fix: Prevented error on using GUI zoom buttons

---

Canvas documentation/connect_lenasys_to_canvas.md

the result of the research we did on LTI, and there are couple of code examples and links.

G1 2021 w17 #10391

---

DuggaSys/diagram.js

Removed line that caused statemachine to save multiple elements

Removed line that caused statemachine to save multiple elements

---

Shared/dugga.js

**Remember to clear localstorage when testing!**

Condense the PDUGGA success function #10422

---

Shared/dugga.js

URL hash can generate with slashes #10457

---

DuggaSys/diagram.js

Selected lines no longer gets deselected when moving a line \o/

Group3 2021 w17 #10377

---

DuggaSys/diagram.js

It's now possible to change the line.kind attribute with radio buttons instead of the previous drop-down menu.

Change: From Drop-down menu to radio button #10394

---

DuggaSys/diagram.js

fixed by adding style to the text attribute to make them act the same way as the text in the entities

"fixed"Make line cardinalities zoom with the rest of the elements.

---

DuggaSys/diagram.js

Moving an element and then resizing now works as intended.
Updated the code inside of the stateChange class to follow new standard using values.
No external behavior changed.

Moving element and resizing now works

---

DuggaSys/diagram.css
DuggaSys/diagram.js
DuggaSys/diagram.php

Made some changes to the grid position so it now is statis to the coordinates in the diagram. Also added the functionality to support snap to grid.

Diagram: Added snap to grid

---

DuggaSys/diagram.js

Done it correctly this time
sorry for brain dmg, today is not my day

Group3 2021 w17 #10456

---

Shared/css/style.css

Change tabs2 to 32 px, then we comment out the (Vertical line for 2 tabs) maybe the code might be useful in the future.
@a18danli

mobile View

---

Shared/css/style.css

Co-Authored-By: a19samke <62887067+a19samke@users.noreply.github.com>

Change color to announcement card text

---

Shared/css/style.css

Co-Authored-By: a18willi <81558529+a18willi@users.noreply.github.com>

Make button text color darker, to improve contrast issue#10404

---

DuggaSys/diagram.php
Shared/icons/diagram_gridmagnet.svg

Created a SVG image for the "snap to grid" button.

SVG button added

---

DuggaSys/diagram.js

It is now possible to pan with the mousewheel pressed (mouse3)

Added: Panning with mouse3 (mousewheel)

---

DuggaSys/diagram.css
DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/templates/diagram_dugga.html
DuggaSys/templates/diagram_dugga.js
Shared/icons/diagram_attribute.svg
Shared/icons/diagram_box_select.svg
Shared/icons/diagram_entity.svg
Shared/icons/diagram_grid.svg
Shared/icons/diagram_gridmagnet.svg
Shared/icons/diagram_line.svg
Shared/icons/diagram_pointer_white.svg
Shared/icons/diagram_relation.svg
Shared/icons/diagram_ruler.svg
Shared/icons/diagram_zoomin.svg
Shared/icons/diagram_zoomout.svg

week 17, weekly merge, group 3

Group3 2021 w17 main

---

Shared/css/dugga.css
Shared/dugga.js

Submissions preview content is no longer offset

G1 2021 #10508

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Removed the panning cursor when pressing middle mouse button

Removed panning cursor

---

DuggaSys/diagram.js

Added ctrlPressed check to onfocus function.

Updated onfocus function

---

DuggaSys/diagram.js

The snap to grid functionallity does now also work with the ghost elements.

SnapToGrid is now working on ghost elements

---

DuggaSys/diagram.js

implemented a function for deltaexceed calculation and fixed the error with box selecting from lines
Co-Authored-By: Hamlet Magnusson Millqvist <81571224+a19hammi@users.noreply.github.com>

"Fixed" Starting a box select on a line bug

---

DuggaSys/diagram.js

Added the missing parameter for `addObjectToLines()` in `addLine()`.

Added missing parameter

---

Shared/dugga.js

To review:
- Make sure hash is correctly stored in your database.
- Check that the flag "ishashindb" is set to it's correct value. To do this, force the value of the hash to be one that already exists in your database, the value should be forced inside the generateHash() method like this: hash = "alreadyExistingValue"; If everything works correctly the flag will notice this non-unique hash and generate a new one (part of _handleHash()_ method).
- Make sure you get a variant when doing a dugga. Change the ms value 2592000000 to 5000 (5 seconds) on row 1165. Then clear localstorage and spam-refresh the dugga, every 5 seconds a new variant of the dugga should be loaded.

"Does the PDUGGA ajax call need an ajax call in its success function" #10504 (now without merge conflict)

---

DuggaSys/diagram.js

There is now only one option while changeing propertys of an line. An line can only have one cardinality and a default has been added.

Updated cardinality

---

DuggaSys/diagram.js

Put the checking of key and ctrl into a general function reducing the complexity of reading

General function for checking key and ctrl

---

DuggaSys/diagram.js

Changed the gridsize to the height of entitys, and added so the size is automatic scales with the varible gridSize.

Changed: gridSize and added automatic scaling to the varible

---

DuggaSys/diagram.js

changed colors from red and green to yellow and purple( colorblind friendly colors)
have NOT tested the colors because i dont have anyone to test them on but the colors that i picked are colorblind friendly according to adobe colors

Change colors of the lines #10546 - colors have been changed 

---

DuggaSys/diagram.css
DuggaSys/diagram.js

Made the select cardinality bars better positioned and made it look prettier! Also added "none" to the empty option!

Group3 2021 w18 10514

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Added lines that are drawn according to the width and height of the window along origo on the x and y axes.
Co-Authored-By: a19aleda <81557207+a19aleda@users.noreply.github.com>

Created thicker lines for origo on the x and y axes

---

DuggaSys/diagram.css
DuggaSys/diagram.php

Added the tool-tip info panel when hover over the option button.

"Fixed" Tool-tip for the option-panel

---

DuggaSys/analytic.php
DuggaSys/analyticService.php
Shared/navheader.php
Shared/sessions.php

Access to analytics now checks if the user is a superuser or creator. Most teachers are creators but not superusers therefore the old code only including superusers didnt work.

Analytics page and "hamburger"-button now shows properly for both teachers and superusers. Issue#10499

---

Shared/css/style.css

Co-Authored-By: a19samke <62887067+a19samke@users.noreply.github.com>

Swimlane layout change

---

DuggaSys/analytic.php
DuggaSys/analyticService.php
Shared/navheader.php
Shared/sessions.php

Removed faulty code that made teachers and students able to access the analytics page. 
#10607 
Co-Authored-By: @a18willi

Removed faulty code

---

Canvas_test_data.md

Added  Students and Teachers on Canvas.

G1 2021 #10572

---

DuggaSys/diagram.js

It's now possible to double-click an element in order to edit the text area.
Double-clicking an element automatically opens the options-panel as well.

Double-click functionality for editing element text 

---

DuggaSys/accessedservice.php

Added a check to see if the user has a write access to the course before sending any any user data.

No longer possible to access student data through the accessed page. Issue#10547

---

Shared/dugga.js

Made it so that you get the same dugga by storing the initial hash and reloading the dugga using the same hash from localstorage. To check, simply clear localstorage, enter the dugga assignment on canvas, and take notice of the dugga key with the hash included and save the dugga. Whereupon you will receive the hash which you can then again load the saved dugga. If you have issues loading the iframe, simply go into the HTML editor and change the filepath to your local address for biträkningsdugga.
The issue should work on both the canvas installation in the assignment and on your local installation of lenasys. Simply enter http://canvas.webug.his.se/courses/1/assignments/5 to go to the live version (which loads the dugga from your local installation).

G1 2021 w18 #10474 v2

---

DuggaSys/showDugga.php
Shared/dugga.js

Saves score variable for each dugga in an array in localstorage

Score in localstorage - #10435

---

Shared/navheader.php
Shared/sessions.php

The hamburger menu now shows for both teachers and superusers while viewing a course though the sectioneditor.

Hamburger menu in sectioned(courses) now show for both supersusers and teachers Issue#10499v2

---

DuggaSys/diagram.css
DuggaSys/diagram.js

Added a square to the middle of the selected lines and included them in the selection box calculation
Pair-programmer: @a19steis

Made it more clear which lines are selected

---

DuggaSys/showDugga.php

**Removed reset button for rapport inlämning (generic_dugga_file_receive)**
* Test this by going to a rapportinlämnings page.
_Co-Authored-By: e15marol <markus-olsson@outlook.com>_

Removed reset button for rapport inlämning

---

DuggaSys/templates/html_css_dugga.html
DuggaSys/templates/html_css_dugga_light.html

Removed Random css dugga pop-up window in html_css_dugga.html and Replaced this window with a instruction container.

Removed Random css dugga pop-up window #10601

---

DuggaSys/showDugga.php

Created a feedback area that is only visible for teachers when ther are logged in and on a handed in assignment (hash is not unknown).

Create feedback area for teachers #10568

---

Shared/dugga.js
sh/index.php

The value "deadline" was missing from the URL when using the hash & password URL, so I simply added the deadline variable to the URL redirection. In addition, if statement _if(comment == undefined)_ used incorrect syntax.
**To test this:**
- Enter a dugga, press Save. Does it tell you if you have missed the deadline or not? Is the message correct?
- Next, use the hash & password URL to enter the dugga again, press Save once more. Is the message still correct?

Receiptbox - The exclamation point is "undefined" if we enter a hash & password URL and press Save #10606

---

Canvas_test_data.md

Created course G1- Webbutveckling - datorgrafik.
Created all assignments for the course, and Iframed all assignments along with a text submission for each assignment.

G1 2021 #10574

---

DuggaSys/templates/dugga3.html
Shared/css/style.css

We've replaced the popup-instructions with an instructions container in linjedugga 1 and 2

Replace popup instructions in linjeduggor #10642

---

DuggaSys/showDugga.php
Shared/css/dugga.css
Shared/dugga.js

Created a "Load Dugga" button in the bottom right of every dugga. If you click it you will get a popup window that prompts you to enter a hash. This then redirects you to index.php wich further redirects you to the specified dugga.

G1 2021 #10628 Create a redirection button for showdugga.php

---

Shared/dugga.js

Removed the grey bulb and "dugga" from the navbar while in a dugga
Co-Authored-By: @a18willi

Removed bulb and dugga from navbar

---

DuggaSys/diagram.js

Snap to grid should now be less chaotic and move in unison
Co-Authored-By: a19aleda <81557207+a19aleda@users.noreply.github.com>

Made elements snap to grid as a unit

---

Shared/css/style.css

Changed from hardcoded colorcode to predefined variables.

Update style.css (Issue #10265)

---

Canvas_test_data.md

Added the course "MasterBranch - Webbutveckling - datorgrafik" and its assignments.

Create assignment in Canvas for the master branch #10644

---

Shared/SQL/alterTables.sql
Shared/SQL/init_db.sql

Added triggers that remove entries from groupdugga whenever a matching hash entry is removed from userAnswer.

Added trigger

---

DuggaSys/showDugga.php
DuggaSys/templates/generic_dugga_file_receive.js
Shared/dugga.js

Separated the accordion toggles for instructions and feedback into two different functions, toggleFeedback and toggleInstructions

Added toggleFeedback function and changed feedback area construction

---

DuggaSys/showDuggaservice.php

Teacher gets a variant! #10650

---

DuggaSys/diagram.js

Added check for if line is a double line and appended "-1" and "-2" to the IDs that are added to tempLines.
Co-Authored-By: a19frelu <62895155+a19frelu@users.noreply.github.com>

Double lines are now included in selection box

---

DuggaSys/showDugga.php
DuggaSys/templates/clipping_masking_dugga.js
DuggaSys/templates/dugga1.js
DuggaSys/templates/dugga2.js
DuggaSys/templates/dugga3.js
DuggaSys/templates/dugga4.js
DuggaSys/templates/generic_dugga_file_receive.js
DuggaSys/templates/html_css_dugga.js
DuggaSys/templates/kryss.js
Shared/dugga.js

To test this issue, simply enter the datorgrafik course and save any of the "duggor" and then save again, whereafter you will receive a popup that asks if you are sure you want to save again.
Co-Authored-By: b18jacha <62884577+b18jacha@users.noreply.github.com>

G1 2021 w18 #10627

---

DuggaSys/diagram.js

If atleast one element is selected that is unlocked, then all those elements will be locked.
If all elements are locked then the elements will be unlocked.
The option is displayed when we generate the properties for one or more elements.

Elements can now be locked in place

---

DuggaSys/diagram.css
DuggaSys/diagram.js
DuggaSys/diagram.php
Shared/icons/diagram_a4.svg

Made a template of a A4-sheet with a button to toggle it on/off

Made a template of a A4-sheet

---

DuggaSys/diagram.js

Now does the stateMachine only store the change and no flags. Also algorithms has been added to remove default values for changes. The  stepBack functioallity has also be changed so when a stepBack in the history is made, the current data is removed and replaced by looping through the history.

Diagram: Reduced history data size

---

DuggaSys/templates/3d-dugga.js
DuggaSys/templates/XMLAPI_report1_file_receive.js
DuggaSys/templates/bit-dugga.js
DuggaSys/templates/boxmodell.js
DuggaSys/templates/clipping_masking_dugga.js
DuggaSys/templates/color-dugga.js
DuggaSys/templates/curve-dugga.js
DuggaSys/templates/dugga1.js
DuggaSys/templates/dugga2.js
DuggaSys/templates/dugga3.js
DuggaSys/templates/dugga4.js
DuggaSys/templates/dugga5.js
DuggaSys/templates/feedback_dugga.js
DuggaSys/templates/generic_dugga_file_receive.js
DuggaSys/templates/group-assignment.js
DuggaSys/templates/html_css_dugga.js
DuggaSys/templates/html_css_dugga_light.js
DuggaSys/templates/placeholder_dugga.js
DuggaSys/templates/shapes-dugga.js
DuggaSys/templates/transforms-dugga.js

We replaced the alerts (that did not work before) with confirms that displays a warning for when clicking on reset-button in duggor. If you choose ok then everything resets and if cancel then nothing happens.

Added warnings for when clicking on reset buttons #10676

---

DuggaSys/diagram.js

You can now choose weak key attribute.
Updated branch and some small fixes.

Fixed weakKey attribute

---

DuggaSys/diagram.css
DuggaSys/diagram.js
Shared/icons/pad_lock.svg

Added a svg element to the locked function, a padlock icon will be placed on the entity if the entity is locked in place

"Fixed" There should be a way to see if a element is locked (visually)

---

DuggaSys/codeviewer.js
DuggaSys/sectioned.js
Shared/dugga.js

We changed some localstorage names to clarify what they actually do.
- Test this by delete all localstorage items and generate new ones!
_Co-Authored-By: e15marol <markus-olsson@outlook.com>_

G1 2021 w19 #10665

---

DuggaSys/diagram.js

Now rulerSettings, zoomSettings and gridSettings are structured as objects

Added objecs for rulerSettings, zoomSettings and gridSettings

---

DuggaSys/diagram.js

Fixed the issue with zoom in/out on mac keyboard zooming in the browser.

Fixed CMD zoom in/out on mac

---

DuggaSys/diagram.js

The stateMachine now support stepBack(), also some changes to the functions has been made for reusablilty.

Diagram: Support for stepForward in the history

---

DuggaSys/sectioned.js

8 commits >:(

---

DuggaSys/showDugga.php
Shared/css/style.css

btn-disable class prevents click and alters color of button.

Added btn-disable class

---

DuggaSys/diagram.js

The text is now calculated from the coordinate on the line instead of the end/start point of the line. The offset from the line is also taken into account depending of the number of connected lines to the same side of an entity.

Updated cardenality

---

DuggaSys/templates/clipping_masking_dugga.js

check that there's no error referring to trying to split on undefined.
fixes #10721

Pull request for #10721

---

DuggaSys/showDugga.php

To test: enter to any assignment as super user, and check if the error message still occurs in the console window.

included the function's path in showDugga.php

---

DuggaSys/codeviewer.php

Fixes the issue.
Test by going into any dugga in the course webbprogrammering.

No more PDOException

---

DuggaSys/diagram.js

Fix bug where elements could be placed with other mouse buttons than left click

Fix bug where elements could be placed with other mouse buttons than left click

---

DuggaSys/diagram.js

Added line to generate properties when everything is selected

Added line to generate properties when everything is selected

---

DuggaSys/diagram.js

Add the function call to display a message

Display message on properties saved

---

DuggaSys/diagram.js

Check so that only mouse button 0 can trigger double click

Check so that only mouse button 0 can trigger double click

---

DuggaSys/diagram.js

fixed an issue where the lock button in the properties field doesnt change regardless if the element is locked or not

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php
DuggaSys/sectionedservice.php
Shared/css/style.css

Can now hide multiple items at the same time using the "-" button.

"Delete marked items" button now hides marked items from students instead. Issue#10280

---

Shared/css/style.css

@a18danli 
Make hidden courses  to line-through to make sure the courses is hidden!

Update the Hidden courses

---

DuggaSys/duggaed.php

Adding padding to the right of the button.
Co-Author: @a19isada

Fab button no longer covers "edit"-button in duggaed. Issue#10761

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

In the edit item menu, it now shows between which dates a deadline has to be set.
Co-Author: @a18willi

Now shows which date a deadline has to be set between Issue#10697

---

Shared/navheader.php

Removed onclick code that made a blank page show onclick on the "looking glass"-icon

Fixed broken search onclick funtion in fileed. Issue#10805

---

Shared/icons/file_download_white.svg
Shared/navheader.php

Added a white download icon and updated navheader for fileed.

Added icon and updated navheader.php issue #10807

---

DuggaSys/sectioned.js

Reverted the old template literals that were breaking several functions.
Co-Authored-By: b19wilfo 62884368+b19wilfo@users.noreply.github.com

Reverted Template Literals

---

DuggaSys/templates/dugga3.html
Shared/css/style.css

**Added some styling so linjeduggor is centered.**
To test:
- Go to a linjedugga and resize the window, also try mobile etc. It should be in the centered.
_Co-Authored-By: e15marol <markus-olsson@outlook.com>_

Added some styling so linjeduggor is centered

---

DuggaSys/diagram.js

Now you cannot change size on ERRelations

Added if-statement

---

DuggaSys/showDugga.php

We fixed so that
- teachers can't upload files on submission dugga 
- feedback area is visible on handed-in assignments for teachers
- save and reset for already handed in assignments should be disabled
- teachers do not need to write in password for students handed-in assignments

Added teacher access/functionality #10781

---

DuggaSys/showDugga.php
DuggaSys/showDuggaservice.php

Fixed function that checks the latest hash visited.

You get prompted for password when you update the "Rapport inlämning" dugga #10735

---

DuggaSys/sectioned.js

Updated the code that makes sure that new items are placed at appropriate places and not off-screen. We still have a bug that places new items at the button at the screen if too many items are created at the same time. We are still waiting for response from teacher regarding this bug.
Co-author: @a19danla

G2 2021 w19 issue#10552

---

DuggaSys/diagram.js

The cardinalities should now be as demonstrated in issue #10577.
The cardinalities sometimes cut into the line but i think that is related to another/earlier issue.

Fixed demo diagram

---

DuggaSys/diagram.js

Now you can copy elements and move them around without any problems or errors with ctrl C and ctrl V.

Fix: copy-paste after/before panning or moving elements

---

DuggaSys/templates/clipping_masking_dugga.js
DuggaSys/templates/html_css_dugga.html
DuggaSys/templates/kryss.js
Shared/dugga.js

Fixed css-dugga, clipping-dugga and frågedugga in the course "Webbutveckling - datorgrafik" so that the buttons now are enabled when the user is interacting with the dugga.

Buttons are now enabled in duggas after interacting #10844

---

Shared/dugga.js

Added a second if statement for value _false_ .
To try this:
- Make sure no "Uncaught TypeError" appear in console when loading a dugga as Guest. 
- As a guest, make sure no "Next variant" button appear next to the dugga title in any dugga.
- As a teacher, make sure the "Next variant" button appear next to the dugga title. Note that on one or two duggor the button doesn't display since no variants have been set yet.

Uncaught TypeError: Cannot read property 'style' of null #10850

---

DuggaSys/diagram.js

Coordinates are now correct when zooming.

Fixed correct coordinates on ruler when zooming

---

DuggaSys/resulted.js

timeSubmitted column is now sortable

Added timeSubmitted as sortable

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Added eventListener for when the mouse leaves container

Fixed: Bug with panning mode staying active

---

DuggaSys/sectioned.php
Shared/icons/ghost_icon.svg

Changed the hide multiple icon from a "-" to a ghost. 
Co-Author: @a18willi

Changed hide multiple button icon

---

Shared/css/style.css

Removed duplicate announcement button
Co-Author: @a18willi

Removed duplicate announcement button

---

DuggaSys/sectioned.js

Updated the file with template literals and row breaks to increase readability.
Hopefully it wont break the swimlane functionality this time.
Co-Authored-By: b19wilfo 62884368+b19wilfo@users.noreply.github.com

G2 2021 w19 issue#10831

---

DuggaSys/diagram.js

Fix so that the ruler bars move independantlly of the x and y position of the mouse position

Fix so that the ruler bars move independantlly of the x and y position of the mouse positon

---

DuggaSys/templates/dugga3.html

Fixed the "Ritverktyg" box overlapping

---

sh/index.php
sh/query.php

We've fixed so that you can use either the hash to load the assignment or the course string. 
To test entering a course for example, simply put "http://localhost/lenasys/LenaSYS/sh/?c=Software Engineering IT301G HT15" in your URL, or to test the hash simply put http://localhost/lenasys/LenaSYS/sh/?a=<hash> with a hash being in your database, if you enter the wrong hash you get a 404 page.
Combining an assignment and course should work, but this is something that's going to be implemented in the next week's branch instead.
Co-Authored-By: b18jacha 62884577+b18jacha@users.noreply.github.com

G1 2021 w19 #10865

---

DuggaSys/diagram.php
Shared/icons/diagram_replay.svg

Created an appropriate SVG image to the replay button.

Created SVG for replay button

---

DuggaSys/diagram.js

Changed the number check, before it also returned true if it was only numbers in the string. Also blacklisted id from appending because it should not be possible. And removed time when restoring an object.

Blacklisted id on append and changed number check

---

DuggaSys/diagram.js

This fixed the problem with the replay in play mode.

Cleared the replayTimer in diagram.

---

DuggaSys/diagram.js

Missplaced if function from the beginning so i moved the if statement so the escape now works

"Fixed" Small bug: Exiting Replay-mode with Esc not always working

---

DuggaSys/contribution.js
DuggaSys/contribution.php
DuggaSys/contributionservice.php

In order to test this the tester needs too change the date on line 185 to (2019,04,02), since the database contains only commits from 2019.
Tester also needs to change the filepath in contributionservice.php, line 21 to your local filepath.
To reach contribution page you first need to sign in as brom from http://localhost/lenaSYS/DuggaSys/courseed.php,
and then go to http://localhost/lenaSYS/DuggaSys/contribution.php
Co-author: @a19kimgr

Contribution committree#10382

---

DuggaSys/templates/dugga3.js

To try this:
- Go into a "linjedugga".
- Open up console.
- Press the button "linje" to add a line.
- Without selecting the line from the list, press "Flytta ner".
- Make sure no error appear in console.

Remove the error when the "Flytta ner" button is pressed in Linjedugga #10821

---

DuggaSys/sectioned.js
Shared/css/style.css
Shared/navheader.php

Made text clickable on the hamburger menu in sectioned.

Dropdown menu text is now clickable

---

DuggaSys/resultedservice.php

added if statement to allow only teachers and super users to view the table in resulted.php

Added teacher access check

---

DuggaSys/resulted.php

Email button is removed
Issue #10970

Removed email button

---

DuggaSys/resulted.php

Removed the examinator dropdown .
Closing #10974

Removed the examinator label and dropdown

---

DuggaSys/sectioned.js

Change the swimlane text color from blue to darkblue !
@a18danli

Change the swimlane text color

---

Shared/navheader.php

Fixed MotD icon, it no longer disappears when reloading. The problem was only for teacher/superuser.

Update navheader.php Issue #10915

---

DuggaSys/resulted.php

The update table function can not be removed
Final result, filter dropdown removed
Issue #10975

Removed the dropdown and label for filter

---

DuggaSys/diagram.js

Added zoomfact to text margins so that the margins change with the zooming

Added zoomfact to margin

---

DuggaSys/diagram.js

Now the code for handeling deleted elements and lines will now be executed. Lenght of keys when deleting elements has the length of 2 not 1.

Chnaged key length to 2

---

DuggaSys/diagram.js

Now placing new elements will only happen in container

Added if statement to check if element you clicked on is in container

---

DuggaSys/diagram.js

Added check so you need to be in replay-mode to exit.

Added check if replay-mode is active on "esc"

---

DuggaSys/diagram.js

Added so isLocked-attribute on elements gets saved in the stateMachine also for lines it now saves "cardenality" and "kind".

Added missing changes to stateMachine

---

DuggaSys/diagram.js
DuggaSys/diagram.php
Shared/icons/.svg
Shared/icons/screenUpdate.svg

Now you can center the camera around all elements.

Center camera

---

DuggaSys/diagram.js

The zoomfactor for max zoom-out is now 0.25

Changed max zoom-out to 0.25 instead of 0.125

---

DuggaSys/resulted.js
Shared/dugga.js

Hard to test before weekly merge. But you can test it on your own setup by opening a dugga, clicking on the save and then try to use the URL to enter the dugga in another tab.

Some of our solutions for URL are hardcoded make them relative in appropriate places #10931

---

DuggaSys/resulted.js
DuggaSys/resultedservice.php

We have added a new column in the resulted table for how many times a handed in dugga has been accessed

Added new table column in resulted  #10981

---

DuggaSys/diagram.css

added a z-index to the replay bar

"Fixed" Messages appear over replay bar

---

DuggaSys/diagram.js

Handle elements overlapping, so that it resets the position of the element being placed over another element and triggers a display message error.

Handle elements overlapping

---

DuggaSys/diagram.css
DuggaSys/diagram.js

Change the z index for elements in context to be 1 and also changed the z index of ruler bars to 2, so that the selected elements doesnt overlap the ruler

Fix selected elements are ontop of other elements

---

DuggaSys/diagram.js

Fix the problem that zoomOrigo was resetted on extra zoom out.

Fix reset on scrollZooming

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php
DuggaSys/showDugga.php

Moved the 'Load Dugga' button to _sectioned.php_
**To try this:**
- Make sure both students and teachers can see the button once entering a course in LenaSys.
- Test the button. No functionality have been altered, so everything should work the same.

"Move load dugga button and code from showdugga to sectioned #10971"

---

DuggaSys/sectioned.js

Swimlane not show in mac safari

---

.gitignore
DuggaSys/contribution.js
DuggaSys/contributionservice.php

Co-author: @a18willi @b16oskni

Created a legend for weekly line chart

---

sh/index.php

**We can now use assignment and course together as parameters in the url.**
a=Biträkningsdugga 1
c=Webbutveckling - datorgrafik IT118G HT15
To test this function, try and enter the following:
* http://localhost/lenasys/LenaSYS/sh/?c=Webbutveckling - datorgrafik IT118G HT15&a=Biträkningsdugga 1

G1 2021 W20 #10934

---

.gitignore
DuggaSys/contribution.js
DuggaSys/contributionservice.php

Updated functionalty to show Hourly activites by weeks instead of day.
Added additional input element.
co-author; @a19isada @a18willi

Added functionality to contribution tool clock. Issue#9837

---

errorpages/404.php

Did a similar solution to the one that already existed in the 403 page code.
Test this issue by entering both:
http://localhost/lenasys/LenaSYS/errorpages/403.php
and 
http://localhost/lenasys/LenaSYS/errorpages/404.php
and clicking the hyperlinks, which should take you to the homepage.

G1 2021 w20 #11031

---

Shared/navheader.php

Searchbar is removed from resulted.php.
The code for the searchbar is commented out for now.

Remove the search bar from resulted #11019

---

DuggaSys/showDugga.php
DuggaSys/showDuggaservice.php
Shared/hashpasswordauth.php

Now you get the login box every time you enter a url after saving.

Remove no password access to saved dugga #11005

---

Shared/dugga.js

To test: close the login box in a dugga. this should redirect you to the according course page.
for some reason, sometimes the login box does not appear. just try with another dugga

redirected duggan's login to course page

---

DuggaSys/resulted.js
DuggaSys/resulted.php
Shared/SQL/alterTables.sql
Shared/css/style.css

added filter option to search by time interval

update resulted table

---

Shared/css/style.css

Changed the colour on the .contribheading
Co-author: @a19isada @b16oskni

Color scheme change in contribution view. Issue#7358

---

DuggaSys/duggaedservice.php
DuggaSys/showDugga.php
DuggaSys/showDuggaservice.php

We've added student teacher acceess to duggaed so that student teachers now can view and change duggas in that file. We also added access to "next variant" as student teacher, and disabled "save" and "reset" buttons in duggas.

Added student teacher access #10982

---

DuggaSys/contribution.js
DuggaSys/contributionservice.php

Co-author: @a19isada @b16oskni

Added a legend to the the bar chart. Issue#11026

---

Shared/css/style.css
Shared/navheader.php

@a18danli 
The message of the day button moved to the dropdown menu in mobile vers!

Update The message of the day and added to the hamburgerBox

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Saves and/or exports a file in JSON-format.
Import only works with JSON-files as well.

Added: Save, Export, Load functionality with buttons in options-panel

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Added a function to the a4 presentation so the user is now able to switch between horizontal and vertical mode and change the size of the A4 template

"Fixed" Be able to resize and move the A4 representation

---

DuggaSys/diagram.js

Ctrl and alt selection also works

Can now select lines with box selection

---

DuggaSys/diagram.js

It is now possible to move selected elements with the arrow keys.
**Keep in mind:** With this soultion it is not possible to move elements in snap to grid.

Diagram: Move element with keys

---

DuggaSys/diagram.css
DuggaSys/diagram.php

changed the z-index for the svg overlay and the changed the order of the php file so the z-index could work

"Fixed" Box surrounding selected elements not on top of other elements

---

Shared/dugga.js

Test all the dugga if they cycle through all the variants.

The next variant gets stuck in Frågedugga 1 #11056

---

DuggaSys/resulted.php
Shared/SortableTableLibrary/sortableTable.js

Removed ladexport from resulted.php and the export functionality in sortableTable class

Removed ladExport

---

DuggaSys/resulted.js
DuggaSys/resulted.php
Shared/css/style.css

added button that shows checkboxes for each dugga, you can now filter by multiple duggas instead of just one

added new dugga filter options

---

Canvas documentation/add_courses_and_assignments.md
Canvas_test_data.md

This Pull request is to get contribution for the courses and users I added in Canvas a few weeks ago.

Added documentation from an old Issue I've already finished #10318

---

DuggaSys/diagram.js

Added an updateA4Pos() and an updateA4Size() call inside the centerCamera() function

A4 will now scale correctly when pressing the "home" key

---

DuggaSys/diagram.js

Added an offset on the y axis for box selection of half the height of the element(s)

Fixed incorrect y axis offset for box selection

---

DuggaSys/resulted.php
Shared/SortableTableLibrary/sortableTable.js
Shared/dugga.js

To test: check so that the title of the dugga + variant is a clickable button that gives you the next variant in both desktop and mobile mode.  (Also, remember to clear localstorage before you try it.)

Combine the title and next variant button in showdugga #11082

---

Shared/css/style.css
Shared/dugga.js

Removed The sun grade from the dugga header in file dugga.js.

No more sun grade in dugga #11081

---

Shared/navheader.php

hover function gone ‎‎‎                    ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎                    ‎‎‎                  ‎‎‎ …

G1 2021 w21 #10996

---

DuggaSys/diagram.css
DuggaSys/diagram.js
DuggaSys/diagram.php

stateMachine does now save only absolute values.

stateMachine does now save only absolute values

---

DuggaSys/contribution.js
DuggaSys/contributionservice.php

Indication of national holidays now show in the barchart. Note that currently holidays needs to be entered manually and is probably something that should be automatized in another issue.
Co-author: @a19isada @b16oskni

Added visual indication of national holidays in barchart. Issue#9768

---

DuggaSys/resulted.js

Now it is possible to sort after Times submitted and Times accessed 👍
The sorting on Times submitted did not work as it should, solved this in the compare function so the numbers were sorted in the correct order.
Check out "Edit student results" and click on the headings for Times submitted and Times accessed and you will see masterpieces of sorting!

Sort after Times submitted and Times accessed #11104

---

DuggaSys/resulted.js
DuggaSys/resulted.php
Shared/navheader.php

Removed old buttons from navbar and dropdown filter.

Removed old buttons

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Disabled CTRL+A in edge creation mode as suggested in the issues comments.

Disabled select all in edge creation mode

---

DuggaSys/contributionservice.php

Commented out unused variables.

Comment out lastname and firstname in contributionservice.php #11066

---

DuggaSys/contributionservice.php

Changed a select statement to select commit count from blamefile instead of from commitgit
Co-auth: @a19isada @a18willi

Commits not showing in contribution #11146

---

DuggaSys/accessedservice.php

Commented out ssn, firstname, and lastname since they're no longer used.
Co-Authored-By: b19wilfo 62884368+b19wilfo@users.noreply.github.com

G2 2021 w21 issue#11070

---

DuggaSys/sectionedservice.php

@a18danli 
Update sectionedservice.php

Comment out lastname and firstname

---

DuggaSys/courseed.js
DuggaSys/sectioned.js
Shared/dugga.js
Shared/navheader.php

MOTD now shows an icon in navheader if closed in courseed page. It will stay that way if you visit another part of the site and then return to the courseed page. 
Co-author: @a18willi @b16oskni

MOTD now shows an icon in navheader if closed

---

DuggaSys/contribution.js

Added holiday to legend
Co-author: @a18willi @a19isada

Add explanation to the legend for the pink bar indicating national holiday #11126

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Removed the fab button from the diagram, also made sure to remove any unusable code. Especially in toggleReplay as suggested in the comments.

Removed fab (+) button from diagram ui

---

DuggaSys/diagram.js

It is now possible to add a label between relation and entity.

Label on lines between relation and entity is possible

---

DuggaSys/showDuggaservice.php
Shared/dugga.js

G1 2021 w21 #11087

---

DuggaSys/diagram.js
DuggaSys/diagram.php

ctrl-z should work as intended now.
Co-Authored-By: Hamlet Magnusson Millqvist <81571224+a19hammi@users.noreply.github.com>

Potential fix: ctrl-z bug

---

DuggaSys/diagram.js

As the topic said, the coordinates values is now without decimals

Position values is now without decimals

---

DuggaSys/diagram.css
DuggaSys/diagram.js

You can now change the fill and stroke colors of elements from the options panel. This has also been added to the State Machine. The undo functionality is, however, a bit broken so it will be difficult to test (hopefully fixed with pull request: #11153).
**Note that the color options are only placeholders and will most likely need to be revised for accessibility purposes.**

Added the ability to change fill and stroke color of elements

---

DuggaSys/diagram.php

change function call to open side bar

change function call to open side bar

---

DuggaSys/diagram.php

the button was successfully moved one step down.

Fixed issue #11116 :  moved the button one step down 

---

DuggaSys/sectioned.js

Removed broken condition for deleteitems function
Co-author: @a19isada @b16oskni

Now able to delete items even when multiple items are selected. Issue#11170

---

DuggaSys/diagram.js

fixed by adding the fucntion to the enter keybinding

"Fixed" Being able to save by pressing enter

---

DuggaSys/resulted.php
Shared/SortableTableLibrary/sortableTable.js

Added search bar to highlight rows with specified number of times accessed. 
To test: simply input the value that you want to highlight in the edit student results page and then click the enable button and the rows with the same/greater values will be highlighted.

Highlight a row that have a extremly high number times accessed #11105

---

DuggaSys/resulted.js
DuggaSys/resulted.php

The date range is now set aside for the earliest and most recent submitted tab

G1 2021 w21 #11086

---

DuggaSys/contribution.js

Added functionalty to show from which dates the data is gathered.
co-auth: @a19isada @a18willi

Add which dates the bar chart is showcasing #11157

---

Shared/css/style.css
Shared/navheader.php

Super_user having access to the teacher tools/ hamburger menu

---

DuggaSys/contribution.js
DuggaSys/showDuggaservice.php
DuggaSys/templates/3d-dugga.js
DuggaSys/templates/bit-dugga.js
DuggaSys/templates/dugga1.js
DuggaSys/templates/dugga2.js
DuggaSys/templates/dugga5.js
DuggaSys/templates/kryss.js
DuggaSys/templates/placeholder_dugga.js
DuggaSys/templates/shapes-dugga.js

G1 2021 w21 #11190

---

DuggaSys/templates/diagram_dugga.js

The future states are now removed before saveing the diagram-dugga.

Diagram-dugga removes future states before saveing.

---

DuggaSys/diagram.js

it is not possible to create a line from/to a relation that has an recursive relation or possible to create an recursive relation if the relation is connected to an other element.

Restriction for lines for Recursive relations.

---

DuggaSys/diagram.css
DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagramkeybinds.md

You can now toggle a list of keybindings by pressing the F1 key.

Added a markdown file with a list of keybindings to the diagram application.

---

testfiles/Grupp3Test/a17nikjo.txt
testfiles/Grupp3Test/a20sacka.txt
testfiles/Grupp3Test/a20vicad.txt
testfiles/Grupp3Test/readme.txt
testfiles/linustestfile.txt

Don't actually accept this pull request it's just a test.

Grupp3 test pull request experiment

---

DuggaSys/accessed.js

Cleaned up code in accessed.js

G1 2022 w1 #11267

---

Shared/SQL/init_db.sql

Removed unnecessary and faulty references that added nothing to the database

---

DuggaSys/sectioned.php
DuggaSys/showDugga.php
DuggaSys/testDugga.php

Solved by going through all files two times, found swedish in three of them

Changed some swedish to english

---

Shared/css/codeviewer.css

Changed display style from inline-block to inline.

Change display style

---

DuggaSys/diagram.js
DuggaSys/diagram.php

The redirect camera to center button will not zoom in to zoomfactor 1x.

No zoom when redirect camera #11236

---

DuggaSys/sectioned.js

Could not find any other reference in LenaSys to "UNKz". Fixing the typo should not cause any problem.

fixed the typo 'UNKz to UNK'

---

DuggaSys/codeviewer.js

added css attribute overflow: hidden to copy notification box

Copy notification does not overflow under other elements #11217

---

DuggaSys/courseedservice.php

Cleaned up code in courseedservice.php

G1 2022 w1 #11305

---

DuggaSys/diagram.css

Clean up of diagram.css #11311

---

DuggaSys/showdoc.php

Clean up of showdoc.php #11335

---

DuggaSys/showDuggaservice.php

Clean up of showDuggaservice.php #11332

---

DuggaSys/codeviewer.php

A commit was made by Henrik Gustavsson that only commented out these lines of code on the September 9, 2021, 12:59 PM.  Since I cannot find a reason in the version controll, the commented code is removed.

Removed commented code.

---

Shared/dugga.js

Commented out the if statement that is always false and is never able to run.

Commented out statement that is always false

---

Shared/css/style.css
Shared/navheader.php

Issue solved, changed login button

G3 2022 w1 #11220

---

DuggaSys/codeviewer.php
Shared/css/style.css

When hambruger menu is clicked once it will view content.

Added a function on body onload

---

DuggaSys/codeviewer.js

Added showCopybutton function to maximizeBoxes. Also fixed the getTotalBoxes function. (It previously always returned undefined.)

Added showCopyButtons() to maximizeBoxes()

---

DuggaSys/codeviewer.js

Removed previously commented out code.

Removal of commented out code

---

DuggaSys/showDuggaservice.php
DuggaSys/templates/generic_dugga_file_receive.js
Shared/dugga.js

Fixed the issue of duggor not properly showing up. The previous code used the variable hash to select database entries which didn't work since no entry was associated with it.  Instead the variable moment is used to retrive all entries for that dugga. The solution might have solved part of the issue but further testing with a larger dataset is needed to confirm.

Origin/g3 2022 w1 #11227

---

DuggaSys/templates/johan.md

Deleted unnecessary file Johan.md

Deleted unnecessary file

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

Created dialog, button and function linking them together.

added dialog and button

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

reverting before mockup for interface is avaliable

Waiting for mockup

---

DuggaSys/resulted.js

Added Teacher visited column in resulted.js

---

DuggaSys/codeviewer.js

For testing:
1: When on the first example in the list of examples, the backwards button should be greyed out and unclickable.
2: when on the last example in the list the forwards button should be greyed out and unclickable.
3: The backwards and forwards buttons should follow the order of the list of duggor.

G2 2022 w2 #1851 

---

Shared/css/codeviewer.css

Compared this to an old version, seems the same.

Added a height attribute to the buttonmenu

---

Shared/css/style.css

Fixed animations with CSS in contribution.php in file style.css

---

Shared/navheader.php

Removed code mentioning analytics.php from navheader.php

G3 2022 w2 #11467

---

DuggaSys/codeviewer.js
DuggaSys/codeviewer.php
Shared/css/blackTheme.css

A class was created and added where dark backgrounds were needed, in two different files. It is style in blackTheme.css.

Added a class DarkmodeBackgorund

---

DuggaSys/showDugga.php
Shared/dugga.js

Adjusted file dugga.js which had an fault on line 1099 resulting in the receipt popup didn't show

Changed dugga.js to reenabled receipt popup

---

DuggaSys/diagram.js

Implemented a delete button located in the right upper corner of a selection box.
3) Click or box select any element/s
4) Click cross icon in the right upper corner of the selection box and the elements selected should get deleted

Implemented delete button #11387

---

DuggaSys/resulted.js
DuggaSys/resulted.php
Shared/SortableTableLibrary/sortableTable.js
Shared/css/style.css

Added a button to filter columns in resulted.php. This pull request does not offer any functionality when the search button is pressed. This adds a functional button beside the current existing one. The button makes a menu appear where you can check different columns in the table below on the same page and should offer functionality to filter which column the teacher would like to filter by in the future.

G3 2022 w2 #11379

---

DuggaSys/diagram.js

Here is a solution. See description in the issue. I talked with Therese about the purple colour and we decided that purple was to dark for the background of the elements, since the text becomes too hard to see.

G1 2022 w2 #11396

---

DuggaSys/templates/diagram_dugga.html
DuggaSys/templates/diagram_dugga.js

Created an alert dialog message that pops up before diagram dugga window is closed or refreshed.

Created functionality for an alert that pops up before closing diagram dugga #11485

---

DuggaSys/codeviewer.js

make Edit Button can not see if you do not login
Go in a Dugga and you can see three Button: maximize button, minimize button, reset button.
Log in with teacher account and you can see the 4th button: Edit button.

move Edit button code

---

DuggaSys/sectioned.js

Removed alert dialog when a new item has been updated

Removed alert dialog

---

Shared/css/blackTheme.css

Added missing section for headers changing to white while user prefers dark mode.

Fixed headers in dark mode.

---

DuggaSys/codeviewer.js

make the dugga layout reset upon loading.

reset page 

---

DuggaSys/diagram.js
DuggaSys/diagram.php
Shared/icons/diagram_uml.svg

Updated diagram.js to allow the creation and placement of UML entities. Some things that should be: Check if it is possible to place, move and delete the UML entity. Check if it is possible to change the title, color of background and stroke. Check if the attribut box expands correctly depending on how many attributes.

Diagram module - UML entity #11445

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

Validation is now uniformly, issue #8528.

Validation corrected

---

DuggaSys/codeviewer.js

Implemented a function to remove the drop down once the user clicks outside of them.

Added function to remove dropdowns when user clicks outside of them.

---

DuggaSys/resulted.js

Clicking a checkbox in the column filter previously had no effect on the resulted table. This functionality was added to hide columns that are unchecked and reveal them again when checked. The functionality of the "Select All" button was also changed slightly.
Added a function that checks what columns are filtered before updating the table. Added and rewrote functions for onclick event for the checkboxes in the dugga and column filter menu to make the "Select All" checkbox more reliable.
To test:
1. Navigate to http://127.0.0.1/LenaSYS/DuggaSys/resulted.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732
2. Open the column filter.
3. Click any checkbox and see the result in the table.
4. Click the "Select All" button with different checkboxes checked/unchecked. The …

Implemented column filter functionality and improved the "Select all" button

---

DuggaSys/fileed.js
DuggaSys/fileedservice.php

In fileed.js
The only testing to be done might be to try editing markdownfiles with "+" signs and se that it works not just for me.

Removed the lines "content = content.replace(/\+/g, '%2B'); for issue #11493

---

DuggaSys/duggaed.js
Shared/navheader.php

Commented out the previous search bar in duggaed.js, this can be removed when the new search bar has been tested properly. Added a new search bar by including the navheader.php search bar. Tooltip functionality added by copying hover-related functions from accessed.js to duggaed.js.

Tooltip functionality added to duggaed.php search bar

---

DuggaSys/diagram.js

G1 2022 w2 #11455

---

DuggaSys/diagram.js

G1 2022 w2 #11479

---

DuggaSys/templates/diagram_dugga.html
DuggaSys/templates/diagram_dugga.js

G1 2022 w2 #11485

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

G1 2022 w2 #8528

---

DuggaSys/diagram.js

G1 2022 w2 #11451

---

DuggaSys/diagram.js
DuggaSys/diagram.php
Shared/icons/exit.svg
Shared/icons/replay.svg

G1 2022 w2 #11442

---

DuggaSys/diagram.js
DuggaSys/diagram.php
Shared/icons/diagram_uml.svg

G1 2022 w2 #11445

---

DuggaSys/diagram_IOHandler.php

#11252 Put a simple description of what the ui in diagram_IOHandler.php does and added some notes for future developers. diagram_IOHandler.php is far from finished so the actual planned functions is not known.

Added a description on diagram_IOHandler.php #11252

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

@a20behta New more conservative version that does not cut as mush code.

G3 2022 w2 #11482

---

DuggaSys/fileed.js
DuggaSys/fileed.php
DuggaSys/fileedservice.php
DuggaSys/filereceive.php

Added comments to multiple files handling upload/download of files, inserts/selects/updates regarding database entries.

Made clarifying comments regarding uploading/saving of files (fileed.php, fileed.js, fileedservice.php, filerecieve.php)

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

This is a work in progress for #11477, but so far it lists files from the database but it isn't doing anything with them. Next step is to filter out everything that isn't a .json file and read it's content as a new diagram dugga. It's possible to test this by editing any dugga in duggaed.php

WIP Creation of file select drop-down menu connected to database #11477

---

DuggaSys/contributionservice.php

Added info about the usage on the provided db file

Added comment about the usage of the db file

---

DuggaSys/contributionservice.php

Fault with Linux machines solved, wrong type of slashes in address

G3 2022 w3 #11598

---

DuggaSys/resulted.js
Shared/navheader.php

Try to search files/duggas and press ENTER and check that the page does not reload.

Prevent "enter" from reloading page

---

DuggaSys/contribution.js
Shared/css/style.css

Adding graphical components to contribution.js and style.css for changing repositories in Contribution.php.

Adding graphical components for changing repositories in Contribution.php

---

DuggaSys/resulted.js

Moved previous code for handling row filter updates to a new function and added a call to the function in the table update function. Made a minor change to the rowFilter function to implement the proper filter behavior, which should also slightly improve readability.
To test:
1. Home page -> Webbutveckling - datorgrafik -> Edit student results (button). Alternatively, go to http://127.0.0.1/LenaSYS/DuggaSys/resulted.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732
2. Open the dugga filter by clicking the button on the top of the screen
3. Select/unselect any checkboxes. The result should be immediately visible in the table.

Added functionality to the checkboxes in the dugga filter in resulted

---

DuggaSys/showDugga.php
Shared/dugga.js

To Test:
Open a dugga change something and leave the page in someway. A promt should appear warning you that changes will be discarded.

Alert when leaving a dugga with changes done.

---

DuggaSys/courseed.php
DuggaSys/coursefooter.php
DuggaSys/sectioned.php
Shared/icons/Dark:lightmode_toggle.svg

Created a new file containing a footer.  It will be displayed on the front and within courses. There is a small icon at the bottom where it should be possible to click so it will be dark mode or light mode. (does not work yet)

Added a footer that contained an icon

---

DuggaSys/diagram.js

removed unnessecary zoomfact that caused issues
https://user-images.githubusercontent.com/81320323/163206219-cfbdeec3-019a-4e9a-8937-12ff8bd6f6db.mp4
issue number #11155

fix for issue #11155 Select & Move labels in diagram

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

Added support for selection of a file in the drop-down menu to be reflected in the automatic JSON params box on the right side of the "edit dugga" menu screen.

Added selected diagram file to be included in generated JSON params

---

DuggaSys/diagram.js

Reverts HGustavs/LenaSYS#11668

Revert "Box around selected element: #11396"

---

DuggaSys/codeviewer.php
DuggaSys/coursefooter.php
Shared/css/style.css

Added the footer in codeviewer, and fixed the overlay in dugga exemple

Fixed the overlay in areas in dugga exemple

---

DuggaSys/codeviewer.js

Add few code to make the dropbar do not disappear when you hold 1s.

Make the dropbar do not disappear

---

DuggaSys/codeviewer.js

Change little code at function copyCodeToClipboard() at codeviewer.js. Make it just copy important code.

Code to just copy important code

---

DuggaSys/sectioned.js

Can now apply invalid deadlines when editing items in sectioned, and fixed validateSectName function for item titles.

Can apply invalid deadlines, fixed validateSectName function #11224

---

DuggaSys/diagram.js

#11668 Was pushed to master , then reverted, but could not make a new pull request so added the code by hand into a new branch.

G1 2022 repair#3

---

DuggaSys/sectioned.js

Previusly you had to click the href link now you can click most of the row (other buttons excluded) to get to the dugga page.

dugga link now works on background element

---

DuggaSys/sectioned.js

you can now click on the background elements for duggor at webbprogrammering aswell.

href now found by searching all children

---

Shared/css/style.css

The code for LenaSYS title dissappearing is now fixed and works correctly.

Changed code for LenaSYS title dissappearing so that it works correctly#11641

---

DuggaSys/showDugga.php

Some commented out code are kept due to them serving a purpouse (testing/"placeholder"/etc.).
No testing required

Removed the commented out code in showDugga.php for issue #11240

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php
Shared/navheader.php

I changed regex on file sectioned.js Line 2409 and Line 2444. 
Select query changed in anheader.php, to fetch start date of course too(Line 127). Year value is equl to year that course starts(Line 136-137).
You can test it by creating new course with information below or other information that you want, but be carefull that copy content from should be none, otherwise you get error. There is other issue for solving this problem.

G3 2022 w4 #11222

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Removed the emoji in Diagram Dugga on optmarker in both diagram.php and diagram.js.

Removed emoji from Diagram Dugga #11762

---

DuggaSys/contribution.js
DuggaSys/contribution.php
DuggaSys/contributionservice.php

Fixed the issue in pull request https://github.com/HGustavs/LenaSYS/pull/11772

G3 2022 w4 #11628

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

Lighthouse no longer complains about missing alt tags on said page.

added alt tags too images

---

DuggaSys/contribution.js

I have already explained what this issue is on several occasions and its the same as always. The only change is that we push into a array rather than make a bunch of variables and the push those variables into a array on lines 118 - 182, also i updated the red day list to contain all holidays that can be red days even if they are on a week end as requested.
To test that this works change branch to G3-2022-W4-#11113 and go to http://localhost/LenaSYS/DuggaSys/contribution.php where you will se a new column in the contribution table.

The latest version of the red day list in contributions

---

DuggaSys/templates/dugga1.html
DuggaSys/templates/dugga1Instructions.md
DuggaSys/templates/duggaTest.html
DuggaSys/templates/duggaTest.js
DuggaSys/templates/duggaTestInstructions.md
Shared/css/style.css

There are 3 "testfiles" that make it possible for teachers to create duggas that get their instructions from a markdown file. This is in preperation for it to be possible to edit their instructions.
These three files are the "temporary testfiles" (they're under templates)
When creating a new dugga using this "model" you open the dugga editor and add a new dugga by pressing the yellow "+"-button and under "template" you choose "duggaTest". Then under the "start page" of the course and add a new test. Under "link" you choose the dugga you just made and press "save". That is all, thank you.

Gather dugga instructions from .md file#11773

---

DuggaSys/codeviewer.js

How to test:
Open HTML5_Example 1(templateid=6) and make sure it doesn't look like this: 
Then create a new code example with template 7 and test the same thing.

G2 2022 w4 #11701

---

DuggaSys/codeviewer.js

Removed hide editbtn to allow editbtn to be shown in template 10

Fixed hideMaximizeAndResetButton() #11708

---

Shared/css/codeviewer.css

10px padding cover the code when drag the box to minimize.

Padding change

---

DuggaSys/codeviewer.js

Cleaned commented out code i file codeviewer.js.

Cleaned code in codeviewer.js

---

Shared/SQL/init_db.sql
sh/index.php

New SH URL handler. Not complete, still needs handling for changed course/assignment names, changed course/assignment id, deleted course/assignment and prevention of creating multiple SHs for the same URL.

G2 2022 w4 #11512 v2

---

DuggaSys/sectioned.js

Add a option "0 tab + end" with "end" css.

Add a option for tab

---

install/SQL/testingCourseData.sql
install/install.php

For testing: 
1.Re-install LenaSYS by running install.php
2. Make sure that the checkbox "include Test-Course" is checked.
3. The test course should appear at courseed.
4. Enter the course.
5. Try to create a new code example choose a prefered template and file. (For example choose the sql file)

Create tests on the lenasys website #11402

---

DuggaSys/codeviewer.php
DuggaSys/courseed.js
DuggaSys/courseed.php
DuggaSys/darkmodeToggle.js
DuggaSys/sectioned.php
Shared/css/blackTheme.css
Shared/css/style.css
Shared/css/whiteTheme.css
Shared/navheader.php

Now there is a toggle/icon in the main header. The next step is to implement the function, so when you click dark or light mode is activated.

Added a toggle icon in main header

---

DuggaSys/codeviewer.php
DuggaSys/courseed.js
DuggaSys/courseed.php
DuggaSys/darkmodeToggle.js
DuggaSys/sectioned.php
Shared/css/blackTheme.css
Shared/css/style.css
Shared/css/whiteTheme.css
Shared/loginbox.php
Shared/navheader.php

The pull requests #11781 and #11733 was having conflicts in `blackTheme.css`and `courseed.css`, but was resolved in this merge.

Test merged two branches to ressovle a conflict

---

DuggaSys/diagram.js

While marking inside the ER-diagram only the rectangle with solid lines can be seen, and after letting the mousbutton go the dashed selectionbox appears.

Changed functionality for selectionbox

---

DuggaSys/diagram.js

Attributes connected to a entity or relation are now blocked from being connected to another entity or relation in diagram.js in the functions addLine and onSetup.
During testing: This issue solves blocking connections between attributes to entities or relations, not the chain of connection that can be created according to er rules between attributes.
A new issue will be created to solve rules of connection between attributes, from attribute to attribute and block connections in that chain to a relation or entity.

Attribute lines to entities and/or relations Issue #11688

---

DuggaSys/contribution.js
DuggaSys/contributionservice.php
Shared/css/style.css
Shared/dugga.js
Shared/loginbox.php

Added more ajaxservices for user-check/creation in dugga.js
Added more to contribution.js to handle gui and some front end checks of input values and calls to ajax
Added more services to contributionservice.php for user creation/checks
please see following comment for related issue for more information: https://github.com/HGustavs/LenaSYS/issues/11416#issuecomment-1109822395

Completed more of issue #11416 as a continuation of previous pull #11700. Should solve #11418

---

DuggaSys/diagram.js

Moved the position of the delete buton and made it bigger. #11387
3) Click or box select any element/s
4) Click cross icon in the right upper corner of the selection box and the elements selected should get deleted

Delete button resized and repositioned

---

DuggaSys/diagram.js

Error checking for ER diagrams, errors will be outlined in red. #11600
Note: testing requires knowledge in ER diagrams.
3) Change the diagram to test all problems listed below:
1. Wrong line type, **correct**:  single line for strong entities and double line for weak entities
2. Wrong key type, **correct**: strong key for stong entities and weak key for weak entities
3. More or less than one key 
4. More or less than 2 lines to entities from a relation
5. Attributes with same name on the same entity
6. No cardinality set (Cardinality is the "N" or "1" situated on a line from an entity to a relation)
7. Wrong relation type, **correct**: weak relation must have a line to a weak entity and strong relation must have …

Error checking for ER diagrams

---

DuggaSys/diagram.js

Issue #11795 Rules according to ER diagram and element connections is implemented.
Test connection between attributes and attributes, attributes to entities and attributes to relations. Test so blockings works for these attributes when they are connected.

G1 2022 w4 #11795

---

DuggaSys/diagram.css
DuggaSys/diagram.js
DuggaSys/diagram.php

Related to issue #11763  and #11610 
I have updated the options panel to change the content, depending on the selected elements and also added the ability to place UML inheritance. The button for inheritance is found in the expandable toolbar for relations:
Things that could be tested for UML inheritance:
- Create, move and delete inheritance element (also test with "x" in corner of selection)
- Using box-selection to mark elements
- Move with "Snap to Grid" enabled
- Connect with lines to different elements
- Check if possible to connect two inheritance elements together
- Verify that it is not possible to adjust the size of the element (no blue boxes)
- Change the type of inheritance (found in the options panel, in a dropdown)
- Check that is not possible to change the color of the …

Implemented UML inheritance and updated options panel

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

Reverts HGustavs/LenaSYS#11796

Revert "Dropdown boxes are now hidden when selected dugga is not diagram #11614"

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

Reverts HGustavs/LenaSYS#11865

Revert "Revert "Dropdown boxes are now hidden when selected dugga is not diagram #11614""

---

DuggaSys/codeviewer.js

Made default value unselectable in file drop-downs.

Made default value unselectable

---

DuggaSys/contribution.js

Adjusted functionality on user select button according to the wish in the issue

G3 2022 w4 #11825

---

DuggaSys/contribution.js
DuggaSys/contribution.php
DuggaSys/contributionservice.php

The sidebar for accepting users is no longer made in the contribution.php file. Instead the sidebar is made in contribution.js. Now when a guest visits contribution.php the sidebar will not be shown. After a user has loged in if they are a superuser the sidebar will be made and shown.
The sidebar still needs to exists in contribution.php but it will just be an empty hidden div untill the function in contribution.js is called. 
Contribution.php login
Contribution.php as Toddler

Made the sidebar only show for superusers

---

DuggaSys/diagram.js

Reverts HGustavs/LenaSYS#11862

Revert "Fixed selection colors issue #11396"

---

DuggaSys/diagram.js

Reverts HGustavs/LenaSYS#11867

Revert "Revert "Fixed selection colors issue #11396""

---

DuggaSys/contribution.js

Please pull @a20behta the gui script

Added the GUI javascript

---

DuggaSys/contribution.js

Reverts HGustavs/LenaSYS#11880
merge to master not

Revert "Added the GUI javascript"

---

DuggaSys/contributionservice.php
Shared/dugga.js
Shared/resetpw.php

Fixed the login backend for contribution, good luck @a20behta

G3 2022 w5 #11872 fixed login backend

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Holy poop emoji is back! "Operation shitstorm is a success!!"- @b19karhj

Holy poop emoji is back!

---

DuggaSys/diagram.js

Updated selected colors for marked elements, now works for UML elements and relation,
weak elements and relations and multi values attributes.
Color should only be set when more than one element is selected.

Updated Selected colors for UML and Weak Entities #11396

---

DuggaSys/diagram.js

clicking anywhere after opening the selection box closes it.
test by opening a selection box an clicking somewhere. clicking the selections should select.

improvement for toolbar for selecting ER/UML

---

DuggaSys/diagram.js

added so the label follows the line even when far from center.
test by creating a label and moving it from the center and then moving the line.
https://user-images.githubusercontent.com/81320323/165773067-8bc5b344-e549-494d-8c78-1deea2487dd3.mp4

added so the label follows the line even when far from center for issue #11155

---

DuggaSys/diagram.js

To test:
-There should be only one save-button in the options panel

Removed duplicate of save-button in option panel

---

DuggaSys/showDugga.php

Literally just that.
A picture of the button that does nothing.

Added a button without function in dugga viewer

---

.gitignore

Removed traces of the illegal database file and cleaned up .gitignore

G3 2022 w5 #11943

---

DuggaSys/diagram.php
DuggaSys/showDugga.php
Shared/dugga.js

Readded code that got lost in merge.
Added extra documentation.
Also added support so diagram dugga works.
This can be tested by doing changes and trying to leave a dugga page.
Should also test diagram dugga.
#11928

G3 2022 w5 #11928

---

DuggaSys/contribution.js
Shared/css/style.css

Removed the static width for the contrib element in order to reduce the wasted space in the contribution table. Also fixed the broken string and moved the <a> tag to the correct place. See issue https://github.com/HGustavs/LenaSYS/issues/11912 for additional context.

Proposed implementation

---

DuggaSys/contribution.js
DuggaSys/contributionservice.php
Shared/SQL/init_db.sql

The new git_user table has been implemented in the install sql so it will be created if you run it again
SSN has been scrubbed from the files and is no longer handled
previous functions are changed to work with the new git_user table
-------Testing-----------------
run the install files and see if a new table is created called git_user following the following format 
Can be tested by using the login on contribution.php and try to create a user that exists on the git data and see if that user is created on the git_user table with an account status of 101
It shouldnt be able to login with the contribution page as of now due to the login not being adapted to the new table, awaiting a new issue to implement that

Finished issue #11896

---

DuggaSys/fileed.js
install/courses/2/helloWorld.html

To test this you need to go on to the fileed.php and try to open a html file. All I did was move a comparison from one if statement to another. 
It used to look like this:
Now it should look like this:

Modified fileed so that html type files uses other function

---

DuggaSys/courseed.js

Added a margin botton in curseed.js LINE 417.

Added style margin-top

---

DuggaSys/diagram.js

Stored the parent attribute and removed it from the attribute list.
#11916
look at the table.

removed parent attribute #11916

---

DuggaSys/diagram.js

The options panel has been updated. The look of the textarea is bad, it will be updated in upcoming issues.
Current look:
Also weak keys are underlined. Added a new storage for entities and attributes.

Underline keys attributes #11909

---

DuggaSys/contribution.js
Shared/css/style.css

Changed buttons for selection of year and course according to discussions at half time seminar

Fixed buttons for year and course selection

---

DuggaSys/sectioned.js

This does solve the problem where the sub-boxes did not get checked when pressing the section box. 
To test this you need to a course and try to mark the section box. 
https://user-images.githubusercontent.com/80856978/166443507-f141009c-b688-4492-986a-0b76730711da.mp4

Added some code that goes trough the array and checks the correct boxes

---

DuggaSys/contribution.js

Added titles for the buttons at the top of contribution.php to give more context to what the button does when a user hovers over them. If the description is not good enough feel free to change the text.
What the buttons actually changes is which group is displayed and which is hidden. (not very user friendly names)
- All - shows group1, group2, group3
- Basic - shows group1 - hides group2, group3
- Charts - shows group2 - hides group1, group3
- Contribution - shows group3 - hides group1, group2

Added descriptive text to buttons

---

DuggaSys/contribution.js

Fixed the typo leftover in the button creation from previous issue and fixed the problem with the merge conflict.
previous issue typo correction: https://github.com/HGustavs/LenaSYS/pull/12078
previous issue merge conflict with: https://github.com/HGustavs/LenaSYS/pull/11940

Fixed missing changes

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/fileed.js
DuggaSys/fileed.php
DuggaSys/resulted.js
DuggaSys/resulted.php

The code below added to resulted, fileed, and duggaed .php/.js

There is no "Back to top" - button on pages other than main course pages #12051

---

DuggaSys/diagram.js

When multiple objects are selected they get a dark violet color. To make the text more readable the font color is changed to white, from black.

Selected objects get white text. Issue #11986.

---

Shared/css/blackTheme.css
Shared/css/whiteTheme.css

Added a black background on icon "tabs icon".

Fixed black background to match with dark mode

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

I implemented a button so if you accidentally delete an example you get 60 seconds to regret the action.

Undo button if accidental deletion of an example #11960

---

DuggaSys/codeviewer.js

You should now be able to resize the boxes in template 7.
For testing:
1: Create a new code example.
2: Once inside it, set the codeexample to template 7 (the 7th from the left.)
3: resizing should work for the boxes now.

Resizing boxes in template 7 implemented.

---

DuggaSys/sectioned.php

Changed "New Quote" to "New message"

Changed "New Quote" to "New message"

---

DuggaSys/accessed.php
DuggaSys/duggaed.php
DuggaSys/fileed.php
DuggaSys/resulted.php
Shared/SortableTableLibrary/sortableTable.js
Shared/css/blackTheme.css
Shared/css/style.css
Shared/css/whiteTheme.css
Shared/navheader.php

Added dark mode in in 4 different files.
- resulted.php
- duggaed.php
- fileed.php
- accessed.php

Added dark mode in in 4 different files.

---

DuggaSys/codeviewer.js

Reszing the boxes in template 6 is now possible.
For testing:
1: Create a new code example.
2: set its template to template 6. (the 6th from the left)
3: You should be able to resize the boxes.

Resizing boxes in template 6.

---

DuggaSys/codeviewerService.php

fixed the Issue in codeviewerService.php where an fatal error occurs and was ignored for some reason.

Fixed fatal error #12014

---

DuggaSys/sectioned.js

I needed to change the code a bit, there was a syntax error.

Added purple color background to the checkboxes.

---

DuggaSys/sectioned.php

change the padding value, make cancel button on the same line with save button.

Cancel Button position

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

Made it possible to have invalid deadlines once again, corrected startdate and enddate when fetched rom database and used hours and minutes when creating the deadline.

Fixed Absolute deadlines #11224

---

Shared/css/style.css

Semi finished. Icon is enlarged but margin should be fixed but to continue #11978 needs to be fixed first.

Home icon #11929

---

DuggaSys/courseed.js

Deleted white background when pressing the gear icon

Deleted white background

---

DuggaSys/sectioned.js
Shared/css/blackTheme.css
Shared/css/whiteTheme.css

Change the ID of the icon. The other icons are black from the beginning, while the new one is white. Needed to add ID in whiteTheme.css and blackThem.css to make the button in the opposite color.

Changed the icon ID

---

DuggaSys/courseed.js

Added target _blank to github link

Add target _blank to github link

---

DuggaSys/sectioned.php
Shared/css/blackTheme.css

Also fixed a bug in sectioned.php file, beyond the issue.

Added white text.

---

DuggaSys/diagram.js
DuggaSys/templates/diagram_dugga.js

changed displacement distance.

Fix for issue #11973 The distance the label gets displaced from the line is incorrect

---

DuggaSys/codeviewer.js

The buttons now Function with the gridview.
For testing: 
1: get the burgermenu to show up by going into a mobile view or resizing the window enough while inside the codeviewer.
2: click the burgermenu and click all the boxes.
3: There should be no white space on the page.
4: Clicking show all will return everything to normal.

Updated the Burgermeny button for gridview.

---

DuggaSys/diagram.js

changed the snapping distance for easier to select the line in the middle.
#11981
https://user-images.githubusercontent.com/81320323/166203848-1ad8f4b1-c2ec-4d38-a5fb-e6e227e1ab94.mp4

fix for issue #11981 The snap is to sensitive for label displacements

---

sh/index.php

Implemented the following requirements:
1. The prevention of creating multiple SH URLs linked to the same course or assignment.
2. Making SH links invalid when the course and/or assignment name has no resemblance with the SH parameters.
3. Deleting or changing id for courses and assignments should update SH links according to requirements.

SH URL complete implementation #11512

---

DuggaSys/contribution.js
DuggaSys/contributionservice.php

@a20behta @c20adael I used ORDER BY in the queries to make it possible to move the queries out of the for loop. The code runs significantly faster as a result.
before changes on the HGustav page.
after changes on the HGustav page.
Please note that I am using a mutated database so load times are longer than they would be with the normal database.
To test that it work's just open my branch on your machine and compare it to the branch for merge 5.

G3 2022 w5 #00001 five times faster load speed on the file contributionservice.php 

---

DuggaSys/sectioned.php

…ent relative which prints the title when hovering over the element

Displays a description of the dropdown menus and of relative when you hover over them

---

DuggaSys/codeviewerService.php
Shared/navheader.php

G2 2022 w5 #12115

---

DuggaSys/sectioned.js

Fixed the incorrect behavior of the checkboxes. The code was in the wrong place.

Fixed bug caused by weekly merge

---

DuggaSys/codeviewer.js

Trying to merge all older commits from issue branch G2-2022-W5#11428 into the new issue branch G2-2022-W6-#11428.

merge old issue branch (W5) into new issue branch (W6)

---

Shared/navheader.php

...except for 1 pixel around the image. I have no idea why.
To test:
1. Go to the demo course page.
2. Attempt to click the return button outside of the image area. The button should not activate (except within 1 pixel)
3. Click the return button. It should work as intended.

Fixed the return button interactive area

---

DuggaSys/contribution.php
Shared/navheader.php

The bar has been added however three new issues are needed because three features don't work. I don't think I am ideal for any of them. Rather they should be given to the people who made the features in question.
1. Dark mode does nothing.
2. Message of the day does nothing.
3. The account request pane covers some of the left navbar and some of the user account button. You can still use the user account button but it looks ugly
.

added navbar to contribution page

---

Shared/navheader.php

Fixed the incorrect navheader. now it looks the same as it did before the issue.
How it looked like before the issue:
How it looks after the fix:
The inline-block caused the empty space and the changes to the if statement fixed the problem with having two bars

Fixed the navheader issue

---

Shared/css/style.css

Added a 50px margin to the top in order to get the elements to not overlap with each other

Fixed the overlaping navbar and sidebar

---

DuggaSys/diagram.js
DuggaSys/diagram.php

There are two videos in the issue that clearly outlines the problem. Do as in the videos and notice a different outcome.

Behaviour of selection box in different scenarios #12180

---

DuggaSys/accessed.php
DuggaSys/courseed.js
DuggaSys/duggaed.php
DuggaSys/sectioned.php
Shared/css/style.css

Changed the class to that it can be applied on multiple pages to form a uniform result. 
To test this: 
Visually check the yellow button on all of the following pages: duggaed, accessed, courseed and sectioned.
If any pages that aren't uniform are found please document these.

Fixed the placement of the FAB button

---

DuggaSys/showDuggaservice.php

Added the duggatitles for superusers. Previously the variable was only assigned if the user was a guest.

Added dugga title for superusers

---

DuggaSys/contribution.js
DuggaSys/contribution.php

Issue with scrolling solved and I also fixed the sizing of the diagrams to be the same when zoomed in.

Issue with scrolling in commit tree and weakly bar chart fixed #12086

---

DuggaSys/contribution.js
DuggaSys/contributionservice.php

both backend and frontend will check using regex and 2 size more or equal 8 and less than or equal 64
note: only done for creating account. not checking. 
testing frontend: 
change to branch on webserver  
be logged out and go to to http://project- 
g3.webug.his.se/DuggaSys/contribution.php
try a password less than 8 characters 
try a password more than 64 characters
try a password with special characters. 
testing Backend
comment out else if statement in contribution.js
line 2323 - 2335
try a password less than 8 characters 
try a password more than 64 characters
try a password with special characters.

Solved validation for username and password on contribution.php #12218

---

DuggaSys/fileed.js
DuggaSys/fileedservice.php
DuggaSys/filereceive.php
DuggaSys/templates/feedback_dugga.js

Uploading a single or multiple files to edit files should where there already is a file with the same filename and filetype should no longer be possible.
Test:
Go into edit files.
Upload  file/files with the same filename and same filetype: Alert should be displayed.
Upload file/files with same filename but different file type: Alert should not be displayed and file should be uploaded.

File with same name and filetype will not be uploaded  #11993

---

DuggaSys/diagram.js

Made it so when closing the options panel the arrow wont disappear. #12244 
3) Close the options panel (if there is an arrow, it is correct).

Arrow does not disappear

---

DuggaSys/contribution.js
Shared/css/style.css

To test this you need to go to the contribution page. Then you need to select a person from the database. After that you need to scoll down to the circle diagram and test its functionallity. 
BE AWARE: Some of the elements will be blocked behind other elements. This is intentional as of now.

Modified the circle diagram to that multiple polygons are shown with the different types

---

DuggaSys/contribution.js

Fixed the issue and tested the site.

Fixed the error with mismatching '}'

---

Shared/navheader.php

Changed the function called by the onclick in  contribution navheader logout button.
#12267

Contribution Logout Button Now Uses git_logout()

---

Shared/css/style.css

Added filter to all the icons with id "dorf" to make them white. The "link icon" will be changed in another branch where and since the styling was moved to a new file.

made the icons white on the purple background

---

Shared/css/blackTheme.css

changed the dark colour #242729 to #303030 and #2d3133 to #343434.
Testing:
Go to course webprogrammering.
1. before switching to branch the background color of the rows should look something like this:
2. after switching to the branch it should look something like this:

changed the colours of rows of the code examples

---

DuggaSys/codeviewer.js
DuggaSys/codeviewer.php
Shared/css/blackTheme.css
Shared/css/style.css
Shared/css/whiteTheme.css

"Edit file" windowis inherits functionality from loginbox window, allowing the window to be closed by clicking ESC or clicking outside of the window.
Testing:
3) Open PHP Example 1
4) Click on "Edit file"
5) Close the popup window by clicking outside of the window form, and also by clicking escape
6) This should work for both darkmode and lightmode

"Edit file" window behaves as a popup window #12292

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

Removed alert and added text to the delete item dialog box

Removed alert and added text 

---

Shared/css/whiteTheme.css

Added style for the link icon

---

DuggaSys/codeviewer.js

Showing and hiding collapsed code is now done recursively to support nested brackets and html tags.
Testing:
2) Enter Demo-Course
3) Create a new code dugga
4) Select a template, Kind: Code Wordlist: JS
5) Click edit file and Add new Global file, upload codeviewer.js from your LenaSYS directory
6) Click the edit cogwheel and select File codeviewer.js (because codeviewer.js has almost 5000 lines of code, it will take some time to load the code example)
7) Try closing and opening nested brackets
Expected behaviour:
https://user-images.githubusercontent.com/102609651/167128279-5f252db3-fc07-4c0f-95e1-e70583c8c343.mp4

Added support for nested collapsible tags #11428

---

DuggaSys/codeviewer.js

Made the burger menu box function like other window boxes, for example the settings window and login box.

The burger menu now behaves like other windows #12173

---

DuggaSys/darkmodeToggle.js

Removed unnecessary console log

Removed unnecessary console log

---

DuggaSys/codeviewer.js
Shared/css/style.css

Reimplemented resize functionality to template 8.
For testing:
1: Create a new code example.
2: Enter it.
3: select the 8th template.(8 from the left.(3boxes))
4: Resize the boxes to see if it works.

Template 8 resizing should now work.

---

install/SQL/testingCourseData.sql
install/courses/global/PHP-TEST1.php
install/install.php

Added code examples for each template to simplify testing of codeviewer. Inside each example the description of each box also shows the boxid.
For testing:
1. Reinstall LenaSYS, make sure to clear the database and include the testing course.
2. Navigate to "Testing-Course".
3. The course should now contain 40 examples.

Create tests on the lenasys website

---

Shared/css/style.css
Shared/css/whiteTheme.css

Added margin to whiteTheme for the content

Added margin to whiteTheme

---

DuggaSys/codeviewer.js

This was not included in the week 5 bracnh due to a missed label.
For testing:
1: Create a new code example.
2: Enter the code example.
3: Set its template to template 4(the 4th one from the left.)
4: Resizing should now function properly

Added resize functionality to template 4.

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Ruler fixed and aligned and screen different will be a deal breaker for the zoom between 0.5 and 0.25 otherwise works well! got some help from Jonathan.

fixed the dashes to a consistent style issue #12039

---

DuggaSys/contribution.js

This will make them differ from each other so that all of the rectangles are able to use its hover function. same goes for the polygons. 
This can be tested by going to the contribution page and selecting a username. then scroll down to the circle diagram and view the difference.

i have modified the baseline of the different polygons

---

DuggaSys/contribution_loginbox.js
DuggaSys/contribution_loginbox_service.php

matched the regex for both php and js files. 
reinstall lenasys (Lenasys/install/install.php)
once done try creating a user (Eg proci) with a password containing åäö.
it should result in a warning popping up

changed regex to match eachother and use same syntax

---

DuggaSys/showDugga.php
DuggaSys/templates/diagram_dugga.js

Reverts HGustavs/LenaSYS#12450
Something happend along the way, worked during the earlier testing.

Revert "User no longer gets prompted to press OK multiple times when opening dugga"

---

DuggaSys/contribution_loginbox.js
DuggaSys/contribution_loginbox.php

Removed the forgot passsword option. Not 100% sure if this is what the issue actually requested or if the request was to implement the functionality in some otherway. After discussing with a20vicad we decided to remove it and if someone thinks otherwise we can revert this change.

Removed forgot password option from login

---

DuggaSys/sectioned.js

creating new issues and headers no longer gives them buttons they are not supposed to have.

New Sections and Headers nolonger have extra btns

---

Shared/css/style.css

Add Padding value to make the search bar looks more comfortable.
1. Login as teacher and go in Webbprogrammering.
2. Click the Button show file at navbar.
3. Confirm the distance between the search bar and the back button.

Add padding left value

---

Shared/loginbox.php

For testing:
1. Click on the login button
2. the "Sign in" text is gone

Removed the "Sign in" text

---

Shared/css/blackTheme.css

Removed the opacity and changed the color to HEX

Changed color to HEX 

---

DuggaSys/sectioned.php

Changed margin-right on undo button

Changed margin on undo button

---

DuggaSys/courseed.js
DuggaSys/courseedservice.php
DuggaSys/sectioned.js
Shared/css/style.css

This tempmerge is a combined project from @a20caros , @a20novra and @c20adael. What has been done is that there is highlighting when you create any type of test or dugga/heading/test on a course site.
Also highlighting has been added to the front page so that when you update a course or create a new one it will show witch one it is. 
How to test: Go to any course and create something from the fabbtn and check if it gets highlighted red.

Temp merge highlighting

---

DuggaSys/contribution_loginbox.js

Added calls to displayalertText that also remove the text after a set time
----------Testing--------------------
Please see if it matches up with the video in the comment https://github.com/HGustavs/LenaSYS/issues/12380#issuecomment-1125410409 and for different users

Solved the issue of "try again" text remaining

---

DuggaSys/filereceive_dugga.php
DuggaSys/showDuggaservice.php
install/SQL/demoCourseData.sql

Fixed the issue of text files being saved as json. Also changed the location of new submissions from htdocs/submissions to duggasys/submissions.
Updated demo-course sql to use unique hash and password.
Made it possible to view all submissions when logged in as superuser if none was selected.
Creating submission as guest - Generic Dugga File Receive
https://user-images.githubusercontent.com/102533453/168076917-144991e8-afbd-4244-9023-c132778eb3d3.mp4
Viewing all submissions as SuperUser - Generic Dugga File Receive
Viewing specific submission as SuperUser - Generic Dugga File Receive
https://user-images.githubusercontent.com/102533453/168076929-fc854632-947f-4192-aa3c-38dd88d28d51.mp4
Viewing all submission as SuperUser - Rapport inlämning

Fixed generic_dugga_file_receive for superusers.

---

DuggaSys/contribution.js
DuggaSys/contribution_loginbox_service.php
DuggaSys/contributionservice.php
Shared/dugga.js

account status now loads in the created accounts and int for status. 
testing:
create a account through contribution (proci or HGustavs or a97marbr) 
log in as teacher. 
check sidebar and see the created accounts there and their status being shown

G3 2022 w7 #12407

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

added a function to sectioned.js to check if user is inlogged. there is an if sats that show the buttons if user is inlogged.

added a function to sectioned.js to check if user is inlogged

---

DuggaSys/filereceive_dugga.php
DuggaSys/showdoc.php

Added missing character to filepath. Also fixed a incorrect if statement which might have caused the files to be saved as json on the web-server but txt on the localhost. Video of how to test the changes
Text viewer
https://user-images.githubusercontent.com/102533453/168278369-1ff94a44-7cb6-4464-8884-dc9377a46c28.mp4
Text download
https://user-images.githubusercontent.com/102533453/168278377-a1e4355f-5767-4778-9010-7c727bbd51d2.mp4

Fixed the text file being unreadable

---

Shared/navheader.php

Add // to the code show announcement button
1. Login as teacher.
2. Go into any course.
3. Check the announcement button do not show at navbar.

Cancel announcement button

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

Added a confirm show items dialog box

Added a confirm show items dialog box

---

Shared/css/style.css

Made the "Link" icon white on the purple background.

Change the "Link" icon to white.

---

DuggaSys/diagram.js

Made a white background for the cardinality (1, N) on lines. #12470 
3) Look at the cardinality (1, N) and see if there is a white background that hides the line its on

White background behind cardinality

---

DuggaSys/courseed.js
DuggaSys/courseed.php
DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/sectioned.js
DuggaSys/sectioned.php
Shared/css/style.css

#11558
Updated Forms found in
duggaed.js/php (edit dugga)
setioned.js/php (Edit Course Version, New Course Version, Tillgängliga Duggor, dugga settings)
courseed.js/php (Edit Course, New Course, Edit Server Settings)
The forms should be looking more consistent, there should also be more error checking which disables submitting.

G1 2022 w7 #11558: Save functionality dugga edit isn't consistent.

---

DuggaSys/contribution.js
DuggaSys/contributionservice.php
Shared/dugga.js

related to #12518 
Frontend buttons added. currentl only do a console log print. 
each button appears based on current status of the account. 
code 101 =  pending
code 102 =  denied
code 0 = accepted. 
testing: 
1) create a account in contributino (proci and HGustavs work)
2) logg in as teacher
3) press side bar. 
4) open inspecter and press console
5) press one of the buttons. note the console log which appears. 
6) change column _status_account_ in database manually (mysql, phpmyadmin etc)
7) refresh and notice that sidebar looks different.

Frontend buttonds for accepting, denying, deleting account.

---

DuggaSys/contribution.js

Standard state is now 'closed' for all tabs until changed

G3 2022 w7 #11946

---

DuggaSys/sectioned.js

This can be tested by going to the sectioned page and pressing the cogwheel. Then modify the name and press the save button. DO NOT press enter to save because there is something wrong with that save method.

Added highlighting to edited elements on the sectioned site.

---

DuggaSys/sectioned.js
Shared/dugga.js

COMMENT out an unnecessary callning. Som changes in dugga.js to click on cog wheel image when someone klick on enter btn.

Did cog whell clickable #12522

---

DuggaSys/codeviewer.js
Shared/css/blackTheme.css
Shared/css/codeviewer.css
Shared/css/style.css

Fixed problem with the resetButton in mobileview when touch the element

Fixed problem with the resetButton in mobileview 

---

DuggaSys/contribution.php
DuggaSys/contribution_loginbox.js
DuggaSys/contribution_loginbox.php

Removed some uneccesary code i had wrote earlier in another pull, added new function to return you to courseed.php
---------------Testing-----
Press X see if you return to courseed.php

Exiting the login window in contribution now only returns you to courseed.php

---

DuggaSys/resulted.php
Shared/css/style.css

Changed the css for resulted so you do not have to scroll sideways in mobile view.

Adapted resulted to mobileview #12526

---

DuggaSys/sectioned.php

The buttons are now in the order as the groupleader had requested. i did this by changing the positions of some code blocks for the buttons. it took a while because they were wierdly placed

The buttons are now in order

---

DuggaSys/diagram.js

Create an Entity of UML type and remove all attributes/functions, and notice that there is no weird behaviour anymore.

UML-entity unchanged when removing attributes/functions. Issue #12537.

---

Shared/css/codeviewer.css

Change the height to make the number is aligned to code.
1. Go into a example at course Webbprogramming.
2. Check the code is aligned to the number.

Change the height

---

Shared/css/blackTheme.css
Shared/css/style.css
Shared/icons/link-icon.svg

Changed color of link icon to purple

Changed color of link icon to purple

---

Shared/navheader.php

Add ontouchstart and ontouchend function for beforebutton and afterbutton at navbar.
1.  Go into an example at course Webbprogrammering.
2. Make sure you are at mobil view.
3. Touch the beforebutton and afterbutton 0.3s, the dropdown will show

Make function available at mobil

---

Shared/navheader.php

Delete the tag <a> for Home button. Add tag <a> id to tag <div>.  The removed tag doesn't appear to affect  button's function.
1. Go into any course.
2. Click the Home icon button, test the function.

Delete unnecessary tag

---

DuggaSys/sectioned.js
Shared/css/blackTheme.css
Shared/css/style.css

Fixed styling of newTabLink in both whitemode and darkmode

Fixed styling of newTabLink

---

Shared/css/blackTheme.css

BlackTheme.css should now have no mentions whatsoever of anything to do with the Position, Widht, Height, Margins, Paddings, top,left,right,bottom.
Since it is only concerned with the color of the Page.
For testing:
1: Navigate through lenasys.
2: Constantly switch between dark and light mode.
3: No element should change position at all.(Meaning that blackTheme.css does not change the position of anything.)

Removed any changes to positioning of elements i BlackTheme

---

Shared/css/blackTheme.css
Shared/css/codeviewer.css
Shared/css/colorblind.css
Shared/css/style.css

Made important rows impossible to select

Made important rows impossible to select

---

DuggaSys/showDugga.php
DuggaSys/templates/diagram_dugga.html

Reverts HGustavs/LenaSYS#12521
Do not work after merge, it does not fold in and the arrow for manual handle is gone. Same type of arrow that can be seen in the top of this image. But this arrow should be in the side that is gone.

Revert ""General information" and/or "Instructions" only show if a file is available #12476"

---

Shared/icons/angelBrackets.svg

created an icon for the new functionality, refer to #12095 and #12424.
This should be merged into #12095 or tested after #12095. 
To test: the icon should look like this <>

Created an icon for the new angle-brackets functionality

---

DuggaSys/showDugga.php
DuggaSys/templates/clipping_masking_dugga.html
DuggaSys/templates/clipping_masking_dugga.js
DuggaSys/templates/curve-dugga.js
DuggaSys/templates/daily-minutes.js
DuggaSys/templates/dugga3.html
Shared/css/blackTheme.css
Shared/css/dugga.css
Shared/css/style.css

Here are the first Dugga exemples that have dark mode in them: 
3D dugga, BIT- dugga, Box modell, Clipping Maskin Dugga, Curve Dugga, Daily Minutes, Dugga 3 .

Added dark mode in some "Dugga examples" on Demo-Course. Part 1.

---

DuggaSys/sectioned.js

All items in sectioned should now be draggable if the user has write access. tabs on items should be visible.
Testing:
3) Create all item types, give random tabs to the items, drag items in random orders ("Moment" cannot have tabs)
User with write access:
User without write access:

Darggable areas and tabs should work as expected #12566

---

DuggaSys/codeviewer.js
Shared/css/style.css

Added press effect on copy button in mobile view

Added press effect on copy button in mobile view 

---

install/CSS/install_style.css
install/install_light.php

Added GUI for install script

---

DuggaSys/sectioned.js

Added the new icons to the tabbable list in order to make sure they are disabled when a menu is open.

Added new icons to tabbable list

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/sectioned.js

How to test the first place
1. login as subuser
2. choose demo course
3. click on this button and add a new item 
4. Tab to this button on the new added item and press enter
5. Press enter again 
If it works the choosed ithem should delete
How to test the second place
1. login as subuser
2. choose demo course
3. Choose show tests
4. Click on the yellow fabbtn and edit a dugga 
5. Tab to this button on the new added item and press enter
6. Press enter again
If it works the choosed ithem should delete

Keypress functions that listen for the enter press to save

---

DuggaSys/diagram.js

Reverts HGustavs/LenaSYS#12619
Do not work, functionality gone when merged and merge conflict resolved as developer instructed.

Revert "Replaced line blocking with errors"

---

DuggaSys/diagram.js

Reverts HGustavs/LenaSYS#12627

Revert "Revert "Replaced line blocking with errors""

---

DuggaSys/courseedservice.php
DuggaSys/sectioned.js
DuggaSys/sectioned.php

Reverts HGustavs/LenaSYS#12586

Revert "Implemented relative deadline"

---

DuggaSys/sectioned.js

removed image tag #12655

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Reset will now work when no diagram is set in variant

Diagram: If no diagram file is not set, the reset button does not reset to default state #12705

---

sh/index.php

removed &embed attribute from redirect link

Made it so loading diagram from hash doesn't remove nav-bar

---

DuggaSys/diagram.js

#12546
Enter:ing not will not save in textarea

G1-2022-w8-#12546: UML-Entities saves everytime a function/attribute is added to their lists.

---

DuggaSys/duggaed.js

If nothing is selected in variant. Note-box is cleared

Notes is not cleared when deselecting row #12644 

---

DuggaSys/diagram.js

Attribute on relation no longer results in error. #12633 
3) Click "Toggle error check"
4) Observe if attributes on relations are outlined in red

Attribute on relation no longer results in error

---

DuggaSys/showDuggaservice.php
DuggaSys/templates/boxmodell.js
DuggaSys/templates/clipping_masking_dugga.js
DuggaSys/templates/color-dugga.js
DuggaSys/templates/dugga4.js
DuggaSys/templates/html_css_dugga.js
DuggaSys/templates/html_css_dugga_light.js
DuggaSys/templates/placeholder_dugga.js
DuggaSys/templates/shapes-dugga.js
DuggaSys/templates/transforms-dugga.js
install/SQL/demoCourseData.sql

Fixed the problem of displayDuggaStatus not being reached due to various factors such as errors caused by syntax or missing variables. Removed placeholder values for param in demoCourseData and instead added real parameters.
_! Need to run install.php in order to test all the changes !_
This title somewhat works for placeholder dugga very briefly but a function makes it go away right after it appears (no clue why they made it like that). 
Before code changes
https://user-images.githubusercontent.com/102533453/169065508-3ee07437-3e30-4529-808a-614c4a78e525.mp4
After code changes
https://user-images.githubusercontent.com/102533453/169065522-bbda9c8d-74e3-445b-ab34-b9baf04f6028.mp4
Edit: the off center issue is already fixed in merge8 i just don't have it on this branch

Fixed displayDuggaStatus not being reachable 

---

Shared/navheader.php

How to test:
1. Login as a student 
2. Choose a course
3. Change to mobile view
4. The issue is sovled if the navburger menu is located in the menu

Generates the navburgermenu when you inlogged as student

---

DuggaSys/codeviewer.js
DuggaSys/codeviewer.php

How to test
1. Choose webprogrammering course
2. Choose mobile view 
3. Click on a dugga
4. Do you see the back button in the menu? if you do, the issue will work

Show the back icon in a dugga when you are in mobile mode

---

DuggaSys/templates/svg-dugga.html
DuggaSys/templates/svg-dugga.js
Shared/css/style.css
install/SQL/demoCourseData.sql

Created the new SVG dugga to look like the one in the mockup, also added some things to the backend in order to have a foundation to work on. Most of the javascript and html is a combination of parts from the other duggas and the code in https://github.com/HGustavs/SVG-Demo
! Don't forget to run install.php before testing.
Landing page view
It is possible to create svg objects by writing code in the right side editor
Dropdown menu to select a different object
This is just a backbone that can be used to build out the functionality further. One of the things missing is save and load functionality, as of now every object in the dropdown is coded into the javascript file and it is not possible to save the object.

Created new SVG dugga

---

Shared/css/blackTheme.css

Needed to add new color on two "color" variables: --color-text-primary and --color-primary-2.

Changed color from purple to gray

---

DuggaSys/templates/XMLAPI_report1.html
DuggaSys/templates/seminar_dugga.html
Shared/css/blackTheme.css

Only removed inline styling in a div element and created a new class and put it in blackTheme.css.

Added dark mode color on XMLAPI Report" & "Seminar Dugga".

---

DuggaSys/templates/transforms-dugga.html
DuggaSys/templates/transforms-dugga.js
Shared/css/blackTheme.css

Added CSS to blackTheme.css for "Transform dugga". This was done to match with dark mode.
A class needed to be created to fix the style in Transform dugga.

Added dark mode color on "Transform dugga".

---

Shared/css/blackTheme.css

For testing:
1. Switch between dark and light mode and check that the purpple color is not the same

Fixed the primary color in ddark mode

---

DuggaSys/sectioned.php
Shared/css/style.css

Changed position of undo button

Changed position of undo button

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

Fixed so the undo delete example button works again.
Also fixed the position of the button  so it sticks to the + ghost and eye buttons.

Made the undo delete button work again. #12578

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php
Shared/css/style.css

Clicking the bottom right plus icon will increase the number of items to be created, when an item type is clicked. Default number of items to be created is 1.
Testing:
2) Enter Demo-Course
3) Click on the plus sign icon in the bottom right 7 times
4) Create a new code example with the bottom right button.
5) 8 new code examples should be created and console output should say:
6) Create a new test dugga
7) only one new test dugga should be created and output should say:

Added possibility to create multiple items at the same time #12673

---

Shared/css/style.css

For testing:
1. Use a mobile phone
2. Login as a teacher
3. Go into a code example
4. Press the edit button 
5. Go into landscape mode

Fixed so that editing in mobile view works

---

Shared/css/blackTheme.css

Added CSS to blackTheme.css for Dugga "HTML CSS Dugga"". This was done to match with dark mode.

Added dark mode color in Dugga "HTML CSS Dugga"

---

DuggaSys/accessed.js
DuggaSys/accessed.php
DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/fileed.js
DuggaSys/fileed.php
DuggaSys/resulted.js
DuggaSys/resulted.php

Fixed navIcons when the screen has a max-width of 380px

Fixed navIcons when the screen has a max-width of 380px

---

Shared/css/style.css

For testing:
1. Go into webbprogrammering course
2. Log in as a teacher
3. Hover over  button, you should be able to click links

changed pixels to a lower value

---

DuggaSys/templates/clipping_masking_dugga.html
DuggaSys/templates/dugga4.html
DuggaSys/templates/dugga4.js
Shared/css/blackTheme.css

Changed to dark mode colors in Dugga 4 and Dugga 5.

Added dark mode in some "Dugga examples" on Demo-Course. Part 2 

---

Shared/css/blackTheme.css
Shared/css/style.css

Reverts HGustavs/LenaSYS#12657
One of the buttons didnt follow along.

Revert "Fixed colors of icons in both lightmode and darkmode"

---

DuggaSys/contribution.js
Shared/dugga.js

How to test:
1. Login as superuser
2. Go to contribution page
3. Tab on every table on the side and check if the table sorts
If you can tab and sort every table head on the contribution page the issue is solved

Tab and sort function on every table in the contribution page

---

DuggaSys/templates/diagram_dugga.js

Outer reset button now have confirm and also clear localstorage

Diagram: Add confrim and localstorage clear to orginal reset button in lower left corner.

---

DuggaSys/templates/diagram_dugga.js

Reverts HGustavs/LenaSYS#12721
Controlling lost functionality in other parts of the diagram that do not has to do with this issue.

Revert "Diagram: Add confrim and localstorage clear to orginal reset button in lower left corner."

---

DuggaSys/duggaedservice.php

Reverts HGustavs/LenaSYS#12663
Testing lost functionality

Revert "It's now possible to delete variants with assigned user answers #12638"

---

DuggaSys/templates/diagram_dugga.js

Reverts HGustavs/LenaSYS#12794
This did not affect the problem we searched for.

Revert "Revert "Diagram: Add confrim and localstorage clear to orginal reset button in lower left corner.""

---

DuggaSys/duggaedservice.php

Reverts HGustavs/LenaSYS#12796

Revert "Revert "It's now possible to delete variants with assigned user answers #12638""

---

Shared/css/blackTheme.css

For testing:
1. Go into darkmode in the homepage and check that the icon is changed

Added a dark mode vairant to icon

---

Shared/dugga.js
Shared/loginbox.php

Added login warning that login is only avalible from course page.
For testing: 
1. Do not be logged in
2. Enter course Webbprogrammering 
3. Press the top right
4. A new link is now visible in the login window.
5. Pressing the new link takes user to the main page.

Added log in warning

---

DuggaSys/duggaed.php
Shared/css/blackTheme.css

Created a new class to change the background color to dark mode in some fieldset elements in the file duggaed.php

Added dark mode color in "Show Test" editor.

---

install/install_light.php

For testing:
1. Go into this link: [localhost]/LenaSYS/install/install_light.php
2. The title should now be `Light LenaSYS Installer` and the password should be hashed

added header and password is now hashed

---

DuggaSys/diagram.js

Related to #11766 
Note, review this only if #12810 fails.
What has been changed:
- Updated how the lines are drawn. UML elements use a special kind of line (polyline) that uses only straight line segments. 
What can be tested:
- Test by using the line tool on UML elements (class or inheritance). The ghost of the line should not be a single diagonal line, instead it should be a line consisting of three line segments.
- Test by using the line tool on ER elements (entity, relation, attribute). The ghost of the line should be a diagonal line (as before)
- Test to connect a UML class to an UML class. The new type of line should be used, similiar to the picture:
- Test selecting the new UML lines, it should work by clicking any of its three line segments. Also check if the selection box …

Updated the line tool to use line segments (polyline) for UML elements

---

DuggaSys/diagram.js

The coordinates for UML Entities used in the function entityIsOverlapping are now correct. #12602 
3) Create a UML Entity
4) Drag other elements to see if the hitbox on the UML Entity is correct

Fixed overlapping for UML Entities

---

DuggaSys/contribution_loginbox.js
DuggaSys/contribution_loginbox.php
Shared/navheader.php

I finished so you get a logout popup when you try to logout from contribution
it also now recognizes git_users as logged in on the contribution page so you should be able to for example see the username "proci" in top right corner if hes logged in.
-------------- Testing --------------
Make sure you can see both teachers and users in the top right corner when they are logged in and that they both get the logout popup when they try to logout
! important ! make sure to force reload/clear your cache as chrome seems very insistent on trying to use old versions if it can

Finished issue #12596 that is handling both git_users and teachers logout and recognizing login on contribution

---

DuggaSys/duggaed.js

Test:
Go to show test, click the pen on diagram dugga. Check if update/disable/enable buttons are disabled.
Click one of the cogweheels for a diagram, check if disabled or enable are disabled depending on the status.
Click update or enable / or disable.
the buttons should show as disabled again.

 Diagram: Variant: Disable, update and enable, #12710 

---

DuggaSys/duggaed.js

Reverts HGustavs/LenaSYS#12744
Disables the pen button, when pressing the pen it wont open the submenu. Important functionality that existed earlier dissapears with this issue.

Revert " Diagram: Variant: Disable, update and enable, #12710 "

---

DuggaSys/duggaed.js

Reverts HGustavs/LenaSYS#12844
Seems like the problem comes from another merge from another group. Adds back this pull request.

Revert "Revert " Diagram: Variant: Disable, update and enable, #12710 ""

---

DuggaSys/diagram.js

Primary keys are recognized and there can be more than one candidate key. #12724
3) Change a candidate key to a primary key (possible to have candidate keys togheter with one primary key)
4) Create 2 candidate keys on the same entity

Primary keys are recognized

---

Shared/css/blackTheme.css

For testing:
1. Go into any course
2. Check that the yellow color is changed in dark mode

Added darkmode variant for yellow color

---

DuggaSys/codeviewer.js

Add closeBurgerMenu() into the resize function
1. Go into an example have Burger Menu.
2. Inspect
3. Click Burger Menu, change window size， see the burger menu disappear or not? (should disappear)

Add function to close burgerMenu

---

Shared/css/style.css
Shared/navheader.php

Increased the size to match the other icons in the navbar.
And made the button not visible in mobile view.

Increased size on button and made it non visible in mobile view

---

Shared/css/style.css

Aligned input elements in dialog boxes

Aligned input elements in dialog boxes

---

DuggaSys/diagram.js

Non-normal attribute on a attribute now results in error. #12748 
3) Create elements on an attribute as shown in the picture in the issue description.

Non-normal attribute on a attribute

---

DuggaSys/diagram.js

ER entities converted to UML now get the right properties. #12780 
3) Create a ER Entity and then change its type to UML
4) Observe if it gets "-attribute" and "+function"

ER entities converted to UML right properties

---

DuggaSys/courseed.js
Shared/dugga.js

How to test:
1. Try to tab to the cogwheel on the home page, can you tab to them and clicked enter and get´s the same result than you usual click on the cogwheel the issue is solved
Make that on both the heading cogwheel and tha courses cogwheel! It should work on the both place

Added tab function on the cogwheel on the home page

---

DuggaSys/duggaedservice.php

When deleting undeletable things in duggaed it now promts an error.

Added error promt if query fails

---

Shared/css/style.css

Changed static css color values to ones used in root.
Should be tested usin versiontesting (ask group leader how it's done).

style.css continued changing from static css colors to ones in root

---

Shared/css/style.css

Changed static css color values to ones used in root.
SHould be tested usin versio testing (ask group leader how it's done).

style.css from static color values to root

---

DuggaSys/diagram.css

Css bug fix issue with width.
Now works

 Diagram: bug fix css #12862 

---

DuggaSys/templates/diagram_dugga.html
Shared/css/blackTheme.css
Shared/css/style.css

For testing:
1. Go into a diagram dugga
2. Check that the description field is changing in dark mode

Dark mode variant added to diaggam

---

Shared/css/blackTheme.css

Changed the background to darker so that it would fit in dark mode. Then you can see the text.

Changed the background to darker

---

Shared/css/style.css

I moved the search icon to the right place by using Padding-right

Moved the search icon to the right place

---

DuggaSys/showDugga.php
Shared/css/blackTheme.css

The background has a darker background.

Change the background in "Diagram_Dugga"

---

DuggaSys/contribution.js
DuggaSys/contribution_loginbox_service.php
Shared/css/style.css

Test by add and change status of users

G3 2022 w8 #12554

---

DuggaSys/resulted.js

The error was caused by the setNameColumn function call which is to a function which was removed last year. I also fixed so that the table could sort both ascending and descending which it couldn't do previously.
Best course to test the changes is [Webbutveckling - datorgrafik](http://project-g3.webug.his.se/DuggaSys/resulted.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732)

Fixed sorting table in resulted.php

---

DuggaSys/contribution.js
DuggaSys/contribution.php
DuggaSys/contributionservice.php
Shared/css/style.css

Displays all files from contribution database into contributino file. 
displayed based on procent of blame usage. 
testing. 
go to contribution
logg in and pick a user.
scroll down and watch chaos. 
NOTE
functionality not completed and needs some more work.  
specifically placing them correctly according to issue

G3 2022 w8 #12467

---

Shared/css/blackTheme.css

This is a fix after another issue

Change the text color

---

DuggaSys/contribution.js
Shared/css/blackTheme.css

Added CSS to blackTheme.css for "Account Request Table". This was done to match with dark mode.

Added color for "Account Request Table".

---

DuggaSys/diagram.css
DuggaSys/templates/diagram_dugga.html

Fixed css issues that was not noticed "gone" in todays test.

 Diagram icons needs update #12872 

---

Hello World

Issue #12895

---

Hello World

Hello raman

---

hejwordskdad.txt
helloWorldg2.txt

learned how to make a pull request

G2 2023 test

---

test.php

test.php now displays text correctly

fix test.php

---

hello.txt

gjort en textfil som heter något i stil med hej.txt

---

JpsTestFile.txt

a new document was created, and contains the nicest message ever.
the issue is resolved

a new document was created

---

Hello World

Updated HelloWorld

---

Shared/navheader.php

Now the text "login" shows in the upper right corner showcasing that the login-button actually exists :)

Added text 'login' so loginbutton is visible

---

DuggaSys/diagram.js

Added onchange="changeLineProperties"  to both select dropdowns. This will call the changeLineProperties() function whenever an icon is selected.

Improve aggression, composition, optionality and cardinality at the end of lines. Issue #12954

---

DuggaSys/diagram.js

Solved issue #13013, where colors wouldn't be saved properly due to an empty array of ids being passed to the _save()_ function.

Colors not saved properly #13013

---

DuggaSys/diagram.php

Commented out code that was not used in diagram.php line 649 so that it can be used in the future.

G1 2023 v0 #12999

---

DuggaSys/courseed.js
DuggaSys/courseed.php
Shared/navheader.php

G3 2023 v0 -> Main branch

---

DuggaSys/templates/diagram_dugga.html

Removed inline styling from assignment_discrb aswell as added padding in diagram dugga. Fixed issue number #12884.

Removed inline styling and added padding. Issue #12884

---

DuggaSys/diagram.js
Shared/css/blackTheme.css

Added classes where the lines where created and then added some css code inte the blackTheme.css to change the lines when its dark mode.

G1 2023 v1 #13051

---

DuggaSys/courseed.php

Test if "Read Only" is visible in darkmode while logged in: DuggaSys/courseed.php

g3-2023-v1-issue#13106

---

Shared/markdown.js

issue #13024 ready to be tested and merged @a21rammo

try to switch $2 and $1

---

backend-models/microservices/profileservice_microservices.txt

added text document for microservices relevant to the file profileservice.php

added profileservice_microservices.txt

---

backend-models/microservices/fileedservice_microservices.txt
backend-models/microservices/fileedservice_provided_services.txt

issue#13095 Investigate potential microservices in fileedservice.php
is ready to be reviewed

G2 2023 v1 issue#13095

---

DuggaSys/courseed.js
DuggaSys/courseed.php

Added a inputfield to add a github link for already created courses

edit course with Github link

---

DuggaSys/diagram.js
Shared/css/blackTheme.css
Shared/css/style.css

Triangle icons changes colors depending on the current theme, making it easier to see. Solves issue #13061.

Triangle is now styled properly for darkmode/lightmode #13061

---

Shared/SortableTableLibrary/sortableTable.js

Before, sorting by date affected the order of duggor even if all duggor had null as dates. Now duggor will not be affected by the sorting if all values are null, and works correctly with dates. (Click "show tests" in navbar in demo-course)

Edit dugga now sorts correctly

---

Shared/css/style.css

Test hover on cogwheel in light mode: DuggaSys/courseed.php

g3-2023-v1-issue#13073

---

recursivetesting/recursivejs.js
recursivetesting/recursivephp.php

What we've done is fetch the api-link for a specific github repo to retrieve the data in JSON-format with fetch (await fetch(url)), afterwards we run a modified breadth first traversal to go through the data including sub-folders of the original data. The out-commented code below console.log(files) is a previously used algorithm to further dive into the data and structure them into individual arrays, but it's in need of refactoring to fit into the current fully functioning version of the fetch with analysis.
Uploaded to the webserver on my (a21olljo) folder. When testing check the console for output
Done w/ @e21krida

Recursively calling a github repo

---

backend-models/microservices/diagramservice_microservices.txt

finished work on potential microservices in diagramservice.php  issue#13093

G2 2023 v1 issue#13093v2

---

backend-models/microservices/contribution_loginbox_service_microservices.php.txt

Added contribution_loginbox_service_microservices.php.txt

---

DuggaSys/diagram.js
DuggaSys/diagram.php

found an inconsistency in getVariantParam where some of the php variables that were pushed into the array were surrounded by '' while others weren't. This caused the code to be parsed in a way that made the browser think UNK wasn't just a placeholder string but an actual variable name that was, of course, undefined.

 You have to zoom in to see the diagram once diagram.php is loaded #13150

---

backend-models/microservices/codeviewerService_microservices.txt

a lot of different elements, summarized at the top under microservices.

added codeviewerService_microservices.php

---

backend-models/microservices/resultedservice_microservices.txt

Hopefully the task is understood. Comments added based on microservices that might be able to be separated.

added resultedservice_microservices.txt

---

backend-models/microservices/duggaedservice_microservice.txt

Added file containing descriptions and potential microservices

Added duggaed_microservice.txt

---

Shared/css/blackTheme.css

Changed styling of system message when the user is in darkmode. Solves issue #13126

System messages are barely visible in darkmode #13126

---

DuggaSys/diagram.js

Changed  the style on the div when it creates, and changed the height of the svg. Now when you create the inheritance it should spawn on the mouse

G1 2023 v1 #13083

---

DuggaSys/diagram.js

added some margin-top to the div encapsulating the UML inheritence element

 UML inheritance appears slightly above where it should #13124 

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/templates/diagram_dugga.js

Commented out the code that generated the predrawn diagram, in both dugga diagram and in diagram.php

G1 2023 v1 #13080

---

DuggaSys/darkmodeToggle.js

added a default theme. If the localstorage item themeBlack is null; it becomes style.css (lightmode)

Make sure localstorage for theme never is null #13177

---

DuggaSys/courseed.js
DuggaSys/courseed.php

Test the validation for both the new course and edit course. You should not be able to create/edit the course unless all input fields are valid. Leaving the field for the github URL empty also counts as it being valid, since it's optional.
Invalid
Valid
Also valid
( Co-creator @g21emmka )

G3 2023 v1 issue#13137

---

Shared/css/blackTheme.css

Added styling to the pop-up in blackTheme.css

G3 2023 v1 issue#13163 popup blending in with background

---

DuggaSys/diagram.js

Changed how the _entityIsOverlapping()_ function works, updated the function-call throughout diagram.js  and changed where system-error messages for collision are generated. Solves issue #13219

Overlapping elements when creating #13219

---

Shared/css/blackTheme.css

Note: the issue-branch is named v1 despite being branched from the v2 branch, this is a simple typo and should be no cause for alarm.

Change fill color of uml-icon triangle in dark-mode

---

DuggaSys/sectioned.js

issue #13220 created 2 diffrent github icons with 2 diffrent titles to clarify that there will be diffrent uses for them in the future.

G3 2023 v2 13220 change GitHub button on course page

---

DuggaSys/diagram.js
Shared/css/blackTheme.css
Shared/css/style.css

Cardinality labels on lines are now white on a black background in darkmode as they should instead of black on white background like in lightmode.

G1 2023 v2 #13203 cardinalities in dark-mode

---

DuggaSys/diagram.js
Shared/css/blackTheme.css

G1 2023 v2 #13282

---

DuggaSys/diagram.js

Identified that the issue only occurs when no elements are placed on the canvas. 
Added a check that stops the function from executing if no elements are placed

G1 2023 v2 #13290

---

Shared/css/style.css

Moved dropdown and changed color while in markdown preview in "fileed.php".

Fixed dropdown issue #13286

---

DuggaSys/courseed.js
DuggaSys/courseed.php
DuggaSys/courseedservice.php
Shared/basic.php

Fixed so that the github url is inserted into the database when creating or editing course. 
Test this by creating a new course and see if the github url is visibile in the database column, also check if the url changes when you insert a different url in editing course. 
( Co-author @c21rebja )

G3 2023 v2 issue#13222

---

backend-models/functional-requirements/FRD accessedservice.md

Remade accessedservice.php.pdf to a md file
Left the pdf file in, was unsure if to delete it or keep it

Create FRD accessedservice.md

---

DuggaSys/diagram.js
Shared/css/blackTheme.css

Changed css for the black triangel, had the same as the normal one

G1 2023 v2 #13300

---

recursivetesting/FetchGithubRepo.php

I've added a basic insertion into the recently created sqlite database "metadata2.db", what i insert is the information regarding each file that is parsed through the "FetchGithubRepo.php" script in the form of Name, URL, File Type, Download URL, SHA & Path. This branch was created before the branch where the database was created through the issue #13256, therefore for testing purposes either run it via a21hugni's branch or test individually with this file and an updated G3-2023-V2.  
Future issues regarding specifying what files to parse and to avoid duplicates for SHA will be necessary.
Relevant files: /recursivetesting/FetchGithubRepo.php & ../githubMetadata/metadata2.db

G3 2023 v2 issue#13254 - "Connect the fetchted data to the Database"

---

DuggaSys/diagram.js

Added zoomfact to the end arrow, the arrow did not have zoomfact and thats why it was not working as intended

G1 2023 v2 #13308

---

functionalRequirementsContributionservice[1590].txt

Created a txt file with functional requirements, testing possibility and description of the code.

ContributionService Functional requirements #13235

---

DuggaSys/diagram.css

Added css so that the user can select the area.

G1 2023 v2 #13321

---

backend-models/functional-requirements/FRD showDuggaservice.md

Replacement for FRD_showDUGGAservice.php.PDF

Create FRD showDuggaservice.md

---

backend-models/functional-requirements/courseedservice_functionalrequirments.md
backend-models/functional-requirements/courseedservice_functionalrequirments.txt

G2 2023 v2 issue #13236 courseedservice.php functional requirements

---

DuggaSys/diagram.js
DuggaSys/diagram.php

made the needed code changes from issue 13215. the button should  work now and not have any conflicts when you press the state diagram button.

G1 2023 v2 #13215

---

backend-models/functional-requirements/contribution_loginbox_service.php.md

created functional requirements for contribution_loginbox_service.php

created FR contribution_loginbox_service

---

Shared/log.php

The serviceLogEvent outputted unix time instead of datetime.
I solved this by converting unix to datetime in the log.php file.
Before:
After:

G2 2023 v2 issue#13331

---

backend-models/functional-requirements/FRD_resultedservice.md

Created FRD resultedservice.md

Created FRD resultedservice.md

---

DuggaSys/diagram.js

Fixed so the SD State button works(typo), and fixed so that you can change name to the state name and add attributes in the optionpane.

G1 2023 v2 #13283

---

DuggaSys/diagram.js

Solved the problem of overlapping the selected element by removing a continue in the loop for exactly that element. It is no longer possible to place a element under the selected one.

G1 2023 V2 #13345

---

Shared/css/blackTheme.css
Shared/css/style.css
Shared/navheader.php

A button to refresh all the metadata for all the files from github has been created in the navbar and also in the hamburger menu (small screen). There are no functions implemented on this button. 
( Co- creator @c21rebja  )

G3 2023 v2 13346 create a refresh button in the headernavbar to refresh all the metadata for all the files

---

Shared/css/blackTheme.css
Shared/css/style.css

In the edit student results the password block was not blocking the password in dark mode. Now it does

G3 2023 v2 issue#13371

---

Shared/css/style.css

Now the td has a pointer no matter if it has been clicked or not. Indicating that it can be clicked again. 
Click the password columns to test: 
https://cms.webug.se/root/G3/students/a21lukpo/LenaSYS/DuggaSys/resulted.php?courseid=1894&coursename=Demo-Course&coursevers=52432 
Relevant files: /Shared/css/style.css

G3 2023 v2 issue#13372 no hover indicator

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

from issue #13223 added a new "screen" for github interactions

G3-2023-v2-issue#13223-GitHub-screen

---

recursivetesting/FetchGithubRepo.php

We changed the local path that the files are saved in to be dynamic instead of static.
Relevant files recursivetesting/FetchGithubRepo.php
Worked in conjunction with @a21lukpo 
(Had to create new branch since everybody was working on the same file and a whole lot of merge-conflicts appeared otherwise)

G3 2023 v2 issue#13337 v2

---

DuggaSys/diagram.css
DuggaSys/diagram.php
Shared/icons/diagram_IE_entity.svg

Made the corners rounded with css because changing the svg file would also change the ER svg. We are using the same svg file for ER and for the State.

G1 2023 v3 #13389

---

DuggaSys/diagram.js

Fixed issue where you can change type when connected, if its UML and ER and displays a message.

G1 2023 v3 #13390

---

DuggaSys/diagram.php

The button has been added, not much more to it

G1 2023 v3 #13438 test-case generation button

---

DuggaSys/profile.php

Added darkmode to profile.php
Relevant files: profile.php
Link to test (you have to be logged in): https://cms.webug.se/root/G3/students/a21lukpo/LenaSYS/DuggaSys/profile.php
This is for issue #13407

Added darkmode to profile page

---

DuggaSys/diagram.js

It is no longer possible to overlap the SD states when placing or moving them.

Overlapping with SD states is no longer possible. Issue#13381

---

backend-models/service-tests/duggaedservice-tests.txt

issue#13343 is finished, needs to be reviewed. 
I have created a text-file which outlines what is to be tested and what values that are used for said tests.
These values are used among other things for SQL-queries and need to be tested to make sure that all queries behave as intended and that LenaSYS still functions with the added or removed data. To give an idea of what to search for, I experienced a bug where and INSERT made it impossible to edit an added "momen", this was a result of faulty values in the INSERT.
could not open edit

G2 2023 v3 issue#13343 - Write tests for services in duggaedservice

---

Shared/log.php

- I have added sorting functionality for log.php.
- I have added default sorting set on time (timestamp) from descending order.
- If you click on the button "Set to default(timestamp, descending order)", then order and sort will be set on default (default is time in descending order).
- I have added styling so the tables becomes easier to read.
- I have updated the `<th>` tags. They are now clickable links:
- If you click on one of the links (and then select the table in the dropdown again), then the sort variable will switch from ascending to descending or vice versa. Which means that the content is sorted in ascending/descending order.

added sorting to log.php G2 2023 v3 issue#13329

---

DuggaSys/diagram.js

Fixed box-select on the lines with corners, did this by adding the attributes that the box-select looks for, this probably isn't the best way to do it, however it does work.

G1 2023 v3 #13470
