HGustavs/LenaSYS

Shared/SortableTableLibrary/sortableTable.js
The sum/average row was rarely used and often appeared as a blank white row. This is now removed from most tables except those that explicitly set the hasFooter variable to true, such as the result table in contribution. Other tables may need to be updated if they wish to use this feature.
To test:
1. Go to duggaed/resulted/fileed
2. Confirm that the table does not have an empty row on the bottom
3. Go to contribution
4. Confirm that the top-most table (above the weekly bar chart) has a bottom row for average/sum.
Note that the table on the bottom of the contribution page has values summed up on the bottom row, but does not make use of the footer. This was the case before my changes as well and it may need to be updated to be in line with the other tables.
=> Added a check to make sure that only tables with footers will have the sum/average row

DuggaSys/diagram.js
Related to #11766 
Note, if this pull request passes the test, close #12811  since this request also includes the same code. And if this request don't pass the test, try #12811  where only straight lines are implemented.
What has been changed:
- Updated how the lines are drawn. UML elements use a special kind of line (polyline) that uses only straight line segments. 
- Implemented the ability to type/write cardinality on UML lines (at start and at end of line)
- Updated the options panel (generateContexProperties) to remove the ER kinds from UML lines and remove UML cardinality on ER lines.
What can be tested:
- Test by using the line tool on UML elements (class or inheritance). The ghost of the line should not be a single diagonal line, instead it should be a line consisting of three …
=> Straight lines and UML cardinality

DuggaSys/sectioned.js
How to test:
1. Login as superuser
2. Choose demo course
3. Click on this icon
4. Does the tab open in another tab? If it works, the issue is resolved. You can also try to tab to the icon and check if it also open in a new tab, it should work in both way
=> Fixed "open in new tab" error

DuggaSys/diagram.js
If an attribute that's a primary or candidate key has child attributes, they're now printed as one underlined key object
You can test this by having a primary or candidate attribute have child attributes, they should then be printed in the ER table as one key object. And if a primary and candidate exist, the candidate and its child attributes will not be printed at all
=> Child attributes of primary/candidate key are now underlined as one key object

DuggaSys/duggaed.js
Issue #12456 was present again in merge 8, the files weren't loaded into the dropdown box.
Ajax call was only made if the dugga was of diagram type, now its done when opening the variant editor.
=> Instruction and General information files are now visible

DuggaSys/diagram.js
Quick fix (called an old function name (now updated)).
Test : Move element or add element, click the reset icon and after pressing ok, the diagram should now be in default position
=> Diagram: Reset does not work (wrong function name in one place) #12749 

DuggaSys/diagram.js
Added dropdowns to the lines between UML and IE entities/classes where you can select the type of symbol to the end of the line and a radio button to be able to select a dashed line.
#12817 
For testing: 
Create multiple UML or IE entities/classes.
Select the line tool and draw a line between them
select the lina and open options
add cardinalitys and symbols and se if it works
if the entities/classes are to close together the symbol does not look the best
UML should work but IE is not tested
=> Added symbols to end of lines for UML and IE

DuggaSys/diagram.js
- #12851
Lines now draw correctly from IE-inheritance.
How to test:
1. Place an IE-entity on the diagram
2. Place and IE-inheritance on the diagram
3. Draw a line between them, manke sure there isn't any space between the line and entity.
4. The fact that the inheritance turns black when drawing a line between ie-entities will be fixed in another issue.
=> Lines draw correctly from IE-inheritance #12851

DuggaSys/diagram.js
- Added white fill on inheritance symbol so that it doesn't turn black when using line tool.
Add two IE inheritance symbols on canvas + two EI entities.
Change one of the IE inheritance symbols to overlapping.
Then make a line between one entity and the inheritance symbol.
Make the test like this: 
Line connection issue solved in other branch.
=> Fixed that inheritance turned black by mistake when using line tool.

DuggaSys/codeviewer.js, DuggaSys/codeviewerService.php
The dropdown menus in change template are auto filled with current information from boxes in the example.
When changing template new boxes are created in the database and already existing boxes are updated with new data.
Testing:
3) Open JavaScript Example 1
4) Click Choose Template
5) The window should display this:
6) Choose a new template and edit the information to this:
7) Clicking save should update the code example with the new template and infromation:
8) Create a new code example in Webbprogrammering
9) Open the new code example, choosing a template and saving should still work.
=> Fixed template dropdown menus and fixed fatal error #9552

DuggaSys/sectioned.js, DuggaSys/sectionedservice.php
Upon deleting listentries from sectioned listentries will now change the attrubute "visible" to 3(deleted) instead of deleting the row from the database. Functions to retrieve rows with visible 3 is created. This is the groundwork  to enable restoration of deleted items from sectioned.php.
**For testing:**
1. Enter webbprogrammering.
2. Delete a example.
3. Check if the "visible"-attribute has changed from 1 to 3 in the database.
=> Deleted listentries from sectioned will now change the "visibile-attribute" instead of deleting the item. 

DuggaSys/courseedservice.php, DuggaSys/sectioned.js
This mainly fixes how the deadlines is displayed if there's no course start date.
Instead of trying to display a specific date it will display which day, week or month from the course start date.
So it would say "Course week 3, 15:00" if there's no course week.
I also fixed some of my own code, bugfixes with the datepicker and new functions to display everything needed.
I understand that when creating a new course version there is no way of getting around the validation to create a course without a start date. This is, however, made upon request from the original issue thread and acts as a fail-safe in case. We don't want the page to break if this accidentally happens in the future.
I test this myself by going into demo courses, add a new course and then manually delete the course start …
=> Fix relative deadline when there is no course start date

DuggaSys/contribution.js
I have tried testing why it was set up this way. It seams so deliberately done. But I can't figure it out. Everything works if substr(1) is removed. 
to test my change switch to my branch and try to use a issue link in contributions.
=> Suggested changes have been applied and tested.

DuggaSys/diagram.js
- #12855 
How to test:
1. Place two or more disjoint IE-inheritances  (the one with the X in the middle).
2. Select them all
3. Make sure the "X" turns white.
=> The disjoint "X" turns white in IE-inheritance when multiple IE-inheritances are selected #12855

DuggaSys/diagram.js
Changes to a diagram is now saved to localstorage when a user leaves the page. When a user opens a dugga, the diagram from localstorage is retrieved and loaded. Solved issue #12882
=> Store and retrieve diagram from localstorage

DuggaSys/diagram.js
color-changing events have been added into the undo-redo-structure, a single line was missing for this. Beware this interacts with another bug meaning the first two events performed will be undone as one so when testing perform more than two changes and perform color-changes after those first two as well.
=> G1 2023 v0 #12957

Shared/css/blackTheme.css, Shared/dugga.js
Solved why the input field text was black on black background. This fix ruined login form because it had inline css background color white so it was white text on white background. Therefore I commented out the inline css in dugga.js
Issue #13014
=> Darktheme inputs text color and login form background color

DuggaSys/diagram.js
Updated what's saved to the state machine for startIcon for UML lines. There seems to have been a mistake in the code. It erroneously saved the value for startIcon under the name endLabel.
=> Icon selection not saving right 

DuggaSys/diagram.js
Made it so that newType is assigned with optional values. If both "typeSelect" and "propertySelect" are null, newType is instead set to undefined. Solves issue #13116 
Changing color while editing an ER attribute will reset the name and variant to thier default values in the options-pane. Could potentially be an issue.
=> Changing properties on ER-Attribute does not work #13116

DuggaSys/courseed.js, DuggaSys/courseed.php, Shared/css/blackTheme.css, Shared/css/style.css
"Stop it from changing text color when creating a new course #13068"
Changed so that the input boxes turn red using classes instead of just setting the style specifically for that element. This makes it possible to use it on all inputs, no matter which theme is currently active. We tested this on the create course form, but it should work just as well on the others.
=> G3 2023 v1 issue#13068

DuggaSys/diagram.js, DuggaSys/diagram.php, Shared/css/blackTheme.css, Shared/css/style.css
Added a darkmode button for the diagram in diagram dugga which can be accessed in the right sidemenu. Saves background color to local storage. Also possible to toggle darkmode with key "d".
=> Add darkmode switch to diagram.php in right sidemenu. Issue#13067

DuggaSys/diagram.js
The previous author thought that icon could be used in an if case with startIcon/endIcon, this is not the case as there are several edge cases like icon being ZERO_ONE and startIcon / endIcon being 0-1. Or icon being WHITEDIAMOND while startIcon/endIcon are White_Diamond. Or icon being FORCEDONE and start/endicon being 1! 
This complete inconsistency of naming has made this issue very bothersome. The best way i found to solve it was to firstly use toUpperCase() on startIcon/endIcon, this solved certain icons like Arrow or Triangle. But the ones that could not be compared as easily I found it best to give them their own If statements; this does inherently lead to some bad smell and the possibilty for refactoring is massive. I strongly believe that if another issue comes up where the root …
=> Icons not saved in options.

DuggaSys/sectioned.js, Shared/css/blackTheme.css
The input fields are now in the correct color depending on the theme. As seen below.
=> Fixed so the input fields are correct.

DuggaSys/diagram.js, DuggaSys/diagram.php
The button is now there, however it's sometimes there when it would usually be hidden by the system. Selecting it also in some cases doesn't allow you to swap back due to a bug. However all these things are caused by the backend not being implemented yet. Also the icon for a statediagram state is at this point the same as for IE-entity
=> G1 2023 v1 #13074 Add a button in the menu for placing statediagram states.

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagram_IOHandler.js, DuggaSys/diagramservice.php
Moved the backend code in diagram.php to diagramservice.php. Changed some code in diagram_IOHandler.php to adapt to the changes made in these files. Updated diagram.js to fetch diagrams from client-side. Solves issue #13102 
Hard to test as the validateHash.php and showDugga.php both use incorrect links for saving/loading from hash.
- Uses hostname/sh/?s=hash, when it should use hostname/LenaSYS/sh/?s=hash
- This issue will probably not affect the stable build as it uses another root
Also, it seems that the cms.webug.se server cannot find the file diagramservice.php (works locally).
The button for saving (uploading) seems to be broken as it returns an error (diagram_dugga.js).
=> Move database backend from diagram.php #13102

DuggaSys/diagram.js
Refactored the function _checkElementError()_ by dividing it further into more maintainable, traceable functions: _checkEREntityErrors()_, _checkERRealtionErrors()_, _checkERAttributeErrors()_ and _checkLineErrors()_.
=> Refactor checkElementError() #13151

Shared/markdown.js
You can now add an image to a md file with %%% image url, thumbnail size, full size %%%.
Can test it on my server version: https://cms.webug.se/root/G3/students/b21leowa/LenaSYS/DuggaSys/courseed.php
This pull request will also fix issue  #13082.
=> Fixed so you can add picture into the markdown file.

Shared/css/blackTheme.css
When you toggle ER-table (can be accessed through key "E") on an ER element the text appears as white when in darkmode.
=> Made text white for ER-table when in darkmode, Issue#13257

DuggaSys/diagramservice.php
Checked diagram.php if there are function that can be moved to diagramservices.php but one was to fetch the data from diagram services and the other to get the error message. In diagramservices i added and error handler where it was missing. By using getMessage(); which returns the description of the error.
=> added an error catch

DuggaSys/diagram.js
Added class 'text' to IE and UML parts that have a stroke color that can possibly be toggled and made the borders change as soon as dark mode is toggled in the diagram.
=> Change entity outline depending on colour and mode. #13211

DuggaSys/diagram.js
Fixed an issue where reverting changes (ctrl+z) while creating an edge causing the app to break. Fixed by clearing/resetting ghost element and line.  Solves issue #13202
=> Reverting while creating edge #13202

DuggaSys/diagram.js
created a new line type: UML_STATE and gave it its own set of icons, called SDLineIcons. This set of icons contains one icon called ARROW which uses the SVG from UML black triangle. Then I implemented this new line type and made it so that any line between two UML_STATES gets this type. I also modified the options panel for state lines to account for the new line type and its icons, so that the drop down for icon selection is correct.
=>  Lines between states should be possible to label #13081 

Shared/basic.php
Modified the database to make repoSHA  unique to avoid duplicated inserts.
Check in server cmd by using "cd /var/www/html/root/G3/students/e21krida/githubMetadata" then "sqlite3 metadata2.db" and finally "select repoName from gitRepos ;"
Now there should only be one repo with the files instead of multiple repos with the same files
=> Made repo unique in database

DuggaSys/diagram.js
Before this issue clicking the button for placing SD states would break the system, after this issue the system will not break in this case, however it still breaks if you attempt to place an SD state. Meaning you can select said button and then select another without it breaking as long as you do not click in the diagram area
=> g1-2023-v2-#13357 Add SD to togglePlacementType()

DuggaSys/courseed.js
Issue #13281 
Removed the ".git" part from the regex on the git input fields. Test this by entering for example "https://github.com/HGustavs/Webbprogrammering-Examples" into the input field on both create and edit course. 
( Co-creator @c21rebja )
=> Deleted .git from regex

DuggaSys/diagram.js
Changed the if statement checking from and to elem that then assigns the correct type to no longer check UML_STATE but instead check SD.
=>  Correct line type for state #13406 

DuggaSys/diagram.css, DuggaSys/diagram.php
Options menu looks the same when selecting an element to change properties. Removed absolute positioning/ style: auto and added margin: auto in diagram.css.
=> Fixed styling/positioning for options menu. Issue#13369

DuggaSys/diagram.js
It was not just lightmode, the corers were rounded in a way that cut off the borders no matter the theme. I fixed this by first removing the CSS border radius since that would never have worked and then i replaced the svg <rect> with a path that had arcs on the appropriate corners. I chose this over rx on the rects because these are two rects on top of eachother which would mean 8 corners are rounded when it really should only look like 4. I guess I could've used a clip for rx but path seems better and more proper.
=>  State entity outline should be fixed for lightmode #13366 

DuggaSys/diagram.js
All of the moving entities get reset when overlapping and they don't get reset because they overlap the original position of a moving entity
=> Problems when moving multiple entities (with box selection) when some entities are overlapping #13353

Shared/basic.php
Issue #13414 
Added another table in the SQL lite database, containing the columns githubURL and commitID.
This can be seen in basic.php and in CMD:
- Enter students/"studentid"/githubMetadata
- Write sqlite3 metadata2.db
- Write .schema
The tables should show up.
(co-creator @g21emmka)
=> G3 2023 V3 13414 Create column/table in SQLLite for commit/link

DuggaSys/diagram.css, DuggaSys/diagram.js, DuggaSys/diagram.php
Moved Zoom-buttons out of the toolbar to the canvas.
The buttons are now placed bottom right and moves with the options panel.
The placement is also updated when the user enters "Replay mode"
=> G1 2023 v3 #13423

DuggaSys/diagram.js
Drawing a line between two state entities should now show a arrow on the end of the line
The arrow is also set when the line is created
It is still possible to remove or add additional arrows on the line once it is created, if this behaviour is unwanted this could potentially be raised as a new issue.
=> G1 2023 v3 #13442

DuggaSys/diagram.js, DuggaSys/diagram.php
The button to toggle now behaves like the button for ER-tables. Clicking one also untoggles the other for simplicity of use. 
However this does mean that this implementation suffers from a bug present with the ER-table. If one of the two toggles are set before clicking an entity, no information will be shown in the options-tab and selecting an entity will not show anything except the standard buttons for import, export, etc.. To see any information such as the entities name and attributes both toggles must be off, at which point the standard options are displayed, before they can be toggled again to show either the ER-table or the testcases. This is probably due to some fault in the display-logic in the function "generateContextProperties" in diagram.js and should be an issue on it's own. …
=> G1 2023 v3 #13446

DuggaSys/courseed.js, recursivetesting/FetchGithubRepo.php
The script fetchGitHubRepo.php now sends http-error codes and error messages that can be dealt and showcased by the frontend (which will be done in issue #13410 ). To test if this works, you need to intenionally break the code by setting the variable "$json" to false and test that error message, and then setting the variable "$data" to false and test that error message. These will be showcased in an alert when creating a course with a github-url or editing a course with a github-url. When no error occurs, the console.log in the "success"-part of the ajax-query in the file courseed.js should be fired and should put a response in the console.
Me and b21leowa have tested both these faults on the webserver since we need to push faulty code to the webserver in order to test and it seems to be …
=> G3 2023 v3 issue#13411

DuggaSys/diagram.js
removed the function after making sure it had no references, calls, implementations or mentions.
=>  data_returned function in diagram.js is never used. #13493 

DuggaSys/diagram.js, DuggaSys/diagram.php
Added correct alt to all img in the menu, this makes navigation with a screen reader possible. Also added aria-hidden="true" to the legends on the menu since these legends just make navigating a menu like this one with a screen reader harder. 
There are still many accessibility problems on this site; including but not limited to: the options panel being readable even when its  supposed to be hidden, the drop downs in the menu not being accessible via a keyboard and also all tool tips not being available on keyboard focus but only on mouse over (direct violation of ARIA). These are major issues for accessibility but they are sadly not covered by the issue I was assigned.
=>  Accessibility for buttons in the buttons-menu to the left need optimization #13495 

DuggaSys/diagram.js
removed get lines since its only purpose was returning a readily available, global, variable and it was only called once in the whole codebase. I changed the code where it was called to just use the global variable "lines" and then removed the, now unused, function.
=>  Investigate getlines ToDo comment in diagram.js #13497 

DuggaSys/diagram.js
There was a style-tag and a few missing classes that prevented the automated systems from kicking in when the color of an entity was set to black. That has now been fixed
=> G1 2023 v3 #13518 darkmode black entity

Shared/basic.php, recursivetesting/FetchGithubRepo.php, recursivetesting/getLatestCommit.php
For issue https://github.com/HGustavs/LenaSYS/issues/13542
This will fix the issue with fetchGithubRepo.php to now be connected to the new SQLite db version and its new columns. 
The downloaded files will now be located under cid = 1 and under the folder Github. 
Since we now are running the fetch and download when creating a new course we are now hardcoding the courseid (cid) to be 1, but for testing purpose this is now ok. This will need to be changed when we dissconnect the fetch from the create new course button and connect it to the refreshbutton on the course page/moment on a course page we can then implement a solution to not hardcode cid to be 1 and instead used the correct cid for the course.
=> G3 2023 v3 fix queries for new db

DuggaSys/diagram.js
I've copied Philip's function that he made in issue #13539 to UML and IE entities. Since these entities are left-aligned instead of centered I've given it some more room before folding because I thought it looked incorrect otherwise.
=> G1 2023 v4 #13562 text-breaks in entites

DuggaSys/courseed.js, DuggaSys/courseed.php
The actual error message that appears to the left of the input-field is the first child element of "messageElement", the previous developer of the error message for a course code already in use had implemented the error message as innerHTML of "messageElement", not of "messageElement.firstChild". This meant that the error message didn't disappear after the value of the input-field had been corrected and simply emptying the innerHTML would cause child nodes to be removed as well, wreaking havoc on the rest of the code. I have corrected this by applying the error message to "messageElement.firstChild". 
I have not been able to locate if this solution affects anything else after rigorous bug-testing. 
I also took the time to position the error message "more" in line with respective …
=> G3 2023 v4 issue#13621

DuggaSys/diagram.js
Made it so that you can overlap any element with a superstate, thereby making it so that you can place any element withing a super state. **Note** that I did not manage to implement so that states can be spawned inside the superstate directly since the selection box got in the way and I couldn't figure out a way around this, but I did make it so that you can spawn states elsewhere, normally, and then simply drag them into the superstate.
=>  Unable to place other elements within the superstate #13627 

DuggaSys/diagram.css
After consulting with the group leader, as can be seen in #13643 , I removed the border.
=>  ZOOM buttons borders are visible in both light and darkmode* #13643 

DuggaSys/diagram.js
removed the console log("Moving Obejct") when there is no display that show that you are moving an object
=> Remove consolelog #13657

DuggaSys/diagram.css
Tooltips for zoom are no longer partially hidden underneath the ruler. Solves #13641
=> Tooltip partially hidden #13641

DuggaSys/diagram.js
Removed the diagramToScreenPosition function in diagram.js due to not being used, but keept screenToDiagramCoordinates due to it being used a bit in digram.js.
=> G1 2023 v5 #13722

DuggaSys/diagram.js
Fixed typo which made certain elements' mouse mode undefined. It is now possible to place elements with thier corresponding keybind. Changed keybind to UML-final state from ctrl + < to f.
=> Fix keybinding functionality for UML-final state #13702

DuggaSys/diagram.js, DuggaSys/diagram.php
commented out function getVariantParam(); and another function that is connected to it, they are not in use anymore because they were used before when the diagram was hard coded.
=> G1 2023 v5 #13736

DuggaSys/diagram.js
fixed so that the output now looks better and unlabled lines are printed as unlabeled. Also the strange changes that were there yesterday are no longer there.
=>  fixed the output of diagram.js for state line labels. 

Shared/test.php
Realized that passed/failed was missing from JSON output. Result was respons in callService(). Now respons is in "respons" and result is marked as either "passed" or "failed".
=> Added passed/failed text

DuggaSys/diagram.js
following the given names for the params for sortvectors, which sortElementAssociations calls. I figured currentElementID and compareElementID were suitable variable names instead of 'a' and 'b'
=>  Replace variable names a and b for function sortElementAssociations #13786 

DuggaSys/diagram.js
The save function for sd lines was a copy of the endIcon save, but not all endIcon mentions were replaced with innerType or lineType. innerType and lineType was also a bit mixed upp.
=> Fixed so that lines save properly

DuggaSys/fileed.js, DuggaSys/fileed.php, DuggaSys/fileedservice.php, Shared/css/style.css
Added a new column to the file editor. There should now be a column that is called "Type".  The data inside should be either "Manual" or "Github". This is decided by the method used when adding files. If you manually upload files the type is "Manual" and if you upload a course from github the files added should have the type "Github". We also added 2 radio buttons that will be used to filter files (they are not working currently, will fix the filtering in future issue).
Relevant files to test: fileed.php
Co-authored by @e21krida and @a21hugni
=> G3 2023 v5 issue#13732

DuggaSys/diagram.js, DuggaSys/diagram.php
Added activation element for sequence diagram. Can be created by clicking the button in the toolbar. 
Is missing the "snap" functionality where an element should snap to the middle of the timeline, however one can place an activation element on top of a timeline.
Solves issue #13728
=> Activation element for sequence diagrams #13728

DuggaSys/courseed.js, DuggaSys/sectioned.js, Shared/navheader.php, recursivetesting/FetchGithubRepo.php, recursivetesting/getLatestCommit.php
issue #13668 
"The bfs and fetchgithubrepo.php functions has been redesigned and the functions has been implemented under the refresh button on the navigation meny at the top.
The bfs function now look at an option parameter to be able to download and insert to sqlite or just insert to sqlite. We also changed so that when creating a new course all the files from the repo are not created on the webserver, the metadata from the files are added to the sqlite db. We tested that the files can be created with the DOWNLOAD parameter and it works.
The refresh button in the navbar is set to the REFRESH parameter to fetch the metadata from the githubrepo only if there has been a new commit to the repo."
To test this, create a course with a github repo you can edit (preferrably your own). After …
=> G3 2023 v5 issue#13668

DuggaSys/diagram.js
The old recursive line had two problems: the first was that only the first out of the four created lines would be inside the highlight box. I solved this by adding a 5th transparent line that covers all other 4 lines diagonally, when you select a recursive line the 5th line and everything it cover will be inside the highlight box.
When a recursive line was created it was seen as a successful line creation and therefor proceeded with the rest of the line creation code, which resulted in a straight line being created between entity 1 and entity 2 which in this case is the same entity. I fixed that problem by moving the recursive line creation down to the straight line creation.
=> improved recursive sd lines

DuggaSys/diagram.js
Fixed issue with  y-offset that is currently blocking the implementation of issue #13689
The lines now ends closer to the edge of the elements when the line type is straight
=> G1 2023 v5 #13810

DuggaSys/diagram.js
It is now possible to switch types with enter and the save button with the options-pane acting accordning to the switch. 
An another note:
The type-changing is not 100% accurate and desirable yet (Because UML classes cant count lines for some reason). This makes it so that it is possible to change from UML - UML to UML - ER, between relations
Image below shows that the system seems to think there are 0 lines connected to the UML element:
=> ER to UML, UML to ER options panel dropdown issue #12694

DuggaSys/diagram.js
It is no longer possible to add and render labels to IE lines as they will be ignored. Solves issue #12860
=> Prevent label and cardinalities on IE lines #12860

DuggaSys/diagram.js
Calling isDarkMode in drawElement and using that to change just the text for actor. This is not a perfect solution but it does solve this issue.
=>  Text without whitebackground remains black in darkmode #13869 

DuggaSys/fileed.js, DuggaSys/fileedservice.php
Fixed the previous issue that @a21hugni couldn't solve, what i did was essentially feed the filePath into the json object for both "trashcan" and "editor" objects as well and used the filePath to determine if the path correctly contained the word "Github", hence marking it as a file originating from Github. If it is a github file i simply emptied the column containing the pen to edit and replaced the trashcan with an octopus-emoji as requested. 
Edit: Changed octopus-emoji to github-icon, as i found it's already saved on the webserver. Was unsure about the rights regarding the icon, but if it's already in use i assume somebody smarter and wiser than me made the decision that it's okay.
Relevant files: DuggaSys/fileed.js & DuggaSys/fileedservice.php
=> G3 2023 v5 issue#13821

DuggaSys/diagram.js
Centered the cursor close to the middle of each ghost element except the current sequance element. IE entity ghost appears doesnt have an utline while its a ghost and should be taken care of in another issue.
I also removed "avgcharwidth" which was a dead variable with no current use after getting permission.
=> Centered the cursor for ghost elements

DuggaSys/diagram.js
created a variable for holding the stroke color for special cases like super state outer border and sequence actor body called nonFilledElementPartStrokeColor. Then implemented that into actor and super state as the stroke color for the parts that do not have a fill. and the actor text.
=>  UML Super State darkmode issue #13905 

DuggaSys/diagram.js
The SD Arrow should now be rotated correctly when the line is "straight", if the line is segmented it will fallback to the previous implementation. *This applies to both the end & start icon*
It is however possible to place the elements in way such that the arrow is somewhat hidden behind the element, if this is deemed problematic, a new issue should be raised
=> G1 2023 v6 #13689

DuggaSys/gitcommitService.php
No longer saving the commit when creating a course. It now saves the commit when pressing the refresh button and instead of just refreshing the metadata it also downloads the files. 
Test this by creating a new course with a github url. 
Check the courses folder to see if you can find a folder with the course id. There should be nothing there.
Open the SQLite database and check the gitRepos table to see that no commit has been saved for the course.
Go into the course you've created and press the refresh button.
Go back into the courses folder. Now there should be a folder with the course id as name, containing the files from the repo you used.
Also check the SQLite database. It should have the latest commit saved for the course. 
co-author @c21rebja
=> G3 2023 v6 issue#13943

DuggaSys/courseed.js, DuggaSys/gitcommitService.php
We have added functionality so that the SQLite database updates when the github repo URL is changed for a course (cogwheel on course page). This includes deleting all of the files connected to a course in the gitFiles table, then updating the course row with the new URL and commit. 
To test this, create a course with a url. 
Open the sqlite database and look at both the gitRepos and gitFiles tables. 
Go to the course page and change the link to a new one. 
Go back to the SQLite db; now both gitRepos (URL and commit) and gitFiles (all new files) should have changed. 
co-author @g21emmka
=> G3 2023 v6 issue#13890

DuggaSys/diagram.js, DuggaSys/diagram.php
Created the element kind sequenceLoopOrAlternative, then created the svg for this and made a loop that draws a number of dashed lines depending on user preference. The default is 1. This is changed via the **options pane**. If this is set to 0, the Alt will automatically change to a Loop.
Also added the ability for vertical resizing in case the user wants many alternatives. This was done via reuse of the same vertical resizing i made for actor and object (their lifeline)
It is noteworthy that naming this or actor and object does not work at the moment but it is the same in the stable branch right now so it is unrelated to this issue.
=>  Add functionality for sequence loop or alternative #13914

DuggaSys/diagram.js
Fixed an issue where ctrl+z when placing elements would cause the ghost to be removed, hence making it impossible to place another element without reselecting it in the toolbar. Solves issue #13965
=> Ctrl+z when placing elements #13965

DuggaSys/diagram.js
Changed the default value `element.type` from "sequence" to "SE" for diagram.js and added the remaining implementation for SE in the option-pane
=> Not possible to rename actors and objects #13958

DuggaSys/diagram.js
If a transition has a label it will now show up like the following:
> "A" goes to "B" with lable "Test"
and if the label has square brackets like `[Test]` it will show up as the following:
> "B" goes to "C" with guard "[Test]"
=> G1 2023 v6 #13991

DuggaSys/diagram.js
Removed condition that made it so that only ER-elements count their lines and add them to their respective array.
Control this by writing `getElementLines(context[0])` after selecting an element *OR* try switching between types while lines are connected.
=> Add functionality for all entities to elementHasLines #13865

DuggaSys/diagram.js
changed the variables of the x and y positions of the labels so that its 1 times the zoomfact on both x and y
=> g1-2023-v6-fix-3-#14022 changed x and y postion of label

DuggaSys/diagram.js
getElementLines used to only work for ER this seems to be due to how the other types tops are defined. element.top.concat was undefined for the other types but changing top with left, right or bottom worked just fine, so i changed element.top.concat to element.bottom.concat and it should now work for all types.
=> getElementLines now works for UML, ER, IE and SD

DuggaSys/diagram.php
made it so the button calls loadDiagramFromLocalStorage onclick
=>  Allow display of saved diagram when loaded #14045 

DuggaSys/sectioned.js, DuggaSys/sectioned.php, DuggaSys/sectionedservice.php
What we've done is created a dropdown menu within the github buttons for each moment in sectioned.php
With this dropdown menu, you can traverse the webserver repostitory for all directories under the courses/{course id}/Github path containing the string "Examples" (This is done as the filtering for downloading files to webserver is not complete yet as far as i'm aware). When you choose one of them, this is supposed to call the automatic creation of course content via issue #13549, but this might not be testable for now. 
This also updates the database table "listentries" with a newly added column "githubDir" with the chosen directory. It will look something like this.
To test this, open a sample course with folders within the courses/{course id}/Github folder that match the syntax of …
=> G3 2023 v6 issue#13897

DuggaSys/diagram.js, DuggaSys/diagram.php
Toggable-buttons now indicate that they're active. I didn't make the bonus effort of making the highlight more visible, but maybe that can get its own issue.
=> Not all toggable-buttons have indication that they are active #14027

DuggaSys/sectioned.js, DuggaSys/sectionedservice.php
Redone the previous version of creating code-examples to fit the new version of how files,dir and moment is located on the webbserver and repo, see https://github.com/LenaSYS/Webbprogrammering-Examples/tree/master/Examples%20Html for moment "Examples Html".
This now creates a code example based on the file name. If multiple files have same name they are created as the same codeexample. Meaning: 
Canvas Animate.html = 1 code-example
Canvas Draw Objects.html =1 code-example
Canvas Gradient.html =1 code-example
Canvas Immediate.html =1 code-example
And 
Canvas Animate.html + Canvas Animate.css 	=1 code-example
This verision does currently not support the possibility to have two files of the same type in a code example because two files cannot have the same type and name. But maybe two or …
=> G3 2023 v7 issue#13549

DuggaSys/diagram.js
I added a svg rect that sits behind the actors name, this caused an unexpected bug though where this rect would be immensely offset if the name of the actor was too long to fit the designated box.
As shown in the comments on issue #14059 there was a discussion between me and the group leader about how this problem should be resolved. I ultimately decided on method two: "A similar method as the name for ER entities; simply have the name cut off into nowhere if its too long."
=>  Name of lifeline elements #14059 

DuggaSys/sectioned.js
This pull request introduces a feature that automatically refreshes code examples when a user is viewing the course page. This PR includes a countdown timer that runs for 10 minutes while the user viewing the course page. Once the timer reaches 0, all code examples for each moment/lecture are refreshed. When the user is not viewing the course page, the timer is paused. This is used by a boolean value 'isActivelyFocued' to ensure if the course page is viewed on by user. Also withthe function from jQuery 'blur' and 'focused' it was simple to implement. 
* The createExamples function was updated in another issue with different parameters, meaning my function also will need to be updated so it has same parameters as that function
* A toaster/alert needs to be fixed so the user can get a …
=> G3 2023 v7 issue#13987

DuggaSys/sectioned.js, Shared/SQL/init_db.sql, Shared/basic.php, recursivetesting/FetchGithubRepo.php
The table gitFiles now contains a new field which is to be used for the actual name displayed in LenaSys, since the feature to be able to change the name which is displayed was to be added and the previous fileName is a primary key.
Co-authored by b21leowa
=> Added column for separate filename in lenasys for gitFiles

DuggaSys/sectionedservice.php
From issue: https://github.com/HGustavs/LenaSYS/issues/14126
Insert correct course version when automatically creating code examples.
We changed how we select the courseversion when we insert new items into listentries. Previouslt we selected from the courses table on the active version column. We changed to select the version from where the button was pressed instead so that the listenries are inserted into the correct moment and version of the course.
Aslo fixed another realated bug with this issue.
The bug: a code example cannot be created on two different courseversions on the same course.
Fixed the count to see if a codeexample exist to also look at the selecteed courseversion from where the button was pressed.
This was done with @b21sebgr
=> G3 2023 v7 issue#14126

DuggaSys/sectioned.php
Now the dropdown for choosing a directory after downloading form Github does not filter out for maps only containing the keyword "Examples", so it should now display all maps within the given directory and look something like this
To test this, simply open sectioned.php, click on an individual github button on a moment to open the dropdown and see if the dropdown contains multiple options not containing the keyword "Examples"
=> Removed filter filtering out maps that doesn't contain the keyword "Examples"

DuggaSys/diagram.js
edited the sequence object svg to fit the avaliable space better, the extra free space made the text seem more broken than it was. The text now works just like all other element names.
=>  Name of sequence object cuts of a little too late #14115 

DuggaSys/gitcommitService.php
Issue #14139 
Now the SQLite table gitFiles are cleared every time the course is refreshed. 
If you haven't run the install script yet today (22/5), please do so before testing.
To test this, create a new course (or use a course you already have with a github url) and download the files with the refresh button. Then check the SQLite database in CMD to see what files are in the gitFiles table (select * from gitFiles). 
Remove a file from your connected github repo and press the refresh button again (note: it is important that you make sure the change has gone through before pressing the button!).
Open the SQLite database again in CMD and see if the files are up to date with your github repo.
co-author @g21emmka
=> Clear gitfiles from SQLite db on refresh #14139

DuggaSys/sectionedservice.php
This is part one to solve issue  #13934 wich is the update part of existing code-examples auto create function.
We divided the update into three parts:
1. Hide an example when all files are deleted to that codeexample in the github repo.
2. Remove/unlink one or more boxes if one or more file (but not all) are removed from the github repi
3. Add boxes to the codeexample if more files are added to the githubrepo and those files should be added onto an existing code-example.
This PR will solve part 1. 
We decided to make a PR for the first part since we created this branch after we did the PR for https://github.com/HGustavs/LenaSYS/pull/14130 but before it was merged and would like this fix for part 1 (and 2 and 3).
We use the previous selection of coursevers here in this branch based on the …
=> G3 2023 v7 issue#13934

DuggaSys/diagram.js
Reworked the current system to store and map multiple JSON strings to their own key, while they are all in the same string (localstorage). Used this system to connect the saving and loading functions for local diagrams.
You can either save a diagram with the same name to overwrite it, or a new name to save it as a seperate diagram.
AutoSave is called the first time a diagram is saved, and then it is called by the function `saveDiagramBeforeUnload()`
=> G1 2023 v7 #14110

DuggaSys/diagram.css, DuggaSys/diagram.js, DuggaSys/diagram.php, Shared/icons/spinner.svg
Created a loading spinner that disappears after the window is loaded and also calls the startup functions.
For the tester: you can use the networking tab of developer tools to artificially throttle your connection to be slower, this allows you to see the loading spinner better if you have fast internet.
=>  Better loadscreen #14121 

DuggaSys/diagram.js
Solved an issue where segmented arrows would strecth if pointing upwards. The underlying issue is not the arrow itself, but the "hitbox" of the SD entity being to large:
I would suggest that the "hitbox"-issue should be fixed in a new issue.
Solves issue #14063
=> Stretching arrow on segmented edge #14063

DuggaSys/diagram.js
Fixed an issue where the changeState() function displayed an error message even though the changes were applied. 
Removed a function call `generateContextProperties()` as the propertySet was overridden by it, causing the changes not to be saved and applied properly. Solves issue #14067
=> changeState() misbehaving #14067

DuggaSys/diagram.js, DuggaSys/diagram.php
Replaced all HTML type adding of event listeners like "onmousewheel...." that used event as argument with javascript addEventListener, thereby removing use of the deprecated 'event' argument and also replacing use of the deprecated 'mousewheel' with the proper argument; 'wheel'.
=>  Even more deprecated arguments #14089 

DuggaSys/diagram.js
fixes #14222 
when testing try drawing lines and elements with type note and check for errors.
=>  fixed so note now follows the corrrect naming skeme

DuggaSys/diagram.css, DuggaSys/diagram.js, DuggaSys/diagram.php
The function I made checks if data[] == 0 which means the container is empty or if the historyindex is -1. It is called whenever the mouseUp event is triggered. It should work with both ctrl+z and removing elements. The buttons is set to "disabled" (only by css) by default.
=> Don't allow clicking on save button if there's nothing to save #14113

DuggaSys/diagram.css, DuggaSys/diagram.js
Added functionality to remove a specific diagram from localstorage. You can now delete a save from the load diagram menu by pressing the delete button.
Since autosave almost always updates, there is no need for the user to be able to remove it.
=> G1 2023 v7 #14153

DuggaSys/diagram.php
Placed Vertical and Horizontal buttons under A4 template.
So it looks like this:
Instead of this:
=> Strange behaviour when both template and example diagrams are toggled on #14233

DuggaSys/gitcommitService.php, DuggaSys/sectioned.js
for issue #14002 
Made the variables for the refresh button into global ones and stored them at the top of the files. 
This is for both automatic (sectioned.js) and the manual (gitcommitService.php).
We noticed while adding this that the automatic refresh runs every 60 seconds unless you do a hard reload of the page, only then does it run every 10 minutes. 
To test this just check that the functionality for the refresh timer (the code for oversaturating github) works both automatically and manually.
co-author @g21emmka
=> G3 2023 v7 issue#14002

Shared/css/blackTheme.css
Fixed color of a4 template text when in darkmode. Solves #14232
=> A4 template in darkmode #14232

DuggaSys/diagram.js
The title is misleading, you can group-select sequence objects. The problem is that resizing an element vertically changes the y position detected when group-selecting and makes it so that the visual location doesn't match up to the actual location needed to include in Box Selection. 
I've fixed that by storing the height when first resizing an element and changing the compared y position based on the difference with their current height. You still need the Box Selection box to be a bit above them, but that has nothing to do with resizing and was both there before I started and was possibly intended.
=> Unable to group-select sequence objects #14026

DuggaSys/diagram.js
There was a problem of not being able to change any attributes, like name etc to anything. This completely broke the context pane. This was fixed by surrounding the reassigning of element.type with an if statement making sure its not undefined first
Please look at files changed, there is only if statements added that checks its not null
This was done together with me (@a21aldsa), the group leader (@b21eriho), the issue leader (@b21phiro) and also @a19clasv
=> Master g1 context pane fix | Null checking element.type being reassigned

install/install.php
checks if directory exists before attempting to delete it.
=> added error handling for deleteMetaData

DuggaSys/diagram.php
Changed from comma to semicolon in 'onclick' on line 1106 in diagram.php as the functions were already implemented but did not work. The semicolon allows multiple functions to be entered inside 'onclick'.
=> Fixed savebutton in diagrams.php (#13984)

DuggaSys/courseed.js, DuggaSys/courseedservice.php
Fixed bug where course GitHub URL was not saved nor displayed correctly when editing a course. With the current fix, the course GitHub URL will now be saved to the database and correctly fetched with a modification of a database query. Please note that when creating a course, the GitHub URL field remains red regardless of input, although this does not affect the functionality of the whole process.
Also fixed the bug where "null" or "UNK" was displayed in the URL field for courses without a GitHub URL.
=> G3 2024 v1 #14322 FIXED

DuggaSys/diagram.js
Tested on Chrome, Edge and Firefox.
=> Now not possible to bring up context menu when on diagram page.

DuggaSys/microservices/courseedService/createCourseVersion_ms.php, Shared/dugga.js
This microservice is used to create new versions of courses.
enter a course while logged in as a superuser and press the plus button to create a new version.
Input the data here. It is important to set "copy content from" to "None" since that functionality will be handled by a different microservice and doesn't work in its current state.
issue #14156 has more information if needed
before merging after testing has been done, dugga.js should be restored to use the monolith service by changing the code on line 1019 back to its original state: 
```
if(kind=="COURSE"){
$.ajax({
url : "courseedservice.php",
type: "POST",
data: "opt="+opt+para,
success: returnedCourse
});
}else if(kind=="VARIANTPDUGGA"){
```
=> G2 2024 v13 issue#14156

DuggaSys/diagram.css
I've modified line 120 as I fixed the button issue where it wasn't able to click on it at the left side (Issue #14367). I added some extra space at the bottom of the button by using a "padding 6px". Now it works better and you can click on the button even on the edge. I checked to make sure it looks good on all the full option screen sizes.
=> Enlarge section that opens the option

DuggaSys/diagram.js
Box selection wouldn't properly select items inside it's area. This issue was created specifically for super-states, but more diagram-types had similar problems. Issue is now solved and you can properly select items with the box selection.
=> Solved issue where box-select wouldn't properly select items. (#14325)

DuggaSys/gitcommitService.php, Shared/css/style.css, Shared/navheader.php
Set a fixed width to the tooltip-box so it is centered underneath the gitRepo-button even if it has no date from last fetch. Set the cooldown to show "0" instead of a negative value if the cooldown in out of sync.
=> G3 2024 v1 #14352

DuggaSys/diagram.js
Note was spelled NOTE, IDE did not give an error for this. this is now fixed.
=> Solved the 'keybind for note' bug

DuggaSys/diagram.js
I changed the parameter (elemsAreClose) in swich case for startIcon with same parameters as there was for other icons.
=> arrow is not broken anymore  #14292

DuggaSys/sectioned.js
For the name:
Validation color for name was based on a variable that was defined in a function that turned out to be unused. Therefore, undefined. Unsure if the function has any other functions and if the variable might be used in other place.
For this validation I created a new variable "inputColorTheme". A function was added to initialize the variable by checking localStorage for which color theme is being used. in "validatesSectName()" the function is always run to reinitialize the variable, since the theme can be changed before or after entering the page. The function then uses the new variable insted of the old one to color the element.
For the date:
The date validation was based on the same variable, which is now changed, so the color will work (confirmed with testing). But that's …
=> Fixed validation for name and date #14368

DuggaSys/sectioned.js
Removed unnecessary for-loop to minimize AJAX-calls. Now there will only be one AJAX-call for every moment in a course. The content of the AJAX-call remains unchanged. 
Now the AJAX-calls are only executed in a 10 minute interval, additionally also when the user refreshes a moment.
We have noticed that within the AJAX-call, there is a `duggor` attribute which contains information unrelated to the course. Another issue might be to change the structure of the AJAX-call to contain less information, thus avoiding unnecessary repetition. 
Issue: 
#14357
=> G3 2024 v2 #14357 Removed redundant AJAX calls and fixed the time interval

DuggaSys/diagram.js
I added the closeModal() function to the if statement regarding escape presses in the keyup EventListener.
=> Added functionality to close loaddiagram using escape key #14403

DuggaSys/darkmodeToggle.js, DuggaSys/sectioned.js, Shared/css/blackTheme.css, Shared/css/style.css
My issue was that there was only a light theme for the course schedule (SVG). 
I made it so that the schedule SVG works in dark mode and light mode. The dark mode version now looks like this:
The theme should also update without having to refresh the page. To update the theme, you should only have to press the moon button:
Additionally, test that it also works when using the moon button from the burger menu (can be accessed with smaller devices). This button within the burger menu can be seen below: 
The SVG whould update without having to refresh the page, even when using the burger menu version of the button.
Pull request from issue #14450
=> G3 2024 v2 #14450 Dark mode for course schedule

DuggaSys/diagram.js
I replaced the break; line with isOverlapping = false. If you draw a super state or sequence actor then you should not be able to overlap with other diagrams like ER diagrams.
=> replaced break; with isOverlapping = false;

Shared/css/blackTheme.css, Shared/css/style.css
The issue appeared to be the styling of the progressbars being applied by simply applying styling to every odd child of swimlaneSVG.
as the demo course has 9 columns instead of 10 like webbutveckling, the styling got "desynced". Simply changing it to apply specifically to children of swimlaneSVG that also have the class progressbar appears to have fixed it well.
the progressbars themselves still span the entirety of the demo course schedule, but we believe that to be intentional.
=> Improve consistency in dark mode for course planning svg

DuggaSys/diagram.js
You can now no longer select an element when you're in the PLACING_ELEMENT mode. Also deleted an unnessesary console.error that was thrown when trying to create an element on top of another.
=> Selecting with ghost entity disable

DuggaSys/diagram.js
Removed 'margin-top' property from all elements. The calculations for the height of the elements when resizing was incorrect due to the 'margin-top' property. 
Resizing elements now work as intended.
=> Fixed issue where resizing elements caused the position to change. #14383

DuggaSys/diagram.css
Weight and height was defined in two places: CSS and javascript . I deleted wight and height from CSS file.
=> deleted height and weight from CSS

DuggaSys/microservices/showDuggaservice/updateActiveUsers_ms.php, Shared/dugga.js
The new microservice is in: updateActiveUsers_ms.php.
I have tested it by running this in the terminal: 
curl -X POST -d "hash=AcIj-Ld6&AUtoken=9999" http://localhost/LenaSYS/DuggaSys/microservices/showDuggaservice/updateActiveUsers_ms.php
and compare the output from the instance in the groupdugga table in the database. I have not been able to test the service in the application.
This service is taken from groupDuggaservice.php monorepo.
To make the microservice run instead of the monorepo version change row 1244 in dugga.js to:
else if(kind=="GROUPTOKEN") {
if(opt=="UPDATEAU"){
$.ajax({
url: "../DuggaSys/microservices/showDuggaservice/updateActiveUsers_ms.php",
type:"POST",
data:"AUtoken="+groupTokenValue+"&hash="+hash+"&opt="+opt+para,
dataType: "json"
});
}else{
$.ajax({
url: …
=> G2 2024 v2 issue#14552 create updateActiveUsers_ms.php

DuggaSys/templates/diagram_dugga.html
Added `padding-bottom: 2px;` to the instructions window so they line up
=> aligned instructions and canvas #12886

DuggaSys/duggaedservice.php, DuggaSys/tests/duggaedservice-tests.php
**Fix bugs in dugggaedservice-tests.php**
File: duggaedservice-tests.php
Issue: Variant tests passes even when the variant id is not retrieved correctly, causing the operations tested to not take place.
all "Test 3 (assertEqual)" tests should now fail when faulty values are entered.
Important for testing:
If you have made changes to the variant table before, you might need to reinstall your database or remove any new rows so that the expected outputs are correct.
If you make the "update variant" or "delete variant" tests fail on purpose, make sure to manually delete the newly created variants in the variants table before testing again (delete the last rows where variantanswer = 'Test text' or 'Test text updated').
=> G2 2024 v2 issue#14504

DuggaSys/validateHash.php
opened the validateHash.php file and removed the echo statement that happens before a redirect (header())
=> remove echo from validateHash.php

Shared/logging.php
Change the paths for logging.
Before a error was shown in the response from logging.php when visiting e.g. 'show tests' as a teacher in a course
=> Merge issue#14650 add correct paths for logging

DuggaSys/diagram.js
We have now managed to make it work so that when you press the button, "\<\<include\>\>" appears instead of "&#60&#60include&#62&#62". Additionally, the white background has been adjusted to fit the text better than before when it was much longer.
So for the textfield, converted character encodings into angle brackets; Then for the label, convert angle brackets into character encodings.
Here is an image of what the diagram looks like now:
=> G1 2024 v3 #14548

DuggaSys/duggaed.php, DuggaSys/showDugga.php, DuggaSys/testDugga.php, DuggaSys/validateHash.php, backend-models/OlderDuggaSYSLogs#13199.txt
We removed all references to timer.js and clickcounter.js since these have been removed since a previous merge. These files only consisted of commented out code and were deemed excessive (and were thus deleted). 
This issue was fixed by uncommenting the pdoConnect() in duggaed.php. 
Pressing “Give students access to the selected version” will result in a crash in all courses. This needs to be fixed.
The “Give students access to the selected version” button can be found in the header of a course:
The result: 
This new potential issue does not have the same problem as ours and requires a different solution (since pdoConnect() is not commented out in this page).
=> G3 2024 v3 #14666 - Fixed "Show tests"

DuggaSys/diagram.css
Added a z-index for the class "zoom-container" in css. Can test it by placing for example sequence lifeline on top of the zoom function on the bottom left and see if the element is on top of the zoom button and if you can still use the button.
=> G1 2024 v3 #14651

DuggaSys/diagram.js
Calling clearContext() and clearContextLine() in the PLACING_ELEMENT mousemode so everything becomes de-selected when you place a new element.
=> Placing a element now de-selects everything.

DuggaSys/sectioned.js
Issue: Its not possible to update the "gradesystem", "visibility" or "moment" of a listed entry in a course. 
I have not been able to recreate the problem with "visibility" or "moment", it works fine for me. however "gradesystem" was not working on listentries with kind 3(type: tests)
After doing some research it seems that only kind 4 should be able to have gradesystem changed.
I remove the gradesysteminput field from listentries with kind 3. When you go into settings for a listentrie that has type: test the inputfield for gradesystem will no longer be shown.
=> Remove gradesystem input on the kind type 3

Shared/navheader.php
It should be possible now to view existing course versions in the course version creator but also in choose course version dropdown. While solving the issue and trying to make it work a strange explode error occurred when you would navigate from version to version but now it's been fixed.
=> the "copy content from" dropdown now displays existing course versions

DuggaSys/validateHash.php
Removed echo and change the url. It is now possible to load a dugga using a hash.
To get a example hash from the db, use:
```
select cid,hash,password from userAnswer;
```
=> G2 Merge issue#14704 

DuggaSys/diagram.js
Simulate a click at mouseMode0 when ctrl + a is pressed before the select all so the user always comes to the select mode.
=> ctrl + a sets mouse to pointer

DuggaSys/diagram.js
I adjusted the deltaY (the change of vertical position) based on the kind of the element being manipulated. The kind attribute "elementData" determines the type of the element, such as 'UMLEntity', 'IEEntity', or 'SDEntity'. Since a UML entity consists of three parts and IE and SD entities consist of two parts, I divided the deltaY calculation by 3 or by 2 for the specific entity. 
This calculation adjusts the vertical movement speed for specific type of entity, allowing the pointer to move in parallel with the mouse.
=> fixed the pointer when dragging down

DuggaSys/sectioned.js
…rse version
The if-statement checks if "param.copycourse" is "None" and then calls either "CPYVRS" or "NEWVRS" via AJAXService.
The problem when creating a new version on a course that has no existing versions was that the dropdown that controls the variable "param.copycourse" had no "None"-option. So the value was simply empty. Which meant that the if-statement was calling "CPYVRS" since the value did no equal "None".
Sidenote:
There we're previous problems with a variable that caused activeversion (aka default version) to not work. Which in turn made creating new versions not work since even though the existed in the database due to the correct if-statement, they weren't displayed on the site still because a course doesn't seem to fetch versions if the course itself has no default …
=> Fixed if-statement calling for copy incorrectly when creating new course

DuggaSys/filereceive_dugga.php, DuggaSys/showDugga.php, DuggaSys/showDuggaservice.php, DuggaSys/templates/3d-dugga.js, DuggaSys/templates/bit-dugga.js, DuggaSys/templates/boxmodell.js, DuggaSys/templates/clipping_masking_dugga.js, DuggaSys/templates/color-dugga.js, DuggaSys/templates/curve-dugga.js, DuggaSys/templates/dugga1.js, DuggaSys/templates/dugga2.js, DuggaSys/templates/dugga3.js, DuggaSys/templates/dugga4.js, DuggaSys/templates/dugga5.js, DuggaSys/templates/generic_dugga_file_receive.js, DuggaSys/templates/shapes-dugga.js, DuggaSys/templates/svg-dugga.js, DuggaSys/templates/transforms-dugga.js, DuggaSys/validateHash.php
Original issue: #14587 
I could not replicate the original error message received in the issue. My guess is that the cause of that error was that the user reporting it was using linux and/or had not configured ZIP-ARCHIVE as is explained in the [install guide](https://github.com/HGustavs/LenaSYS/blob/60fa0a4f5d03b176fc48452ed0b53346defc3cbc/README.md#to-get-zip-archive-to-workused-in-download-zip-function).
I did not have any issues with ZIP-ARCHIVE since I am using windows where it is built in.
I did however find a bunch of different bugs that kept the user from being able to save a dugga.
- When a dugga is saved the generated link linked to the wrong /sh folder instead of /LenaSYS/sh.
- Loading a saved dugga in ValidateHash.php also linked to /sh instead of LenaSYS/sh.
- Uploading a …
=> G2 2024 v3 issue#14587 - Fix bugs in showDuggaService

DuggaSys/microservices/accessedService/addClass_ms.php
The microservice is supposed to be used when adding a new course, as can be seen from the ```accessedservice.txt``` text:
```* Add new course (opt = ADDCLASS)```. However, when creating a new course I was not able to see the ```accessedservice.php``` file being called at all. I couldn't find ```ADDCLASS``` used anywhere else either. Because of this I have not actually been able to  test the implementation.
If any tester finds where it's used you can test the implementation by changing the ```kind=="ACCESS"``` part in the ```AJAXService()``` function inside ```dugga.js``` to:
```
else if(kind=="ACCESS"){
let serviceURL = "accessedservice.php";
if (opt=="ADDCLASS"){
serviceURL="../DuggaSys/microservices/accessedService/addClass_ms.php";
}
$.ajax({
url: serviceURL,
type: "POST",
data: …
```
=> Create microservice addClass issue #14756

Shared/css/style.css
Changed the height to 85vh for ERTable in style.css, it should now expand with screensize to mitigate scrolling. Link to issue: https://github.com/HGustavs/LenaSYS/issues/14778https://github.com/HGustavs/LenaSYS/issues/14778
=> Increased the height for ER-tables: issue#14778

DuggaSys/showDugga.php, Shared/navheader.php
Before it wasn't possible to display an error message for wrong login because of Uncaught PDOException that caused a php error for uncaught SyntaxError for invalid JSON. But now when a user enters wrong credentials the error is displayed.
=> G3 2024 v3 #14664 error message for wrong login is fixed

DuggaSys/diagram.js
Can now press a keybinding and the sub-menu is closing when open. Can test it by have a sub-menu open and press for example "1" and the sub-menu should be closing.
=> G1 2024 v3 #14769

DuggaSys/gitcommitService.php
Made it so that the github repos files are saved to the githubmetadata2.db.
To be able to test this you must reinstall lenaSYS so the database is up to date. 
Add a github repo in editcourse 
And also test it by adding it in fetch github.
we used DB Browser to look in the githubmetadata2.DB
@a22natth and @a22oscja assinged aswell.
=> G3 2024 v3 #14526

DuggaSys/diagram.js
Added global variables that saves the original properties of an entity before resizing while in "mdown()" and then lets the user resize freely when the program is in "mmoving()". and then when the resizing is done, the "mup()" reverts the entity to the original state if overlapping was detected and sends an error-message.
=> Program now detects overlapping while resizing objects

DuggaSys/duggaedservice.php
The error was occurring because the ```useranswer``` table has a foreign key constraint to ```quiz```. The solution I ended up with was to delete all instances of ```useranswer``` with a reference to the quiz to be deleted.
This is only a good idea if useranswers are SOLELY answers in quizes, which I assume. However, I am not 100% sure this is the case. A tester should ideally come to the same conclusion as me. What the tables are supposed to do can be found in ```dbTables.md```. 
The two rows look like:
```
The quiz table contains everything related to a dugga, and connects the dugga to a specific .js template file. It does not save answers, it only loads the dugga how it is supposed to look like.
```
```
Stores all the duggas that has been saved in the system. That is, the answers that …
```
=> g2-2024-v3 issue #14803

DuggaSys/diagram.js, DuggaSys/diagram.php
Copying a lifeline actor/object was not possible before due to the way they were drawn inside the div. 
I've separated the actor/object into two different elements, making it possible to copy the lifelines. 
I have not changed the tooltip for either of the two elements, and the new type of element has a placeholder icon. (These will have to be fixed in a new issue, due to no time before merge).
=> Separated the lifeline actor/object into two different elements. (#14654)

DuggaSys/sectioned.php, Shared/css/blackTheme.css, Shared/css/style.css
Fixed it so that tooltips appeared on the correct row **when trying to create a new course version**. These tooltips can be seen when pressing the "+"-icon from the navbar and entering an invalid input in the form. 
The "+"-icon:
Now the tooltips should look like this:
Also updated it so that the little triangle shape at the right side of the tooltip also appeared in darkmode.
**To test this pull request: test that the tooltips for every input appear on the right row for you. Also make sure no new errors are created and that everything looks fine.**
=> G3 2024 v4 #14851 Tooltips appearing on the wrong row

DuggaSys/diagram.js
I fixed so that not only superstates but also the other elements have a minWidth and minHeight variable storing their specific minimum height and width so that you can call on these variables in one switch case instead of creating multiple different if statements one for each element. And I adjusted the minimum heights and widths to be realistic for each element.
=> Fixed the minimum height and width for superstates

DuggaSys/microservices/sharedMicroservices/setAsActiveCourse_ms.php
fixed issue according to description:
Add pdo as parameter, dont create a new one with pdoconnect
Remove as many includes as possible
Remove session_start()
The reason for this: This things are already done by the calling microservice
IF IT DOESNT NEED PDO ( DOES NOT EXECUTE QUERIES) , JUST MARK ISSUE AS COMPLETE)
=> 14916 fix setasactivecourse msphp

backend-models/microservices/duggaSys services/Microservices.md
The service was considered redundant since updateUserPassword_ms.php from profileService already does this.
=> Deleted changeUserPassword_accessed

Shared/css/blackTheme.css
Added CSS in blackTheme.css that uses both the "#Courselist" and "#fabBtn" to get a hihgher priority than previous "#Courselist" and "a". This made the color of the "+" in the fab-button to have the same color as the links in Courselist.
=> Added new CSS

DuggaSys/sectioned.js, Shared/css/style.css
Smooth scrolling has been added for when an item is created. It does appear to be decently fast(atleast on firefox), but it is the standard used in all browsers, so it should be reasonable.
As for the highlighting of items, could not figure out how to make highlight only go back upon hover. Because of this I simply doubled the time it takes to fade out, which makes it a little more clear.
=> Automatic scroll function for new items

DuggaSys/diagram.js
Added a eventlistener for when the mouse is leaving the window/website. Can test it by select the box selection tool and use the tool, but before the left mouse click is up have the mouse outside of the website/window. When your mouse is outside of the website you can have the left mouse button up, and the box selection should be gone when the mouse is returning to the website.
=> G1 2024 V4 #14878

DuggaSys/microservices/showDuggaService/updateActiveUsers_ms_test.php
The test works, but the output of the microservice is very short, so that should probably be changed in the future and consequently also this test.
To test this you need to replace the includes at line 65 and 203 in test.php to `include_once( __DIR__ . "pathtofile");` (where pathtofile is the path already written there).
=> Created updateActiveUsers_ms_test.php

DuggaSys/courseedservice.php
It appeared that a red line would appear when one would create a new course version, and for some reason, I hope that it is local otherwise, it might be some weird bug with the code. But hopefully, it should work.
To tester:
Valid input format
Version ID: 2001
Version Name: HT01
Start Date: 01/05/2024
End Date: 30/06/2024
MOTD: MOTD
Copy content from: ST20 - 52432
=> Fixed visual bug when copying a new course version 

Shared/css/style.css
The issue was due to an !important set on the element that was displaying the element. By removing this it seems to work.
=> Fixed the top dropdown not showing on smaller screens #15111.

DuggaSys/microservices/resultedService/getUserAnswer_ms.php, DuggaSys/microservices/resultedService/retrieveResultedService_ms.php
The MS was tested by first removing the permission checks from ```getUserAnswer_ms.php```, and then running the command:
```
curl -X POST -d "cid=2&vers=97732" http://localhost/LenaSYS/DuggaSys/microservices/resultedService/getUserAnswer_ms.php
```
=> g2-2024-v5 issue #15266

DuggaSys/gitcommitService.php, DuggaSys/gitfetchService.php, DuggaSys/sectioned.js
The issues I could find seemed to be related to the page reloading upon the save button having been clicked (in course) as well as the program simply not being set to "DOWNLOAD" when using one of the windows.
Tested both in course and through edit course, with both working to actually download files now, on top of inserting to metadata.
As I also noticed that the error logging was turned off if no token was present, I also took the time to fix this as i'd imagine it was causing confusion.
I also added a small function to gitcommitservice which simply lets you write into the log (as using echo/print_r no longer gives alerts, likely from toasts now existing).
The main issue currently would be that the downloading of files can be quite slow (took me 8 minutes for lenaSYS), but I could not …
=> Fetching github repo now works correctly - #15129

DuggaSys/sectioned.js
I assume that hideDeleted() was needed at some point to make the drag and arrange feature work properly, but have now been deprecated. There was a possibility of hideDeleted() being renamed but did not find any method matching the "hide deleted" name. The `.deleted` class used to mark the sections that are being deleted within 60 seconds, is not used for any extra hiding functionality.
=> remove unused method call hideDeleted() g3-2024-v5-#15055

DuggaSys/sectioned.js
Since the bug is only rare and visual, and trying to fix the race condition caused the edit section popup and no animation at all. Adding 100ms more delay is the simplest solution.
=> Scroll getting halted when adding new section, G3 2024 v5 #15157

DuggaSys/sectioned.js, DuggaSys/sectioned.php
To test:
After a codeexample has been fetched.
Check that the column filesize in table fileLink for the fetched files has recieved an insert containing their filesize.
=> Add filesize value in fileLink table db when fetching code examples #15230

newinstaller/tools/credentials_manager.php
The file credentials_manager is a tool class thats supposed to be used when creating new databases for user as they run through the installer. This is ment for the new installer and not the old one #15149.
For the following pr the class credentials_manager has been implemented to fully work. The idea is to use this when users create new databases through the installer, and functions thats included are getters / setts, initial creation of database, as well as some private functions thats running to see that everything needed exists and works properly. The class also checks for user permissions, and if permissions are not sat properly, the user doesn't get to change the file. This class also tries to find coursesys.php, and if it doesn't exists, it creates one.
The test should include …
=> g3-2024-v5-#15149

DuggaSys/courseedservice.php, Shared/navheader.php
When using the old database that the live version of LenaSYS is using, it wasn't possible to load into courseed.php. This was due to missing attributes and tables when comparing the database to the newer one. The main problem was that the database tried to execute queries made for the new database on the old database, so we implemented try/catches that execute an alternate query that works for it.
!IMPORTANT!
To test this you will need to use the old database.
=> Made courseed.php backwards compatible with the old database G3 2024 v5 #14849

DuggaSys/diagram.js
Adding e.preventDefault() to the arrows keybindings prevents the user from scrolling with the arrows while in a diagramdugga.
Regarding the change-request we (me and a22cazlu) couldn't reconstruct the problem trying different browsers and we dont see how adding the e.preventDefaults that almost all other keybindings also have would be the reason for the problem that the reviewer described. Is it possible that the reviewer didn't test the issue in the correct landscape or that any other factor might be the reason for the problem?
=> preventDefault() added to MOVING_OBJECT

DuggaSys/microservices/resultedService/getUserAnswer_ms.php, DuggaSys/microservices/resultedService/retrieveResultedService_ms.php
Tested by looking at the resulteditor of a course before and after implementing the changes. Before nothing could be seen, but after the changes, it works.
=> Small fix to getUserAnswer_ms.php issue#14500

DuggaSys/microservices/sectionedService/updateCourseVersion_sectioned_ms.php, DuggaSys/microservices/sharedMicroservices/setAsActiveCourse_ms.php
You can test this microservice by going to a course and clicking the cogwheel for "edit the selected version".
I couldn't get the logging to work, but that might just be on my end. I haven't been able to find a fix. If the tester also doesn't get the logging to work I will delve deeper into it.
Change row 1102 in ```dugga.js``` to:
```
}else if(kind=="SECTION"){
let service_url = "sectionedservice.php";
if (opt == "UPDATEVRS"){
service_url = "../DuggaSys/microservices/sectionedService/updateCourseVersion_sectioned_ms.php";
}
$.ajax({
url: service_url,
type: "POST",
data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
success: …
```
=> g2-2024-v5 issue #14423

DuggaSys/showdoc.php
showdugga seemed to work correctly for the most part, I have tested by inputting data needed into the database. As I noticed that all showdugga pages use showdoc.php instead if you do not have access to editing the page. This did not work but had support implemented already, so it was an easy fix.
From what I could tell from looking around everything should work now. However, it is not possible to actually get the current system to display anything (as the files/data needed is not included in the data we were given). Because of this, the testing becomes quite rudimentary. All in all i'd say out of all the pages, this one is the most likely to break with proper files/data, but I believe there is no way to get around this from our side.
**Testing:**
- get access to old database from …
=> legacy support for showDugga.php

Shared/toast.php
When calling the toast() function and assigning duration to 0 or null, it will now not be given a timeout. In other words, the user has to manually close the toast.
To test this i recommend changing the toast on row 1011 in sectioned.js. This toast will pop up when you delete an item.
=> Duration set to "0" will now not be given a timeout G3 2024 v5 #15423

DuggaSys/sectioned.php, Shared/css/style.css
There were specific styles being prioritized on certain elements. Which has probably been quick fixes. When these were solved, new issues with alignment appeared in other places. Most likely due to other quick fixes. There was a span element covering two elements which had a margin covering them both. Causing them to visually have double margin values when these elements themselves inherited the correct margins.
Hopefully, whenever a new element is added in the future, they should now inherit the correct styles. However, there might potentially be some places on the website where new issues arise. I can't find any for now, but they might pop up in the future unless a thorough search is conducted.
For testing, just check the alignments on all input elements you can find. For the specific …
=> Fixed aligments on input and select elements (issue: #14940)

Shared/dugga.js
Added async false to avoid xhr error in courseedervice
In previous version when copying new course version or editing version there is an xhr error in the network traffic caused by asynchronous calls being made.
With these changes a response can be retrieved
=> Added async false

Shared/css/style.css
Having overflow-y set to auto enables it to switch to a scroll-wheel whenever the text overflows in the y-direction. If the text does not overflow the toast, it will no longer show a scroll-wheel. Whenever the text overflows the toast, that's when the scroll-wheel appears.
The easiest way to test this is to go into toast.php and extend the timers for the toasts and then edit the content inside.
=> Changed .toastText overflow-y from scroll to auto.

Shared/navheader.php
The variable was declared in an unreachable else state. Moved it so that its declared. The error should be gone now for Mac users when opening courseed.php.
=> Moved the variable so that its declared. #15390

Shared/css/style.css
Minor additions were made to the style.css file where the login text and the hamburger menu always remains white, regardless of theme. This can be seen in the examples below. 
In dark mode:
Within sectioned.js (logged out):
On homepage(courseed.php, logged out):
On homepage in darkmode (logged out):
=> Changed the hamburger menu and login color - G3 2024 v5 #15318

DuggaSys/sectioned.js
It appears to have been the same lines that were removed in the old issue, likely someone accidentally put them back in.
**testing:**
check if the "User is focusing on course page, isActivelyFocused is now true" and "User lost focus on course page, isActivelyFocused is now false" console logs persist anywhere (although they were only present in sectioned.php)
=> remove unecessary console logs

DuggaSys/diagram.js
Fixed issue where an element would make a big jump when moving or resizing it. 
There is still a very small jump when resizing using the left node and the upper node (also affects the upper left and lower left nodes), but this seems related to the 'startX' and 'startY' values.
Also removed the 'preResizeHeight' code from the upper node (This code is not used anymore from what I can see).
=> Fixed move and resize jump. (#14623)

DuggaSys/diagram/helper.js
The if-statement that we changed didn't work good att all. If there was a sequence object on the diagram you could place objects on eachother freely. Now you can place sequence objects on eachother as long as it's not the same kind as the overlapping object. Same with UML state objects.
While solving the issue we also fixed so that you only can insert UML-state properties into UML superstate and that you only can insert sequense-diagram properties into loop/condition.
=> changed the conditions in EntityIsOverlapping

DuggaSys/sectioned.js
Moved the github buttons to the front of the row. Since this buttons seems to be one of the few that doesn't always appear on a row, they would shift the entire row by one step, therefore making it asymmetrical with other items.
Now it looks like this:
=> Changed order of buttons to make them align (from issue #14946)

DuggaSys/templates/generic_dugga_file_receive.html, DuggaSys/templates/generic_dugga_file_receive.js, Shared/css/blackTheme.css, Shared/css/dugga.css, Shared/css/markdown.css, Shared/css/style.css
Previously, when entering “Datorgrafik” and clicking on “Rapport inlämning”, the boxes below were not adjusted to the dark theme.
With the solution to this issue, changes were made to mirror the alternating background color of the table columns and the text-color. This can be seen in the example below:
=> Fixed the dark theme of boxes in "Rapport inlämning" - G3 2024 v5 #15405

Shared/navheader.php
It was never declared if there was data in the database, specifically it would only declare if there was no github repo set.
Now it sets depending on if its column has a value and also gets set if there is no data at all.
**Testing:**
- open basically any page on the website(sectioned, courseed, etc), check for an alert that complains about updateTime when the page loads.
=> Errors when entering new courses

DuggaSys/courseedservice.php
*copied over changes from last week, did a quick test to make sure it worked and fixed an edge case.
old text:
It was attempting to insert data into the database twice, leading to the error. I also added support for the old data. As a result of this fix, the course should also now show up without reloading the page, as it was getting stopped from making that happen before.
**testing:**
- if you do not have access to old data, get it from me/leaders/anyone really
- make a new course, check for errors.
- repeat on current/old data as much as you'd like.
=> Internal server error when making new course

DuggaSys/microservices/duggaedService/retrieveDuggaedService_ms.php, DuggaSys/tests/microservices/duggaedService/createDugga_ms_test.php
The file should now be fixed.
I tested it by doing:
```
INSERT INTO quiz (cid, autograde, gradesystem, qname, quizFile, qrelease, deadline, relativedeadline, creator, vers, qstart, jsondeadline, `group`)
VALUES (1885, 0, 1, 'Test321', 'group-assignment', '2024-02-02 02:02:02', '2024-01-01 01:01:01', 'Snart', 101, '1337', '2024-03-03', '{"TestJSON":"2024-04-04 04:04:04"}', 1);
```
And then executing ```createDugga_ms_test.php``` and looking at the response (no filter).
Now all relevant values should be retrieved.
Since ```createDugga_ms_test.php``` is the only test for duggaedService implemented at this time, the expected output only needed to be updated there.
=> g2-2024-v6 issue #15514

DuggaSys/tests/microservices/duggaedService/createDuggaVariant_ms_test.php
I wanted to have more output by filtering like this, but it did not work for some reason. I guess it has to do with test.php. 
```
'filter-output' => serialize(array(
'entries' => array(
'variants' => array(
'param',
'variantanswer',
'disabled',
),
)
)     
),
```
Just having it like this works, but then 'modified' is included which depends on the time the test was executed.
```
'filter-output' => serialize(array(
'entries' => array(
'variants'
)
)     
),
```
=> Created test for createDuggaVariant_ms.php issue#15197

DuggaSys/diagram.js, DuggaSys/diagram/events/mouse.js, DuggaSys/diagram/helpers/element.js, DuggaSys/diagram/helpers/mouse.js
Overlapping is checked for objects when not in snap to grid.
newX and newY was undefined for all non snap checks
=> Fixed overlapping check #15508

DuggaSys/tests/microservices/duggaedService/updateDuggaVariant_ms_test.php
Unfortunately there seems to be an issue with ```test.php```, which is why the filter-output looks like it does. Until #15543 has been fixed it will have to look like this, unless a tester finds another solution.
=> g2-2024-v6 issue #15202

DuggaSys/diagram/constants.js, DuggaSys/diagram/helper.js
UML super state and loopOrAlt can no longer overlap. They can overlap with all other elements.
=> background overlap fix #15555

DuggaSys/codeviewer.js
Implemented keyup event for esc.
Integrated a check if popups are open in codeviewer.
Should work on all popups.
For testing:
--------------------------------------------------------------------------
Problem when pressing esc while previewWindow loginBox is open. 
Its container "previewWindowContainer loginBoxContainer" is set to none while "previewWindow loginBox" is still not changed from block to none. Circumvented this in this pullrequest but this will be looked into in another issue.
=> Added ESC to go back in codeviewer.php #15438

DuggaSys/diagram/draw/element.js
the sequence-actor and object was not alinged to the middle, this was beacuase they previously added the linewidth to the position of certian parts of elements. After removal this was fixed
=> #14986 actor and object alignment 

DuggaSys/accessed.js
Fixed current iteration of keyup for enter and esc. 
Integrated a check if popups are open in this eventlistener.
As the popups already has a close function attached to them we only go back if none are open.
Only current popups/modules in accessed are "createUser" and "addUser".
"removeUser" and "createClass" will be added later. These should be inserted into allPopups array when implemented.
For testing:
=> Added ESC to go back in accessed.php

DuggaSys/courseed.js, Shared/css/blackTheme.css, Shared/css/style.css, Shared/toast.php
Now there is a confirm toast available to be used among the rest of the toasts. I did this through adding additional elements to toastContainer that shows the two buttons (thanks Moa). To pass the arguments for the buttons, the last two arguments in the toast functioned are used for this (arguments and arguments2). 
To call this function, you just add the following code to a php-file that implements toast.php (for example courseed.php):
``` javascript
toast("confirm", "Are you sure you want to do that?", 0, "", "");
```
=> Added a confirm toast to the toast roster G3 2024 v6 #14813

DuggaSys/codeviewer.js, DuggaSys/contribution.js, DuggaSys/contribution.php, DuggaSys/contribution_loginbox.js, DuggaSys/contribution_loginbox.php, DuggaSys/duggaed.js, DuggaSys/sectioned.js, Shared/toast.php
I changed the most prominent alerts to toasts when browsing LenaSYS. Some alerts are left untouched due to them being needed for debugging or having important functions on the backend. By doing changes in courseed or codeviewer etc the alerts should now be replaced by toasts. 
One issue that this has generated is that toast does not pause the execution of code like alerts did. This means that some alerts, for example in codeviewer, shows for a short moment before the site is refreshed.
=> Changed important alerts to toasts. G3 2024 v6 #15388

DuggaSys/microservices/codeviewerService/deleteCodeExample_ms.php, DuggaSys/microservices/codeviewerService/editBoxTitle_ms.php, DuggaSys/microservices/codeviewerService/editCodeExample_ms.php, DuggaSys/microservices/codeviewerService/editContentOfExample_ms.php, DuggaSys/microservices/codeviewerService/retrieveCodeviewerService_ms.php, Shared/dugga.js
retrieveCodeviewerService_ms.php has now been implemented with its microservices.
I used curl commands to test because the website would refresh when calling a service, making the output not show in the network tab.
editCodeExample
```
curl -X POST -d "opt=EDITEXAMPLE&courseid=1885&cvers=1337&exampleid=7000&examplename=UNK&sectionname=UNK&addedWords=foo,bar&log_uuid=TmX2JZ8vpNIWHYh
" http://localhost/LenaSYS/DuggaSys/microservices/codeviewerService/editCodeExample_ms.php
```
editContentOfExample
```
curl -X POST -d "opt=EDITCONTENT&courseid=1885&cvers=1337&exampleid=7000&boxtitle=Testingbox&boxcontent=Code&wordlist=3&filename=JS-TEST1.js&fontsize=10&boxid=1
&log_uuid=TmX2JZ8vpNIWHYh
" http://localhost/LenaSYS/DuggaSys/microservices/codeviewerService/editContentOfExample_ms.php
``` …
=> G2 2024 v5 issue#15387

DuggaSys/courseed.js
It was not actually requiring you to insert a github key, it stemmed from the bfs function reaching the data limit. 
Since there reasonably is not much I can do about the data limit as well as the bfs function being worked on in another issue I just changed the error message to a more descriptive and made it close the window upon it being sent.
Dont think this really needs testing, but simply reach the data limit and insert only a link for a course that you do not already have files downloaded for.
=> When editing a course it will require you to input a github key

DuggaSys/codeviewer.php
Toast now shows correct icons after exiting the template form.
=> Added reference to icons. g3-2024-v6-#15507

DuggaSys/fileed.js
Fixed current iteration of keyup for esc and control.
Integrated current filePreviewClose() call when pressing esc and popup is open.
Integrated a check if popups are open in this eventlistener.
Current popups are when adding a file, previewWindow (Edit file icon) and fileViewPreview (clicking on the file name).
Added intended integration with "x" key. this was not implemented but previous devs had intended for it.
Also fixed previous indentation.
For testing:
Also try closing fileView with x key. It should not produce duplicates in view if opened again.
=> Added ESC to go back in fileed#15439

DuggaSys/tests/microservices/courseedService/createNewCourse_ms_test.php
Created the test for createNewCourse_ms.php
versions is included in the filter because it was not filtered out because that array also contains, e.g. "coursename".
Cid is not included in expected-output or the filtered values because it is a autoincrement column in the db, which means a user needs to reset the db before running the test. Coursecode and name should be sufficient.
=> G2 2024 v6 issue#15191

DuggaSys/accessed.js, DuggaSys/accessed.php, DuggaSys/accessedservice.php
Whats done:
- Dropdown list in both Remove user and add user is filled with all users.
- Add User now adds a user to the course without having to create one again. 
- Remove User now removes selected user from that course.
- Changed so readaccess users is seen is the list and not just teachers.
- Dynamic tooltipTerm for input validation.
For some reason the Term element has to be in Remove User popup. I dont know why but when its removed the dropdown options are not shown. Will look into this
Todo in future issues:
- Add Classes?
- Add Groups?
- Maybe update Term value if user already exists in course while trying to Add User.
Testing:
All users should show in both dropdown lists (Add User and Remove User)
Try adding any user into any course. Then reload the page and it should show up as …
=> Add functionality to "Add User" && "Remove User" button #15562

DuggaSys/courseedservice.php
You can now copy and set default courses
There was a missing $ in front of a variable
=> Copying and setting default versions #15392

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagram/constants.js
Added the new keybinding for save diagram, load diagram and test case. The keybinding is CTRL + S for save diagram, CTRL + L and CTRL + ALT + T for test case. Needed to have CTRL + ALT for test case because if I use CTRL + T a new tab pop out.
=> G1 2024 v6 #15553

DuggaSys/microservices/sharedMicroservices/getUid_ms.php, DuggaSys/tests/microservices/codeviewerService/editBoxTitle_ms_test.php
editBoxTitle_ms_test.php has been created.
I had to delete the line: ```include_once "../../../Shared/coursesyspw.php";``` from getUid_ms.php because it was causing errors, breaking the microservice. I can't see any place where the include is actually being used in getUid though so I don't think it should cause any problems deleting it. 
I had some other issues with the assert test failing even though the output and expected output were identical, I made it work by adding a bunch more values to the inserts, so there shouldn't be any problems now.
=> G2 2024 v6 issue#15184

DuggaSys/profile.php, DuggaSys/pushnotifications.js, Shared/dugga.js
If you log out while in profile.php you will now be directed to courseed.php.
Also the error regarding push notifications will no longer appear if not working in a setup that supports it. Essentially it was trying to interact with an element that would only be created if support for push notifications was installed, hence it was never created.
I also included some improvements to pushnotifications.js (changing var to let, and making parts of it use the standard for pushnotifications). I did not touch the other parts as I was unable to test it, so did not want to touch.
**Testing instructions:**
- To reach profile.php, be logged in and click your name in the top right from any page.
- if at this point it tells you that you need a secure https connection (which it will, unless you use one), …
=> If a user is logged out in profile.php, they should be taken to the home page and no errors should appear

DuggaSys/microservices/accessedService/getAccessedService_ms.php
This service should run when the GET opt is called. The point of this service is to run the retrieve service without running an other microservice before, this has been implemented in sectioned and showDugga as well.
The service only gathers the opts, makes the necessary includes and runs the retrieve service.
=> create service getAccessedService_ms.php

DuggaSys/sectioned.php, Shared/css/style.css
removed the inline styling and put it in style.css. and because im not allowed to change the css using class selectors i added 100px on the id dialog10 instead.
Testing:
go into a course and press the cog wheel on a moment:
then add an "illegal" character in the Name inputfield:
=> Fix tooltip for "Edit section" form

DuggaSys/sectioned.js
**Co-commit with @d22isaka** 
We have now fixed the deletion of duggor. The selected duggas get added to the "selectedItemList" array, from which all items are deleted and hidden when a user click "yes" in the confirmation box.  This happens in "deleteItem()" and in "deleteAll()" functions. "Undo" still works as usual.
The only bug that still persist is that duggas come back if the page is refreshed while the "undo" toast is still active. At the moment we have not found a way to combat this issue.
=> Fixed deletion of duggor

DuggaSys/courseed.js, Shared/css/style.css
`$(messageElement).stop(true, true);` does not exist in other form validations and seems to be very useful in stopping spam causing repeat fade-ins and -outs
Affected forms: Edit Course and New Course in courseed.php (quickValidateForm in courseed.js)
Extra:
* Added an neutral class for when optional fields are empty.
Note that the save button does not get disabled due to it currently being dynamic.
=> Elements now correctly fade in and out.

DuggaSys/sectioned.php, Shared/css/style.css
After fixing this issue, the dropdown now stays centered in relation to the “+” button for new items. The example below shows the menu at full screen.
The image below presents a more narrow screen size.
Lastly, the example underneath illustrates the menu with the smallest screen size. Additionally, z-index was added so that the menu does not fall behind the big “+” button at the bottom of the screen. Kindly, made sure that this works on both chrome and firefox.
=> Fixed positioning of "New Item"-dropdown

DuggaSys/diagram/draw/line.js
The new code makes rotating arrow tips better by using 45-degree turns instead of the old 90-degree ones. This change makes it easier to adjust how arrow tips look, making them both work better and look nicer.
=> Double arrow when creating Sequence diagram

DuggaSys/diagram/draw/element.js
Implemented a CSS styling to fix the issue where the Inheritance ghost element was appearing underneath other objects. By adding a z-index of 2 to the "Inheritance" element, it now correctly appears above other elements.
=> IE Inheritance ghost element appears under the object

DuggaSys/sectioned.js
Removed the call to the function "initInputColorTheme" from the validateSectName that is supposed to check the local storage if it is blacktheme or not. This seemed to get called wrong or something. After this was removed I wasn't able to get the fault of color for the input.
Check original issue for the sequence to manipulate the fault of input-background color.
=> Removed a call to function

.gitignore, DuggaSys/sectioned.js, DuggaSys/sectioned.php, DuggaSys/sectionedservice.php
Current v6 solved the halting issue. 
Copied from last pull request #15600
Extra:
* Added .vscode to .gitignore to make it easier to debug using visual studio code.
* Fixed errors occurring in sectioned.php due to them obscuring important footer texts.
* Fixed sections not inserting with correct positions or duplicate positions which would break functionality.
0. Reinstall using install.php but make sure to clear the folder `/LenaSYS/courses` before so that earlier GitHub files gest cleared.
Should like this after a clean install.
1. Create a empty test course or use an existing empty course like `Distribuerade system`
2. Connect https://github.com/LenaSYS/Webbprogrammering-Examples as github URL
3. Create a course version and add 7 Moments with some few random elements sprinkled in. …
=> Adding a github repo to a Moment should now spawn the items right under it.  #15319

DuggaSys/courseed.js, DuggaSys/courseed.php, DuggaSys/courseedservice.php
Made the delete feature work again as it was reverted in the merge.
see #15540 for more detailed information.
**testing:**
- go to the main page and click edit on a course
- click delete and see if everything is deleted as it should
=> Fix functionality to delete a whole course

DuggaSys/courseed.js, Shared/css/style.css
Copied from #15635
`$(messageElement).stop(true, true);` does not exist in other form validations and seems to be very useful in stopping spam causing repeat fade-ins and -outs
Affected forms: Edit Course and New Course in courseed.php (quickValidateForm in courseed.js)
Extra:
* Added an neutral class for when optional fields are empty.
Note that the save button does not get disabled due to it currently being dynamic.
=> reFixed dialog fade in/out g3-2024-v6-#15614

DuggaSys/courseed.js
Courseed.php has not been reloading after creating a new course for some time now. To fix this, i added location.reload() to createNewCourse(). This location.reload() is inside of a setTimeout() to give the site enough time to save the new course. 
To test this, just create a new course and see if the site reloads and that the new course appear in the list.
=> Added an location.reload() to createNewCourse() to #15837

newinstaller/tools/configuration_manager.php, newinstaller/tools/install_engine.php
Now the installer should be working to install the system, beware before running it, that if everything works properly, the current db will be overwritten. See settings in `LenaSYS/newinstaller/installer_ui.php`.
1. Set the proper root authentication settings in `LenaSYS/newinstaller/tools/install_engine.php`
3. Navigate to [LenaSYS/newinstaller/installer.php](http://localhost/LenaSYS/newinstaller/installer.php).
4. Navigate to [LenaSYS/courseed.php](http://localhost/LenaSYS/DuggaSys/courseed.php).
Note: I renamed credentials_manager to configuration_manager as it could be used to store more than just database credentials.
=> Now saving db credentials when running installer

backend-models/microservices/duggaSys services/Microservices.md
This microservice does makes a query to the database to retrieve listentries with visible = 3.
It never uses the result in the current state. Furthermore retrieveSectionedService already returns all listentires, which includes those mentioned. To retrieve all listentries the microservice getListEntries may be used instead. This makes the getDeletedListEntries microservice redundant.
=> G2 2024 v7 issue#15515

DuggaSys/diagram.js, DuggaSys/diagram/camera.js
Now it is possible to center the camera when there is no element on the screen. Can test it by have element on the screen and press the reset button to see if the camera is on the default position or not (it should only remove all the element). And if there is no element on screen then you should be able to center the camera to default position.
=> G1 2024 v6 #14235

DuggaSys/darkmodeToggle.js
The drawswimlane function were called then toggling between night and day mode, the function is now gone from pages where it does not need to be called and should not appear as a error in the console anymore. 
Function:
drawSwimLane()
Error in the console before: 
'drawswimlane is not defined'
=> Drawswimlane error gone

DuggaSys/codeviewer.js
Implemented keyup event for esc.
Integrated a check if popups are open in codeviewer.
Should work on all popups.
For testing:
Problem when pressing esc while previewWindow loginBox is open.
Its container "previewWindowContainer loginBoxContainer" is set to none while "previewWindow loginBox" is still not changed from block to none. Circumvented this in this pullrequest but this will be looked into in another issue.
=> Remerge after revert

DuggaSys/microservices/sectionedService/retrieveAllCourseVersions_ms.php, DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
The `$debug` parameter has been made mandatory in the function retrieveSectionedService.
=> G2 2024 v7 issue#15891

DuggaSys/diagram.js
added a check to make sure that data isnt empty before trying to autosave, this stopped the error message from appearing
=> fixed "You don't have anything to save." appearing when reloading/leaving the site when you havent added anything to the diagram #15527

DuggaSys/duggaedservice.php, DuggaSys/microservices/duggaedService/retrieveDuggaedService_ms.php, DuggaSys/tests/duggaedService_test.php, DuggaSys/tests/microservices/duggaedService/createDuggaVariant_ms_test.php, DuggaSys/tests/microservices/duggaedService/deleteDuggaVariant_ms_test.php, DuggaSys/tests/microservices/duggaedService/deleteDugga_ms_test.php, DuggaSys/tests/microservices/duggaedService/updateDuggaVariant_ms_test.php
Removed the $variants output from duggaedservice.php and retrieveDuggaedService_ms.php and updated all tests using it to instead use the $entries array. 
Deleting the $variants variable should not break any systems since it was not used for anything other than testing, I added it a few weeks ago to make tests work before double nested arrays were possible in the testing API.
=> G2 2024 v7 issue#15856

DuggaSys/tests/microservices/sectionedService/reorderListEntries_ms_test.php
**Note: ** This test fails if any new listentries has been added to Testing-Course. This is because the json used has to compare all listentries (it's not possible to just pick the ones we are modifying in the microservice)
=> G2 2024 v6 issue#15694

DuggaSys/sectioned.js
I don't think the "undo" button not working is our group's problem. There seems to be some code in sectioned.js which is supposed to handle undoing by using classes, arrays, and timers.
I changed sectioned.js to use deleteListEntries instead of removeListEntries, which fixes the deleting issue. Unless I am misunderstanding something I think deleteListEntries is actually the correct microservices to use. But then I am not sure what removeListEntries should be used for.
It's almost like 2 different groups had different ideas on how to implement the "undo" function and implemented both at the same time.
See issue comments for more information.
=> G2 2024 v7 issue #15908

DuggaSys/fileed.js
d22mikwe
Collaborator
[d22mikwe](https://github.com/d22mikwe) commented [last week](https://github.com/HGustavs/LenaSYS/pull/15560#issue-2288509174)
Fixed current iteration of keyup for esc and control.
Integrated current filePreviewClose() call when pressing esc and popup is open.
Integrated a check if popups are open in this eventlistener.
Current popups are when adding a file, previewWindow (Edit file icon) and fileViewPreview (clicking on the file name).
Added intended integration with "x" key. this was not implemented but previous devs had intended for it.
Also fixed previous indentation.
For testing:
If a popup is not open it should redirect to …
=> Added ESC button to go back in fileed.php

DuggaSys/duggaed.php
It turned out to be more simple than I thought. session.start() was missing in duggaed.php.
Login now stays when going into duggaed and through a refresh.
=> Added missing session_start() #15760

Shared/dugga.js
I wasn't able to find where the OPT was used, so the microservice hasn't been implemented. Instead, only the relevant case has been added.
=> G2 2024 v7 issue #15961

DuggaSys/courseed.js, DuggaSys/courseed.php
Added eventlistener and also added tabindex to make the surrounding div focusable. If a user clicks somewhere inside the form and isn't focused on an actual input field, the eventlistener wouldn't trigger. Adding tabindex makes the entire div focusable, which makes the eventlistener active.
=> Added keypress functionality to creation of new course

DuggaSys/sectioned.js, DuggaSys/sectioned.php, Shared/css/style.css
This pull is mostly due to unnamed body and footer divs which could cause confusion. The divs are now properly named and will be reported in the [wiki](https://github.com/HGustavs/LenaSYS/wiki/Popup-form-conventions#currently-known-popup-forms-on-lenasys)
Extra:
* Added more conventional headline for the Github repo form
* Did not touch 'Choose Template' because it appears to be dynamic and uses tables.
* Fixed missing body elements and moved some elements
* Fixed misaligned cancel button which became visible with these changes.
* Slight adjustments to some sizes and paddings.
Note: These changes are needed to be in forms in other files, but it is currently not possible yet due to merge conflicts. So only sectioned.php is affected in this pull request.
=> Added classes formBody and formFooter

DuggaSys/microservices/accessedService/updateUser_ms.php, DuggaSys/tests/microservices/accessedService/updateUser_ms_test.php
Both the test and the microservice was updated.
I had to change ```$username = getOP('username');``` to ```$username = getOP('user_name');``` in the MS because of duplicate entries in the service-data. In the monolith they get around this by using ```$val``` instead of separate variables like ```$firstname```.
I wasn't able to find any frontend use for the microservice, but it's possible that further changes need to be made because of the name change.
Perhaps the MS should use ```$val``` instead? I assumed the way it was implemented is how it's supposed to look, so I didn't change it to use ```$val```.
I also added an OPT, but I don't think anything more needs to be changed regarding that since the microservice hasn't been integrated.
=> G2 2024 v7 issue #16056

DuggaSys/diagram/draw/options.js
the ID being passed to the button was `id='lockbtn'`, so the ID the button got was `id="id="`, which caused it to not be found by the toggle function
=> fixed the id on the lock button

Shared/navheader.php
A white space has been implemented for the paragraph to break. 
Other functions have been implemented, but white space is the only one to have an effect. 
Click on the icon for the hover to apear, inside the hover- check that the paragraph breaks and DO NOT go outside the dropdowns whitelane. 
Screen of how the hoover looked before p break:
Should look now:
=> whitespace tag for the break to work

DuggaSys/accessed.php
Moved the "First Name" label to the correct place since it was in the header element previously. To access this, go into a course and press the keylock button. This is what it looked like before:
And this is what it looks like now:
=> Moved the "First Name" label to the correct place

DuggaSys/accessed.php, DuggaSys/codeviewer.php, DuggaSys/codeviewerService.php, DuggaSys/contribution.php, DuggaSys/courseed.php, DuggaSys/diagram.php, DuggaSys/diagram_IOHandler.php, DuggaSys/fileed.php, DuggaSys/microservices/sectionedService/readCourseGroupsAndMembers_ms.php, DuggaSys/profile.php, DuggaSys/pushnotifications.php, DuggaSys/resulted.php, DuggaSys/sectioned.php, DuggaSys/tests/duggaedService_test.php, DuggaSys/tests/fileedService_test.php, Shared/loginlogout.php, Shared/resetpw.php, errorpages/404.php, testingdb/testingdb_setup.php
I have removed the include of "coursesyspw.php" at the top of files that already includes "sessions.php". 
I checked if this broke anything by navigating to the part of the sites that is still used in LenaSYS. Tests and files like e.g. codeview.php still works without any issues.
=> G2 2024 v7 issue#16092

Shared/css/blackTheme.css
There was a margin on the select element, that has been removed. There was also a background color not using the predefined color variables. I guess it's used for something, but it was applied to the formBox select as well, so I removed that. It seems to be working fine.
I suspected the loginbox might have had consequences, but it didn't. It looks like it dide before the changes.
When editing a course. Det dropdown should now be aligned with the rest of the inputs.
=> Updated blacktheme.css (#16076)

DuggaSys/accessedservice.php, DuggaSys/codeviewerService.php, DuggaSys/contributionservice.php, DuggaSys/diagramservice.php, DuggaSys/duggaedservice.php, DuggaSys/fileedservice.php, DuggaSys/highscoreservice.php, DuggaSys/microservices/highscoreService/highscoreservice_ms.php, DuggaSys/profileservice.php
```$userid``` was changed from "1" to "guest" in several php files. To make this work, ```checklogin()``` had to be added before setting ```$userid```.
Markdown files were not changed.
=> G2 2024 v7 issue #16096

DuggaSys/resulted.js, Shared/css/blackTheme.css, Shared/css/style.css
Added styling to dark theme for hash links. since they did not appear with good enough contrast previously. To access this go to a course and then edit student results. In light mode it looks like this:
And in dark mode the hash link has now been modified with a lighter color for readability:
=> Added styling to dark theme for hash links

DuggaSys/sectioned.js, DuggaSys/sectionedservice.php
The Name input is now updated to the list entry name and the codeexample name.
Testing:
Create a new code example.
Fetch a file/files from the github icon.
Click Save.
The Name input should now be displayed as the list entry name and code example name.
Title is also updated (codeexample name)
This can be doublechecked in the db table "listentries" and "codeexample"
=> Make Name input change the codeexample name #15231

DuggaSys/microservices/fileedService/deleteFileLink_ms.php, DuggaSys/microservices/fileedService/getFileedService_ms.php, DuggaSys/tests/microservices/fileedService/deleteFileLink_ms_test.php, Shared/dugga.js
The microservices have been integrated. See dugga.js at ```kind=="FILE"```.
I tried creating getFileedService_ms.php, however I couldn't get it to work. I didn't want to broaden the scope of this issue too much so it will be looked at in another issue. Because of this the "GET" opt still uses the monolith.
You can test the integration by going into a course, clicking "show files" in the toolbar (the plug icon), and then updating and deleting files. All different kinds of files/links should work correctly (global, etc).
=> G2 2024 v7 issue #16105

DuggaSys/sectioned.js, Shared/toast.php
just before when you would press ESC you would be transported form sectioned.php to courseed.php when closing these popups with ESC, get canvas link, settings (JS-TEST template 3) and settings (JavaScript-Code) In the issue description it wasn't mentioned which specific popups this happened to but these three popups were however found and fixed.
=> fixed ESC button when closing modals in sectioned.php

DuggaSys/diagram/draw/element.js
Text in the UML super state and note elements are fixed to fit within their containers
Taken from the old pull request #16264, and fit with the updated version for 2025. The text in "note" and "UML super state" are fixed to be able to handle longer text . The note element adjusts to fit the content without overlapping the borders, and the UML super state ends with an elipsis ("...").
=> Solution for text not fitting in the "note" and "UML super state" elements 

DuggaSys/diagram/draw/element.js, Hello World
The upper part of the SD entity did not have the class that gives each entity some of their properties, so the color of the line did not change properly when switching to dark mode.
The upper line of the SD entity now works the same as the other elements.
https://github.com/user-attachments/assets/fd23e515-db98-4af6-85bb-d04e8f3722e8
=> Added class to upper part of SD entity

DuggaSys/diagram/draw/node.js
When creating the nodes to all elements there was a if statement that made sure the start/end elements did not get nodes. when the new corner nodes were added, the creation of the corner nodes was placed outside of this if statement. this is now fixed by adding the corner creation to the inside of this if statement.
=> added the corner node code to the start/end if statement

DuggaSys/diagram.js
The issue was that when dragging the nodes, they would jump while being dragged. Initially, the element would change its position based on the start and end point of a mouse click-and-drag event, causing the element to jump to where the mouse was at the start. This behavior has now been modified to depend on the delta movement of the mouse, preventing the element from jumping.
=> Fixed Resizing with upper nodes on elements weird

DuggaSys/sectioned.js, Shared/css/style.css
Added logic to the styling and grouping, along with necessary class and CSS. This is based on the assumptions made from the prod version of canvas. Essentially, a header seems optional and a section seems to be used within a moment.
The added logic does the following:
1. Every header div except the first one gets a top margin
2. Every row div gets a left and a right border
3. Every moment div that isn't preceded by a header gets a small top margin
4. Every row div that precedes a moment div but isn't a header gets a bottom border
5. Every row div that precedes a header row also gets a bottom border
6. The very last row div in the array gets a bottom border
7. Every row div except for the header gets a class for shorter width
This will give us a box-like interface where a header is …
=> New styling and separation of groups in Sectionlistc (#16179)

DuggaSys/diagram/draw/element.js
I modified how the "splitFull" function was used and adjusted the maximum number of characters per line because "MaxCharactersPerLine" allowed too many characters for the IE entity element.
=> Fixing the primary key problem

DuggaSys/sectioned.js, DuggaSys/sectioned.php, Shared/css/style.css
Copying code from pull request  #16183 for issue #16181 to new branch to be merged later.
There issue was to fix the Eye button so you could hide the viability of crossed over tests.
And from what I've tested it does its job.
=> Moving code from Pullrequest #16181 

DuggaSys/diagram.js
Fixed the smoothness of the modeling page by removing the debounce function that slowed down the page and making everything slower.
=> Brought back the smoothness of the modeling page

DuggaSys/diagram/theme.js
issue #16224.
Elements no longer jump when 'snap to grid' is active. Replaced hardcoded condition for EREntity with all different element type check. Changed also the top position calculation to stop elements from jumping when clicked in 'snap to grid' mode.
=> Updated theme.js

DuggaSys/diagram/draw/line.js
The selection box for a recursive arrow had too large of a margin to the left of the arrow before, now sits flush with the arrow.
=> Fixed too large selection box for a recursive arrow.

DuggaSys/diagram/draw/element.js
The problem was that the objects Z value where set to low to be able to appear above when hovering as ghost.
Setting these values to 2 seems to have fixed it.
=> G1 2025 v2 issue #16196 elements ghost hover behind

DuggaSys/diagram.js
When clicking a line and choosing the same element it will now make an arrow from and to the element. It is also made so that if no second element is chosen, that line will be destroyed.
[Screencast_20250410_101319.webm](https://github.com/user-attachments/assets/37773e4e-753e-444a-85fa-92b291598df3)
=> Fixed recursive line adding to elements

DuggaSys/microservices/Microservices_inverse_dependencies.md
No include logUserEvent_ms.php exist in the microservices files. Fixes issue #16384
=> Updated microservices_inverse_dependencies

DuggaSys/sectioned.js, DuggaSys/sectioned.php
A small feature was added that allows the user to change how the section list is displayed. The user can switch between:
- Normal (default view)
- Scroll (limits height and adds internal scroll)
- Overview (zooms out to give a bird's-eye view of all items)
=> Added a view mode toggle (Normal / Scroll / Overview)#16185

DuggaSys/diagram/draw/element.js, DuggaSys/diagram/helpers/element.js
Fixed issue where the text in the ER-entity does not format properly. Update ensures that the text spans across multiple lines rather than the previous single line where the text ended up out of bounds of the element.
=> ER-entity text does not format properly

DuggaSys/diagram.js, DuggaSys/diagram/defaults.js, DuggaSys/diagram/draw/element.js, DuggaSys/diagram/draw/node.js, DuggaSys/diagram/draw/update.js
**This element wasn't created with the purposes of being resizable, so an amount of reworking of the element had to be made for it to be possible to resize.** 
Nodes were added to the element to allow resizing, and special functionality for this specific element was added so that it would resize properly, without leaving vertical empty space when the height was increased. Only corner resizing is allowed for this element since it's implemented as half a circle, which made for errors when trying to only manipulate height/width. Most likely possible to add separate manipulation of height and width but that would require a lot more changes to the element and how it works.
Base size shape before resizing, with nodes:
Shape after resizing, with visible nodes and size comparison with base size: …
=> [Issue #16216] Implemented functionality for resizing IE Inheritance elements

DuggaSys/diagram/draw/update.js
Update update.js
Changed the x coordinate value of the A4 text to only move a little bit but always stay close to 0,0 like the corner of the A4 outline.
=> Fixed A4 text to align with the corner of the A4 outline

DuggaSys/microservices/Microservices_inverse_dependencies.md
Documentation for the inverse dependencies for the microservice editBoxTitle_ms.php.
No inverse dependencies where found. Fixes issue #16442 .
=> Documentation inverse dependencies for editBoxTitle_ms.php 

DuggaSys/diagram/draw/element.js
Fixed the issue with the text in the header not fitting the element width. Adjusted the "Header"-portion of the updateElementUMLEntity-function to create line-breaks if the text is wider than the entity. Text no longer goes out of bounds.
=> Updated UML-entity header-text

DuggaSys/microservices/Microservices_inverse_dependencies.md
Fixes #16446, documented inverse dependencies for retrieveCodeviewerService_ms.php in Microservices_inverse_dependencies.md
=> Documented inverse dependencies for retrieveCodeviewerService_ms.php

DuggaSys/diagram.php
Changed the value from 0 to 1, since there is no element matching "0" of "type 1" in the togglePlacementType() function. As a result, the menu disappeared. But when "1", there is a match and the ER relation element stays and the menu remains.
**Before:**
https://github.com/user-attachments/assets/a6ce4d11-76bd-4d62-a893-c633c0d86d81
**After:**
https://github.com/user-attachments/assets/8586f5da-7412-4f0f-88b2-d301853d6020
=> Fixed ER relations disappear

DuggaSys/microservices/Microservices_inverse_dependencies.md
Fixes #16460, documented no inverse dependencies for updateCourseVersion_ms.php in Microservices_inverse_dependencies.md
=> Documented inverse dependencies for updateCourseVersion_ms.php

DuggaSys/diagram/draw/line.js
The recursive line is now able to be modified with arrows. The cardinalities, label and changing to dashed is still broken.
State diagram states are a bit broken because it wants to do a straight line when the recursive relation line is a segmented one (changing the line to segmented fixes this). A fix might be to make recursive lines a segmented line directly when created on a state.
[Screencast_20250411_113443.webm](https://github.com/user-attachments/assets/e1a3298d-801c-4f54-8949-b81342d871c9)
_The recursive line now supports different arrows_
=> Fixed recursive arrows #16370

DuggaSys/diagram/draw/element.js
Example state diagram is now fixed, lines and elements now load correctly without any problem
=> G1 2025 v2 #16191 the example diagrams doesnt load correctly

DuggaSys/diagram.js
Elements could previously be pasted on top of each other, as shown in the picture below.
The entityIsOverlapping() method, which detects entity overlaps, has been added to the pasteClipboard() method. This allows the parent function to flag the overlap, deny pasting and notify the user. Trying to paste objects on top of eachother will result in an error as shown in the picture below.
=> Implemented overlap-detection for pasting elements.

DuggaSys/diagram/draw/options.js
removed the ability to add lables to lines between ER elements, labels are still available to other lines. 
the solution was to remove 
"str += includeLabel(line);"
from the ER case in drawlineproperties in options.js
=> komplettering b22jonan 15751

DuggaSys/diagram/draw/line.js
Added the line offset value to the from x, to x, from y and to y values before the cardinality is added.
=> Fix for issuie #15036, overlapping cardinalities on UML

DuggaSys/diagram.js, DuggaSys/diagram/events/mouse.js, DuggaSys/diagram/helpers/mouse.js
**helper/mouse.js:**
Extracted ghost-snapping logic into a reusable function: snapElementToLifeline(element, targetId) to allow both ghost elements and placed elements to snap to the center of the nearest lifeline.
snapSAToLifeline() still handles ghost snapping on hover, but its logic now matches the real element snapping logic more closely.
When placing a new element (placeElementAt(x, y)), the code creates a new element, finds the nearest lifeline using findNearestLifeline(x, y) and snaps the element to that lifeline before adding it to the diagram.
**events/mouse.js:**
Modified the mouse release (mouseup) behavior. If elements were moved (context.length > 0), each is snapped to the nearest lifeline after release using the same snapElementToLifeline() logic.
Uploading Inspelning …
=> G1-2025-v2-#15647 snap to lifeline or object after placement

DuggaSys/diagram/draw/element.js
Fixed issue with the text in the header getting clipped if it is longer than the entity is wide - the text now fits within the header even if it is longer than the entity is wide.
=> Text in header no longer gets clipped

DuggaSys/microservices/Microservices_inverse_dependencies.md
getCourseed is never used as an include. In the Microservices.md it say getCourseed has been replaced with retrieveAllCourseedServiceData
fixes #16454
=> Documented getCourseed in Microservices_inverse_dependencies

DuggaSys/microservices/Microservices_inverse_dependencies.md
Are not used anywhere. getCourseGroupsAndMembers has been replaced with readCourseGroupsAndMembers, and getCourseVersions has been replaces with readCourseVersions.
fixes #16595
=> Documented getCourseGroupsAndMembers_ms.php AND getCourseVersions_ms.php

DuggaSys/diagram/helper.js
Solved the hitbox issue for the ER Relation element. Its angled side can now be placed closer to other elements without the collision detection kicking in to reject its position.
https://github.com/user-attachments/assets/5e5002b9-21fb-453b-82aa-14c6e09843fb
=> G1 2025 v2 #16455 the hitbox for some object does not match the object it self

DuggaSys/microservices/Microservices_inverse_dependencies.md
getListEntries is not used anywhere, but is supposed to be replaced with retrieveAllSectionedServiceData, but that file does not exist. getuserDuggaFeedback is not used, is replaces with readUserDuggaFeedback
fixes #16598
=> Documented getListEntries_ms.php AND getUserDuggaFeedback_ms.php

DuggaSys/microservices/endpointDirectory/nameQuery.php
Added a database connection to name query, now correctly checks database for data.
To test open /endpointDirectory/EndpointDirectory.php and add ?name=example_ms at the end of the url.
Need to install db and fill with data first.
This error is normal and will be fixed by another issue.
Fatal error: Uncaught Error: Call to undefined function render() in C:\xampp\htdocs\LenaSYS\DuggaSys\microservices\endpointDirectory\endpointDirectory.php:32 Stack trace: #0 {main} thrown in C:\xampp\htdocs\LenaSYS\DuggaSys\microservices\endpointDirectory\endpointDirectory.php on line 32
fixes #16570
=> Connect name query to database - Issue #16570

DuggaSys/diagram/classes/stateChange.js
An old check in stateChange.js was blocking IE-relations from saving changes to inheritance type. It was meant to avoid issues with a now-removed dropdown.
That check is no longer needed and has been removed. IE-relations can now switch between disjoint and overlapping as intended.
https://github.com/user-attachments/assets/2e40ac96-d32f-4bf3-87f5-02aca0b46563
=> Updated stateChange.js

DuggaSys/sectioned.php, Shared/css/style.css
I have removed the three different view buttons from the DOM for screens smaller than or equal to 570px. I have also moved the related styling to the external stylesheet and improved the semantics of the elements.
=> G3 2025 v2 issue #16612 remove view buttons from mobile screens

DuggaSys/microservices/Microservices_inverse_dependencies.md
Updated Microservices_inverse_dependencies.md with inverse dependencies for updateListEntriesTabs_ms.php AND updateListEntries_ms.php. None found. Fixes issue #16664 .
=> List inverse dependencies for updateListEntriesTabs_ms.php AND updateListEntries_ms.php

DuggaSys/diagram/constants.js, DuggaSys/diagram/helper.js
The problem was fixed by explicitly ensuring that the COPY and PASTE events do not have meta as true but false.
Fixed this issue #16658
=> Fixed: Copy pasting is no longer working in the diagram site.

DuggaSys/microservices/Microservices_inverse_dependencies.md
Updated Microservices_inverse_dependencies.md with inverse dependencies for updateListEntryOrder_ms.php AND updateQuizDeadline_ms.php. None found. Fixes issue #16666 .
=> Update Microservices_inverse_dependencies.md for updateListEntryOrder_ms.php AND updateQuizDeadline_ms.php

DuggaSys/microservices/endpointDirectory/directoryRendering.php, DuggaSys/microservices/endpointDirectory/endpointDirectory.php
Fixes #16522, now you get a markdown/html (html conversion can be added later) output of the relevant microservice documentation (from the database). Also removed debug outputs for less clutter and easier testing. The searchable parameters include: name, description and parameter, these are the ones that should be used when testing. More parameters can be added later if requested.
=> Fixed microservice endpoint output format

DuggaSys/diagram/draw/line.js
This issue seems to have stemmed from duplicate code being added during the merge to the weekly branch. The function getLineAttribute had been updated in between the opening of the merged branch and the merging of the branch, which caused duplicate code to get added that didn't align with how the updated function worked, breaking before it could return the correct values for the left side, causing all lines to stop updating if lineDirection.LEFT was true. 
That issue may mostly have been my fault, since it was my code that got added that messed up the function and was outdated - most likely due to not fetching origin or something of the sort, so apologies for that.
The lines should now work as intended again.
=> [#16669] Fixed issues with lines not updating when moving to left side

newinstaller/installer_ui.php, newinstaller/tools/components.php
Added 'root' as the default pre-filled username in the new installer. The `$inputValue` parameter is set to an empty string by default, ensuring no impact on other input fields. 
`htmlspecialchars()` is used to prevent XSS vulnerabilities.
Also fixed som faulty indentation I came across in the files.
Fixes issue #16634
=> Pre-filled root username with 'root' in new installer

DuggaSys/sectioned.js, Shared/css/style.css
This is a retread of a previous PR that did not get implemented before the weekly merge. 
Unnecessary white space have now been removed. I have left the white space between the header, course title and load dugga heading. I have only changed styling for mobile screens (width <= 570px). A separate issue for white screen on desktop will need to be created. I have also changed some HTML and moved inline styling to the external stylesheet. More courses is also visible on mobile devices now per the request, although this feels a tad bit excessive for mobile platforms. 
Future issues include reviewing the different SectionList ID's, small course names and egregious use of inline styling as well as creating tables correctly.
=> G3 2025 v2 issue #16348 white space on mobile devices

DuggaSys/diagram.css
Update diagram.css
Changed the position of options tooltip.
Before:
After:
=> Fixed the tooltip for options panel

DuggaSys/diagram.css
he task bestowed upon me is now complete.
I have removed right: 0; from the tooltip, as it caused the text to hide behind the toolbar. In its place, I added left: 0;, which ensures the tooltip appears correctly—spaced out and visually distinct from surrounding elements. If change is demanded for better UI then i shall make it so.
before:
after:
The code awaits your judgment.
=> 16617 fix the tooltip for scaling panel

DuggaSys/microservices/Microservices_inverse_dependencies.md
Documented inverse dependencies: deleteFileLink_ms.php and getFileedService_ms.php, found no inverse dependencies for neither of them. 
Fixes #16727
=> Documented inverse dependencies: deleteFileLink_ms.php AND getFileedService_ms.php #16727

backend-models/microservices/duggaSys services/Microservices.md
Previous documentation said updateOrder should replace reorderListEntries, but it is supposed to be updateListEntryOrder. Changed the documentation from updateOrder to updateListEntryOrder, since updateOrder was incorrect.
Also, reorderListEntries and updateListEntryOrder contain the exact same code, reorderListEntries should be completely replaced with updateListEntryOrder and then removed (?).
=> Corrected the documentation of reorderListEntries/updateListEntryOrder

DuggaSys/diagram/events/mouse.js
There are two different mouseDown events that both check for clicks on the delete button but according to documentation one is for sole elements and the other is for deletions of multiple selected elements. Both called the _checkDeleteBtn()_ function that has a flag which is toggled between true and false if the conditions for a deletion are appeased. The problem seemed to be that one of the calls never toggled the boolean flag back to true and thus creating problems on every deletion except the first where the flag was initially true. The inconsistency of whether the class element was erased alongside the line might have been some kind of race condition, where the function with the actual flag toggle accidentally got through, that stemmed from the defective code. Hopefully this is now …
=> Hopefully solution for disappearance of object elements when deleting attached lines

DuggaSys/microservices/Microservices_inverse_dependencies.md
Fixes #16729, no found for fetchOldToken, one for clearGitFiles.
=> Documented inverse dependencies for clearGitFiles and fetchOldToken.

DuggaSys/diagram/draw/line.js
The solution was to remove a misplaced comma in the iconPoly function so the points for polyline dont get any unexpected attributes and it follows the correct syntax for declaring the points.
Fixed this issue: #16742
=> Fixed: Fix so you do not get a lot of errors in the when loading up the example diagrams

DuggaSys/microservices/Microservices_inverse_dependencies.md
Fixes #16752, no inverse dependencies found for either.
=> Documented inverse dependencies for getGithubURL and getIndexFile.

DuggaSys/microservices/Microservices_inverse_dependencies.md
Documented inverse dependencies for insertToFileLink_ms.php and insertToMetadata_ms.php. None found. Fixes issue #16753.
=> Documentation inverse dependencies for insertToFileLink_ms.php and insertToMetadata_ms.php

Shared/css/style.css
Issue has been fixed by simply using the table row colour variables rather than the high constrast on only odd rows.
See results
=> #16467 fix darkmode by using colour variables on even & odd table rows

DuggaSys/microservices/Microservices_inverse_dependencies.md
Document inverse dependencies: highscoreservice_ms.php and retrieveHighscoreService_ms.php, found one inverse dependency for retrieveHighscoreService_ms.php. 
Also discovered that highscoreservice_ms.php is not in use anymore. It's commented out in the code in dugga.js.(highscoreservice.php is used instead).
Fixes issue #16754
=> Documented inverse dependencies: highscoreservice_ms.php AND retrieveHighscoreService_ms.php #16754

DuggaSys/diagram/draw/element.js
The actor element had a zLevel = 2; and the activation element didn't have any zLevel.
I added zLevel = 3; to the activation element to always be above the actor.
=> Fixed activation element in sequence diagram always is above actor

DuggaSys/JSON/UMLDiagramMockup.json
The solution to this problem was to change the JSON file for the UML Mockup diagram, removing the text from start- and endIcon and adding the corresponding cardinality to start- and endLabel.
The cardinalities should now be in the UML format and values should be correct as well.
**Known Issue:** I personally had some issues getting the JSON file to reload with the new updated data, which seems to be a browser cache issue or something of the sort, not properly reloading the JSON file since it already existed in the cache. I managed to get the new data to show by opening up the website in incognito mode, and also outside of incognito after restarting my pc with some additional hard browser refreshes after that.
**UML Mockup diagram with updated cardinalities:**
=> [#16631] Fixed UML example diagram using icons instead of cardinalities

DuggaSys/diagram/helper.js
The program now correctly prohibits the user from copy pasting elements on top of each other if the element has a label.
_before_
https://github.com/user-attachments/assets/da688d1e-5b23-426f-8cdc-66fb3a023b19
_after_
https://github.com/user-attachments/assets/0519878a-6109-4a59-a0df-caabf65a9a22
=> Fix for copypasting elements with labels #16542

DuggaSys/diagram/draw/options.js
Issue is now fixed, refreshing is not needed anymore, the ER or test case toggle does no longer get stuck once clicked, when they are clicked and an element afterwards is placed, selecting the pointer and clicking on the element will show **that** elements properties in the right options panel, and when deselected the regular options panel is shown. See Fixed version video below.
**Master:**
https://github.com/user-attachments/assets/9bc05afe-93cd-49a5-9d95-14e6991a0c82
**Fixed version**:
https://github.com/user-attachments/assets/bfa8f9c7-44c4-4def-a53d-d112718c5582
=> Options table fix

DuggaSys/diagram/draw/line.js
Solution for issue [#16588](https://github.com/HGustavs/LenaSYS/issues/16588) 
Moved the recursive line to now instead be on top of the element and in the right corner.
The lines should now also always stick to the corner when the element is re-sized to keep out of the way.
[Screencast from 2025-04-22 10-13-21.webm](https://github.com/user-attachments/assets/537eff61-bef2-4ab7-9645-b4b12945789d)
=> Fix for the multiple lines overlapping with the recursive line 

DuggaSys/diagram/draw/element.js, DuggaSys/diagram/draw/options.js
Added a function that escapes strings with html-characters to normal string characters. Attempts to insert html code now simply inserts that code as strings instead. 
_The tag <script...> that would have previously be handled as code is now simply displayed as a string. This can also be seen in the console_
=> Sanitized inputs #16782

DuggaSys/diagram.php, DuggaSys/diagram/draw/update.js
The A4 template title text scaled with zoom before. This added patch makes the title text static, which effectively solves the target issue. The aim for the issue was to make the title text static, since the A4 template size was static, the fix involved copying the code that scales the A4 accordingly with the current zoom-factor, and applying it in a similar manner to the text element.
0.5x zoom:
2x zoom:
=> A4 template title text size is now static

DuggaSys/diagram.js
The solution was to place back the if-statement that sends the keybinds of toggle_error_check and if it is true then it executes the toggleErrorCheck() function. 
Fixed the issue: #16818
=> Fixed: You can't toggle the error check using its keybind

DuggaSys/sectioned.js, DuggaSys/sectioned.php, Shared/css/style.css
And changed so the text in css for #svimlaneSVG is 1em, which will make the font change size dynamicly based on parent element. 
(Also removed an unnecessary <style>-tag in style.css since it gave me an ulser)
- Need to make a new issue for fixing on mobile! 
Old swimlanes
New swimlanes
=> fixed so weeks are 'taller' in sectioned.js

DuggaSys/microservices/Microservices_inverse_dependencies.md
Updated document with found inverse dependencies.
loadDugga had an inverse dependency inside of an if-statement in retrieveShowDuggaService_ms.php.  
Fixes issue #16793
=> Inverse dependencies: getShowDugga_ms.php & loadDugga_ms.php

DuggaSys/diagram/constants.js, DuggaSys/diagramkeybinds.md
The solution was to alter the keybind for toggling the keybind list by changing ctrl from false to true. So, when you press f1 + ctrl, then the keybind list should toggle. Also changed the instruction on keybind list document so the keybind matches with the list. I have also tested the remainder of the keybind. 
Fixed the issue: #16848
=> Fixed: The keybinding for toggling the keybind list is not working

DuggaSys/diagram/helper.js
The issue where ER and UML elements could overlap is now fixed by updating helper.js file. The issue was that ER relations and UML inheritance was using a custom center-point overlap check inside the function entityIsOverlapping(), which wasn't reliable when detecting collisions with other elements. This caused them to be placeable on top of UML classes, IE entities, and SD states unlike other elements which correctly triggered an overlap error.
The issue was fixed by removing the custom center-based logic and applying the same collision detection method used by all other elements. So the elements stated in the issue that could overlap, can't anymore either. .
=> Fix for overlapping elements

DuggaSys/sectioned.js
The issue was that the jquerycode that was responsible for the drag and drop feature had been commented out, removed the comments so now it works again, it does however need to be rewritten in javascript but that is a separate issue
=> Removed broken comment

DuggaSys/diagram.css, DuggaSys/diagram/draw/line.js
By changing the line spacing between the lines, you are now able to zoom out and in without the it looking too messy. Especially when zooming out, the lines no longer deattaach from the source and target object.
=> Fixed the lines between objects when zooming in andor out

DuggaSys/diagram/draw/element.js, DuggaSys/diagram/draw/line.js
The line anchoring points for the IE-relations were previously calculated by the height and width of the element. Due to the curvature and smaller size of the element inside, it appeared as if the lines didn't connect to the actual element, but instead floated mid-air. This has been corrected so that the lines now connect to a set of adjusted coordinates within the IE relation shape, which makes the lines visually connect to the IE-relation. 
Before. Line endings floating mid-air:
After. Corrected anchoring points and lines connect to the element:
=> Corrected IE relation line anchoring points

DuggaSys/diagram.js
Implemented the ability to scroll on the grid/canvas with touch. Added events in _**diagram.js**_ that listens to events caused by a touch input. _**tmoving**_ function is handling the movement of the finger touch and the _**tstart**_ function is storing the start position of the finger.
_There is still more functions that has to be adjust to touch but this will be handled in other sub-issues related to the mobile implementation of the diagram tool._
**Before:**
_(No ability to use touch to scroll on canvas)_
https://github.com/user-attachments/assets/2c52eb53-576c-4d20-8990-ad2cf9417446
**After:**
_(**New feature!** Ability to scroll on canvas)_
https://github.com/user-attachments/assets/f0ae3339-5009-441b-984a-387b410cc5ba
=> 16836 implement scrolling the canvas in the mobile version

DuggaSys/diagram/draw/line.js
Solution to #16869
Fixed so that when cardinality values are added to a line, they no longer effect the positionering of that same lines label.
Previously cardinality added offset the fils global variables fx, fy, tx and ty. Now instead its a self contained variable just for cardinality. 
https://github.com/user-attachments/assets/9d897d94-8e0e-4c0e-9d7b-05e83f1a9e02
=> Line labels now dont move when cardinality is added

DuggaSys/diagram.php
All element/entities keybinds are now updated to be consistent. 
_**How it looks as of this fix:**_
The previous solution where every entity had their own tooltip-name (such as "_tooltip-PLACE_ATTRIBUTE_") was not working as these tooltips seem to not exist since they generate no keybind. 
To fix this all elements on the same row use the same tooltip to make sure that the correct keybind is generated. For example, switching them from "_tooltip-PLACE_ATTRIBUTE_"  to "_tooltip-PLACE_RELATION_" might make it less clear in the code, but the "_ATTRIBUTE_" generates no keybind while "_RELATION_" generates the correct one for the specific elements on that row - this achieves the consitency we were looking for and fixes the issue.
=> Fixed the keybinds to be consistent

DuggaSys/diagram.js
Fixed issue where saves with numeric names could appear above AutoSave. This update introduces custom sorting that keeps AutoSave fixed at the top at all times, and then sorts all other saves by their timestamp, showing the most recent ones first (closest to top) for a more natural behavior.
=> Fixed saved file issue .

DuggaSys/diagram.css
The solution was to add a specific css by targeting only the tooltip text that is a child of the element with the id "mouseMode1", only meant for the tooltip text for the box selection, so the remainder of the tooltip texts dont get affected by this change of position.
PS: Auto indented the css
=> Fixed: Box selection hover-box is cut off 

DuggaSys/diagram.css
=> Fixed margin for the subicon tooltips

DuggaSys/diagram.js, DuggaSys/diagram/helpers/mouse.js
When the sequenceActivation object has already been placed on the diagram grid and is moved close to a lifeline there is now a visualization which indicates snappable locations just like for the ghost version.
There are some issues with this interaction that were already there before. The hitboxes when placing something on a lifeline seem wonky and for some reason the actual snap applies everywhere along the lifeline's vertical line, even outside its boundaries. To fix this changes will need to be done to the actual snap logic, which could be the target for potential new sub-issues.
https://github.com/user-attachments/assets/9c6a215e-da10-49d1-ad84-a10181bef3a0
=> Visual snap indicator for mmoving element

DuggaSys/diagram/draw/line.js
Cardinalities were being hidden in ER relation lines due to inconsistent line calculations.
- Removed the separate logic recursiveERRelation() function and replaced it with getLineAttributes() to unify line positioning logic across all diagram types.
- getLineAttributes() was refactored to return clear coordinates and offsets.
- To eliminate a visual gap between ER relation diamonds and their connecting lines introduced by the adjustment, a small ER-specific offset tweak was also made.
**Master version**
**Fixed version**
=> Fixed cardinality issue with ER lines #16923

DuggaSys/microservices/endpointDirectory/fillEndpointDb.php, DuggaSys/microservices/endpointDirectory/installEndpointDb.php, DuggaSys/microservices/endpointDirectory/microserviceList.php, DuggaSys/microservices/endpointDirectory/newMDStructureTest.md
Some fixes for the microservice documentation database. Fixes #16896 
- Added skips to placeholder texts in the documentation template (if these are not removed when writing documentation they will now be skipped).
- Added a skip for the "-" sign in the calling methods field
- Created a separate table for outputs (that has a 1-M relationship to microservices). A microservice can now have multiple outputs. Outputs was stored in the same table as microservices in the previous version, which means that it could only have one output. (Multiple outputs can be seen in image 2) 
In order to test this you might need to recreate the microservice database. Follow the steps below.
1. Delete 'endpointDirectory_db.sqlite' from the endpointDirectory folder (if you have it).
2. Run …
=> G2 2025 v4 #16896

DuggaSys/sectioned.js
**Since sections already had the functionality, added it to header-type items as well.**
Unsure if this will be used, since I haven't found any headers with trashcans from browsing existing ones. Although, if trashcans were added to them, the problem is solved. for additonal information surrounding delete via trashcan, view: https://github.com/HGustavs/LenaSYS/pull/16879#event-17385722221
**One approach to testing this, and how to get to the functionality:**
select course of your choice (which has duggor, ex. Testing Course) -> log in -> from here, if you press the cogwheel on a dugga you can change its type. By doing this, you can "create" applicable headers.
=> G3-2025-V4-#16925-delete-without-selection-header

DuggaSys/microservices/courseedService/copyCourseVersion_ms.php, DuggaSys/microservices/sectionedService/createGithubCodeExample_ms.php, DuggaSys/microservices/sectionedService/createListEntry_ms.php, DuggaSys/microservices/sharedMicroservices/createNewCodeExample_ms.php
Re-engineered to remove old includes and replaced with POST calls and recieves. Have tried inspecting sectioned.php for both files, none found. Have played around a bit and nothing seems to be broken. Dont know if the changed files are implemented yet. Fixes issue #16826 .
=> Re-engineer microservice createNewCodeExample

DuggaSys/diagram/draw/options.js
Fixed so the text in the properties-box doesn't delete the text between the "<>", and when you remove the label, the testcase updates correctly and doesn't say that the line has a label anymore. All I had to do was to add _escapeHtml_ in the output for the label in the testcase.
=> Fixed: 16817 the testcase does not update when removing a label and if the text of the label is not visible if closed in

DuggaSys/diagram/draw/line.js
In drawLine(), the lines and labels are now separated into two variables, lineStr and labelStr. This allows all the lines to be drawn first, followed by the labels, which prevents lines from overlapping the labels associated with other lines.
This solves the issue #16863.
**Before:**
**After:**
https://github.com/user-attachments/assets/e0f53d4d-47fe-4d02-86a1-f9f4d68ce0cb
=> 16863 the lines overlap the labels when the lines cross each other

DuggaSys/diagram/draw/element.js
Improve note rendering by calculating character width more accurately and allowing text to fill full width.
https://github.com/user-attachments/assets/a01226b5-adba-4710-8bab-805505993494
=> Fixed issue #17008

DuggaSys/diagram.php
All tooltips now have correct grammar (the ones in modes menu). One thing to note is that dots are used in some places and not in others. Could be made into a sub-issue to remove dots or add dots.
=> Improved tooltips information

DuggaSys/diagram/draw/line.js, DuggaSys/diagram/draw/options.js, DuggaSys/diagram/helpers/line.js
Added the ability to set a recursive relation for a sequence activation box. This implementation causes the recursive relation to always be at the top of the box, which means that users will have to make additional boxes in sequence if they want to show the recursive sequence between two sequence changes. Labels should probably also be able to be added to the recursive sequence, but that does not work yet.
=> Added recursive relation for SE

DuggaSys/microservices/endpointDirectory/microserviceUI.php
Added a try/catch block to the pdo connection. If its unsuccessful there will be an error message, else the page will render. Fixes #17024 
(Remember to remove 'endpointDirectory_db.sqlite' if you have it to test this)
Suggestion: when the setupEndpointDb.php file has been approved we can add a button to the error message, letting the user setup the database directly in the UI. If the user is supposed to be able to setup the database of course, otherwise ignore this suggestion.
=> Improve error handling for microserviceUI.php when database is missing. #17024

DuggaSys/sectioned.js
**Prevented deletion of section whiles items within the section still exists.** 
- Streamlined selection of Section/Header/Moment - items by making sure that it stops when it found the next section (meaning current sections items end.)
- Made sure that if a code-dugga has been deselected, the connected section is also deselected. This means that the section can not be deleted without everything within it also being deleted.
- Created function for gathering the code-duggas parent (section) that might also be reused in the future.
**One approach to testing this, and how to get to the functionality:**
select course of your choice (which has duggor, ex. Testing Course) -> log in -> test selection box!
- box marked in red should be able to select all items within the section (and deselect if …
=> G3-2025-V4-#16880-deletion-of-section-without-children

DuggaSys/sectioned.js, DuggaSys/sectioned.php, Shared/components/Dropdown.js, Shared/css/style.css, Shared/icons/hamburger_menu_google_fonts.svg
I have added a reusable React Dropdown component that's placed inside of Shared/components. The actual implementation uses the Button component found in the same directory. An open source icon from Google fonts has also been added. When the dropdown is pressed, each row quickly slides down with a small delay added to each one for a nicer effect. The dropdown will animate up to 9 buttons placed inside it, if more is needed, CSS keyframes will need to be mofified to accomodate it. A function to close the dropdown by clicking anywhere on the page has also been implemented. 
This dropdown is then used to move the view buttons onto the header, which removes the unneccesary space underneath them previously. The placement is similar to that of the mockup in the issue and can be seen in the video …
=> G3 2025 v3 #16722 view buttons position

DuggaSys/codeviewer.js
Replaced remaining jQuery code with vanilla JavaScript from line 4668 to end of codeviewer.js. 
Replaced $.getScript with manual script loading.
Fixed typo in setShowPane() where "gtidRow" was corrected to "gridRow".
=> Replaced jQuery with vanilla JavaScript from line 4668 to end of file #16775

DuggaSys/sectioned.js
Quickfix of PR [#16894](https://github.com/HGustavs/LenaSYS/pull/16894) : removed the hashtag symbol to correct the syntax issue derived from PR [#16894](https://github.com/HGustavs/LenaSYS/pull/16894) . Highscore pop-up dialog broke because of wrong syntax and is now fixed.
`getElementById()` does not need a `#` symbol to retrieve the id of an element. If it has a `#` symbol then it either ignores the symbol and then tries to retrieve the element by id or code breaks.
Converting the jQuery code to JavaScript between L2248-2272 is a complex task. It requires further investigation into the JavaScript equivalent of the `sortable()` jQuery function, which may lead to the creation of a new issue.
=> Quickfix: removal of hashtag symbol 

DuggaSys/microservices/endpointDirectory/fillEndpointDb.php
Added selections to the script that ignores some files that are not wanted in the database. In addition to 'microservice_connections.md' I also added a selections to ignore 'template.md' aswell. 
To check this you can refill the database by running 'setupEndpointDirectory.php' and check if there are unwanted entries from those documents in the microserviceUI.php. Fixes #16994 
Before these selections, the entries in the image below was inserted. The file has successfully ignored the md files if these are not in the database.
=> Ignore the file "microservice_connection.md" in the Microservice directory database script #16994

DuggaSys/diagram.css, DuggaSys/diagram.php, DuggaSys/diagram/toggle.js
This hopefully fixes the issue regarding implementing a way to hiding the toolbar so it does not disturb the user experience and limit the space available for modeling. I have eliminiated most of the overflows that were visible on the mobile version before (see video 1) and this switch with hiding the toolbar happens when the width of the device is 414px or less than 414px. 
This fix could still need som further styling and added functionality for opening the sub-menus. 
Fixed the issue: #17092
The toolbar before (video 1):
https://github.com/user-attachments/assets/2a4c380d-716e-4c07-baaf-f0e22c13a739
The toolbar now (video 2):
https://github.com/user-attachments/assets/98a7cf97-0c8a-4704-ba75-8994cdfdd26e
=> Fixed: Implement hiding the toolbar for mobile version

DuggaSys/sectioned.js, Shared/components/Dropdown.js, Shared/css/style.css
**Fixed icon blocking button**
- Since the problem stemmed from the icon receiving clicks instead of the button, made the icon non-interactable so that the button instead receives the clicks. Also fixed some minor spelling mistakes. 
**Fixed icon missing**
- There was some issues regarding the image-path within some systems where /lenaSYS/ were missing. Fixed this by starting with ../Shared/ instead of /lenaSYS/.
_**One approach to testing this, and how to get to the functionality:**
Enter course of your choice, ex. Demo-Course and investigate view dropdown, marked in blue:_
=> G3-2025-V5-#17048-view-button-not-fully-clickable

DuggaSys/diagram/helper.js, DuggaSys/diagram/helpers/element.js
This PR updates the element movement logic to allow moving multiple elements as a group without triggering the "too close together" warning. The overlap check now correctly ignores elements that are part of the same group, while still preventing collisions with external elements.
Modified entityIsOverlapping(id, x, y, ignoreIds) to accept an optional ignoreIds array and skip overlap detection for those IDs.
Updated setPos() to pass the list of selected element IDs to entityIsOverlapping when moving multiple elements.
https://github.com/user-attachments/assets/8ac07fb3-e27f-4d9b-8df4-b7b818d3809d
=> Fixed: G1-2025-v5-#17009 moving short distance with box selection

DuggaSys/microservices/courseedService/deleteCourseMaterial_ms.php, DuggaSys/microservices/courseedService/retrieveCourseedService_ms.php
Fixes deleteCourseMaterial dependency to retrieveCourseedService.
It says all rows changed in retrieveCourseedService but i only fixed indentation, only thing I added is pdo_connect() and session_start(), I also removed the function wrapper in that file, no other changes.
To test, open up the database and go to codeexamples. There should be a long list. Find the course which has all those codeexamples (I think one of the courses is test something, open it up and you should see on the bottom the codeexamples). When that course gets deleted the codeexamples should all be deleted too.
Fixes Issue #16858
=> DeleteCourseMaterial reengineered - Issue #16858

DuggaSys/diagram.js, DuggaSys/diagram/toggle.js
I have now fixed the rulers position so it adapts to both desktop and mobile version. So, when you toggle on both version they are positioned correctly based on their environment (other elements e.g. navbar on desktop). And if you resize the window they are positioned correctly so you dont need to toggle the ruler to make the position correct. see video 1 to see the result. 
PS: The code is now auto formatted/indented
fixed the issue: #17116
video 1
https://github.com/user-attachments/assets/404e4967-546f-44e3-8090-9a3121f7fbac
=> Fixed: Fix the rulers position so it adapts to mobile versions

DuggaSys/diagram/draw/line.js
This solves a lot of the problems in issue #17014.
I've added an if block that recalculates the fx, fy, tx, and ty coordinates when the line is connected to or from an IE relation element. I also refactored the logic slightly to improve readability and maintainability.
The final change in this PR is the implementation of zoomfact to the stroke-width attribute in the SVG elements. This ensures that the line thickness scales proportionally with the zoom level.
~~The only remaining issue, or issue caused by this PR, is that in some ER relations, the lines still don't fully connect to the element as expected (watch end of video). Will add a new issue for that.~~
https://github.com/user-attachments/assets/a27c6e82-bb1b-45fa-91ea-601e980d04a2
=> 17014 there are problems with the lines loaded from the example diagrams

DuggaSys/diagram/draw/options.js
This functionality gives all input textareas an autosave feature so that when you change colour of the background for the entity the text is always saved beforehand. At the same time you write in the input textarea the entity recieves and updates the text inside it. 
Although this functionality makes the save button useless, it still solves the problem at hand:)
=> Added autosave to input for textareas

DuggaSys/diagram.js
**Quicksaving should no longer trigger constantly when holding down the keybind, and will only trigger once upon releasing the keys.**
This was a slight miss on my part when I initially reported it, not realizing that the "functionality" was there, just not very well documented. There's another function that worked in the same way, which was centerCamera(). This action also happens instantly and only happens once. This was due to not calling upon the function in the keydown-eventListener, instead only calling upon it in the keyup-listener, performing the action once when the key was released. The same functionality was applied to the quicksave keybind, only calling upon the function when the key is released. 
This _does_ feel slightly jarring, with nothing happening upon pressing the key, …
=> [#17086] Fixed issue with quicksave keybind triggering constantly when held down

DuggaSys/diagram/constants.js, DuggaSys/diagram/defaults.js, DuggaSys/diagram/helpers/element.js
When using snapToGrid rectangular elements now snap to grid lines instead of snapping irregularly beside them. Other shapes snap to their center. Overall it gives the user an easier time to line up elements on the grid which seems to be the original purpose of the feature. I also made some changes to note and added elementTypeNames to its kind to match the other elements. For some reason note was previously just a string.
https://github.com/user-attachments/assets/92aeae88-6d4d-45ab-8845-0ed95f0744a3
=> [#17075] snap to grid doesnt align elements with the grids x axis

Shared/css/style.css
Fixed so that the course name is as centred as it can be with the space in the header. Its still not perfect but the fab buttons needs to be sized down before it can be perfect but it is as good as it can get right now.
=> Fixed the course name in mobile view for issue #17064

DuggaSys/diagram.php
I changed so that the sub-icon order for the relations always are the same order. take a look at issue #17140 to see how it looked before the fix.
=> Fixed sub-icon order

DuggaSys/diagram.css, DuggaSys/diagram.js, DuggaSys/diagram.php
When a user have made changes and tries to load a new save without first saving a popup appears.
Asking if they want to save the changes they made to the current file. Yes, it loads the new files and saves the changes.
No,  loads new file but don't save changes.
=> Promp for unsaved changes 

DuggaSys/sectioned.js
Fixes #17142. 
The function that validates the 'Message of the day' text had a missing variable (errorMsg) that is now declared. 
For testing I created a new course, filled in the necessary information and saved the information and started adding items to the course. If set to default, the created version will always be loaded, otherwise the same information has to be filled in again. 
The screenshot below shows that the editing for a course now works:
=> G3-2025-V5 #17142 Fix course creation error/prevention

DuggaSys/diagram.php, Shared/css/style.css
I have implemented the FAB-btn. The FAB-btn as of now is correctly positioned based on the mockup https://github.com/HGustavs/LenaSYS/issues/16813#issuecomment-2847517767, and the FAB-btn is only being displayed on mobile versions and not desktop or tablet versions. More specifically when the screens width is 414px or less than that, see figure 1.  I have also tried to reuse as much as possible from the other fab-btns available on section editor. 
Fixed the issue: #17162
figure 1
=> Fixed: Implement FAB "button"

DuggaSys/diagram.css
The issue should be solved.
Had to change a few things:
- Removed the zoom container when media=414px because I thought it just took up space, and I assume the user uses the fingers to zoom in and out on the phone. But if someone else thinks it should be there, it's an easy fix to put it back.
- Since the toolbar was removed from the left side, I had to change the ruler overlay to "left: 0" to remove the gap between the grid and the ruler on the left.
https://github.com/user-attachments/assets/68f8d9c5-e0e1-46d9-be4f-8ada7bc26cd9
=> Fixed: G1 2025 v5 #17156 the rulers position is out of place when reloading the page on mobile version

DuggaSys/microservices/curlService.php
There was an error in the callMicroserviceGET function in curlService.php. I have changed the parameter "$microservicePath" to "string  $path" since it's used in the URL and now the function should work.
fixes #17186
=> Changed callMicroserviceGET function parameter in curlService.php #17186

DuggaSys/microservices/endpointDirectory/dependenciesList.php, DuggaSys/microservices/endpointDirectory/fillDependenciesDb.php, DuggaSys/microservices/endpointDirectory/installEndpointDb.php
Added foreign key fields in the dependencies table. These can however be null and are intended to make queries easier. 
There are some inconsistencies in how the documentation is created and stored in the database. Some documentation has '_ms' in the name, some has '_ms.php' and some doesn't have any of them. In order to solve this, and still match microservice names to get the id and be able to insert the id in the dependencies table, I created a function. This function check the database for all the variants of the name and returns it when it finds it (or null if it didn't, since this usually means that there isn't any documentation yet). 
The microservice documentation isn't complete at the moment, so the test-data is limited. You can see the results below, but when more documentation …
=> Add foreign key from microservice table to dependencies table in endpoint database #17212

DuggaSys/microservices/endpointDirectory/microserviceUI.php
Fixes #16967 and adds edit functionality to the microservice UI. Editable attributes include the microservice name, description, calling methods, and microservices used. The parameters and outputs values are intentionally not editable through this form due to complexity and the need to maintain the structure/associations between microservices. IF these attributes should be made editable despite the potential issues, I recommend creating a separate issue for implementing their edit functionality.
=> Added edit functionality

DuggaSys/microservices/curlService.php
Put the return option to true instead of false on the GET function.
Fixes issue #17114
=> Fix return options on curlService Get function - Issue #17114

DuggaSys/diagram.js
When the user loads another file and proceeds to make changes and save that save now targets the correct loaded file instead of the previous one. 
https://github.com/user-attachments/assets/9bcadeb0-db2c-460c-a706-93e3986fc484
=> Loading file and saving

DuggaSys/diagram.css
the new media query for min-width was used to alter the height of the toolbar on desktop mode without making the mobile version change.
=> Fixed desktop toolbar height

DuggaSys/diagram.php
The solution was to remove an class from the sequence activation box in the dropdown that was used to mark what element is active, and then add that class to the correct element that was being active. see figure 1 for result. 
The issue that was fixed: #17141
=> Fixed: Wrong tool gets highlighted in the sub-menu

Shared/css/style.css
buttons are smaller and equidistant, as well with slightly more spacing to reduce chance of mistapping. They look good on all the aspect ratios I have tried (most popular phone ARs). Also moved course name and code so it's not in the way. Since only styling has been changed I don't see how functionality should differ but I haven't found any issues.
This is the old styling with larger buttons and overlapping text.
This is the new styling with slightly smaller buttons and centered text.
=> added styling to mobile buttons

DuggaSys/codeviewer.js, Shared/css/codeviewer.css
Ended up not really improving on the code structure, but the functionality should hopefully be the same as before. Testing this specific function is simple, try every codeviewer template and try dragging the boxes to resize them. 
I don't think anything outside of these pages should be affected by the changes.
=> Swapping all the jquery in resizeBoxes function in codeviewer.js #16774

DuggaSys/diagram/helpers/mouse.js
Fixed this issue **again**. Had to put back some disappearing code in some functions in helpers/mouse.js.
https://github.com/user-attachments/assets/a15def50-c895-4d13-9afa-6ec12e593c15
=> Fixed issue #15647-snap-to-lifeline-or-object-after-placement

DuggaSys/microservices/gitCommitService/getCourseID_ms.php, DuggaSys/microservices/gitCommitService/insertIntoSQLite_ms.php
Have Reengineered insertIntoSQLite its invert dependent file getCourseID. Post without answer implemented according to standard in file microserviceRefactorPOSTnoAnswer.md. Have tried testing with no result, the tables from the database which both files use, calling either empty rows or a database which does not seem to exist "gitRepos". Have tried adding a github repo to LenaSYS since the file likely does something with github but that function does not seem to be working on my branch nor the groups weekly branch, unsure how to test further. Not sure if files are used in LenaSYS yet. Fixes issue https://github.com/HGustavs/LenaSYS/issues/16867 .
See previous PR #17124 .
=> Re-engineer of insertIntoSQLite_ms.php

DuggaSys/sectioned.js, Shared/icons/eye_closed_icon.svg
Added a new SVG called eye_closed_icon. It shows up after you have opened up the hidden elements, you can close them by pressing the new SVG (which is stillin the same spot). Its a bit more clearer now!
Elements closed(by default).
Elements open.
=> #17184 ToggleElements button should indicate when in use and when not

DuggaSys/diagram/theme.js
A previous pull request I made (#17241) fixed an issue where single-selected elements didn't turn purple upon selection. However, it also introduced a new bug that caused the text color to turn white for certain sequence elements and the UML super state element. This became problematic because the background color wasn't updating correctly to purple on selection, making the white text appear to disappear.
I've now patched this issue by extending the earlier fix to include these elements as well, ensuring they also turn purple when selected. Additionally, I’ve verified that everything continues to work correctly with dark mode enabled.
Before: 
After: 
Fixes: #17245
=> Fixed: Sequence elements turn purple upon selection.

DuggaSys/diagram/draw/line.js
Removed duplicated logic for arrow positions and drawing arrow shapes for both the start and end of a line.
Added a new function: calculateArrowPosition
which calculates the arrowhead position at the start or end of a line.
https://github.com/user-attachments/assets/52db799a-99f8-4a4a-b433-a406ddce9c95
=> Fixed: G1 2025 v6 17169 the arrows is not visible on straight line between state diagram entities

DuggaSys/diagram.css
There was missing functionality specifically for "disabledicons" when hovering hence why the tooltips was not being shown, so this was implemented and the tooltips started showing for "save" and "save as", as well. After this was solved some slight tweaks was made with the transition delays when hovering so all the buttons behave the same and consistent.
=> Tooltip fix issue #17237

DuggaSys/microservices/endpointDirectory/microserviceUI.php
Added a table that outputs the microservices that the chosen microservice is depending on. I also made the name of the microservice clickable, if clicked the user will be taken to that microservice instead. Fixes #17269 
There was some styling for the a-tags, so there are currently buttons in the table. If that is undesirable we could create a issue that changes the styling (create a class that holds the styling instead of a-tags). Otherwise, leave as is. 
To test this, make sure to have the database installed and fille, then select a microservice that has documented dependencies in microserviceUI.php. 
If there are no dependencies this will be outputted instead.
=> Add dependencies to microservices in microserviceUI.php #17269

DuggaSys/diagram/toggle.js, DuggaSys/templates/diagram_dugga.js
**For reviewer:** To test this fix you need to be in _showDugga.php_ (Start from "_./LenaSYS/DuggaSys/courseed.php_", click on "_Demo-Course_", scroll down to "_Tillgängliga Duggor_" and click on "_Diagram Dugga_").
(**TLDR:** The fix was to remove an extra keylistener for the keybind in a separate function that was independent of diagram.js. The error check keybind should no longer trigger outside of intended situations.)
The reported issue here was that the error check keybind (h) triggered when writing in input fields, which wasn't supposed to happen. Upon further investigation it was discovered that the error check keybind triggered twice when not having selected an object. This only happened if you weren't logged into lenaSYS. If you were logged in as "brom" (an admin user) the bug …
=> [#17198] Fixed error check key triggering outside of intended usage

newinstaller/tools/configuration_manager.php
Fixes issue #17319, to test it, either remove or backup the `coursesyspw.php` file located at `C:/xampp/htdocs/coursesyspw.php`. After you did this, follow these steps in new lenasys installer:
Step 1: Select Windows
Step 2: Select both checkboxes
Step 3: Database name: lenaDB, MySQL user: Daniel, Hostname: localhost, MySQL user password: 1234, and for the rest, uncheck.
Step 4: Root username: root and Root password: empty
Step 5: Select all options
Step 6: Click install-button.
The new installer will create the file `coursesyspw` in the same directory and successfully installed the lenasys.
=> Fixed issue #17319. Use only Windows with XAMPP

DuggaSys/microservices/endpointDirectory/microserviceUI.php
Fixes #16965 and adds microservice form functionality for adding a microservice in the UI. It looks and functions almost the same as the edit functionality, but with this form, you can now instead add a microservice using the same attributes as the edit form. Parameters and outputs, for the same reasons as when implementing the edit function, will not be added at this time.
To test it, go into microserviceUI.php and press "Add Microservice". (checking for CSRF token was also added as it was requested last time for the edit form)
=> Added microservice form functionality

Shared/css/style.css
I fixed the redundant box shadow definitions in style.css by:
1. Identifying duplicated box-shadow code throughout the file
2. Creating standardized CSS variables in the  section:
--box-shadow-normal: rgba(0,0,0,0.2)
--box-shadow-dark: rgba(0,0,0,0.5)
--standard-shadow: for common shadow patterns
--light-shadow: for lighter shadow effects
3. Replacing all instances of repeated shadow code with these variables
=> Fixed box shadow definitions #17043

Shared/css/style.css
All I have done is move the item create menu 75px to the right.
It looks like this now
=> Moving item creation for new item button #17260

DuggaSys/diagram.js, DuggaSys/diagram/helpers/mouse.js
The visual indicator of a snap to lifeline is now back and working even when dragging an already placed element. The visualization is only observable for sequenceActivation elements.
https://github.com/user-attachments/assets/72fbd32e-b50c-4823-acc8-ce600570b240
=> Fixed: G1 2025 v6 #17277 visualization of snap to lifeline is not showing anymore

DuggaSys/diagram.js, DuggaSys/diagram/events/mouse.js, DuggaSys/diagram/helpers/element.js
I have removed overlapping of all the elements. You can resize, drag, create and move with the arrow keys over other elements. No error is shown either.
The z-index dose not update when you pick up a new element making it rather jarring to use and should be solved in a different issue.
=> G1 2025 v6 17382 delete detection of overlapping

DuggaSys/diagram.js, DuggaSys/diagram/draw/line.js, DuggaSys/diagram/draw/options.js, DuggaSys/diagram/helpers/line.js
The recursive line can now be changed to dashed and back using the radio buttons in the options menu.
[Screencast from 2025-05-08 13-25-07.webm](https://github.com/user-attachments/assets/5917e5aa-bf5a-4cef-aedb-f7a70be1af12)
=> Dashed recursive line

DuggaSys/microservices/endpointDirectory/microserviceUI.php, DuggaSys/microservices/endpointDirectory/style.css
Added a class to a-tags (in microserviceUI.php) that are buttons and added the class to the stylesheet instead of the a-tag.  A-tags that are not supposed to be buttons are now links. Fixes #17340
=> Change the styling of a-tags in MicroserviceUI #17340

DuggaSys/sectioned.js
Links can now be created without crashing LenaSYS
Added a null and undefined check to stop the if statement executing .substring on a null or undefined link. If one of these evaluates to false, the if statements stops and throws an error instead of crashing. To test, create a new link in sectioned.php.
=> G3-2025-V6-#17179 Links crash lenasys

DuggaSys/diagram/draw/line.js
There's a converter built into the drawLine function that checks if the user has input the symbols "<" or ">". If they had, the input symbols would be converted to their HTML number values, most likely to avoid conflicting with any html that was to be sent by the rest of the function. There were however semicolons missing at the end of the HTML numbers, which caused further digits to change the HTML number completely. For example, if the user input "<24", the converter **should** have converted the string into "**_&# 60;24_**" which would've displayed as "<24" (_Had to put a space between "&#" and the numbers since it got converted in the text as well_). However since the semicolons were missing, the string was converted into "**_&# 6024_**", which is the HTML number for "ឈ", a Cambodian …
=> [#17302] Fixed unintended label interactions with "<" and ">"

DuggaSys/diagram/events/mouse.js, DuggaSys/diagram/helpers/mouse.js
Added some check conditions that were missing on the y-axis of the lifeline causing elements to snap infinitely along the vertical line. This should not be possible anymore and snaps only occur to the actual lifeline.
https://github.com/user-attachments/assets/49bde8a2-cec7-4743-8530-47c2d5ffe69b
=> Fixed: G1 2025 v6 #17316 snapping to lifeline occurs infinitely along the vertical line

DuggaSys/courseed.php, DuggaSys/showDugga.php, Shared/dugga.js, Shared/navheader.php
Burger menu has been added to dugga.js for mobile. The burger dropdown menu contains the navigation tools: home, toggle darkmode/lightmode and return/back.
It's an ugly solution but it works. I am aware that the burger icon is not consistent with the others, the positioning of the burger menus are different for each burger menu(there are three in total), in fact the burger menu in sectioned and courseed differed from the start.
The navheader.php file is currently messy, unstructured, and not scalable for long-term use. It contains a significant amount of redundant code that PHP may tolerate. All these greatly hinders readability and maintainability.
There are currently three burger menus in total, all using duplicate and inconsistent IDs. This is the reason why the hamburger icon fails to …
=> Burger menu added in dugga for mobile

DuggaSys/sectioned.js
Changed the default visibility new objects to be true, as before it was automatically hiding new objects. Also switched which icon should be used at which point to reflect the actual state of the button.
Before:
Now:
=> G3 2025 V6 changed default visibility of objects

DuggaSys/diagram/draw/options.js
**For reviewer:** If you want to try to replicate the bug shown in the issue, copy the text at the bottom of this description or get your own large amount of text and paste it into the input field (_hold CTRL + V for like 5-10 seconds_). The page should start freezing once you have enough characters in the field.
The issue here wasn't as much an error with the options pane, but rather a weird side effect of having too many characters in the input field for naming elements. Once you're up above a certain amount of characters (_vague estimate of approx. 6000+_) the page starts experiencing some performance issues, like freezing. One weird side effect of this was that the options pane color field didn't update its color after having changed the color of an element until you reopened the …
=> [#17400] "Fixed" issue with color change not updating in the options pane instantly

DuggaSys/diagram.css, DuggaSys/diagram.js, DuggaSys/diagram.php
Added an element that displays the name of the current file for the user. If no file has been opened, the div is not displayed at all. When a user is changing between files the name updates along with the file being loaded. All of the logic is handled at the same time as the file is loaded (in the same function), so there is no delay in showcasing the name or loading the diagram.
Currently the only way to display the name (so that the only place it shows up on is the diagram pages) is to display it in the drawing-area (or on top of the ruler) which might not be the most convenient place but seems to work well enough for the most part. 
https://github.com/user-attachments/assets/326194ef-2464-4435-be22-895e0d2feb30
=> Name of current file is being displayed to the user

DuggaSys/diagram/draw/element.js, DuggaSys/diagram/theme.js
Fixes issue: #17436, the issue was that when adding alternatives to sequence loops, it broke the color manipulation of the element (my fault).
The small text area dynamically changes position relative to its parent (in the html-structure) when alternatives are added to the element. But since the color was manipulated with a static child reference, the color manipulation broke when adding alternatives. To fix it I added an ID to the <path> for the small top left text area and changed the color-updating logic filter on that instead of a statically defined child. This solved the issue and is much more reliable.
Before: 
After:
=> Fixed multiple alternative sequence-loop highlight color

DuggaSys/microservices/highscoreService/highscoreservice_ms.php, DuggaSys/microservices/highscoreService/retrieveHighscoreService_ms.php
Fixes #17117 . I've changed the microservice retrieveHighscoreService_ms and its inverse dependency file highscoreservice_ms to use the curlService functions for POST. These files weren't re-engineered correctly before since the cURL options for POST weren't set and the data wasn't received in retrieveHighscoreService_ms. From what I have found it's still the old highscoreservice.php being used and not these microservices so I haven't been able to test it properly. It should be changed in the future to use these files instead. The reviewer can tell me if you find something different.
=> Changed to curlService in retrieveHighscoreService_ms and highscoreservice_ms  #17117

DuggaSys/diagram.css
Fixed diagram message positioning on mobile because it got cut off by the options-panel. I moved it to the top left corner instead and changed the width on the box. I think the top left corner is the best place because the toolbar and the FAB is at the bottom of the screen. 😄
https://github.com/user-attachments/assets/63f6d423-6ee1-4211-9c85-1ea80ea299fd
=> Display message positioning fixed on mobile

DuggaSys/diagram.css, DuggaSys/diagram.php, DuggaSys/diagram/toggle.js
Fixed the HTML, JS, and CSS to match with the "Example diagram"-button and functionality. The A4 template can now be toggled from a dropdown, and is not too close to the Darkmode-button.
=> A4 template options change-up (#17429)

DuggaSys/diagram/theme.js
**TLDR:** The program didn't account for the object still being selected after snapping back from out of bounds, causing any selection action afterwards where the mouse is pressed down to move the object(s) relative to the cursor position.
Previously, when moving an object outside of the grid viewport the object would snap back to its previous position. The object was still selected after this snap-back happened, which caused some weird interactions with the pointer- and box selection tools.
**When using the pointer tool, the element would move independently of the grid when grabbing the background after having snapped back:**
https://github.com/user-attachments/assets/3519ca75-c7ce-4b16-9f76-239905ce362e
When using boxselect, the object would snap to a different location when the …
=> [#1720] Fixed odd behaviour with selected elements after snapping from out of bounds

DuggaSys/diagram/classes/element.js, DuggaSys/diagram/classes/stateChange.js, DuggaSys/diagram/draw/element.js, DuggaSys/diagram/draw/line.js, DuggaSys/diagram/helper.js
The issue( #17272) was that the sequence diagram functionality was borderline useless in terms of how sequence diagrams are supposed to look and be used. Lines would automatically connect to the center of the sequence activation elements, just as they do with other elements. This would however defeat the purpose of a UML-diagram type that is meant to have clear, distinguishable and customizable transitions between activations along a timeline. 
The implemented fix has resolved the main parts of the original problem. Lines can now be drawn to user-specified anchoring points on the activations. Lines won't be rearranged by removal of other lines and the arrowheads are correctly placed on the line ends instead of being misaligned etc. However, repetitively using the undo/ctrl+z as well as …
=> Made sequence-diagram lines behave appropriately 

DuggaSys/diagram/events/mouse.js
Now sequenceActivation should be the only element to actually snap to different lifelines. Just added an extra check before snapping.
https://github.com/user-attachments/assets/444ed525-798b-4021-a38f-d5096ba31e39
=> Fixed: G1 2025 v6 #17469 elements snapping to lifeline

DuggaSys/diagram/draw/element.js, DuggaSys/diagram/draw/options.js
!!(I should note that the original purpose of the issue has evolved—from automatically bringing an element to the front when selected, to giving users manual control over which elements should appear in front or behind. This gives users more flexibility when arranging their diagrams.)!!
This pull request, that has been given life by me, adds two buttons in the options panel that let you change the layer order of elements on the canvas. When one element overlaps another, you can now choose to move it forward or backward by adjusting its z-index.
The functions work by finding the current highest or lowest z value and updating the selected element accordingly. Then the entire canvas is redrawn to reflect the change.
I’ve tested this with different kinds of elements and it behaves as …
=> 17390 fix z index on latest interacted with element

DuggaSys/diagram/draw/line.js, DuggaSys/diagram/draw/options.js
Removed the redundant label from options.js. Added a condition statement in line.js to customize label positioning for SE recursive lines, also the label should now appear after saving.
=> Fixed-sequence-table-recursive-relation-labels

DuggaSys/diagram.css
Change the width from 30% to 70% to fit better and show more of the saved files.
=> Fixed the width of the load modal

DuggaSys/diagram.css, DuggaSys/diagram/toggle.js
This change simplifies the positioning logic and reduces unnecessary calculations. The whole color menu is now visible on both desktop version and mobile version. When the user clicks on a color, the color menu closes as it was before.
Desktop version:
Mobile version:
=> Fixed: G1 2025 v6 #17437 fix so you can see all colors in mobile version

DuggaSys/diagram/draw/options.js
It was mostly what i will assume AI typos which made some comments very hard to understand because they were barley English. I have updated them to actually describe what they do.  Thankfully Sol Milleding (My GOAT🙏) last year made some outstanding comments on the majority of the file so it was not that much work!
Like this was one of the comments this inst even English like what!?
We should consider renaming:
select()
radio()
and option()
They do a way more specific job then their names makes you believe. 
But the opposite is for:
lineLabel()
Which is way more generic then what its name entails. 
All so I do question the necessity for the function setLineLabel() and where its used. Kinda feels like there is a easier way of doing that but I'm still new to the code
=> G1 2025 v6 17428 documentationcomments in optionsjs

DuggaSys/microservices/endpointDirectory/admin-endpointDirectory_db.php, DuggaSys/microservices/endpointDirectory/deleteEndpointDb.php
Created a page where you can install, fill and delete the endpoint directory database. Fixes #17414 
On 'admin-endpointDirectory_db.php' you can do things based on the current status of the database. If its installed, you can delete it, if its not installed you can install it, if its installed but not filled you can delete it or fill it etc. 
When testing this you can use 'microserviceUI.php' to see if the database if installed or not, and to check if its filled. 
At the moment there are no login requirements.
=> Admin panel for endpointDirectory_db.sqlite #17414

DuggaSys/diagram/draw/element.js
A quick fix to remove the redundant variables introduced here https://github.com/HGustavs/LenaSYS/pull/17552 that broke the diagram.
_Image of the removed lines_
=> Quick fix of the diagram

DuggaSys/diagram/draw/element.js
This change makes the name of the attribute centered but if the name is too long, it shows the first part of the attributes name instead of the middle part of it.
=> Fixed: G1-2025-v7-#17554-align-er-attribute-name-to-the-left

DuggaSys/diagram/camera.js
**TLDR:** Implemented special handling for certain elements when getting largest y-value since some elements don't have default height values.
The problem was caused by the _centerCamera()_ function in camera.js. It turns out that certain elements (_UML Entities and SD Entities_) don't have a default height value assigned to them, which clashed with how the function got the positional values for centering the camera (_This basically just means that the element objects have no height value to retrieve_).
The function works by getting the smallest and largest values of the entire diagram, which it then uses to determine zoom level and where to position the ruler bars. Since UML- and SD-entity elements don't have heights, the largest y-value became **NaN** (_Apparently, y-pos (which had a …
=> [#17567] Fixed issue where app breaks when centering camera on example diagrams

DuggaSys/diagram.css
Improved the design consistency by adding custom styles to .saveButton (for <button> elements):
CSS:
border-radius: 4px; — adds rounded corners to match the style of input buttons
font-size: 16px; — ensures consistent text sizing across all buttons
margin-top: 10px; — creates visual spacing between stacked buttons
padding-left: 5px; — adds inner spacing for a cleaner, more balanced look
This update ensures the “Bring to Front” and “Send to Back” buttons visually align with the rest of the options panel.
=> new css class

DuggaSys/diagram/draw/options.js
As requested, I changed some functionnames, like "radio()" "select()" and "option()". I did not change the name of the function "lineLabel" becuase it had preferences to other files and my opinion is that it's unnecessary to do all that work for that function.
"setLineLabel()" sets the lines label to "< < include > >" via the include-button on the picture below so I left that function as it is.
=> Fixed G1-2025-v7-#17553-examine-options.js

DuggaSys/diagram/draw/element.js
Fixed the issue where IE relation got cut of at max zoom. For some reason, only the IE relation had this problem while the other relations didn't.
_**Max zoom**_
=> [#17561] Fixed IE relation getting cut of at max zoom

DuggaSys/diagram/draw/element.js, DuggaSys/diagram/theme.js
A recent change seems to have changed the way the _updateCSSForAllElements()_ function looked for elements in an entity that were supposed to be affected when changing the fill color of it. I assume this was related to the change where all selected objects now get a purple fill color. The sequence loop object and UML super state entity had the affected elements retrieved by finding the element with the ID "_loopLabel_". This ID had however not been added to the element in the UML super state object, so when the system tried to draw the super state entity the element to fill returned as null, which froze the app since the function for updating the CSS stopped working. 
The ID has now been added to the correct element in the super state object, in addition to changing the ID name from …
=> [#17579] Fixed issue with app freezing after placing an UML Super State object

DuggaSys/diagram.css, DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagram/constants.js, DuggaSys/diagram/toggle.js, DuggaSys/diagram/tooltip_information.js
My solution consists of having only one element used to contain information about the elements and act as a tooltip. When the user hovers on an element the tooltip's position is calculated based on where the hovered element are. For example the tooltips associated with the options panel gets a different position in contrast to tooltips on the toolbar. The tooltips information gets filled based on the hovered element. if the pointer element is being hovered then the tooltip gets filled with information about the pointer from the file that contains all information about the elements (tooltip_information.js). 
With this i have removed every old tooltip that existed for every element, this reduces the code especially for the toolbar. 
I think i have found a great refactoring solution to the …
=> Fixed: Examine the tooltips for refactoring

DuggaSys/diagram/helpers/line.js
Removed an if-statement from line.js which was responsible for automatically making the line double when connected to weak entities (only applies to the ER entities, all other ones are un-touched). 
The user now has to manually select "Double" for the line in the options-tab, see below. 
https://github.com/user-attachments/assets/2e32d8dd-8d39-47ad-8a11-2444a16edafc
=> Remove auto double line ER-element feature (#17529)

DuggaSys/templates/diagram_dugga.html
The solution was to replace the containers height from 50.1rem to 100dvh and then have other elements inside it inherit that height. And the ifram inherits from .canvas_right and needed to explicit set the height of #close_open_border to 100dvh.  see figure 1. 
I fixed the issue #17639
figure 1
=> Fixed: Diagram-toolbar is not completely visible in showDugga

DuggaSys/diagram/draw/line.js
This patches an issue for Firefox users where zooming didn't correctly scale the cardinality text labels. See the attached video in the issue for a problem demonstration (#17569).
The issue was that the cardinality text was styled using a CSS font-size property, and apparently Firefox does not consistently apply this styling to SVG <text> elements, causing the text to remain the same size regardless of zoom level. This was changed to dedicated font-size and fill SVG attributes being used for the cardinality texts. 
**This change should be tested specifically in Firefox to confirm the fix.**
=> Fixed: Cardinality labels do not scale correctly with Firefox

DuggaSys/diagram.js
The changeState()-function has been fixed so that it can handle a name-change or color-change before changing the "variant" (state) of an element (see issues #17511 and #17575). 
Now it handles any change to the selected elements state, and then redraws the canvas to display the change, making it possible to change name or color and then change the state.
This should affect any elements/entities that utilize the "Variant"-option in the options-panel.
https://github.com/user-attachments/assets/34c2083c-e8a3-4ea4-b7e9-87a39113dc2d
=> Problem with variants of elements (#17511 and #17575)

DuggaSys/diagram.js, DuggaSys/diagram/draw/options.js
Changed undo/redo behavior from character-by-character updates which felt unnatural, to using a blur event. Now when the user finishes input (e.g. clicks save or clicks away on the grid), pressing undo will remove the entire input (e.g. full name) instead of one character at a time. Redo behaves the same.
=> Fix undo/redo name issue #17185

.gitignore, newinstaller/installer_ui.php, newinstaller/tools/ssl/ssl_generator.php
This is a SSL cert generator that generates localhost.key and localhost.crt.
These files will later be used for a tutorial that explains how to enable HTTPS on your local machine.
The .gitignore needs to be updated with _*.crt_ and _*.key_ since these files are supposed to be local, and not be pushed to remote.
=> SSL-generator #17644

DuggaSys/microservices/endpointDirectory/microserviceUI.php, DuggaSys/microservices/endpointDirectory/style.css
- Made edit microservice form to an overlay
- Made add microservice form to an overlay (a little bit bigger than edit)
- Changed styling for filter button to match the other buttons
<b>This wasn't part of this issue</b>
I also changed the button menu a little bit, so the buttons wont rearrange when the reset buttons appear (if this isn't a wanted change we can remove the last commit and create a new issue) 
It now looks like this: 
And when the reset button appears it now looks like this:
Before these changes when the reset button appeared it looked like this:
=> Updating the microservice UI design/structure #17304

DuggaSys/microservices/resultedService/getUserAnswer_ms.php, DuggaSys/microservices/resultedService/retrieveResultedService_ms.php
Fixes #17416 . I've changed to curlService in retrieveResultedService_ms and its inverse dependency microservice getUserAnswer_ms. At the moment these files are not used and it's the old resultedservice.php being used when you go to "Edit student results". Also, retrieveResultedService_ms just sends the same data back to getUserAnswer_ms as it received. To test that the communication works between these two files I created a testfile to send real values from the database for "cid" and "coursevers" to getUserAnswer_ms. I had to comment out the "isSuperUser().." line of code and change "(kind=3)"  to "(kind=2)" in the query in getUserAnswer_ms, then I was able to get a response with data of the two arrays.
=> Changed to curlService in retrieveResultedService_ms #17416

DuggaSys/diagram/draw/element.js
Reduced the whitespace in the bottom section under "Attribute" and "Function", to make the UML class element more compact. The same proccess was implemented to the IE ("Primary" and "Attribute") and SD ("do: func") elements. The changes made were done in the element.js file.
=> Fixed and reduced whitespace in UML Class, IE and SD elements

DuggaSys/diagram/draw/options.js
Elements should now not dissappear behind the canvas no matter how many times "Send to Back" button is pressed. This solution has been implemented by setting a cap to the minimum "z" in the "sendtoBack" function. These changes were made in options.js file.
=> Fixed "Send to Back" elements placed behind the canvas

Shared/css/blackTheme.css
Added a courseRow hover in blackTheme as there was none and therefor used the lightmode hover. It now looks much better and readable when youre hovering over a listitem in sectioned.php.
Hover now
Hover before
=> Fixed the too light hover

DuggaSys/sectioned.js, Shared/css/style.css
The date for dugga items is now displayed. 
For testing: go to any course with duggas/tests, view the page in both the mobile and desktop view, switch between logged in/out.
Note that default window size of mobile-view for testing is 320x600(talked to group leader)
I was about to give up on the issue with the solution burger menu containing buttons, but the group leader suggested an alternative approach: placing the title and date above the buttons. See PR [#17661](https://github.com/HGustavs/LenaSYS/pull/17661) for the burger menu.
While this(this PR) is not an ideal solution and requiring considerable changes, this temporary solution works for now. 
Initially, the dugga item had a different layout/design for its elements(the initial commit: [Mobile-view display of …
=> Display date of dugga in mobile-view

DuggaSys/sectioned.js, Shared/css/style.css, Shared/navheader.php
For mobile view, this PR removes the button for viewing announcements in the burger menu. Although I am unsure if the page displaying announcements is still accessible, it is probably outside the scope of this issue. This is what it looks like before/after changes:
For testing, simply navigate into any course, CTRL + SHIFT + I and enter mobile view. The previous "Announcements" button should not be visible anymore within the burger menu (three horizontal stripes) and presumably no related code should be remaining within the codebase.
=> Removed the button for announcements on mobile view for issue #17501

DuggaSys/tests/testGithubLinkCodeExample.php
Acceptance Test Script for Connecting Course Element to Github #16513 
The file was bugging locally so it got 3 commits for 1 so just ignore it.
I am not 100% sure if I understod the issue or solved it.
The file created is test "testGithubLinkCodeExample.php" and it is located at: C:\xampp\htdocs\LenaSYS\DuggaSys\tests\testGithubLinkCodeExample.php
How to test it: 
Locate the file in browser at:
http://localhost/LenaSYS/DuggaSys/tests/ 
Click the file: 
testGithubLinkCodeExample.php
It should say Test passed, and if failed: Test failed.
Now go in to the file but in vs code at path:
DuggaSys\tests\testGithubLinkCodeExample.php
Put "//" (comment out) the three rows of "Deleting/Cleanup" so it looks like this:
// Cleanup/Deleting
// $delete = $pdo->prepare("DELETE FROM codeexample WHERE …
=> Acceptance Test Script for Connecting Course Element to Github

DuggaSys/diagram.js, DuggaSys/diagram/globals.js
The load button didn't have special formatting to ensure that load buttons fit within the load modal window. This caused the button to extend outside of the window, bringing the delete button with it. The button was still accessible if you scrolled horizontally, but ideally it should just fit into the available window. 
A condition has been added so that the text in the buttons receive special formatting if the browser is in mobile view, limiting the displayed text to 12 characters of the file name. This, admittedly, isn't the most elegant solution to the problem, but it does its job.
A global variable called _isMobile_ has also been added for future mobile specific formatting.
**After fix - mobile view:** 
**After fix - pc view:**
=> [#17508] Fixed wide load button issue on in mobile view

newinstaller/installer_ui.php, newinstaller/tools/components.php, newinstaller/tools/configuration_manager.php
Fixes #16150.
When you run the new installer for the first time, then the configuration manager file going to read the default values from coursesyspw.php, which are:
• DB_USER = lenasys
• DB_PASSWORD = password
• DB_HOST = db
• DB_NAME = lenasysdb
• DB_USING_DOCKER = on
After the configuration manager finish reading the coursesyspw.php, then configuration manager going to assign all the values to each input, so that skipping rewrite them over again. 
When the installer begin to install the lenasys and complete the installation of lenasys, then the configuration manager will write or overwrite the coursesyspw.php. If you go back to the new installer, then all values will be updated.
Note: These values only assign the username, password, hostname, database name, and distributed environment …
=> Added funtionality for read existing configuration for new installer

DuggaSys/microservices/endpointDirectory/setupEndpointDirectory.php
Removed the old code that removes the database (if it exists) before reinstalling it. It does the same thing as before, but there was a delete script made for a different issue, so it might as well be used here too. Fixes #17467 
To test this you can run `'setupEndpointDirectory.php'` and check when the `'endpointDirectory_db.sqlite'` was created. If you didn't have the database before running `'setupEndpointDirectory.php'` you need to run it two times.
=> Change 'setupEndpointDirectory.php' to use delete script #17467

DuggaSys/microservices/Microservices_inverse_dependencies.md
Fixes #17664 . Some inverse dependencies were missing for getUid_ms.php and have been added to Microservices_inverse_dependencies.md. It's important that all of them are correct before the re-engineering can be done for this microservice.
=> Added inverse dependencies for getUid_ms.php in Microservices_inverse_dependencies.md #17664

DuggaSys/diagram/draw/element.js
It was discovered that certain elements did not respond to the bring/send to front/back operations via the buttons in the options panel. This was due to static zLevel values having been attributed to these elements, which would override any attempted z-ordering changes. By removing these static zLevel values, the elements now respond as expected.
The specific elements that were affected are: Sequence Actor, Sequence Object, Sequence Activation, Sequence Loop, UML Superstate, UML Initial State, and UML Final State. These have been modified to respond correctly in this patch.
An alternative approach could be to remove the relevant option buttons for these elements **IF** they are intended to remain locked at certain z-levels. One inherent issue with the implemented solution is that Sequence …
=> All elements now work with bring/send to front/back

DuggaSys/diagram/draw/line.js
Lines will no longer stop short and create a gap when trying to attach them to an ER Attribute element. Instead the line should now run all the way to the ellipse regardless of its position.
https://github.com/user-attachments/assets/538fdd2a-e24b-4a15-bb7c-b141df541e8a
=> Fixed: G1 2025 v7 #17555 fix the lines floating on er attributes

DuggaSys/diagram/draw/line.js
Changed the part where to recursive lines should be sorted out of the offset.
The logic was broken and the recursive line where not excluded from the offset.
With this change the recursive line is now not part of the line offset and the lines behave as before and multiple recursive lines can not be stacked on each other.
[Screencast from 2025-05-19 11-59-21.webm](https://github.com/user-attachments/assets/3db9b40c-5f0a-4d07-9d4c-d21140a27a26)
=> Fix Lines move weirdly with recursive

DuggaSys/diagram/draw/line.js, DuggaSys/diagram/helpers/line.js
closes https://github.com/HGustavs/LenaSYS/issues/17590.
Added bounds detection so that the lines only can be drawn to a position in an element that is within the first clicked elements y-coordinates.
Implemented a way of visually showing how the lines will look while dragging it around. Also removed the 3 line limit on activation elements.
_Video of the implementations_
https://github.com/user-attachments/assets/95b7ce5c-5b66-41ef-8c78-66a27017b395
Resizing the activation element will move the lines to unwanted positions. Arrows will also stick around weird places when resizing.
Moving an activation element will only carry with it the lines that were drawn _to_ it.
Undo/redo still a bit broken in sequence diagram, the line might not be added to statemachine or something.
=> Fixed the sequence diagram lines #17590

DuggaSys/microservices/Microservices_inverse_dependencies.md
fixes #17694 . I found two more inverse dependencies for retrieveSectionedService_ms.php and added them in Microservices_inverse_dependencies.md. The documentation has to be correct before the re-engineering of this microservice can be done.
=> Added missing inverse dependencies for retrieveSectionedService_ms.php in Microservices_inverse_dependencies.md #17694

DuggaSys/diagram.css
The buttons did not disappear, they were out of the screen because the diagramFileName created overflow. The solution was to set a max-width on it and then place a overflow hidden and text-overflow ellipsis on the p-tag. This creates an ellipsis implying that the file name is longer only when the name is longer than the width of the diagramFileName. see video 1 for illustration. 
Fixed the issue #17703 
video 1
https://github.com/user-attachments/assets/2fe3ca35-899f-4b61-83ed-457eb11e715b
=> Fixed: Fix so fab buttons doesn't disappears when loading file

DuggaSys/diagram.css, DuggaSys/diagram.js, DuggaSys/diagram.php, Shared/css/style.css
Made a working fab-button for the options menu that is only visible at mobile version.
Added a close-button to the options
menu. Also only visible when user is on mobile version.
https://github.com/user-attachments/assets/ab271a48-5ab5-4385-a5a6-a532d3868f13
=> Fixed: G1 2025 v7 #17431 implement mockup for the option panel

DuggaSys/microservices/endpointDirectory/microserviceUI.php
Added a query to get dependencies and added another table to the dependencies. Now both inverse dependencies and dependencies for a microservice are displayed. 
Only inverse dependencies was displayed before. Fixes #17721
=> Add dependencies to microserviceUI #17721

DuggaSys/gitfetchService.php, DuggaSys/microservices/sectionedService/createGithubCodeExample_ms.php, DuggaSys/test_gitfetch.php
The problem I found was that when a new course is created, the files from the GitHub repo are not downloaded into the course folder (courses/"cid"/Github/) like they should be.
I’m committing the changes I’ve made so far related to the GitHub file download when a new course is created.
I don’t even know if this is the actual problem we’re supposed to fix, but I tried to make it so the files from the GitHub repo are downloaded automatically. I got it working through a separate test file, but couldn’t get it to work properly from the normal course creation automatically.
I’ll commit what I have anyway, just in case it helps or someone else knows how to continue from here. I’m a bit lost. 
#17702
=> Tried to fix GitHub functionality #17702

DuggaSys/diagram.css
The problem were not that the elements didn't show, because they are always "visible". The problem was that depending on the users screen size, they may had to scroll down in the whole browserwindow. This made some options "disappear" when they in reality only were outside of the screen. To fix this, I implemented a scrollbar in the options panel and styled it a bit to make it fit in more (it can still be a lot nicer).
**NOTE:** This scrollbar only works in web browsers that uses chromium. The other ones gets the default ugly looking gray scrollbar.
https://github.com/user-attachments/assets/06e32b75-9005-49f8-b4b8-ac401f651fa0
=> Fixed option menu does not show all options

DuggaSys/diagram.css, Shared/css/style.css
This solution is not good but does the job. I changed the z-index from 10 to 5000 but the user can still make the object appear above the FAB and the menu-buttons if the "Bring to Front" is pressed enough times. I can try to implement a better solution for this but it has to be made next week (G1-2025-v8).
https://github.com/user-attachments/assets/7e0d2d47-d76d-4ad5-8c17-242c64fbed73
=> Fixed elements placed on the canvas is above the FAB

DuggaSys/templates/diagram_dugga.html, Shared/navheader.php
I have implemented the approved mockup #17485, with a slight change from the mockup being the buttons are not placed above and are following the same approach as the option panel btn is. The diagram dugga now only consists of the diagram on the page but the general information and instructions are hidden from the user until one of the button are clicked, and the information is shown. This enables the user to smoothly work on an assignment by toggling the instructions and then model it with no interference. See video 1 for a illustration on how the implementation works. 
video 1 
https://github.com/user-attachments/assets/51795538-de62-45ec-ad12-ea16a440ec56
=> Fixed: Implement the diagram integration in show_dugga

DuggaSys/diagram.js
Now multiple sequenceActivations are allowed to snap, at the same time, to a lifeline when they are box selected. However if there are different elements within the box selection (in addition to sequenceActivations) the erratic behaviour still persists for these. This problem was there before this fix but at least sequenceActivations now behave correctly. The bug is a minor one as the user will seldom attempt to box select-snap a mixture of elements not belonging to a sequence diagram when that diagram type is the focus. This could be targeted in a future issue should it be deemed necessary.
https://github.com/user-attachments/assets/dc4c0083-72e8-4654-a61a-e6c2bc6f4418
=> Fixed: Multiple activation element snap bug

DuggaSys/diagram/draw/line.js
The solution to the issue [#17563](https://github.com/HGustavs/LenaSYS/issues/17563) "Improve the segmented lines" did not require redefining how a line’s start and end points are set, adding complex proximity logic, or rebuilding the line rendering system to switch between bent and straight modes.
Instead, the fix was much simpler: by updating the drawLineSegmented function, the line (or arrow) now automatically draws straight when the connected elements are nearly aligned. This approach improves the visual result without altering any core behavior—just a smart enhancement to the drawing logic.
https://github.com/user-attachments/assets/50d32af2-d4df-4a1e-9def-48f4e95c851b
As the video shows, the solution did fix the problem, but there is a small bug that makes the arrow look weird.
=> changes to drawLineSegmented

DuggaSys/diagram/draw/line.js
You are now able to see the arrows properly and they align with the line
This is a known issue that was here before i started and unfortunately has stayed I would love to try and fix it after the weekly merge
=> G1 2025 v7 17559 arrows are wrong in state diagram

DuggaSys/diagram.css
A function in toggle.js made inline styling which overrid diagram.css. Resulting in the hover effect being useless. Added !important to the hover class to make sure it is always active. Make sure to check issue #17718 for a video of before this change as reference.
=> Fixed hover effect in options panel

DuggaSys/diagram.php, DuggaSys/diagram/draw/options.js, DuggaSys/diagram/events/mouse.js, DuggaSys/diagram/globals.js
This is an implementation of the feature mentioned in the following issue: (#17731). It allows for the options panel to toggle automatically upon selecting elements, which allows for a smoother interface and a faster and easier UX. 
**It works as follows:** 
By default the options panel will open when selecting an element to edit, and it will hide as soon as either the canvas or the toolbar is clicked. 
The user can also lock the toolbar into a desired position i.e. they can open the toolbar before placing any elements and it will remain open until the user closes it. During this state it stays unaffected by any automatic toggle-attempts following selection and de-selection of elements.
Similarly, the user can close the toolbar if they wish to keep it closed while editing elements, and it …
=> Implemented feature: Automatic options-panel toggle

DuggaSys/diagram/draw/line.js
With the way the entire system for drawing lines and determining the connection type between them, it is essentially impossible to implement logic to "fix" the line moving issue described. To do that a large amount of code would have to be rewritten to accommodate a better way of determining it, as it's currently determined by the middle point between two elements instead of the lines position relative to the elements. This code also affects all lines which could cause a lot of issues if all lines aren't accounted for.
In order to somewhat alleviate the problem presented, the leniency of the determining system has been increased. There is now a dead zone which retains the current connection type until the border of the opposite type is crossed. This is as mentioned not a complete fix to …
=> [#17616] Decreased sensitivity of the way the system determines line connection type

DuggaSys/microservices/Microservices Documentation/gitCommitService.md
Created a new documentation file - gitCommitService.md.
Documented these files:
- clearGitFiles_ms
- fetchOldToken_ms
- getCourseID_ms
- insertIntoSQLite_ms
- newUpdateTime_ms
- refreshCheck_ms
- refreshGithubRepo_ms
- retrieveGitCommitService_ms
Unsure of the types related to the token parameters though.
=> Documented files in gitCommitService

DuggaSys/diagram.css, DuggaSys/diagram.php
Added a media query that had the width values inbetween mobile and desktop and displayed it as none to remove its existance. Make sure to check issue #17739 for reference.
=> Removed visible icon when over the mobile width limit

Shared/css/blackTheme.css
I think this is what the issue wanted.
Only added the hamburgerBox tag to the dark mode file and gave it the correct color
pic of how the dropdown looks in dark mode now.
=> Changed the background color of burger drop down on mobile #17495 V2

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagram/toggle.js
I have implemented the mobile tooltip and have made so that when the user holds in the toolbar modes or the replay buttons, the tooltips appear on the top right corner of the screen with reasons to cause as low intereference to the modeling. see video 1 for illustration on how it works. If the tooltips should work on the option panel button as well, just add the mb-tooltip class and an if-statement on `tooltipPosition()`. 
video 1
https://github.com/user-attachments/assets/7ba47946-069c-490b-9a20-9ec735d31999
=> Fixed: Implement the mobile tooltip from mockup

DuggaSys/templates/diagram_dugga.html, Shared/css/mobile-diagram.css, Shared/css/style.css
I have now made so the top menu sidebar has the highest priority when it is open. So, all the other elements are either placed under it or hidden. The fab button was easy to fix because you needed to change its z-index to something lower than the sidebar, however that solution didnt work with the other to buttons (general information and instructions). Because when you tried to lower the z-index on them it disappeared and was behind the iframe, then the solution was to access the elements from the iframe and make buttons disappear when the toggle icon sidebar was clicked, and for every click you check if the sidebar is open or not. If it is open then hide the buttons, and if not display them only after a delay to make it more smoothly and less snappy. 
see video 1 
video 1 …
=> Fixed: Fix the toolbars z-value and position in mobile

DuggaSys/diagram/draw/element.js, DuggaSys/diagram/draw/options.js
Since a 10-character limit on stereotypes would feel too restrictive from the customer’s perspective the maximum length has now been extended to 30 characters. While it may be unlikely that such long stereotypes will be used frequently, it is still  beneficial to support them to ensure flexibility and avoid limitations for those cases that it may occur. The goal was to make this increase possible without breaking the layout such like cut offs, overflow or text continuing in a new row.
What has been done:
- Implemented logic to dynamically shrink stereotype text when it exceeds 20 characters
- Used lengthAdjust and textLength to fit long text within the box without unnatural behavior occuring.
- Preserved default size and readability for shorter texts (i.e ≤20 characters)
Down below you …
=> Fixed stereotype length issue#17565 stereotype

DuggaSys/templates/dugga5.js
This PR complements PR [#17654](https://github.com/HGustavs/LenaSYS/pull/17654#event-17716343158) (which I reviewed), as I realized there were some remaining jQuery I initially missed since it was not the usual `$` sign syntax. I noticed this while working on PR #17527, which involves converting jQuery to JS in the `dugga1.js ` file - a file with a similar structure to dugga4.js.
Additionally, I noticed the use of jQuery's `$.getScript()` which I forgot to address in the review of  PR [#17654](https://github.com/HGustavs/LenaSYS/pull/17654#event-17716343158). Since there is no direct equivalent for this in JavaScript, replacing it would require a custom implementation. This is too big part this issue and should therefore be addressed in a separate issue.
=> COMPLEMENTS PR #17654: Convert JQuery in \DuggaSys\templates\dugga5.js - #17534 

DuggaSys/diagram.js
This PR fixes issue: #17842
Previously, hovering over a toolbar button with a submenu caused the tooltip to overlap the submenu, demonstrated below:
_Tool tip overlaps the sub menu._ 
An if-statement has been added that repositions the tooltip-box position if a submenu is present, eliminating the overlap. Additionally, the margin differences were also adjusted and the tool tip box now sits just as flush to the submenu as to the tool bar. This is what the behavior looks like now:
_Overlap eliminated by the repositioned tool tip. Margin between tool tip and sub menu reduced (compare this with weekly branch)._
=> Fixed: Tooltip overlaps submenu

DuggaSys/templates/dugga4.js
This PR complements PR [#17723](https://github.com/HGustavs/LenaSYS/pull/17723#event-17737125675) (which I reviewed), as I realized there were some remaining jQuery I initially missed since it was not the usual `$` sign syntax. I noticed this while working on PR #17527, which involves converting jQuery to JS in the `dugga1.js ` file - a file with a similar structure to dugga4.js.
=>  COMPLEMENTS PR #17723: G3 2025 v7 #17532 convert jquery to js in dugga4.js

Shared/css/blackTheme.css
Fixed the darkmode of the codeblock when editing in codeviewer.
Before
After
This did however add a new problem where some of the icons arent clearly visable in darkmode. Ive already made a new issue for that [here](https://github.com/HGustavs/LenaSYS/issues/17848)
=> Editing a codeblock is not in darkmode #17455

DuggaSys/diagram/draw/line.js
Arrows should now be visible again when using SE lines between sequenceActivity elements. Had to update icon draw logic with an extra check condition for straight lines since SE and SD are situated within the same code block. Also updated the iconX/YModifier variable to not start as null which caused errors. Since this whole if-statement wasn't properly indented I also enhanced its readability.
https://github.com/user-attachments/assets/ae2beec8-4c48-4d11-825f-97582ad41a6f
=> Fixed: #17790 Arrows no longer show up on sequence lines

DuggaSys/diagram.js, DuggaSys/diagram/draw/options.js
The real-time typing for the elements is back, AND the undo/redo works. In other words; the undo/redo doesn't remove one letter at the time, it removes the latest save or when the user presses "enter". Also the user can se the typing directly in the element. I had to remove the stateMachine.save in the function saveProperties() and only have it in the blur event.
https://github.com/user-attachments/assets/a6813a5c-93d7-4236-bd62-1a531035c0f6
=> Fixed G1-2025-v8-#17695-real-time-typing-in-elements

Shared/css/blackTheme.css
This PR addresses issue #17600 where a dropdown contrast issue made the text in dropdown difficult to see. I fixed this by adding a override for the dropdown inside of blackTheme.css and changing default text label color to white (#fff).
Here is what it looked like before:
Here is what it looks like now:
- Go into any course logged in as brom and tap the "edit course access" button. Then validate changes made for this PR actually work.
- Ensure changes don't break any other feature utilizing blackTheme.css.
=> (mobile-view) BUG Wrong darkmode contrast on dropdown text in accessed.php #17600

DuggaSys/templates/dugga1.js
Replaced jQuery with JS in `/DuggaSys/templates/dugga1.js`. 
Additionally, the toggle feedback and show/close facit features has not been introduced to the page yet, making it impossible to verify whether the JS conversion works as intended. Related functions: `toggleFeedback()`,  `showFacit()`, `closeFacit()`
The `toggleInstructions()` and `toggleFeedback()`  functions in the end of the file have not been converted as there is no direct JavaScript equivalent for jQuery's `slideToggle()`  function, replacing it would require a custom implementation. This is too big part this issue and should therefore be addressed in a separate issue.
=> Replaced jQuery with JS in dugga1.js

DuggaSys/templates/diagram_dugga.html
I added a function so it can be reused in the click listeners. The function checks if either the sidebar or the option panel is open, if it true then it hides the buttons, if not then it displays the buttons after a delay. I needed to add this function to both the option fab and the close btn because otherwise the buttons would stay hidden because i could not press the option fab since it is under the option panel when it is active. see video 1 on how the solution works. 
video 1
https://github.com/user-attachments/assets/d2e519ef-2a29-4e33-8fbc-f6a6b5c64037
=> Fixed: Make the showDugga buttons be behind ui elements in mobile

DuggaSys/diagram.css
Previously, users could hover over a disabled icon. This could give a misleading impression that the icon was clickable or active. With these changes; opacity and no hover, it is now clear that the icon is inactive and cannot be clicked. The message "You don't have anything to save!" still appears if the user presses Ctrl + S. Additionally, the border around the Save and Save As icons has been removed, making them more consistent with the rest of the icons.
=> Fixed: G1-2025-v8-#17844 refine the appearance of the save and save as buttons

DuggaSys/tests/microservices/sectionedService/createGithubCodeExample_ms_test.php
Fixes #17813 and adds a test file for createGithubCodeExample_ms. You'll find it in tests/microservices/sectionedService/createGithubCodeExample_ms_test.php. The third test case currently fails, consistent with other existing tests due to the new database schema since last year. The third test could be passed by hardcoding values that match the current database, but this would not be sustainable (as we notice happen with the old tests not passing the third test). This was mentioned in PR #17830.
=> Created test for createGithubCodeExample_ms_test.php

DuggaSys/diagram.js, DuggaSys/diagram/events/mouse.js
To make the code differentiate mouse clicks and phone touch, I had to change the eventListeners to pointer instead of mouse. I also had to add an if-statment to check if the pointerType is a mouse or not.
You can now only open the options panel by double clicking with the mouse and not with touch.
https://github.com/user-attachments/assets/fcef9ae0-c74b-4afd-966d-c05872e6c436
=> Fixed remove option panel double click on mobile

DuggaSys/diagram.css
fixed the issue where the bottom toolbar icons would disappear when resizing.
https://github.com/user-attachments/assets/53d5e6c6-c30a-4166-bf95-3ec88c0dbeaf
=> Updated diagram.css

DuggaSys/microservices/profileService/retrieveProfileService_ms.php, DuggaSys/tests/microservices/profileService/retrieveProfileService_ms_test.php
The test is located at: tests/microservices/profileService/retrieveProfileService_ms_test.php. 
The third test case is currently failing, which is consistent with other existing tests since the database schema update last year. While it's possible to make the test pass by hardcoding values that match the current database, this approach is not sustainable.
=> create a test for profileService/retrieveProfileService_ms.php #17810

Shared/css/style.css
This PR is connected to the relevant Issue #17832 
--
This PR also simply removed a "}" that broke the styling of the buttons relevant to the Issue
=> mobile buttons overlap #17832

DuggaSys/sectioned.js
I got rid of the NONE alert that appears when trying to create a element
=> got rid of the NONE alert in section.js #17620

DuggaSys/diagram.css
The #diagram-toolbar element already contained enough content to require scrolling on smaller screens.
However, without overflow-y: auto, the browser didn’t allow scrolling, which caused the layout to break or clip icons.
With overflow-y: auto and height: 100vh, the browser now detects when the content overflows and automatically shows a scrollbar as needed.
https://github.com/user-attachments/assets/71869b0c-4d0a-43e1-95a1-698a4ffd4627
As demonstrated in the video, when the screen height becomes too small to fit all toolbar icons, vertical scrolling is enabled
=> Added: overflow-y: auto;

DuggaSys/codeviewer.js, Shared/css/blackTheme.css, Shared/css/codeviewer.css, Shared/css/style.css
I have changed some of the colors for the darkmode codeviewer since it was hard to read before. Lightmode has been slightly affected as well since I could not find a darkmode option for HTML, so I changed the colors to work better in darkmode while also being readable in lightmode. The lightmode comment color has been slightly darkened for better readability. The colors used for darkmode are colors usually used in IDEs when darkmode theme is used.
JS Before:
JS After:
HTML Before:
HTML After:
=> G3-2025-V8-#17629 darkmode codeviewer hard to read

DuggaSys/diagram.css, DuggaSys/templates/diagram_dugga.html
The issue was to fix the spacing between the option-fab button and the dugga-button so they don't overlap. I added some more margin between them so that shouldn't be a problem. Although (at least for me) it wasn't the browser that was the problem. it was the size of the screen on the phone you used. When you are on a bigger phone, like Iphone XR (figure 2 below), the spacing is a little bit bigger than if you use an Iphone SE (figure 1). But I see this as a positive thing because the two dugga-buttons is a group and that should be visible, while the fab-option button is for it self.
Iphone SE:
_figure 1_
Iphone XR:
_figure 2_
=> Changed css for fab buttons

DuggaSys/tests/microservices/codeviewerService/updateCodeExampleTemplate_ms_test.php
Fixes #17807 and adds testing for updateCodeExampleTemplate_ms.php following the same standard as the other tests in tests/microservices.
To test it, go into tests/microservices/codeviewerService/updateCodeExampleTemplate_ms_test.php and see if it passes all the tests, and if it does, I assume documentation will need to be added in "codeviewerService_documentation.md" (in another issue?) that the service passed the tests.
=> Created test for updateCodeExampleTemplate_ms.php

DuggaSys/microservices/sectionedService/readCourseVersions_ms.php, DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
Fixed the codeExample part of course pages not updating when adding a codeExample. 
Now if you add a codeExample or test or whatever in a course page it should update without needing a page refresh (you still get an error you have to click away but I think that is fine?, since the listEntry appears as soon as you click it away)
=> Fixed page not updating properly

DuggaSys/diagram.js
The element should now continue snapping when moving from the breaking point, thus being placed beneath the cursor. Instead of calculating with deltas ( startx, targetPos) etc, the element is placed directly under the mouse using its center. These changes were implemented and made in the diagram.js file.
=> Fixed snapping of activation elements

DuggaSys/diagram/toggle.js
The A4 templates was placed incorrectly and not from the origin, also when trying to load A4 templates the system displayed some incorrect behavior where it only loaded the A4 container and not the template and you had to toggle back and forth between horizontal and vertical until eventually something loaded up. These issues have been fixed
-  Updated toggleA4Vertical and toggleA4Horizontal to always reset both rectangles before showing the selected one.
-  Set explicit top/left to "0px" to guarantee origin positioning.
-  Removed duplicated calls between vertical and horizontal modes.
-  Moved logic to show a4Template into applyA4Option() so it's always visible when toggling.
-  Call to applyA4Option() added inside toggleA4Template() for immediate application of current layout.
**Fixed …
=> Fixed issue #17865 A4 template problem

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagram/events/mouse.js, DuggaSys/diagram/helpers/pointerTool.js
Fixed the issue with being unable to select and move an element using the pointer-tool on the mobile version. The user is now able to select an element, and then move it around the grid-area. 
Is this the perfect solution? Honestly no. 
However, the main problem is solved - a user can select an element, drag it around, and can open options if they press the options-button while the element is selected. Sure, the element is not visible while dragging it around (like it is when using box-select), but at this point that feels like a minor problem that can be fixed later on (and should be it's own issue as I have not managed to fix that in the four days I've been trying to solve this). 
https://github.com/user-attachments/assets/a3bd75c1-705c-4ae4-892d-25d40bc8886e
=> Fixed pointer-tool on mobile (#17545)

DuggaSys/diagram.css
Added an ellipsis on the popup so the text overflow doesn't get outside the box.
Added an ellipsis to the filenames too so they fit in the load container.
desktop:
mobile:
(the arrow-chevron disturbs me because it's over the load container. It's not a part of this issue so I'm making a new issue about this)
=> Fixed G1-2025-v8-#17901 add a limit to characters in savefile

DuggaSys/diagram.js, DuggaSys/diagram/draw/options.js
Created a for loop that iterates through the elements placed on the canvas and if the bring to front button is pressed on a Loop, Alt or Super State, nothing happens and the code return nothing.
Also removed some unnecessary console logs in the code.
=> Fixed selection conflicts when using UML Superstate and Sequence Loop templates

DuggaSys/diagram.js, DuggaSys/diagram/draw/element.js, DuggaSys/diagram/events/mouse.js
Certain elements, the ones that consisted of multiple "layers", i.e. UML Class, SD State, and IE Entity elements, were behaving weird when trying to resize them.
The cause of the bug lied in the way the elements were drawn. The _boxh_ value had been removed from the function that drew each box "layer" in the element. Without this, the elements wouldn't resize properly since boxh is crucial for all elements to resize properly. Boxh has been readded to the affected elements, while trying to keep the box-layer height ratios as similar as possible to what they were during the bug.
**The affected elements now resize properly again:**
https://github.com/user-attachments/assets/aab2c62e-0ce0-42d3-b0e5-ae3df0d816d6
=> [#17888] Fixed issue with certain elements not resizing properly

DuggaSys/diagram.css
Unfortunately, the scrollbar and popouts are both situated in the same targeted div, which made the css overflow code - that creates the scrollbar - override the popout's overflow on the x-axis. The only way I found to solve this would have been to rewrite a large chunk of the toolbar html-code inside the diagram.php-file to incorporate a specific div for the scrollbar. I had a talk to the group leader and he said that it was better to prioritize the popout menus rather than having a scrollbar for the toolbar. So while this solves the problem of the popouts not showing, it isn't really a complete solution. Hence the Issue #17756 for the scrollbar will probably get reopened for someone to try to implement in a better way that doesn't remove the popouts. …
=> Fixed: Tool sidebar no longer showing up when hovering over toolbar #17927

DuggaSys/diagram/toggle.js, Shared/css/mobile-diagram.css
Added logic to toggle the sidebar-open class on the <body> element when the mobile sidebar is opened or closed.
This class does so the fab buttons is invisible while the sidebar is active.
https://github.com/user-attachments/assets/64f8f9b1-d51c-4f15-817b-bb79859b4a51
=> Fixed G1-2025-v8-#17921 sidebar should cover fab button on mobile

DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php, DuggaSys/tests/microservices/sectionedService/removeListEntries_ms_test.php
Fixes issue https://github.com/HGustavs/LenaSYS/issues/17814
To test comment out the delete part:
`'query-after-test-1' => "
DELETE FROM listentries WHERE lid = 9999;
",`
Check the database table "listentries".
A new row should appear and the value visible should change to "3".
Had to add "include_once "../curlService.php";" in updateCourseVersion_sectioned_ms.php because it uses the function callMicroservicePOST.
The file removeListEntries_ms.php has an include to updateCourseVersion so would get error without the new include.
=> G2 2025 v8 #17814

DuggaSys/diagram/draw/options.js
The **Bring to Front** button is no longer displayed in the options pane for the UML SuperState and Sequence Condition elements. 
The description of the issue was to make it greyed out and unclickable, but that seemed a bit uneccessary, since it would've just made it so that the options pane included an "empty" button with no functionality. This felt like it would've been cluttered and a bit misleading so I chose to just remove the button displaying for those elements altogether. Readding the button with the greyed out style and unclickability isn't a difficult thing to do, _just add the button to the else statement with the proper modifications_.
**How the options pane looks now (The Sequence Condition element is identical from the save button down):**
There is an issue with the bring to …
=> [#17957] Changed visibility of buttons in options pane for UML SuperState and Sequence Condition elements

Shared/css/markdown.css, Shared/css/style.css
Fixes #17860 
- Multiple CSS on the same element has been removed so only styling from `style.css` is now active 
- All styling about the headers in `markdown.css` has been removed
- Added styling for headers with no styling or different styling from the rest
Before:
After:
=> G3 2025 v8 #17860 fix h3 styling fileed

DuggaSys/sectioned.js
Added dots and commas as legal names when editing a section name.
Name can now contain . or , and still be valid.
=> G3 Added dots and commas as legal names

DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
Fixes #17954 . I've simply removed "global  $pdo" from createNewListEntry_ms.php as this gave an error before and it should be enough with pdoConnect();. The error disappeared but I don't think it made any difference to the functionality when creating a new list entry in a course (for example a new section).
But I found another issue which I don't think is related to this issue and I'm not sure if it's our re-engineering of microservices that broke it or if the issue was there already (it's also in the master branch). When a new list entry is created you can see it in the UI but it's not inserted to the database. I will create a new issue for this if the reviewer confirms it as well.
=> Fixed $pdo error in createNewListEntry_ms.php #17954

xampp/setup.sh
Fixes #17984.
I found out why the page was empty, the problem was with the log folder, because it needs the correct permissions and inside this contains a database file.
To fix this, I needed to add permissions to 777 for the `htdocs/log` folder, but to prevent another permission errors, I chose to add the permissions recursively to the whole `htdocs` folder. To make sure not make any new error.
=> Fixed course page shows empty. Linux and macos only.

newinstaller/installer_ui.php, newinstaller/style.css
The page class had `display: flex` when the page loaded which caused page 1 and 7 to be visible and didn't get display: none until the user changes page. Fixes #18052 
I replaced flex with none on the page class and gave page1 `display: flex`. 
Only page 1 should be visible now and the page navigation will still work.
=> Fix initial page on newinstaller/installer.php  #18052

dockerenv/setup.sh
Fixed #18054. 
I renamed `CHMOD_CMD` to `CHOWN_CMD`.
**How to Test:**
1. Open the terminal and navigate to the `LenaSYS/dockerenv/` directory.
2. Run the script: `bash ./setup.sh` or  `./setup.sh`
3. Open `Docker Desktop`. 
4. Go to the `containers tab`. 
6. Click the three dots on the apache-php container and select the `Open in terminal`.
8. In the terminal type: `ls -l`
You should now see your username and group:
macOS: _username_:_username_
Linux: _username_:_username_
=> Fixed the typo. Only macOS and Linux

Shared/css/style.css
**This is a retread of [#18043](<https://github.com/HGustavs/LenaSYS/pull/18043>) due to a bug causing the cogwheel on courseed.php to stop working.**
- Logout button is now visible on smaller screens while logged in as admin.
- Hamburger icon now uses a `<button>` element.
- Removed some inline styling
- Moved media query to a more suitable location
- Fixed issue with unused elements not disappearing from the DOM.
The fix for the unused elements uses `!important` which is not great. I will create an issue for another problem I encountered which will also remove the need to use `!important`.
`Pick a course -> Login as admin (brom) -> Test different screen sizes`
=> G3 2025 v8 the logout button is not in view #17928

DuggaSys/courseed.js, Shared/dugga.js
Upon updating MOTD, it disappears for the user updating it. May cause an error for users also, has not been tested, however this issue has been fixed by updating the show value within sessionstorage upon submitting the form.
=> G3-2025-V8-#18082-BUG MOTD not displayed correctly
