HGustavs/LenaSYS

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Made it so you can see how nodes and edges are connected. the output shows up in The console when you click the test case button.
There is also an alert that pops up that tells you the amount of lines and nodes.
Send me a dm on discord if you want to use the diagram I tested against.
> G1 2023 v3 #13437

- recursivetesting/FetchGithubRepo.php
When resolving merge conflicts I missed includes.
Pull request in question #13515
> Added missing includes to PR #13515

- Shared/css/blackTheme.css
We added box shadows in the profile page.  
Files changed: blacktheme.css 
To test: https://cms.webug.se/root/G3/students/a21lukpo/LenaSYS/DuggaSys/profile.php
> G3 2023 v3 issue#13501

- DuggaSys/sectioned.js
- DuggaSys/sectionedservice.php
- Shared/basic.php
For issue https://github.com/HGustavs/LenaSYS/issues/13478 so we can continue in https://github.com/HGustavs/LenaSYS/issues/13421
Modified the sqlite database to better handle what we currently want to use it for
> SQLite modification

- DuggaSys/diagram.js
Remade the function that generates the state diagram info so that its output matches the desired output listed in #13517.
> G1 2023 v3 #13517

- DuggaSys/diagram.js
Both lines and arrows now connect for SD elements.
> Lines don't connect vertically #13540

- DuggaSys/diagram.js
Issue: https://github.com/HGustavs/LenaSYS/issues/13539
> When a width limit is reached it stretches vertically to make more space

- DuggaSys/sectioned.js
- DuggaSys/sectionedservice.php
- recursivetesting/FetchGithubRepo.php
Added refresh button to moments.
> G3 2023 v3 issue#13452

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
Added the zoom indicator to the zoom container and changed some css
> G1 2023 v3 #13486

- recursivetesting/FetchGithubRepoVisual.php
Simply recreated the visual representation that previously was found in FetchGithubRepo.php, now it's found in the separate file FetchGithubRepoVisual.php, to test this open the FetchGithubRepoVisual.php-file and add whatever repository link you want to try it with, preferably a smaller repository in the code shown below.
`// Here you paste the appropriate link for the given repo that you wish to inspect and traverse.
GetGitHubURL('https://github.com/e21krida/Webbprogrammering-Examples');`
> G3 2023 v3 issue#13475

- DuggaSys/diagram.js
Lines connecting to the bottom of IE-entities wasn't quite connected before, it now is. I simply tagged onto Claes's solution in issue #13540
> Ammend IE to changes made in #13540

- Shared/log.php
- Shared/logSearch.js
- backend-models/service-tests/README.md
Created a search functionality for log.php in issue #13330
> G2 2023 v3 issue#13330 v3

- DuggaSys/diagram.js
Issue: https://github.com/HGustavs/LenaSYS/issues/13462
>  Arrows are either too big or lines have to be adjusted #13462 

- DuggaSys/courseed.js
- recursivetesting/FetchGithubRepo.php
Both of us have tested on the webserver with $json and $data set to false as per the commits. You can test this as well, by changing these variables to false in the webserver: do sudo -i , then go into your studentfolder, switch to the correct branch, go into the recursivetesting folder and then nano into the file FetchGitHubRepo.php and set these variables to false before each of their if-statements (but only one at a time). That way, you can test that these error message occur at the right time. When done, just do "git restore . " on the webserver
If the link is correct and both JSON and data is true, the course will be added. But there is a slight chance that the course won't be published because of the API has to many request recently. To solve it you need to add your API token on the …
> G3 2023 v3 issue#13410

- DuggaSys/diagram.css
- DuggaSys/diagram.php
- Shared/icons/diagram_state.svg
- Shared/icons/diagram_super_state.svg
created the button and a new icon for it. also, upon talking to the issue leader, updated the old icon for states.
> Create a button for super-states #13589 

- DuggaSys/diagram.js
Created an if statement so that SD does not get any line kind
> G1 2023 v4 #13588

- DuggaSys/diagram.js
- Shared/icons/diagram_UML_final_state.svg
changed in the svg radie and when placed
> G1 2023 v4 #13609

- DuggaSys/diagram.js
I added functionality to the button, created an svg for the SuperState. This can be changed.
> G1 2023 v4 #13613

- recursivetesting/FetchGithubRepo.php
What has been done is a general cleanup of the code within FetchGithubRepo.php. 
1) The individual parts like writing to databases have been separated out into it's own functions
2) The code that handles the downloading and writing of files and directories onto the web server has been separated out into it's own function
3) All styling has been removed.
4) Some parts of the code has been simplified to potentially save a few milliseconds, as the script takes it sweet time currently.
This means that instead of having one massive "bfs" function, we now have the functions "insertToFileLink", "insertToMetaData" & "downloadToWebServer". 
To test this, create a new course with a GitHub repository, preferably a smaller one and afterwards analyze that the information was downloaded properly into …
> G3 2023 v4 issue#13447

- recursivetesting/getLatestCommit.php
Added code for updating a course and comparing the two commits (the old one from the database, and a new one fetched with getCommit(url)). 
Test this by pulling the branch to your folder and create a new course. Use the github url  "https://github.com/c21sebar/test" to create it. Then go into getLatestCommit.php. This is the output you should get:
co-author @g21emmka
> G3 2023 v4 issue#13422 compare 2 commits

- DuggaSys/fileedservice.php
- DuggaSys/filereceive_preview.php
- DuggaSys/showdoc.php
- backend-models/microservices/fileedservice_microservices.txt
Added file services to files from Github, this PR involves checking that the files can be accessed wherever they are used, and verify that nothing has been missed or done incorrectly. 
issue#13573
> G3 2023 v4 issue#13573

- DuggaSys/codeviewerService.php
Fixed the codeviewerService file, $info variables string
> G2 2023 v4 issue#13629

- DuggaSys/sectioned.php
issue #13450  Added a dropdown with options from the sqlite database for that specific course.
what has been changed and can be viewed in the https://github.com/HGustavs/LenaSYS/issues/13450#issuecomment-1527320173
> G3-2023-v4-13450-create-a-dropdown-list 

- DuggaSys/diagram.php
Changed the SVG for the different toolbarModes
> Pop-out has the wrong icon for statediagram #13639

- Shared/log.php
- Shared/logSearch.js
Fixed:
- Timestamp
- Column names not showing up when you search
> G2 2023 v4 issue#13330

- DuggaSys/accessedservice.php
- DuggaSys/codeviewerService.php
- DuggaSys/courseedservice.php
- DuggaSys/diagramservice.php
- DuggaSys/duggaedservice.php
- DuggaSys/fileedservice.php
- DuggaSys/filereceive.php
- DuggaSys/filereceive_dugga.php
- DuggaSys/filereceive_preview.php
- DuggaSys/highscoreservice.php
- DuggaSys/profileservice.php
- DuggaSys/sectionedservice.php
- DuggaSys/showDuggaservice.php
- errorpages/404.php
Done researching and making changes in-order to label the $info variable so that we in our log.php file can see what all the other variables in $info carry in form of data. 
This new "styling" do not change the earlier tables of data, but every new log will be printed out in this new format.
> G2 2023 v4 issue#13491

- DuggaSys/diagram.js
Added an if statement to check if the line is drawn to the UML Initial State
> G1 2023 v4 #13649

- DuggaSys/sectioned.js
Clicking refreshbutton on a moment now runs the method "refreshCodeExample" on each code example within a certain moment.
This might be troublesome to test since moments are very bugged. Sometimes the codeexamples "moment" does not update properly and you might have to drag around the moments a bit and update them to apply the moments id to the code examples. You can always console.log the object "retdata" right within inspector tools to be able to see the status of all code examples within entries (see picture below)
Co-authored by b21leowa
> G3 2023 v4 issue#13453

- DuggaSys/diagram.css
added a fully transparent border
>  Fix visual bug induced in #13643 #13663 

- Shared/css/blackTheme.css
Type, Type dropdown and Name now have a white background with black text in darkmode
> dropdown and textfield incorrect in darkmode #13606

- DuggaSys/diagram.js
the labels should now be correctly displayed.
>  changed diagram.js so that arrow labels are printed

- DuggaSys/sectioned.js
- DuggaSys/sectionedservice.php
https://github.com/HGustavs/LenaSYS/issues/13549
> G3 2023 v4 issue#13549

- backend-models/service-tests/fileedservice-tests.txt
> G2 2023 v4#13398

- DuggaSys/diagram.js
Added functionallity to remove lines while the Line creation tool is active,
It should now be possible to remove the lines with the red 'X' on the screen or 'Delete' & 'Backspace' buttons on your keyboard
> G1 2023 v4 #13640

- Shared/css/blackTheme.css
- Shared/css/style.css
Check the color of the field when entering message of the day in courseseed.php:
> G3 2023 v5 issue#13677

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
The "load" button is now toggled instead of fixed. It has also been styled according to the design of the options-pane
> Toggle load button as well as dropdown #13680

- backend-models/functional-requirements/FRD_codeviewerService.md
Added the missing content as requested!
> Added missing content to codeviewerService.md

- DuggaSys/diagram.js
Added comments for mdown(event) function. Solves #13705
> Documentation for mdown(event) #13705

- DuggaSys/diagram.js
checked if the default is null with console log and then after i removed the TODO
> G1 2023 v5 #13711

- DuggaSys/diagram.js
Added an else if to check which kind of element it is and if its a line from UMLFinalState then you can not draw a line from it to another element but you can draw to UMLFinalState
> G1 2023 v5 #13682

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Fixed keybinding for UML initial state, UML final state and UML super state.
> Fix keybinding functionality for UML Initial State #13701

- backend-models/functional-requirements/FRD_highscoreservice.md
i have remade this document with what i hope is the correct information.
close #13653
> G2 2023 v5 issue#13653 - Add missing content to FRD_highscoreservice.md

- DuggaSys/diagram.php
Added descriptions to diffrent element and functions.
Added descriptions to:
All entity types,
ER relation,
UML inheritance,
IE inheritance,
ER attribute,
Inital state,
Final state,
Lifeline,
SuperState,
Sequence object,
Sequance activation,
Error toggle
The descriptions briefly the function of each element/function. Note that the pop out boxes have diffrent descriptions based on which element is selected.
> G1 2023 v5 #13687

- DuggaSys/diagram.js
Removed all instances of cursorStyle/setCursorStyles and replaced it with containerStyle/setContainerStyle.
> Clean function "setCursorStyles"

- backend-models/functional-requirements/FRD_resultedservice.md
I added the missing content and also made minor adjustments!
> Added missing content and smaller changes to FRD_resultedservice.md

- backend-models/service-tests/sectionedservice-test.txt
> G2 2023 v5 issue#13400

- DuggaSys/diagram.php
>  Remove unused code in diagram.php #13782 

- DuggaSys/diagram.php
Removed a section of code which was commented and unused. Solves issue #13742
> Removed unused code #13742

- DuggaSys/diagram.js
Updated some "element" variables to use `const` instead of `var`. Solves issue #13783
> Variables should use local scope #13783

- DuggaSys/diagram.php
- DuggaSys/modules/search.module.js
a module has been implemented. The import works but currently whatever value you send in will give null because the php side has not been set up yet. I think i have managed to implement what the issue linked to this pr is after
> G1 2023 v5 #13734

- DuggaSys/diagram.js
- Shared/css/blackTheme.css
I changed so that the states are white in darkmode and white in dark mode
> G1 2023 v5 #13737

- DuggaSys/diagram.php
created a new function when fetching the courseId and did, gives the same response as before.
> G1 2023 v5 #13769

- DuggaSys/diagram.js
Removed the TODO because it was not valid in this case. What i think the TODO was for was the keybinds in the code that it was named delete key and they wanted to change it to delete or del. In the event restoreState() keys are different attributes of the state like id kind x and y therefore it was an unvalid TODO because there is no key for deletion except for the keybinds.
> G1 2023 v5 #13798

- backend-models/functional-requirements/FRD_courseedservice_functionalrequirments.md
Co-authored-by: c21axepe c21axepe@student.his.se
> added test proposals to courseedservice

- backend-models/service-tests/fileedservice-tests.txt
Created 3 different tests for the file fileedservice.php
> fileedservice-test.txt file for Issue#13398

- DuggaSys/diagram.php
the php code has now been removed from diagram.php as according to the issue. Do to scoping issues with modules after talking to issue responsible we decided to just include the module functionality in diagram.php and remove search.js. There are also some issues with the output  that will give errors but those are other issues that will be fixed. the output that you get with the php code there and without the php code is the same.
> G1 2023 v5 #13735

- Shared/test.php
> Added the option "name" for a test

- DuggaSys/showDugga.php
- DuggaSys/templates/diagram_dugga.html
fixed the left side description on the dugga site to not vanish when the closing animation plays.
> G1 2023 v5 #12889

- DuggaSys/diagram.js
Removed the code that was causing the bug, you can now switch to overlapping and move it around with out it breaking the diagram.
> G1 2023 v5 #12883

- DuggaSys/diagram.js
Added variable to remove magical number and to add meaning. Removed #TODO comment
> Fix magic-number TODO #13724

- DuggaSys/diagram.css
- DuggaSys/diagram.js
Added vertical nodes for super state, did not make the design conform to wanted notation so that will have to be a separate issue.
> Superstate should be scalable height-wise

- backend-models/service-tests/accessedservice-test.md
- backend-models/service-tests/accessedservice-test.txt
Created a txt document with tests for all services in accessedservice.php
> G2 2023 v5 issue#13393

- DuggaSys/diagramservice.php
Fixed an issue where fetching the diagramservice.php file would cause the server to throw a HTTP 500 error. Added an if-statement for the "github" code and moved some error-prone code into the try-catch clause. Solves #13861
> Diagramservice throws a 500 HTTP error #13861

- DuggaSys/diagram.php
- Shared/icons/diagram_optionLoop.svg
added a button for sequance option loop
> added a button for sequance option loop

- DuggaSys/diagram.js
Made so that when you select and element it shows the ghosted version before you place it, so you know where you are going to place it. Every works except the IE where you dont see the lines but you can se the name and the attribute.
> G1 2023 v5 #13796

- DuggaSys/diagram.php
changed what placing type it is and the issue is fixed you can now place sequence life
> g1 2023 v6 #13906

- backend-models/service-tests/courseedservice-test.md
Updated courseedservice-test.txt to .md and added expected output
> G2 2023 v6 issue#13908

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Moved code from v5 to v6 which made all sequence buttons into a pop-out
> Added pop-out for sequence and added all the buttons

- backend-models/service-tests/resultedservice-test.md
Created a md file that contains all tests for resultedservice.php
> Created tests for resultedservice.php in md

- DuggaSys/diagram.js
Copied changes from g1-2023-v6-#13785.  Pull request Fix function linetest() #13785 #13923 should also be closed when this pull request is done.
> Fix function linetest() #13785 fix 3

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Linked the storeDiagramInLocalStorage function to the save button
> Linked the save function to the save button

- DuggaSys/diagram.js
> [NOTE: This is the PR for "v6-fix-3"] State without attributes displays incorrectly

- DuggaSys/diagram.js
Fixed positioning of label when recursive edge. Solves #13966
See pr #13997
> Label position recursive edge #13966

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/icons/diagram_load_icon.svg
Created a load button below the save button
> Create a "load-save" button. #13986

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Removed button from pop-out and changed the increment of `elementPlacement`
> Remove button for sequence object #13978

- DuggaSys/diagram.css
- DuggaSys/diagram.js
could not make it so that you can place the sequence activition on top of the sequence life but you can drag it on top of it. Added so that you can expand or make it smaller vertically.
> G1 2023 v6 #13945

- DuggaSys/diagram.js
Added checks for IE where they were missing, on top of the previous checks for UML etc.
> Changing icons for IE-entities throws TypeError #13988 

- DuggaSys/diagram.js
I made so that there is a message when saving, tried to make it so that you could not save as many times as possible, but there was a issue where if you change the type or placed another element instead of the one already in place you could not save.
That's why i chose to just it to check if the current index is -1 you can not save the diagram
> G1 2023 v6 fix 3 #14007

- DuggaSys/diagram.js
> G1-2023-v6-fix-3-#14019 Typo fix

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Since the first branch had so many issues, this is the new branch that will be merged into fix3 of v6. see #13980 for explanation on what this new element is and can do.
>  Add functionality for sequence loop or alternative #13914 new

- DuggaSys/sectioned.js
- DuggaSys/sectionedservice.php
- Shared/dugga.js
For issue https://github.com/HGustavs/LenaSYS/issues/13549
Clicking the refresh button on a moment now creates a codeexample with the name of the "selected" folder.
Since the "selected" folder/directory is not yet implemented we have a harcoded string for this.
This string is located in sectioned.js at line 3602, for your testing change this to a folder you have access to with relevant files.
Note that this is directory should only include the files relevant to the code-example, no subdirectories or any other files. Minimum 1 file and max 5 files because no support for other templates in a code-example.
A codeexample is created with the correct name.
A box for each file in the folder is created and linked to the code-example.
A listentries is created linked to the codeexample with the …
> G3 2023 v6 issue#13549

- DuggaSys/diagram.js
>  Clipping outlines for superstate and sequence activation #14038 

- DuggaSys/sectioned.js
- Shared/css/blackTheme.css
- Shared/css/style.css
Changed the color of the cogwheel and trashcan so they are visible in light mode. 
To test this navigate to a course in courseseed.php and create a new heading using the fab-button. Switch dark and light mode and see if the icons are visible. You can also look through the code to see that it does not conflict/override any other styling. 
Worked with @b21geoyo on the some of the latest commits.
> G3 2023 v6 issue#13939

- DuggaSys/fileed.js
- Shared/css/blackTheme.css
- Shared/css/style.css
The issue branch #13771 has been rebased to g3-2023-v6.
To test this issue go through the issues that were listed in the comments of #13771 and make sure that the issues have been resolved.
To see if the issues have been resolved go to LenaSYS directory in your server version then use the commands below:
```
sudo git switch g3-2023-v5-issue#13771
```
Then you have to use git pull
```
sudo git pull
```
> G3 2023 v5 issue#13771

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/blackTheme.css
Added a pop-up modal that lets the user select a save from localStorage (Currently a dummy array with fake values)
> Added functionality for "Load"-button

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
We have now added functionality to the moments dropdown were it saves the last selected option in local storage. This can be tested by choosing an item within the moments dropdown and then closing it. Open the moments dropdown once again and the last selected option should still be selected.
> G3 2023 v7 issue#14065

- backend-models/functional-requirements/FRD_profileservice.md
Renamed header columns in FRD_profileservice.md
> G2 2023 v7 issue#14035

- DuggaSys/codeviewer.js
- DuggaSys/codeviewer.php
- Shared/navheader.php
This PR handles where the manual order selection for code examples was found not functional due to our github integratioin (i think).  I decided to comment out the code for those function instead of removing them completely. In order if a  reimplementation is needed, it should take secounds. PS I wrote wrong issue number on my branch
**Please note that no code was removed in this PR.**
> G3 2023 v7 issue#14021

- backend-models/microservices/microservice_priority.md
This PR closes issue #12921 
A priority list for the microservice transition of services
> G2 2023 v7 issue#12921 priorities microservices

- DuggaSys/diagram.js
fixes #14092
this appears to work as expected when testing but wwhen reviewing check so that i have not missed changing a variable name somewhere.
>  fixed duplicate variable declaration in diagram.js

- DuggaSys/diagram.css
- DuggaSys/diagram.js
Scrollbar is set once the container for the buttons goes over 200px.
The only way i know of testing this as far as I know is to manually add items to the array
> Set max-height and scrollbar to load-screen #14114

- DuggaSys/diagram.css
- DuggaSys/diagram.php
Moved some styling from html to css. Solves issue #14088
> Inline styling in diagram.php #14088

- DuggaSys/diagram.js
> Comparison may cause unexpected type coercion #14091

- DuggaSys/diagram.php
fixes #14082 
make sure that the design is still good when reviewing.
>  moved some p tags in diagram.php

- DuggaSys/diagram.php
> removed a duplicate attribute inside diagram.php

- DuggaSys/sectioned.js
- Shared/SQL/init_db.sql
- Shared/basic.php
- recursivetesting/FetchGithubRepo.php
Removed the changes added in the closed PR # 14127
Co-authored by b21leowa
> G3 2023 v7 issue#14144

- DuggaSys/diagram.js
- Shared/css/blackTheme.css
- Shared/css/style.css
The box-selection lines are white when the user is in darkmode.
> Box selection line is white in darkmode

- backend-models/microservices/duggaSys services/Potetial_micro_services.md
Changed the name of a micro-service
> G2 2023 v7 issue#14123

- DuggaSys/diagram.js
IE has now the outlines so that you can see them,
> Added stroke #14057

- DuggaSys/sectioned.js
* The updateIntervallForCodeExamples is set to 1 minutes, so the day we have presentation we can showcase the automation
* I removed some unnecessary console log to reduce the messy console logs. Some that is reasonable for development remained
* I've added user notification with the basic inbuilt javascript alert function. User will get different alert depending on scenario:
1. Failure to fetch code examples (both for automated and manual)
2. Succesfully fetched of automated code examples
3. Succesfully fetched of manual code examples
The goal of this PR is to simply improve user experience and give a bit of feedback depending on scenario and improving the cleanliness of the function including console logs for development.
**For the manual alert testing, you need to have a github url in …
> G3 2023 v7 issue#14103

- DuggaSys/diagram.php
>  fixed a space missing in diagram.php

- Shared/navheader.php
@a21olljo Double check if this is what u wanted
close #14050
> G3 2023 v7 issue#14050 revert

- DuggaSys/tests/duggaedservice-tests.php
- Shared/test.php
Tests for duggaedservice.php.
Every test is tested and all tests passed when me and anton ran the api
> G2 2023 v7 issue#13854

- DuggaSys/diagram.js
It is now possible for ER-entities to switch between single and double-kind lines.
NOTE: Recursive does not work and im not quite sure how it is supposed to work either since a line can't be drawn to itself anyways.
> Line kinds not working #14135

- DuggaSys/diagram.css
updated the style for the menu buttons to be more prominent
> Clearer visability for toggled buttons #14118 

- DuggaSys/diagram.js
there was an old if statment that is never used that got activated by notes special dashed lines, the if statment tried to change a button that does not exist in the system and there for would give an error.
> Fixed error that occurred when connecting line with note

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/blackTheme.css
> Darkmode toggle button is now filled when user already have darkmode on #14072

- DuggaSys/microservices/shared_microservices/createNewCodeExample_ms.php
- Shared/dugga.js
Moves the functionality to create new items to a microservice and changes to dugga.js to ensure that it is called when creating new items.
The call to the microservice is not commented out, as it doesn't interfere with basic functionality.
> G2 2023 v7 14154 create microservice createnewcodeexample

- DuggaSys/microservices/shared_microservices/setAsActiveCourse_ms.php
- Shared/dugga.js
Created microservice setAsActiveCourse #14157.
DuggaSys/microservices/shared_microservices/setAsActiveCourse_ms.php
> Created microservice setAsActiveCourse #14157

- DuggaSys/courseedservice.php
- DuggaSys/microservices/courseedservice/retrieveCourseedService_ms.php
- DuggaSys/microservices/monolithic-to-microservices.md
retrieveCourseedService_ms.php created
Guide for retrieve information created
> G2 2023 v7 issue#14159

- Shared/dugga.js
All vestiges of the test redirects to the created micro services has been removed. 
dugga.js is now reverted to its original state.
> removed code that redirects to the created microservices

- markdown-testfiles/lenasys-markdown.txt
> Issue #14264 Added "test" to lenasysmarkdown test

- install/install.php
Created pull request for issue #14821.
> Added option to enable "Using Docker" in installer.

- DuggaSys/diagram.php
Reverts HGustavs/LenaSYS#14300
This issue should not have been merged and is not on the correct branch
> Revert "Fixed savebutton in diagrams.php (#13984)"

- install/install.php
Replaced the ob_end_clean() method with ob_clean() method to only clear the current output without ending the entire output buffering.
> modified the installer

- DuggaSys/microservices/sectionedService/createListentrie_ms.php
Created the microservice createListentrie under sectionedService
> Created microservice createListentrie_ms.php #14212

- DuggaSys/sectioned.js
- markdown-testfiles/lenasys-markdown.txt
- testfiles/Text.txt
Due to Async calls the console logs was printed in the console before the Async call was completed for all the objects. Therefore we had to wrap the whole Async call into a Promise and then use the Promise from setInterval to ensure that the Async call was completed in its entirety before logging the success.
closes #14241
> G3 2024 v1 #14241

- DuggaSys/gitcommitService.php
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
Essentially adds an html window for adding a github repo which opens when trying to download a repo from a course that does not have one.
For testing i'd recommend setting shortdeadline and longdeadline in gitcommitservice.php to 0, as otherwise there is a cooldown of 10 minutes on the button which opens the window.
> G3 2024 v1 #14315

- DuggaSys/duggaed.php
@a22willi found the solution was to start the session before including any files.
> Moved starting of session

- DuggaSys/microservices/sectionedService/removeListentries_ms.php
- Shared/database.php
**Explanation on what the micro service should do from potential_micro_services.md**
removeListentries (hides the entrie, no delete it)
This will change the visibility of a listentry to deleted instead of deleting the item from the database. This will enable restoring deleted items.
Uses the services updateTableListentries to change the content of these columns:
visible = 3
**Test example for the microservice**
1. To sent DELETED ops to the microsevice, replace the "SECTION" else if block on row 1075 in **dugga.js** to this:
```
else if(kind=="SECTION"){
if (opt === "DELETED") {
$.ajax({
url: "../DuggaSys/microservices/sectionedService/removeListentries_ms.php",
type: "POST",
data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['course …
```
> G2 2024 v13 issue#14211

- DuggaSys/microservices/sectionedService/getGroupValues_ms.php
Tested by adding the following code to the function AJAXService in dugga.js
if(opt==="GRP"){
$.ajax({
url: "../DuggaSys/microservices/sectionedService/getGroupValues_ms.php",
});
}
Note: There is a problem with getting the user info for SQL inside of database.php causing warnings and errors. However I do not think this is due to faults inside of getGroupValues_ms.
> getGroupValues_ms.php #14207

- DuggaSys/diagram.js
- DuggaSys/diagramkeybinds.md
Updated keybinding to reflect order in toolbar.
Added cycling between items in all sub menus when pressing the same keybind.
> Updated keybinds, added cycling #14314

- DuggaSys/diagram.php
Fixed the syntax issues within the lines and tidied up the code to follow the same style as the rest of the file.
> Cleaned and fixed

- Shared/navheader.php
By using date() i was able to get $_SESSION['fetchCooldown'] in minutes and seconds instead of just seconds
- #14454
> fixd #14454

- DuggaSys/courseed.js
- DuggaSys/courseed.php
Updated the code so that the error messages shows on the same row as the text input. When logged in as Admin, press the "+" FAB to the bottom right and choose course. Alternatively, you could press the cog next to a course's name to edit.
(This has been updated from v1 to v2)
issue #14343
> Updated validation for new and old courses #14343

- DuggaSys/tests/duggaedservice-tests.php
The "qid" was not being fetched correctly, which resulted in assignments not being deleted. Since the old assignments remained the expected output did not match the actual output. This should now be fixed, and the tests should pass.
> g2-2024-v2 issue #14408

- DuggaSys/sectioned.js
To fix
- #14358 I added a for loop in returnedSection() because it redrew all elements that still were in the database as if they werent deleted.
> Fixed #14358

- DuggaSys/microservices/courseedService/createNewCourse_ms.php
- Shared/dugga.js
simplified the code and added comments + added new check in dugga.js. Also new code uses the getUid() system to handle login.
> fixed #14460

- DuggaSys/microservices/courseedService/deleteCourseMaterial_ms.php
I created a new file called deleteCourseMaterial_ms.php. This file can only delete things about the course, not add it.
> g2-2024-v2-#14206

- DuggaSys/diagram.js
Fixed issue introduced in merge
> Fixed accedental context clear #14483

- DuggaSys/diagram.js
Centering now works. Notification is only displayed once but the rest of the function is repeated like in previous issue.
> Updated centering #14446

- DuggaSys/gitcommitService.php
- Shared/navheader.php
- #14398
added SESSION[updatetGitReposCooldown][$cid] to refreshCheck in gitcommitService.php
So that the update cooldown is connected to courses through the course id
> Fixed #14398

- DuggaSys/microservices/sectionedService/getDeletedListentries_ms.php
- DuggaSys/sectioned.js
I've create the microservice getDeletedListentries_ms.php. It can be called from the function `getDeletedListEntries()` in sectioned.js. Remember to uncomment the code that integrates it!
Open the file getDeletedListentries_ms.php in you'r browser to see the data retrieved by the microservice.
To test the javascript function it can be executed in the browser console when visiting a page using sectioned.php (any course page).
> G2 2024 v2 issue#14435

- DuggaSys/diagram.js
You are no longer stuck when you collide with another objekt using the arrow keys.  Implemented in some code in setPos()- if(overlapping) that make the objekt take one step back if it collide.
> Fixed the collide issue

- DuggaSys/microservices/courseedService/updateCourseVersion_courseed_ms.php
- DuggaSys/microservices/updateCours_ms.php
- DuggaSys/microservices/updateCourse
Implemented a secure DB connecntion and update logic in updateCourse ms
Loaded DB credentials from a non-web-accessible file for enhanced security. Validate and sanitize input for courseID and courseName from POST-data. Included prepared statements for update of course-info.
Also implemented JSON responses for success, no change and error situations.
> G2 2024 v13 #14199

- DuggaSys/diagram.js
The problem was that delete button area was covering the element area because of the wrong “deleteBtnX” callcullation. 
I changed the “deleteBtnX” calculation. I added 5 pixels to the X-coordinate of the selected element's right edge (highX) to position the delete button slightly to the right of the element.
With this change the delete button is outside the element area and it is not possible to delete it without pressing on the element, when delete button is visible.
> fixed element delete function

- Shared/dugga.js
- Shared/navheader.php
There should now be an error message stating "Wrong username or password" when the user enters the wrong credentials for a user. This message can be seen below (the red text):
Please test that this message also appears for you (the tester) when you enter the wrong username or password when trying to log in. 
1. While logged out, an error message related to the fetching of github repos will be emitted every second, should this be fixed? The error message:
2. In the code, there seems to be an attempt to display an error message when the user has reached the log in limit. However, I found that I can spam the login button with the wrong credentials without ever getting this message. Perhaps a new issue should be made to fix this. 
The attempt can be found in the `processLogin()` function from …
> G3 2024 v2 #14556 Error message for wrong credentials

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
We have added functionality to retreive codeexamples through github.
> G3 2024 v2 #14370

- DuggaSys/sectionedservice.php
Added a query under the opt "DEL" that deletes records in useranswer that references the listentry to be deleted, before deleting the listentry itself.
> Update sectionedservice.php issue#14573

- DuggaSys/sectionedservice.php
Reverts HGustavs/LenaSYS#14591
It was not tested and destroys everythign
> Revert "Update sectionedservice.php issue#14573"

- DuggaSys/courseedservice.php
Reverts HGustavs/LenaSYS#14538'
> Revert "Fix bug in courseedservice.php #14452"

- DuggaSys/sectionedservice.php
Reverts HGustavs/LenaSYS#14595
> Revert "Revert "Update sectionedservice.php issue#14573""

- DuggaSys/diagram.js
Resizing nodes for some of the elements did not show. Nodes are now shown as intended.
> Fixed issues with nodes for resizing not showing. (#14523)

- DuggaSys/microservices/sectionedService/changeActiveCourseVersion_sectioned_ms.php
I do not know how this should be tested since the opt "CHGVERS" is not set anywhere currently (at least not what I can find).
> Created changeActiveCourseVersion_sectioned_ms.php issue#14424

- DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
The microservice has been implemented and undergone some modifications to meet the objective. The aspect that needs testing is the JSON output generated by `retrieveSectionedService` and the JSON code from other microservices. The JSON from other microservices should be appended at the bottom of an array named 'serviceInformation'. The `retrieveSectionedService` functions as a method call with parameters $pdo, $userid, and an array retrieved from other microservices.
Additional information: this microservice is not entirely optimal, as it lacks clarity on what the `retrieveServiceInformation` should include from previous projects. It needs optimization since it contains a lot of redundant data (null values). This could potentially be a topic for discussion once the transition from …
> G2 2024 v2 issue#14319 Implement retrieveSectionedService_ms

- Shared/css/style.css
The position of the arrow has been changed as well as the "Back to top" text, there is also now different styling where the arrow ^ turns yellow on hover.
> G3 2024 v2 #14557

- DuggaSys/sectioned.js
- Shared/navheader.php
Added a check to if there is a Github URL set for the course when trying to get the latest fetch.
> G3 2024 v2 #14533

- Shared/css/style.css
- Shared/navheader.php
Fixed the styling of the navbar so that navbar items don't jump down at certain screen sizes anymore. 
The current appearance:
> G3 2024 v2 #14518 Navbar bug fixed

- DuggaSys/microservices/courseedService/deleteCourseMaterial_ms.php
> G2 2024 v2 #14206 fixed

- DuggaSys/microservices/sectionedService/updateListentrie_ms.php
Created the microservice updateListentrie using code form sectionedservice.php for the `opt` "UPDATE".
Testing is done using the code described in the issue comments.
> G2 2024 v2 issue#14420

- DuggaSys/diagram.js
- DuggaSys/templates/diagram_dugga.js
uncommented the setup() function at line 22-33 in the diagram_dugga.js in the DuggaSys\templates\diagram_dugga.js filepath.
> Reimplemented setup() function from issue#14426

- DuggaSys/diagram.js
Broke out labels and line icon into functions
> line draw refactor#14494

- DuggaSys/microservices/sectionedService/updateListentriesTabs_ms.php
Created the microservice. Added instructions on how i tested it in the issue comments.
Not possible to integrate at this point (see comments).
> G2 2024 v2 issue#14422

- DuggaSys/microservices/showDuggaService/loadDugga_ms.php
Created the microservice. Info in issue#14555 comments on how I tested the microservice
> G2 2024 v2 issue#14555

- DuggaSys/sectioned.js
- Shared/dugga.js
Merge of #14412 into g3-2024-v2.
This has already passed testing in a previous [pull request](https://github.com/HGustavs/LenaSYS/pull/14566).
> G3 2024 v2 #14412

- DuggaSys/diagram.js
Fixed formatting issues and deleted line causing bug
> Fixed delete button on select #14615

- DuggaSys/duggaed.php
- Shared/navheader.php
The 'show tests' page now loads when entering it as a teacher.
> G2 2024 v3 issue#14625

- DuggaSys/diagram.js
Created a new branch "g1-2024-v3-#14485" and made all changes that was made on both old PR's:
https://github.com/HGustavs/LenaSYS/pull/14517 and https://github.com/HGustavs/LenaSYS/pull/14524
> New Pull request for issue#14485

- DuggaSys/diagram.js
Reverts HGustavs/LenaSYS#14660
> Revert "New Pull request for issue#14485"

- DuggaSys/diagram.js
You can now have the pop-out menu hide regardless where you click on the website. Can test it by have the pop-out menu open and click somewhere and see if the menu hides.
> G1 2024 v3 #14291

- DuggaSys/diagram.js
Issue #14572 was a problem where the shape became wierd when adding to the height of the element. A bug regarding attributes in the SDelement was also fixed.
> issue #14572 is now fixed

- DuggaSys/diagram.js
ALL variables in "elementTypesNames" are changed from this : kind. == "ERRelation"  to this  kind. == elementTypesNames.ERRelation
As well as : 
kind. != "ERRelation"  to this  kind. != elementTypesNames.ERRelation
kind. === "ERRelation"  to this  kind. === elementTypesNames.ERRelation
kind. === 'ERRelation'  to this  kind. === elementTypesNames.ERRelation
kind. == 'ERRelation'  to this  kind. == elementTypesNames.ERRelation
kind. != 'ERRelation'  to this  kind. != elementTypesNames.ERRelation
> changed all variables in elementTypesNames

- DuggaSys/diagram.js
Replaced all colors strings with variables
> replaced color strings #14485

- DuggaSys/diagram.js
All strings showing direction and strings describing entities have been replaced with constants
> replaced strings with direction const #14491

- DuggaSys/microservices/shared_microservices/createNewListentrie_ms.php
- Shared/database.php
> add sessions.php, remove duplicate row in database.php.

- sh/index.php
I only deleted the echoes which came right before a header call.
> Deleted echoes before header() - issue#14702

- DuggaSys/microservices/sectionedService/getUserDuggaFeedback_ms.php
- Shared/dugga.js
Created microservice `getUserDuggaFeedback_ms.php`
> G2 2024 v3 issue#14434

- DuggaSys/codeviewerService.php
- DuggaSys/microservices/codeviewerService/deleteCodeExample_ms.php
- Shared/dugga.js
See issue more info on ex how to test the service.
> G2 2024 v3 issue#14640 Create microservice deleteCodeExample

- DuggaSys/microservices/showDuggaService/saveDugga_ms.php
- backend-models/microservices/duggaSys services/Potential_micro_services.md
Me and c22emigr implemented the file saveDugga_ms.php
> G2 2024 v3 #14693

- DuggaSys/microservices/codeviewerService/editCodeExample_ms.php
Created the microservice, see issue comments for testing steps done.
> G2 2024 v3 issue#14638

- DuggaSys/tests/sectionedservice_Test.php
issue: #14716 
The removeListEntries test should work now.
> G2 2024 v3 issue#14716

- DuggaSys/diagram.js
Now should the '0'-point on the rulers and the origin lines be at the right position and are aligned to the grid. Can test it by zoom in and out to see if they are aligned, the ruler to the grid.
> G1 2024 v3 #14632

- DuggaSys/microservices/fileedService/deleteFileLink_ms.php
The microservice is used when a file is deleted from a course. You can create new files and delete them for testing purposes. New files can be created from the UI and will be placed in ```LENASYS/courses```, the subfolder is determined by if the file is global or local.
The original code from the monolith can be found inside ```fileedservice.php``` on row 63-142.
The implementation was tested by changing the ```kind=="FILE"``` part in the ```AJAXService()``` function inside ```dugga.js``` to:
```
else if(kind=="FILE"){
let serviceURL = "fileedservice.php";
if (opt=="DELFILE"){
serviceURL="../DuggaSys/microservices/fileedService/deleteFileLink_ms.php";
}
$.ajax({
url: serviceURL,
type: "POST",
data: "cid="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&opt="+opt+para, …
```
> G2-2024-V3 Issue #14635

- DuggaSys/courseed.js
- DuggaSys/courseed.php
- DuggaSys/gitcommitService.php
- DuggaSys/gitfetchService.php
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/basic.php
Moved and fixed the solution for #14563 from its v2 branch to its v3 branch
> moved solution for #14563 to v3 branch

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Created functionality to store code examples in the sqlite database tables gitFiles and gitRepo in metadata2.db.
Also created functionality to store the code examples in LenaSYS/courses/$cid/
To test that this works. insert a repository and filepath
When save button is clicked a folder should be created in LenaSYS/courses/ named after the courseid unless the folder already exists. Inside the folder all codeexamples should appear.
Use DB Browser to check metadata2.db and see if all files have been stored in gitFiles and a gitRepo connection has been made.
> Store relevant github database entries for codeexample #14525

- DuggaSys/microservices/courseedService/retrieveCourseedService_ms.php
I slightly altered the condition so that it matches the one in courseedservice.php. There should now be no error when opening the file in a browser. I have not tested the actual functionality of the microservice since I am unsure of how it should be used.
> Fixed error #14782

- DuggaSys/microservices/courseedService/updateCourse_ms.php
Fixed the implementation of the microservice, check issue comments for testing steps.
> G2 issue#14777 Fixed the implementation of the microservice updateCourse_ms.php

- DuggaSys/diagram.js
Broke out UMLEnity into function and updated resizing behaviour
> G1 2024 v3 #14701

- DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
Created a retrieiveSectionedService microservice, see issue comments to see how testing was done.
> G2 merge issue#14590

- DuggaSys/microservices/codeviewerService/editCodeExample_ms.php
> removed line 5 #14804

- DuggaSys/microservices/showDuggaService/createDuggaVariant_ms.php
this issue is not done yet because the servise nsertIntoTableVariant  is missing. View the pull request for the code that was created before insertIntoTableSettings and see what can be used.
> g2-2024-v3-#14644

- DuggaSys/diagram.js
Can now click on the text when you want to change what kind of line it should be. Test it by have a line between elements and click instead on the text when change for example to double line under the "Kinds" header.
> G1 2024 V3 #14776

- DuggaSys/diagram.js
Changed IEEntity to behave like UMLEntity
> Changed IEEntity to behave like UMLEntity

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
To tester: Please post any error or bugs that you may found. Especially user input errors when attempting to save a code example.
What has been improved:
- Indentation, commenting, error handling, 
-Overwrite handling in gitRepo db. I'e If a user has fetched a repo for the current course, fetching a code example won't overwrite that row.
-Some users didn't have a course folder in root. Now creates a course folder in root if it doesnt exist.
-Writes to folders and creation of dir moved into separate functions.
-Inserts into sqlite db moved to separate function.
-Filter to only files after fetching.
- Input fields are removed when clicking the Exit or save button. Also when clicking outside of the popup templatebox.
> Improve functinality of code example downloader #14656

- DuggaSys/microservices/duggaedService/deleteDuggaVariant_ms.php
The microservice is implemented, see issue comments for help with testing.
> created the microservice deleteDuggaVariant_ms

- DuggaSys/microservices/shared_microservices/retrieveUsername_ms.php
Created the ms retrieveUsername that retrieves a username depending on the uid from the current session.
The Uid is retrieved from the ms getUid.
> retrieveUsername_ms.php issue#14765

- DuggaSys/microservices/sectionedService/createListentrie_ms.php
- DuggaSys/microservices/shared_microservices/createNewCodeExample_ms.php
- DuggaSys/microservices/shared_microservices/createNewListentrie_ms.php
Added includes and removed old code. CreateNewCodeExample will be fixed in another issue.
> g2-2024-v3 issue #14839

- DuggaSys/diagram.js
Broke out all UML states into functions, updated text placedment in superstate
> UML states broken out #14823

- DuggaSys/microservices/shared_microservices/createNewCodeExample_ms.php
MS was tested with the command:
```
curl -X POST -d "courseid=1&examplename=TESTEXAMPLE&sectname=TESTSECT&coursevers=123" http://localhost/LenaSYS/DuggaSys/microservices/shared_microservices/createNewCodeExample_ms.php
```
> g2-2024-v3 issue #14836

- DuggaSys/microservices/sectionedService/getCourseGroupsAndMembers_ms.php
Added use of:
- `showgrp`
- returned json uses data from `retrieveSectionedService()`
> G2 2024 v3 issue#14825

- DuggaSys/microservices/sectionedService/createListentrie_ms.php
- DuggaSys/microservices/shared_microservices/createNewCodeExample_ms.php
- DuggaSys/microservices/shared_microservices/createNewListentrie_ms.php
Changed createNewCodeExample_ms and createNewListentrie_ms to functions instead.
These functions are called from createListentrie now, instead of createListentrie executing the same code itself.
Tested it by changing the service url in dugga.js (see issue comments) and by adding new items inside of a course.
> G2 2024 v3 issue#14844

- DuggaSys/diagram.css
- Shared/css/style.css
Made it so the ruler on the left and the toolbar to the left looks better when the screen height it higher then 1200 pixels. Can test it by have a bigger screen and see if it looks like when it is for example 1920x1080 screen.
> G1 2024 v3 #14740

- DuggaSys/diagram.js
deleted some conditions in a if-state: context[0].kind != elementTypesNames.ERRelation.
> deleted some conditions

- DuggaSys/microservices/codeviewerService/editContentOfExample_ms.php
Created the microservice editContentOfCodeExample_ms.php, see issue comments for testing steps.
> G2 merge issue#14639

- DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
- DuggaSys/sectioned.js
- DuggaSys/sectionedservice.php
- Shared/SQL/init_db.sql
A dugga will now take it's deadline from listentries from the database and will no longer have it's deadline affected by other instances of dugga (quiz in database). For testing purposes you'll need to do a new install of LenaSYS to ensure that your lokal database i up to date.
Database changes:
- Added handindeadline to listentries.
> Fixed deadlines for duggor G3 2024 v3 #14447

- newinstaller/style.css
- newinstaller/test.html
Created a new map with files and copied the code from last week branch.
Read more about the issue here: https://github.com/HGustavs/LenaSYS/issues/14569
> Re-branched last weeks changes

- DuggaSys/microservices/sharedMicroservices/createNewCodeExample_ms.php
- DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
- DuggaSys/microservices/sharedMicroservices/retrieveUsername_ms.php
Functionality was remade into a function.
I only updated the files that already used the old MS, but there are several more that should be updated to use the ```retrieveUsername``` MS.
> g2-2024-v4 issue #14886

- DuggaSys/showDuggaservice.php
- DuggaSys/tests/showDuggaservice_test.php
The Get active users test in showDuggaservice_test.php should work now.
Important:
Some tests require a fresh DB install to work.
> G2 2024 v4 issue#14500

- backend-models/microservices/duggaSys services/Microservices.md
> G2 2024 v4 issue#14467

- DuggaSys/microservices/sharedMicroservices/retrieveUsername_ms.php
Added needed changes. See issue comments for testing steps.
> G2 Merge issue#14911

- DuggaSys/microservices/accessedService/addUser_ms.php
- DuggaSys/microservices/accessedService/updateUserCourse_ms.php
- DuggaSys/microservices/courseedService/changeActiveCourseVersion_ms.php
- DuggaSys/microservices/duggaedService/deleteDuggaVariant_ms.php
- DuggaSys/microservices/sectionedService/deleteListEntries_ms.php
> g2-2024-v4 issue #14906

- backend-models/microservices/duggaSys services/Microservices.md
The microservices was reverted since there was some problem with the code.
> Reverted processDuggaFile_ms.php

- DuggaSys/diagram.js
Broke out note into function. Issue with vertical resize was present in previous version. Overlap does not work when dragging other objects into note. This was also present in previous version.
> Broke out note into function #14941

- DuggaSys/diagram.js
Have change the order of the attribute states for the ER diagram. Test it by see if the order is "correct" and the most common attribute is more in the top of the drop-down menu.
> G1 2024 V4 #14880

- DuggaSys/diagram.js
Now should the "Recursive" option be gone for ER diagram, label section for IE diagram and cardinalities for state diagram. Can test it by see if all the option still works and if the option that I removed is gone.
> G1 2024 v4 #14872

- DuggaSys/courseed.php
- DuggaSys/sectioned.php
- Shared/css/style.css
- Shared/loadingButton.js
Buttons now have loading capabilities when waiting for a request to be fulfilled, replace old buttons/inputs
Old:
```
<input id='saveRepo' class='submit-button' style='float:right; margin-right:5px;' type='button' value='Save' title='Save Changes' onclick='validateForm("githubPopupWindow");' />
```
New, make a container and include `loadingButton.js`
``` js
<script src="../Shared/loadingButton.js"></script>
<div id="buttonContainerSaveRepo"></div>
```
Within `loaderButton.js` fill in the function to be called, the argument, label and containerID in the _actions_ object
```js
const actions = {
saveRepo: {
action: validateForm, // Function
argument: "githubPopupWindow", // Argument to pass to the function
buttonLabel: "Save Repo", // Button label
containerId: "buttonContainerSaveRepo" // …
```
> Loader for buttons G3 2024 v4 #14648

- DuggaSys/microservices/gitCommitService/refreshGithubRepo_ms.php
Se issue 14965 for how it is tested and to what extent i have been able to test it.
> G2 2024 v4 issue#14965 Create microservicec refreshGithubRepo_ms.php

- DuggaSys/diagram.js
Should fix it with the sequence activation can be on top of sequence condition without it overlapping. Can test it by have a sequence condition on screen and try if sequence activation it still overlapping or not.
> G1 2024 V4 #14944

- DuggaSys/tests/accessedService_test.php
fixed accessedservice_test.php all tests can now run and receive output.
> g2-2024-v4-issue#14989

- DuggaSys/sectioned.js
- Shared/dugga.js
Added an if-statement that checks whether all information in the form is correct before allowing the user to update an item by pressing enter. To check if this fix works, try to update an item (for example a dugga) with an illegal character in a text-input. An example of an illegal character is **´**. For example, try pressing enter when the form is looking something like this:
It should not allow you to submit the form and update the item. Also test that no new errors have been created because of this fix.
> G3 2024 v4 #14877 Pressing enter with invalid information

- DuggaSys/diagram.js
Broke out ER into functions. Restructured drawElement()
> Broke out ER into function #14979

- DuggaSys/diagram.js
Changed it so cardinalities are now placed next to the ER-entity instead of the relation.
> Changed position for cardinalities on ER-lines. (#14882)

- DuggaSys/microservices/sectionedService/updateListEntriesTabs_ms.php
Added a more fitting debug message.
> Changed debug message

- DuggaSys/microservices/sharedMicroservices/updateSecurityQuestion_ms.php
- DuggaSys/profile.js
Created and tested a new microservice for updating or adding a security question for a user (not for teachers or superusers). Tested to confirm that it works by changing the url on row ~ 31 to use our new microservice updateSecurityQuestion_ms.php in the file profile.js
> Created the file updateSecretQuestion_ms.php issue#14930

- DuggaSys/gitcommitService.php
Added a empty string to the function `insertIntoSQLite()` function call in `getCourseID()`. Tested by creating a new course and adding a url. After that checking if the url is there when the course has been created
> G2 2024 v4 issue#15011

- DuggaSys/microservices/gitCommitService/getCourseID_ms.php
Added the getCourseID function in it's own file microservices/gitCommitService/getCourseID_ms.php.
See issue comments for testing.
> G2 2024 v4 issue#15027

- DuggaSys/microservices/sectionedService/createListEntry_ms.php
Fixed naming from entrie to entry. can be merged now.
> G2 2024 v4 #15058 1

- DuggaSys/microservices/gitCommitService/insertIntoSQLite_ms.php
Added the function into a separate file. See issue comments for testing steps.
> G2 2024 v4 issue#14962

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
- Shared/toast.php
Added an toast to sectioned.js where a section gets deleted.
Regular
Hover
Toast now takes 4 arguments, the last argument is a default argument and does not need to be included in every toast() call
The argument is used to add an method call from sectioned.js to sectioned.php.
> Undo toast type #14945

- DuggaSys/microservices/gitfetchService/getIndexFile_ms.php
I took the function from gitfetchService.php and put it here. What it does and how it should be tested I have no idea. Someone experienced enough to find out should test it
> Implemented microservice getIndexFile

- DuggaSys/diagram.js
Moved div and variable init from functions to drawElement.
> Moved common code to drawElement #15046

- DuggaSys/microservices/fileedService/updateFileLink_ms.php
To be able to test the microservice, change the code at kind "FILE" in dugga.js to the following.
```
}else if(kind=="FILE"){
let serviceURL = "fileedservice.php";
if (opt=="SAVEFILE"){
serviceURL="../DuggaSys/microservices/fileedService/updateFileLink_ms.php";
}
$.ajax({
url: serviceURL,
type: "POST",
data: "cid="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&opt="+opt+para,
success: returnedFile
})
```
Check all this for global, course-local and version-local files.
- Check that the updating of the filesize in table "fileLink" is performed.
- Check that logging to loglena6 database is performed. 
- Check that the file is successfully written to in C:\xampp\htdocs\LenaSYS\courses.
Note: I could not get the logging to work, although I am not sure why …
> Created updateFileLink_ms.php

- DuggaSys/diagram.js
Replaced all find line functions with one that takes a type
> Replaced functions #15044

- DuggaSys/diagram.php
Swapped places of the ER-relation and the UML-inheritance declaration in diagram.php on line 314-328.
Link to issue:
https://github.com/HGustavs/LenaSYS/issues/14376
> Moved ER-relation to be the second item in the relation sublist for issue#14376

- DuggaSys/microservices/gitCommitService/fetchOldToken_ms.php
Added the microservice (function) fetchOldToken_ms.php. See issue comments for testing
> G2 2024 v4 issue#14963

- DuggaSys/microservices/gitCommitService/newUpdateTime_ms.php
Added the function into a microservice. See issue comments for testing.
> G2 2024 v4 issue#14959

- DuggaSys/courseedservice.php
- DuggaSys/sectionedservice.php
- Shared/dugga.js
It seemed like the solution to the problem was to add another else if statement but for CPYVRS and fix a syntax error. So now it should be possible to copy content from existing course version when creating a new course version. The correct format for creating a new course version is
Version ID: 2001
Version Name: HT01
Start Date: 01/04/2024
End Date: 31/05/2024
MOTD: MOTD
Copy content from: ST20 - 52432
> Copy content from existing course version fixed

- DuggaSys/microservices/gitCommitService/clearGitFiles_ms.php
- DuggaSys/microservices/gitCommitService/refreshGithubRepo_ms.php
This file cleares the current github files. It is used by the services updateGithubRepo and refreshGithubRepo.
> Create ms clearGitFiles_ms.php #14967

- backend-models/microservices/duggaSys services/Microservices.md
Observe, the ms has a new filename (deleteGitFiles_ms.php).
> Updated clearGitFiles_ms.php

- DuggaSys/accessed.js
- DuggaSys/accessed.php
- DuggaSys/codeviewer.js
- DuggaSys/codeviewer.php
- DuggaSys/courseed.js
- DuggaSys/courseed.php
- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
Added toasts where they fit and could be viewed by and user and fixed toast container permanently blocking elements behind it.
Files affected
Most Alerts are connected to debugging and are not expected to be viewed by an user, and or used to block refresh until OK response, therefore the majority is still not touched.
Most toasts inserted are connected and responses to the forms listed [here](https://github.com/HGustavs/LenaSYS/wiki/Popup-form-conventions#currently-known-popup-forms-on-lenasys)
> Replace js alerts with toasts #14876

- DuggaSys/diagram.js
Moved element and line properties into own function.
Test option pane properties for combinations of elements and lines.
> G1 2024 v4 #15050

- DuggaSys/sectioned.js
- Shared/css/style.css
check visual elements in  resulted.php, sectioned.php, courseed.php and codeviewer.php  nothing should be missing, i have only changed places of the code
> started to reorganize style.css #14661

- Shared/navheader.php
Transferred code from last weeks branch that didnt get merged
> g3-2024-v4-#14669

- DuggaSys/diagram.js
> fixed note resizing #15031

- DuggaSys/courseedservice.php
Before it wasn't possible to load duggor when creating a new course version and you would copy content from existing course version. Hopefully it should work now. The tester should try this with demo-course. Keep in mind that with webbutveckling - datorgrafik it won't work because it didn't work before this, so it's normal. So it concerns another issue.
> copied duggor into the newly created course version is fixed

- DuggaSys/diagram.js
revertet a commit, should work now
> G1 2024 v4 #14112 - v2

- DuggaSys/diagram.js
- DuggaSys/diagram/helper.js
Replaced all instances of function
> Replaced getPoint #15042

- DuggaSys/diagram.js
Removed repetition and nesting in entityIsOverLapping
> Removed repetition and nesting #15100

- DuggaSys/diagram.js
> element z-index #15170

- DuggaSys/diagram.js
- DuggaSys/diagram.php
updated submenu icons and cycling
> updated submenu icons and cycling #15133

- dockerenv/Dockerfile
- newinstaller/tools/permissions.php
- has_permission
- get_permissions
- get_owner
- get_group
- get_process_user
These will all be used in the new installer, to help the user with permissions. 
You can paste this code into `newinstaller/installer.php`:
```php
echo "Owner: " . Permissions::get_owner("test.html") . "<br>";
echo "Group: " . Permissions::get_group("test.html") . "<br>";
echo "Has permission: (1 = true, nothing = false): ". Permissions::has_permission("test.html") . "<br>";
echo "Permissions: " . Permissions::get_permissions("test.html")["permissions"] . "<br>";
echo "Process user: " . Permissions::get_process_user();
```
> Merge of #15121 into g3-2024-v4

- DuggaSys/diagram.js
Should not be able to draw a line between two ER entity anymore.
> G1 2024 V4 #15000

- DuggaSys/diagram.js
> Broke out attribute change #15085

- DuggaSys/microservices/sharedMicroservices/isSuperUser_ms.php
Create the microservice isSuperUser_ms, that implements a function that is similar to a function in sessions.php (same name). This function requires a pdo to be sent as a parameter. See issue comments for testing steps.
> G2 2024 v4 issue#14931

- DuggaSys/accessedservice.php
- DuggaSys/tests/accessedService_test.php
It is now possible to make tests in accessedservice_tests.php. I have created 3 functioning tests to check that it is working. I have commented out all the tests that haven't been updated. New issues will need to be created for these, when this has been tested/merged.
> G2 2024 v4 #15012

- DuggaSys/sectioned.js
Test that you can click on both buttons that calls showcanvasLink and opencanvasLink
> Eliminate error message in console and fix the code to implement toasts. #15070

- DuggaSys/tests/sectionedservice_Test.php
Changed parameters, expected-output and filters
> G2 issue#15153 merge

- DuggaSys/microservices/sectionedService/getCourseVersions_ms.php
Created _getCourseVersions_ms.php_ solves issue #14838 
Microservice uses service selectFromTableVers to get information it requires from vers.
The microservice's output, `$versions` array is incorporated within the _returnedSection_ array in _sectioned.js_. To effectively test the microservice:
1. Connect to the database
2. Open the _getCourseVersions_ms.php_ file in your browser.
3. Verify that it retrieves and displays the expected data from the "vers" table.
> G2 2024 v4 issue#14838 - Create getCourseVersions_ms.php

- backend-models/microservices/duggaSys services/Microservices.md
Updated information about the microservices that have been missing so far. Updated information about which service files we should hold off on and which ones need research to see which ones are actually used and therefore should have microservices.
> Updated Microservices.md

- DuggaSys/sectioned.php
Refactored pdo implementation when inserting to db
> Refactor pdo implementation when inserting into database #15040

- DuggaSys/tests/showDuggaservice_test.php
All tests for create active users pass now. However it is not known if this is what the output will be in the future.
> G2 2024 v4 #15104

- DuggaSys/microservices/gitCommitService/newUpdateTime_ms.php
- DuggaSys/microservices/gitCommitService/refreshCheck_ms.php
- DuggaSys/microservices/gitCommitService/refreshGithubRepo_ms.php
See comment in the issue for details about this issue: https://github.com/HGustavs/LenaSYS/issues/14958#issuecomment-2084623995
This pull request is not possible to fully tests because of another issue group 3 is working on.
> G2 2024 v4 issue#14958

- Shared/test.php
Tests can now run from anywhere.
> G2-2024-v5 issue #15232

- backend-models/service-tests/codeviewerService-test.md
- backend-models/service-tests/courseedservice-test.md
Update some of the test documentation to better describe the different tests purposes.
> G2 2024 v5 issue#15139 - update some test documentation to better describe the tests purpose.

- DuggaSys/microservices/accessedService/retrieveAccessedService_ms.php
Since the frontend for accessedservice.php, is not finished its not possible to test that the retrieve or any related microservice to accessedservice works. I suggest we merge this microservice for now and create a new microservice once the frontend is implemented, where we test integration of the microservices together.
> G2 2024 v5 issue#15250

- DuggaSys/microservices/profileService/updateSecurityQuestion_ms.php
- DuggaSys/microservices/profileService/updateUserPassword_ms.php
Created the folder profileService and moved the files updateSecurityQuestion and updateUserPassword into it. Also changed the path for the "getUid_ms.php" ms file that was included.
> Created folder "profileService" and moved the files "updateUserPassword" and "updateSecurityQuestion"

- newinstaller/tools/permissions.php
Implemented a more generic way of handling output from the Permissions file. You can now get proper error messages if anything goes wrong, the data you requested and wether or not the operation was successfull.
Simply paste this code into `newinstaller/installer.php`:
```php
echo Permissions::get_permissions("test.html")['message'] . "<br>";
echo implode(Permissions::get_permissions("test.html")['data']). "<br>";
echo implode(Permissions::get_owner("test.html")). "<br>";
echo implode(Permissions::get_group("test.html")). "<br>";
echo implode(Permissions::get_process_user()). "<br>";
echo implode(Permissions::has_permission("test.html")). "<br>";
```
The output should look something like this:
Note that it could look different on different platforms, as not all platforms have file …
> Implemented more informative returns for all functions.

- DuggaSys/resultedservice.php
- DuggaSys/sectionedservice.php
- Shared/navheader.php
*This is changes copied over from last week, but i did also test it to make sure it still worked
old text:
This issue uses try/catch statements to work around the database queries, then uses isset() to determine if a column is present or not in the answer received. I'd also like to add that the only relevant changes are to sectionedservice.php, the other changes are due to a merge with my previous issue branch due to the changes to navheader.php being needed to load the page.
**Contact me or the current leaders for access to the old database.**
**Testing instructions:**
- Initially, check out any courses page on the current database to ensure it still works.
- Then run the database file to get the old database (if using phpmyadmin, click your database and select import)
- Following this, …
> legacy support for sectioned.php

- DuggaSys/microservices/accessedService/addClass_ms.php
- DuggaSys/microservices/sharedMicroservices/getUid_ms.php
- DuggaSys/tests/microservices/accessedService/addClass_ms_test.php
The only output from the MS is ```$debug```, so the comparison is only done to that.
Since this branch was created before the recent ```test.php``` fix, you will need to modify the file. Change row 64 to:
```
include_once __DIR__ . "/../../coursesyspw.php";
```
and row 202 to:
```
include_once __DIR__ . "/sessions.php";
```
> g2-2024-v5 issue #15178

- DuggaSys/microservices/sectionedService/createGithubCodeExample_ms.php
- DuggaSys/microservices/sharedMicroservices/createNewCodeExample_ms.php
- DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
This is a quite involved microservice to test, so make sure you check some of the comments of the issue. I have been able to test it to some extent, but not completely. This is one of those microservices that are a bit unclear if the original functionality is used, even though it is possible to kind of use it on the actual website. Another thing is that this uses the github fetching functionality, which is barely working at the moment (see issue comments) and it makes you wait 5 minutes between each test. Adding a repo to a course also downloads the files into the LenaSYS/courses/<courseid> directory, so sometimes you need to add the repo to another course if you want to perform new testing.
The createGithubCodeExample microservice should use createNewCodeExample and createNewListEntry …
> G2 2024 v5 issue#14928

- DuggaSys/tests/microservices/showDuggaService/loadDugga_ms_test.php
A working test for loadDugga_ms.php has been created.
> G2 2024 v5 issue#15164

- DuggaSys/microservices/profileService/retrieveProfileService_ms.php
- DuggaSys/microservices/profileService/updateSecurityQuestion_ms.php
- DuggaSys/microservices/profileService/updateUserPassword_ms.php
The retrieveProfileService_ms.php file has been created and implemented.
The profileService microservices only output basic status messages on the operations made. I have made a super simple retrieve-function that can be expanded in the future if more output is required.
To test the microservices change the urls in profile.js
line 33:
```"../DuggaSys/microservices/profileService/updateSecurityQuestion_ms.php"```
line 166:
```url: "../DuggaSys/microservices/profileService/updateUserPassword_ms.php",```
Then login and press the username in the top right corner (requires https connection). Here you can attempt to change the password and security question. This should send the output to the network tab in your browser.
> G2 2024 v5 issue#15310

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
Implemented regex to the inputs for filename and github-link so it matches the requirements. 
Added so it visualize if an invalid input is entered and that a template needs to be chosen before saving the information.
> G3 2024 v5 #15033

- DuggaSys/diagram.js
- DuggaSys/diagram/constants.js
- DuggaSys/diagram/helpers/line.js
Broke out error handling in addLine into function.
Removed unused code in addLine.
Added const array with types that handle error checking in the same way.
> Broke out error handling in addLine #15311

- DuggaSys/microservices/duggaedService/createDuggaVariant_ms.php
- DuggaSys/microservices/duggaedService/createDugga_ms.php
- DuggaSys/microservices/duggaedService/deleteDuggaVariant_ms.php
- DuggaSys/microservices/duggaedService/deleteDugga_ms.php
- DuggaSys/microservices/duggaedService/retrieveDuggaedService_ms.php
- DuggaSys/microservices/duggaedService/updateDuggaVariant_ms.php
- DuggaSys/microservices/duggaedService/updateDugga_ms.php
You can test it using any duggaed microservice, but I used createDugga. First create a new dugga using the monolith and save the response. Then add this code to createDugga_ms.php.
```
include_once("retrieveDuggaedService_ms.php");
$log_uuid=getOP('log__uuid');
$array = retrieveDuggaedService($pdo, $debug, $userid, $cid, $coursevers, $log_uuid);
echo json_encode($array);
```
And change the code at the else-if for kind "DUGGA" in dugga.js.
```
}else if(kind=="DUGGA"){
let serviceurl = "duggaedservice.php";
if (opt=="SAVDUGGA")
serviceurl = "../DuggaSys/microservices/duggaedService/createDugga_ms.php"
$.ajax({
url: serviceurl,
type: "POST",
data: "opt="+opt+para,
success: returnedDugga
});
```
Then create a new dugga and compare the responses.
> Created retrieveDuggaedService_ms.php issue#15254

- DuggaSys/JSON/ERDiagramMockup.json
Remove object with ID BA4BCD in JSON file.
{
"kind": "ERAttr",
"name": "Ghost",
"stroke": [
"#383737"
],
"width": 5,
"height": 5,
"x": 1805.5,
"y": -37.5,
"id": "BA4BCD"
},
Closes issue #15263
> Remove object with ID BA4BCD  #15263

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
I've added the option to deleted selected items with one click. When clicking the checkboxes on one or more items on the coursepage and then clicking the delete button, all selected items will be deleted.
> Selected items can now be deleted with 1 click G3 2024 v5 #15278

- DuggaSys/diagram/draw/line.js
- DuggaSys/diagram/draw/options.js
- DuggaSys/diagram/events/mouse.js
Added icons, label and dashed line to SE
> Added icons, label and dashed line to SE #14819

- DuggaSys/tests/microservices/profileService/updateUserPassword_ms_test.php
Made the test-file updateUserPassword_ms_test.php.
The first test tries to change the password of a user which should work.
The second test tries to change a teachers password, this should not work and return: ```{"success":false,"status":"teacher","debug":"NONE!"}``` since teachers are not allowed to change their own passwords.
> G2 2024 v5 issue#15358

- DuggaSys/diagram/draw/options.js
Removed break for non attributes
> Removed break for non attributes #15383

- DuggaSys/tests/getdataUserAnswer_test.php
I have updated the Url of the by changing showDuggaservice.php wiht getdataUserAnswer.php.  Changed also     //     'query-after-test-1' => "DELETE FROM userAnswer ORDER BY aid DESC LIMIT 1;",      with              'query-after-test-1' => "DELETE FROM userAnswer WHERE hash = 'ghj1jfg2';",
> getdataUseAnswer lasted updated version  

- newinstaller/tools/testdata_setup.php
See previous comments for this issue before testing. The requirements has come to change....
Whats has been implemented is a class that takes sourcePath, destinationPath and callback function.
There are two public functions that are used, these are copy_test_course, which effectively copies all available test-courses to the correct folder when choosen to, through the installer. The second function is copy_course, which copies specific courses.
When testing this you can use the following image as a guide to setup you're testing.
Try switch between existing courses when trying the copy_course function (available courses are '1', '2', 'global'). Also play around with no / true / false for the verbose boolean (True gives better feedback, false / empty provides little to none feedback).
closes …
> Pull request for G3-2024-v5-#15320

- Shared/loginbox.php
checked if you can log do a log-in form anywhere in the system and that works for me and removed the text, i am on an docker system and would probably be good to test this on an xampp system as well.
to tester:
try and log in and out at any place you can find and report back if a place dose not work; if this massage comes up:
i have confirmed that this is a separate issue in the system now an id being looked at, but you should still be able to log in.
> removed "Login is only possible from course page!" and check login works

- DuggaSys/sectioned.js
- Shared/css/style.css
Has fixed the highlight to light up the whole table row instead of just the text. also created a function in order to not use repeating code. This could need a double check/test in order to confirm functionality.
> New branch for week 4 issue #15159

- newinstaller/installer.php
- newinstaller/installer_ui.php
- newinstaller/tools/db_setup.php
- newinstaller/tools/install_engine.php
- newinstaller/tools/sse_receiver.js
- newinstaller/tools/sse_sender.php
Now incorporates all the requirements of the issue:
- SSE receiver
- SSE sender
- And a coarse version of the installer for testing. (this will be replaced by a proper implementation of UI).
- Also fixed some bugs in other newinstaller files.
Navigate to `localhost/LenaSYS/newinstaller/installer.php`
> Implemented first draft of installer

- DuggaSys/courseed.js
- DuggaSys/courseed.php
Old MOTD:
Now shows error messages which are aligned:
Old edit course messages:
Are now aligned and there an error for the Github Key field, which is optional:
Old new course messages:
Are now aligned:
> Aligned and added error messages #14875

- DuggaSys/diagram.js
- DuggaSys/diagram/helpers/mouseMode.js
- DuggaSys/diagram/toggle.js
icon in toolbar now changes when pressing  keybinds
> icon change on cycling #14375

- backend-models/microservices/duggaSys services/Microservices.md
> G2 2024 v5 issue#14467

- DuggaSys/microservices/duggaedService/createDugga_ms.php
Necessary code was added, unnecessary code was removed, refactoring was done.
You can test the microservice by going into a course, clicking "show tests" at the top, and then creating a new test. The frontend doesn't seem completed so you will have to check the database to see that the correct values are entered.
Change row 1062 in ```dugga.js``` to:
```
}else if(kind=="DUGGA"){
let service_url = "duggaedservice.php"
if (opt == "SAVDUGGA")
service_url = "microservices/duggaedService/createDugga_ms.php"
$.ajax({
url: service_url,
type: "POST",
data: "opt="+opt+para,
success: returnedDugga
});
```
> g2-2024-v5 issue #15461

- DuggaSys/accessed.js
- DuggaSys/accessed.php
- Shared/css/blackTheme.css
- Shared/css/style.css
Have applied a couple of new styles to the popup window.
Included button into a general wrapper-class in order to give all content of the popup window a common padding.
Have also corrected the hightlight for validation of all the input fields and made sure they work in both light & dark mode. Lastly, I've cleaned up the code a bit and removed 2 unused function calls.
> Updated the popup for creating new user

- DuggaSys/diagram.js
- DuggaSys/diagram/camera.js
- DuggaSys/diagram/classes/rect.js
- DuggaSys/diagram/classes/stateChange.js
- DuggaSys/diagram/classes/stateChangeFactory.js
- DuggaSys/diagram/constants.js
- DuggaSys/diagram/defaults.js
- DuggaSys/diagram/draw/element.js
- DuggaSys/diagram/draw/line.js
- DuggaSys/diagram/draw/node.js
- DuggaSys/diagram/draw/options.js
- DuggaSys/diagram/draw/ruler.js
- DuggaSys/diagram/draw/selection.js
- DuggaSys/diagram/draw/update.js
- DuggaSys/diagram/errorHandling.js
- DuggaSys/diagram/events/mouse.js
- DuggaSys/diagram/globals.js
- DuggaSys/diagram/helper.js
- DuggaSys/diagram/helpers/boxSelect.js
- DuggaSys/diagram/helpers/element.js
- DuggaSys/diagram/helpers/line.js
- DuggaSys/diagram/helpers/mouse.js
- DuggaSys/diagram/helpers/mouseMode.js
- DuggaSys/diagram/message.js
- DuggaSys/diagram/theme.js
- DuggaSys/diagram/toggle.js
- DuggaSys/diagram/zoom.js
Updated unused paramters, inconsistent whitespace, const/let instead of var and missing semicolons
> G1 2204 v5 #15478

- DuggaSys/microservices/highscoreService/highscoreservice_ms.php
The microservice seems a bit redundant as the original mono file is already reasonably small. Im not sure if the file should be simmered down further so will just create the file and add it to microservices/highScoreService/highscoreservice_ms.php. 
Only file to review is highscoreservice_ms.php located in microservices folder
> 15352 create microservice highscoreservice msphp

- DuggaSys/microservices/sectionedService/createGithubCodeExample_ms.php
- DuggaSys/microservices/sectionedService/createListEntry_ms.php
- DuggaSys/microservices/sharedMicroservices/createNewCodeExample_ms.php
- DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
Change the parameters of createNewListentry from a array to variables instead, as well as the same name as the microservice file.
> G2 204 v6 issue#15499

- DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
- Shared/dugga.js
To test the microservice change the url used for the opt "CPYVRS" to use the microservice.
Go into a course->Create a new version of this course->Copy a existing version.
Check response to the request to copyCourseVersion_ms.php.
> G2 2024 v6 issue#14198

- DuggaSys/microservices/duggaedService/retrieveDuggaedService_ms.php
- DuggaSys/tests/microservices/duggaedService/createDugga_ms_test.php
- DuggaSys/tests/microservices/duggaedService/updateDugga_ms_test.php
Ignore the 2 other files changed, they are there because of a squash merge of #15514, which updated the retrieve MS.
> G2-2024-v6 issue #15203

- DuggaSys/microservices/codeviewerService/updateCodeExampleTemplate_ms.php
Fixed the change requests i hope it's alright now
> Create microservice updateCodeExampleTemplate issue#14637

- DuggaSys/microservices/courseedService/updateCourseVersion_ms.php
Changed the microservice to actually update a course version. See issue comments for testing.
> G2 Merge #15433

- DuggaSys/sectioned.js
- Shared/navheader.php
Fixed the titles after the testing review.
Fixed icons:
src='../Shared/icons/select.png'
src='../Shared/icons/PenT.svg'
src='../Shared/icons/list_docfiles.svg'
Themetoggle.svg
refreshIMG
> Updated version after testing 

- DuggaSys/tests/microservices/duggaedService/deleteDuggaVariant_ms_test.php
Created the test: deleteDuggaVariant_ms_test.php
The test creates 2 variants and deletes one of them, in the output only the non-deleted variant can be seen.
> G2 2024 v6 issue#15200

- DuggaSys/tests/microservices/profileService/updateSecurityQuestion_ms_test.php
Created _updateSecurityQuestion_ms.php_ to test the microservice.
How to test:
Locate the file in your browser with a database connection.
> G2 2024 v6 issue#15357 - Create new test for the microservice updateSecurityQuestion_ms.php

- DuggaSys/tests/microservices/accessedService/updateUser_ms_test.php
Created test for microservice updateuser. I could not find how to trigger the updateuser function on lenasys, therefore I could not determine the output manually. Instead I looked at the first uncommented test for accessedService_test.php which seems to work. The remaining tests were created and their output determined from the first uncommented test and by looking at relevant tables in mysql. 
I am a little unsure how to test this for the microservice but the following documentation on the test API might provide some guidance: 
Shared/Documentation/Test API/Guide on how to use Test API.md
> 15181 create new test for the microservice updateuser msphp

- DuggaSys/fileed.php
- Shared/navheader.php
Fixed error by including ace.js in the fileed.php file. Also fixed error in navheader.
> G3 2024 v6 #15341

- DuggaSys/diagram/draw/element.js
IE height now includes primary keys
> Corrected IE height #15539

- DuggaSys/tests/microservices/codeviewerService/deleteCodeExample_ms_test.php
Need some help with this one. on test 3 i get
Test 3 (assertEqual): failed with error: no valid values to compare
value expected: null
value output: null
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':exampleid)' at line 1 in C:\xampp2\htdocs\LenaSYS\Shared\test.php:87 Stack trace: #0 C:\xampp2\htdocs\LenaSYS\Shared\test.php(87): PDOStatement->execute() #1 C:\xampp2\htdocs\LenaSYS\Shared\test.php(179): doDBQuery(Object(PDOStatement), 'UNK', 'UNK', 'UNK') #2 C:\xampp2\htdocs\LenaSYS\DuggaSys\tests\microservices\codeviewerService\deleteCodeExample_ms_test.php(34): testHandler(Array, true) #3 {main} thrown in …
> G2 2024 v5 #15183

- DuggaSys/tests/microservices/accessedService/addUser_ms_test.php
Inspect the code and run the test in your browser with a database connection
> Created test file 'addUser_ms_test.php' to test microservice 'addUser'

- DuggaSys/diagram/draw/line.js
- DuggaSys/diagram/globals.js
- DuggaSys/diagram/helpers/line.js
**Original task:**
>Make that cursor would be beside the line.
**The finished result:**
https://github.com/HGustavs/LenaSYS/assets/129273186/2e2d3417-1f5d-4553-a43e-3f964593fb47
The result has been achieved by having a boolean value that says if it's drawing or not. While it's drawing, the coordinates for x & y should follow the cursor.
**To test:**
Make sure that the cursor follows the draw being drawn, that the sit besides each other.
> G1 2024 v6 #15086

- DuggaSys/diagram.js
- DuggaSys/diagram/draw/options.js
- DuggaSys/diagram/events/mouse.js
- DuggaSys/diagram/helper.js
Undo and redo should now be fully complete. Any bugs should be reported
> finished undo #15498

- DuggaSys/tests/microservices/courseedService/copyCourseVersion_ms_test.php
Created the test for copyCourseVersion_ms.php. The test do not work for courseedservice.php.
> G2 Merge issue#15378

- backend-models/microservices/duggaSys services/Microservices.md
> G2 2024 v6 issue#15515

- DuggaSys/microservices/courseedService/deleteCourseMaterial_ms.php
- DuggaSys/microservices/courseedService/retrieveCourseedService_ms.php
I've made deleteCourseMaterial into a function that retrieveCourseedService is using. This is because retrieveCourseedService was already courses marked for deletion, making the deleteCourseMaterial microservice redundant before.
> G2 2024 v6 issue#15611

- DuggaSys/assets/js/fetchDiagramInfo.js
Changed the indentation of the code in the file fetchDiagramInfo.js and removed blank spaces and other unnecessary bloat, to follow clean code principles. The functionality of the code wasn't altered. 
Link to issue:
https://github.com/HGustavs/LenaSYS/issues/15593
> Changed the identation and removed blank spaces for issue#15593

- DuggaSys/highscoreservice.php
- DuggaSys/microservices/highscoreService/highscoreservice_ms.php
- DuggaSys/microservices/highscoreService/retrieveHighscoreService_ms.php
- Shared/dugga.js
Created retrieve microservice for highscoreservice. For some reason the original service file highscoreservice.php is not working correctly when testing on lenasys. The microservices in DuggaSys/microservices/highscoreservice were created from that file so the same errors are probably present there as well. Therefore testing and reviewing are rather limited.  
~I will create new issues focused on addressing the errors with both the highscoreservice.php and its related microservices.~
> 15353 create a retrievehighscoreservice microservice

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
the issue was that the validation function was called multiple times in both editSection and sectionname. i removed the calls to the function in editSection. 
testing:
add this code into to the validateSectName function in sectioned.js.
let i = 1;
function validateSectName(name) {
console.log("validateSectName() has run "+i+" times.");
i++;
. . .
}
then press the cog wheel on and go at it.
> G3 2024 v6 #15504

- DuggaSys/diagram.css
- DuggaSys/diagram/zoom.js
- Shared/css/blackTheme.css
- Shared/icons/pad_lock.svg
The padlocks now don't expand the div, have the same position in light and dark mode, and is visible in light and dark mode
> fixed padlocks #15267

- DuggaSys/microservices/courseedService/getCourseed_ms.php
Test the microservice by going to this url: `http://localhost/LenaSYS/DuggaSys/microservices/courseedService/getCourseed_ms.php`
> G2 2024 v6 issue#15638

- newinstaller/installer_ui.php
- newinstaller/tools/install_engine.php
- newinstaller/tools/permissions.php
- newinstaller/tools/testdata_setup.php
1. First change the file `LenaSYS/newinstaller/tools/install_engine.php` to contain the proper pdo authentication settings. 
2. Run the code by navigating to [localhost/LenaSYS/newinstaller/installer.php](http://localhost/LenaSYS/newinstaller/installer.php). The output should look something like this: 
3. You can ensure that everything works properly by deleting the course directory `LenaSYS/courses`. Then run the installer again. If the course directory is created again, it works as intended.
> Implemented course directory creation for new installer

- DuggaSys/tests/microservices/courseedService/retrieveCourseedService_ms_test.php
Created the test for retrieveCourseedService_ms.php. The it uses the service getCourseed_ms.php, which retrieves the information from `retrieveCourseedService()`and returns it.
> G2 2024 v6 #15193

- Shared/css/style.css
- Shared/loginbox.php
Changed the max width to fit content in the loginbox and set the logintable to have some margin to look a bit nicer. The only thing that is now is that on some places where the loginbox-class is used as css when the content inside is not filled wider than 200px (min-width) it get pretty small. Attached some pictures where it is changed with the new css.
> Changed css for the loginbox

- backend-models/microservices/duggaSys services/Microservices.md
Deleted information about logUserEvent_ms.php and logServiceEvent_ms.php due to conclusion in research about these microservices in the issue #15532.
> G2 2024 v6 issue#15532

- DuggaSys/courseed.php
- Shared/css/style.css
moved all "style='X' " from courseed.php to style.css, check that everything visually works as normal. 
if you fined spelling mistakes or better suggestions for naming thing add that to.
> fixed all style in courseed.php to go in to style.css #15062

- DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
> fixed include

- DuggaSys/courseed.js
- DuggaSys/courseedservice.php
You should not see any errors in the console anymore since it has been handled and it should work to update/edit any course.
> G3 V6 #15581 successfully edit and update a course

- DuggaSys/microservices/sectionedService/getCourseVersions_ms.php
- DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
- Implemented _getCourseVersions_ms_ into _retrieveSectionedService_ms_.
- Used function `getCourseVersions($pdo)` to replace the older duplicated code that retrieved course versions.
- Inspect the changes
- Test a microservice that calls the _retrieveSectionedService_ms_ function to verify it handles expected outputs and returns an array containing version information.
> G2 2024 v6 issue#15605 - Implement 'getCourseVersions_ms' into 'retrieveSectionedService_ms'

- Shared/css/style.css
- Shared/navheader.php
Added new id for img.
Changed id in navheader
> Fixed img id

- newinstaller/installer_ui.php
- newinstaller/style.css
Created the new page described in for the issue, also fixed small alignments for page 3.
closes #15701
> g3-2024-v6-#15701

- DuggaSys/microservices/sectionedService/deleteListEntries_ms.php
- DuggaSys/tests/microservices/sectionedService/deleteListEntries_ms_test.php
The test has been created. Small changes were made to the MS.
> g2-2024-v6 issue #15685

- DuggaSys/microservices/sectionedService/updateQuizDeadline_ms.php
- DuggaSys/tests/microservices/sectionedService/updateQuizDeadline_ms_test.php
The test has been created. Small changes were made to the MS.
> G2-2024-v6 issue #15702

- DuggaSys/accessed.js
- Shared/SortableTableLibrary/sortableTable.js
- Shared/css/style.css
Added a function that removes classes "even" and "odd" from the table-rows that are rendered and adds them to the new ones that are rendered. Also puts the class "collapsed" to the table-rows that are hidden (collapsed) so they are not affected by the count of even odd as it was before. Had to make the function as an onclick property on the table-headings so it runs every time it sorts the table and in the function "returnedAccess" so it applies from the start of the rendering as well. Added correct css-variables to the table background so it works in darkmode as well and therefor removed the adding of class "changeColorInDarkModeTable" because this is now unnecessary .
> Applied new css and functions

- DuggaSys/darkmodeToggle.js
- DuggaSys/sectioned.js
An error appared in the console before where it said that 'drawswimlane is not defined' when toggling from light to dark mode.
Therefor the function has been erased from all pages except sectioned and an if or else has been made where the function is only called if available.
> The drawswimlane function should not be called 

- DuggaSys/microservices/sectionedService/retrieveAllCourseVersions_ms.php
Created the ms file retrieveAllCourseVersions_ms.php because the code hadn't been included in any other ms yet. The code is taken from the sectionedservice.php file from row 912 - 921.
Have not found where it is used yet but still implemented it because now everything from sectionedservice.php has been or will be implemented shortly.
> Created ms retrieveAllCourseVersions_ms.php issue#15652

- DuggaSys/microservices/sectionedService/updateListEntriesGradesystem_ms.php
- DuggaSys/tests/microservices/sectionedService/updateListEntriesGradesystem_ms_test.php
The test has been created. Small changes were made to the MS.
> g2-2024-v6 issue #15698

- DuggaSys/accessed.js
- DuggaSys/accessed.php
- Shared/css/style.css
Added an edit column and option to users in accessed.php. The cogwheel will show a box where users can be edited (this is yet to be implemented, but a placeholder will show).
To test this, you can use this link: http://localhost/LenaSYS/DuggaSys/accessed.php?courseid=2&coursevers=97732
Click on the cogwheel and see if the popup will show. This should also be tested for newly created users, which can be made from the fab button.
> Added an edit column and option to users in accessed.php G3 2024 v6 #15428

- newinstaller/installer_ui.js
- newinstaller/installer_ui.php
- newinstaller/style.css
- newinstaller/tools/components.php
Created page 5 for the new installer. This included:
* Rendering php-components.
* Creating additional php-components.
* Fix relevant styling in css stylesheet.
* Implement required Javascript to handle disable / enabling of sub-checkboxes.
* Fixed missing text-elements
* Fixed alignment of elements such as radio buttons / checkboxes
* Removed the ability to highlight text from checkboxes / radio buttons
This PR closes issue #15707
> g3-2024-v6-#15707

- Shared/css/style.css
- Shared/navheader.php
made the pop up on accessed.php search bar to change size depending on what is put into it. No more scroll. Changed the lower corners to be rounded and it now matches the color of the table shown
> G3 2024 v6 #15537

- Shared/dugga.js
> g2-2024-v6 issue #15745

- DuggaSys/sectioned.js
The function setCreatedDuggaAnimation() seems to do the work. By observing how it worked when a new list entry was being created it appeared that the same functionality should be used.
> G3 2024 V6 #15584 list entry is highlighted when updating/editing a list entry

- backend-models/microservices/duggaSys services/Microservices.md
See issue #15532 for reason behind deletion.
> Deleted hasAcess_ms.php from the dokumentation

- DuggaSys/microservices/sectionedService/getCourseVersions_ms.php
Fix getCourseVersions_ms.php. This makes the retrieveSectionedService run as intended.
> G2 2024 v6 issue#15753 fix getCourseVersions_ms.php

- .gitignore
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- DuggaSys/sectionedservice.php
Reverts HGustavs/LenaSYS#15749
> Revert "Adding a github repo to a Moment should now spawn the items right under it.  #15319"

- DuggaSys/sectioned.js
Reverts HGustavs/LenaSYS#15744
> Revert "G3 2024 V6 #15584 list entry is highlighted when updating/editing a list entry"

- DuggaSys/sectioned.js
Reverts HGustavs/LenaSYS#15743
> Revert "Removed a call to function"

- DuggaSys/gitfetchService.php
Reverts HGustavs/LenaSYS#15726
> Revert "Add handling of http status codes in the bfs()-method from gitfetchService"

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Reverts HGustavs/LenaSYS#15536
> Revert " Student Feedback Question illigal symbols."

- DuggaSys/tests/getCourseVersion_test.php
The new file test getCourseVersion  that will be use the test getCourseVersion_ms.php has now been created
> Created  getCourseVersion_test.php 

- DuggaSys/diagram/helpers/mouse.js
Created function getTopHeight() that calculate the height of the top object of sequence actor and sequence object. Then there is now a minimum value for y in snapSAToLifeline().
> G1 2024 v6 #15259

- DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
Fixed "tabs" not being retrieved correctly.
> G2 2024 v7 issue #15748

- DuggaSys/microservices/sectionedService/updateListEntriesTabs_ms.php
- DuggaSys/tests/microservices/sectionedService/updateListEntriesTabs_ms_test.php
The test has been created. The MS needed to be modified since it previously updated ```gradesystem``` instead of ```tabs```.
The branch has been rebased to v7.
> G2 2024 v7 issue #15700

- newinstaller/installer_ui.php
- newinstaller/tools/credentials_manager.php
- newinstaller/tools/install_engine.php
- newinstaller/tools/permissions.php
- newinstaller/tools/sse_receiver.js
- newinstaller/tools/sse_sender.php
- newinstaller/tools/testdata_setup.php
This has already been merged and tested, but disappeared after fixing several issues related to the weekly merge.
> Merge g3-2024-v7-#15636 into g3-2024-v7.

- DuggaSys/sectioned.js
changed the property of screenPos to 1 instead of 0 and it seems to work
> changed the property of screenPos

- DuggaSys/sectioned.js
Removed the call to the "initInputColorTheme". This function sets the black theme properties but it seems to be unnecessary though the black theme works as it should without this call.
Look in the issue (https://github.com/HGustavs/LenaSYS/issues/15662) to see how to test the fault of the input.
> Removed call to function

- backend-models/microservices/duggaSys services/Microservices.md
> G2 2024 v7 issue#15515

- DuggaSys/diagram.js
- DuggaSys/diagram/draw/node.js
Removed nodes that only resize in one direction. Modified delta to always resize both directions to the largest size.
> inital/final state resizing #14828

- DuggaSys/diagram/theme.js
Centered all elements  on cursor
> G1 2024 v6 #14922 2

- DuggaSys/tests/microservices/sectionedService/getUserDuggaFeedback_ms_test.php
Created test for microservice _getUserDuggaFeedback_ms_test.php_
Does not give the expected output from the microservice but works on the monolithic service.
Inspect and run the test. 
This test can aid in debugging and fixing the _getUserDuggaFeedback_ms_ microservice.
> G2 2024 v7 issue#15692 - Create test for microservice getUserDuggaFeedback_ms

- newinstaller/installer_ui.php
- newinstaller/style.css
- newinstaller/tools/components.php
Finnished implementing page 6 to work as intended, and look like the figma mockup. This included creation of php-functions, fixing some styling with css as well as rendering the php function as html.
Closes #15785
> PR g3-2024-v7-#15785

- DuggaSys/sectioned.php
- Shared/css/style.css
Added the changes from the old branch to the new branch due to problems with the weekly merge, which had resulted in reverting a few commits back (including the one for the issue #15473). Therefore a new branch had to be created which included the adjustments to which fixed the problem of the weird positioning of the dropdown for the new item "+"- button.
> Added changes from old branch to new branch

- DuggaSys/courseedservice.php
Copied over the changes made in previously merged issue and made sure it worked.
See #15503 and #15450 for more detailed info.
**Testing:**
- make a course
- look for error
- you may also try on the old database, just beware that one foreign key contraint will appear unless you manually add an account and use it to make the course.
> Internal server error when trying to create a new course

- DuggaSys/diagram/classes/rect.js
> Wrote jsdocs for rect

- DuggaSys/accessed.js
- DuggaSys/accessed.php
- Shared/css/style.css
[a22edvbu](https://github.com/a22edvbu) commented [yesterday](https://github.com/HGustavs/LenaSYS/pull/15721#issue-2295179803) • 
Added an edit column and option to users in accessed.php. The cogwheel will show a box where users can be edited (this is yet to be implemented, but a placeholder will show).
image
To test this, you can use this link: http://localhost/LenaSYS/DuggaSys/accessed.php?courseid=2&coursevers=97732
Click on the cogwheel and see if the popup will show. This should also be tested for newly created users, which can be made from the fab button. @a22edvbu
> Remerge after revert

- DuggaSys/diagram.js
- DuggaSys/diagram/classes/stateChange.js
- DuggaSys/diagram/classes/stateChangeFactory.js
Changed JSDocs and minor code styling issues
> JSDoc update #15736

- DuggaSys/accessed.js
- DuggaSys/accessed.php
- Shared/css/style.css
Since the solution to the issue was lost after the weekly merge, the changes have been added to a new branch again. 
In the example below, when hovering the “+” button, an additional icon has been added named “add user”. 
When pressing on the icon, the following modal will appear with the label “Choose user” combined with a searchable dropdown menu. A save button has also been added. 
In the example below, the search ability is displayed with example “data”. 
Furthermore, the example below portrays the ability to just press the dropdown menu which then will display the different options. 
No further functionality has been implemented since it was not requested. Additionally, no specification regarding the “add user” icon has been made, therefore, the icon used is the same one as for …
> Added changes from the old branch to the new branch

- DuggaSys/sectioned.js
- Shared/css/style.css
managed to make the scroll function work but i couldnt make the scroll go any slower. also put up the time on the highlight so you cant miss which element is added
Test:
add new items in a course and make sure that it scrolls to the newly added element.
> Fix the automatic scroll function for new items

- DuggaSys/tests/microservices/sectionedService/getGroupValues_ms_test.php
> G2 2024 v7 issue#15690

- DuggaSys/diagram/draw/selection.js
Broke resize of elements with multiple boxes.
> Revert "(Doing this again cause some error) DeleteButton scales with size and zoomfact"

- DuggaSys/courseed.js
- DuggaSys/gitcommitService.php
- Shared/navheader.php
the code is now fixed since it was missing because of v6 merge problems
> G3 V7 #15581 successfully edit and update a course. (Changed the code back to work again)

- DuggaSys/diagram/draw/selection.js
Was not the problem, revert the revert.
> Revert "Revert "(Doing this again cause some error) DeleteButton scales with size and zoomfact"" // Was not the problem, revert the revert.

- DuggaSys/courseed.php
- Shared/css/style.css
moved all "style='X' " from courseed.php to style.css, check that everything visually works as normal.
if you fined spelling mistakes or better suggestions for naming thing add that to.
> fixed all style in courseed.php to go in to style.css #15062 Fixed after merge 

- DuggaSys/sectionedservice.php
Updated the query on line 755. Closes #15330.
> Updated sectionedService.php

- DuggaSys/diagram.js
- DuggaSys/diagram/classes/stateChangeFactory.js
Updated the JSDOC for stateChangeFactory.js
> Updated documentation #15779

- Shared/css/style.css
> Fixed login/logout css

- Shared/dugga.js
Some parameters like `pos` where not being sent in the ajax request being made in the kind "SECTION". It should now work.
> correct parameters are sent in the ajax request for the kind SECTION

- DuggaSys/tests/microservices/sectionedService/getCourseGroupsAndMembers_ms_test.php
Created the test for microservice _getCourseGroupsAndMembers_ms.php_
Inspect and test _getCourseGroupsAndMembers_ms_test.php_ located in _DuggaSys\tests\microservices\sectionedService_
> G2 2024 v7 issue#15686 - Create new test for the microservice getCourseGroupsAndMembers_ms.php

- DuggaSys/tests/microservices/courseedService/courseedService_documentation.md
Made documentation for the test-files in courseedService.
> G2 2024 v7 issue#15828

- DuggaSys/fileed.php
- Shared/navheader.php
Added the code (that was used to solve this issue last week) again as it seems it dissapeared
> g3-2024-v7-#15341 

- Shared/loginbox.php
Changed all tables in loginbox to a div structure instead
> G3 2024 v7 #15633

- DuggaSys/diagram/theme.js
the line removed is the cause for adding style="stroke: rgb(0, 0, 0)" which caused the text to appear bolded. from what i saw while messing around with the diagram i dont think that this messes anything up but im not 100% sure so it will need to be tested a bit better than i did
> fix for #15617

- DuggaSys/microservices/accessedService/addClass_ms.php
- DuggaSys/microservices/accessedService/retrieveAccessedService_ms.php
- DuggaSys/tests/microservices/accessedService/addClass_ms_test.php
The test was updated with a few changes.
The microservice was updated to use the retrieve MS.
The retrieve MS was updated to retrieve more information from the table "class".
> G2 2024 v7 issue #15377

- DuggaSys/microservices/sectionedService/readCourseGroupsAndMembers_ms.php
- DuggaSys/tests/microservices/sectionedService/readCourseGroupsAndMembers_ms_test.php
- Shared/dugga.js
- backend-models/microservices/duggaSys services/Microservices.md
Renamed the microservice and everywhere it is called in the system. Also renamed the test for the microservice, along with the function name and the url.
Note, I´m not updating the names for the microservice in the database_related_micro_services since it will be obsolet when the documentationen is done. I´m also not updating the sectionedService_test.php, the function there is not the microservice per se.
> Renamed getCourseGroupsAndMembers_ms.php -> readCourseGroupsAndMembers_ms.php

- DuggaSys/accessed.js
- DuggaSys/accessed.php
- DuggaSys/accessedservice.php
Whats done:
Dropdown list in both Remove user and add user is filled with all users.
Add User now adds a user to the course without having to create one again.
Remove User now removes selected user from that course.
Changed so readaccess users is seen is the list and not just teachers.
Dynamic tooltipTerm for input validation.
Todo in future issues:
Add Classes?
Add Groups?
Maybe update Term value if user already exists in course while trying to Add User.
Testing:
All users should show in both dropdown lists (Add User and Remove User)
Try adding any user into any course. Then reload the page and it should show up as a list entry.
Try removing a user from a course. It should disappear from the list entries
> Reverted remerge "Add functionality to "Add User" && "Remove User" button #15562"

- DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
- DuggaSys/microservices/courseedService/createCourseVersion_ms.php
- DuggaSys/microservices/courseedService/createMOTD_ms.php
- DuggaSys/microservices/courseedService/createNewCourse_ms.php
- DuggaSys/microservices/courseedService/getCourseed_ms.php
- DuggaSys/microservices/courseedService/specialUpdate_ms.php
- DuggaSys/microservices/courseedService/updateActiveCourseVersion_courseed_ms.php
- DuggaSys/microservices/courseedService/updateCourse_ms.php
Changed the microservices in the courseedService folder to all assign $userid with the getUid function, look in issue for more info.
This shouldn’t break any systems since $userid is still being retrieved in the same way, just using getUid instead of retrieving it manually. I tested most of the microservices after I updated them and didn't find any issues but a second look would be good.
I tested by using the courseedService test-files and also tried out all the microservices I could find on the website, after switching them out in dugga.js.
> G2 2024 v7 issue#15987

- DuggaSys/diagram/classes/element.js
- DuggaSys/diagram/theme.js
> documentation for element.js

- DuggaSys/sectioned.js
- Shared/dugga.js
Removed the console.log that cluttered the console. See the issue https://github.com/HGustavs/LenaSYS/issues/15626 to see how it looked before. Also check with the responsible of issue (d22mikwe) or group leader (a22moamy) if it is correct.
> G3 2024 v7 #15626

- DuggaSys/microservices/accessedService/addUser_ms.php
- DuggaSys/tests/microservices/accessedService/addUser_ms_test.php
A few changes were made to both the test and the MS.
The expected output for this test does not include everything that ideally should be included. But since users are not retrieved from the retrieve MS, this is what it has to look like.
> G2 2024 v7 issue #16003

- DuggaSys/microservices/duggaedService/updateDugga_ms.php
Updated updateDugga_ms.php to assign $userid with the getUid function.
> g2-2024-v7-issue#16060

- DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
Since the delete function is not currently testable, only sorting when adding to `listentries`  will be implemented in this pull.
To test 
1. Create a new course
2. Add several elements
3. Ensure that there is no duplicate positions in the database. (positions start at 1)
4.Optionally, add a github fetch to course and choose code examples for moment section (don't forget to press refresh button on the section) and  then check if the added code examples appear under correct moment section.
> Added insertion sort function to createNewListentry in createNewListEntry_ms.php #16044

- DuggaSys/diagram/classes/rect.js
- DuggaSys/diagram/draw/boxSelect.js
- DuggaSys/diagram/draw/selection.js
- DuggaSys/diagram/helpers/boxSelect.js
Fixed scaling and color of "X" as well as  box select for lines
> G1 2024 v7 #15993

- DuggaSys/diagram/draw/boxSelect.js
> G1 2024 #15781

- DuggaSys/diagram/draw/element.js
- DuggaSys/diagram/helpers/mouse.js
> Revert "change color of ghost #15131"

- DuggaSys/diagram/draw/options.js
In DuggaSys/diagram/draw/options.js are some documentation for the function.
> G1 2024 v7 #15786

- DuggaSys/microservices/fileedService/updateFileLink_ms.php
Added fetching and checking of "path" to updateFileLink_ms.php, based on how it is done in the monolith. It does not have a use currently, since path is not set for any file when created using filereceive.php. However, I think it best to include the path-code in the microservice since it is exists in the monolith and will probably be relevant in the future.
> G2 2024 v7 issue#15980

- DuggaSys/accessed.js
I've implemented a small function named "updateCourseUsers()" that after a small delay reload the current page. The timeout ensures a reponse from the respective AJAX call and make sure the course users get updated correctly. I experienced a lot of bugs when I did not use the timer.
I've also included if-statements to make sure users cannot add/delete users without any data in the input fields, which would trigger unnecessary page reloads.
> Implemented page reload after both adding & removing user from course

- DuggaSys/accessed.js
d22mikwe
Collaborator
[d22mikwe](https://github.com/d22mikwe) commented [2 weeks ago](https://github.com/HGustavs/LenaSYS/pull/15559#issue-2287532008)
Fixed current iteration of keyup for enter and esc.
Integrated a check if popups are open in this eventlistener.
As the popups already has a close function attached to them we only go back if none are open.
Only current popups/modules in accessed are "createUser" and "addUser".
"removeUser" and "createClass" will be added later. These should be inserted into allPopups array when implemented.
For testing:
> ESC to go back in accessed #15440

- DuggaSys/microservices/codeviewerService/retrieveCodeviewerService_ms.php
Deleted unused variables in retrieveCodeviewerService_ms.php
> G2 2024 v7 issue#16093

- DuggaSys/microservices/gitCommitService/refreshGithubRepo_ms.php
> G2 2024 v7 issue #16094

- DuggaSys/sectioned.js
- Shared/navheader.php
New pull request after the issue didnt go through the merge. 
How to test it:
Put your mouse on the icons for the titles that desrcibe the icons to appear. 
Fixed icons:
src='../Shared/icons/select.png'
src='../Shared/icons/PenT.svg'
src='../Shared/icons/list_docfiles.svg'
Themetoggle.svg
refreshIMG
> G3 2024 v7 #15054

- DuggaSys/microservices/sectionedService/createListEntry_ms.php
- DuggaSys/microservices/sharedMicroservices/createNewCodeExample_ms.php
- DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
Both createNewCodeExample and createNewListEntry are now returning a debug value. This value is used in createListEntry.
> G2 2024 v7 issue#16097

- DuggaSys/sectioned.js
Added an if-statement that checks if the data in the entry "grpmembershp" is not null to prevent the code from brake from the split() function of null-value.
> Added a check for data entry

- DuggaSys/diagram/draw/ruler.js
added documentation for ruler.js
> updated documentation for ruler.js

- DuggaSys/tests/microservices/accessedService/addUser_ms_test.php
Updated the filter-output and the expected-output.
> G2 2024 v7 issue #16123

- includeInstructions.md
go through the instructions. Maybe any inputs?
> made md file and wrote instructions

- DuggaSys/courseed.php
- DuggaSys/duggaed.php
- DuggaSys/fileed.php
- DuggaSys/sectioned.php
- Shared/css/style.css
It is now more clearer how the popup forms are constructed
Extra:
* Removed hidden legacy dialogs.
* Added an empty wrapper for special cases
* Moved some wrapper into correct element.
* completed Edit Dugga with new convention
Now have the missing padding (fileed.php)
The Buttons are now aligned more conventionally.
> Extended formBody and fomFooter #16059

- DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
Added checks for login, permissions and opt before the queries in the microservice are made. If any of them fails a return is made.
> G2 2024 v7 issue#16125

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/navheader.php
The timer no longer starts without a Github repo link
If the string dosent contain certain elements that all github links have you cant save them
WARNING TO TESTER:
If you get a red toast warning when pressing the repo button you have to enter a github token on that course. You do this here.
It has to be a valid github token not just random text
> Fixing buggs with github repo button 

- DuggaSys/accessed.js
- DuggaSys/codeviewer.js
- DuggaSys/sectioned.js
- Shared/toast.php
Implemented it in codeviewer and accessed too
> Fixed probem with esc button. toastContainer  was somehow changed

- newinstaller/installer_ui.js
- newinstaller/tools/db_setup.php
- newinstaller/tools/install_engine.php
Added the missing installer options as detailed in issue #16103
> Merge of #16103 to g3-2024-v7

- Shared/css/style.css
The animation was done by the glowAnimation keyframes.
It has been made 20% faster (8 seconds instead of 10) and the color has been changed to the same green that is used as the background for the logout button, as requested.
For testing:
Create a new code item ( or whichever item you want) and make sure that the animation of the row is a fading green over 8 secs.
> Changed animatiom for new list items in sectioned.php

- DuggaSys/microservices/sectionedService/readUserDuggaFeedback_ms.php
- DuggaSys/tests/microservices/sectionedService/readUserDuggaFeedback_ms_test.php
- Shared/dugga.js
Added feedbackquestion to the microservice and the test for the microservice, updated URL in AJAX call under USERFB condition and removed the case "GETUF" because it was never used and did not work as intended.
> Added 'feedbackquestion' into the microservice and the test for the ms

- DuggaSys/diagram/draw/line.js
> Reimplemented recursive relation on ER diagram

- DuggaSys/duggaedservice.php
- DuggaSys/tests/newUpdateTime_test.php
A new test file has been created for the microservice newUpdateTime.
> A test file for the ms newUpdateTime has been made. 

- DuggaSys/diagram/classes/stateChangeFactory.js
- DuggaSys/diagram/helpers/rect.js
- DuggaSys/microservices/courseedService/changeActiveCourseVersion_courseed_ms.php
- DuggaSys/microservices/courseedService/getCourseed_ms.php
- DuggaSys/microservices/sectionedService/changeActiveCourseVersion_sectioned_ms.php
- DuggaSys/microservices/sectionedService/getCourseGroupsAndMembers_ms.php
- DuggaSys/microservices/sectionedService/getCourseVersions_ms.php
- DuggaSys/microservices/sectionedService/getDeletedListEntries_ms.php
- DuggaSys/microservices/sectionedService/getGroupValues_ms.php
- DuggaSys/microservices/sectionedService/getUserDuggaFeedback_ms.php
- DuggaSys/microservices/sectionedService/reorderListEntries_ms.php
- DuggaSys/microservices/sectionedService/setVisibleListentries_ms.php
- DuggaSys/microservices/sectionedService/updateCourseVersion_sectioned_ms.php
- DuggaSys/microservices/sharedMicroservices/isSuperUser_ms.php
- DuggaSys/microservices/sharedMicroservices/logUserEvent_ms.php
- DuggaSys/microservices/sharedMicroservices/updateSecurityQuestion_ms.php
- DuggaSys/microservices/sharedMicroservices/updateUserPassword_ms.php
- DuggaSys/tests/duggaedservice-tests.php
- DuggaSys/tests/getdataUserAnswer_test.php
- DuggaSys/tests/microservices/courseedService/changeActiveCourseVersion_courseed_ms_test.php
- DuggaSys/tests/microservices/courseedService/deleteCourseMaterial_ms.php
- DuggaSys/tests/microservices/sectionedService/changeActiveCourseVersion_sectioned_ms_test.php
- DuggaSys/tests/microservices/sectionedService/setVisibleListentries_ms_test.php
- DuggaSys/tests/microservices/updateActiveUsers_ms_test.php
- Shared/css/style.css
- Shared/dugga.js
- backend-models/microservices/duggaSys services/Microservices.md
- newinstaller/new_components.js
- newinstaller/new_components.php
- newinstaller/tools/credentials_manager.php
The issue was to fix so the addElement and fabBtns hovers would work fine and be clickable which was done with css for the hover to be moved so the mouse still can interact with the new buttons without them diseppearing because of it being too far away. 
The functional issue within the same elements was to show that the addElement button (small plus) is clickable through it doing a spin when the mouse goes past it. As it is the 'head-element' on the page that shows the other buttons the user can interact with. This was made through changes in the if or else.
> Komplettering a22diako #16199

- Hello World
Test to see if i can commit to LenaSys. Added to hello world
> Testing out commit

- Hello World
Had wrong year, i was still in 2024 inside my head
> Wrote wrong year

- Hello World
> testAlexander

- Hello World
La till rader under hejhejhej och en liten smiley till slut
> Issue-000000 a20artje hello world

- DuggaSys/microservices/Microservices.md
fixed common spelling error in 71 places
> Fixed common typo in Microservices.md

- DuggaSys/fileed.js
- Shared/css/style.css
Fixed the higlighting so the full row is highlighted instead of a single cell.
Before 
After
> Fixed highlight in fileed.php

- DuggaSys/sectioned.php
- Shared/css/style.css
Buttons fixed, they now appear the same
> Fixed courseed and sectioned motd button

- DuggaSys/diagram/draw/selection.js
added documentation for selection.js, used JSdoc to describe the function as a whole and added some comments inside to clarify whats happening inside the function
> Komplettering b22jonan 15788

- DuggaSys/microservices/Microservices.md
Documentation created for specialupdate_ms.php in Microservices.md (courseedService). Includes brief description, inclusion of files and sql queries.
> 16213 create documentation for specialupdate msphp and add it in microservicesmd

- DuggaSys/diagram/draw/element.js
Moved the updated documentation from Pull Request #15782 for issue #15988. I also made some corrections to minor grammatical issues I found.
> Corrected some minor misspellings in the documentation.

- DuggaSys/diagram/draw/node.js
Reverts HGustavs/LenaSYS#16275
> Revert "added the corner node code to the start/end if statement"

- DuggaSys/microservices/Microservices.md
Changed the style of documentation regarding retrieveGitCommitservice_ms.php to match the rest of the document Microservices.md according to issue #16327 .
> G2 2025 v2 #16327 a23axehe

- DuggaSys/diagram/draw/element.js
Tested and implemented the solution from pull request #16236, so it can me merged with Master.
> 2025 Grupp 1 Integrating pull request from #16236

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Added comment. Two files use setAsActiveCourse -- updateCourseVersion_ms and updateCourseVersion_sectioned_ms
fixes #16386
> Documented where setAsActiveCourse is used

- DuggaSys/diagram.php
Stripped & escaped exposed variable outputs to mitigate XSS vulnerabilities.
> G3 2025 V2 #16240 fix variables in html output

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Added inverse dependencies for createNewListEntry_ms.php to the documentation file for #16381.
Found 3 files where this microservice is included.
> Added inverse dependencies for createNewListEntry_ms.php #16381

- Shared/css/style.css
Made the width of the buttons larger so now the text fits inside the buttons.
> Fixed text inside buttons

- DuggaSys/microservices/Microservices_inverse_dependencies.md
fixes issue #16385
edited in the DuggaSys/microservices/Microservices_inverse_dependencies.md
> Document inverse dependencies of  retrieveUsername_ms.php

- DuggaSys/microservices/Microservices_inverse_dependencies.md
No inverse dependencies found. Fixes issue #16394 . Added documentation to Microservices_inverse_dependencies.md
> Research inverse dependency for getAccessedService_ms.php

- DuggaSys/microservices/Microservices_inverse_dependencies.md
RetrieveAccessedService is include in addClass, addUser, getAccessedService and updateUser
fixes #16395
> Documented retrieveAccessedService

- DuggaSys/microservices/Microservices_inverse_dependencies.md
> No dependencies found for 'addClass_ms.php'

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Now I have added a list of all inverse dependencies in updateUserPassword section.
> Added a list of all inverse dependencies in updateUserPassword section

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Fixes issue #16380 Added the file names in the document under the given file createNewCodeExample
> Added inverse dependencies for createNewCodeExample_ms.php

- DuggaSys/microservices/Microservices.md
Fixed typo in microservices.md on getAccessedServices_ms.php. Fixes issue #16409 .
> Fix typo in Microservices.md

- DuggaSys/microservices/Microservices_inverse_dependencies.md
No inverse dependencies found. Fixes issue #16383.
> Documented inverse dependencies for isSuperUser_ms.php

- DuggaSys/codeviewer.php
- Shared/css/codeviewer.css
- Shared/css/style.css
Fixes issue #15064. All inline css in codeviewer.php has been moved to external CSS files, style.css or codeviewer.css
> Remove possible inline css #15064

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Fixes issue #16397 
No inverse dependencies found.
> Added updateUser inverse dependencies

- DuggaSys/microservices/Microservices_inverse_dependencies.md
No updateUserCourse_ms.php in any files. fixes issue #16396
> Updated microservices_inverse_dependencies

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Fixed #16449 for adding a text about inverse dependencies.
> Added a text about inverse dependencies

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Fixed delete function, wrong handling was made within the function deleteAll and deleteItem which resulted in error.
> G3 2025 #16334 bug restoration of deleted objects

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Found no inverse dependencies for updateCodeExampleTemplate_ms.php for the issue #16447.
> Added inverse dependencies: updateCodeExampleTemplate_ms.php #16447

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Created documentation for inverse dependencies for retrieveAllCourseedServiceData_ms.php. Fixes issue #16456 .
None found.
> Documentation for inverse dependencies retrieveAllCourseedServiceData_ms.php.

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Found all inverse dependencies of createDuggaVariant
Fixes issue #16470
> Found inverse dependencies - 16470

- DuggaSys/microservices/Microservices_inverse_dependencies.md
I have found a few inverse dependencies and added text in the Microservices_inverse_dependencies.md
> Added directory text

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Added documentation regarding inverse dependencies for updateDugga_ms.php. Fixes issue #16479 .
No dependencies found
> Add documentation regarding inverse dependencies

- DuggaSys/microservices/Microservices_inverse_dependencies.md
> Added documentation for updateActiveCourseVersion_courseed_ms.php

- DuggaSys/microservices/Microservices_inverse_dependencies.md
no inverse dependencies found.
> issue#16452

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Fixed issue #16450 and didn't find "include createCourseVersion_ms.php" in any file
> Updated microservices_inverse_dependencies for "createCourseVersion_ms"

- DuggaSys/courseed.php
- Shared/loadingButton.js
Added CreateCourse to eventListener in Shared\loadingButton.js and replaced the button for submitting course in DuggaSys\courseed.php.
Video of button behaviour:
https://github.com/user-attachments/assets/71ef327c-50c8-406b-9f67-f377ea91a612
Wiki for [loadingButton.js](https://github.com/HGustavs/LenaSYS/wiki/loadingButton.js) was extremely helpful.
> G3-2025-V2 issue #14980 replace button with loading button

- Shared/css/style.css
- Shared/navheader.php
Fixed the allignmentissue for the navbar items in accessed.php
> G3 2025 v2 fix alignment of navbar items in accessed.php #15534

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Fixes #16474, documented that no inverse dependencies were found.
> Documented inverse dependencies for deleteDugga_ms.php

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Found no inverse dependencies for specialUpdate_ms.php for the issue #16458
> Added inverse dependencies: specialUpdate_ms.php #16458

- DuggaSys/sectioned.js
Changed the function cancelDelete() to affect the right "class"-items. Also made some changes to deleteAll() function so that it removes from the internal class as well, not just the database.
> G3 2025 v2 #16344 fix undo

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Fixed issue #16475 . For retrieveDuggaedService.
> Updated dependencies.

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Disabled and commented out the old jQuery function and replaced it with a custom React-style drag-and-drop sorting. Added a login check to allow sorting only for logged-in users.
> Replace JQuery drag-and-drop with custom React-style #16412

- Shared/css/style.css
- Shared/navheader.php
Switched Jquery to React/Babel in the logout popup, requiring a rebuild (only solution i could think of) of popup and buttons
as per #16508
> Logout: Change JQuery to React/Babel

- DuggaSys/microservices/Microservices_inverse_dependencies.md
> G2 2025 v2 #16453

- DuggaSys/microservices/Microservices_inverse_dependencies.md
No inverse dependencies found.
Fixes issue #16478
> Documented inverse dependencies for updateDuggaVariant_ms.php

- DuggaSys/microservices/Microservices Documentation/template.md
Added folder for documentation and template
fixes #16574
> Create Documentation folder and template

- DuggaSys/fileed.php
- Shared/css/style.css
Resolves issue #15065. I have moved as much inline css from fileed.php to style.css as reasonably possible as well as some light cleanup. Nothing appears broken.
> Remove as much inline css as possible from fileed.php #15065

- DuggaSys/diagram.js
This is the solution to issue #16430.
> G1 2025 v2 16430 the diagram save button isnt working

- DuggaSys/microservices/endpointDirectory/endpointDirectory.php
- DuggaSys/microservices/endpointDirectory/nameQuery.php
Still needs to add database connection, right now there is only a link between the directory and the nameQuery file and the display of the information.
To test go to the php page of endpointDirectory:  http://localhost/LenaSYS/DuggaSys/microservices/endpointDirectory/endpointDirectory.php
Add ?name=whatever.
Some data should show up (same no matter the parameter).
Partly fixes issue #16519
> Add communication between EndpointDirectory and nameQuery - issue 16519

- DuggaSys/microservices/endpointDirectory/endpointDirectory.php
Merge branch to access database and this code on same branch
> NameQueries first iteration done 16519

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Documented inverse dependencies: changeActiveCourseVersion_sectioned_ms.php, createGithubCodeExample_ms.php for the issue #16593. Found no inverse dependencies for both of them.
> Documented inverse dependencies: changeActiveCourseVersion_sectioned_ms.php, createGithubCodeExample_ms.php #16593

- DuggaSys/microservices/Microservices_inverse_dependencies.md
No inverse dependencies found for either createListEntry or deleteListEntries.
fixes #16594
> Inverse dependencies for createListEntry and deleteListEntries

- DuggaSys/microservices/microservice_connections.md
I have updated the document further with information about the connections. There are many more, but I will continue with the documentation after the merge.
partly fixes #16566
> G2 2025 v2 #16566

- DuggaSys/microservices/Microservices_inverse_dependencies.md
> Documented lack of inverse dependencies in editCodeExample_ms.php

- newinstaller/installer_ui.js
I added a button when installer failed to install lenasys. This fixed issue #16152.
> Added a button when installer failed to install lenasys

- Shared/navheader.php
Removed Instance 5 and 6 of JQuery from #16427 
Simply removed dead JQuery code
> Replacing/removing Jquery from topbar with React/Babel

- DuggaSys/diagram/constants.js
Added some documentation that was missing for some new structures and functions. Changes some pre-existing documentation for easier readibility in constants.js.
Link to issue:
https://github.com/HGustavs/LenaSYS/issues/15794
> Added documentation for issue#15794

- DuggaSys/diagram/draw/update.js
Issue #15789, updated documentation was never merged.
> Documentation updated for DuggaSys\diagram\draw\update.js

- DuggaSys/diagram/draw/line.js
The main issue here was that getLineAttributes returned the incorrect value for t.x when the lineDirection was left, returning x1 instead of x2, which didn't align with the value pattern the other directions were returning. **This should and probably will affect all types of lines**, although it will most likely expose faulty handling of line alignment.
Added special offsets for the UMLFinalstate, making sure that the line anchors to the outer ring at all zoom levels. 
Also took the opportunity to tweak alignments for the other SD elements, making the line anchor a bit into the element, instead of right on the edge, which in my opinion looked and felt nicer during usage (very easily removed if unwanted).
**KNOWN ISSUES:**
- Line spacing permanently changes anchor position, never reverting …
> [Issue #16536] Fixed line anchoring to UML FinalState elements

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/components/Button.js
Trashcan button has been refactored to use a reusable React component `Button.js` located in `/Shared/components/Button.js`.
Created a resuable React button component `Button.js`  located in `/Shared/components/Button.js`.
jQuery logic for the trashcan button has been replaced with JavaScript in `sectioned.js` located in `/DuggaSys/sectioned.js`.
The HTML for the `delete-item-button` and `close-item-button` in `/DuggaSys/sectioned.php` has been converted to React to using the  `Button.js` component.
> Refactoring of the trashcan button to use a React button component 

- DuggaSys/microservices/Microservices_inverse_dependencies.md
> Document inverse dependencies for updateVisibleListEntries

- DuggaSys/microservices/endpointDirectory/endpointDirectory.php
- DuggaSys/microservices/endpointDirectory/parameterQuery.php
Made a query for searching for parameters in the microservice documentation database. Fixes #16520.
Although, when the database is finished the query might need to be updated (small change)
> G2 2025 v3 #16520 a23oskme

- DuggaSys/diagram/draw/line.js
Solution to issue: [#16647](https://github.com/HGustavs/LenaSYS/issues/16647)
To have a line being able to have different offset on each side is done here by adding new properties to the line object inside the checkAdjacentLines and then inside drawLine give different offset defendant on these properties. checkAdjacentLines checks if i object have lines going out or coming in, and dependent on that set values to these new properties so the right x and y gets increased.
[Screencast from 2025-04-16 14-07-19.webm](https://github.com/user-attachments/assets/5957393a-212d-4554-92b2-7768b37281a3)
> Lines should now move towards center when neighbor lines are removed

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Found inverse dependencies for retrieveFileedService and updateFileLink
Fixes issue  #16728
> Documented inverse dependencies for retrieveFileedService and updateFileLink

- DuggaSys/microservices/Microservices_inverse_dependencies.md
found 1 inverse dependency for insertIntoSQLite and 0 for getCourseID
fixes #16731
> Issue#16731

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Documented inverse dependencies for getUserAnswer_ms.php and retrieveResultedService_ms.php. Found one inverse denpendencies for retrieveResultedService_ms.php.
Fixes #16792
> Document inverse dependencies: the two files in /resultedService #16792

- DuggaSys/microservices/Microservices Documentation/microserviceCodingStandard.md
Created an md file regarding how to change the microservices from dependencies to http requests.
Fixes issue #16665
> Microservice conversion coding standard 

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Added for processDuggaFile and retrieveShowDuggaService
Fixes Issue #16794
> Added inverse dependencies - Issue #16794

- newinstaller/tools/modal.js
I have fixed #16507 for adding selection to check if buttons are not null.
> Added selection to check if buttons are not null

- dockerenv/document/docker_install_instructions.md
Corrected grammar and fixed typos in the file docker_install_instructions.md. This fixes issue #16801 .
> Fix grammar and typos for docker_install_instructions.md

- DuggaSys/microservices/Microservices_inverse_dependencies.md
Standardized the documentation with lists instead of links.
> standardized documentation

- DuggaSys/diagram.css
Increased toolbar width and icon size for better visibility on large screens
Before
After
> Updated diagram.css

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/components/Button.js
Cogwheel button has been refactored to use a reusable React component `Button.js` located in `/Shared/components/Button.js`.
jQuery logic for the related to the cogwheel button has been replaced with JavaScript in `sectioned.js` located in `/DuggaSys/sectioned.js`.
HTML for save/cancel button of  "edit section dialog" has been converted to React using the `Button.js` component
> Refactoring of the cogwheel button to use a React button component

- DuggaSys/microservices/microservice_connections.md
Finished the documentation in issue #16566 and #16635
> G2 2025 v3 #16635

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/components/Button.js
Reverts HGustavs/LenaSYS#16837
> Revert "Refactoring of the cogwheel button to use a React button component"

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
This pull request solves issue #16685 by tweaking the size and positioning of the "load dugga" button. For further info see comment left on issue conversation.
> Fixed Load Dugga button in sectioned

- DuggaSys/codeviewer.js
changed the JQuery used in codeviewer.js with normal JS #16768, between the lines 1029 - line 1499
> Changed the JQuery used in codeviewer.js with normal JS - G3 2025 v4 a23alera #16768 

- DuggaSys/codeviewer.js
Reverts HGustavs/LenaSYS#16877
> Revert "Remove the jquery UI in code viewer #16718"

- DuggaSys/microservices/courseCreationAcceptanceTest.php
Test to check if course creation with giturl works.
Location of file is not good, don't know where it should be.
Should fix issue #16512 if I understood it correctly.
To test you can comment the delete part of the test and the course should appear in the database.
> Create courseCreationAcceptanceTest.php #16512

- DuggaSys/microservices/highscoreService/highscoreservice_ms.php
- DuggaSys/microservices/highscoreService/retrieveHighscoreService_ms.php
Re-engineered retrieveHighscoreService and its inverse dependencies. Also formatted the code using the built-in formatter, so some changes might look more than they are beacuse of the formatting. 
This fixes issue #16870
> Re-engineer microservice retrieveHighscoreService #16870

- DuggaSys/sectioned.js
Since there was some problems within merges and code was overwritten, troubleshoot and brought the code back. To avoid further problems, removed conflicts.
> G3-2025-V4-#16336-delete-without-selection-V3-MergeFix

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/components/Button.js
Cogwheel button has been refactored to use a reusable React component `Button.js` located in `/Shared/components/Button.js`.
jQuery logic for the related to the cogwheel button has been replaced with JavaScript in `sectioned.js` located in `/DuggaSys/sectioned.js`.
HTML for save/cancel button of  "edit section dialog" has been converted to React using the `Button.js` component.
This is the continuation of the pull request[#16837](https://github.com/HGustavs/LenaSYS/pull/16837#event-17364560509) fixing the bug: broken/non-functional FAB button. 
PR #16837 merged into branch G3-2025-V3 and got unmerged with PR [#16844](https://github.com/HGustavs/LenaSYS/pull/16844).
> FAB button bug fixed: refactoring of the cogwheel button to use a React button component

- Shared/css/style.css
The mobile styling where overwriting my previous styling that fixed the visibility of the text in swimlanes, so I removed it.
> G3 2025 v4 issue 16738

- DuggaSys/sectioned.js
Fixes #16748 I have changed the found jquery between lines 2184-2573. I haven't found any error when using the program.
> Changed jquery between lines 2184-2573 in sectioned.js

- DuggaSys/diagram.js
- DuggaSys/diagram/draw/element.js
A sollution for [#16868](https://github.com/HGustavs/LenaSYS/issues/16868) 
Changed so the autosave file is now called latestChange and keeps track of the latest user action on the canvas and saves them. So instead if it having only the first save, it now keeps the latest thing a person did. As its not a save per say any more, it just keeps track of what he last thing the user did was. 
If the program crash before a user saves, it should keep track of how the canvas looked. As long as no new input is given. 
It does not distinguish between save files, there is only one latest change.
[Screencast from 2025-04-28 09-31-47.webm](https://github.com/user-attachments/assets/95498ef8-966f-4b60-9d7f-8615c4e07163)
> AutoSave is now latestChange (name Subject to change)

- DuggaSys/sectioned.js
This PR is focused on the returnedSection(data) function (alot of code)
> Locate and change the JQuery used in sectioned.js with normal JS -= commands =- returnedSection(data)#16745

- DuggaSys/courseed.js
- DuggaSys/courseed.php
All JQuery I could find has been converted to JS in courseed.js. I have done testing and all appears fine. I made JS functions for the fade animations that JQuery implemented. The JQuery .ajax() requests have been replaced with fetch and in some places XMLHTTPRequest since fetch was not able to return a boolean without changing every implementation where the function is called. The refactor would be too large for this issue, but will have to be done at some point. Added flatpickr library to replace the JQuery datepicker.
> G3-2025-V4-#16642 JQuery to JS in courseed.js

- DuggaSys/microservices/codeviewerService/deleteCodeExample_ms.php
- DuggaSys/microservices/codeviewerService/editBoxTitle_ms.php
- DuggaSys/microservices/codeviewerService/editCodeExample_ms.php
- DuggaSys/microservices/codeviewerService/editContentOfExample_ms.php
- DuggaSys/microservices/codeviewerService/retrieveCodeviewerService_ms.php
Re-engineered retrieveCodeviewerService and its inverse dependencies. Also formatted the code using the built-in formatter, so some changes might look more than they are beacuse of the formatting. I hope I did the re-engineer part correct, still not sure. 
This fixes issue #16830.
> Re-engineered microservice retrieveCodeviewerService #16830

- DuggaSys/diagram/draw/element.js
- DuggaSys/diagram/helper.js
- DuggaSys/diagram/helpers/mouse.js
The activity box can be placed on the top of object version.
> G1 2025 v4 16838 sequence activity box cant connect to the top a sequence object

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
Rewrote the logic for motd banner
Previous
Now with changes
The content has been placed in flexboxes and aligned correctly relative to the size of their parent containers, and smaller devices with extra support using media queries.
> Fix message of the day on mobile #16800

- DuggaSys/codeviewer.js
Changed the JQuery to JS between line 2502 - 2981
> Changed the JQuery to JS #16671

- DuggaSys/microservices/Microservices Documentation/microserviceRefactorGET.md
A tutorial for the replacing of functions with a return and no parameters sent.
Fixes Issue #16933
> Get tutorial for refactoring - Issue #16933

- DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
> Documented updateUserPassword_ms.php

- DuggaSys/microservices/endpointDirectory/microserviceUI.php
Fixes #16968 and adds functionality to the delete button in the microservice UI. To test this go into microserviceUI.php, then view a microservice, then press delete (re-install database to reset microservices after deletion if you wanna test again).
> Added delete functionality to the UI

- DuggaSys/microservices/Microservices Documentation/accessedService.md
Documented addClass and addUser from the accessedService map. Unsure if the $newusers input parameter in addUser should be the same as $newclass in addClass, since newusers can affect 2 tables depending on the situation?
fixes #17012
> Documented addCladd and addUser

- DuggaSys/microservices/resultedService/getUserAnswer_ms.php
- DuggaSys/microservices/resultedService/retrieveResultedService_ms.php
Fixing issue "Re-engineer microservice retrieveResultedService #16951 "
> Re-engineer microservice retrieveResultedService #16951

- DuggaSys/microservices/Microservices Documentation/microserviceRefactorPOSTWithAnswer.md
Added same clarifications to tutorial as other POST tutorial
Fixes issue #16976
> Added clarifications to tutorial 16976

- DuggaSys/diagram/errorHandling.js
Reviewed the code and identified that there was logic for validating ER entities and relations, so this wasn't the issue. The main issue was a broken loop, where the iteration over the lines array was not handled correctly, causing connection checks to fail. This was corrected by fixing the loop to iterate through all lines. Also implemented a new error check that seemed reasonable that ensures that ER entities without any connections (lonely entities) are flagged as errors.
In the screenshot down below you can see that after creating your model and then clicking the error detection button it now flags errors that are implemented in the logic. For example entities with no connections are marked as errors, entities with no primary key, entities with a relation that are missing cardinality, …
> Fix for error checking & added one new error check issue #16972

- DuggaSys/diagram/helpers/mouse.js
Updated mouse.js so the sequenceActivation doesn't snap to the lifeline on the y-axis, when outside the range. Checks have been implemented to see it the lifeline has ended, and if that is the case the sequenceActivation does not snap to the y-axis. 
If the sequenceActivation is moved into the lifelines range it will still snap to it!
https://github.com/user-attachments/assets/fdf65ecc-8b9d-4f97-8d5f-09c23ccb66a8
> Fixed sequenceActiation to not snap to the lifeline when outside the range

- DuggaSys/microservices/Microservices Documentation/sectionedService.md
Documentation for microservices createListEntry and deleteListEntries in sectionedService.
Could not find the parameter type for $opt and I am a little unsure about $log_uuid as well.
fixes #16985
> Documentation for microservices createListEntry and deleteListEntries.

- DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
- DuggaSys/microservices/Microservices Documentation/template.md
Documented the two first files in the sharedMicroservices file. Unsure of calling methods in createNewCodeExample, and if examples of use is necessary in both?
fixes #16678
> Documentation for createNewCodeExample and createNewListEntry

- DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
Documented getUid and isSuperUser from the sharedMicroservices folder. Unsure if examples of use is necessary.
fixes #16913
> Documentation of getUid_ms.php and isSuperUser_ms.php

- DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
> Documented setAsActiveCourse and updateSecurityQuestion

- DuggaSys/backToTop.js
Replaced jQuery with JavaScript in `/DuggaSys/backToTop.js` .
> Replaced jQuery with JavaScript in backToTop.js

- DuggaSys/sectioned.js
jQuery code has NOW been replaced with JavaScript in the file `sectioned.js` between  L4084-4757(end of file). 
Make sure you...
- log in as admin 
- enable student feedback: Settings for a dugga --> Enable student feedback
...before testing.
> Replaced jQuery with JS in sectioned.js between L4084-4757(end of file)

- DuggaSys/backToTop.js
Reverts HGustavs/LenaSYS#17031
> Revert "Replaced jQuery with JavaScript in backToTop.js"

- DuggaSys/sectioned.js
Swapped the Jquery for javascript as mentioned in the issue
> G3 2025 v4 locate and change the j query used in sectioned.js with normal js   setup and event listeners   line 3530   4082

- DuggaSys/diagram/draw/line.js
Small update to hopefully fix the problem that occurred after merge where no recursive relations worked.
> Updated str to lineStr

- DuggaSys/microservices/Microservices Documentation/accessedService.md
- DuggaSys/microservices/Microservices Documentation/template.md
Made the template a little bit more clear regarding names and fixed accessedService.md. Fixed #17059
> Make the template more clear for documentation of Microservices + fix accessedService.md #17059

- DuggaSys/microservices/endpointDirectory/microserviceUI.php
Fixes #17061 where old code was merged and problems occured with the microservice UI.
> Reverted to original working code WITH the try catch

- DuggaSys/microservices/Microservices Documentation/sharedMicroservices.md
Reorganized so the documentation is in the correct order, and added the parts that were missing
fixes #17077
> Resolved conflicts in sharedMicroservices documentation

- DuggaSys/microservices/endpointDirectory/microserviceUI.php
Added a query to get outputs from the outputs table and added a table that looks like the parameter table to present the outputs. Fixes #17065
> Fix underfined array key warnings for output fields in microserviceUI.php. #17065

- DuggaSys/pushnotifications.js
Replaced jQuery with JavaScript in `/DuggaSys/pushnotifications.js` .
The functionality should remain unchanged. However, I was unable to verify whether it works because the profile page (of brom) shows the message "Notifications subsystems not installed, notifications unavailable.". When attempting to directly access the file `pushnotifications.php` from [https://localhost/LenaSYS](https://localhost/LenaSYS/DuggaSys/courseed.php) you are directed to this page:
Which does not say much. This behaviour is consistent across both the week branch and the issue sub-branch.
> Replaced jQuery with JavaScript in pushnotifications.js

- DuggaSys/courseed.js
- DuggaSys/courseed.php
- Shared/css/style.css
- Shared/navheader.php
Fixes #16856. 
I moved last weeks work to this branch. Last week I added the hamburger menu icon and and the functions needed for it to work as well added home and darkmode buttons to the menu. 
This week I moved the 'Message of the day' icon to the menu as well. 
Now it looks like this:
> G3 2025 v5 #16856 navbtns disappears in mobile

- DuggaSys/backToTop.js
Replaced jQuery with JavaScript in `/DuggaSys/backToTop.js` .
> Replaced jQuery with JavaScript in backToTop.js (NEW)

- DuggaSys/diagram.css
- DuggaSys/diagram/draw/options.js
Fixed some issues with the string generation in the ER-table mentioned here https://github.com/HGustavs/LenaSYS/issues/17113
_Before_
_After_
> Fixed some issues with ER-table generation

- newinstaller/installer_ui.js
- newinstaller/installer_ui.php
- newinstaller/style.css
- newinstaller/tools/modal.js
- newinstaller/tools/modal.php
- newinstaller/tools/sse_receiver.js
I have now implemented the modal for issue #16039. This pull request continues work from pull request #17028, but it doesn't work on macOS with XAMPP and merge deadline has passed, it was closed. I'm having problems with XAMPP, so I can't test it there, instead, I'm using Docker on Windows. This issue #17058 was tested on macOS with XAMPP and got some problems with the new installer, so there is sub-issue for that, but I know it works on Windows with Docker. 
There is Docker install guide here: https://github.com/HGustavs/LenaSYS/blob/master/dockerenv/document/docker_install_instructions.md
To get a database connection error, you need to enter an incorrect root username, password, or hostname. Im using docker, so hostname is db and if you use xampp then read this …
> Added specific error handling for events modal in new installer. Use Docker and Windows to test it.

- DuggaSys/microservices/Microservices Documentation/accessedService.md
Documented getAccessedService_ms and retrieveAccessedService_ms
fixes #17118
> Documented getAccessedService_ms and retrieveAccessedService_ms

- DuggaSys/microservices/endpointDirectory/microserviceUI.php
When a database isn't created and microservicesUI.php is accessed the page now features a button that installs a database and reloads the page. Solves issue #17074
> Added a button to create database in microservicesUI.php

- DuggaSys/microservices/showDuggaService/getShowDugga_ms.php
- DuggaSys/microservices/showDuggaService/loadDugga_ms.php
- DuggaSys/microservices/showDuggaService/retrieveShowDuggaService_ms.php
- DuggaSys/microservices/showDuggaService/saveDugga_ms.php
- DuggaSys/microservices/showDuggaService/updateActiveUsers_ms.php
> Re-engineer microservice retrieveShowDuggaService #16979

- README.md
Added macOS command to instructions in README.md
Solves issue #16914
> Added macOS command to instructions

- DuggaSys/microservices/sectionedService/readCourseVersions_ms.php
- DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php
> updated readCourseVersions to use cURL

- DuggaSys/diagram/draw/element.js
Closes #17192.
Since I was the one who introduced the ugly space I made a quick fix here. 
_The fix_
https://github.com/user-attachments/assets/a702fd74-ad39-4438-90be-fe7a895ea720
> Added relative height for UML class

- DuggaSys/microservices/endpointDirectory/microserviceDirectoryDocumentation.md
Created an installation tutorial for the endpoint directory database, fixes #17106. 
Note that the table documentation isn't a part of this issue and has already been reviewed.
> Create a tutorial for installing the Microservice directory database #17106

- DuggaSys/microservices/endpointDirectory/microserviceUI.php
Added a button that allows the user to download the database. Fixes #17188
> Add database download button to microserviceUI #17188

- DuggaSys/microservices/Microservices Documentation/accessedService.md
Documented updateUser_ms and updateUserCourse_ms
> Documented updateUser_ms and updateUserCourse_ms

- dockerenv/document/docker_install_instructions.md
Fixes #17214. I have added macos command in Docker installation instructions and [Docker installation instructions on the GitHub wiki](https://github.com/HGustavs/LenaSYS/wiki/Docker-installation-instructions#run-containers-in-docker) in step 5.
> Added a command text "docker compose up --build" for macOS

- DuggaSys/microservices/showDuggaService/processDuggaFile_ms.php
- DuggaSys/microservices/showDuggaService/retrieveShowDuggaService_ms.php
Fixes sub-issue https://github.com/HGustavs/LenaSYS/issues/17078
Adds a function to handle all the calls for processDuggaFile from retrieveShowDuggaService.
Fixes the connection to the database for processDuggaFile to make future Re-engineers simpler.
To see documentation on the parent issue check the comment for the sub-issue.
> mini re-factor for duggaService

- DuggaSys/microservices/showDuggaService/getShowDugga_ms.php
- DuggaSys/microservices/showDuggaService/loadDugga_ms.php
- DuggaSys/microservices/showDuggaService/retrieveShowDuggaService_ms.php
- DuggaSys/microservices/showDuggaService/saveDugga_ms.php
- DuggaSys/microservices/showDuggaService/updateActiveUsers_ms.php
Reverts HGustavs/LenaSYS#17099
> Revert "Re-engineer microservice retrieveShowDuggaService #16979"

- Shared/css/style.css
The lock is now visible in dark coloured class boex.
> Updated style.css

- DuggaSys/microservices/accessedService/retrieveAccessedService_ms.php
- DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
- DuggaSys/microservices/courseedService/createCourseVersion_ms.php
- DuggaSys/microservices/courseedService/createNewCourse_ms.php
- DuggaSys/microservices/courseedService/updateCourseVersion_ms.php
- DuggaSys/microservices/courseedService/updateCourse_ms.php
- DuggaSys/microservices/fileedService/updateFileLink_ms.php
- DuggaSys/microservices/sectionedService/createListEntry_ms.php
- DuggaSys/microservices/sectionedService/updateCourseVersion_sectioned_ms.php
- DuggaSys/microservices/sharedMicroservices/createNewCodeExample_ms.php
- DuggaSys/microservices/sharedMicroservices/createNewListEntry_ms.php
> Changed microservice retrieveUsername to use curlService #17273

- DuggaSys/microservices/endpointDirectory/microserviceUI.php
Fixes #16964 and adds filter functionality to the microservice UI. As of now you can only filter between the calling methods POST and GET until more documentation is added. More filtering options in general can also be added later with more documentation and attributes to filter between. To test go into microserviceUI.php.
> Added filter functionality

- Shared/css/style.css
Did exactly the same change for a third time, make sure put a reviewer who know how to branch correctly this time and go to the mobile version of sectioned.php for an example of how this solution works check issue #16936
> Updated dateSize 3.0

- DuggaSys/profile.js
Moved all changes from last week's PR (#17073) to this one, the changes requested have been made and the code should work.
> G3 2025 v6 #17025 jquery to js in profile.js

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
Added four buttons to the Fab as per the mock up.
Buttons should appear when main button is clicked
> Implement sub menu for the fab a23carpa

- DuggaSys/microservices/Microservices Documentation/template.md
Added clearer instructions to the template for documenting microservices.
> Updated Microservices Documentation template.md

- DuggaSys/sectioned.php
- Shared/navheader.php
Fixed the motd button on course pages
> Fixed MOTD button #17244

- DuggaSys/diagram.js
Added event listeners to each of the buttons, to call the same functions as the desktop buttons do.
[Screencast from 2025-05-12 11-04-35.webm](https://github.com/user-attachments/assets/f89a48ac-c050-4f45-8002-21778c5fb710)
> Fab button functionality works

- newinstaller/installer_ui.php
- newinstaller/new_components.php
- newinstaller/test.html
- newinstaller/tools/modal.js
Fixes #16672. 
In the step 3 there is a checkbox `Use distributed enviroment` which it should updated the `coursesyspw.php` file located at `C:/LenaSYS/dockerenv/coursesyspw.php`, but the file never updated value `define("DB_USING_DOCKER", "")`. The `DB_USING_DOCKER` never add values or never updated, it doesn't matter if you check or uncheck `Use distributed enviroment`. 
In `installer_ui.php` there is a checkbox which says `distEnvironment`, but in an `install_engine.php` look for `distributed_environment` line 127. These names are not the same which `DB_USING_DOCKER` never uppdated which lead to acccess denied user.
I also updated `new_component.php` and `test.html`, but these are never used.
To test this here are all the steps:
Step 1: Select OS
Step 2: Select both checkboxes
Step 3: …
> Fixed acccess denied user, when go to a course page using new LenaSYS installer with docker

- DuggaSys/sectioned.js
**Unsure if this was an simplification, but I do believe that the code is (if not only) more readable now.** 
Also changed the function to be able to handle not only selectedItems (list), so reuse is better.
There should be no new functionalities, and the changes affect the selections which can be done on "duggor" within courses.
**One approach to testing this, and how to get to the functionality:**
select course of your choice (which has duggor, ex. Testing Course) -> log in -> test selection box 
(Image of selection boxes)
_note: I'm highly unsure if this is better or not. Please give feedback if changes not needed!_
> G3-2025-v6-#17291-markeditems-simplification

- DuggaSys/microservices/Microservices Documentation/resultedService.md
Added documentation in microservice folder resultedService i.e files getUserAnswer_ms.php and retrieveResultedService_ms.php. Fixed issue #17367
> added documentation for microservices in microservices/resultedService

- DuggaSys/microservices/Microservices Documentation/fileedService.md
Created documentation for all microservices in fileedService folder. Fixes issue #17362 .
> Documentation for fileedService folder

- DuggaSys/microservices/Microservices Documentation/codeviewerService.md
Fixes #17356 . I've documented the microservices deleteCodeExample_ms.php and editBoxTitle_ms.php in the file codeviewerService.md.
> documented microservices in /codeviewerService #17356

- DuggaSys/microservices/Microservices Documentation/duggaedService.md
Documented microservices microservices/duggaedService in /Microservices Documentation/duggaedService.md.
Fixes issue #17360
> documented microservices in microservices/duggaedService #17360

- DuggaSys/sectioned.js
The arrows now work as expected and hide the dugga lists.
> G3 2025 V6 fixed hide dugga list arrows

- DuggaSys/microservices/Microservices Documentation/gitFetchService.md
Did the documentation for the files:
bfs_ms
downloadToWebServer_ms
getGithubURL_ms
getIndexFile_ms
insertToFileLink_ms
insertToMetadata_ms
Fixes issue #17364
> G2 2025 v6 a20artje 17364

- DuggaSys/microservices/Microservices Documentation/courseedService.md
Document microservices in microservices/courseedService, fixes issue #17359.
> G2 2025 v6 #17359 Document microservices in microservices/courseedService

- DuggaSys/diagram.js
- DuggaSys/diagram/helper.js
Went through the entirety of diagram.js and updated the grammar and punctuation of existing comments and function descriptions. Added new comments and function descriptions where it was deemed necessary. Also updated the region tags in the document to show in the sidebar, providing easier navigation. Added a new region at the bottom for mobile code, where most of it seemed to be located.
Removed some comments and descriptions that didn't seem to have ties to any still existing code. Also added documentation to a function in helper.js that was _only_ used in diagram.js and nowhere else.
This should hopefully improve the clarity and ease of understanding when it comes to the many functions and classes in the file. Most, if not close to all undocumented code should be covered now. There are …
> [#17444] Revised comments and documentation in diagram.js

- DuggaSys/diagram/draw/element.js
> 17424 documentationcomments in elementjs

- DuggaSys/microservices/Microservices Documentation/codeviewerService.md
fixes #17447 . I've documented these two files from microservices/codeviewerService in codeviewerService.md.
> Documented editCodeExample_ms.php and editContentOfExample_ms.php #17447

- DuggaSys/diagram/draw/line.js
I have gone through line.js in its entirety and updated comments, descriptions and added some extra spaces for enhanced readablility within functions. Mostly I've tried to keep a clean structure to comments and therefore removed or added to some I deemed too abstract. For functions that were missing the parameter description at the start I added a somewhat coherent one. 
There were functions within functions calling each other and I don't know how many offset-calculating functions for labels and lines and I am not sure every single one of them is unique, or even used, but at least they are all (decently) commented now! I am not sure how much clarity I was able to provide for the line.js overall, since much of the beginning of this file consists of the monolithic function that is drawLine …
> Fixed: G1 2025 v7 #17426 documentationcomments in linejs

- DuggaSys/microservices/deprecated_microservices.md
Fixes #17594, adds file/documentation for existing and future depricated services.
> Added file/documentation for deprecated services

- DuggaSys/microservices/Microservices Documentation/showDuggaService.md
Documented all files in showDuggaService-map:
- getShowDugga_ms
- loadDugga_ms
- processDuggaFile_ms
- retrieveShowDuggaService_ms
- saveDugga_ms
- updateActiveUsers_ms
Documented them in a different order than in the actual microservice map, since one file relies on another etc. Not certain of AUtoken parameters, the different variant parameters and the contactable parameter.
> Documented all files in showDuggaService-map

- DuggaSys/sectioned.js
- Shared/css/style.css
Made a new PR for this issue after realising that it had not been merged. Changes made since approval is only that it has now been rebased for the current weeks groupbranch, hopefully it gets merged in time this week 🙏 
Please refer to previous PR for further inquiries:
#17037 
#17076 
#17310
> Changed jquery between lines 3014-3528 in sectioned.js for issue #16750 (Rebased)

- DuggaSys/templates/boxmodell.js
> Convert JQuery in \DuggaSys\templates\boxmodell.js - #17516

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram/toggle.js
- DuggaSys/templates/diagram_dugga.js
- Shared/css/mobile-diagram.css
Followed the mobile mock-up and made the the sidebar similar to the bottom menu.
Note: I was not able to implement the logout button, this will need a sub issue in the future.
The other buttons should work as their desktop versions. 
Second note: Save, load and reset dugga will not work in only the diagram.php file.
They need showdugga for specific functions.
[Screencast from 2025-05-16 13-18-10.webm](https://github.com/user-attachments/assets/6bd75813-17b9-4da9-90ab-71b39ed9e45a)
> Implemented sidebar for mobile

- DuggaSys/microservices/endpointDirectory/admin-endpointDirectory_db.php
> Added two alerts

- Shared/css/style.css
Replaced max-height with scaleY transform for smoother open/close animations. Added slight delay to opacity during close to enhance fade-out effect.
> animated view menu for closing #17396

- DuggaSys/microservices/Microservices Documentation/codeviewerService.md
Fixes #17619 . I've documented these two files in codeviewerService.md.
> Documented retrieveCodeviewerService_ms.php and updateCodeExampleTemplate_ms.php #17619

- DuggaSys/templates/kryss.js
Replaced jQuery with JS in `/DuggaSys/templates/kryss.js`. 
I have not been able to verify whether the JavaScript code works, the quiz (pen icon) button for the dugga does not work in both the week branch and the issue sub-branch(that's if you're logged in). Directly accessing the `kryss.html` file located in `/DuggaSys/templates/kryss.html` shows a non-interactable page with quiz instructions. Quiz instructions and the actual quiz displays while logged out but what is the actual purpose of this? It does not do anything when selecting an option. 
Comment on `kryss.js `file:
The `kryss.js` file seems like an experimental file, unfinished and casual.
> Replaced jQuery with JS in kryss.js

- DuggaSys/microservices/showDuggaService/processDuggaFile_ms.php
- DuggaSys/microservices/showDuggaService/retrieveShowDuggaService_ms.php
Fixes issue https://github.com/HGustavs/LenaSYS/issues/16978
To test this try to Load a dugga with and without the curlService include in the retieveShowDuggaService file.
This is the only place I could see that this code effected.
> curlService for processDuggaFile

- DuggaSys/microservices/courseedService/changeActiveCourseVersion_courseed_ms.php
- DuggaSys/microservices/courseedService/copyCourseVersion_ms.php
- DuggaSys/microservices/courseedService/createCourseVersion_ms.php
- DuggaSys/microservices/courseedService/createMOTD_ms.php
- DuggaSys/microservices/courseedService/createNewCourse_ms.php
- DuggaSys/microservices/courseedService/getCourseed_ms.php
- DuggaSys/microservices/courseedService/retrieveAllCourseedServiceData_ms.php
- DuggaSys/microservices/courseedService/retrieveCourseedService_ms.php
- DuggaSys/microservices/courseedService/specialUpdate_ms.php
- DuggaSys/microservices/courseedService/updateActiveCourseVersion_courseed_ms.php
- DuggaSys/microservices/courseedService/updateCourseVersion_ms.php
- DuggaSys/microservices/courseedService/updateCourse_ms.php
- Shared/dugga.js
Fixes #17602.
You can test seven microservices: createNewCourse_ms, createCourseVersion_ms, updateCourseVersion_ms, copyCourseVersion_ms, updateCourse_ms, createMOTD_ms, and specialUpdate_ms. These microservices are used in dugga.js.
The other microservices are not used in dugga.js because they never had AJAX implemented. Someone should create an issue to implement these microservices in dugga.js.
**createMOTD_ms:**
Click the gear-icon, enter a message, and save it. The text on the yellow banner will change.
**createNewCourse_ms:**
Click the yellow plus-button, enter the name and course code, and press save. The new course should appear.
**updateCourse_ms:**
Once you have created the course, click the gear-icon next to the course element and change the properties, an example the course …
> Re-engineered microservice retrieveCourseedService

- DuggaSys/templates/dugga5.js
last instance of JQuery is to be left alone, too big for this issue, since it requires creating its own complete function + possibly touching CSS
> Convert JQuery in \DuggaSys\templates\dugga5.js - #17534

- DuggaSys/templates/bit-dugga.js
- Shared/css/style.css
Converted all JQuery to JS, have tested the functions I could think of and haven't found any issues.
One thing to note is that saving duggas can only be done by students, not teachers or admins. It is also possible to be logged out.
> G3 2025 v7 17515 convert jquery in bit dugga.js

- DuggaSys/templates/seminar_dugga.js
convert jquery in LenaSYS\DuggaSys\templates\seminar_dugga.js
[#17525](https://github.com/HGustavs/LenaSYS/issues/17525)
> convert jquery in LenaSYS\DuggaSys\templates\seminar_dugga.js

- DuggaSys/diagram.css
Adjusted the toolbar icons sizing, they all now fit
> Adjusted toolbar issue #17705

- DuggaSys/templates/dugga3.js
Replaced JQuery within the file dugga3.js, which were represented via the course: _Webbutveckling - datorgrafik_, and its _Geometri_ section. Both Linjedugga 1 & 2 were affected by the changes, and should match the weekly branch in terms of functionality. 
_Note that other duggas might have been affected, though I haven't noticed any problems._
**Ignored functions:**
- Functions which contained AJAX, which will be replaced within another issue.
- Functions connected to feedback, which seems to be removed and will be replaced within another issue.
_That said, some of the functions within the most recent commit might have affected code related to feedback as well - ignore if so._
> G3-2025-v7-#17533-convert-jquery-in-dugga3.js

- DuggaSys/templates/transforms-dugga.js
I have converted the Jquery that was used in transforms-dugga.js to javascript.
The easiest way to test this is in Transforms Dugga in Demo-Course.
> Convert jquery in transforms-dugga.js #17520

- DuggaSys/codeviewer.js
I've removed the duplicated code, now it seems to work
> G3-2025-V7-(desktop-view) BUG Code is replicated and cut off in the codeviewer window #17458

- DuggaSys/microservices/Microservices Documentation/sectionedService.md
Fixes #17432 and adds documentation for the mentioned files. For testing, check so that the documentation is relevant to the specified file and that the varchar/int values are correct according to the database.
> Documented removeListEntries_ms.php and reorderListEntries_ms.php in sectionedService.md

- DuggaSys/microservices/sectionedService/createListEntry_ms.php
Fixes #17708 . I've removed "header("Content-Type: application/json");" and changed the URL so it works for the curlService function callMicroservicePOST. I also removed "global $pdo" as this gave an error.
> Fixed URL and removed header in sectionedService/createListEntry_ms.php #17708

- DuggaSys/microservices/microservice_connections.md
I have reformatted the text file according to the new template, updated the information in the document, and corrected spelling errors.
> Update microservice_connections #17427

- DuggaSys/microservices/Microservices Documentation/courseedService.md
Added the missing information.
> Add missing information to microservices/courseedService #17584

- DuggaSys/microservices/sharedMicroservices/setAsActiveCourse_ms.php
Fixes issue #17714
To test the solution change the active course version and check the database table "course".
To change active version in the database first change the version on the application, then press the cogwheel and fill in the parameter "change this to the default value. The active version should now be seen in the database.
> Added receieveMicroservicePOST for setAsActiveCourse

- DuggaSys/templates/html_css_dugga.js
- Shared/css/style.css
The feedback toggle was difficult to test since I couldn't find where it's triggered in the interface. However, the logic and CSS implementation should be correct based on the code.
> Replaced jQuery with vanilla JS in html_css_dugga.js #17540

- DuggaSys/microservices/endpointDirectory/microserviceUI.php
Added parameter search. Microservices that has a parameter that matches (using LIKE) the input will now be displayed when using the parameter search. Fixes #17789 
I also added some text that displays what was searched for (for all three different sorting options)
And I added a text that is outputted if there was no search results (the microservice table wont be outputted if empty either).
> Add parameter search to microserviceUI #17789

- Shared/css/style.css
I have fixed the problem of there being a Horizontal scroll bar in section.
> Horizontal scroll in section is gone #17794

- DuggaSys/sectioned.js
Added styling for code examples on mobile. Only applies to mobile screens and while logged in. Being on desktop or being logged out shows normal style.
> Added mobile styling to code

- DuggaSys/microservices/duggaedService/createDuggaVariant_ms.php
- DuggaSys/microservices/duggaedService/createDugga_ms.php
- DuggaSys/microservices/duggaedService/deleteDuggaVariant_ms.php
- DuggaSys/microservices/duggaedService/deleteDugga_ms.php
- DuggaSys/microservices/duggaedService/retrieveDuggaedService_ms.php
- DuggaSys/microservices/duggaedService/updateDuggaVariant_ms.php
- DuggaSys/microservices/duggaedService/updateDugga_ms.php
Fixes #17603.
Now all files are using `curlService.php`.
Well, you can't, because all new microservices are not used in `dugga.js`, which is located at `LenaSYS/Shared/dugga.js`.
However, I created a small `index.php` file with all input fields. You can feed in values and submit to `createDugga_ms.php`. I did **not** commit the `index.php` to the repo, because this file is only for testing and should not be included in the LenaSYS repo.
Instead, I’ve copy and paste the code below. This code should be saved as `index.php` inside of `LenaSYS/DuggaSys/microservices/duggaedService/index.php`. After creating the file, then navigate to URL in your browser to use it.
**Note:** This code only tests `createDugga_ms.php`, not the other files, but you can test other files if you want to.
Also, it's …
> Re-engineered microservice retrieveDuggaedService

- DuggaSys/microservices/Microservices Documentation/sectionedService.md
Added retrieveAllCourseVersions_ms.php and retrieveSectionedService_ms.php information to the /sectionedService documentation. Fixes issue #17433
> Document retrieveAllCourseVersions_ms.php and retrieveSectionedService_ms.php #17433

- DuggaSys/tests/microservices/fileedService/retrieveFileedService_ms.test.php
I have tested it on my machine it worked just fine. To test head to:  
lenasys/duggasys/tests/microservices/fileedService/retrieveFileedService_ms.test.php
And see if it passes all the tests. Fixes issue #17809 .
> Created a test for fileedService/retrieveFileedService_ms.php

- Shared/css/blackTheme.css
Instructions-content text now stays in one column
> Fixed the bug in dark mode for instructions #17498

- DuggaSys/templates/default.js
Converted the JQuery in default.js, I actually dont know where this is used or even if it is used in the current rendition of LenaSYS. So for testing purposes, I assume it might suffice to ensure that nothing breaks as a result of these changes. This PR solves issue https://github.com/HGustavs/LenaSYS/issues/17524. Changes from last weeks branch is that it has been rebased.
Previous PR: #17750 
Issue: #17524
>  Convert jquery in \DuggaSys\templates\default.js #17524

- DuggaSys/tests/microservices/resultedService/retrieveResultedService_ms_test.php
Made a test file for retrieveResultedService_ms.php and tested it.
http://localhost/lenasys/duggasys/tests/microservices/resultedService/retrieveResultedService_ms_test.php
#17811
> Created a test for resultedService/retrieveResultedService_ms.php #17811

- DuggaSys/templates/curve-dugga.js
Replaced jQuery with JS in `/DuggaSys/templates/curve-dugga.js`. 
Additionally, the toggle feedback and show facit features has not been introduced to the page yet, making it impossible to verify whether the JS conversion works as intended. Related functions: `toggleFeedback()`,  `showFacit()`
The `toggleFeedback()`  function in the end of the file have not been converted as there is no direct JavaScript equivalent for jQuery's `slideToggle()`  function, replacing it would require a custom implementation. This is too big part this issue and should therefore be addressed in a separate issue.
> Replaced jQuery with JS in curve-dugga.js 

- DuggaSys/templates/3d-dugga.js
- Shared/css/style.css
re-uploaded PR #17587 from last week, should work the same and I couldn't find any issues with it. For info on what has changed see old PR.
> G3 2025 v8 #17513 change jquery in 3d dugga

- DuggaSys/microservices/endpointDirectory/microserviceUI.php
- DuggaSys/microservices/endpointDirectory/style.css
Simply added a button on microserviceUI that takes the user to dependenciesUI.php. Fixes #17854
> Add button from microserviceUI to dependencyUI #17854

- Shared/css/style.css
- Shared/navheader.php
The alignment with the burgermenu button now is more aligned.
New allignment
Old
Remade becuase merged into master.
> Fixed misaligned burger menu (Remake)

- DuggaSys/diagram.js
mouseMode_onMouseUp() now closes the open mobile submenu (if there is one) after it finishes placing the element.
> Added fucntionality in mouseMode_onMouseUP()

- DuggaSys/microservices/Microservices Documentation/renamingMicroservices.md
Documented all files in microservices that are supposed to be renamed, along with which files will be affected after the renaming.
Included a short description of how to change the names of the microservices, and the purpose of the namechanges.
> Documented microservices to be renamed #17847

- DuggaSys/sectioned.js
Entry 4, 14 and 17 have been changed to use the modern javascript fetch method, while maintaining headers and toasts as best as possible.
Entry 4
Entry 14
Entry 17
> G3 2025 v8 #17178 locate and change ajax a23kavis

- Shared/css/blackTheme.css
updated darkmode to show white font
> Updated darkmode

- README.md
Fixes #17998 and stops sending the user to a new "reloaded" page of README.
> Removed "README.md" from the links

- DuggaSys/courseed.js
**This PR is a documentation of issue** [#17831](https://github.com/HGustavs/LenaSYS/issues/17831).
After some digging, I'm still not sure what's causing the GitHub URL to be undefined or empty nor have I found a solution for this issue.
When testing each function related to the GitHub URL individually, they all appear to work as expected. However, the whole process of updating the GitHub URL doesn't seem to work for some reason. 
##
**Note for when testing:** I filtered the GitHub URL to safely handle double quotes and avoid injecting undefined values into HTML attributes which is why the value is empty instead of "undefined".
**Disclaimer:** Initially intended to attach a recording of the test, but the file exceeded the 10 MB limit.
**Sample test:**
When selecting a course to edit with …
> Investigation of saving modifications of the Github URL of a course

- DuggaSys/microservices/Microservices Documentation/accessedService.md
- DuggaSys/microservices/Microservices Documentation/codeviewerService.md
Added some stuff that was missing, mostly getUid_ms on dependencies. Also removed some empty rows and added output data and format for updateCodeExampleTemplate_ms.php. Fixes issue #18016 .
> Doublechecked Microservices Documentation\accessedService.md and Microservices Documentation\codeviewerService.md

- Shared/css/style.css
Fixed the horizontol scroll that appeared in sectioned while in mobile view.
> G3 Fixed the horizontal scroll in sectioned.

- DuggaSys/courseed.php
- Shared/css/style.css
- Shared/navheader.php
Reverts HGustavs/LenaSYS#18072
> Revert "Fixed styling and logic of burger menu in mobile"
