DuggaSys/codeviewer.php

changed x to px in the loginbox

w14-fix-for-issue #2593

---

DuggaSys/codeviewerService.php

Changed string to match filename

---

.idea/workspace.xml
DuggaSys/showDugga.php

W14 close tag was missing

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Added a button to diagram.php and a function for deleting the last moved object in diagram.js.

Fixed issue #2606

---

DuggaSys/testDugga.php

close head tag was missing in this file

added closing head tag

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Shows the current selected object by painting its borders yellow.

Fixed issue #2624

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Fixed button for hide and show console, also made the canvas area resized when console is hidden/shown, when pressing the button

#2642 : partial done

---

DuggaSys/fileed.js

Fixed some syntax errors. "thead" not closed, removed a few lines. Part
of issue #1867

Fixed syntax in fileed.js

---

DuggaSys/diagram.js
DuggaSys/diagram_example.js

Edited code to make it easier to read, and added accidental removed button in a merge failure

Small-code-fix

---

DuggaSys/resulted.js

Added a missing squarebracket that caused an error. Replaced "start"
with the value 0 in the section that "redraws magic header".

Error fix #2608

---

DuggaSys/diagram.js

added updategfx, so that the display updates when changes are made

added-updategfx-for-button-actions

---

DuggaSys/sectioned.js

A warning icon is now visible in the dugga viewer to warn the user when
he has submitted after the deadline has past.

Warning triangle in the dugga view. Issue #2572

---

lenasys-markdown.txt

Fix for issue #2676. Updated the documentation to match the code in markdown.js and showdoc.php.

Updated lenasys-markdown.txt

---

DuggaSys/accessed.js

Fixed sorting in access view. Also renamed Study program to Class to match column in database.
Closes #2647

Fixed sorting in access view

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

Some functions that generates a JSON string from a form. This is used
in duggaed.php and .js. The functions sets the generated JSON string to
the "param" field. To make it work, the newly created form needed some
redesign aswell.

Javascript logic to extract JSON from the dugga submissions form, and some redesign of said form.

---

DuggaSys/diagram.js

Function was moved from mousemov event, to mousedown event

Fix for Issue #2710

---

DuggaSys/templates/PHP_Ex2.txt
Shared/markdown.js

adding unorderedlist feature to markdown.js. refactoring function parseLineByLine(), bugs regading previous lines and readability

Fix for issue #2635, adding unorderedlist feature to markdown.js

---

DuggaSys/diagram.js

Revert "Fix for Issue #2710"

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Revert "#2706 fixed"

---

DuggaSys/diagram.js

fixed the error occured due to some wierd merging overwriting old pull, added solution to #2706.

#2706-merge-fixed-correctly

---

DuggaSys/diagram.js

Issue #2606 was reverted because of merging issues, and is now implemented again.

Refix for issue #2606

---

DuggaSys/diagram.js

Makes it possible for the user to double click

Fix for issue #2694

---

DuggaSys/diagram.js

Revert "Fix for issue #2694"

---

DuggaSys/diagram.js

Made so that you can move multiple object at the  same time.

#2712 Fixed

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Added the button for opening the dialog menu for appearance. Also added base functionality for this button, like actually opening a window/dialog thats planed to be the menu.

Fix for issue #2732

---

DuggaSys/diagram.js

Changed variable name from ghostingvrosses to ghostingcrosses.

4:Fix for #2709

---

DuggaSys/courseed.js
DuggaSys/courseedservice.php
Shared/css/style.css

Changed color of course links in course editor for courses a user is registered to. If not registered to a course, the link is less opaque. If registered - the link is fully opaque.

Alternative colors for registered students in course view

---

DuggaSys/diagram.js

The function is called upon from other functions that also delete objects.

made a universal deleteobject function

---

Shared/markdown.js

Now the ordered lists in markdown.js working.

Ordered lists in markdown.js are working for issue #2637

---

DuggaSys/courseed.js
DuggaSys/sectioned.js
DuggaSys/sectioned.php
DuggaSys/sectionedservice.php
DuggaSys/showDugga.php
Shared/dugga.js

A field has been added on the Edit Dugga View where teachers are able to
write a comment that will show upp for students when they submit a
dugga.  It uses the column that was created in #2616 for storing the
comment in the database

Added a comment field in Edit Dugga View

---

Shared/dugga.js

Warning icon added in dugga receipt when a user submitts a dugga after
the deadline has past.

Warning in dugga receipt.

---

Shared/dugga.js

Revert "Warning in dugga receipt."

---

DuggaSys/fileed.js

The arrows for showing collapsability are now fixed to be consistent
with "sectioned". Referring to issue #2753

Toggle-function on arrows

---

DuggaSys/diagram.js

Enables the user to double click on the canvas in order to bring up a window.

#2684-fixed

---

DuggaSys/diagram.js

also commentet on the variable ghostingcrosses, on what it does.

4: implemented that a dialogwindow shows up when a enitity is created

---

DuggaSys/diagram_symbol.js

Added code to prevent incorrect sizing for classes

fixed-#2588

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Added textfields in dialog to change name och attributes and entities.

Added textfields in dialog to change name och attributes and entities.

---

DuggaSys/diagram.js

Fix for change name.

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/duggaedservice.php
DuggaSys/showDugga.php

added delete button for dugga in the test view, also closed a head tag in showDugga.php

W14 fix for issue#2605

---

Shared/markdown.js

The bugg for ordered lists is fixed in markdown.js for issue #2754

---

Shared/css/style.css

Added two complementary CSS classes that adds icons.

Fixed arrow icons in the JQuery datepicker

---

Shared/dugga.js

The submission of a dugga is now sensetive to the time of the day and
not only by the date.

Fixed submission of dugga.

---

Shared/markdown.js

sublisting unordered lists should now work correctly

fixing issue 2746. sublisting bug for unordered lists in markdown.js

---

DuggaSys/profile.php
DuggaSys/pushnotifications.js
DuggaSys/pushnotifications.php
DuggaSys/pushnotificationsserviceworker.js
Shared/SQL/changes.txt
Shared/SQL/init_db.sql

Save push notification endpoints to database and implement a way to test sending

---

DuggaSys/diagram.js

I have made it possible to get the coordinants and to close the eventlistener.

Part fix for issue #2737

---

Shared/dugga.js

Related to #2572 and #2567. The intended warning icon to be used at dugga viewer will also be implemented at the receipt when submitting a dugga after the deadline has passed.

Add warning icon to dugga receipt

---

DuggaSys/codeviewerService.php

Error message is fixed but the switching of templates does not work. This needs to be fixed in a new issue.

Error message fixed in codeviewer.

---

DuggaSys/fileed.js

I reused the basic code from resulted.js for later on sorting functionality in fileed. Since the sorting functionality is not done i choose to not print out the simple icons. Later on the function setupSorting will be excuted onload on body.
In resulted.js the function setup is in start of the file (since that is the correct code standard) but here i selected to have it at the end. I also then choose to name it setupSorting instead. Will it be a problem? I was afraid of collisions with other groups if i put it at the start of file.

Added increment for sorting in fileed.js

---

Shared/SQL/init_db.sql

Both folders should now be the same.

Copied install/SQL to shared/SQL - init_db was not up to date.

---

Shared/dugga.js
Shared/loginbox.php
Shared/resetpw.php
Shared/sessions.php

Fixed so that the enter key works as intended even when using the forgot password screen. Also implemented a way to check if the answer to the security question is correct

Solves issues #2763 and #2731

---

Shared/css/style.css

The tables in the file-upload page are now styled to be keep consistency
with the duggas in "sectioned", with the same colors on the tablerows.
Also fixed some indentation. Part of issue #2434

Styling in file-upload

---

Shared/dugga.js
Shared/loginbox.php

Fixes so that the input fields in forgot password turns red if wrong input is sent in, and gives a good error message for if the answer is wrong. However the error message for checking the username is wrong, not done and non descriptive

Partly solves #2815

---

DuggaSys/fileed.js

Input button for add file said 'add link'. Changed to 'Add File' of the 2 input buttons value. This reference issue #2788.

Changed value of input button

---

DuggaSys/diagram.js

You are now able to move around in the diagram. The problem is that there is an offsett that will be solved in the next fix.

Part-fix for issue #2737

---

DuggaSys/fileed.js
DuggaSys/sectioned.js
DuggaSys/sectioned.php

#2796 added button

---

DuggaSys/diagram.js

Can connect items with lines where connector- top, left, right and bottom are defined. Objects where symbolkind == 2 also work, as they are connected to their center.

Issue#2619

---

DuggaSys/diagram.js

Implemented a dialog window that pops up when new attribute is created.

Fix for issue #2744

---

Shared/css/style.css

The border-radius on duggas is removed. It looked weird with rounded
corners and didn't keep constisency. Solution for issue #2847

Border-radius on duggas

---

DuggaSys/diagram.js

Remove checkboxes and the cancel button due to it being redundant.
Added CSS to better structure the window and make it convenient for the user.

fix-for-issue#2835

---

install/CSS/install_style.css
install/install.php

You will not miss this window....
Also permissions fixed and some clean-up in code.

#1967: Dialog window at start is better.

---

DuggaSys/diagram.js

Dialog is closed when click is done outside the box.

Solved issue #2837.

---

DuggaSys/diagram.js

Revert "Solved issue #2837."

---

DuggaSys/codeviewer.js
DuggaSys/codeviewer.php

The text input field was a replaced with a dropdown list, same as the
one in code example for files.

Fix for issue #1878. Replaced text input with a dropdown lsit

---

Shared/dugga.js

Change feedback when user enters a username that does not exist.

Change the feedback #2815

---

DuggaSys/diagram.js

Removed incorrect code. Remove checkboxes and the cancel button due to it being redundant.
Added CSS to better structure the window and make it convenient for the user.

Fixed-for-issuev.2#2835

---

DuggaSys/diagram.js

If click is done outside dialog, it is closed.

Issue #2837

---

DuggaSys/diagram.js

Implemented a drop down-menu for choosing attribute type.

Fix for issue #2764

---

install/SQL/init_db.sql

Added column for uploaddate in fileLink table

---

DuggaSys/accessed.js
DuggaSys/accessedservice.php

Added a version column to Access Editor.

Current course version

---

DuggaSys/resulted.js

Due to the fact that indentation and formation changes the wholy file these changes will create a conflict during merge. I spoke to the group leader and we decided that only smaller changes should be pulled.

#2859 Smaller code cleanup

---

DuggaSys/fileedservice.php

Filledservice now requests uploaddate from database so that it can be viewed.

Fileedservice now fetches uploaddate from database

---

DuggaSys/fileed.js

Added upload date and time in files table in fileed.js

---

Shared/markdown.js

Now there is no need for an extra break-line in the text-file to make the last line show up.

Fix for issue #2723 break-line bug

---

install/SQL/changes.txt
install/SQL/init_db.sql
install/SQL/testdata.sql

This will later be used to be able to add students to groups for
assigning with duggas and such. Not entirely sure about the constraits
in user_usergroup though. Subject for review.

Changed the database to include two new tables, usergroup and user_usergroup

---

DuggaSys/profile.php
DuggaSys/pushnotifications.js
DuggaSys/pushnotifications.php
install/SQL/changes.txt
install/SQL/init_db.sql

Fixes part of issue #2767 by adding VAPID and client keys using WebPush library

Making notifications work in chrome

---

DuggaSys/diagram.js

can delete object with delete key

---

DuggaSys/diagram.js
DuggaSys/diagram_figure.js

Figures now renders correctly.
Did some clean up of comments and variables related to this function.

fix-for-issue-#2845

---

DuggaSys/diagram.js
DuggaSys/diagram_figure.js

Added the select drop-down menu for creating figures. Also added example values that hasn't been implemented yet.
Separated the function createFigure() to be able to add forms easier.

fix-for-issue-#2901

---

DuggaSys/diagram.js
DuggaSys/diagram_figure.js

Added the shape "square" as a predefined figure.

fix-for-issue-#2903

---

Shared/css/style.css

Now the rows in file-upload have different colors every other row (.list
tbody tr:nth-child(odd). Also fixed indentation, it was all over the
place. Solution for issue #2848

Fixed colors on table-rows

---

DuggaSys/diagram.php

A one line fix, diagram.php loads the updategfx function at body onload

Initially draws the diagram

---

install/install.php

This is a first draft of dialog box at the end. The bash commands will be added to this box. Will do this in a later version.

#1967: Added dialog box at the end of installation.

---

Shared/markdown.js

Fixing break line bug in for issue #2723. Adding nextLine to parse lineByLine() and refactoring broken functions.

Adding nextLine to parse lineByLine() and refactoring broken functions. #2723

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/sectioned.js
Shared/dugga.js

deleted the List button and cleaned the code

Deleting the 'List' button

---

DuggaSys/diagram.js

This pull request solves the problem in i ssue #2735. You are now able to move around in the diagram. 
There are some bugs right now, but these will be solved when the zoom-function is implemented.

Fix for issue #2735

---

Shared/css/style.css

Fixed the CSS so that the pointer shows that it's clickable.

Fix for issue #2905

---

DuggaSys/duggaed.php
Shared/css/style.css

Fixed the lost things from the merge. (Form and JSON string)

Added things lost in merge

---

install/SQL/changes.txt
install/SQL/init_db.sql

To store information about filesize for uploaded files. Fix for issue #2524

Added filesize column to fileLink table

---

DuggaSys/filereceive.php

Filereceive.php now inserts filesize into database when a new file is added.
Partfix for issue #2524

filereceive.php now inserts filesize into database

---

Shared/css/style.css

Fixed the CSS so that the pointer shows that it's clickable.

Fix for issue #2924

---

DuggaSys/duggaed.php

Added so that a scrollbar will appear if needed when adding many submissions in the Edit variant box in the dugga editor.

#2898 - fixed scrollbar

---

DuggaSys/diagram.js

When dialog is up, background is dimmed.

Solved issue #2906, dim outside dialog.

---

Shared/dugga.js

Added a function to reset all login/forgot password forms, the error messages and the red backround after a failed input

Fixed so that forms are reset when you change/exit windows

---

DuggaSys/sectioned.js

A button has been added that links to grouped.php when it is created in issue #2897. The link wont work before grouped.php is merged into G2 but the button will work when it is.

Added a button for grouped.php

---

DuggaSys/fileed.js
DuggaSys/fileedservice.php

Filesize from database is now fetched in fileedservice. Function formatBytes converts the Bytes to ex. The table in file view prints out in human readable format by that function.

Table in file view for teachers listes file size

---

DuggaSys/grouped.js
DuggaSys/grouped.php

This page will allow for group editing. Fun!

Created an empty page grouped.php and a corresponding js script grouped.js

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php
DuggaSys/sectionedservice.php

Before the FAB created a set Section. The user had to click on the cog wheel to change it everytime the FAB was used. Now the Edit Item View appears when FAB is clicked which means that a set Section is not
created everytime. The user has to choose which type of dugga should be created directly after clicking the FAB.

Changed FAB and New Item button in sectioned.php

---

DuggaSys/sectioned.js
Shared/dugga.js

The warning for the dugga view and the dugga submittion is fixed and works as it should. From issue #2918.

Fixed deadline handler for duggor.

---

DuggaSys/sectioned.js

Added CourseID and CourseVersion as parameters on Groups button

Added parameters to grouplink

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

Fix for issue #2899. When enter is pressed in text fields in edit variant in dugga editor now nothing happens.

Enter pressed in text field fixed

---

Shared/navheader.php

The same code appeared twice in navheader.php, removed one of them.

Duplicate code entry removed

---

DuggaSys/diagram.js

Fixed the problem with the empty name field when altering an object.

Fixed issue #2840

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Fix for issue #2836

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Added code to make it possible for users to change color of the text inside an object.

Fix for issue #2741

---

Shared/markdown.js

fixing issue #2972.
Gave code explanatory and more proper comments. Unused variables was removed. Minor bugs are fixed.

fix for issue 2972 - refactoring and updating comments

---

Shared/css/style.css

Added space between logo and the dotted line

Issue_#2932_a15cecal_w15

---

Shared/dugga.js
Shared/resetpw.php
Shared/sessions.php

Since we should not do anything special if a user does not have a security question it just returns an error.

Fixes so that the forgot password box gives more desciptive errors

---

DuggaSys/profile.php

Fixes to the profile page so that it looks good on smaller devices too.
Fixes for issue #2982.

Mobile friendly profile page

---

install/SQL/init_db.sql

added db entries

---

DuggaSys/profile.php
DuggaSys/pushnotifications.php
DuggaSys/pushnotificationsserviceworker.js
Shared/pushnotificationshelper.php
install/SQL/changes.txt
install/SQL/init_db.sql

This pull request will fix issue #2990 and #2991 .
There are two reasons for solving two issues at once. One is because the changes was very interconnected. The other is because the pull request was originally planned for fixing issue #2504 , but that issue has many other required fixes to complete so it was extracted into new issues.
The changes made does not effect general lenasys usage.
The sql code in init_db.sql has been verified to work.

Further enhance and clean up push notification system

---

DuggaSys/diagram_symbol.js

Added a function that let you mark attributes as primary keys.

Added Primary attribute function

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Added code to make it possible for users to change fonts on text inside objects.

Edit font of text in objects (#2598)

---

DuggaSys/diagram.js

Removed a button and it's now possible to use one button to open and close the possibility to move around.

Fix for issue #2912

---

DuggaSys/sectioned.js

The title has been changed on Groups button

Changed title on Groups button

---

DuggaSys/fileed.js

There is now a column for the file extension of a file. This fix also removes the file extension from the file name in the file view. 
This is to allow for sorting of file extensions.
Closes #2884

Added column for file extension in file view

---

DuggaSys/diagram.js

Users can now only choose the style of the text inside an object from a list of predefined values.

Dropdown menu for font styles

---

install/SQL/testdata.sql
install/install.php

Added 15 students and assigned these to courses.
Added 5 teachers and assigned these to courses.
Added 'datorns grunder' as course (empty) for testing.

Added some testdata

---

DuggaSys/courseed.php
DuggaSys/sectioned.php

'Verison' -> 'Version'

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Attribute dialog window now has the same options as the dialog window for entities.

(#3014) Added functionality to attribute dialog window

---

Shared/dugga.js
Shared/sessions.php

However the error message should be changed before the merge into master, the error message now is to descriptive.

Added code to check if user is a superuser or teacher

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

A droplist for selecting backgroundcolor when creating or updating a
dugga (test) is added. The values are generated from the JS-file.
Part of a solution for issue #1937

Droplist for selecting color on test-row

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Adds the possibility to change between strong and weak entity.

fix-for-issue-#2843-&-#2842

---

DuggaSys/templates/PHP_Ex2.txt
Shared/markdown.js

this pull-request partially solves the markup for tables in markdown.js. tables with tables rows and table data are parsed curroectly, however, there is no support for alignment or table-headers, etc. This branch and Issue #1781 should therefore not be closed.

Week15 issue#1781 d15johro a15ramha

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Enables the user to assign the type "derived" to an attribute.

Fixed issue 2720

---

DuggaSys/showdoc.php

Added document name to page title

Informative title

---

install/install.php

minus the password, FOR SECURITY!
If the file "coursesyspw.php" exists.

Fills in current credentials when running the installer,

---

DuggaSys/grouped.js
DuggaSys/grouped.php

Styling has been added for grouped.php. More content will be added in the future.

Created styling for grouped.php

---

Shared/dugga.js

Added an alert and a reload of the page when the user session ends.

Timeout now visible on the screen.

---

DuggaSys/profile.php
DuggaSys/pushnotifications.js
DuggaSys/pushnotifications.php

Adding ability to deregister browser for push notifications

---

install/SQL/testdata.sql

2 more courses added with students and techers.
1 example dugga added to one course. The dugga gives error but this will be solver later. At least it shows up.

Added more testdata

---

DuggaSys/duggaed.js
Shared/css/style.css

The user should now be able to show/hide variants when a dugga is clicked on in the test page.  New variants and deleted variants should now  also cause the the corresponding dugga to give feedback to the user by showing that a variant is added or removed in the table.

#2931 Added functionality to show/hide variants.

---

DuggaSys/duggaed.js
Shared/css/style.css

Reverts #3020. Box shadows added for buttons in css applied to all pages on the site. This needs to be fixed before merge.

Revert "#2931 Added functionality to show/hide variants."

---

DuggaSys/sectioned.js

Added a controll if submitted is not null. Therefore will Webbprogrammering work again.

Made the Webbprogrammering course work again

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

I have now removed all unnecessary loc where we have had console.log() without any purpuses. This fixes issue #3051.

Removed all Console.log - Fix for issue #3051

---

Shared/swimlane.php

There is now a overlay in swimlane.php. It is the same principle as
loginbox.php.

#2451-Overlay

---

DuggaSys/diagram.js

This commit solves issue #3065. Under the canvas you can now see the values of zoom and X + Y coordinates.

Fix for issue #3065

---

DuggaSys/diagram.js

The offset that got wonky is now fixed. This fixes issue #2913

Fix for issue #2913

---

DuggaSys/profile.php

Added a password limit (72 characters) and a message informing the user of this.

Password limit

---

DuggaSys/diagram.js

Removed all redundant buttons on create attribute and create entity, now there is only a OK-button to accept all choices that the user has made.

Fix for issue #3015

---

DuggaSys/duggaed.php

Removed the old version of the submission types field.

Fixes mentioned in #3076

---

DuggaSys/sectioned.js

Deleting 'List' button #3061

---

DuggaSys/groupedservice.php

This page is for now mostly a placeholder, and is intended to supply
information about the groups to the grouped.php page.

Created the groupedservice.php service

---

DuggaSys/fileed.js
DuggaSys/fileed.php
Shared/css/style.css

* Unified table for all files. This includes global, course local and local files. It excludes URL:s.
* jQuery toggle function to enable switch between the table views. 
* Button for switching between separate tables and a unified table.
* Added styling for button to fit the general theme of LenaSYS.
Modified files:
```
fileed.php
fileed.js
style.css
```
This pull request was worked on by:
@a15freku
@a15wilhe
@a15oscwe
This pull request closes issue #3019

Added function to switch between separate tables and one unified table

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Normal attribute now return the state to normal, on entities,

Normal Attribute

---

DuggaSys/sectioned.js

Removed additional cogwheel from Section Editor

---

DuggaSys/groupedservice.php
Shared/dugga.js

Some changes has been made to make the grouped.php show the same as it did before the change from resultedservice.php to groupedservice.php were made.

Made the grouped.php work again after change to groupedservice.php

---

Shared/css/style.css
Shared/dugga.js
Shared/loginbox.php

Styled alert message before session timeout

#2627 Styled alert message before session timeout

---

DuggaSys/diagram.js
DuggaSys/diagram_figure.js

Figures now render in the background.

Fix-for-issue-#3033

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php
DuggaSys/sectionedservice.php
install/SQL/changes.txt
install/SQL/init_db.sql
install/SQL/testdata.sql

Duggas now have the option to either be styled as a dugga or as a
header. When adding or updating a dugga you can select which kind of
styling in a droplist. Solution for issue #3062 and #1937

Duggas as headers

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Attributes can now be marked as multivalued

Fixed MultiValue Attribute

---

install/SQL/changes.txt
install/SQL/init_db.sql
install/SQL/testdata.sql

This will enable groups of users to be connected to listentries, also known as coarse moments. Fun times!

Added a new database relation between usergroups and listentries

---

DuggaSys/profile.php
Shared/dugga.js

The content of the profile.php page is now hidden for guests.

Content hidden for guests.

---

DuggaSys/diagram.js

Draws a grid that is semi-compatible with the camera

Draws grid

---

DuggaSys/diagram.js
Shared/css/style.css

The zoom is now implemented and works very well. Need to fix the double click function, but that's another issue.

Fix for issue #2735 and #2472

---

DuggaSys/diagram.js

Now the user can select the derived type on attributes. But still alot of other errors remains.

Fix-for-issue#3101

---

Shared/css/style.css
Shared/dugga.js
Shared/loginbox.php

If someone want to change the text or design on the last box, feel free to do so.

Displays a message that the user can expect a new password soon

---

DuggaSys/fileed.php

Added search field and button for search function in file view

Added search field and button

---

DuggaSys/templates/PHP_Ex2.txt
Shared/markdown.js

table in markdown.js now got inline-styles.

styling tables in markdown.js

---

install/SQL/changes.txt
install/SQL/init_db.sql

Added a column in the database for group duggas (normal dugga, seminar, group dugga, group seminar) saved as a tinyint.

Added grouptype to init_db.sql

---

Shared/navheader.php
Shared/swimlane.php
install/SQL/testdata.sql

Only working for webbutveckling - programmering. Testdata needs to be standardized and courses needs a start date. Right now swimlane always start at week 1 of the year. Should start at week 1 of course but this doesn't exist.

Swimlane beta 1.0

---

.gitignore
DuggaSys/pushnotifications.js
DuggaSys/pushnotifications.php
README.md
Shared/pushnotificationshelper.php
composer.json

Info and safeguards for installing the push notifications system

---

DuggaSys/fileed.js
DuggaSys/fileed.php

Added function to filter data based on search term

---

DuggaSys/grouped.js
DuggaSys/groupedservice.php

Changed position on Groups and Students on the webiste. Also presents all students that is a member of a group in the course, together with the name of the group.

Changed layout on grouped.php

---

DuggaSys/fileed.js
DuggaSys/fileed.php

Added so that the enter button on the keyboard works for search input
field

Added ENTER-button functionality

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

Changed the style of the buttons in edit variant. Partly solving issue #3130.

Buttons in edit variant

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Fixed the following issues:
-Primary key does not give the underline as it should
-Multivalue does not give the border around
-Changing text scale does not work
-Weak option does not give the border around the entity

Partial fix for issue #3140 v.2

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Added functionality to create Relations.

Issue #3058

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php
DuggaSys/sectionedservice.php
install/SQL/changes.txt
install/SQL/init_db.sql

Empty date field start date will be filled in with the current date, and any empty end date will be the same as start date

Added option to have start date and end date on a version of a course.

---

DuggaSys/duggaed.js

Minor fix for #3104 Arrows have been swapped for a more logical approach.

#3104 Swapped arrows in dugga editor

---

Shared/navheader.php
Shared/swimlane.php

Will now only show duggas for the current version (In swimlane)

Added version

---

DuggaSys/fileed.js
DuggaSys/fileed.php

The "one" view table with all files and the search table now has filtering on keyUp. 
Function keyUpSearch is run onclick on button for switching table view. 
When user hits search the other keyUp functionality is runed. 
You can check out the functionality at my folder.

Added keyUp filtering to fileed

---

README.md

Add https comment to readme about push notifications

---

DuggaSys/sectioned.js
Shared/css/style.css

Rows that act like headers now have a shadow.
Issue #3118

Shadow on rows that are headers

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php
DuggaSys/sectionedservice.php

Grouptype alternative was added when creating or changing a dugga. Now you can seperate regular duggas from groupduggor, seminars and groupseminars.

Added grouptype alternative.

---

DuggaSys/fileed.js
DuggaSys/fileed.php
Shared/css/style.css

"Add link" and "add file" buttons made clearer and easier to identify as
buttons.

Made buttons more buttonlike

---

Shared/navheader.php

#2451 Changed id swimlane

---

DuggaSys/diagram.js
DuggaSys/diagram.php

I've now moved everything out from innerHTML, with the exception of the canvas-element. Because we want the size of the canvas-element to be decided whenever the screen size is changed.

Fix for issue #3095

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Fixes issue #3183 and some bug-fix that doesnt belong to this issue. Everything should work now.

Fix for issue #3183

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php
DuggaSys/sectionedservice.php

To make it easier to understand what the code do

Added comments

---

DuggaSys/codeviewer.js

No the variable have the right declaration and the website is working properly.

Fix for the wrong varible declaration in codeviewer.js

---

DuggaSys/diagram.js

Added a line of code that prevents other elements to inherit the "derived" type.

Fixed issue #3162

---

DuggaSys/fileed.js

For consitens I changed the place of arrow icons as the other tables have and also added the newly added css class fileed-button. All this is added to the search result table. This reference to 2 old close problems. You can check out the result at my folder at the testsite in fileed.

Changed position of arrow icon in fileed for the search table

---

DuggaSys/resulted.js

Add output if filter list is empty

---

DuggaSys/diagram.js

Changes relations size as mirrored.

Issue #3165

---

Shared/swimlane.php
install/SQL/testdata.sql

New design and mouse-over effects on duggas. A red line added in swimlane to show what week you're on right now. (still only works with 'Webbutveckling - datorgrafik' because of no database standard).

Swimlane beta 1.1

---

install/install.php

It is now possible to resize error windows.

Error windows now resizeable.

---

install/SQL/testdata.sql

Added a missing comma in test data.

Added missing comma.

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Do not delete branch
Implements a grid with a minor visual bug related to camera position. Does not yet align object borders to the grid, but this will be implemented at a later stage. 
Gives some objects a standard size for when the user creates an object that has a size that is considered "too small".

Grid and standard size

---

install/SQL/testdata.sql

And changed some test data user names to be less associated with real live entities within the school area.
Oh.. swapped around the order on some of the entries to be more uniform.

Fixed an issue where a "," was lost in translation when resolving conflict..

---

DuggaSys/sectioned.js

Both functions that loads when page loads are now defined in the same block

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

When creating relation, opens appearance dialog.

#issue 3170

---

DuggaSys/diagram.js

Fixed sizing regarding relations. It now mirrors the selected points location.

Fix mirrored sizing regarding relations.

---

DuggaSys/templates/PHP_Ex2.txt
Shared/markdown.js

The issue is solved and the tables should work with the new setup where the second line in the tables determine the alignment of the text in the rows.

Week16 #3126 a15ramha d15johro

---

DuggaSys/showdoc.php

The method doesn’t seem to exist

W17 fix for issue#3198

---

DuggaSys/diagram.js

Now it's possible to assign lines to relations.

Add lines to the relations

---

DuggaSys/diagram.js

Fix issue regarding not getting live update when resizing attributes and entities.

Fix live resize update. Issue #3245

---

DuggaSys/groupedservice.php

Only the duggor that is marked as a group will be displayed in grouped.php

Only gruppduggor/gruppseminarie will be shown in grouped.php

---

Shared/css/style.css
Shared/navheader.php

Added a message informing about cookies. (Fix for issue #2758)

Cookie message

---

DuggaSys/fileed.js

Button for switchContent now dynamically changes text based on whether there is one table or multiple tables in view

Button now dynamically changes text based on view

---

Shared/navheader.php

It is now possible to navigate back the proper way.

Go back works now#3180

---

Shared/css/style.css

Added border-radius to all buttons

---

DuggaSys/resulted.js

This should fix #3246 and remove the bug causing the result editor page being blank for internet explorer users.

Fix incompatiblity in resulted.js for IE

---

Shared/loginprompt.php
Shared/sessions.php

Removed loginprompt.php and added helper function to show the login box

---

Shared/css/style.css
Shared/navheader.php
Shared/swimlane.php

Swimlane is now pop-up over sectioned.

Swimlane Beta 1.2

---

DuggaSys/accessed.js

- Added in returned function: a input field, a button and a table body. 
- Function KeyUpSearch is executed onclick on the button and searches through the tables body. 
- Added function searchKeyPress to press enter for easier search.
You can check out the result at my testfolder.

Added functionality to search in table in accessview

---

DuggaSys/duggaed.js

In Edit variant the submissions types-box is now changed to better work with multiple submissions of the same type. The functionality of creating a JSON-string needs changes. (Partially fixing issue #3029)

Changed design of the "Submission types"-box

---

DuggaSys/templates/PHP_Ex2.txt
Shared/css/markdown.css

adding styles to markdown table

---

DuggaSys/showdoc.php

Added forced download for files ending with .html .js .css
fix for issue #3253

Added forced download

---

DuggaSys/duggaed.js

Now the JSON-string is created properly from the form. (Fix for issue #3029)

Create JSON from form

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Fixes the double click issue. You can now doubleclick on a symbol.

Fix for issue #3228

---

Shared/dugga.js
Shared/loginbox.php

Make chrome and firefox able to remember passwords

---

DuggaSys/resulted.js
DuggaSys/resultedservice.php

* Yellow background on teachers.
* Saves to local storage
* Updates when the filter menu is closed

Filter option for teachers in resulted view.

---

DuggaSys/accessed.js
DuggaSys/courseed.js
DuggaSys/duggaed.js
DuggaSys/fileed.js
DuggaSys/sectioned.js

The under-lay(everythying behind the pop-up window) will now be grey if a pop-up window is shown on the site. The under-lay will also turn back to normal when the pop-up window is closed. (Fix for issue #3152)

Made the background grey if a pop-up window is shown

---

DuggaSys/fileed.js

Added input element with type radios for sorting with pairing labels. Lots of props. And also a onclick function that has not been submitted yet. You can check out the result at my folder at the testsite in fileed. 
Partfix for #3277

Added radios for sorting in fileed

---

Shared/loginbox.php

Moved the button to its own table row

---

Shared/sessions.php

Added a check to see if the user already have requested to change password

---

Shared/css/style.css

Removed the backgroundcolor in body so it became white automatically
then I added grey background in class version in style.css so it got
grey at the bottom.

#3212 Delete backgroundcolor in body

---

DuggaSys/resulted.js

Moved "onlypending" checkbox to the the new menu, still works and uses
local storage, I also and made it match the style of the menu for   a e
s t h e t i c   purposes.

Moved checkbox from sorting to filter

---

Shared/css/style.css

Fixed ugly border-radius

---

DuggaSys/profile.php

The questions are just template and will probably change

Added a form with predefined security questions

---

DuggaSys/diagram.js

Did some clean up of some of the functions that might have something to do with this issue.
(Was going crasy over the code because of the bad formating)
Don't know if it will stay as this, but at least we can try to go after the code standards and keep the indentation?
While i did the clean up I found some missing semi-colons, missing var declaration on local variables and also some performance issues that i fixed.

Partial fix #3268 #3032 [Do NOT close the issue]!

---

DuggaSys/diagram.js

- Deletion of figures now works.
- Moving them does not work.
Maybe we should splitt this issue into two issues? One for deletion and one for moving them. The reason for splitting them is that they are two problems and not one as we thought from the beginning.
If this is done the issue for deleting figures could be closed!

Partial fix for issue #3032

---

Shared/navheader.php

Fixed syntaxerror on all other pages than sectioned.php (because there it worked).

Fixed syntaxerror.

---

DuggaSys/sectioned.js

Buttons now re-arranges synchronized when window size is changed.

Button bar at top of the section editor page now have same style-tags

---

DuggaSys/sectioned.js

Now dropdown menu is to the far left.

Moved position of version dropdown menu in Section editor

---

DuggaSys/diagram.js

Fix issue regarding clear local hash.

Fix clear local hash.

---

Shared/swimlane.php

Courses without parts failed to show duggas correctly. This is now fixed and duggas will be shown without a course part (heading).

Fixed courses with no course parts in swim lane.

---

DuggaSys/sectioned.js

If time is anything else then 00:00:00 the date and time will show but if the time is 00:00:00, then only the date will show.

The duggas only show time if the time is set in Section Editor

---

install/install.php

* Restyled code boxes for the file creations
* Added warning sign to the popups

Autofill root username for database

---

Shared/css/style.css

Small z-index fix to hide the .fab-button

Small z-index fix.

---

DuggaSys/sectioned.js

Added attributes to buttons: new item, files and tests

Added attributes to buttons: new item, files and tests

---

Shared/css/style.css
Shared/navheader.php

The cross is moved inside the swim lane window. Easier to find and looks better.

Better exit button on swim lane.

---

DuggaSys/grouped.js

A button has been created on grouped.php. The button is useless as of now but functionallity will be added later.

Created a button to be able to create a new group

---

DuggaSys/sectioned.js

Changed the value for the button and put it in the same class as the other button for it to have the same styling.

Fix for issue #3378

---

Shared/swimlane.php

When time is 00:00:00 it will not be shown.

Removed 00:00:00 in swim lane

---

Shared/dugga.js

This pull request partially fixes #2946. 
@a15herny is working on the session timeout part of the issue, so don't close it yet.

Reload page after logout instead of returning to courseed

---

DuggaSys/resulted.js

Added a checkbox to select and unselect all duggas in the filter menu.
Solves issue #3366

Added checkbox for filtering duggas in resulted

---

DuggaSys/sectioned.js
Shared/css/style.css

Added a hide-all button for all moments. Changed color and class for the different buttons to submit-button, from the previous submit-button-rounded, for consistency.

Section editor interactivity

---

DuggaSys/grouped.js
DuggaSys/grouped.php

A pop-up window will now appear when 'New Group' is clicked in grouped.php. The point is to be able to create a new group in the database when 'Save' is clicked but that is a later issue.

Created a pop-up window when 'New Group' is clicked

---

DuggaSys/sectioned.js
Shared/css/style.css

* Threshold: 480px wide
* Version (eg. HT15) disappear when window is less than threshold
* Deadline time and date is trunkated (fades away) at threshold
* Course name is ellipsis (... at end) when it dow not fit...

Ellipsis of different kinds in Section Editor

---

DuggaSys/templates/johan.md

adding .md-file for testing purposes. Solving issue #3404

adding .md-file

---

Shared/css/style.css

Extra character, and wrong color.

Errors in css.

---

DuggaSys/diagram.js

The offset is now fixed. This fixes the issue #3281.

Fix for issue #3281

---

DuggaSys/resulted.js

It should now be possible to order resulted both ascending and descending.

Descending order of results now working

---

DuggaSys/diagram.js

Relation symbol is not scalable. Bug regarding resizing and marking figure is present.

Issue # Relation symbol should not be scalable

---

DuggaSys/diagram.js

Removed console messages. Old messages were spamming the console window.

#3407: Removed console messages.

---

Shared/pushnotificationshelper.php

Fix the SQL to properly update the db when sending messages

---

DuggaSys/diagram.js

Done.
Implements a working standard width for all objects within the diagram, except line and figure.

Issue#3206

---

DuggaSys/sectioned.js

Removed a function that didn't do anything.
Solves issue #3417

Removed useless function

---

DuggaSys/showdoc.php
DuggaSys/templates/showdoc-test.md

fixing parsing bugs so that it works correctly aswell as refactoring to match markdown.js

fixing bugs and refactoring showdoc.php

---

Shared/css/style.css

The barely visible border-radius is removed.
Solves issue #3454

Removed border-radius on Lightbox

---

DuggaSys/resulted.js

If anything is selected, it will clear
Else it will fill all

The filter button Select All / None now behaves correct.

---

DuggaSys/accessed.php
DuggaSys/duggaed.js
DuggaSys/fileed.php
DuggaSys/grouped.js
DuggaSys/resulted.js
DuggaSys/stats.php
Shared/css/style.css

Now there is titles for the subpages of the section-editor.

Titles for the subpages of the section-editor. #3007

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

Added a check for submission names and an error message if the same name is used multiple times (the background color changes for the textboxes with the same content too).

Fixes for Edit variant (issue #2956)

---

DuggaSys/resulted.js

When checking och unchecking a moment in resulted all submoments will we checked/unchecked. Solves issue #3433

Toggling moment will toggle all submoments

---

DuggaSys/courseed.js
Shared/css/style.css

The icons will line up when shrinked, and no wrapping will occur on small width screens.

Course Ed now has ellipsis (...) at the end of the headline, and the courses.

---

DuggaSys/duggaed.js

Deleting submissions now work

---

Shared/navheader.php
Shared/swimlane.php

There are now clearer rows in swim lane.

Rows in swim lane

---

Shared/css/style.css

centered the section, now when pressing plus the section appears in the
middle

The Edit section is now centered

---

DuggaSys/sectioned.js
Shared/css/style.css

Moved the "+" button for creating a new list entry in the Section editor to the course name row.

Moved "+" button

---

README.md

Fixes issue #3466
The changes can be previewed at https://github.com/HGustavs/LenaSYS/tree/3466
Make sure to look at the new wiki pages created to, as they are part of this pull request

Add more information for installing LenaSYS

---

DuggaSys/duggaed.js
Shared/dugga.js
Shared/loginbox.php
Shared/loginlogout.php
Shared/resetpw.php
Shared/sessions.php

Comments have been changed, deleted and added in some files to better work with the content and to better keep the style of the code.
Related to issue #3278 + a few extra fixes.

Comments fixed/changed

---

DuggaSys/duggaed.js

If everything looks good (not the same name multiple times) in the form, a JSON string is created when the Save button is pressed. (No need to press the Create JSON-button). Fix for issue #3438.

Creates JSON from form when Save button is pressed

---

Shared/css/style.css

Removed the blue border that shows up when you click the add dugga-button.

Fix for issue #3445

---

Shared/swimlane.php

Week text and duggatitles changed to bold. Better visibility. Solves issue #3487

Made important text bold.

---

DuggaSys/sectioned.php

The popup box was not showing the full window. Was moved. Fix for issue #3482

New item window position fixed.

---

DuggaSys/sectioned.js

Show/hide button had disappeared somehow but is now back.

Added show/hide all button again

---

DuggaSys/sectioned.js

'New Item' Shows up when hovering over both add-buttons now. Fix for issue #3493

Round add button in sectioned now has a title

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Fixed the delete function, and removes all the relevant X's for issue #2813

Issue#2813

---

DuggaSys/diagram.js

Waldo is not a point on th diagram anymore, but an empty string, causing the points to disappear completely.

Fix for issue #3462

---

DuggaSys/showdoc.php

The ordered lists are working in showdown.php #3189

Week18 #3189 a15ramha d15johro

---

DuggaSys/showDuggaservice.php
install/SQL/changes.txt
install/SQL/init_db.sql

The number of submissions a user does on each dugga is now recorded in the database table "userAnswer".

Count the number of dugga submissions. (#2282)

---

DuggaSys/resulted.js

Swapped arrows when sorting ResultEd

---

DuggaSys/grouped.js

The active group is selected in the dropdown

Added dropdown menus for each student and group

---

DuggaSys/sectioned.js

Animations when collapsing sections in sectioned are now working on arrows.  Solves issue #3489

Arrow animation works.

---

DuggaSys/grouped.js
DuggaSys/groupedservice.php

Firstname, lastname and ssn will now be shown instead of userid when mouse hover over usernames in grouped.php.

Changed what is shown when mouse hover over usernames in grouped.php

---

DuggaSys/templates/generic_dugga_file_receive.js
Shared/dugga.js

I have as of now changed the styling on the box, by removing the weird inset shadowing. There has also been a slight shift of elements, added new table header for preview etc. 
The issue is not completely solved, as I am working on a new icon for the preview button, and also a restyling of the file submitting form. Since I dont think I'm gonna be finished with everything before the merge, I am splitting up the issue in smaller parts

Partfix for issue #2429 - restyling of preview list box

---

DuggaSys/grouped.js
DuggaSys/groupedservice.php

This will enable easier recognition of the groups

Made the name available in the dropdowns in the group editor

---

DuggaSys/sectioned.js

Disabled until Hamburger Menu is implemented. /a15eriho

Implemented non stacking buttons in Section Ed

---

DuggaSys/sectioned.js
Shared/css/style.css

It is disabled atm due to usability while the hamburger menu is created.

Implemented the shrinking menu in CSS instead of JavaScript

---

DuggaSys/diagram.js
DuggaSys/diagram_figure.js
DuggaSys/diagram_symbol.js

#3410 - Added comments

---

DuggaSys/sectioned.php

Not showing outside the window. should be in the center.

Edit section box showing correctly

---

DuggaSys/sectioned.js

Added a cursor pointer and moved Show/hide arrow up a little. Waiting for approval from Henrik before closing this issue.

Style fixes Show/hide arrow

---

DuggaSys/diagram.js

Removed the line that adds the hash to the URL.

Fix for issue #3570

---

DuggaSys/sectioned.js

Only moments worked before. Now sections works too.

Text for moments and sections on small screens fixed.

---

DuggaSys/resulted.js

The magic heading know stays visible after clicking it.
Solves issue #2433

Magic heading now stays visible after click

---

DuggaSys/sectioned.php
DuggaSys/showdoc.php
Shared/markdown.js

Now the pixels are right and the all the options should show up.

Week18 #3580 a15ramha d15johro

---

install/md/block.md
install/md/ordered-list.md
install/md/table.md
install/md/unordered-list.md

adding testfiles in install folder

---

DuggaSys/grouped.js

This function is called when the user selects some dropdown list in the
group editor. The function should in the next step make a ajax request
to update the database with the values.

Created parameters for the changegroup() function

---

Shared/loginbox.php

Added for attr to the label "Rememeber me" for faster click in the loginbox that references the input tag for remembering the user.
This solves issue #3581 .
You can checkout the result at my testfolder.

Added for attr to label to loginbox

---

DuggaSys/diagram.js

Sort all connectors related to entity dynamic.

#3607 - Sort connectors

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Issue#3498

---

DuggaSys/sectioned.js
Shared/css/style.css

It is deactivated though, and will be activated once this issue, and the issue with disappearing buttons, has both been merged.

Hamburger menu in Section Ed is now completed

---

DuggaSys/duggaed.js

Unnecessary labels for entries removed. This is a remake of the pull request that was removed due to merge yesterday.

Removed duplicatelabels for entries, fix for issue #3529 

---

DuggaSys/sectioned.js
Shared/css/style.css

is now activated in section editor.

Buttons-be-gone

---

DuggaSys/showdoc.php
Shared/markdown.js

Now tables are working properly in showdoc.php.

Showdoc now supports tables.

---

DuggaSys/diagram.js

Loops through localstorage and removes all localdiagram

Remove hashed diagram changes

---

DuggaSys/codeviewer.js

Fix for the issue causing errors when using '.

Fix for issue #2100

---

DuggaSys/grouped.js
DuggaSys/grouped.php
Shared/css/style.css

Styling of the groups page

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Solved problem regarding sizing all entities except relations. All other points, including figure, can be moved.

Solved issue #3623 - Sizing of entities.

---

Shared/css/style.css

Fixed the styling for the search input field.

Fix for issue #3609

---

Shared/css/style.css

3427 changed opacity overlay

---

DuggaSys/showdoc.php
DuggaSys/templates/PHP_Ex2.txt
Shared/basic.php
Shared/markdown.js
install/md/parsing.md

fixing bug for issue #3650 as well som refactoring and implementing a shared debug function in Shared/basic.php

Week19 #3650 d15johro a15ramha

---

DuggaSys/profile.js
DuggaSys/profile.php
DuggaSys/profileservice.php

Issue #3382. Functionality for the password form has been added. It now validates the entered input and also has functionality to update the password in the database.

Added functionality to change password

---

DuggaSys/diagram.js

The fixes that have been implemented makes it possible to zoom and move one time. But when you want to move when zoomed in, the offset doesn't work as it should. I'm leaving this issue for a later date.

Can't resolve this issue

---

DuggaSys/sectioned.js
Shared/css/style.css

Now using css when hiding date and course version

---

DuggaSys/showdoc.php
Shared/markdown.js

Now there is no need for spaces like | Head1 | this |Head1| can be used too.

White spaces are not needed anymore between pipes.

---

DuggaSys/sectioned.js

Was a remainer from testing stuff out.

ellipseBox was never used in original implementation

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_IOHandler.js
DuggaSys/diagram_example.js
DuggaSys/diagram_figure.js
DuggaSys/diagram_mouse.js
DuggaSys/diagram_symbol.js

I've split up diagram.js and added some comments so that we can understand the files more.

Fix for issue #3350

---

DuggaSys/courseed.js
DuggaSys/sectioned.php

i hope the dialog is now centered.

title + edit dialog positioning

---

DuggaSys/profile.js
DuggaSys/profile.php
Shared/dugga.js

Added functionality which checks if the browser is using a HTTPS connection to LenaSYS. If that's not the case, the password form at the profile page will be hidden. This adds extra security for password management.
Issue #3383.

Password management now only works on HTTPS connections

---

Shared/css/style.css

Remove empty classes and broken attributes

---

DuggaSys/resulted.js
DuggaSys/resultedservice.php

The number of times a dugga has been graded is now displayed in the result page. This issue is a continuation of issue #2282.

Time graded is now displayed.

---

DuggaSys/codeviewer.js
DuggaSys/diagram.js
DuggaSys/fileed.js
DuggaSys/resulted.js
LenaSYS.iml
Shared/dugga.js
Shared/navheader.php
install/install.php

Changed switch cases that had too few cases to if-statements and changed ? operator to if-else statements according to Henriks wishes.

Switch cases and ? operator changes

---

Shared/css/style.css
Shared/dugga.js
Shared/loginbox.php

Fixed the design and made it easier to understand how to reset your password. Issue #3521

Redesign of the forgot password boxes

---

DuggaSys/duggaed.js
Shared/css/style.css

Changed (lowered) padding for td, input, label and "buttons" in table in tests (dugggaed) so the height of each row is more compact like other tables.
This is a partfix for issue #3624 .
You can see the changes in my folder.

Changed padding for table contents

---

DuggaSys/resulted.js

The layout is abit smoother, with fixed columns and headers that match.

---

install/CSS/install_style.css
install/install.php

The installer is now cool and this solves issue #3577.

GUI for installer made cooler.

---

Shared/css/style.css

Swimlane is now more responsive and calculate the view & height from the display.

#3703 swimlane -  fix

---

DuggaSys/groupedservice.php

Adjusted a query in the groupedservice that used a database table that does not exist anymore

---

DuggaSys/codeviewer.js
install/SQL/changes.txt
install/SQL/testdata.sql

Codeexample now uses the current courseversion for the course webbprogrammering
Added the changes to changes.txt
Closes #3233

Updated testlink and updated course version for testdata

---

DuggaSys/sectioned.js
Shared/css/style.css

Made the decision to remove the fab since it was unnecessary.

New fix for issue #3576

---

DuggaSys/diagram.php
DuggaSys/diagram_symbol.js

Commented out class button, as it's not needed at the moment.

#3710 - Commented out class button.

---

DuggaSys/grouped.js

Backgroundcolor will be changed when "Studenter" is clicked in grouped.php. ASC and DESC icons will also be shown as they should on "Studenter".

Backgroundcolor and icons are shown on "Studenter" in grouped.php

---

install/CSS/install_style.css
install/install.php

If there was an error that exits installation a button will appear that takes you back to installation start.

Try again button added to installer.

---

DuggaSys/resulted.js

Truncated names of duggas and moments

---

DuggaSys/profile.php
Shared/css/style.css

Added heading in the profile page. Also added css in style.css because it seems to have disappeared in one of the weekly merges. The css was originally added in issue #3007.

Added heading in the profile page.

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_symbol.js
DuggaSys/forms/font_appearance.php
DuggaSys/forms/global_appearance.php
DuggaSys/forms/line-thickness_appearance.php

Adds all the global menus into one, breaks down their functionality to be more consistent. Added a menu for editing global line-thickness #3586

Issue#2473

---

install/CSS/install_style.css
install/install.php

The styles in install.php was removed and moved into the css-file.

All in-line css removed from installer.

---

Shared/css/style.css
Shared/loginbox.php

Pressing enter closed the window and refreshed the site because the use of forms and input fields were wrong. Removed the forms and replaced it with a div. Issue #3677

Pressing enter now works as it should on the forgot password windows

---

DuggaSys/__RemovedStyles__.txt
Shared/css/style.css

Remove unused css

---

DuggaSys/diagram.js
DuggaSys/diagram_example.js

Example objects and points is commented out.

#3713 - Remove example objects

---

DuggaSys/grouped.js
Shared/css/style.css

A button has been added in navheader. If the mouse hover over the button a dropdown will be displayed. Nothing in the dropdown is working at the moment but it will be fixed later in issue #3682.

Added a filter button in grouped.php

---

DuggaSys/resulted.js

Filter and sorting in course Programmeringsmetodik

---

DuggaSys/diagram.js
DuggaSys/diagram.php

I've now removed console from the site plus made so that the crosses are not presented. The crosses can be presented if we press the "debug"-button

Fix for issue #3707

---

DuggaSys/grouped.js
Shared/css/style.css

It is now possible to order students by firstname, lastname, username and ssn in grouped.php. This is done by hover on the icon to the right in the navheader. Some styling has also been deleted from style.css that was not supposed to have been added. It was added by mistake when issue #3681 was merged in to this issue.

Made some more sorting changes in grouped.php

---

DuggaSys/profileservice.php

The security question answer is now hashed when saved in the profile page. (#3631)

Hashed security question answer.

---

DuggaSys/accessed.php
DuggaSys/courseed.php
DuggaSys/showDugga.php
DuggaSys/showdoc.php
DuggaSys/testDugga.php
errorpages/403.php
errorpages/404.php

Removed unused $loginvar and loginvar cookie

---

DuggaSys/diagram.js
DuggaSys/diagram_figure.js
DuggaSys/diagram_symbol.js

- Figures can now be selected on their own. Either by draging and selecting all points of the figure or by clicking inside the figure.
- Figures can now be moved on their own.
- Figures can now be reformed/resized. (a single point of a figure is now movable)
- Figures can now be deleted.
NOTE: Inconsistency when selecting figures. Some times it only works if you drag and select all points of the figure, and sometimes it only works if you click inside of the figure. Eg. to remove a figure you have to drag and select all points.
Open a new issue about this!

Fix-For-Issue-#3321-&-#3400-&-#3409

---

DuggaSys/diagram_mouse.js

I removed the wrong things when I resolved a conflict. This is now fixed!

Fix for Pull Request #3761

---

Shared/css/style.css

Now the overlay fills the screen and doesn't stop before end of page

Overlay swimlane in Webbprogrammering

---

DuggaSys/profile.js
DuggaSys/profileservice.php

Issue #3637. Now teachers and superusers cannot change password or security question at the profile site. Also cleaned up the code in profile.js a bit.

Deny teachers and super users for changing credentials

---

DuggaSys/fileed.js
DuggaSys/fileed.php

Changed header when adding new file/link

---

install/CSS/install_style.css
install/install.php

There is a progress bar added to show installation progress.

Added progress bar.

---

DuggaSys/fileed.js

Refreshing page when deleting a file or url, which fixed the problem.

Now deleting last file/url in file editor

---

Shared/basic.php

issue #3800 
adding function debug_to_console

adding function debug_to_console

---

Shared/css/style.css

How to test this:
Go to webbprogrammering-->PHP example 1-->Cog wheel
Issue: #3790 
This is wrong:

Float removed to fix the misalignment

---

DuggaSys/filereceive.php
DuggaSys/filereceive_dugga.php

Added uploading of .sr files. Commented out some printing of array in fileupload.php. Switched to new style of upload filtering in filereceive_dugga.php. Copied upload not allowed error message from fileupload.php to fileupload_dugga.php.

#3384 filereceive and filereceive_dugga

---

DuggaSys/diagram_mouse.js

Each object has a corresponding dotted line related to its shape.

Issue #3757 - Mode specific drawing tools

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_mouse.js

The zoom recommendation is now fixed. I've also fixed the grid when you zoom in and zoom out.

Fix for issue #3764

---

.gitignore
DuggaSys/profile.php

Questions were too general. More personlized secret questions have been added :)
#3554

#3554 Added secret questions

---

DuggaSys/profileservice.php

$hashedPassword is now using standard password hash function. (#3803)

Using standard password hash function.

---

DuggaSys/diagram.php
DuggaSys/forms/attribute_appearance.php
DuggaSys/forms/class_appearance.php
DuggaSys/forms/entity_appearance.php
DuggaSys/forms/relation_appearance.php

This fixes the issue. The text now updates in realtime.

Fix for issue #3808

---

DuggaSys/diagram_dialog.js
DuggaSys/diagram_mouse.js
DuggaSys/diagram_symbol.js
DuggaSys/forms/attribute_appearance.php
DuggaSys/forms/entity_appearance.php
DuggaSys/forms/relation_appearance.php

Fixed drop down option for background color for symbols (relation, attribute and entity).

Fix for issue #3774

---

DuggaSys/fileed.js
DuggaSys/sectioned.js

Added a few comments

---

DuggaSys/forms/global_appearance.php

Fix for issue #3829

---

DuggaSys/grouped.js

A funnel icon has been added in the navheader in grouped.php. It has been added because it should be able to only show specific moments in the table. Functionallity will be added later.(Fixes issue #3780)

Added a funnel icon in the navheader of grouped.php

---

DuggaSys/diagram_dialog.js
DuggaSys/diagram_symbol.js
DuggaSys/forms/entity_appearance.php
DuggaSys/forms/line_appearance.php
DuggaSys/forms/relation_appearance.php

Customization for lines (strong/weak) can now be done. There is an issue regarding selecting the line and open the dialog, sometimes it works and sometimes it doesn't.

Issue #3719 - Customization in dialog menu for lines

---

DuggaSys/diagram_symbol.js

Fixed the offset of the lines when the relation is weak.

Issue #3852 - Line offset on weak relation.

---

DuggaSys/diagram.js

Changed default size of objects to match and align to relations.

Issue 3756 - Default size of relationship not even multiple of default size of entity

---

DuggaSys/diagram_symbol.js

Fixed offset to align on weak relation.

Fix for issue #3852 - Line offset on weak relations

---

Shared/sessions.php

Use standard hashing functions

---

install/CSS/install_style.css
install/install.php

Aligned two checkboxes in installer. This solves issue #3854. Also added some media styles for smalles screens.

Checkboxes aligned and some media styles added.

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Fixed the standard sizes of objects.

Fix for issue #3756, standard sizes.

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_IOHandler.js
DuggaSys/diagram_dialog.js
DuggaSys/diagram_example.js
DuggaSys/diagram_figure.js
DuggaSys/diagram_mouse.js
DuggaSys/diagram_new_function_names.txt
DuggaSys/diagram_new_variable_names.txt
DuggaSys/diagram_symbol.js

Fixed alot of function- and varablenames and added correct comments to some of the functions.
I did some cleanup of the code.
None of the issues can be closed! This is just a partial fix.

Partial Fix for #3693 & #3410

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Draws derived objects proprely, and doesn't make the rest of the diagram to become derived.

Issue #3826

---

DuggaSys/diagram.php

The canvas didn't load properley before. Now this should work just fine.

Canvas fix

---

DuggaSys/diagram_mouse.js

No need to select object to move points.

Issue #3874 - Fix for moving points.

---

Shared/css/style.css

Removed a selector and it's styling since its a duplicate. The second one (selector) a few lines down contains more styling and the styling I removed. So this won't interfere what I see. Also let's hope no other group won't style in this selector. This styling is for duggaed (tests) table.

Removed duplicate selector and styling

---

DuggaSys/sectioned.js
Shared/css/style.css

Now the course name doesn't overlap the Show/hide all-button in Section Editor.

No more overlap in mobile view

---

install/install.php

It is now possible to resize the window during/after installation and it will properly scale the progress bar relatively. Fix for issue #3847

Window resize scales progress bar.

---

DuggaSys/diagram_dialog.js
DuggaSys/diagram_mouse.js
Shared/css/style.css

I've now fixed so that when you doubleclick on a symbol, it will load the current data from the array into the forms. I've also added some padding to the Name-box. 
NOTE: When you doubleclick, the console will say that there is an error. But there is no error. This is a bug for a later issue.

Fix for issue #3802

---

DuggaSys/accessed.js
DuggaSys/accessed.php

This fixes #3672 by adding an additional popup that allows for easy input when adding a single user, while still keeping the old popup to import multiple users at the same time.

Easier input for "Create user" window

---

DuggaSys/showdoc.php
Shared/basic.php
install/md/unordered-list.md

showdoc.php supports nesting for unordered and ordered lists. #3059

Week20 #3059 a15ramha d15johro

---

DuggaSys/diagram_dialog.js
DuggaSys/diagram_figure.js
DuggaSys/diagram_mouse.js
DuggaSys/forms/figure_appearance.php

Added dialog menu for figures.

Issue #3877 - Dialog menu for figures

---

DuggaSys/profile.php

Changed the user input from password to text. So the user can see what they are typing. #3633

Changed security answer input type

---

Shared/css/style.css

Solved the problem with overlapping buttons.

Issue #3691 a15cecal w19

---

DuggaSys/diagram.php

On customer's request, the coordinates are placed in the down left corner of the canvas.

Fix for issue #3615

---

install/CSS/install_style.css
install/install.php

The user must enter a value in all text field on current page in installer to proceed. Fix for issue #3892

User have to enter all fields before proceeding.

---

DuggaSys/diagram.php
Shared/css/style.css

Does not fully solve #3743, preliminary push

Application document menu

---

DuggaSys/showdoc.php
Shared/markdown.js

#3913 
regex functions is now considering start of line with the carrot-sign

fixing bug in markdown.js and showdoc.php regex

---

Shared/dugga.js

securityquestion only exist if logged in. closes issue #2975

Cookies won't exist if not logged in

---

DuggaSys/showdoc.php
DuggaSys/templates/PHP_Ex2.txt
Shared/markdown.js

The regex has been modified and the bug should be fixed.

The bug is fixed and the unordered lists should work.

---

DuggaSys/swimlane.js
DuggaSys/swimlane.php
DuggaSys/swimlaneservice.php

Comments and more descriptive variables

---

install/install.php

Javascript error at start of installer removed. Solves issue #3906

Error removed

---

DuggaSys/diagram_mouse.js
DuggaSys/diagram_symbol.js
DuggaSys/forms/line_appearance.php

Enabled a dialogue window that will now appear when line is made and implemented a dashed line called "forced".

Fix for issue #3771

---

DuggaSys/sectioned.js
DuggaSys/sectionedservice.php

Writes out which group a student belongs to for a moment. Fix for #2963.

Writes out group belongings

---

DuggaSys/diagram_figure.js
DuggaSys/diagram_symbol.js
DuggaSys/forms/line_appearance.php

Change name on line types, weak to forced and forced to derived.

Issue #3943 - Change name on line types

---

DuggaSys/diagram.js
DuggaSys/diagram_dialog.js
DuggaSys/diagram_mouse.js

This fixes the error messages that are displayed when you use the global apperance-button.

Fix for issue #3932

---

DuggaSys/resulted.js
Shared/css/style.css

Made every other line a darker color and the others a bit lighter. Related to issue #3845.

Added color on the results page

---

DuggaSys/diagram_mouse.js

Now the grid doesn't get dashed when creating attributes and lines.

Issue #3923 - Fix for dashed grid

---

DuggaSys/sectioned.js

Arrow in Show/hide all is now clickable

---

DuggaSys/sectioned.js
Shared/css/style.css

Version dropdown list is now displayed at the course name instead of the navigation bar. Issue #2951.

Moved and redesigned dropdown for course version

---

install/CSS/install_style.css
install/install.php

Installer will now focus the first empty field on current page. This will make it easier to navigate by keyboard only.

Autofocus on input fields

---

DuggaSys/fileed.js

To two keyUp function that filters tables and hide rows, I added odd even bkgrd coloring in jQuery. 
This solves is #3968.
You can see the result at my folder.

Added odd even bkgrdColor after searching in tables in fileed

---

DuggaSys/diagram.php
DuggaSys/diagram_IOHandler.js

I've part-fixed the issue. You can export both JSON and a picture right now. The thing is that the picture is exported in JPG instead of SVG. See comments in issue #3748 for the reason why.

Part fix for issue #3748

---

DuggaSys/resulted.js

The graphical bug in the result view when hovering a column is now corrected

Fix for graphical bug result view when hovering

---

DuggaSys/profile.js
DuggaSys/profile.php
DuggaSys/profileservice.php

Refractor the profile backend and make the profile.js file simpler

---

Shared/css/style.css

I have removed the background color in the check box that appears
outside of the browser internet explorer in the box edit version and new
version.

#3999 Removed the background color in the checkbox

---

DuggaSys/resulted.js
Shared/css/style.css

Rownumber as well as the student info will stick to the left side of the
screen when scrolling horizontally.

Created Magic Heading for the first 2 columns i the result table

---

Shared/css/style.css
Shared/loginbox.php

The loginbox is now aligned abit better on mobile. 
Issue: #3880

Fix for mobile browsing for loginbox

---

DuggaSys/resulted.js

Fix for for merge fault

---

DuggaSys/groupedservice.php

Groupname will now be sorted in the dropdownlists in grouped.php. (Fixes issue #4008)

Dropdownlists in the table in grouped.php are now sorted by name

---

DuggaSys/groupedservice.php

This should not be possible, as dropdowns are used. A user should only be able to participate in one group per listentry.

Fixed an issue where multiple group assignments for the same user and listentry was inserted to the database

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Implements top, right, bottom and left align, as well as vertical and horizontal align.
These options are added to an additional drop down menu, titled "Align". This is possibly a temporary solution.
Does not work for figures.

Issue #3745

---

Shared/icons/animation.html

Have made a svg picture that I will use for animation. It will rotate
and be smaller then used up in the left corner and will appear when a
page is loaded for a long time.

#1887 Loading icon

---

Shared/loginbox.php

The loginbox was the target this time!

Added some titles to various buttons

---

DuggaSys/diagram.php
Shared/css/style.css

Someone had forgotten some curly brackets in the CSS. This has now been fixed, so it can be merged now.

Fixes the CSS

---

DuggaSys/fileed.js

Before when dblclicking on the thead anywhere else but on the icon the icon did not toggle. 
Now the icon changes when you dblclk anywhere on the thead.
This solve is #4029 
You can see the result at my folder.

Added more specific call on changing icon when collapsing/compressing table in fileed

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_dialog.js

Fixes the error message that was displayed in the console when you pressed the 'Global Appearance'-button. We still have some error messages to fix.

Fix for issue #4042

---

DuggaSys/duggaed.js
Shared/css/style.css

giving odd and even rows in table with id testTable different background colors. removing old css for odd even tablerows. setting thead to table in table rendering.
issue #3624

Week20 #3624 d15johro

---

install/SQL/changes.txt
install/SQL/init_db.sql

Added database table for opponents

---

DuggaSys/sectioned.js

solving issue #1896 
filtering output in list by selected fileextensions

Week21 #1896 d15johro

---

DuggaSys/diagram.js
DuggaSys/diagram_figure.js

Removed code regarding selectedIndex and figures. The problem with a selection appearing after completing figure is now gone.

Issue # 4052 - Selection mode after completing a figure.

---

Shared/css/style.css

In sectioned there was some dropshadow that made some vertical lines in sectioned, they are now removed.

Removed grey vertical lines

---

DuggaSys/sectioned.js

When closing all with the Show Hide All, the rows scaled both height and width. Should only reduce the height.

Same animation for closing/opening the sections/moments

---

DuggaSys/diagram.js
DuggaSys/diagram.php
Shared/css/style.css

I've made it possible to save the state you are at and to return to the previous state. The problem is that it won't redraw the diagram and the points. That is the only thing left in this issue.
I have also made some fixes for the site overall. Some CSS-tricks. 
Issue #3208 will have to be put on hold.

Part-fix for issue #3208

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_mouse.js
Shared/css/style.css

Svg icons in inside icons folder. Svg files for the buttons entity, class, line, relation and move arrows.
Blue color (they're otherwise grey with transparent background) and when selecting them they become orange.

Button Icons & Color Select

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_mouse.js
Shared/css/style.css

Revert "Button Icons & Color Select"

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Distribute support for vertical and horizontal. Also implements a bubble sort function and an objects sort function, for the objects vertical and horizontal positions within an array.
Fixes a small miss where diagram was referred to instead of selected_objects in the implementation for  align support.

Implements issue #4024

---

DuggaSys/sectioned.js

The arrow on the hide/show all does not represent the correct state, this is a bug that has to be fixed in a separate issue.

The hide/show all works

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_mouse.js
Shared/css/style.css
Shared/icons/diagram_create_attribute.svg
Shared/icons/diagram_create_class.svg
Shared/icons/diagram_create_entity.svg
Shared/icons/diagram_create_line.svg
Shared/icons/diagram_create_relation.svg
Shared/icons/diagram_move_arrows.svg

This includes svg files used for the buttons entity, line, relation, attribute and move arrow.
Also contains the blue color that can switch to orange when the button has been selected.
Known problem: Orange color doesn't disappear after one of the buttons functions been used. Frankly, don't have more time to develop on this and this needs to be merged in.

Diagram Svg Buttons & Color

---

DuggaSys/resulted.js

Added code that adds the class "hi" or "lo" to the magic heading rows
creating a "striped" pattern in the table.

Added code to add repective class to magic heading rows.

---

DuggaSys/accessed.js
DuggaSys/accessed.php

Change the search layout in accessed

---

DuggaSys/diagram.js
DuggaSys/diagram_mouse.js
DuggaSys/diagram_symbol.js

When a user now creates one entity, one relation and drags a line between them two arity signs appears close to the entity. These signs moves around with the entity and changes side when the connected line changes side.
Missing functionallity:
- Cant double click the arity signs/letters. Which means that a user cant change the text.

Fix-For-Issue#3793

---

DuggaSys/resulted.js

Created a if statement that creates the rows with their corresponding
class

Changed inline if statement to a standard one

---

Shared/css/style.css

Fixed the ugly styling of the OK-button.

Fix for issue #4091

---

Shared/css/style.css

Revert "Fix for issue #4091"

---

DuggaSys/diagram.php
Shared/css/style.css

Revert "Fix for issue #4083"

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_dialog.js
DuggaSys/diagram_mouse.js
Shared/css/style.css
Shared/icons/diagram_create_attribute.svg
Shared/icons/diagram_create_class.svg
Shared/icons/diagram_create_entity.svg
Shared/icons/diagram_create_line.svg
Shared/icons/diagram_create_relation.svg
Shared/icons/diagram_draw_free.svg
Shared/icons/diagram_draw_square.svg
Shared/icons/diagram_move_arrows.svg

This pull request fixes all three issues. It:
* Matches the appearance of buttons to LenaSYS general theme
* Deselctes a button if the button was selected before
* Adds two new symbols to the toolbox

Fix for issue #4084 + #4085 + #4088

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

The function drawOval is moved to diagram_symbol.js. Also, the standard line thickness of the objects is changed to achieve consistency.

Issue #4110 - Move function drawOval

---

Shared/css/style.css

Now it's aligned to the right. Also added a little margin to the left of the version text. Solves issue #4112

Moved the arrow in version dropdown

---

DuggaSys/sectioned.js

Added Title for Show/hide all

---

install/install.php

Hides checkboxes when testdata isn't checked

---

Shared/css/dugga.css
Shared/dugga.js

As title says, added some styling to the preview table in file upload-dugga. Fix for issue #3603

Added styling to preview table - fix for issue #3603

---

install/install.php

Titles added to all elements in installer.

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

The mockup that was made earlier in issue #4060 have been implemented in code now.

Issue #4060 a15cecal w21

---

Shared/css/style.css

Moved the arrows down to match Show/hide all better

Moved arrowcomp and arrowright down

---

DuggaSys/sectioned.js
Shared/css/style.css

Issue #3889. The dropdown list for versions was moved back to the navigation menu and the relevant buttons has been redesigned. This change adds some more use of icons and will save space.

Redesigned [New version] and [Edit version] buttons

---

DuggaSys/forms/attribute_appearance.php
DuggaSys/forms/entity_appearance.php
DuggaSys/forms/figure_appearance.php
DuggaSys/forms/fillcolor_appearance.php
DuggaSys/forms/fontcolor_appearance.php
DuggaSys/forms/line_appearance.php
DuggaSys/forms/relation_appearance.php
DuggaSys/forms/strokecolor_appearance.php

Background colours is now lighter.

Issue #4123 - Make background colours lighter

---

DuggaSys/templates/generic_dugga_file_receive.js

Fix for issue #4119 . The scrolling only made the design worse, so I removed it and added a min-height to the element instead. Looks way better.

Removed overflow:scroll and set min-height on preview table

---

DuggaSys/grouped.js

Repulling since there were many conflicts. Related to #4106

Fix for 3849

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/sectioned.js
install/SQL/init_db.sql

Fix issue #3465 . Changed so the arrow is inside the div of the name instead of outside.

#3465 - Fix ellipsis on the dug name when the page dispayed in smaller size

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/sectioned.js
install/SQL/init_db.sql

Revert "#3465 - Fix ellipsis on the dug name when the page dispayed in smaller size"

---

DuggaSys/sectioned.js

#3465 - New pull request to add to correct branch (group branch instead of master).

#3465 - Fix so the arrow dosent comes on a new row.

---

DuggaSys/accessed.js

Accessed.js row 272
Added dropdown menu for version field.

fixed issue #4211

---

DuggaSys/resulted.js
DuggaSys/resulted.php

Issue 4176

---

DuggaSys/courseed.js

changed button type to a fab #f16linli

Issue#4171

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/sectioned.js
install/SQL/init_db.sql

#4247 - Fix the issues that were overwritten (Pull request #4235) 

---

DuggaSys/resulted.js
DuggaSys/resultedservice.php

In result view: The date the dugga was submitted is now red if the deadline has been passed

In result view: date is now red if deadline has passed

---

DuggaSys/diagram.js
DuggaSys/diagram_dialog.js
DuggaSys/diagram_mouse.js

Fixed so the user can unselect the button by pressing the button again, and mode is being set to normal.
Reffering to #4249 and #4104

G2 a16rasja 4104

---

DuggaSys/courseed.js
DuggaSys/courseed.php

Issue #4172 
Vet inte varför det står att så många rader har ändrats, har tagit bort rad 375 i .js filen och 102-125 i .php filen.

Removed 'pen icon' and its functionality

---

DuggaSys/diagram.php
DuggaSys/diagram_dialog.js

Added functionality so that the user will be able to press the enter key to apply the changes that have been made to the appearance of an object.

The enter key can now be pressed to apply changed appearance of objects

---

DuggaSys/accessed.js
DuggaSys/accessed.php

issue#4157 magic headers on table made sticky
students:
f16linli
a16hamsa

issue#4157 magic headers fixed in access view

---

DuggaSys/sectioned.js
Shared/css/style.css

Changed the dugga date size from static width to an adaptive width by adding a new css class called ”dateSize”. This class is later used in different media queries in order to be able to change the width of the date size based on the screen size.
Changed the dugga title in order to be able to wrap the text based on screen size and free space. The task was competed by adding ”nowrap” and ”ellipsis”  classes on the titles div tag.
Changed the font size for the course title to be able to adapt based on screen size. This was completed by changing the font size in the different media queries that the ”style” CSS file used.

#4180_ver01

---

DuggaSys/resulted.js

issue #4227
Tror att det löser problemet, lade till en checkbox i vad jag tror är filtermenyn.

added checkbox for mini mode

---

DuggaSys/diagram.js
DuggaSys/diagram_mouse.js

We preserve the uimode state when clicking inside movingaround-state. We block targeting when in movingaround aswell. //b16ponpe & b16petma

G2 b16ponpe 3371 2

---

DuggaSys/fileed.php
Shared/css/style.css

The issue is solved. The search functionality used to have a separate search button, I grouped the button and the input together in a div and made it appear as they are "glued together". The button used to contain the word "Search", now it contains a looking glass.

Switch the search button to a looking glass and attached it to the search input

---

DuggaSys/sectioned.php

Remove comment for deadline.
Co-Authored-By: b16filor <b16filor@users.noreply.github.com>

Fix for issue #4191

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_mouse.js

Icon for movearound is hidden from start. Spacebar activates movearound and icon shows. To not movearound anymore use space or click the icon.
//b16petma and a16adala

G2 b16petma 4265

---

DuggaSys/diagram_figure.js
DuggaSys/diagram_symbol.js

The issue is solved. Now all objects have shadows except lines as requested. 
Save and Restore are changed to make better structure of the code and to erase code without functionality.

G2 a16juleh 3937

---

DuggaSys/sectioned.js
index.php

The header with title of duggas was changed(added classes ellipsis and nowrap in div and removed ellipsis from span) so that  depending on the width of the text and screen nothing overlaps.

fixed 4290

---

DuggaSys/diagram.php
Shared/css/style.css

Moved the export options to a separate dropdown that is activated when hovering the Export link in the File-menu. Used the previous styling to style the new dropdown.

G2-c16linst-3988

---

DuggaSys/duggaed.js

issue #4302 . Remove double alertbox.

#4302 - Removed double alert box when removing dugga in duggaed.

---

DuggaSys/diagram.php
DuggaSys/diagram_toolbox.js
Shared/css/style.css

Added a button for minimizing the toolbar.
You are able to press in the vicinity of the button

G2 - a16rasja and c16carbe - 4280

---

DuggaSys/swimlane.js
DuggaSys/swimlaneservice.php

Fixed so that the grade doesn't get returned by the ajax service, now only a color gets returned. The feedback has also been added to the pop-up of hovering a lamp.

Issue 4298

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

Add textfield and datepicker for additional  deadlines and comments.
Co-Authored-By: a16katba <a16katba@users.noreply.github.com>

Fix for issue #4240

---

DuggaSys/diagram.php
Shared/css/style.css

Made a help option in the toolbar. The help option tells the user what hotkeys there are. Changes have been done to diagram.php and the css to have a simular visual appearance

G2 a16adala 4283

---

DuggaSys/swimlane.js

The pop-up feedback can now contain a total of 400 characters . Also changed the max-width of the pop-up box to 350px.

G1 issue 4298

---

DuggaSys/sectioned.js

This solves issue #4307. The state of the arrows have been fixed by adding functionality for local storage and using ids that are unique for every course. The code related to this functionality have also been better structured by adding new relevant functions.
People who worked on this issue: b16linra, a14oliri.

#4307 - On branch #4181, arrow on collapsed menus are displayed incorrectly

---

DuggaSys/resulted.js

Issue #4147 
Removed extra borders and fixed the sort button showing in the filter menu.

Fixed separating lines

---

DuggaSys/accessed.js
DuggaSys/accessedservice.php

Made it possible to see all courseversions and change between them in access editor.
Co-Authored-By: a16katba <a16katba@users.noreply.github.com>

Fixed issue #4215

---

DuggaSys/resulted.js

Issue #4218 
Added support for the cmd key, the ctrl key seems to always be a right click when using chrome on osx

Added support for the cmd-key so mac users can use this feature

---

DuggaSys/diagram.js
DuggaSys/diagram_figure.js
DuggaSys/diagram_mouse.js
DuggaSys/diagram_symbol.js

I have renamed canvasContext to ctx in all diagramfiles

G2 b16petma 4325 rename

---

DuggaSys/diagram.js

I have refactorized a few functions so that they are easier to read and understand.
Some functions were deleted because they were unnecessary and/or already existed in javascripts core functionality. e.g. sort() instead of the bubbleSort() that some students had written.
Logic in a few functions was re-written to optimize the code and/or minimize LoC impact but still had the exact same functionality.

G2 c16carbe refactorization #4325

---

DuggaSys/diagram.js
DuggaSys/diagram_mouse.js

Renamed startX and startY to sx and sy in all diagram files.

G2 b16ponpe 4325

---

DuggaSys/sectioned.js
DuggaSys/sectionedservice.php

#4353, Removed the function and everything that has to do with .arrowRightMeta and .arrowCompMeta.

Removed function setGlobalArrowWhenSingleMomentIsActivated() 

---

DuggaSys/diagram.js

Changed variable names. I created one figure each and also deleted it.
Issue #4325

Changed variable names endX and endY to ex and ey 

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/sectioned.js
DuggaSys/sectioned.php

#4208 - Fixed the issue when writing headings, sections, etc. that include quotes (") in sectioned and duggaed will make editing of that line impossible.
The task was completed by creating a method that checks if the title input has any invalid characters. If any invalid characters are found then the input row changes color to red, and the submit/save button cant be pressed until all invalid characters are gone.

#4208 - Issue with writing headings etc. that include quotes (")

---

DuggaSys/resulted.js

The issue #4219 as already solved, added a variable so that the time can easily be changed as instructed from gushen

Added a variable to seasier be able to change the timelimit

---

Shared/dugga.js
Shared/loginbox.php

The two bugs should be fixed now

Issue#4336 fixed

---

DuggaSys/swimlane.js

Fixed bug with feedback box in swimlane sometimes flashing and made the box appear on the left if theres not enough space on the right.

G1 issue 4360

---

DuggaSys/accessedservice.php
Shared/basic.php
Shared/dugga.js
Shared/loginbox.php

A barrier has been added to prohibit someone from requesting to many password resets on diffrent user accounts within a 5 min timeframe.
The current limit is set to 5 attempts before the lockout period begins.

A barrier has been added in password reset requests

---

DuggaSys/resulted.js
DuggaSys/resultedservice.php

Issue #4220 
For some reason atom automatically edits alot of whitespace. The changes in the service file is only rows 82-84
Click a grade that is already set to revert it to ungraded

G1 issue 4220

---

DuggaSys/courseed.js

removed the yellow box around the course when the cogwheel has been clicked on the course page.
The actual fix was removing row 115, 116 and 118.
While I was investigating this issue I found the abomination method "returnCourse(data)" where proper indentation was not used, so I lined up the code properly.

removed the yellow box around the course when the cogwheel has been clicked

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

#4358 - The confirm box now only appears when trying to delete something.
People who worked on this issue: @b16linra, @a14oliri.

#4358 - SectionEd: No "Are you sure"-prompt unless you're about to delete something

---

DuggaSys/sectioned.js

#4398 
Fixed the issue where ellipsis was not working correctly on mobile phones.

#4398 - SectionEd: Mobile formatting, ellipsis lost in a merge

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

#4376 - The title in the edit section dialog has been changed to be dynamic, i.e. when adding an item the title says "New item" and when clicking on a cogwheel the title says "Edit item".
People who worked on this issue: b16linra, a14oliri.

#4376 - SectionEd: Dialogue-box title

---

DuggaSys/migration.php
Shared/database.php

#4341  - Parser to parse data from array

#4341 - Added migration functionality with versioning.

---

DuggaSys/sectioned.js

#4417 - Fixed by creating a new function, editSectionDialogTitle(), instead of using an existing function, selectItem(). The issue was probably related to the parameters.
People who worked on this issue: @b16linra, @a14oliri.

#4417 - Pull request #4389 caused some other issues in SectionEd

---

DuggaSys/sectioned.php

#4423 - Fixed the issue by closing a div that did not have an end tag and improved the indentation in the whole file.
People who worked on this issue: @b16linra, @a14oliri.

#4423 - SectionEd - Confirmation dialog when deleting items is hidden

---

DuggaSys/sectioned.js
Shared/css/style.css

#4435 
Made sure that the buttons weren't put into the hamburger-menu to early by declaring new max-widths in the css-file to match the wanted behavior.
Fixed so that the contribution-button gets put in the hamburger-menu by correcting a class-mismatch.

#4435 SectionED: Problems with the dynamic hamburger menu for navigation

---

DuggaSys/fileed.js
DuggaSys/fileed.php

Cleaned up old code in the fileed files. This should be used as a reference for other groups.
This is a partial fix for Issue #4453

Cleaned up fileed.js and fileed.php

---

DuggaSys/fileed.js
DuggaSys/fileed.php
DuggaSys/fileedservice.php
Shared/SortableTableLibrary/sortableTable.js

Cleaned up sortabletable and made the base for the fileed so the other group can have a reference.

cleaned up sortabletable

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

#4453 Just cleaned some stuff.

#4453 Clean up the old table code related to SortableTable

---

DuggaSys/sectioned.js
Shared/css/style.css

Fixed an issue where the settings and delete button in SectionEd were a bit off from their original position.

#4452 - SectionEd: Edit the css to move the buttons further to the left

---

Shared/SortableTableLibrary/sortableTable.js

**Imported the sortable table.**

#4466  Importing sortable-table to G3-V03

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php
Shared/css/style.css

#4457 - Clarification about not being able to use "Test" type when no dugga is present has been implemented.

#4457 - SectionEd: Clarify why "Test" cannot be chosen as a type

---

DuggaSys/duggaed.js
DuggaSys/duggaedservice.php
Shared/SortableTableLibrary/sortableTable.js

#4477 
Modified the table-model to fit the desired structure.
Made sure that names for each column, matched across the 2 files. (Dugged.js and DuggaedService.php)

#4477 DuggaED: Working with implementing the sortable-table. Reinsert all columns

---

DuggaSys/sectioned.js

#4500 - Called validatetype and -name when pressing the add new item button so the error checks goes away.

#4500 - SectionEd: Error color when creating a test does not get reset

---

DuggaSys/fileed.php

I switched the search bar that came with sortabletable to the one we created earlier in the project (with the looking glass). No functionality is added.
This solves issue #4483

G2 c16linst 4483

---

DuggaSys/fileed.js
DuggaSys/fileed.php
DuggaSys/fileedservice.php

Fixed so the markdown button only works for markdown files (.md). Also removed unnecessary code and fixed so the JSON encode works correctly in the fileedservice.php.

Fix for issue 4430

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

#4480 - The title now changes to represent which course the user has opened.
People who worked on the issue: @b16linra, @a14oliri.

#4480 - SectionEd: Page title always showing Section Editor

---

DuggaSys/fileed.js
DuggaSys/showDugga.php
DuggaSys/showDuggaservice.php
DuggaSys/showdoc.php
DuggaSys/templates/clipping_masking_dugga.js
DuggaSys/templates/feedback_dugga.js
DuggaSys/templates/generic_dugga_file_receive.js
DuggaSys/templates/html_css_dugga.js
DuggaSys/templates/html_css_dugga_light.js
DuggaSys/templates/placeholder_dugga.js

Pair programmed with c16matan
Issue #2436 
To test it you need to change permissions via mySQL for the dugga and the course, as there are not templates for the tests in the example data you can not change the visibility in the course/dugga editor, if you try to do this you will remove the test. 
The permission int's is pretty stupidly defined like this:
0 = hidden
1 = public
2 = private (requires login and access to the course)

Working permissions for showdoc and showDugga

---

DuggaSys/fileed.js
DuggaSys/fileed.php
Shared/css/style.css

Added two add-buttons - one to add a link and one to add a file. These are located outside the table, but are working like they did before the sortabletable update. There is one problem though - you can't choose whether you are uploading a global or local file. Maybe this could be added as a new issue?
This solves issue #4486

G2 c16linst 4486

---

DuggaSys/accessed.js
DuggaSys/accessed.php
DuggaSys/accessedservice.php

replaced access table with sortable table

---

DuggaSys/accessed.js
DuggaSys/accessedservice.php

Added column Examiner in access view. Adding correct data instead of "examiner1" is next part of main issue.

Fix for issue #4439

---

DuggaSys/duggaed.js
DuggaSys/duggaedservice.php
Shared/SQL/init_db.sql

Changed variablename inside duggaed.js and duggaedservice.php to match the variablenames inside the database.
Both autograde and gradesystem now show the actual value and not an integer.
#4505

#4505 DuggaEd: Translate data into readable values

---

DuggaSys/preview.php

fixed issue #4535 with text getting out of the textarea

fixed vertical out of textarea

---

DuggaSys/diagram_mouse.js
DuggaSys/diagram_symbol.js

Able to hover a line when you are in snap to grid mode and the line is in vertical mode. 
Added a tolerance check when you use entityhover for a line. 
Solution for issue #4437

G2-b16ponpe-4437

---

DuggaSys/fileed.js
DuggaSys/fileed.php
Shared/SortableTableLibrary/sortableTable.js
Shared/css/style.css

Added the magic header to sortabletable and made it work for fileed. Fixed the styling so that the magic header always follows the size of the table and so the header never disappears. Styled it so the magic header looks exactly like the table header.

G2 a16juleh 4524

---

DuggaSys/diagram.js
DuggaSys/diagram_dialog.js

Added a boolean to for checking if the appearance menu is open or not. 
Also added an if condition when the backspace key is pressed, it now checks so the appearance menu is closed.
This is the solution for issue #4537

G2 a6rasja 4537

---

DuggaSys/accessed.js
DuggaSys/accessedservice.php

Added dropdown in access view called "Examiner". I also made the dropdown functional (#4481).

Fix for issue #4440 and #4481

---

DuggaSys/duggaed.js

#4497 Made a clickable trashcan which is used to delete a dugga. The back-end implementation to delete dugga at the same time from the database was also done.

#4497 DuggaED: Working with implementing the sortable-table. Adding "Delete"-buttons

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/sectioned.js
Shared/SortableTableLibrary/sortableTable.js
Shared/dugga.js

#4568
Added a similar fix as in sectioned.js for the confirmbox.

#4568 - DuggaEd: Change the "Deletion-confirmation"-message 

---

DuggaSys/fileed.js
DuggaSys/fileed.php
Shared/SortableTableLibrary/sortableTable.js

Added the search functionality to sortabletable. This is now used in the search bar in fileed.php. It is now possible to search for anything in the table. 
This is a fix for issue #4251 
PS. also changed the variable name "myTable" to our table name "fileLink". This bothered me. :)

G2 c16linst 4251

---

DuggaSys/fileed.js
DuggaSys/showDugga.php
DuggaSys/showDuggaservice.php
DuggaSys/showdoc.php
DuggaSys/templates/clipping_masking_dugga.js
DuggaSys/templates/feedback_dugga.js
DuggaSys/templates/generic_dugga_file_receive.js
DuggaSys/templates/html_css_dugga.js
DuggaSys/templates/html_css_dugga_light.js
DuggaSys/templates/placeholder_dugga.js

Revert "Working permissions for showdoc and showDugga"

---

DuggaSys/diagram.js

I made a solution for the growing point-array. We reuse indices of the array now.
When we add points we loop over the array and return the index to the first unused index and set that index to the point. If no unused index exists we push the new point to the array and return points.length - 1.

G2-b16petma-4479 housekeeping strategy

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

#4406
Fixed an issue where the "new item" window didn't reset when pressing the ESC button.

#4406 - SectionEd/DuggaEd: Pressing Escape-button does not clear the error

---

DuggaSys/sectioned.js

#4599
Removed so that the delete-button no longer shows when editing since that button is no longer used when editing.

#4599 - SectionEd: Cancel-button changes to a delete-button  

---

Shared/css/style.css

#4593 
Added changes in Shared/style.css with class dateSize so that the whole date will show in SectionEd.

#4593 - SectionEd - Deadline is not completely visible 

---

DuggaSys/sectioned.js
Shared/css/style.css

#4449
Fixed the positioning of the hamburger/menu button when viewing from mobile. Added a new funtionality to the hamburger icons.

#4449 - SectionED: Fix the placement for the hamburger-button in the navigation-menu.

---

DuggaSys/fileed.js
DuggaSys/fileed.php
Shared/SortableTableLibrary/sortableTable.js

When we merged #4583 with the group branch, some issues appeared with updating the search results in the table. The rows that matched the search query was drawn outside of the table (see screenshot below). The problem was that the declaration of the tables had switched places. This is now fixed.

Fix for issue #4251

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

#4569 - Delete deletebutton and set close button.

#4569 - Delete deletebutton and set close button.

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/duggaedservice.php

#4482
**Added a button for adding new duggas.
Made sure that the adding of duggas actually work.**
_(All fields except second and third deadling and the comments needs to be filled. And the styling is not yet done.)_

#4482 DuggaED: Working with implementing the sortable-table. Buttons for adding a dugga

---

DuggaSys/swimlane.js
DuggaSys/swimlane.php
DuggaSys/swimlaneservice.php

Solves issue #4565. Added pie chart in the swim lane view. It still needs to be connected to the database which will be solved in issue #4566.
People who worked on this issue: @b16linra and @d15marwi.

#4565 - SectionEd: Grade overview with Pie Chart, Part 1 (ref #4185)

---

DuggaSys/resulted.js
DuggaSys/resulted.php
DuggaSys/resultedservice.php

Issue #4513 
Added a first version of sortableTable on the result page without any real functionality.
The issue is not finished, there is more work to be done.

G1 issue 4513

---

DuggaSys/diagram_dialog.js
DuggaSys/diagram_symbol.js
DuggaSys/forms/line_appearance.php

When you double click on a line you can now set cardinality for left and right point.
This is a partial soulution for issue #3793

G2 a16rasja and c16carbe 3793

---

DuggaSys/fileed.js
DuggaSys/fileed.php

Cleaned up some dead code, added and fixed comments, moved places of functions (so that they lie in a more reasonable order), and moved up some stray variables that weren't lying in the top of the code.
We also removed the "Switch to One table" button, and the sorting dropdown in the header. There is only one table (hence the removal of the button), and the sorting can be done through clicks in the table header. There is no need for a dropdown.
This solves issue #4638

G2 c16linst a16juleh 4638

---

DuggaSys/sectioned.js
Shared/css/style.css

#4644
Fixed an issue where you could select the "+" character on the FAB button.

#4644 - SectionEd: Markable FAB

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_IOHandler.js

When the import menu item is clicked a dialog pops up that allows you to choose a textfile and import it to the diagram
This is a fix for issue #4637

G2 a16timsc 4637

---

DuggaSys/diagram.js

Fixed hover highlight not working properly by changing some hover functionality code in diagram.js
This is a fix for issue #4669

G2 a16timsc 4669

---

DuggaSys/accessed.js
DuggaSys/fileed.js
DuggaSys/fileed.php
DuggaSys/fileedservice.php

Switched places for the columns editor and delete for better consistency with all tables in LenaSYS. Also removed the headlines for the same reason.  
This solves issue #4649

G2 a16juleh c16linst 4649

---

DuggaSys/accessed.php

Fixed the scrolling with magic header when reducing the size in access the table will  not fall out of place and got rid of the green border.

G1 issue 4682

---

DuggaSys/sectioned.php

#4611-SectionEd: Too many spaces around the variable sectionedPageTitle

---

DuggaSys/courseedservice.php
DuggaSys/duggaedservice.php
DuggaSys/sectioned.js

Also fixed so that you can close the box with the escape key.

#4672 - ReFix the Hamburger-button

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

#4640
Added functionality to the action bubbles.

#4640 - SectionEd: FAB-button functionality

---

DuggaSys/duggaed.php
Shared/css/style.css

#4575 
Decreased the text-boxes width in the edit-box so they would fit better on a smaller screen. Also changed some names from 'First Deadline' to '1st Deadline' so it would fit better.

#4575 - DuggaEd: New/Edit item-windows on Mobile Browsers 

---

DuggaSys/diagram_mouse.js

Added if statements to check if you are able to draw a line. Changed position where you set points just to be sure you start on a valid object and even end on a valid object.
Solution is in #4608

Objects have to be connected to each other

---

DuggaSys/sectioned.js

#4677 
Added the posibility to close the FAB action bubbles when pressing outside the container.

#4677 - SectionEd: Closing the FAB by pressing elsewhere

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/duggaedservice.php

Have made a sure that there is a clickable arrow on the leftside of duggas.
When you click the arrow, a editingview showing the variants of the dugga gets displayed.
**NOTE! The functionallity of the edetingview needs to be further implemented.**
#4507

#4507 DuggaED: Working with implementing the sortable-table. Adding "Arrow-functionality"

---

DuggaSys/sectioned.js

#4698
Added the ability to close the "loginBox" window by clicking outside the target.

#4698 - SectionEd: Closing windows by clicking elsewhere

---

DuggaSys/swimlane.js

#4566
Connected database to piechart on swimlane. Depending on the students grades the pie chart changes now. 
Assignees: @d15marwi, @b16linra

#4566 SectionEd: Grade overview with Pie Chart, Part 2 (ref #4185)

---

DuggaSys/diagram.js

Both the hover functionality and selection of symbols now select the object that's on top in the diagram
This is a fix for issue #4697

G2 a16timsc 4697

---

DuggaSys/sectioned.php

#4661-SectionEd: Incorrect indentations in sectioned.php

---

DuggaSys/diagram_mouse.js
DuggaSys/diagram_symbol.js

I have added check if we already are connected with an entity to attribute.
Made function that checks if we have a point in an entities connectors.
Solution for issue #4695

G2-b16petma-4695

---

DuggaSys/accessed.js

Created a new function for making dropdowns in access editor. #4645

Created new dropdown function

---

DuggaSys/diagram_mouse.js

Added two more statements when mouse is pressed down inside a movable object to check you are not moving a line.
Solution for issue #4567

G2 b16ponpe 4567

---

DuggaSys/diagram_dialog.js
DuggaSys/diagram_symbol.js

You are not able to have a cardinality between attribute and etity anymore.
This is a solution for issue #4718

G2 c16carbe and a16rasja 4718

---

DuggaSys/accessed.js

Fixed so the magic header works when reducing the screensize when scrolling in access view.

G1-issue-4432

---

DuggaSys/fileed.js
DuggaSys/fileed.php
DuggaSys/preview.php
Shared/css/style.css
Shared/markdown.js

All code from preview.php are now in fileed.php. Some changes had to be made to js, css and html to make it work. Also the css have been moved from preview.php to style.css and all js from preview are now in markdown.js

G2 a16adala 4643

---

DuggaSys/duggaed.php

Change the text on the deletion-confirmation window from "Are you sure you want to make this happen?" to "Are you sure you want to delete this item". Also changed some indentation in "Confirm Section Dialog"
#4673

#4673-DuggaEd: Less ambiguous confirmation-message

---

DuggaSys/fileed.js
DuggaSys/fileedservice.php

The issue is fixed but need issue 4643. When the pen-button is pressed the corresponding file mentioned on that row should open by using the right file path. 
This is a fix for #4648

G2-a15setno_and_b16nicbr-4648

---

DuggaSys/diagram.js
DuggaSys/diagram.php

Added a new button to the toolbox and functionality for pressing it. 
This is a soulution for issue #4728

G2 c16carbe and a16rasja 4728

---

DuggaSys/fileed.js
DuggaSys/fileedservice.php

Added a 'kind' column to the table. It converts the integers in the database to strings of text with help of an already existing function "convertFileKind".
This solves issue #4691

G2 c16linst a16juleh 4691

---

DuggaSys/diagram.js
DuggaSys/diagram.php
DuggaSys/diagram_symbol.js

Fixed how the UML object is drawn. It is now drawn correctly.
Also added a variable for fontColor that didn't seem to originally exist.
This is a partial fix for #3739.

G2 c16carbe 3739

---

DuggaSys/diagram_symbol.js

G2 b16andka 4403

---

DuggaSys/diagram_mouse.js

Fixed autoselection for UML diagram.
This is a fix for issue #4749

G2 c16carbe 4749

---

DuggaSys/sectioned.js
DuggaSys/sectioned.php

#4690 
A new item-kind has been added with the name 'Group Activity', right now it has no functionality and I have only added the options which I thought would be needed after I heard HGustavs talk about it, but the values are not saved anywhere at the moment, this has to be fixed.
Also fixed some stuff when hiding and showing buttons and what you can write in each kind-box when creating or editing. Before every type of edit-box was showing for header, but 3 were only actually used.

#4690 - SectionEd: Create new type "Group Activity"

---

DuggaSys/showdoc.php
Shared/navheader.php
install/SQL/testdata.sql

Issues #4683 and #2436 
Working credentials check for showdoc.php. It now checks if the user have permission to the file anywhere in the system, if so , it displays the file. 
The change in showdoc.php is the only file that is needed for the final soulotion, the small changes in the other files are small bug-fixes that needed to be fixed to properly test the new showdoc.php
Pair programmed by me, @c16matan and @b16filor 
🤔

Working permissions for showdoc

---

DuggaSys/sectioned.js

#4703 
Added functionality so that enter-press will execute the same functions as pressing Yes/OK/SUbmit/Whatever. added this for both adding new items, editing items and deleting.

#4703 - SectionEd: Enter-key = Yes/Finalize

---

DuggaSys/accessed.php

Fixed the placement for the search button in access and the bottom border.

Gi-issue-4770

---

DuggaSys/duggaed.js
Shared/dugga.js

#4713 - Sub-Issue: Edit-button functionallity from
Seed the information to the form when pressing cogwheel.

#4713 - Sub-Issue: Edit-button functionallity from

---

DuggaSys/diagram_dialog.js
DuggaSys/forms/class_appearance.php

You are now able to change the name of the UML class and press the ok button to close the class appearance menu.
This is a soulution for issue #4752.

G2 a16rasja 4752

---

DuggaSys/diagram.js
DuggaSys/diagram_mouse.js

Rewritten diagram symbol selection in order to make dotted selector work with ctrl/cmd hotkey
This is a fix for issue #4346

G2 a16timsc #4346

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php

#4714 You can now save the changes made to variants. But you still neded to close the window and reopen it to se the changes which will be fixed in #4732.

#4714 Sub-Issue: Save-button functionallity from #4706

---

DuggaSys/accessed.js

Regarding issue #4503
Clicking the column headers in the Access Editor table will now sort the elements in the column either in ascending or descending order.
Known issues:
* The first click on a column will sometimes not sort correctly, after the second click it will work, however.
* Å, Ä and Ö are treated like A and O respectively - unwanted behaviour?
* Clicking too fast seems to collapse the entire table
* Columns with dropdown menus seems to not be working

#4503 - Column sorting in Access Editor

---

DuggaSys/sectioned.js

#4773 
Added new function on mousedown that checks if the current clicked element is a loginBox or not, saving this value and checking it when clicking outside the loginbox to see if it should be closed or not

#4773 - SectionEd: Pop-up closes when draging & releasing the mouse button (Chrome) 

---

DuggaSys/sectioned.js
DuggaSys/sectionedservice.php

#4737 -  SectionEd: New Item state isn't being registered.
When adding  an Listentry gradesystem and highscoremode were not included.

#4737 - SectionEd: New Item state isn't being registered

---

DuggaSys/sectioned.js

#4795 
Added a whole line of code that I forgot earlier

#4795 - SectionEd: The type "Group Activity" includes fields that are not hidden

---

DuggaSys/accessed.js
DuggaSys/accessedservice.php

Issue #4504 
Use enter to save the input to the database
Last part will be added in issue #4806

Added functionallity to edit username, ssn, firstname and lastname in table

---

DuggaSys/sectioned.js

#1928 - Added gradesystem field on moment

---

DuggaSys/diagram_mouse.js

Fixed bugged selection when pressing objects middle point
This is a fix for issue #4776

G2 a16timsc 4776

---

DuggaSys/accessed.js
DuggaSys/accessed.php

In accessed view: Filtering works.
Co-Authored by: b16filor b16filor@users.noreply.github.com

Fixed issue #4502

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/duggaedservice.php

#4712 - Sub-Issue: Submit-button functionallity from. 
Fix the issue so we can post variants.

#4712 - Sub-Issue: Submit-button functionallity from

---

DuggaSys/diagram.js
DuggaSys/diagram_dialog.js
DuggaSys/forms/class_appearance.php

When you open up the appearance menu for a UML-class object you now get two textareas to write attributes and operations for the class.
This is a soulution for issue #4766

G2 a16rasja 4766

---

DuggaSys/sectioned.js
Shared/css/style.css

#4769
Made it possible to add extra bubbles to the FAB functionality and made the code easier to edit and understand for further development.

#4769 - SectionEd: Reduce and refine the code used for the FAB-button

---

DuggaSys/resulted.js
DuggaSys/resulted.php
DuggaSys/resultedservice.php
Shared/css/style.css

Issue #4513
Used the old implementation of the table to implement sortable table. Most of the old code was placed in comments for now.
Filtering and sorting is not working.

Replaced the table in resulted with sortable table

---

DuggaSys/accessed.js
DuggaSys/accessed.php
DuggaSys/accessedservice.php
DuggaSys/resulted.js
DuggaSys/resulted.php
DuggaSys/resultedservice.php
DuggaSys/showDugga.php
DuggaSys/showdoc.php
DuggaSys/templates/clipping_masking_dugga.js
DuggaSys/templates/html_css_dugga.js
Shared/css/style.css
Shared/dugga.js
Shared/icons/file_download.svg
Shared/loginbox.php
Shared/navheader.php
install/SQL/testdata.sql

G1V04 2018

---

DuggaSys/sectioned.js

#4836 Its now possible to add a message inside the FAB.

#4836 Add message functionallity inside FAB

---

DuggaSys/sectioned.js

#4833 
Added so the tabs-box gets shown when creting and editing message-items, also added so it shows tabs when getting created.

#4833 - SectionEd: Message option doesn't have "tabs" 

---

DuggaSys/accessed.js
DuggaSys/accessedservice.php

issue #4806 
Uses  @b16filor function that came with the merge

Added a dropdown menu for users class in the accesspage

---

errorpages/403.php

Not exactly sure where you get the 403 error(permission denied). But you can view the page directly on errorpages/403.php.

Added the link to the frontpage from errorpages/403.php

---

DuggaSys/sectioned.js

#4828 Change name from message of the day to Message inside sectioned

#4828 Change name from message of the day to Message inside sectioned

---

Shared/css/style.css

Fixed issue #4829 it now works as it should 
To see edited code, see style.css and the pre tag from the class markdownPrev
picture below of how it looks right now

G2-b16nicbr-4829

---

DuggaSys/accessed.js
DuggaSys/accessedservice.php

#4827 
Created coloum in access. 
Assignees: @d15marwi, @b16linra

#4827 Creating a group column in Access (Part 1 of #4169)

---

DuggaSys/diagram.js
DuggaSys/diagram_symbol.js

Bugfixes for issue #4783
Points are removed from entities when lines connected to it are removed. Lines connected to symbols that are removed is removed at the same time as the symbol.

G2-b16petma-4783

---

DuggaSys/duggaed.js
DuggaSys/duggaed.php
DuggaSys/duggaedservice.php

#4715
Disable/enable now works for both edeting and adding variants. The visual aspect however has not been implemented.
Made disabled values turn red

#4715 Sub-Issue: Enable/Disable-button functionallity from #4706

---

DuggaSys/diagram_mouse.js
DuggaSys/diagram_symbol.js

Made the amount of lines between an entity and relation a maximum of 2
This is a fix for issue #4852

G2 a16timsc 4852

---

DuggaSys/accessed.php

Now the solution has  a capsule-shaped border around the search box and  a looking glass icon.

Search button is out of place in access

---

DuggaSys/accessed.js

Fixed the bug mentioned in issue #4844.
Co-Authored by: a16jonis a16jonis@users.noreply.github.com

Fixed duplicate nav buttons bug 

---

DuggaSys/sectioned.js

#4846
Added the possibility to auto scoll to the bottom of the page after a new entry to the list.

#4846 - SectionEd: Creating a new item through the FAB list the entry stays underneath the FAB button

---

DuggaSys/diagram.js
DuggaSys/diagram_mouse.js
DuggaSys/diagram_symbol.js

This pullrequest fixes issue #4841 
It is now possible to draw lines between two UML objects in the diagram.

G2 a16rasja 4841

---

DuggaSys/accessed.js

If the sortableTable sorting "move"-row bug hasn't been fixed one needs to add the line:
**"if(!(typeof tbl.tblbody[rowno] === "object")) continue;"**
on line 320 in Shared/sortableTableLibrary/SortableTable.js in order to test this.
Co-Authored by: b16filor b6filor@users.noreply.github.com

G1 issue 4794

---

Shared/basic.php
errorpages/404.php

The service is logged like this:
"404: pageTried/toBeAccessed"
Some variables logged gain the value "UNK"(unknown) but I dont beleive that matters much.

Added logging to the custom 404 page.

---

DuggaSys/sectioned.js

#4880 
Now always showing all boxes, whether they have any effect on the item or not, both when creating and editing.

#4880 - SectionEd: All options when creating an item should be reverted

---

DuggaSys/diagram.js
DuggaSys/diagram_mouse.js
DuggaSys/diagram_symbol.js

When you draw a line to a relation the line is connected in one of the four edges.
Used the same implementation for relation as for entities concerning connectors but we don't spread the points out they share the same position in relation (symbol).
Solution for issue #4203

G2-b16ponpe-4203

---

DuggaSys/diagram_symbol.js
DuggaSys/forms/attribute_appearance.php

Added partial key with dashed line for attributes
This is a fix for issue #4878

G2 a16timsc 4878

---

DuggaSys/duggaed.js
DuggaSys/duggaedservice.php

#4732 - Fix issue when updating variant.

#4732 - Fix issue when updating variant.

---

DuggaSys/sectioned.js

added the validate type functon in order to error check the edit/new item box

#4842 - SectionEd: Editing a test while no links available
