HGustavs/LenaSYS

- DuggaSys/fileed.js
- Shared/css/style.css
Added functionality to open files by clicking on filenames in table. The filenames will change color when the user hovers over them for clarity. 
This solves issue #4918
> G2 a16juleh c16linst 4918

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- DuggaSys/fileedservice.php
- Shared/css/style.css
Fixed the problem that it wasn't possible to search on the kind column. We also added radio buttons so that the user can choose whether they want to see only global/course local/version local files, links, or both.
This solves issue #4919
> G2 c16linst a16juleh 4919

- DuggaSys/fileed.js
- DuggaSys/fileed.php
When using the radiobuttons to filter the table, only the correct filekinds are shown.
> G2 b16andka 4928

- DuggaSys/duggaed.js
> #4935_Removed error, and fixed naming.

- DuggaSys/fileed.js
- Shared/SortableTableLibrary/sortableTable.js
Moved the rowcounter into SortableTable.js. The variable is set to 0 each time the table is rendered. 
The variable is used and incremented in renderCell().
> Fix for #4746

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
#4840 - a16thegu
Created a validate function and it activates via onclick on the FAB-button (sectioned.js) instead of adding a new item directly. Added a confirm dialog window if no duggas are available under Tests (sectioned.php).
> #4840 - SectionEd: Tests can be created without any links

- DuggaSys/sectioned.js
The save button should only be clicked now when both name and type is valid
> #4929 - SectionEd: Items with invalid names can be created

- DuggaSys/duggaed.js
- DuggaSys/templates/kryss.js
#4933 - Fix preview functionallity. This solves the issue of opening previews of templates for variants. But there is a problem with some of the templates that need to be fixed. All templates are not working properly at the moment.
> #4933 - Fix preview functionality.

- DuggaSys/diagram_mouse.js
Fixed the issue with entities not connecting to attributes when line is drawn from the entity.
Solution for Issue #4754
> G2-b16petma-4754

- DuggaSys/duggaed.js
Fixed the validatedugganame, added the error check and block submit button when invalid characters are present.
> #4612 - DuggaEd: Able to save even though the title has illegal characters

- DuggaSys/duggaed.js
- Shared/SortableTableLibrary/sortableTable.js
#4941 - Fix problem when adding dugga. It was a problem in sortabletable.
> #4941 - Fix problem when adding dugga.

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- DuggaSys/fileedservice.php
The fab button is only shown if the current user has access to save files.
Solution for issue #4961
> G2-b16andka-4961

- DuggaSys/fileed.js
Enter can now be used to login from fileed.php
Solution for issue #4974
> G2-b16andka-4974

- DuggaSys/accessed.js
- DuggaSys/accessedservice.php
Sorting now works in access editor. Sortable tables have two bugs that will be fixed in next big merge. 
Bug one: one of the rows in the table isn't being rendered. 
Bug two: sorting ascending in one column and then clicking on another column will display that it's sorting ascending while it sorts descending.
> Added sorting to access editor

- DuggaSys/courseed.js
- DuggaSys/resulted.js
- Shared/css/style.css
Added cell highlighting on resulted table. Issue #4903
> Added cell highlighting on resulted table

- DuggaSys/fileed.js
The pen-icon exists for all editable files now, or at least for js, html, css and php. A small note is that the pen-icon doesn't work in the current state, it's just a not working button for now!
This is a fix for issue #4936
> G2-c16jonha-4936

- DuggaSys/duggaed.js
#4862 - Added a background color to the table row that is being edited.
People who worked on this issue: @b16linra.
> #4862 - DuggaEd: Mark the selected variant when editing

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
- DuggaSys/duggaedservice.php
- Shared/css/style.css
#4892 
Changed the styling in the variants window. As it is right now, the styling will break if the window is to narrow, but this will probably not be an issue.
People who worked on this issue: @b16karhe and @b16linra.
> #4892 DuggaED: Fix the styling in the variant editor.

- DuggaSys/duggaed.js
#4597 - DuggaEd: Pressing Escape-button does not clear the error.
This was an issue overall in duggaed.
> #4597 - DuggaEd: Pressing Escape-button does not clear the error

- DuggaSys/sectioned.js
#4981 - a16thegu
Added a boolean (nameSet) in the validateName() function to know if the user have changed the name of the section in edit/new mode and then used the existing function changedType() to add all kinds as if-statments to change the "placeholder"/value in the name, depending on which type the user is selecting.
> #4981 - SectionEd: Change default value when creating a new item with add button

- DuggaSys/duggaed.js
**#5007 Made the window close by using a similar function to sectionED.**
_Closing this issue will also close #5008 and #5010 so check those issues as well._
> #5007 DuggaED: Clicking outside the variant editor should close the window.

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_IOHandler.js
- DuggaSys/diagram_mouse.js
Added undo/redo functionality with support for CTRL+Z and CTRL+Y. 
This is a fix for issue #3208
> G2 a16timsc 3208

- DuggaSys/accessed.js
- DuggaSys/accessed.php
#4985 
Added row filtering by searching in the searchbox top right of access editor.
> Added searching in access editor

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- Shared/css/style.css
- Shared/markdown.js
When the pen-icon is clicked and if the file (attached to it) is a php, html, js or css file an editor will open. The editor makes it possible for the user to edit or modify the file. When you open the file the content will load and as the print screen below shows, there is a textarea with the file content. 
---
This is a fix for issue #4949
> G2-a15setno-4949

- DuggaSys/duggaed.js
#5005 Swapped the icon to the markdown pen to make use of similar styles as the file editor.
_Also remove the unnecessary hashtags._
> #5005 DuggaED: An icon that more clearly links to variants.

- DuggaSys/fileed.js
It is now possible to search for the displayed content in size column and get the correct result.
I also removed the search functionality from Counter, Editor and Trashcan column
Solution for #4986
> G2 b16andka 4986

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- Shared/css/style.css
The error-message is now gone. The problem was the id "filecont", I accidentally wrote "filecontent" instead.
This is a fix for #4949
> G2-fix-a15setno-4949

- DuggaSys/diagram.js
- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
Fake points that references the real points coordinates is used for resizing. 
Solution for Issue #4957
> G2-b16petma-4957

- DuggaSys/fileed.php
- Shared/css/style.css
- Shared/icons/insert-photo.svg
- Shared/markdown.js
Fixed issue #4532 and issue #4943 
implemented for issue 4943 more functionalities, this is shown below
and for issue 4532 it now looks like this
> G2-b16nicbr-4943 and 4532

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
#5018 - a16thegu
Removed group related code for new/edit section item dialog window.
> #5018 - SectionEd: Delete group selection option in SectioneEditor

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_symbol.js
You are able to copy objects except lines.
Added a new method and push all targeted objects to a new array when you press ctrl+c.
When you press ctrl+v loop through the new array which contains all targeted objects and copy all points and create new object with the copied points.
There is still an issue when you copy objects with a line, it can't connect to the objects correctly.
There will be a new issue for that.
Solution for issue #4907
> G2-b16ponpe-4907

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
#5004 - Make it posible to generate variant parameter from the json form.
> #5004 - Make it posible to generate variant parameter from the json form.

- DuggaSys/fileed.php
- Shared/css/style.css
- Shared/markdown.js
fixed issue #5031 so that it now takes the styling from markdown.css. Also fixed so that code block now correctlly gets the style from markdown.css and not style.css
> G2-b16nicbr-5031

- DuggaSys/diagram.php
- Shared/css/style.css
Fixed jumping navbar items
This is a fix for issue #4999
> G2 a16timsc 4999

- DuggaSys/fileed.js
- DuggaSys/fileed.php
Implemented column specific searching. It is done by searching with following syntax
COLUMN_NAME::SEARCHTERM
Example: kind::global
Solution for #5003
> G2 b16andka 5003

- DuggaSys/fileed.php
- Shared/css/markdown.css
- Shared/css/style.css
- Shared/markdown.js
fixed issue #5030 so that the header tag gets infront of the text instead of behind it
> G2-b16nicbr-5030

- DuggaSys/sectioned.js
> #4194-Moved the deadline icon.

- DuggaSys/diagram.js
- DuggaSys/diagram_mouse.js
Checks for items inside targetingbox in mousemove aswell. We use a flag as parameter to see if we should target or hover-mark the symbols.
Solution for issue #5036
> G2-b16petma-5036

- DuggaSys/resulted.js
Issue #4899
- The checkbox for show teachers should now work as intended
- Checkboxes for unimplemented filters are disabled.
- Row filtering based on a searchterm should work.
> Added row filter for teachers and searchterm in resulted

- DuggaSys/diagram_symbol.js
Added some if statements to check if text length is bigger than object size. If text size is bigger, we set textAlign to "start" it's because the start text should always be visibly. 
Solution for #4997
> G2-b16ponpe-4997

- DuggaSys/duggaed.js
#5063 Added "float-left" to improve the placment of the "+" button.
> #5063 DuggaED: Placement for the "+" button.

- DuggaSys/diagram.js
- DuggaSys/diagram_mouse.js
We dont set isHovered when we are using the selectionbox.
Solution for issue #5056
> G2-b16petma-5056

- DuggaSys/diagram_mouse.js
Added one line that makes appearance menu movable.
Solution for #5064
> G2-b16ponpe-5064

- DuggaSys/fileed.js
It is now possible to specify multiple columns to search from.
Ex. kind::global && extension::jpg (This will find all global files that has jpg as extension)
> G2 b16andka 5015

- DuggaSys/duggaed.php
- DuggaSys/sectioned.php
- #5068 **_Made use of the allready avalablale styling for the "content" div to fix the padding around the table in duggaED._**
> #5068 DuggaED: Add padding around the table.

- Shared/css/style.css
#5091 
Added the "same" border on the left side to make it look like the borders on the right and the bottom.
> #5091 DuggaEditor: Add line on left side in table.

- DuggaSys/migration.php
> #5099 database table

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- DuggaSys/fileedservice.php
- DuggaSys/filereceive.php
- DuggaSys/filereceive_preview.php
- Shared/css/style.css
- Shared/markdown.js
It is now possible to save the file when it has been edited in the markdownpreview.
The save button will need some style fixing.
> G2 b16andka 4431

- DuggaSys/duggaed.js
#5105
**Made the duggaTable sortable in a similar fashion as the table in fileED.** 
_Some styling might be needed, but a separate issue will be done for that._
> #5105 DuggaED: Sortable table should be sortable

- DuggaSys/duggaed.js
#5019
Changed the icon to a "real" play button and change a comment.
The spacing in the columns change automatically to fit the content.
> #5019 DuggaED: Fixes around the icons in the variant table.

- DuggaSys/accessed.js
- DuggaSys/accessed.php
- DuggaSys/accessedservice.php
#4910 
Now it is possible insert new classes which are not suggested.
These new classes will not be created inside the class-table but added to the user-table.
> Changed the dropdown menu to a datalist.

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- Shared/css/style.css
Changed the radio buttons so that they align vertically on mobile screens and changed the width of the searchbar as well. 
This is a fix for issue #5000
> G2-c16jonha-5000

- DuggaSys/resulted.js
- Shared/SortableTableLibrary/sortableTable.js
Issue #4899 
- Made changes in sortabletable.js in order to fix column filtering for sortable tables. 
- Filter settings are saved in local storage and should be applied when revisiting the table.
- Column filters implemented in resulted.
> Fixed column filtering in sortable table

- DuggaSys/migration.php
- DuggaSys/sectioned.js
#4760 - Migration to remove old groupstable.
> #4760 - Migration to remove old groupstable.

- DuggaSys/courseedservice.php
#5111 -  CourseED: Groups for each course
> #5111 -  CourseED: Groups for each course

- DuggaSys/sectionedservice.php
#5112 - SectionED: Old group related code in sectionedservice
> #5112 - SectionED: Old group related code 

- DuggaSys/sectionedservice.php
#5093 - Changed the error message that is shown in SectionEd when it is not possible to delete an item.
> #5093 - SectionED: SQL pop-up message

- DuggaSys/duggaed.js
#5117
Made the variant table sortable by adding a function for sorting that looks alot like the dugga one.
Co-Authored-By: b16linra <b16linra@users.noreply.github.com>
> #5117 DuggaED: Variants table should be sortable

- DuggaSys/duggaed.js
- DuggaSys/sectioned.js
#5092 - @a16thegu and @a14oliri has worked on this issue.
Added local storage function to remember the scrollbars position on the page. Right now it is functional in section editor och dugga editor with diffrent local storage variables (depending on coursecode), a global solution to this can be difficult because every page need it's own variable to store the scrollbar position in.
> #5092 - SectionED & DuggaED: Scroll-position

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- DuggaSys/filereceive_preview.php
- Shared/css/style.css
A popup window is showed when a file is successfully saved. 
This solves #5116
> G2 b16andka 5116

- DuggaSys/diagram.js
You are now able to move objects with the arrow keys.
This is a soulution for issue #5046
> G2-a16rasja-5046

- Shared/css/style.css
The last edit & delete button couldn't be clicked because the FAB button was in the way.
> #5142 - SectionED: Entry table bottom-margin

- DuggaSys/duggaed.js
**#5148**
_Fixed so that qstart gets sent into addugga._
> #5148 DuggaED: Start date is not registered

- DuggaSys/sectioned.js
#4294 
@a15magkn
Simply deleted two blank lines.
> #4294 Part 3 - Check of code standard in HGustavs/LenaSYS/DuggaSYS/sectioned.js

- DuggaSys/sectioned.js
#4884 
Did not add Long-press, but Hover+quickclick
Added a timer that starts when hovering over the FAB-Button, which at the moment set to 2500ms, and after the time has run, it will check where the mouse is hovering, if it is inside the menu we wont close it, else we will close the menu.
> #4884 - Long press on FAB

- DuggaSys/resulted.js
Issue #5130 
- You can no longer filter the first column.
- Most code from the old filtering is removed.
> Removed checkbox for FnameLnameSSN and old code for filtering

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- DuggaSys/filereceive_preview.php
- Shared/css/style.css
- Shared/markdown.js
It is now possible to save html, js and similiar files. There is still work to do with the styling but will be handled in another issue.
Solution for #5108 and #5116
> G2 b16andka 5108

- DuggaSys/sectioned.js
- Shared/css/style.css
Only the FAB button is visible on mobile version
> #5086 - SectionED: Only a FAB button on mobile version

- DuggaSys/duggaed.php
#4549 - Fixed the zoom level in Chrome by adding a meta tag in DuggaEd.
> #4549 - DuggaEd: Check Mobile browsing

- DuggaSys/sectioned.js
- Shared/css/style.css
#5045 - SectionEd: Timestamp is wrong, shown twice.
> #5045 - SectionEd: Timestamp is wrong, shown twice 

- DuggaSys/contribution.js
- DuggaSys/contribution.php
- DuggaSys/contributionservice.php
#4823 
Added a bar diagram in contribution to show commits, events, comments and lines of code. Also added an infobox when hovering over bars.
> Added bar diagram to contributions

- Shared/SortableTableLibrary/sortableTable.js
To test this you need to add a div with ID="editpopover" in a PHP file with a table, set the 3:d last attribute to the sortableTable object to an empty function that also needs to be defined in the javascript file related to the PHP file.
The SVG's should show up under the table when you click a cell
> Uses correct path to the SVG files

- DuggaSys/courseed.js
The last course is now visible even when there is a motd banner active.
> Fix for MOTD covering last course

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- Shared/css/style.css
Added a touchstart-event and touchend-event on the fab for mobile devices. I had to remove the image in the large fab to make it possible to hold it pressed and not making the "save image"-dialogue popup appear. I replaced the image with a plus sign that I styled in the css file to make it look like the previous image. 
This is a fix for issue #4998
> G2-c16jonha-4998

- DuggaSys/accessed.js
- DuggaSys/accessed.php
- DuggaSys/accessedservice.php
- DuggaSys/contribution.js
- DuggaSys/contribution.php
- DuggaSys/contributionservice.php
- DuggaSys/courseed.js
- DuggaSys/resulted.js
- DuggaSys/resultedservice.php
- Shared/SortableTableLibrary/sortableTable.js
- Shared/css/style.css
> G1 V06 2018

- DuggaSys/diagram.php
Removed shading behind the appearance menu so that it's easier to see whats going on with the object that you are currently changing
This a fix for issue #5087
> G2 a16adala 5087 2

- DuggaSys/contribution.js
#5197
Changed the hover box on the bar diagram to display information about the entire bar instead of the individual parts.
> Changed hover in contribution

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
#4380 
@a15magkn
Created a new FAB-button in the DuggaEd. However since the only functionality required at the moment was to add a new deafault dugga, the FAB only has one single functionality.
> #4380 DuggaEd: Change the button "Add Dugga" to a "+"-button

- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_symbol.js
The size of a UML object is no longer static.
You can now resize a UML object to whatever size you want, with the minimum width and height being the longest operation/attribute-name and the number of operations/attributes.
> G2 c16carbe 5084

- DuggaSys/sectioned.js
- Shared/css/style.css
#4655 
Moved the Edit Version and New Version buttons out of the Hamburger-menu. Also removed the hamburger-separator and everything involved with that since that is no longer used.
> #4655 -  SectionEd: Clarification of the Hamburger-menu

- DuggaSys/duggaed.js
- Shared/css/style.css
#5162 - Changed the table in the variants editor. Column widths have been changed and ellipsis has been added to the Parameter column.
> #5162 - DuggaED: Ellipse long parameters

- DuggaSys/fileed.js
- DuggaSys/fileedservice.php
Column search now works correctly
Solution for #5193
> G2 b16andka 5193

- DuggaSys/diagram.php
- DuggaSys/diagram_mouse.js
Removed the unnecessary choices of zoomvalues. Partial fix for issue #5145
> G2-b16petma-5145

- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
When there is an object on canvas you are not able to invert the object. You can't minimize the object smaller than the original size of the object. Added some if statements to check if you are able to minimize the objects.
> G2-b16ponpe-5082

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
- Shared/css/style.css
**#5123 The styling has been fixed to look somewhat like the mock-up.** 
**_The search functionality needs to be implemented further. This will be done in a separate issue._**
_To work with the search functionality it is needed to write "rowFilter" on ROW 285 in duggaed.js and then look at ROW 163-165 in duggaed.php and ROW 766-773 in duggaed.js_
> #5123 DuggaED: Rework variant view (Mock-up)

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
Objects can now be locked through Edit > Lock/Unlock selected.
It is quite unclear whether an object is locked or not but this will be fixed in a future issue.
This is a fix for issue #3747
> G2 c16carbe 3747

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
#5119 
Added new drop-down boxes to add time when creating/editing versions in SectionEd.
> #5119 -  SectionED: Change the old datepicker to the browsers default

- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
An entity/attribute can no longer be inverted.
An object created in an inverse fashion will no longer get clamped incorrectly and will adhere to whatever size the user created it with.
This is a fix for issue #5239 and issue #5226
> G2 c16carbe 5239

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
#5232 Made it possible to search in the variant editor through:
- **_Removed unused functions._**
- **_Fixed the filter function._**
- **_Made the filter reset when the window is closed and a new one is opened._**
- **_Added some comments._**
> #5232 DuggaED: Implement further the search functionality

- DuggaSys/duggaed.js
- DuggaSys/duggaedservice.php
- Shared/css/style.css
#5214 
@a15magkn
Changed the visibility of certain elements such as the control-table and FAB-button. 
If the logged-in user does not have writeaccess (e.g. is not a teacher) then the these elements should not be visible.
> #5214 DuggaED: Creating tests shouldn't be possible if you don't have access

- DuggaSys/sectioned.js
- Shared/css/style.css
Added a pierchart to the new stasticsitsitics tab. 
People who worked on this issue: @a16thegu & @a14oliri :dollar: :heavy_dollar_sign:
> #5243 - SectionED: Insert the piechart in the new statistics section

- DuggaSys/duggaed.php
> #5248-DuggaED: Add a title

- DuggaSys/fileed.js
- DuggaSys/fileedservice.php
- Shared/SortableTableLibrary/sortableTable.js
- Shared/css/style.css
The code to add a counter column in sortabletable is moved into SortableTable.js. 
A new parameter got added to create a sortabletable which should be true or false depending on if a counter should be visible or not. 
Solution for #5256
> G2 b16andka 5256

- DuggaSys/duggaed.js
#5277 - @a16thegu
Changed 'let' to 'var' on 'let'-declarations.
> #5277 - DuggaED: Change every "let" to "var" 

- DuggaSys/sectioned.js
Changed two lines. :feelsgood:
> #5275 - SectionED: Change every "let" to "var"

- DuggaSys/duggaed.php
- Shared/css/style.css
**#5249 Does not really refer to the issue in hand but this is a fix to the sortable-table errors that occurred during the problem solving.**
_Test the fix by pressing enter around searching to see that no error occur in the log._
> #5249 SPECIAL CASE

- DuggaSys/contribution.js
- DuggaSys/contribution.php
Implemented line diagram for the contribution page. It shows contributions for all weeks or for a specific week. #4824
> Line diagram for contribution page

- DuggaSys/duggaed.js
- DuggaSys/sectioned.js
- Shared/css/style.css
#5287 
@a15magkn
Deleted some line from the style.css and enabled the FAB-button in the SectionEd again
TIP: clear the browser-cache and test thoroughly.
> #5287 SectionED: Fab button is not visible

- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_symbol.js
- DuggaSys/forms/line_appearance.php
You are now able to add cardinality between UML classes.
The dialog menu has been changed so it dynamically changes depending on if it is UML type cardinality or not.
> G2 c16carbe and a16rasja 5284

- DuggaSys/duggaed.js
User is now redirected to sectionEd if they don't have write access
> 5267 - Added a 'changeURL' function if user doesn't have write access

- DuggaSys/resulted.js
Issue #4230 
When minimode is active the cells for each student/moment shows a color based on grade and nothing else.
> Cells now get colors based on grade in minimode

- DuggaSys/duggaed.js
#5286 
@a15magkn
Hid the Searchfield in the DuggaEd, if you are not logged in as a teacher.
> #5286 DuggaED: Hide more content

- DuggaSys/diagram_mouse.js
Checks if we should save the state at mouse-up event or not.
Solution for issue #5291
> G2-b16petma-5291

- DuggaSys/diagram_toolbox.js
- Shared/css/style.css
This solves the problem with the toolbar dissapearing when pressing escape
This is a fix for issue #5312
> G2 a16rasja 5312

- DuggaSys/fileed.php
- Shared/css/markdown.css
- Shared/css/style.css
The styling is changed now, but we kept the windows in the editor because of the shortcut buttons. Also, we added some small changes - like the scroll in the textarea. And the save and close buttons are more consistent with the rest of LenaSYS. You can see the changes below, the layout for the mobile view is also updated!
The regular view
---
This is the layout for the mobile view
---
This is a fix for issue #5210.
> G2-b16nicbr-a15setno-5210

- DuggaSys/fileed.php
- Shared/css/style.css
Fixed issue #5321 it now displays a darker background
> G2-b16nicbr-5321

- DuggaSys/duggaed.php
- Shared/css/style.css
#5334 
@a15magkn
Changed the styling of the searchbar in duggaEd
> #5334 DuggaED: Fix search field 

- DuggaSys/accessed.js
- DuggaSys/resulted.js
- Shared/css/style.css
#5021 
Fixed highlight styling in accessed and resulted. And created css classes for easier changes.
> Fixed highlight styling in accessed and resulted

- DuggaSys/fileed.js
Changed from let to var in fileed.js
This is a fix for issue #5272
> G2 a16adala 5272

- Shared/SortableTableLibrary/sortableTable.js
Switched from let to var in the sortableTable.js
This is a fix for issue #5271
> G2 a16adala 5271

- Shared/css/style.css
fixed issue #5329 it now has a more similar view on the mobile view and the desktop view
Desktop view
Mobile view
> fixed margins of file editors and button margins

- DuggaSys/sectioned.js
#5330 - The scrollToBottom function call has been moved and some comments have been added to clarify code.
> #5330 - SectionED: Small improvement to code when creating new items

- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
It is now possible to resize it down to template-size/2 and default size is the same as before.
Solution for issue #5319
> G2-b16petma-5319

- DuggaSys/sectioned.js
#5288 
Added so that if we don't have any tests, show a gray piechart which shows that you have 100% Not Submitted tests.
> #5288 - SectionED: Need a piechart even if no tests exist

- install/SQL/testdata.sql
Added test data for user submissions to se more submissions on the result page.
#5246
> G1 issue 5246

- DuggaSys/duggaed.js
#5260 Merged because of merge..
**I made sure that the preview function imports the right data. However the actual template files needs a lot of work to function like they should.**
> #5260 DuggaED: Variant preview error [PART 1]

- DuggaSys/resulted.js
Issue #5353 
checkboxes and activation of custom filters such as "show teacher" or "only pending" are now implemented in a uniform way.
localstorage now stores a Json object containing the status of each customfilter instead of the old one.
> Made a uniform way to create custom filters

- DuggaSys/sectioned.js
> Removed contribution button

- DuggaSys/contribution.js
#5340 
>![image](https://user-images.githubusercontent.com/37804205/40177526-23679f44-59df-11e8-9200-3b7ff873bf3b.png)
>The scale of the diagram is incorrect and the lines should scale to the propper values.
To test this issue navigate to a course then change the URL from /DuggaSys/* to /DuggaSys/contribution.php
The line diagram now scales properly which can be seen below, it aslo work reguardless of what week is choosen.
> Fixed scaling on the line diagram in contribution

- DuggaSys/duggaed.js
- DuggaSys/duggaedservice.php
- Shared/dugga.js
- install/SQL/init_db.sql
Issue #4241 
Still saves the first entered deadline as the old format in the database. Now we can start working on the issue to use this new JSON deadline.
> JSON deadline object for database

- DuggaSys/diagram_figure.js
- DuggaSys/diagram_mouse.js
* The dotted line will now show when you are in freedraw mode.
* The distance tolerance has been increased so that you don't have to be as precise when creating the last point in free-draw.
This pullrequest fixes issue #5371
> G2 c16carbe 5371

- DuggaSys/accessed.js
- DuggaSys/accessed.php
#4984 
Removed old filtering (without sortable table) and added new using sortable table.
> Added filtering in access with sortable table

- DuggaSys/resulted.js
#5386 
In the result page searching now correctly searches for matches in the lastname aswell.
> Fixed the sorting to now also apply lastname

- DuggaSys/resulted.js
#5297 
Magic header should now work properly on the resulted page
> Fixed magic header on resulted page

- DuggaSys/resulted.js
Changed the grammar in the error message.
#4932
> Changed the sentence

- DuggaSys/migration.php
> changed version 6 of database to fit our current model.

- DuggaSys/diagram.js
- DuggaSys/diagram_figure.js
- DuggaSys/diagram_symbol.js
When you change line thickness in global appearance it scale to same thickness of all kinds of objects now.
Solution for #5332
> G2-b16ponpe-5332

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
#5392 
@a15magkn
Fixed some indentation errors in sectioned.js and sectioned.php
These changes were made in Atom and this might be a issue between IDEs, since I don't think anyone actually used spaces instead of tabs, so the code should probably be checked in a IDE other than Atom to make sure.
> #5392 SectionED: Fix indentation

- DuggaSys/diagram.js
- DuggaSys/diagram_figure.js
- DuggaSys/diagram_mouse.js
Was a problem with selected_objects array where figues wasen't added.
Solution for issue #5376
> G2-b16petma-5376

- DuggaSys/accessed.js
- DuggaSys/accessedservice.php
#5409 - Implement to add group into accessed.
> #5409 - Implement group relations into accessed.

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
#5398
Made sure that some content will only be visible for users with access
> #5398 - DuggaED: Only people with access should be able to see content

- DuggaSys/resulted.js
> Enabled row numbering

- DuggaSys/duggaed.js
- DuggaSys/duggaedservice.php
#5403
_**Removed unused functionality in duggaedservice.php, moved to functions so that the ones relating to dugga and the ones related to variants are located in proximity to eachother.  Also deleted a forgotten console log.**_
> #5403 DuggaED: Clean up the duggaservice.php file

- DuggaSys/accessedservice.php
- Shared/dugga.js
- Shared/loginbox.php
- Shared/loginlogout.php
#5363 
Before you could ignore the barrier by changing the js code in dugga.js. Moving the barrier to php solved this issue.
> Fixed login barrier security issue

- DuggaSys/duggaed.js
- DuggaSys/duggaedservice.php
#5425 - Added an error message that is shown to the user if it is not possible to delete a quiz/dugga.
> #5425 - DuggaED: Some test don't delete

- DuggaSys/diagram_mouse.js
Checks if the line is drawn to the same object.
Solution for issue #5294
> G2-b16petma-5294

- DuggaSys/accessedservice.php
- Shared/basic.php
- Shared/dugga.js
- Shared/loginbox.php
- Shared/resetpw.php
#5364
Before you could ignore the barrier by changing the js code in dugga.js. Moving the barrier to php solved this issue.
> Fixed security issue with request password

- DuggaSys/diagram.js
- DuggaSys/diagram_figure.js
Added figures to the SVG export
This is a fix for issue #5395
> G2 a16timsc 5395

- DuggaSys/diagram.js
The user is now able to press escape when using the freedrawing tool to cancel the drawing.
This is a solution for issue #5417
> G2 a16rasja 5417

- DuggaSys/diagram.js
The user can press ctrl + a to select all objects in diagram.
This is a solution for issue #5436
> G2 a16rasja 5436

- DuggaSys/fileed.php
- Shared/css/style.css
Fixed issue #5410. Lowered the padding so that the label now doesn´t beakline the label
> G2 b16nicbr 5410

- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_figure.js
- DuggaSys/diagram_symbol.js
- DuggaSys/forms/figure_appearance.php
When appearance menu is open the default colors are now selected correct.
Solution for #5378
> G2-b16ponpe-5378

- DuggaSys/accessedservice.php
- Shared/dugga.js
- Shared/loginbox.php
- Shared/resetpw.php
#5365 
Before you could ignore the barrier by changing the js code in dugga.js. Moving the barrier to php solved this issue. This is the last login page, after clicking forgot password and continue.
> Fixed security issue with request password change

- DuggaSys/migration.php
#5429 - Fix for adding groups when adding a new course.
> #5429 - Groups: When a course is created, all groups for the course are created 

- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
- DuggaSys/forms/text_appearance.php
Added the possibility to add text to the diagram which also gets added to the SVG export
This is a fix for issue #5432
> G2 a16timsc 5432

- DuggaSys/diagram.php
Moved "Change appearance" and "Delete object" to edit dropdown.
Solution for #5447
> G2-b16ponpe-5447

- DuggaSys/diagram.js
- DuggaSys/diagram_figure.js
A rectangle path-object will now maintain its rectangle appearance if a point is dragged around.
This is a fix for issue #5442
> G2 c16carbe 5442

- DuggaSys/accessed.js
#5465 
Added the sort icon in accessed without any function.
> Added sort icon in accessed

- DuggaSys/fileed.php
- Shared/css/style.css
Fixed issue #5459. The selected-header does not display incorretly anymore, it now displays correctly
> G2-b16nicbr-5459

- DuggaSys/diagram.js
- DuggaSys/diagram_symbol.js
Removed "dragging points" for free text
This is a fix for issue #5476
> G2 a16timsc 5476

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
- Shared/css/style.css
**#5464**
Fixed the styling of the variant window.
Removed a problem with that the wrong variant got previewed.
_-- A issue needs to be created to enable the same type of closing mekanisms for the preview window as there are for all the other windows. Meaning that the "closeWindows()" function should be used and it should be possible to close the window by clicking outside of it._
> #5464 DuggaED: Fix the styling on the variant view #5464

- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
- DuggaSys/forms/text_appearance.php
Added multiple lines support for free text
This is a fix for issue #5486
> G2 a16timsc 5486

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- Shared/css/style.css
We changed the width of the icons elements. We also made the table more adaptive to the width of the screen, as well as the table's width. We also aligned the contents of all the table data, except for filename, to the center.
This is a fix for issue #5440
> G2-b16andka-c16jonha-5440

- DuggaSys/sectioned.js
#5073
Fixed the position of +.
>  Misaligned "+" in FAB

- DuggaSys/diagram_symbol.js
Added multiple lines support for free text in SVG
This is a fix for issue #5498
> G2 a16timsc 5498

- DuggaSys/courseedservice.php
- DuggaSys/sectionedservice.php
#5451 - Implement so groups are seeded when visiting sectioned.
> #5451 Groups: Add groups for every course if the groups does not exist 

- DuggaSys/forms/attribute_appearance.php
- DuggaSys/forms/entity_appearance.php
- DuggaSys/forms/figure_appearance.php
- DuggaSys/forms/global_appearance.php
- DuggaSys/forms/relation_appearance.php
- DuggaSys/forms/text_appearance.php
Changed the colors used by diagram objects. 
Solution for #5504
> G2 b16andka 5504

- DuggaSys/sectioned.js
#5435  - @a16thegu
Made changes to the pie chart to suit the new design.
> #5435 - SectionED: Make the piechart bigger

- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_figure.js
- DuggaSys/forms/figure_appearance.php
You are now able to change to opacity of figures. You are also able to set no fill as a fill color.
This is a solution for issue #5373
> G2 a16rasja 5373

- DuggaSys/sectioned.js
#5328
Added a new functionality to the FAB button. Simple click creates a default item, press and hold opens the fab menu.
> #5328 - SectionEd: FAB-button functionality. 

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
**#5493**
_Made sure that all closing of windows in duggaED uses the shared "closeWindows()" function and removing the individual closing functions for the respective windows._
> #5493 DuggaED: Consistent code in variants view #5493

- DuggaSys/sectioned.js
> #5399-SectionED: Error when clicking access

- DuggaSys/diagram.js
When using the free draw tool and changes to the square tool it now cancels the free draw.
This is a solution for issue #5407.
> G2 a16rasja 5407

- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_symbol.js
- DuggaSys/forms/text_appearance.php
Added the ability to change text alignment of free text
This is a fix for issue #5501
> G2 a16timsc 5501

- Shared/css/style.css
Changed the height of the sorting div and the distance to top on the sortingBar and searchBar. I also added a min-width for the table  on smaller screens
This is a fix for issue #5509
> G2-c16jonha-5509

- DuggaSys/accessed.js
- Shared/css/style.css
Changed from swedish to english text in group select box on the access page.
#5355
> Changed language in select box

- Shared/css/style.css
**#5538**
_Made the hamburger menu appear at the right time and fixed some indentation on the surrounding lines._
> #5538 SectionED: Hamburger menu shows before a nav button is hidden

- Shared/SortableTableLibrary/sortableTable.js
- Shared/css/style.css
Issue #5170 
The part of sortableTable that moves the inline editing div now works properly with LenaSYS
To test: 
Add a function to the accessed.js file called "something"
Add this function as a parameter to the sortable table after "rowHighligtOff" in the same file
Edit one of the cells in renderCell to only output the value from the json, and not the entire input string ( like obj.username)
Add a div at the end of accessed.php with id "editpopover"
or
Ask me tomorrow how to test it and i'll help
The styling might not be the most beautiful thing ever seen, but it works 👍
> Move cell editing to proper cell

- DuggaSys/accessed.js
- DuggaSys/accessed.php
- DuggaSys/accessedservice.php
#5134 
Added an error message for the first input thats incorrect and marked all incorrect inputs red.
> Added error messages for creating a class

- DuggaSys/accessed.php
#5095
Now the placement of the searchbar and title follow the same theme of the other pages.
> Accessed - Reposition searchbar & title text

- DuggaSys/duggaed.js
- DuggaSys/duggaedservice.php
Issue #5377 
@b16nilpe knows whats up 
The function for adding 3 deadlines as a json now also works with creating new tests
> Added jsondeadline for the createdugga function

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_toolbox.js
- Shared/css/style.css
- Shared/icons/textbox.svg
I have added a button for writing free text in the diagram.
Solution for issue #5477
> G2-b16petma-5477

- DuggaSys/sectioned.js
#5548 - Fixed arrow state when moving moments by clicking and dragging. The arrows do not use the id counter anymore, but instead use the moment name to get a unique name.
> #5548 - SectionED: Fix an arrow bug

- DuggaSys/sectionedservice.php
#5549
Added the ability to get the start date for each dugga in the returned data.
> #5549 - SectionED: Get start date from the duggaED

- DuggaSys/diagram.php
- Shared/css/style.css
Changed id to class where the id was the same.
also changed the css so it works with the classes.
This is a solution for issue #5528
> G2 a16rasja 5528

- DuggaSys/courseed.js
Moved the cogwheel closer to the text on courseed page.
#5100
> Moved cogwheel closer to the text

- DuggaSys/accessed.php
#5553
Made the wrappall wider and got rid of the border around it and created a margin.
> Accessed - Styling fixes

- DuggaSys/diagram.php
- Shared/css/style.css
Added functionality for undo and redo tooltip.
This is a solution for issue #5527.
> G2 a16rasja 5527

- DuggaSys/accessed.js
- DuggaSys/accessedservice.php
- DuggaSys/sectionedservice.php
#5503 - Take vers in considiration
> #5503 Take vers in consideration.

- DuggaSys/duggaed.php
> #5532-SectionED: Change the search placeholder in variant view 

- Shared/navheader.php
> #5545 - SectionED: Remove the swimlane icon

- DuggaSys/accessed.js
#5523 
Remove an empty line in the class dropdown in accessed.
> Removed empty option in class dropdown access

- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_forms.php
The code for the appearance menu is now modular (for the most part). There is now less redundant code and it is easier to change. If you wanted new colors you would now only have to change it in one place instead.
This is a final fix for #4198
> G2 c16carbe and a16rasja 4198

- DuggaSys/sectioned.js
#5574
Made the statistics text unselectable.
> #5574 - SectionED: Make statistics text unselectable

- DuggaSys/sectioned.js
#5572 - Fix issue for sectioned groups.
> #5572 - Fix issue for sectioned groups.

- DuggaSys/migration.php
- install/SQL/init_db.sql
#5569 - Update infromation in install.sql
> #5569 - Update infromation in install.sql

- Shared/dugga.js
Removed the two else if blocks containing usermanagementviewservice.php, a file which no longer exists.
> Removed usermanagementviewservice.php from code

- Shared/dugga.js
> Revert "Removed usermanagementviewservice.php from code"

- Shared/dugga.js
> Revert "Revert "Removed usermanagementviewservice.php from code""

- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
Added description relating to parameter when creating Symbol, as well as the variable symbolKind.
> Added additional comments regarding symbols#5674

- DuggaSys/contribution.php
Changed noup COURSE to SECTION
> Changed noup COURSE to SECTION in contribution

- DuggaSys/diagram_forms.php
Changed the max value to 2. If it were 5 the lines merges together
> Fixed issue #5525

- DuggaSys/accessed.js
- DuggaSys/accessedservice.php
- Shared/SortableTableLibrary/sortableTable.js
Fix for issue [5152](https://github.com/HGustavs/LenaSYS/issues/5152)
Made rows in accessed for users that requested password reset red
> Rows in accessed table is now red if user requested password reset

- Shared/css/style.css
Fixes issue [5644](https://github.com/HGustavs/LenaSYS/issues/5644)
> Removed dateSize from the media query for small devices

- DuggaSys/sectioned.php
- Shared/css/style.css
- testfiles/OscarsTestFil.php
Changed the opacity to a more satisfying one.
> Grupp b2019 oscar

- DuggaSys/accessedservice.php
This pull request is actually a sub-issue of "Uneconomical use of space in result view" #5625.
This is the isse:
Null value appears in result view #5661
https://github.com/HGustavs/LenaSYS/issues/5661
> Update accessedservice.php #5625

- Shared/navheader.php
This change suppresses alert messages if the user is not logged in and/or is not a superuser
> GruppC: Fix for issue #5691

- DuggaSys/diagram.js
Added spacing between overlapping objects when aligning them.
Fixed for both vertical and horizontal alignment.
> Fix for #5686

- DuggaSys/resulted.js
- DuggaSys/resulted.php
> Revert "Grupp b2019 #5633"

- DuggaSys/diagram.php
- Shared/css/style.css
The menu bar is now attached to the top of the page, even if the user scrolls the page.
I added some CSS to fix this.
#5695
> Fix for #5695

- DuggaSys/diagram_mouse.js
Added line of documentation about preview line settings
> Added documentation regarding preview lines

- DuggaSys/diagram_symbol.js
Changed the letter o to letter p
> Fixed typo on documentation in diagram_symbol.js

- DuggaSys/diagram_IOHandler.js
Issue: #5712 
Only removed two unused functions and added the correct spacing between the nearby functions.
> Fix for issue #5712

- Shared/navheader.php
https://github.com/HGustavs/LenaSYS/issues/5656
> Removed back button from Course Editor page

- DuggaSys/sectioned.php
Fixed issue #5696 a second time for new branch, the other solution with creating a specific one might be valid as well but this soluiton works the same was as normally clicking the big orange fab button so its more reused.
> Update sectioned.php fixed upper plus(add new item)

- DuggaSys/courseed.js
- DuggaSys/sectioned.php
- Shared/css/style.css
Fix for issue [#5728](https://github.com/HGustavs/LenaSYS/issues/5728).
> Made FAB in courseed uniform with the rest, moved FAB in sectioned slightly to the left.

- DuggaSys/resulted.js
- Shared/css/style.css
Moved Times graded next to the grading buttons, added the class "WriteOutTimesGraded"  for styling, and added margin-right: 10px; inside the stylesheet at .VGh
> Grupp b2019 w#5662

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- DuggaSys/sectionedservice.php
Code updated with the new branch from the complete new GruppB2019W16 branch.
#5614
> Pull request to branch gruppB2019W16 #5614

- DuggaSys/sectioned.js
- Shared/css/style.css
- Shared/dugga.js
Removed "e.style.display= "none"; in dugga.js,
in the if(index_highest>0). It caused the escape button to remove/hide the fabBtn.
https://github.com/HGustavs/LenaSYS/issues/5782
> Fixed the issue #5782

- DuggaSys/diagram.js
- DuggaSys/diagram.php
#3752 
Co-Authored-By: b17robev <b17robev@users.noreply.github.com>
> Fix for issue #3752

- DuggaSys/diagram.js
- DuggaSys/diagram_symbol.js
#5736 
Co-Authored-By: b17robev <b17robev@users.noreply.github.com>
> Fix for issue #5736 

- DuggaSys/diagram_toolbox.js
Issue #5709  Have given every value a variabel that represent the toolbarstate.
> Issue #5709 fixed. Variables checked against numbers

- DuggaSys/diagram.php
- Shared/css/style.css
> Fix for issue #5639

- DuggaSys/diagram.js
- DuggaSys/diagram_mouse.js
Old pull request: https://github.com/HGustavs/LenaSYS/pull/5751
Issue: #5746 
Added two new variables that tracks the mouse coordinates in the canvas and later change the innerHTML so it always shows on screen.
> Fix#2 for issue #5746

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_IOHandler.js
- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
- DuggaSys/diagram_toolbox.js
> Fix for issue #5711

- DuggaSys/diagram_symbol.js
Seems to be working, copied code from old merge but didn't seem to cause any problems #5747
> Fix for issue #5747

- DuggaSys/resulted.js
As instructed in https://github.com/HGustavs/LenaSYS/pull/5873#pullrequestreview-226049241, this should resolve the issue with code missing from resulted.js
> Fix issues caused by merge problems resulting in missing code

- install/install.php
New pull request for the new branch.
> Fixed stripping of redundant slashes on new branch

- Shared/css/style.css
Changed the cursor style in ".loginBoxHeader" in style.css.
Co-Authored-By: a17alevu <a17alevu@users.noreply.github.com>
> Fixed issue #5846

- DuggaSys/accessed.js
Also added sorting for password reset requests.
For issue #5901
> Fixed sorting in access table. 

- DuggaSys/filereceive.php
Fixes issue [5899](https://github.com/HGustavs/LenaSYS/issues/5899)
> Added recursive option for mkdir

- Shared/css/style.css
> Update style.css #5875

- install/install.php
the "after" merge fix for #5652 and #5740
Had a pull request up for this already at #5759 , it got approved but wasn't merged to gruppC2019 before the big master merge. Manually copied the code back into the project so it should still work as before altough I didn't test it as much as I did the first time.
> New branch version fix for install with coursesys and timeout

- DuggaSys/diagram.php
> Fix for issue #5928

- Shared/css/style.css
Issue fixed! #5563 I have changed the margin the searchbox and moved up search-box and serach-button 5px up
> Fix for issue #5563

- DuggaSys/diagram_objects.js
Comment was not needed as the fix has been used permanently for the black box problem. 
#5707
> Removed obsolete comment - Fix for #5707

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_objects.js
> Grupp a2019 w16#5897

- Shared/SortableTableLibrary/sortableTable.js
> Revert "Tabel sorting fix for the access, test and files tab."

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- Shared/css/dugga.css
Shortened time format, used media queries to implement ellipsis on heading. Also added a span which contains all the info and shows on hover
Changes made in resulted handin popupview (Click on the fist) - Ellipsis should appear when resizing the window and all the heading info should apperar on hover
https://a17alian.group.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> #5907 - Improvements for responsive design

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_IOHandler.js
- DuggaSys/diagram_IOHandler.php
- DuggaSys/diagram_forms.php
- DuggaSys/diagram_objects.js
Very small quality fix for the code related to the diagram-files.
Issue: #5840
> Fix for issue: #5840 "Add whitespace before brackets"

- DuggaSys/diagram_forms.php
> Fix for issue #5896

- Shared/css/style.css
Changed the Shadow of the username text in the navbar to black instead of green
> GruppC2019W16_5870 Username Shadow changed

- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/5876
> Change inline-block to block for #Sectionlistc

- DuggaSys/accessed.js
Commented out the hoverc() and hovers() functions as they had a mouseover effect where an empty field appeared.
#5975
> Solution of issue #5975

- DuggaSys/diagram.js
#5942 
Shows lines for (0,0) so it is clear where the initial origo is.  Further the functionality to toggle origo on and off based on developer-mode.
> Fix for issue #5942

- DuggaSys/sectioned.js
> GruppB2019W16#5992 pull request to GruppB2019W16

- Shared/css/style.css
Updated style.css to remove the move-cursor on LoginBoxHeaders.
[#5858](https://github.com/HGustavs/LenaSYS/issues/5858)
> GruppB2019W16#5858

- DuggaSys/diagram_objects.js
The issue was solved in Issue: #5868 and therefore I only fixed small typos in comments and added some more documentation before each section (before the two functions that handle CREATE & DRAW). I also argue that it is not worth it to merge the two functions because they are constructed in different ways.
> Fix for issue #5837

- DuggaSys/diagram.js
> Add checkboxes - Fix for #5694

- DuggaSys/diagram.js
- DuggaSys/diagram_IOHandler.js
- DuggaSys/diagram_IOHandler.php
- DuggaSys/diagram_objects.js
Comments in all files named "diagram" have now been updated to follow the comment standard. In the PHP files there are HTML comments, and as there is no comment standard provided these have not been changed.
https://github.com/HGustavs/LenaSYS/issues/5708
> Fix for #5708

- DuggaSys/duggaed.js
- DuggaSys/fileed.js
- DuggaSys/resulted.js
Changed magicHeading to make  the "ghost table" disappear.  issue #5953
It also solved the issue with missing heading on the test page.  issue #5972 
I will just make one pull request for both this issues because it is the same code that solves them. 
When testing this use branch gruppC2019W16_5953 to check both issues.
> Fix for "ghost table" and missing heading on tests. 

- DuggaSys/resulted.js
- Shared/SortableTableLibrary/sortableTable.js
+autoformat, with tabs (as per code standard, probably)
> merge fixing: removes syntax errors, erroneous structure and call before definition

- DuggaSys/diagram.php
Issue fixed. #5890 I have removed "Snap to grid" in Item drop down menu
> Grupp a2019 w16#5890

- DuggaSys/diagram.php
> Fix for issue #6006

- DuggaSys/diagram.js
#6006 affected checkboxes, this commit makes checkboxes more robust. Fix for #5694
> Make checkboxes more robust, response to #6006 - Fix for #5694

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Fix for issue #5886
Removing lines from each align function now instead as that seemed to work better
Closed previous pull request as the branch had an old version which made testing harder
> Grupp a2019 w16#5886

- install/install.php
Reverts HGustavs/LenaSYS#5836
Reverting this pull request for the purpose of documentation. This issue and pull-request have too been remade.
> Revert "Changed textfield constraints for root password - Fix for #5720"

- Shared/SortableTableLibrary/sortableTable.js
fixed curly brackets so they match the if else statements. So now the sortabletable should be working.
> Fix for else error in sortabletable

- Shared/SortableTableLibrary/sortableTable.js
reinstate #5533 functionality (now in the big merge)
> fix merge typo/code ended up outside original function (re-fix #5533)

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
Issue: #6020 
Fixed that you don't have to scroll up/down & sideways, in other words, you always see 100% of the screen without scrolling.
> Fix for issue: #6020 "Diagram.php uses space that isn't used"

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- DuggaSys/resultedservice.php
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- DuggaSys/sectionedservice.php
For more commits and to easier see the history of the development look on branch "GruppB2019W16#5887".
Site: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
In the Result tab there is a mail button that will mail all students in the "view" (the current table that is showing). And you can use the search bar to search for different things and then click the mail button to open the mail with those students emails already assigned.
issue = #5887
> #5887 Pull request for the Mail button in the Result view.

- Shared/SortableTableLibrary/sortableTable.js
> spring cleaning: remove uncommented code and console prints

- Shared/SortableTableLibrary/sortableTable.js
Created a new branch, based on (https://github.com/HGustavs/LenaSYS/pull/6067), and merge it to our weekly branch.
> Grupp c2019 w17 springclean

- install/install.php
The same fix as #5836 but now using the W17 branch. 
Fix for #5720
> Re-fixed the install constraint on the root pwd textfield

- DuggaSys/duggaed.js
> DuggaEd: Added substr manipulation on the release date

- Shared/SortableTableLibrary/sortableTable.js
> Fixed sorting for password in access table

- DuggaSys/courseed.js
- Shared/css/style.css
New pull request for fixing cogwheel cursor on frontpage for issue https://github.com/HGustavs/LenaSYS/issues/5726 , based on https://github.com/HGustavs/LenaSYS/pull/5795.
> New fix for issue #5726

- Shared/SortableTableLibrary/sortableTable.js
> Added swedish locale to localeCompare

- DuggaSys/resulted.js
- Shared/css/style.css
> styling  been fixt#6030

- DuggaSys/accessed.js
Removed compare function that is not used anymore after the merge (2019-04-17). Removed an commented copy of the function as well.
> Removed Dead and commented code

- DuggaSys/filereceive_dugga.php
- Shared/SQL/init_db.sql
Gets rid of the trailing 0's in the submission view
> Time sheet: Changed day from DATETIME to DATE

- DuggaSys/duggaed.js
- DuggaSys/fileed.js
- DuggaSys/resulted.js
Removed dead code that is not used anymore since the newCompare function was added in sortableTable.js. It can be hard to test the result table because it was and are still broken even with the newCompare function.  Refers to this issue #6123
> Removed dead code. 

- DuggaSys/accessed.js
- DuggaSys/duggaed.js
- DuggaSys/fileed.js
- DuggaSys/sectioned.js
- Shared/css/style.css
- Shared/dugga.js
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6045
> Adjust FABs to use hover instead of mousedown to display sub-fabs on desktop devices

- DuggaSys/codeviewer.js
#6081 
Added and removed whitespaces
> Fix for #6081

- DuggaSys/resulted.js
> Grupp b2019 w17#6101

- DuggaSys/accessed.js
- DuggaSys/resulted.js
Masking ssn in resulted and access page - solving issue #5630 - hiding ssn
> Masking ssn

- DuggaSys/showDugga.php
> Changed 'overflow' to 'overflow-y' for submission view

- DuggaSys/showDugga.php
Reverts HGustavs/LenaSYS#6066
This should already be fixed (https://github.com/HGustavs/LenaSYS/issues/6044)
> Revert "Changed 'overflow' to 'overflow-y' for submission view"

- Shared/SortableTableLibrary/style.css
- Shared/css/style.css
> Modified add button to become lighter on hover.

- Shared/css/style.css
Closes #6140 
Test site: https://c17julka.gruppb.webug.his.se:20002
> Removed width of grading buttons

- DuggaSys/diagram.js
- DuggaSys/diagram.php
> Fix for issue #6073

- DuggaSys/resulted.js
Closes #6112 
Test site: https://c17julka.gruppb.webug.his.se:20002
> Removed filter button

- DuggaSys/diagram_objects.js
Should now automatically make lines forced between relations and entities when setting the relation to weak
#5143
> Grupp a2019 w17#5143

- Shared/dugga.js
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6169
> Fix issue with FAB button disappearing when pressing esc in some areas

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
There is now a function in diagram_objects.js that can be used, e.g. to evalutate which kinds of symbols a line is connected to.
The function is called on the line in question and returns an array with the two symbol objects that is connected to the line.
https://github.com/HGustavs/LenaSYS/issues/5960
> Fix for #5960:  Ability to find connected entities 

- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6147
> Set default webkit appearance to none for submit-button-newitem

- DuggaSys/showDuggaservice.php
- Shared/SortableTableLibrary/style.css
> Grupp c2019 w17 6091 - Switched deadline and release

- Shared/css/dugga.css
Added spacing between table headings. Solves this issue #6167
> Added table spacing

- DuggaSys/diagram.js
> Fix for issue #6155 Can't lock after alignment

- DuggaSys/diagram.js
- DuggaSys/diagram.php
> Fix for issue #6031

- DuggaSys/fileed.js
#6113 
Changed the comments to its right standard
> Fix for #6113

- DuggaSys/diagram_objects.js
#6179
Seems to work now. 
However, there is an error still present. It does not affect performance and I am not sure of why we get this error. I'll set it up as a new issue.
> Update diagram_objects.js #6179

- DuggaSys/diagram_objects.js
Issue #6028 Fixed. Changed the x and y values so the cardinalities dosen´t gets hidden by the weak entities
> Grupp a2019 w17#6028

- Shared/css/style.css
Fix for: #6191 "Spaceing for coordinates and zoom-placements".
> Grupp a2019 w17#6191

- DuggaSys/resulted.js
Fixes #6199 
Test site: https://c17julka.gruppb.webug.his.se:20002
> Removed commented code

- testfiles/OscarsTestFil.php
#6004 Removed a  unnused .php file that was made by me to make a test commit the first week.
> removed unnused file #6004

- Shared/css/style.css
https://github.com/HGustavs/LenaSYS/issues/5931
> Grupp c2019 w17 5931

- DuggaSys/resulted.js
- DuggaSys/resulted.php
#5635 
Cannot search on multpiple values yet
> Grupp b2019 w17#5635

- DuggaSys/diagram_objects.js
> Fix for issue #6177: Textbox selection does not have a good indication of when it is selected

- DuggaSys/sectioned.js
> Removed log keyCode in sectioned.js

- DuggaSys/sectioned.js
Swimlane improved visuals, adjusted width of the yellowboxes to prevent spilling out.
> Grupp b2019 w18#5866

- DuggaSys/duggaedservice.php
If-statement on line 55 commented out
Fixes #5981 and closes #6174
Test site: https://a17alian.groupb.webug.his.se:20002
> If-statement

- DuggaSys/duggaed.php
issue #6084 changed "release" to "result release" to make it a little bit clearer that the inputted date is the time when students can view their test results.
Can be seen at duggaed (tests) when creating a new test.
> changed "name" of field for new test

- DuggaSys/filereceive_dugga.php
Fix for issue #6002 
This will calculate the week number given the date the user submitted and insert it to the database table.
> Added insertion of week number to timesheet table

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Fix for issue #5826
Hopefully does not break any major parts of the program.
> Fix with zoom #5826

- DuggaSys/diagram_objects.js
#6251
added comment to function to clarify its use.
> Update diagram_objects.js #6251

- DuggaSys/filereceive_dugga.php
Changed the code in line with the issue explanation.
> Fix for #6262, typo fixed.

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
#6166 
I believe that i've changed the most important variables, however if there are more that should be added feel free to request them.
> Fix for issue #6166: Make variables more readable by adding values ​​to attributes

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Reverts HGustavs/LenaSYS#6273.
This issue caused problems with the diagram. The resolved conflicts did some damage. Please look into this.
> Revert "Fix for issue #6166: Make variables more readable by adding values ​​to attributes"

- DuggaSys/courseed.js
"Course Name" text window will now handle ÅÄÖ when you "Edit Course".
> Fix for issue #6190

- DuggaSys/resulted.php
- Shared/css/style.css
#6248
Hover over the questionmark next to the searchbar on the resulted page.
Link for testing: https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/resulted.php
> Grupp B - tooltip for searchbar that shows keywords

- DuggaSys/diagram.js
> Fix for issue #6050

- DuggaSys/diagram.php
#6283 
Changed the dropdown text below "help"
> Fix for #6283

- DuggaSys/courseed.js
Version ID removed from title on cogwheel hover in courseed. Only course name should appear. 
Closes #6291
Test site: https://a17alian.groupb.webug.his.se:20002/DuggaSys/courseed.php
> Version ID removed from hover

- DuggaSys/resulted.js
- Shared/css/style.css
if -statement on line 217(resulted.js) has been changed to 30. and entryname.length from 8 to 30.
Test site: https://a16hiwah.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Grupp b2019 w18#6202

- DuggaSys/diagram.js
Fix for issue #6234
Mapped drawing to pixelsToCanvas()
> Fix for issue #6234

- DuggaSys/diagram_objects.js
https://github.com/HGustavs/LenaSYS/issues/6274
UML lines are now smarter, using only as many kinks as are necessary.
(That the line breaks in when the UML classes get too close to each other is a separate issue that will be solved later)
> Fixed UML lines: #6274

- DuggaSys/resulted.js
#5622
When you press the hand on an assignment in the resulted view the name of the assignment will now be shown on the title of the box.
Test link: https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> assignment title shown in handin box in the resulted view

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
> diagram.js diagram.php style.css

- DuggaSys/diagram.js
> Revert "Update to diagram.js #5945"

- DuggaSys/diagram_objects.js
> Fix for issue #6247: Locks are no longer stuck to objects

- DuggaSys/accessed.js
- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
- DuggaSys/fileed.js
- DuggaSys/fileed.php
- DuggaSys/resulted.js
- DuggaSys/resulted.php
- Shared/css/style.css
#6253 
In resulted, accessed, fileed and duggaed, the search bar is now in the header. 
Might have issues with the tooltip fix (#6306). The tooltip from that pull request was implemented into this branch with some adjustments. If there are any search bar elements left in any of the .php files (like the tooltip might be), they should be removed.
Test site: https://c17julka.gruppb.webug.his.se:20002/
> Search bar moved to header

- Shared/css/style.css
#6334 
Also changed hover effect to be on <a> instead on the div.
Test site: https://c17julka.gruppb.webug.his.se:20002
> Fixed width of username element

- DuggaSys/diagram.js
#5945 
Fixed the issue again after the realization that the hovobj variable had been changed for some reason. Now it seems like it works as it did before the issue was merged into the group branch.
> Grupp a2019 w18#5945

- DuggaSys/diagram.js
- DuggaSys/diagram.php
> Fix for issue #6348: ghostingCrosses variable should be changed

- DuggaSys/diagram.js
Fix for issue #6263 
Math now properly included
> Fix for issue #6263

- Shared/css/style.css
Fix for issue #6029
Removed fixed position as it is no longer needed because scrolling isn't possible anymore. 
Added margin-bottom as well for style points and improved UX.
> Fix for issue #6029

- Shared/css/style.css
style on line 2764 change px to 35
Test site; https://a16hiwah.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Gropp b2019 w18#6256

- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6222
> Adjust margin of content div & TopMenuStatic in sectioned.php

- Shared/css/style.css
Removed the border-radius in style.css that made the button change on hover.
> Fix for issue #6300

- DuggaSys/accessed.js
https://github.com/HGustavs/LenaSYS/issues/6127
> "Added" to "Last Modified"

- Shared/css/style.css
Fix for the border lines #6279
> Fix on #6279, border lines on the tables. 

- Shared/css/dugga.css
Removed code that changed <tr> color.
> Fix for issue #5973

- DuggaSys/showDugga.php
Cleaned up some whitespaces in showDugga.php
> Fix for #6364

- DuggaSys/sectioned.js
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6367
> Change groups to use "a" tag instead of a div

- DuggaSys/accessed.js
- Shared/SortableTableLibrary/sortableTable.js
If you unselect all boxes it will now say none, before you couldnt unselect all groups for a student.
> You can now unselect the groups for the student

- DuggaSys/sectionedservice.php
fixing issue #6380 by moving and deleting code. also deleting some comments that clutter the code.
Should be able to log in as a normal registered to the course user and see the coursepage instead of "UNK".
> Removed duplicate code and moved a code section to the correct line

- DuggaSys/accessed.php
- DuggaSys/resulted.php
#6391 
Test site: https://c17julka.gruppb.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursevers=97732
> removed second search bar

- DuggaSys/diagram.js
Fix for issue #6280
Bounding rect should now be implemented correctly. 
It is set once the canvas is loaded and also when the window is resized.
The current branch to test on is gruppA2019W18#5609
> Fix for issue #6280

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Fix for issue #6269
Toggle for orientation of A4, icon should be changed when toggling and hid when a4 is not displayed
> Fix for issue #6269

- Shared/css/style.css
- Shared/navheader.php
Changed the hover function to just make the icon brighter and removed the man icon completely.
> New fix for issue #5655

- DuggaSys/resulted.js
solving issue #6331
in resulted. js the funnel and sorting icons should remain the same as before except this way of adding them(showing them) should be more easy to change in the future since the icon and parent div is created in the same place as for access and other pages (in navheader.php)
> Grupp c2019 w18 6331, funnel and sorting in resulted are now added in a way with less redudant code

- DuggaSys/diagram.js
> Fix for issue #6327: Reset view to origin doesn't work 

- DuggaSys/diagram.js
> Fix for issue #6335

- Shared/css/style.css
Issue #6375 fixed. Added cursor: pointer; to the Zoom increase and Zoom decrease buttons.
> Grupp a2019 w18#6375

- DuggaSys/resulted.js
- Shared/SortableTableLibrary/sortableTable.js
Fixed sortable headers in resulted, sort after fname, lname, ssn and grade.
testing site: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Grupp b2019 w18#5916

- DuggaSys/accessed.js
#6400 
Test site: https://c17julka.gruppb.webug.his.se:20002/DuggaSys/accessed.php?cid=2&coursevers=97732
> Removed unused function in accessed.js

- Shared/SQL/deltachange.sql
- Shared/SQL/init_db.sql
> Add updated column to vers

- Shared/SortableTableLibrary/sortableTable.js
#6329, a few comments added but more are needed
a duplicate of the magicHeader function was also removed.
> Commenting sortableTables

- DuggaSys/diagram.js
> Scroll zoom implemented

- DuggaSys/diagram.js
Fix for issue #6263 
Already tested and merged but disappeared so trying again now
> Trying again

- DuggaSys/courseed.js
Removed version ID and course coordinator. Added course code instead
Closes #6313 
Test site: https://a17alian.groupb.webug.his.se:20002/DuggaSys/courseed.php
> Title info

- DuggaSys/diagram.php
- Shared/css/style.css
Uses function on-input rather than onChange, minor UI change to border-radius on buttons
> Fix for issue#6362

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
> Zoom value implemented everywhere

- DuggaSys/diagram_objects.js
https://github.com/HGustavs/LenaSYS/issues/6322
Set breakpoints to same as start and end points when classes are too close to each other.
> Fix for UML lines #6322

- DuggaSys/sectioned.js
There shouldnt be any trouble, but heres a test site just in case
#6439 
https://c17alepe.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursevers=97732
> deleted commented out code

- DuggaSys/sectioned.js
Added comments for the rules of the deadline section. Did this to clearify to the developers that the rules of the "statistics-pie" also applies to the section that shows the time period of each dugga deadline.
> Pull request for #6197

- DuggaSys/courseed.js
- DuggaSys/courseed.php
- Shared/css/style.css
- Shared/dugga.js
- Shared/navheader.php
https://github.com/HGustavs/LenaSYS/issues/6210
> Grupp c2019 w18 6219

- DuggaSys/diagram.js
Fix for issue #6344 
Removed some old unused stuff as well
> Added updateGraphics() after resize

- DuggaSys/courseed.js
Text title when logged out is fixed. Registered and version ID removed, course code added.
Closes #6441
Test site: https://a17alian.groupb.webug.his.se:20002/DuggaSys/courseed.php
> Text hover fixed

- DuggaSys/sectioned.js
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6459
> Fix small syntax error

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
You can no longer resize or open the appearance menu for locked objects.
#6309
> Fix for #6309 - Locked objects can not be interacted with

- DuggaSys/diagram.js
- Shared/css/style.css
#6121 
Made the canvas work space bigger and fixed so that the margins around the canvas are equal.
> Fix for #6121

- DuggaSys/diagram.js
Fix for issue #6440 
Right click does not move objects anymore
> Added canvasRightClick

- DuggaSys/accessed.php
H1 title in accessed now centered
closes #6411
Test site: https://a17alian.groupb.webug.his.se:20002/DuggaSys/accessed.php?cid=2&coursevers=97732
> H1 title centered

- DuggaSys/resulted.php
- DuggaSys/resultedservice.php
Fixes the issue of being able to access emailbutton while not logged in or not logged in as superuser.
closes #6398
test site: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Grupp b2019 w18#6398

- Shared/css/style.css
fixes issue #6386 ,
added styling in media queries so the searchbar input will be smaller.
> Grupp b2019 w18#6386

- DuggaSys/diagram.js
- Shared/css/style.css
#6449 
Changed the styling so the text no longer looks like a button and also clarifies that it shows the selected mode.
> Changed text styling for mode - Fix for #6449

- Shared/loginlogout.php
> Removed unused database reference

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
> Fix for issue #6382: Warning when switching modes

- DuggaSys/diagram.js
Issue #6289 fixed. Can move around with arrowkeys in "MoveAround" mode.
> Grupp a2019 w18#6289

- DuggaSys/sectioned.js
- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6467
> Add padding to no access/no items message

- DuggaSys/sectioned.js
Fixed the problem with the missing icon when creating a message, due to not being able to find which old icon was used i decided to use the warning triangle to make a clear signal that this was important (the message not the issue).
> Grupp b2019 w18#6223

- DuggaSys/resultedconstants.php
- DuggaSys/resultedservice.php
- Shared/SQL/init_db.sql
- install/SQL/2019vt_delta.sql
To test these changes, a database update is required. See the committed delta-file.
This will close #6466 (apparently the auto-close-reference does not work in the title?)
> Implements and closes #6466 - a sub-issue to #5613

- Shared/css/style.css
> Fix for #6476

- DuggaSys/diagram.js
Fix for issue #6469 
Javascript is still bad at math
> Rouning error solved

- DuggaSys/diagram.js
Fix for issue #6489 
Now scales with zoom as well
> Fixed resize issue

- DuggaSys/templates/daily-minutes.html
- DuggaSys/templates/daily-minutes.js
- Shared/css/dugga.css
Made a new form for smaller devices. If the window width is bigger than 1120px the old form will show. If the window width is smaller than 1121px the new mobile friendly form will show and the other form will be hidden.
**Normal form:**
**Mobile friendly form:**
> Moblie friendly form added to Daily-minutes

- Shared/css/style.css
Fix for issue #6474
Is now white
> MEGA FIX FOR ZOOM BAR

- Shared/css/style.css
Moved the accept and cancel button with Justify-content: space around
@a17vikab helpt with this issue
> Added flex styling

- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6510
> Change login/logout button colors

- DuggaSys/diagram.js
Fix for issue #6490 
Toolbar state had a bug in it which broke the developer mode in it.
> Fixed developer mode logic and bug, Fix for issue #6490 

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
> Fix for issue #6409: Drawing objects should be centered on the pointer 

- Shared/css/style.css
like for test : https://a16hiwah.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
i removed all !important  and used CSS Specificity instead. all changes has been on style.css
> Using CSS Specificity instead !important.

- DuggaSys/courseedservice.php
> Remove duplicate variable

- DuggaSys/accessed.js
As @a17joaap suggested, adding the three lines solves issue #6513.
See his first pull request #6303.
> Re added code that went missing to accessed.js

- DuggaSys/sectioned.js
- Shared/css/style.css
> Fixed draggable on error/empty message.

- DuggaSys/diagram.js
We have fixed the distribute-functionality to work as it was expected. Also, the align-functionality works as @HGustavs wanted to be.
_(Me and @a17drama has worked with this issue)
#6578_
> FIX: Move align functionality to distribute #6578

- Shared/css/style.css
- Shared/navheader.php
Solved the styling issue for the "cookie" tab. Open the site in "inkognito" mode (ctr+shift+n) and see if the button is correctly alinged.
> Grupp b2019 w19#6511

- DuggaSys/resulted.js
- DuggaSys/resultedservice.php
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- DuggaSys/sectionedservice.php
- Shared/SortableTableLibrary/sortableTable.js
> Grupp b2019 w19#6245

- DuggaSys/resulted.js
Look at issue #6494.
Will now stop scrolling, also changed left to transform: translateX() since that property is supposed to be better for animating. Which I think resulted in smoother animation for the ladExportContainer when scrolling horizontally.
for testing: https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Fix for infinite scroll

- DuggaSys/courseed.php
> Pointer cursor missing #6535 Update courseed.php

- Shared/css/style.css
For issue #6509 
Fixed the styling of the searchbar.
Works in all the sites exept Resulted due to another bug for that perticular site.
https://a17oscno.gruppb.webug.his.se:20002/DuggaSys/courseed.php
> Grupp b2019 w19#6509

- DuggaSys/duggaed.js
Fix for https://github.com/HGustavs/LenaSYS/issues/6518
> Removed duplicate FAB

- DuggaSys/contribution.js
https://github.com/HGustavs/LenaSYS/issues/6583
> Fixed spelling error

- Shared/css/style.css
https://github.com/HGustavs/LenaSYS/issues/6575 
Just one row changed. row 1600. I guess my editor, atom, removes unnecessary white spaces(?)
Changed the transistion on the hover from 1 to 0.1 for faster response on the hover on buttons.
(Can't for some reason not create a gif on my laptop. So you have to test this on your own test environment.)
> Faster response on button hover #6575

- DuggaSys/sectioned.php
- Shared/SortableTableLibrary/style.css
- Shared/css/style.css
[Issue](https://github.com/HGustavs/LenaSYS/issues/6218)
The greyed out color might be something to change. If so, please respond with a suitable hexcode for the color.
> gruppB2019W19#6218

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
#6457 
The toolbar is now moved to the left and seems to work as intended.
Moved canvas to the right to make room for the toolbar
Changed size of the toolbar
Removed the minimize toolbar functionality
Removed the align toolbar horizontal functionality
Removed unnecessary functions
> Grupp a2019 w19#6457

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
Fix for issue #5750
Previous pull request:
https://github.com/HGustavs/LenaSYS/pull/6547
Added constants and dropdown options + hotkeys
> Fixed move to front / move to back, Fix for issue #5750

- DuggaSys/diagram.php
- Shared/css/style.css
Fixed so every button behave the same, eg: hover-effect and styling in change-mode-dialog
Issue: #6495
> Fix #6495 global button styling

- DuggaSys/diagram_objects.js
Fix for issue #6434 
Added pixelsToCanvas to locks and points
> Fixed lock and points resize, Fix for issue #6434 

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- Shared/navheader.php
Re-implemented code from resulted.js and commented out code inside navheader.php that would collide with resulted.js and create issues.
> Searchbar, sorting has been moved. 

- DuggaSys/diagram_objects.js
Fix for issue #6608 
Added zoomValue so now they scale
> Fixed offsets for weak entities, relations, and multi valued attributes

- DuggaSys/templates/kryss.html
- Shared/css/dugga.css
> Styling fix for kryss template

- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6625
> Remove overflow-y on body

- DuggaSys/diagram.js
> Fix for issue #6370: You shouldn't be able to draw lines to text

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Fix for issue #6475
Touchpad zoom is acceptable but inertia is still a problem. Does not seem to have a good fix.
Grid is broken but it was before so scroll functionality was prioritized in this case. Works better on even values but not good.
> Grid is broken but now touchpad zoom is smoother, Fix for issue #6475

- DuggaSys/sectioned.php
- Shared/css/style.css
> Increase responsivness burger

- Shared/dugga.js
- Shared/loginbox.php
- Shared/loginlogout.php
fixes #6272
When the session has 15 minutes left a message box appears and the user has a chance to refresh the session. Otherwise when 15 minutes more pass the user will be logged out and the page refreshed.
For testing you can remove the comment on line 329 and 343 while also commenting out line 330 and 344 in dugga.js. This will set so the session box appears after 1 minute and the user is logged out after 2 minutes.
> Notifies user when session is running out

- DuggaSys/accessed.js
fixed https://github.com/HGustavs/LenaSYS/issues/6649, Searchbar is back in accessed.php!
> fixed 6649

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- Shared/css/dugga.css
- Shared/dugga.js
Moved feedback section into fab button. Should animate window in from left when fab is clicked
Fixes #6589
Before:
After: 
Test site: https://a17alian.groupb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
(Student Sven Brock should have handins to test)
> Redesign feedback for handin

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
Issue #6017 fixed. When trying to make a line between two ER attributes an error dialog that none of the objects are Composite.
> Fix #6017 ER composite behaviour 

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Fix for issue #6648 
Math is unpredictable but seems to work in all zoom modes, at least inside the canvas...
> Grid working when looking at it, Fix for issue #6648 

- Shared/css/style.css
https://github.com/HGustavs/LenaSYS/issues/6479
> Centered request PW button

- DuggaSys/templates/generic_dugga_file_receive.js
- Shared/css/style.css
Added some css that adds an other color to the rows on showDugga's tables.
(forgot to refer the issue: https://github.com/HGustavs/LenaSYS/issues/6564 )
> showDugga.php - Alternating rows fix #6564 

- DuggaSys/diagram.php
- DuggaSys/diagram_IOHandler.js
#6461 
Deleted the function createFolder since it was never used. Commented out getImage and where it was used. It seemed like this function did not get implemented because of some old issue. I found this comment in the code:
`THESE OBJECTS ARE NOT IN THE TOOLBOX OR THE MENU AS THEY PROBABLY SHOULD BE IMPLEMENTED SOMEWHERE WITHIN ISSUE #3750`
> Fix for #6461

- DuggaSys/diagram.php
- Shared/css/style.css
Issue #6385 fixed. The styling of the zoombar is improved. The increase and decrease button are bigger and have the same size. Removed position: absolute and istead use dispay: flex.
> An improved styling to the zoombar

- Shared/SQL/deltachange.sql
- Shared/SQL/init_db.sql
> Create the database in its final form directly

- Shared/css/style.css
- Shared/navheader.php
**Added 4px of bottom margin to the button:**
> Fixed bottom margin of cookie popup msg button

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Changed previous branch/pull request (https://github.com/HGustavs/LenaSYS/pull/6606) to accommodate new symbolKind changes.
> Grupp a2019 w19#6664

- DuggaSys/contributionservice.php
Prevents contribution from loading
> Fixed issue from previous merge

- Shared/css/style.css
Removed commented out lines and changed the margin to be more consistent
> Updated margins on Stoplights

- DuggaSys/sectioned.js
Added a space between error-texts.
> Fix for #6524

- DuggaSys/accessed.js
- Shared/SortableTableLibrary/sortableTable.js
The hover functions are back on the accessed page, although just a white box for now. 
The file in question is accessed.php
> Accessed hover and leave functions are but pack #6657

- DuggaSys/accessed.js
- Shared/SortableTableLibrary/sortableTable.js
Fixed missing div and columno spelling in sortableTable.js
> Grupp c2019 w19 funnel missingdiv fix

- DuggaSys/diagram.js
Fix for issue #6675
Added scaling and removed global variable
> Removed global variable and added scaling, Fix for issue #6675

- DuggaSys/diagram_IOHandler.js
- DuggaSys/diagram_IOHandler.php
Cleaned the code and made it more readable.
issue: #6693
> Cleaning code: diagram_IOHandler.php/js #6693

- DuggaSys/duggaed.js
- DuggaSys/resulted.php
- DuggaSys/sectioned.js
> Removed gradesystem U-3-4-5 from sectioned and in general cause it doesn't exist anymore.

- DuggaSys/resulted.js
Fixes #6154 
Number will now be updated and show the new value after every time a grade is changed.
> Grupp b2019 w19#6154

- DuggaSys/resulted.js
- Shared/css/style.css
Added some clarity in resulted to when an assignment was submitted late. Unsure if this is enough to fix the issue(#4164 ) but it atleast adds some clarity.
test-site: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/courseed.php
> Added clarity to late submission in resulted

- DuggaSys/sectioned.php
- Shared/dugga.js
Fixes #6290
You should now be able to right-click or ctrl + click to open a new tab.
Test site: https://a17alian.groupb.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732
> Open Results, Tests etc. on a new tab

- DuggaSys/resulted.js
- DuggaSys/resultedservice.php
- Shared/SortableTableLibrary/sortableTable.js
Fixes #6581 
Test site: https://c17julka.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
This makes it so that the SSN is not used at all in resulted, which indeed hides it from appearing in the site's response. However, the LadExport no longer includes the SSN. I am thinking this needs to be separated into its own issue, since the LadExport would need to be redesigned in order to also include the SSN.
> Removed import of ssn to resulted

- DuggaSys/duggaed.php
Removing the "Create JSON"-button. Pull request for issue: https://github.com/HGustavs/LenaSYS/issues/6632
> Fix for issue #6632

- DuggaSys/diagram.js
- DuggaSys/diagram_forms.php
- DuggaSys/diagram_objects.js
> Fix for issue #6533: Relation lines missing in UML 

- DuggaSys/contribution.js
- DuggaSys/contributionservice.php
Returning the amount of students in the course and in the groups to then use in the intervalToColor instead of a hard coded 41, fixes #6446.
> Contributionservice returns amount in groups and course

- DuggaSys/diagram.js
This fix should solve the issue but there is much more to do. Copying doesn't get effected by this change as it is now. Should be a different issue consider what @a16tobfr is wishing for this in the future. I will write a few more issues building on this one with regards to the wishes. All this does now is that it start's different kinds from 0.
> Fix for #6688 Numbering of different kinds start at 0

- DuggaSys/diagram.php
- Shared/css/style.css
undo/redo buttons are now next to eachother
> Grupp a2019 w19#6707

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
#6709 
Moved toolbar and changed the text
> Moved toolbar and changed text

- DuggaSys/diagram.js
Fix for issue #6613 
Cannot test this as we do not have such screen.
> Should be fixed, Issue #6613

- DuggaSys/diagram.js
Fix for issue #6432
Changed logic for cursor changes and narrowed it down to fewer functions
It was changed in several functions which caused them to compete and also,
the correct cursor for resize was only set once and not continuously.
> Removed unnecessary cursor changes, Fix for issue #6432

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- Shared/SortableTableLibrary/sortableTable.js
- Shared/navheader.php
Closes #6650 
Sets the sort, filter and searchbar at the right place with the right code. See issue #6650 and #6649.
> GruppB2019W19#6650

- DuggaSys/resulted.js
Fixes #6766
Test site: https://c17julka.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Removed console.trace

- DuggaSys/accessed.js
- DuggaSys/accessed.php
- DuggaSys/fileed.php
- Shared/css/style.css
More mobile friendly tables (AccessEd, FileEd, DuggaEd)
https://github.com/HGustavs/LenaSYS/issues/6216
> Update issue 6216 to new master

- DuggaSys/templates/daily-minutes.html
- Shared/css/dugga.css
- Shared/css/style.css
Fixed styling so it's consistent with other dugga pages. For example changed color of "Add row" and "submit" button aswell as padding.
> Pull request for #6579

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
#6749
Fixed position of the horizontal/vertical toolbar
This solution also fixes #6750, #6708, and finishes the Toolbar megathread #6699
> Toolbar styling changes

- Shared/SortableTableLibrary/sortableTable.js
#6722 
"var filteredRows = []; " store the data of all currently visible rows.
Then picks out the usernames for each row. 
To Store all data instead of only username is more generic and gives openess for future purpose of the variable.
> Mail only visible rows/users W20 #6722 

- Shared/dugga.js
> fixed .zip and .rar to not show additional popup dialog for download.

- DuggaSys/diagram.js
Minor issue that fixes the undo redo functions.
> Undo and redo working again

- DuggaSys/accessed.js
Added the functionality that the user can use "Enter", to confirm the change, or "Escape" to cancel the change (remove the box).
Original issue: https://github.com/HGustavs/LenaSYS/issues/6644
> AccessEd: Added keyboard shortcuts to edit boxes 

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- DuggaSys/sectionedservice.php
Fixes #5620 
It is now possible to change the deadline of a test (dugga) in sectioned instead of going into the "Tests" tab  (duggaed). 
Just click on the cogwheel on a test and change the deadline and then go into the tests tab and do it there to. You should see that both updates and that it actually updates the deadline in the database.
Link: https://a17oscno.gruppb.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursevers=97732
> Grupp b2019 w20#5620

- DuggaSys/resulted.js
Fixes #6757 
That last slash from the picture is now removed. This is in the resulted page of dugga in the table.
Test site: https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Removed the last slash

- Shared/css/style.css
Aligned items in the navbar according to the dropdown.
Fixes #6745 
use branch: GruppB2019W20#6745
if test site doesn't work: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursevers=97732
> Aligned items in navbar

- DuggaSys/templates/generic_dugga_file_receive.js
Most browsers should give the upload file popup a filter with zip and pdf files properly. fixing #6780
works for most browsers.
https://www.w3schools.com/tags/att_input_accept.asp
> Upload file filtering added

- DuggaSys/diagram.php
- Shared/css/style.css
#6795 
Also removes the need for inline styling in the diagram.php document
> added CSS class to fix the issue #6795

- Shared/css/style.css
> Fix for issue #6751, position of coordinate-box

- DuggaSys/diagram.php
- Shared/css/style.css
Issue #6748 is fixed. The position and styling of the zoombar is fixed.
> Zoombar fixed #6748

- DuggaSys/diagram.js
#6792 Deleted wrong comment and deleted some unnecessary comments.
> Fix for #6792 Wrong comments

- DuggaSys/contribution.php
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6803
> Fix error message when hovering bar graph in contribution

- DuggaSys/duggaed.js
> Fixed selection issue to be able to deselect by pressing the cog again.

- DuggaSys/diagram.js
> Fix for issue #6465: Cursor change to indicate objects are movable in 'MoveAround' mode 

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Closes #6530 
You should now be able to click outside of hamburger menu without menu and navbar disapperaring
This was only an issue in Firefox
> Hamburger menu fix

- Shared/css/style.css
- Shared/navheader.php
> Grupp b2019 w20#6520

- DuggaSys/resulted.php
- Shared/css/style.css
Inline style has been removed and moved to External style sheet
test link: https://a16hiwah.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Grupp b2019 w20##6742

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/dugga.js
Fixes: #6735
Hamburger menu/ navbar is no longer disappearing when using esc button in FireFox to close hamburger menu.
> Esc button fix

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
before
after
#6740 
Javascript now assigns a title to the id #course-coursename
testsite: https://c17alepe.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursevers=97732
> Title attribute fix

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/dugga.js
Fixes #6753 
Added separate function to specificly handle changing course version which should prevent breaking anything else depending on changeURL function in LenaSYS
> issue #6753 - fix for not being able to change coursevers in dropdown box

- DuggaSys/contribution.js
- Shared/css/style.css
Added buttons for sorting views in contribution.php
Buttons and functionality can be added with ease by tagging classes with "group1-3" and adding more groups and buttons should not be a problem in the future since the buttons only really sends the values of the classes that should be hidden to a generic function. One caveat is the sortable table in the bottom of the page, could not find a way to set a class for it so had to hide it manually using its ID. Therefore improvements could be made in the future.
> Added sorting to contribution views Gruppc2019w20_6312

- DuggaSys/duggaed.js
https://github.com/HGustavs/LenaSYS/issues/6278
> Remove sorting for icons

- Shared/css/style.css
Added the same kind of borders that exists for the other tables on the side
> Accessed: Added Borders to table data issue: #6818

- DuggaSys/accessed.js
- Shared/css/style.css
Adds a button that lets you toggle all the check-boxes in the drop-down on accessed.
FIxes #6769
> Adds toggle all checkboxes on accessed issue: #6769

- Shared/dugga.js
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6841
> Remove login session refresh success alert message

- Shared/css/style.css
Added styling for "submit" button and "add new" button.
> Added styling for daily minutes. #6743

- DuggaSys/templates/daily-minutes.html
A fab-click on the "Daily minutes" page now results in an added row.
> Pull request for #6703

- DuggaSys/codeviewer.js
Function brackets now follow the function standard.
> Pull request for #6124

- DuggaSys/diagram_IOHandler.js
- DuggaSys/diagram_objects.js
> Fix for #6868

- DuggaSys/diagram.js
Issue: #6684 
Removed the console.log command for when developer mode is being disabled.
Should the console.log command for when developer mode is being enabled still exist? If not, I can remove that aswell. Just let me know.
> Fixed issue #6684: Unnecessary console.log in groupbranch

- Shared/css/style.css
> nudging position burger

- DuggaSys/diagram.js
> Fix for issue #6826

- DuggaSys/accessed.js
Fix for #6670 Someone had replaced the img ID with the class attribute.
> AccessED: Fixed bug where old version icon didn't show.

- Shared/dugga.js
> Added titles to download and new tab images

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
#6387 
Co-authored with @a17jacsv
> Fix for issue #6387: Free draw/draw square objects can not be locked 

- Shared/css/style.css
fixed by specifying the correct value to transition
> Update edit version and create version buttons hover transition #6819

- DuggaSys/diagram.js
- DuggaSys/diagram.php
https://github.com/HGustavs/LenaSYS/issues/6893
"Draw Text" button is now visible in all modes and in correct place.
> Fix for #6893: Text button is now visible

- DuggaSys/filereceive_dugga.php
- DuggaSys/templates/generic_dugga_file_receive.js
- Shared/css/style.css
https://github.com/HGustavs/LenaSYS/issues/6744
> Overhauled the wrong file extension error in file submission

- DuggaSys/diagram.js
> Fix: #6853 - Remove hover-functionality when drawline-tool is used

- DuggaSys/accessed.js
- DuggaSys/accessedservice.php
Fix for https://github.com/HGustavs/LenaSYS/issues/6580. Made the decision to remove SSN all together in accessed. Removed it from the table and it's no longer a GDPR violation.
> AccessED: Removed ssn in table and it no longer shows in HTTP JSON response 

- DuggaSys/codeviewer.js
Fix for https://github.com/HGustavs/LenaSYS/issues/6122. Code should be easier to read now.
> Removed empty rows in codeviewer.js

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
supposed to fix the issue part of #6669
(in the comments). Editing the json text area should if possible make corresponding changes to the form on the left.
> Added reverse/two way functionality to jsonText

- DuggaSys/contribution.js
fixes ##6931 no longer prints undefined underneath the ranking table.
> createTimeSheetTable no longer added to str

- DuggaSys/codeviewer.php
Switched out the placeholder trashcan favicon for the one present on the rest of LenaSYS.
New vs old
> fixed issue #6903 - changed favicon in codeviewer.php 

- Shared/css/markdown.css
https://github.com/HGustavs/LenaSYS/issues/6924
> Fixed the document view in codeviewer

- DuggaSys/accessed.js
Fixes #6837 
Now possible to sort through the dropdown.
> Added sort options to sort dropdown

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
#6859 Almost according to the list in issue. Switched attribute till Shift + A and put in Text that is coming in the future on Shift + T. Rest is according to the list/comments in the issue. Also ordered the key declarations in key code ascending order.
> Fix for #6859 Shortcuts for toolbar and some other things

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
> Fix for issue #6875: Diagram lock should be able to unlock when clicking on the lock.

- DuggaSys/codeviewer.js
- DuggaSys/codeviewer.php
- DuggaSys/codeviewerService.php
- Shared/SQL/init_db.sql
- Shared/css/template10.css
> Pull request for issue #1779

- install/install.php
> Add check for correct upload_max_filesize during install 

- DuggaSys/codeviewer.js
> Codeviewer: Fixed file upload button

- DuggaSys/sectioned.js
Fixes #6836 
If the dugga name is longer than the svg element, it fades out. You can see the whole name if you hover over it.
> Added faded and hover effect to swimlane segments

- DuggaSys/fileed.php
Fixes #6831 
Now when you click on the text the corresponding radio button will be selected.
Test site: https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/fileed.php?cid=2&coursevers=97732
> Radio buttons are now "connected" with the text

- Shared/css/style.css
Fixes #6782 
testsite: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732
or branch GruppB2019W20#6782-2
> Aligned checkbox in popups

- DuggaSys/codeviewer.php
- Shared/icons/template10_butt.svg
https://github.com/HGustavs/LenaSYS/issues/6978
> New icon for new template

- DuggaSys/codeviewer.js
- DuggaSys/codeviewerService.php
https://github.com/HGustavs/LenaSYS/issues/6951
> Codeviewer file extension filtering

- DuggaSys/codeviewer.js
> Added a small How-To in codeviewer.js

- DuggaSys/diagram.js
- DuggaSys/diagram.php
This pull request is a partial fixed. This solved issue #6685, #6686, #6687. Can copy of entities, attributes, and relation but copy the line doesn't work yet.  When removing the copy objects the original line doesn't remove any more.
We have removed "Object.assign" witch only create shallow copies. Instead, we used JQuery.extend witch make deep copies.
> Issue#5040  Copy functinality

- DuggaSys/diagram.php
#6910 
Fixed the indentations of the divs in the diagram.php document.
> Grupp a2019 w20#6910 <div></div> indentations in diagram.php

- DuggaSys/codeviewer.js
> Codeviewer: Prevent line break in contenteditable spans

- DuggaSys/codeviewer.js
- Shared/dugga.js
https://github.com/HGustavs/LenaSYS/issues/6998
Fixed so the page doesn't stay dark when you save your settings.
Also fixed some smaller code standard errors and a comment that was outdated.
> Grupp c2019 w20 #6998

- DuggaSys/templates/daily-minutes.js
- DuggaSys/templates/feedback_dugga.js
- DuggaSys/templates/generic_dugga_file_receive.js
- DuggaSys/templates/group-assignment.js
Fixes #6796 
No error message should pop up in the console now when navigating to a dugga using either of these templates:
- generic_dugga_file_receive
- group-assignment
- feedback_dugga
- daily-minutes
> Fixed upload instructions conditional

- DuggaSys/diagram.php
- Shared/css/style.css
Issue #6885 fixed. All the buttons have the same styling now.
> button styling #6885

- DuggaSys/diagram.php
- Shared/css/style.css
> Revert "button styling #6885"

- Shared/SortableTableLibrary/sortableTable.js
This fixes #6930 the issue of sorting files according to size. 
Testsite : https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/fileed.php?cid=2&coursevers=97732
or branch GruppB2019W20#6930
> Fix for sorting files according to size

- DuggaSys/contribution.php
- DuggaSys/showDugga.php
> Remove submit button table for contribution

- Shared/css/template10.css
#6982 
Changed the width of "box1wrapper" to cover the whole page.
> Pull request for #6982

- DuggaSys/courseed.php
- Shared/css/style.css
Fixes #6568 
The checkbox placement has been changed and it is now possible to press the checkbox. The functionality will remain due to it changing values in the database that is used (but might not serve a purpose, hard to tell) also changed the name to a easier one.
Link: https://a17oscno.gruppb.webug.his.se:20002/DuggaSys/courseed.php
> Grupp b2019 w20#6568

- DuggaSys/duggaed.js
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6955
> Fix two small typos

- DuggaSys/diagram.js
Follows the code standard much better now...
Issue: #6943
> Cleaned code of diagram.js #6943

- DuggaSys/diagram.php
#7006 
Added shortcut command tooltip for redo and undo buttons.
> Shortcut command tooltip for undo/redo buttons #7006

- Shared/dugga.js
- Shared/loginbox.php
Added some kind of response to multiple failed login-attempts in a row. 
Fixes #5917 
Test-site: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursevers=97732
> Added failed-login response 

- DuggaSys/sectioned.php
fixed by removing unnecessary date input in  sectioned.php. line 232
test link; https://a16hiwah.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732
"before"
"after"
> [SectionEd] Set Date in Edit Item view style needs fixing #6812

- Shared/SortableTableLibrary/sortableTable.js
Fixes #6557 
To test, go to "webbplatsdesign" and then click contribution
Testsite: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/courseed.php
or branch GruppB2019W20#6557-2
> Fixed sorting week-column in contribution

- DuggaSys/courseed.php
- Shared/css/style.css
#6832 
Also corrected the MOTD message so it's now in the middle.
> Grupp b2019 w20#6832

- DuggaSys/codeviewer.js
- Shared/css/codeviewer.css
Only a QOL improvement to codeviewer that lets you maximize the window you want to have maximized with a single button press. Right now it supports all templates except for template 9(template 9 is a little broken)
> codeviewer: Ability to maximize a window

- DuggaSys/codeviewer.php
Changed heading from "Edit Example" to "Choose Template". #7044
> Pull request for #7044

- DuggaSys/diagram_objects.js
Made the if statements in drawUMLLine, use pixelsToCanvas to be compatible with the new camera system. Fix for issue https://github.com/HGustavs/LenaSYS/issues/6452.
> Pull request for issue #6452

- DuggaSys/codeviewer.js
- Shared/css/style.css
- Shared/icons/Copy.svg
https://github.com/HGustavs/LenaSYS/issues/7013
> Grupp c2019 w20 7013

- DuggaSys/fileed.php
- Shared/css/style.css
Fixes #6591
A box shows up containg the allowed files. I am not sure if there are more files allowed but that is easy to add later.
This is in the fileed part of dugga when uploading a file.
Test site: https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/fileed.php?cid=2&coursevers=97732
> Shows allowed files when uploading in fileed

- DuggaSys/codeviewer.js
- Shared/css/codeviewer.css
- Shared/css/style.css
Fix after conflicts broke the button
> Fixes copy button and moves the css for the button

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Issue #6573
Removed code for draw square
> Issue #6573

- DuggaSys/diagram.php
- Shared/css/style.css
Issue #6885 fixed. All the buttons have the same styling and have moved some css from the php file to style.css
> Restyling on buttons and moved styling from php file to style.css

- Shared/css/style.css
Issue #7074 fixed. There is now space between the zoombar and the zoom-text
> Space between zoombar and zoom-text

- Shared/dugga.js
Fixes #6965 
Testsite: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursevers=97732
> Fixed error when pressing escape

- DuggaSys/resulted.js
fixes #6999
When you filter for "only pending" in the filter dropdown in the menu only the pending duggas will be shown. This is in the resulted part of dugga.
Test site: https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Filter for pending duggas

- DuggaSys/codeviewer.php
Added description "No spaces" for "Important words" to clearify for the user. #6952
> Pull request for issue #6952

- Shared/css/style.css
Issue: #7077 
I removed the ability to even select the buttons while clicking and dragging with the mouse, but the functionality of the buttons should still work fine. I tried them all and it seemed to work.
> Fixed issue #7077: Selecting some of the buttons made them appear orange instead of the usual blue

- DuggaSys/accessed.js
- Shared/css/style.css
https://github.com/HGustavs/LenaSYS/issues/7116
> Changed sort button styling

- Shared/css/style.css
> white header when editing gone

- Shared/css/style.css
Suggestion: Made it so when you are logged out, the icon is red. When you hover over it (to log in) it turns green. When you are logged in, the icon is green and when you hover over it it turns red. Fixes: https://github.com/HGustavs/LenaSYS/issues/7099
> Fix for #7099

- DuggaSys/codeviewer.js
https://github.com/HGustavs/LenaSYS/issues/7102
Moved the resize, reset and copy to clipboard buttons out of the if statement checking if the user has write access, making them available to all users.
Also cleaned up said if-statement a bit (it had 4 identical variable declarations)
> Fixed codeviewer buttons + cleaned the code a bit

- DuggaSys/resulted.js
- Shared/SortableTableLibrary/sortableTable.js
Our issues have the need of the same functionality but used differently so instead of redundancy we merge togheter the code.
> Merging togheter our branches because of needed code

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
#7075
Removed the application header from diagram.php and style.css since it is not used anymore.
Removed inline styling since it was redundant code and was not needed.
Fixed the position of the toolbar
Reduced toolbar width size
removed toolbar borders
> fixed vertical toolbar #7075

- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/7104
> Fix missing padding for the no access message in sectioned.php

- DuggaSys/sectioned.js
Fixes #7028 
An issue that showed error-messages related to swimlane in the sectioned-view.
Testsite: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/courseed.php
or branch GruppB2019W21#7028
> Swimlane error-fix

- Shared/SortableTableLibrary/sortableTable.js
> Fixed height of column in resulted

- DuggaSys/diagram.js
Fixed naming text objects for the issue: #7053
> Fixed naming text objects. Issue: #7053 

- DuggaSys/codeviewer.js
> CodeViewer: Fixed upload button again

- DuggaSys/templates/daily-minutes.js
- Shared/css/dugga.css
> Made upload button in mobile form same as in big form

- Shared/css/style.css
Pullrequest #6947 
Issue #6946 
Removed code that was not being used instead of just commenting out.
> Grupp b2019 w21#6946 

- DuggaSys/templates/daily-minutes.js
Also fixed row size when adding new row
Fixes #7085
> Daily minutes: Fixed form resetting when resizing

- DuggaSys/showDugga.php
> Fixed titles for Contribution and Daily minutes

- Shared/icons/file-upload-icon.svg
- Shared/icons/general_upload_button.svg
- Shared/navheader.php
https://github.com/HGustavs/LenaSYS/issues/7144
> Change file upload icon in navheader

- DuggaSys/contribution.js
- Shared/css/style.css
No longer clashing with the buttons.
> #7097 Fixed contribution text issues. 

- DuggaSys/duggaed.js
Should fix #7175
This can best be tested by going into datorgrafik and editing variants for the test "quiz". It should no longer throw an error on line 252(253 in this version).
> surrounding block with try and catch

- DuggaSys/diagram.js
Copying the TextBox works now
a16tobfr Edit: Issue #7169 has been fixed here as well since I needed this solution in order to fix the issue where copied objects should be named the same as the original
> Issue #7149 fixed. Copy of Textbox is working

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Fix for issue #6960
#7162 is not necessary anymore as that issue is solved here
> Removed transparency for objects, Fix for issue #6960

- Shared/css/style.css
Fixes #7095 
Made dropdown height auto and removed the scrollbar.
Does not seem to break anything in resulted.
> Fixed height and removed scrollbar for dropdowns in access and result

- DuggaSys/diagram.js
- DuggaSys/diagram.php
#6899 Zooming on center of screen works now. Additional changes to this is an implementation of a crosshair while in developer mode and a debug circle that can be drawn on any position where the developer wishes. This is intended to be used while developing. #6854 became an victim of this change as well because it was needed for solving this issue.
> Fix for #6899 Zooming on center of screen

- DuggaSys/diagram.js
Changed if statement to cover umllines, when it comes to drawing lines before symbol. https://github.com/HGustavs/LenaSYS/issues/7184
> changed if statement to accomdate umllines

- Shared/dugga.js
Fixes #6965 that concerned an error message when pressing escape in fileed, duggaed, resulted and accessed.
Testsite: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Second PR for escape-error

- DuggaSys/resulted.js
- DuggaSys/resultedservice.php
Reverted changes made from this pull request by request from henrik: 
https://github.com/HGustavs/LenaSYS/pull/6700
Fixes #6937
> reverted ssn, fixes ladexpport - Grupp b2019 w21#6937

- Shared/css/style.css
Fixes: #7109 
Do give feedback if there could be a better solution than this.
> Added slight gradient to navbar buttons in sectioned

- Shared/css/style.css
> removed width of dateSize

- DuggaSys/diagram.js
Issue #7186 fixed. Copy of the textbox works again.
> Issue #7186 Fixed. Copy of the text box

- DuggaSys/resulted.js
This fixes #6917 
Go to the issue for information about what this issue was.
Use branch GruppB2019W21#6917
> Fix for repetetive feedback

- Shared/navheader.php
> Grupp b2019 w21#7106

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
> Change course version #7079

- DuggaSys/resulted.js
- Shared/SortableTableLibrary/sortableTable.js
> Sorting grades in resulted #6876

- DuggaSys/diagram.php
Fix for issue #7126
Merge conflict resolved properly
> Added Ctrl+Z and Ctrl+Y to tooltip,  Fix for issue #7126

- DuggaSys/diagram.js
fix for https://github.com/HGustavs/LenaSYS/issues/6879
Removed if statement that unpresses linebutton after draw. Replaced uimode that calls for normal, and replaced with CreateLine
> removed unpressed, added uimode

- DuggaSys/accessed.js
- Shared/css/style.css
> Made style of dropdown in access conform to the ones in result

- DuggaSys/accessed.php
Fixes #5940 
Can finally merge this after Henriks last comment in https://github.com/HGustavs/LenaSYS/issues/6425
> Updated user import instructions

- DuggaSys/codeviewer.js
- Shared/css/codeviewer.css
> codeviewer: fix to make copy notification sticky

- DuggaSys/contribution.js
- DuggaSys/contribution.php
Soultion for issue #7134 . Removed the old table and changed it to a sortabletable. Also implemented a "user content check" that handels cases where users data dont have the same position in different databases.
> Removed the old "allrank table" and changed it to a sortabletable.

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Fix for issue #7161
Now menu doesn't close when toggling a4 settings
> Fix for a4 events, Fix for issue #7161

- install/install.php
> Use existing db password if it exist

- DuggaSys/duggaed.js
> Remove extra submission rows when opening variant editor

- DuggaSys/accessed.js
- Shared/dugga.js
https://github.com/HGustavs/LenaSYS/issues/6424
> Fixed Error when clicking FAB in access

- DuggaSys/accessed.js
- DuggaSys/accessedservice.php
> When logging out on access, browser will redirect to courseed

- Shared/navheader.php
Fix for issue https://github.com/HGustavs/LenaSYS/issues/7232
> Only show code editor edit options for superusers

- DuggaSys/duggaed.js
Fix for duggaED part of https://github.com/HGustavs/LenaSYS/issues/7019
> Slightly improve DuggaED title

- DuggaSys/accessed.js
- Shared/css/style.css
https://github.com/HGustavs/LenaSYS/issues/7123
> Fixed Reset PW button

- Shared/dugga.js
Fixes #7236 
Login box in codeviewer should now look like the rest of them..
> Removed 'alert' class from login error message

- DuggaSys/codeviewer.js
now possible to edit the name of a frame in codeviewer.php regardless of type. Previously only worked with code windows but now works with all :)
> #7237 now possible to edit title of document and preview type

- DuggaSys/showDugga.php
Fix for showDugga part of https://github.com/HGustavs/LenaSYS/issues/7019
> Show dugga name in page title (showDugga.php)

- DuggaSys/diagram.js
#6789 Draw grid now syncs with all symbols and works correct.
> Fix for #6789 Rework of drawGrid()

- DuggaSys/diagram.js
> Scrolling is reasonable in mozilla, Fix for issue #7255

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
> Fix for issue #7133: Lock icon should have a hover effect + changed tooltip 

- Shared/css/style.css
Courseed MOTD message  now is wrapping correctly.
test link; https://a16hiwah.webug.his.se:20002/DuggaSys/courseed.php
'efter'
> Courseed MOTD message is  wrapping correctly

- DuggaSys/profile.php
Fixes #7211 
Made it so that the divs align with each other and it should work on mobile now (atleast when i tested it with my phone and the debugger in chrome).
Link: https://a17oscno.gruppb.webug.his.se:20002/DuggaSys/profile.php
> Grupp b2019 w21#7211

- DuggaSys/accessed.js
- DuggaSys/accessedservice.php
Fixes #7251 
Now possible to add new users to a course in accessed. To do this, either use the 'create user' form or the 'import user' form, and put 'Registrerad' as status.
This PR validates the import and create user forms according to the constraints in the database:
- Class: Must be 10 characters or less (can be empty)
- First and Last name: Must be 50 characters or less (can be empty)
- SSN: Must be 20 characters or less (must be unique)
- Email: Must be 256 characters or less (can be empty)
If email is not empty:
- Must contain '@'
- Characters before '@' must be between 1 and 80 characters
- Characters before '@' (username) must be unique
> Added validation and error handling for user import/creation

- DuggaSys/diagram.js
- DuggaSys/diagram_IOHandler.js
Fix for issue #7141
Now serialnumbers are updated and reset properly
> Added serialnumbers for labeling objects, Fix for issue #7141

- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/7263
This can be tested by going to courseed and selecting Webbutveckling - Datorgrafik & then pressing the Random CSS dugga (in mobile mode)
EDIT: To clarify, the problem was that the text in the headers went outside the box, so you couldn't see the full text
> Remove fixed height on loginBoxHeader

- DuggaSys/contribution.js
- Shared/css/style.css
Contribution: When you press the contribution button, the content should now appear at the top of the page (just like it does when you press any of the other buttons on this page). Also added some styling. Fixed issue: https://github.com/HGustavs/LenaSYS/issues/7266
> Fix for #7266

- DuggaSys/codeviewer.js
Clicking outside any loginbox will now close it.
#437
Review tips: Open the cog Wheel in codeviewer and click outside the box when it's open.
> Added code for closing boxes on outside click in codeviewer.

- DuggaSys/diagram.js
#7139 Fixed this cursor issue for that I'm pretty sure got fixed way back. Could be nice if we don't overwrite code in the future.
> Fix for #7139 Wrong cursor when hovering point on locked object

- DuggaSys/diagram.js
Fix for issue #6613 probably solved grid issue
> Fix for issue #6613, grid issues

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- DuggaSys/resultedservice.php
- Shared/SQL/init_db.sql
fixes #4178.
You can now sort the table after examiner from the dropdown.
Test site: https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Added examiner dropdown to filter table

- DuggaSys/accessed.js
- DuggaSys/accessedservice.php
- DuggaSys/codeviewer.js
- DuggaSys/codeviewerService.php
- DuggaSys/fileed.js
- DuggaSys/fileedservice.php
- DuggaSys/sectioned.js
- DuggaSys/sectionedservice.php
- Shared/navheader.php
- Shared/sessions.php
Fixes #7262  
To make a student teacher, go to access editor and change 'Access' to Student teacher for a user you can log in with.
The user should be able to:
- Edit codeviewer titles and content
- Edit content of files in fileed
- Edit rows in accessed
- Create/Import users in accessed
- Edit items in sectioned
The user should not be able to:
- Navigate to resulted or duggaed
- Delete items in sectioned or fileed
- Upload files to fileed
> Added student teacher access type

- DuggaSys/codeviewer.js
Added support for the missing HTML tags listed in the issue https://github.com/HGustavs/LenaSYS/issues/7269
> Added support for the missing HTML tags listed in the issue.

- DuggaSys/resulted.js
- Shared/css/style.css
#7235 
Height is now consistent. Added "heights" in .resultTableCell.
> Grupp b2019 w21#7235

- DuggaSys/sectioned.js
Added red text in the swimlane for tests that are pending but turned in after deadline. 
Testsite: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/courseed.php
Testelev: s94sveri
PW: password
> Swimlane adjusted

- DuggaSys/sectioned.js
> Clicking Fab button in sectioned w21#7068

- DuggaSys/resulted.js
- Shared/css/style.css
- Shared/navheader.php
test link; https://a16hiwah.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
efter
> Resulted filtering drop-down out of position been fixed #7091

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
Issue: #7311
Fixed position after recent merger of issue: #6297 and added new hotkeys for grouping items.
**Co-Authored-By: @a16jenja**
> #7311 Fixed position and added new hotkeys

- DuggaSys/diagram.js
- DuggaSys/diagram_IOHandler.js
Fix for issue #7309
Better for saving settings in the future, to avoid having a separate item added to the localstorage.
> Replaced serialnumbers with settings array, Fix for issue #7309

- codeviewer_add_update_templates.md
md file that documents how to create new/update templates. Reference to: #7063
> Codeviewer: Added Documentation for updating/Adding new Templates

- DuggaSys/diagram.js
- DuggaSys/diagram.php
#7093 
You can now accept the change by pressing enter or cancel by pressing escape
> Fix for issue #7093: When changing modes you should be able to accept by clicking enter 

- DuggaSys/accessed.js
Fix for issue #7305.
This need to be tested on the test-server. The purple button does not appear on my local server...
> Fixed the button that appears more to the left.

- DuggaSys/contribution.js
Fix for issue #7328.
Removed magicHeading from all the tables on the contribution page..  Just waste of time to add a new issues to change 4 lines of code..
> Disabled magicHadings on the tables at the contribution page.

- DuggaSys/resulted.js
- Shared/SortableTableLibrary/sortableTable.js
> Sorting radion buttons. A more responsive #7240

- DuggaSys/resulted.js
- Shared/css/style.css
Reverts HGustavs/LenaSYS#7298
Have to revert this because it breaks the table style in resulted.
> Revert "Grupp b2019 w21#7235"
