HGustavs/LenaSYS

- DuggaSys/courseed.js
Get all courses after you have added new course, so you don't have to update site to see the newly added course.
> Fixed #558

- DuggaSys/courseed.php
The attribute "value" changed to "placeholder" so input field automaticly clears when you type in new values
> issue #736 - Input fields in "New Course" should clear default values automatically 

- Shared/css/whiteTheme.css
I have added more "air" in the layout.
I added padding to both classes: codeborder and normtextwrapper.
The numbers presenting line number and code example was very tight positioned against the edges. I then just added a little air between the edges.
> CodeViewer: Tight style #790

- index.php
index.php is located in the root directory, redirecting the user to the LenaSys-frontpage instead of showing the root file structure.
> #543 - Create index.php on root-directory.

- CodeViewer/codeviewer.js
- Shared/css/codeviewer.css
Added overflow control for the boxes in codeviewer, to make the information accessable even after resizing the boxes to small ones.
> Overflow control to codeviewer boxes. Issue#832

- Shared/navheader.php
Refactored how the "home" and "back" buttons work for all the groups. It relies on the $noup variable to see what the back button will link to.
Uses ternary operations.
> Refactor shared navhead to work with all groups

- Shared/loginlogout.php
- Shared/sessions.php
Added a new function called addlogintry();
What was missing was that the php never attempted to connect to the database when someone attempts to log in and failed, it only sent empty variables to nothing, so this was added.
@a13chrju was also working togheter with me
> Issue #594 and #731

- Shared/SQL/init_db.sql
This event should perform a weekly clear of the eventlog table. The eventlog table can grow to a great size and old information in that table may not be relevant after a long time. Moreover, for performance and storage space reasons, this event is also an optimization. #903
> Added a weekly event in the database, issue #903

- CodeViewer/EditorV50.php
- CodeViewer/codeviewer.js
- Shared/css/codeviewer.css
- Shared/css/template3.css
- Shared/css/whiteTheme.css
Functionality for resizing boxes for template 1-5.
Fixed the CSS for template 3 as it was just a copy of template 4.
Removed redundant overflow properties.
Removed a link to template1.css in EditorV50.php, that was overwriting the css for other templates when they are loaded. Causing them to display incorrect structure.
> Code view#840

- CodeViewer/codeviewer.js
- Shared/css/style.css
Changed the parser so that it uses the replace() function from javascript with regular expression as parameters, Instead of the previous functions.
This also makes the parser able to handle headings, and whitespace after markdown symbols better. The new function needs to be tested with a lot of different markdown inputs since I have not tested it all.
> Codeviewer#959 markdown headings

- DuggaSys/sectionedservice.php
Changed 'COURSE' to 'course' since mysql is case sensitive on our platform. issue #1085
> Fixed faulty sql query

- CodeViewer/codeviewer.js
- CodeViewer/descupload/test.txt
- Shared/css/codeviewer.css
The first pull-request was into master so this is a reopen of #1123.
#873
Using regular expression to replace certain symbols with html list tags.
For ordered lists type any integer value followed by a dot and then some text, e. g.
1. entry 1
2. entry 2
4. entry 3
For unordered lists type a line, followed by a space, followed by some text e.g.
entry 1
entry 2
If you are unsure if the input is parsed correctly try the same input here http://spec.commonmark.org/dingus/. If the our parser translates input differently it is regarded as unexpected behavior.
> Code view#873 markdown list

- CodeViewer/codeviewer.js
This update fixes the breaking windows caused by pixel based positioning, by exchanging measurments used for percentage based ones. This also fixes the first time experience of the resizable windows, due to used uninitialized variables the windows behaved very strangely for first time visitors. This should now be solved.
> Updates to Resizable windows!

- CodeViewer/codeviewer.js
Issue #828 
This changes makes it possible to print indentations in the code examples by using "tab" and not 4 spaces.
+ changed to follow the codestandard
> Codeviewer: #828  Print indentations

- CodeViewer/codeviewer.js
- Shared/css/codeviewer.css
Fixes issue #874 . Implements code blocks with markdown.
To test this, view example number 9 and edit the test.txt file located in the CodeViewer/descupload folder.
To make a code block use the markdown symbol: ~~~ before and after the code you want in the block.
Example:
\~~~
// Kommentar
var variabel = 5;
if(variabel == 5){
alert("Hej");
}
\~~~
> Code view#874 markdown code/text field

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- DuggaSys/sectionedservice.php
- Shared/SQL/init_db.sql
When a user creates a dugga list item, the user is now presented with the possibility of selecting how to count high scores. 
The database table 'listentries' was updated to include what kind of high score mode should be associated with a dugga, currently my thoughts are
0. None
1. Timer based
2. Click based
See issue #1265
> Highscore modes update

- CodeViewer/codeviewer.js
The code for code blocks with markdown has yet again disappeared so I'm adding it back in. This fixes issue [#1211](http://github.com/HGustavs/LenaSYS/issues/1211).
> Code blocks inclusion and bug fix

- DuggaSys/clickcounter.js
- DuggaSys/sectioned.js
- DuggaSys/showDugga.php
- DuggaSys/showDuggaservice.php
- DuggaSys/templates/dugga1.js
- DuggaSys/timer.js
This update allows the user to select between timer and click based highscores for dugga1.js. Both high score mode calculations are fully functional. Will be refactoring and updating more in next issue. 
See issue #1285
> Update high score modes

- Shared/css/codeviewer.css
#1314 
Just a small fix for the description box.
> Code View #1314: Description box alignment

- CodeViewer/codeviewer.js
- CodeViewer/editorService.php
#1301 
The openBoxID was not a global variable.
The main problem was that the list with codeexamples only read files that ended with .js before.
> Code view #1301   adding/removing imp rows

- DuggaSys/courseed.js
- DuggaSys/courseed.php
- DuggaSys/duggaed.php
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
Have changed the layout in the dialogs "new course", "edit course", "new version", "edit version", "edit item", "edit dugga" and "edit variant". All tables have been removed and instead added divs for the layout. Some new css for the new layout.
This is fix for issue #1303, #1305 and #1308
> Ds19#1303 - "edit course", "edit version" and "new verison" dialogs should be more UX-friendly

- CodeViewer/codeviewer.js
#1300
Add a function that replaces  the "< and the >" part of a tag with "&lt, and &gt". This will prevent the browser from rendering the them as html.
> Format html tags in quotes

- CodeViewer/codeviewer.js
Fix for issue #1378.
Removed extra whitespaces.
> Fix for broken markdown headings

- DuggaSys/accessed.php
- DuggaSys/courseed.php
- DuggaSys/duggaed.php
- DuggaSys/fileed.php
- DuggaSys/resulted.php
- DuggaSys/resultlisted.php
- DuggaSys/sectioned.php
- DuggaSys/showDugga.php
- DuggaSys/showdoc.php
The cookies and the "loginvar" variable were redundant as we have changed the processLogin and processLogout functions.
> Removed redundant cookies and use of the variable "loginvar"

- DuggaSys/courseed.php
- Shared/css/style.css
The courseed page now displays the current master branch hash on the bottom of the page. 
See issue #826
> Added "version" hash on courseed page

- CodeViewer/codeviewer.js
The wrong item in the array of information about the boxes had been chosen, which made it display a number instead of the boxtitle.
Only changed from item 3 to item 4 in that array to get the proper item.
> Updated createboxmenu function!

- Shared/css/responsive.css
- Shared/css/style.css
#1289 
* Codeexample title is now vertically centered
* The navigation buttons have "cursor: pointer".
* Codeexample title overflow is hidden
* Responsive title size.
* Removed unnessecary css for login button.
* The table in navheader is now the correct height (50px) instead of 54px.
> CodeViewer #1289: Title fix

- Shared/css/whiteTheme.css
A white gap shows up on the code border when viewing certain templates. 
Issue: [#1288](https://github.com/HGustavs/LenaSYS/issues/1288)
Fixed it by removing padding from normtextwrapper.
> Fixed white gap on the codeborder

- DuggaSys/showDugga.php
Now the timer doesn't start if the user is unknown to the course where the dugga is located.
> Show timer in dugga bug

- DuggaSys/courseed.php
This update changes the file loading code in the php section of courseed.php to check whether the git/ref/master file exists before loading it, if it doesn't exist then the php error won't be displayed but rather a message under the "master hash" string that states that the .git folder was missing.
See issue #1512
> Handle warning when .git folder is missing

- Shared/dugga.js
If the user inputs an invalid username or password combination and closes the loginbox, the next time the user opens the loginbox it will have been reset and the red color in the input box as well as the warning will have been cleared.
See issue #1220
> Loginbox reset

- CodeViewer/codeviewer.js
#870
Fixed a bug that caused the highlight of important words disappear from the description box.
> Codeviewer #820 Description Box Highlight Fix

- Shared/css/whiteTheme.css
#1589
Fixes words not being highlighted when moused over in the description box.
> Codeviewer #1589 Highlight Mouse Over Fix

- Shared/css/style.css
The font size on the class navHeading was defined as em instead of pixels. On lower resolutions, the text would scale up and cover the whole navHeader, hiding the loginButton. Instead of having a dynamic font size, we agreed to change it to  static pixel sixed. From 2.5em to 26px.
> #1577 - font size issue.

- CodeViewer/dragndrop.php
The dragndrop.php file loaded files that were already loaded, which made for some unstable behaviour with the resizing functionality of the page. The page would sometimes not recognize the function resizable from jQuery ui, this due to that the framework was redundantly loaded again. The problem did not persist after these deletions.
> Deleted redundant loading of files.

- Shared/css/template1.css
- Shared/css/template2.css
- Shared/css/template3.css
- Shared/css/template4.css
- Shared/css/template5.css
- Shared/css/template6.css
This makes all resizable boxes have a min and max size, which means they cant be resized into the edge of the screen. There will always be a minimum of 10% of one box showing.
> Cv22 #965 MinMax sizes on resizable boxes.

- CodeViewer/dragndrop.php
- CodeViewer/dragndropService.php
- Shared/css/codeviewer.css
- Shared/css/style.css
This is a fix for issues #1629, #1585 and #1478.
CSS added in codeviewer for the scroll, fixing the bug with scroll not enabling the dragging of example to boxes. Removed duplicate old css from style.css that messed up and overwrote the css from codeviewer.css. 
Fixed the issue where the beforeid got updated wrong and was set to the current example id instead of the example id before it.
> Cv22#drag and drop fixes

- Shared/SQL/testdata.sql
#1599
There where two occurences of the word appendChild, which caused som weird behavior.
> Codeviewer #1599 Important word exists twice

- CodeViewer/dragndrop.php
- CodeViewer/dragndropService.php
- Shared/css/codeviewer.css
This fixes the issues regarding error message when there is no sequence and the user is promoted to create a new sequence. It also resets the codeexample table if there is no sequences active, reverting it to its former, orginal structure where ever example is listet after eachother until the final example is reached.
> Cv#1651 and 1646

- DuggaSys/timer.js
With this update the dugga timer should stop immediately after a user has handed in a dugga. The code 'clearInterval(self.timer);' was not working for some reason and I don't know enough javascript to debug this without hassle so I just implemented a pretty naive solution which stops the timer updating the ui.
See issue #1634
> Dugga stops timer when handed in

- CodeViewer/codeviewer.js
Does as the title says, this updated version of the function now features checks before every action if it should be run or not.
The parent width have been changed to window width.
Now, if the window becomes smaller than 1100px the mobile theme triggers, and the layout of the site dramatically changes. This abolishes the need for the resizable functions, and this destroys those functions if they are found. However if the site later becomes bigger than 1100px it also reinitializes the resizeboxes function and makes the codeboxes resizable again.
> Disables resizable functions in mobile theme

- CodeViewer/dragndrop.js
Simple fix to popup the user a confirmation popup when he/she presses the delete button instead of just deleteing the sequence right off. Issue #1692
> cv#1692 - Confirm popup when deleting a sequence.

- Shared/css/style.css
- Shared/dugga.js
Prevents the user from dragging the draggable boxes outside of window-space. See #1702
> Draggable box boundaries

- DuggaSys/courseedservice.php
The fix ensures that you have to be logged in to see the different courses, but if you're not logged in you cannot see any course at all. A message telling you to log in wouldn't go amiss.
> Temporary fix, will probably have to be edited.

- Shared/markdown.js
Fixed issue where an extra blank codeblock was generated whenever a
codeblock was closed and did not have any code/spacing following it.
> grp2w14-issue-1775

- DuggaSys/filereceive_dugga.php
- DuggaSys/templates/generic_dugga_file_receive.js
added validation for links and that you can only add one "zip/rar" or "pdf" when the submit is of those types, when using type "multi", different and multiple files can be added at the same time. 
even when you are in submit type "pdf" you cannot add multiple pdf at the same time. The reason is that only the first pdf is previewed anyways, so if multiple files must be added at the same time, use the "multi" submit type instead.
> fixed issue 1920, and some things around it

- Shared/css/whiteTheme.css
Added this one line to fix the overlapping highlights (important words)
in codeviewer.
> Fixed issue #1323

- DuggaSys/duggaed.js
- DuggaSys/duggaedservice.php
- DuggaSys/sectioned.js
- DuggaSys/sectionedservice.php
- Shared/css/style.css
- Shared/getCookies.php
Pull Request for Issue #2174 
- Internet Explorer collapse bug solved, recognizing DOM elements with jQuery in IE
- Change duggaed page collapse system from _onlick_ on blankspace, to _onclick_ on arrows added to left hand side
- Ditch encryption for cookies as UID is no longer used to ident cookies, cookie ident is now: _username + cookie string + cid + course vers_
_dugged collapse_
_section collapse_
> [grp1w15]Fixing bugs for collapse system - #2174

- Shared/css/codeviewer.css
Markdown images were shown in bigger size than thumbnail, all images
should be thumbnail size at first glimpse. Therefore this code could be
deleted.
> Fixed issue 2237

- DuggaSys/sectioned.js
Fixes that item type 'link' can't be updated in the section page.
> Fix link issue on update item

- DuggaSys/showdoc.php
- Shared/markdown.js
Changed the code so it would be able to handle stuff between numbered
lists without breaking the couting sequence. Also changed how lists are
implemented. This also fixes sublists for an ordered list. Added to
JavaScript and PHP.
(###) To start an ordered list.
1. Hi (number, dot, space, and content to start couting sequence).
(/###) To end an ordered list.
To create sublists just start a list within another list.
> Fixed issue #1938

- Shared/allowCookiesForUser.php
- Shared/dugga.js
- Shared/sessions.php
Fixed the mainfunctionality that was asked for in https://github.com/HGustavs/LenaSYS/issues/1864. However, it is only a "window.confirm" right now because i did not know how to properly implement a custom made roll-down for this particular problem.
The issue is that the cookie-check is done when its known that a real user logged in. In window.confirm you can not continue after the login if you do not interact with the dialog at first. But with a custom made dialog I do not know how the implement the same idea in a clean way. You would be able to ignore the dialog and continue like nothing happened
> Grp1w18 issue1864

- Shared/dugga.js
cancel button on cookiedialog was not logging out on some browsers/machines. the issue was problably that location.reload() was called while a ajax call executed in processLogout()
> issue1864 fix

- DuggaSys/forum.js
- DuggaSys/forumEditor.php
- DuggaSys/thread.php
- Shared/css/style.css
This change was necessary to support potentially having two editors on the same page (for example when you want to edit a thread).
> Editor now uses classes instead of id.

- DuggaSys/sectioned.js
fixed so the scan for a matching version for the variable "coursevers" is done beforehand. So now the user is presented with text that says that the version does not exist if the value is null or no matching version were found https://github.com/HGustavs/LenaSYS/issues/2369
> fixed issue2369

- DuggaSys/sectioned.js
added an if-statement that ensured that the "create new version" dialog is only shown if writeaccess is present when the courseversion does not exist https://github.com/HGustavs/LenaSYS/issues/2368
> fixed issue 2368

- Shared/SQL/testdata.sql
This is only for the description box. The code box was more complicated.
fix for PHP example file not found #2527
> Added testdata for PHP Example 2

- Shared/SQL/testdata.sql
As commented on issue #2535, there were two testdata courses with the id Datorns grunder, which created a conflict. Decided to delete one of the course since it's unnecessary to have duplicate courses. The course deleted is DA121G.
> Removed course DA121G(datorns grunder), fix for issue #2535

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Changed diagram.js and diagram.php so that mousepos is working correctly for chrome,edge and firefox
> Fixed #2580 - correct mousepos for chrome,edge and

- DuggaSys/codeviewer.js
Playlink now uses the correct path when using courses
> Corrected path for playlink

- DuggaSys/codeviewer.js
It is not possible to change to a title with 'åäö' in code editor and see the correct name when changing title later.
> Fixed correct output of special chars in textfields for 'Section Title' and 'Title'.

- DuggaSys/codeviewer.php
This should now show the editing window without textfield sticking out to the right.
> Fixed window size.

- DuggaSys/courseed.js
Makes it possible to add new list entry with ' (for example Erik's course) without breaking the edit or setting icon, which used to not work when using '.
> Enables list entry with '-character

- DuggaSys/fileed.js
The styling of the file-upload has been changed to match the collapsable
sections in "sectioned". Old toggle-function has been removed to be
replaced with Jquery. The arrows in the header are clickable with a
pointer as cursor. The animation doesnt match because "slideToggle"
doesn't work on tables. A part of issue #1867
> Styling of file-upload to match "sectioned"

- Shared/SQL/changes.txt
- Shared/SQL/init_db.sql
A column with the name comment was added to the database. The reason is because #2615 needs to store the comment in the database.
> A column was added to the database

- DuggaSys/resultedservice.php
Due to stricter control by mysql, the query did not execute.
> Fixed invalid mysql call

- DuggaSys/sectioned.js
The arrows indicating the section is collapsable are fixed. Now there is
different arrows depending on if the section is collapsed or not.
This is also connected to issue #2674
> Arrows fixed to toggle

- DuggaSys/diagram.js
Fixed so lines are rendered before other objects, so they are always behind
> Fixed-#2607

- DuggaSys/diagram.js
By mistake a earlier merge from local branches removed 4 lines of code, that removed the "crosses" when deleted object, added them again
> Small-bug-fix-#2736

- DuggaSys/fileed.js
The content collapsed when you clicked "Add File" in the file-upload
page. This bug is now fixed using Jquery's "stopPropagation();".
Part of issue #2434
> Fixed bug in "fileed.js"

- DuggaSys/fileed.js
The arrows were misplaced. This is now fixed by declaring them after the
title of the header instead of before. Solution for issue #2873
> Fixed placement of arrows in fileed

- Shared/sessions.php
When a user enters their answer to the security question in forgot password will no longer care wheter or not the user uses lower or upper case. This is by making the check to the database into lowercase. #2828
> Fixed so that the security question answer is not case sensetive

- DuggaSys/sectioned.js
A function is added to prevent content from collapsing when clicking the
cog-wheel in "moment" or "section".
Solution for issue #2909
> Prevent collapse when clicking icons

- DuggaSys/templates/PHP_Ex2.txt
- Shared/markdown.js
fixing issue #2808. 
Markdown is now correct for ordered and unordered lists. critical changes are made in functions handleUnorderedList() and handleOrderedList()
> fixing bug in unordered and ordered list regarding sublisting.

- DuggaSys/diagram.js
Fixes issue #2970 and also makes eraseSelectedObject run the eraseObject function instead of directly calling upon object.erase(), resulting in consistency when running the different delete functions.
> Fixe for issue #2970

- DuggaSys/profile.php
- Shared/css/style.css
The styling of the profile page has been changed. A field has been added where you can enter an answer to the challenge question. A field for entering a new password again has also been added.
To be able to change either the challenge question or the password a field has been added where you have to enter the current password.
This commit only contain styling/design fixes so no functionality has been added. (Partially related to issue #2638)
> Changed styling of profile page

- DuggaSys/diagram.js
Users can now only choose from a predefined list of colors when changing the text inside an object.
> Dropdown list for text color

- DuggaSys/sectioned.php
Limits the number of characters allowed in the version id field when creating a new course version.
> maxlength='8' set on the version input field.

- DuggaSys/sectionedservice.php
Stop lights now displays correct for duggas. If grade is pass - green, if fail - red. If not marked - yellow.
> Stop light logic is not correct for moment that has duggas

- DuggaSys/fileed.js
- DuggaSys/fileed.php
Removed code that shows icon for filter since customer no longer wants to filter but to search in table (another issue). Also added the function to be executed on load of fileed.php so the icon now shows up. You can view the change in my folder on the testsite.
This is only a partfix for 2775. Do not close the issue.
> Show sort icon onload - fileed sort

- DuggaSys/codeviewer.js
Probably fixed tokenizer not being able to recognize for example #34edaf (two numbers and an 'e') as a colour in certain situations.
> W16 issue 1888 a15emibo

- Shared/dugga.js
It will later be used by grouped.js, which will be changed in a later issue.
> Added a new kind in the else if-case in dugga.js

- DuggaSys/grouped.js
The change were made to make the grouped.js work after the changes in Pull Request #3082 were made. The grouped.js is now using grouedservice.php instead of resultedservice.php
> Changed the AJAXSERVICE and name on function in grouped.js

- DuggaSys/duggaed.js
- Shared/css/style.css
Since there was some problems during the previous merge I'm doing another pull request.
The user should now be able to show/hide variants when the arrow button is clicked in the dugga editor. New variants and deleted variants should now also cause the the corresponding dugga to give feedback to the user by showing that a variant has been added or deleted in the table.
> #2931(repulling) Added functionality to show/hide a variant 

- DuggaSys/duggaed.js
- Shared/css/style.css
Dropdown icon should now only be displayed on the rows that have a variant to show in the dugga editor. Icon now also changes when clicked upon to give feedback.
> #3027 Properly display dropdown icon in the dugga editor

- DuggaSys/templates/PHP_Ex2.txt
- Shared/markdown.js
Solution for the bug and now its working properly now and a breakline is not needed at the end of lists.
> Fix for issue #2983 regarding breakline after ending lists

- DuggaSys/accessedservice.php
- Shared/sessions.php
- install/SQL/init_db.sql
Fixes issue #1964 .
Will improve security of the system by replacing outdated functions.
The fix will slowly update any old passwords when people log in to be in the new standard.
> Use PHP's password_hash and related function instead of MYSQL password

- DuggaSys/sectioned.js
The page now refreshes when an item is added. It makes it able to update
an item directly after adding it, instead of after refreshing
the page manually. Solution for issue #3168
> Refresh page after adding an item

- DuggaSys/grouped.js
- Shared/css/style.css
Numbers are now displayed to the left of the students. It will make it easier for teachers to know how many groups there are.
> Added numbers to the left of students in grouped.php

- DuggaSys/profile.php
- Shared/dugga.js
If for example a security question is not found, a error message will be displayed and red color will highlight the error.
> Added error message to the profile page for security question

- Shared/navheader.php
The cookie message is now only shown once after you press the OK-button. (Fix for issue #2769)
> Cookie message only shown once

- DuggaSys/sectioned.php
Delete and Save buttons are now shown instead of Cancel and Submit if the cog wheel is clicked after an object is created with FAB or New Item. (Fix for issue #3256)
> Made Delete and Save buttons show correctly after an object is created.

- Shared/css/style.css
The FAB is now moved up a bit to not end up too close to the cookie message (if the cookie message is not closed before). (Issue #3264)
> Moved the FAB up a bit

- errorpages/404.php
The 404-page now has an error message. The error message is displayed in the header as before but without "h1" tags.
> 404-text updated

- DuggaSys/codeviewer.js
- DuggaSys/codeviewerService.php
Playbutton will now be grayed out if the playlink is empty or if the file does not exists.
Also fixed the behavior of the playbutton when clicked. The page will now redirect based on if the file is global or not.
> Playbutton is grayed out if there's no playlink and also redirects correctly

- Shared/css/style.css
Changed the mouse pointer from a marking  pointer to a "finger"-pointer when hovering over the X to close swimlane.
> Swimlane close button - changed pointer when hoover

- Shared/dugga.js
- Shared/loginbox.php
- Shared/loginlogout.php
- Shared/sessions.php
A notification window is now displayed whicn prompts the user to set a challenge question if it's not set. If it is already set no window will appear.
Solves the issue #2826
> #2826 Force users to set a security question

- Shared/css/style.css
Added padding to the FAB to get '+' aligned in the center. (Fix for issue #3296)
> Adjusted '+' to the center of FAB

- Shared/dugga.js
The underlayer(grey background) will now be shown when the pop-up window that makes the user to set a security question on login is shown. The underlayer will disappear when the pop-up window is closed.
> Made the grey background show when the security question pop up is shown

- Shared/dugga.js
This will be used for issue #2638. The function checks if the user is on HTTPS and by doing that we can allow certain functionality only for users on HTTPS (such as changing password).
> Added function to check if user is on HTTPS

- Shared/sessions.php
Fixes #3329 the fix however is not that clear since if the user is a superuser/teacher they should not get a popup to set a security question, in the code however it checks this criterion but returns that the user has a question "set" which is a lie.
> Fixed so the reminder that the user needs to set a security question wont affect teachers/superusers

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
The forms in Edit variant is now filled in (if you have a JSON-string) when the box is opened so that you don't have to fill it all in again. Fix for issue #3266.
> Forms in Edit variant filled in

- DuggaSys/diagram.php
Temporarily fixes the problem with clearing hash. Clicking remove hash and delete all, now runs both functions to make sure that the hash gets cleared.
> Temporary fix of Hash Removal

- DuggaSys/fileed.js
In fileed, the 2 last tables there was an incorrect closing of span tags. I added a "/" to 2 spans tags. 
Previously there was a strange transistion, issue #3351, in the tables when collapsing but is now fixed.
Issue is fixed if your review is ok. You can see the result at my testfolder.
> Added correct closing of span tags in fileed

- Shared/css/style.css
Commented out the line for border radius in the .hidden class, this was
the cause of the ugly CSS on the site in Chrome.
> fix for issue #3364

- DuggaSys/showdoc.php
adding function parseLineByLine() and identifier() that handle line by line parsing (equivalent to parseLineByLine() in markdown.js)
> #2631 adding line by line parsing in showdoc.php

- DuggaSys/codeviewer.php
the width of the box didn’t match the frame size
> Changed the width of the Edit box

- DuggaSys/diagram.js
All changes made in dialogue box is saved so when the user double click the symbol they can see the choices they've made.
> Fix for issue #3088

- DuggaSys/diagram.js
The zoom function is now fixed, and the mouse point is also fixed. You can now zoom in and out without any problems. When zoomed in, you can press and move any figure or symbol that you want.
> Fix for issues #3365 and  #3270

- DuggaSys/accessed.php
- DuggaSys/codeviewer.php
- DuggaSys/diagram.php
- DuggaSys/duggaed.php
- DuggaSys/fileed.php
- DuggaSys/resulted.php
- DuggaSys/sectioned.php
- DuggaSys/showDugga.php
- DuggaSys/templates/3d-dugga.html
- DuggaSys/templates/XMLAPI_report1.html
- DuggaSys/templates/bit-dugga.html
- DuggaSys/templates/boxmodell.html
- DuggaSys/templates/color-dugga.html
- DuggaSys/templates/curve-dugga.html
- DuggaSys/templates/dugga1.html
- DuggaSys/templates/dugga2.html
- DuggaSys/templates/dugga3.html
- DuggaSys/templates/dugga4.html
- DuggaSys/templates/dugga5.html
- DuggaSys/templates/feedback_dugga.html
- DuggaSys/templates/generic_dugga_file_receive.html
- DuggaSys/templates/html_css_dugga.html
- DuggaSys/templates/html_css_dugga_light.html
- DuggaSys/templates/shapes-dugga.html
- Shared/loginbox.php
All popup windows should now have the cursor 'pointer' on the x, when closing the popup. I added a generic CSS class in style.css called cursorPointer and added class='cursorPointer' to all popup windows closing button.
> Fix for issue 3144 - changed cursor in all popup windows to 'pointer' on the closing button

- DuggaSys/diagram.js
"Delete All"-button now removes the information about the crosses, but doesn't remove the poistion in the array.
> Fix for issue #3442

- Shared/dugga.js
Fixes issue #3469
To test this, open the frontpage of LenaSYS, open the javascript console and run randomstring() several times, before the update it often gave strings with less than 9 characters
> Generate a consistent number of characters in the randomstring function.

- install/install.php
It takes a level argument, and working the same as the PHP7's version of dirname(path, level).
For usage without a level argument, use the PHP dirname(path) function, which works prior to the PHP7 version.
> Made a version of dirname which is PHP5 compatible

- DuggaSys/codeviewer.php
- DuggaSys/showDugga.php
- DuggaSys/templates/dugga3.html
- DuggaSys/templates/shapes-dugga.html
- DuggaSys/testDugga.php
All popup boxes should now have the correct cursor when the close button is hovered over. Fixes #3452
> Add cursorPointer class to remaining popup boxes

- DuggaSys/diagram.js
- DuggaSys/diagram_symbol.js
Created a difference betwen how a figure and a symbol is erase, which solves the bug when using the delete object function to delete figures.
Also added a global standard line-width for all drawn objects, the result is a bit cleaner diagram.
> Fix for issue #3498

- DuggaSys/filereceive.php
- DuggaSys/showdoc.php
Autodetect extension of file if a case has not been implemented yet. This allows certain browsers, e.g Safari, to download these files. 
Also corrected a minor error where "filesize" was misspelled.
> Autodetect extension of file

- DuggaSys/sectioned.js
Now the button works in 'Webbprogrammering' as well, which it didn't before.
> Show/hide button working in 'Webbprogrammering'

- .gitignore
- Shared/css/style.css
- Shared/dugga.js
- Shared/loginbox.php
- Shared/loginlogout.php
A user now has the option to refresh the current session when timeout is imminent without having to manually relog. Furthermore, the timeout funtion whic is called when the session HAS expired is now styled in the same manner as the expire div. Additionally the page is reloaded automatically.
> Additional session expiration functionality

- DuggaSys/filereceive.php
DuggaSys/filereceived.php now uses mime_content_type function instead of file['type'] to determine MIME type of uploaded files. A few new types were added to whitelist. File changed is used when uploading files to LenaSYS.
> 3384 mime_content_type

- DuggaSys/showdoc.php
- DuggaSys/templates/unordered-list.md
implementing support for unordered lists in showdoc.php aswell as removing old (not working) logic. Now parsing is handled line by line with the functions parseLineByLine() and identifier()
> Week18 #3188 d15johro a15ramha

- DuggaSys/fileed.js
The table headers were hopping before on collapse/expanding in fileed. Fixed with setting a fixed width on th tags with inline styleing on all tables. 
This should solve issue #3446.
This should probably later be fixed with flexbox to be mobile friendly.
> Fixed hopping table header on collapse in fileed

- DuggaSys/diagram.js
- DuggaSys/diagram_symbol.js
When weak is selected, an extra border appears around the figure to signify the weakness of the relation.
> Fix for issue #3355

- DuggaSys/fileed.js
The tables in file view will now sort on single click, based on what column was pressed, while a double click will result in the table collapsing. All tables are sortable and all tables can collapse.
Closes issue #3277
> Added sorting to file view on click and collapse on double click

- DuggaSys/diagram.js
Object's top left corner now snap to the grid that is drawn. I attempted comparing the two corners bottom right and top left in order to decide which one to snap to the grid, but it was deemed unsuccessful as it lowered the overall quality.
Suggestion for new issues:
* The grid is not drawn properly (bug)
- When navigating far outside the start position in the canvas, the grid is no longer drawn
* Snap a group of objects to grid
> Issue#3097

- DuggaSys/sectioned.php
The box position is wrong. It should be lower because right now it cant be closed because the X cant be pressed.
> Edit section box position

- DuggaSys/diagram.js
Added event listners for touch. Tried it on a android 5.0 device with chrome as browser.
Now it at least tries to move the attributes and entitys etc. But almost nothing is actually working as expected on phone. The scaling isn't working. The canvas element scales down aka the boarder fits on the screen, but the diagram it self doesn't scale down very well.
> Added Event listners for touch

- DuggaSys/diagram.js
Relation gets standard size even if a selection is made bigger or smaller than default size.
> #3621 - Size of relation is fixed.

- DuggaSys/diagram.js
Settings are saved when the user doubleclick the relation symbol to re-open dialogue box.
> Fix for issue #3564

- Shared/css/style.css
The button will now disappear when you zoom in (as for small screens), and it won't block the content.
> Fix for issue #3576

- DuggaSys/diagram.js
Currently we only store localdiagram without any numbers, that's why "localdiagram" + i did not work. If we however start storing localdiagrams with numbers we would have to revert this change.
> Fix for removeLocal()

- DuggaSys/resulted.js
The magic heading now stays visible after the content has been filtered
in the result-view.
Solves issue #3655
> Magic heading now stays visible after filter

- DuggaSys/showdoc.php
- DuggaSys/templates/PHP_Ex2.txt
- Shared/markdown.js
- install/md/parsing.md
markdown.js and showdoc.php now support dashes when creating unordered lists in markdown. solving issue #3626
> fixing bug markdown bug #3626

- install/install.php
Now the progress is only collapsed if no errors occured during installation. If there was an error it wont collapse.
> Install progress only collapsed when no errors.

- Shared/css/style.css
Now the scrollbar will always be there so the tables won't hop when collapsing. 
I added overflow-y:scroll to body.
This solves is #3704 .
> Added overflow-y scroll to body

- DuggaSys/templates/PHP_Ex2.txt
- Shared/markdown.js
Issue #3059 
Implementing support for nesting unordered and ordered lists in markdown.js. 
Do not close this branch or issue after merging since it's only partially fixed. Same logic will be implemented in showdoc.php
> Week19 #3059 support for mixing nested sublists in markdown.js

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_mouse.js
- DuggaSys/forms/attribute_appearance.php
- DuggaSys/forms/class_appearance.php
- DuggaSys/forms/entity_appearance.php
- DuggaSys/forms/relation_appearance.php
#3766: Cuts out the dialog window functionality into a seperate javascript file.
#3733:
Created a function for loading the forms with a simple AJAX-script.
This also gives the editing within the diagram more visual feedback. It laso removes a lot of redundant code by making functions more streamline.
ID:s and inner variables AttributeType, EntityType and RelationType have been removed and replaced with "object_type".
Fixed a bug where double-clicking anywhere in the diagram (that isn't an object) causes an error.
> Issue #3733 & #3766

- DuggaSys/grouped.js
- DuggaSys/groupedservice.php
Groups were tied a listentry in issue #3674 and #3685, which the group editor now reflects by only having the available groups showing up in the dropdown lists per listentry. 
Some JSON comments were also included in the code to clarify all the looping going on, this is possibly redundant. Not sure there.
> Made groups assigned to a listentry appear under that listentry only

- Shared/css/style.css
- Shared/loginbox.php
The remember me function is now removed. This is replaced by #1846 so the browser is remembering the login. So the remember me function is not needed. 
Solves issue: #920
> Remove remeber me from loginbox

- DuggaSys/grouped.js
- DuggaSys/grouped.php
The moments in the dropdown in Manage Groups on the Groups page is now getting the names dynamically. Fix for issue #3786.
> Manage groups moments update automatically

- DuggaSys/forms/line-thickness_appearance.php
The line thickness option do not longer overlap the dialogue window.
> Fix for issue #3842

- DuggaSys/sectioned.js
The arrows now toggle correctly in sectioned. If a section is already
hidden when you collapse all content the arrow stays to show it's
hidden.
Solves issue #3836
> Arrows now toggle correctly in sectioned

- DuggaSys/fileed.js
Is #3448 wants only one icon to be showed at one time in the transition when collapsing och compacting the tables. 
Added a jQuery .delay so both icons is not visible at the same time. This would make the table headers hop.
You can see the result at my folder in fileed.
Note that the icon transistion is only runned when you dblclick on the icon. This got strangely changed last week although no code for the toggle whas changed. I think we should add a issue for that.
> when collapsing tables in fileed now only one icon is showed at a time

- install/install.php
Pressing enter to move on in installation should now work on different browsers in different operating systems.
> Enter now works in Linux and Windows

- DuggaSys/diagram_symbol.js
The center line in the forced relation is now always white.
> Issue #3945 - Fix global line color regarding forced relationships.

- DuggaSys/sectioned.js
When window is re-sized down it transforms and still keep a position to the left. Solves issue #3938
> Now Show/hide all transforms properly

- DuggaSys/sectioned.js
The Show/hide all button know collapses and shows all section with the
same animation as if a single section is collapsed. Instead of hide and
show there is slideUp and slideDown.
Solves issue #3911
> Same animation for toggling content in sectioned

- DuggaSys/grouped.js
- DuggaSys/groupedservice.php
Fixed an error that would make only one group appear in the dropdown under each listentry, even though in the database more groups were available for that listentry. Now all available groups per listentry is displayed in the dropdowns.
> Made all groups available in the dropdown per listentry

- DuggaSys/sectioned.js
The animation on the arrows for showing collapsed or open content is
fixed. It's now consistent with the rest.
Solves issue #3966
> Fixed animation on arrows in sectioned

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_toolbox.js
- Shared/css/style.css
This issue is not yet finished, since it requires a solution for mobile.
Implements Issue#3743 for PCs. Tried to maintain the cohesive design, but does have some minor differences that will be changed at a later date.
It is worth noting that some buttons don't have a place within the toolbox yet, such as the delete and change appearance functions. The delete function, alongside the change appearance function, will likely be moved within the layers toolbox. See issue #3750 for the issue tackling layers.
I suggest moving the global change appearance function into the edit drop down menu.
> PC mode - Issue#3743

- DuggaSys/sectioned.js
- Shared/css/style.css
If student doesn't belong to a group the text "(No group)" should appear instead of the groupname. If you hover over the text a message should appear. Fix for #3974.
> Added "(No group)" and hover text

- install/SQL/changes.txt
- install/SQL/init_db.sql
Changed 'name' in 'usergroup' table to be not unique anymore. The reason is because usergroups are connected to lid(listentry id)  and therefore it should be possible to have the same name on groups, but the groups still need to have different lid to be able to have the same name. If 'name' would be unique it would not be possible to have 2 groups with the name 'A' for example. It is not needed to change PRIMARY KEY in 'usergroup' table. (Fixes issue #3963)
> Makes 'name' in usergroup not UNIQUE

- Shared/dugga.js
Previously the preview has used the preview button to preview the uploaded file and clicking on the name of the uploaded file would give a link to the file in a separate window. A switch between these links was suggested and have been implemented in this pull request.
> Fix for issue #3601 - switched link to preview of uploaded file from preview button to file link and vice versa

- DuggaSys/showdoc.php
- DuggaSys/templates/PHP_Ex2.txt
- Shared/markdown.js
Changed syntax for tables to eliminate the breakline issue from tables. #3964
> The breakline issue in markdown.js and showdoc.php is now fixed

- DuggaSys/grouped.js
This allows the user to change the group assignment one more time after the first time, without
having to refreshing the page. This is achieved by updating the ID of the changed element (and those are later thrown into the service file for database update)
> Made it possible to change a group assignment dropdown twice

- DuggaSys/groupedservice.php
Those colons are really needed here
> Added colons to two lines binding params to a query

- DuggaSys/grouped.js
- DuggaSys/grouped.php
- DuggaSys/groupedservice.php
New groups are now able to be created with 'Manage Groups'. The groups can either have capital letters or numbers as names. The teacher that makes groups will not have to name all groups, the names will be created automatically.(Fixes issue #3675 )
> Made it possible to create new groups with 'Manage groups'

- DuggaSys/grouped.js
There was a bug where the sorting stops working if filtering has been done, the sorting only broke if the moments was shown in a different order than it was default. For example, if Biträkningsdugga is not shown the table will still be sorting on that moment because it was shown as the first moment as default. This commit solves that bug which makes the sorting work if some moments are filtered and not shown.(Fixes issue #4028)
> Makes the sorting work if filtering has been done in grouped.php

- DuggaSys/codeviewer.js
Playlink opens up a new page upon viewing an example. issue#1914.
> Upon pressing play link, a new page opens

- DuggaSys/grouped.js
- DuggaSys/grouped.php
Added a check to see if the user tries to add more groups than there are capital letters. If a user tries to add more groups a pop-up will appear. This makes it not create groups with weird names like "[" or "/". (Fixes issue #4037)
> Created a limit on how many new groups can be added with letters as name

- DuggaSys/resulted.js
Change offset to +15 instead of -10 making the magic heading appear as
soon as the header text dissapears on the screen.
> Changed offset value to make the magic headings appear earlier.

- DuggaSys/templates/PHP_Ex2.txt
- Shared/markdown.js
The markdown.js tables support those styles
Please do not close issue! #2648
> markdown.js now supports styles in tables which are bold, italic and code.

- DuggaSys/diagram_symbol.js
The text in attribute and entity will no longer go outside the borders. Partial fix for the issue. Still not fully fixed.
> Partial fix for issue #3864

- DuggaSys/grouped.js
- DuggaSys/grouped.php
- DuggaSys/groupedservice.php
- Shared/css/style.css
A new button has been added which is called 'Remove Button' where it is possible to remove  groups that have been created. Some changes has also been made to 'Manage Groups' which now is called 'New Groups' instead. It makes more sense to have two different buttons for create and remove groups and therefore don't show create groups and remove groups at the same time. Some functions in the grouped.js have changed names to make it easier to understand what they do. (Fixes issue #4051)
> It is now possible to remove groups in grouped.php

- Shared/css/style.css
There was a set height for ALL inputs in the LenaSYS. Removed this hardcoded input height enforcement.
There were none set for input tags at start of the project. This made the filter menu in resulted and grouped look bad, but i fixed it!
> Removed the static height of input element of 26px

- DuggaSys/diagram.php
- Shared/css/style.css
"Move canvas"-button is moved to the top right corner of the canvas.
> Fix for issue #4083

- DuggaSys/showdoc.php
- lenasys-markdown.txt
showdoc.php now support table styles according to markdown cheatsheet 
Please do not delete issue but you can delete the branch! #3193
> showdoc.php now supports table styles according to markdown cheatsheet

- Shared/navheader.php
The dropdownlist that appears when mouse hover over Funnel icon will now disappear when the mouse hover over Back-button in navheader. This does mean that the dropdownlist will not be shown incorrectly anymore. The same issue was also present in resulted.php but it will also be solved with this change.(Fixes issue #4063)
> Dropdownlist will be hidden if mouse hover Back-button in grouped.php

- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_figure.js
- DuggaSys/diagram_mouse.js
Removed line 304 because this line calls the function to show apperancedialogmenu.
> B16ponpe g2 4248

- DuggaSys/diagram_figure.js
- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
The issue is solved. Changed the default color for the symbols and figures. The default background color is now white, and the line color is black. Also changed the line width for all objects to 2.
On line 554, the lineWidth is multiplied by 2. This is because some objects automatically get half the line width otherwise.
> Changed the default color and line width

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Made dialogbox showup to fix #4286
_"Used the same type and style of fix to the dialogbox as in #4097."_
> #4286 DuggaED: CRUD-operations should show a confirmation before executing.

- DuggaSys/sectioned.js
#4308 - Issue has been solved by moving the functions getHiddenElements() and hideCollapsedMenus() so they are not called before the elements that should be hidden have been created.
People who worked on this issue: b16linra, a14oliri.
> #4308 - On branch #4181, the state of collapsed menus are not always remembered

- DuggaSys/resulted.js
Issue #4228 
Hiding the images for grades/changing grades when mini mode is checked in the filter menu.
> Hide marking grades in mini mode

- DuggaSys/diagram.js
This is a fix for the issue #4364.
The fix is done by looping through the objects backwards when checking if an object is being clicked.
> The top object is now selected when objects are stacked

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
Added a tooltip that pops up next to the "name" input box whenever the user types an invalid character. This design was implemented in both Duggaed and Sectioned.
> #4366 - SectionEd/DuggaEd: Explain why a title is invalid

- DuggaSys/sectioned.php
- Shared/dugga.js
#4381 - The fault was that the save-button was hidden and never shown again. This was fixed by adding the showButton() function to escape-press-event and also after creating a new item.
This issue was solved by @a14oliri and @b16linra.
> #4381 - SectionEd: Duplicating items when going from hidden to public 

- DuggaSys/diagram.js
- DuggaSys/diagram_mouse.js
I enabled that when the flag ctrlIsClicked is active and an item is already selected we de-select it. We had a bug that all functions pushing to selected_objects didn't check if the item already was in selected_objects which made the list contain alot of duplicates, this caused alot of bugs.
This is a solution for Issue #4345
> Possible to de-select items with ctrl/cmd-key

- DuggaSys/diagram.js
- Shared/css/style.css
To toggle movearound with spacebar works as intended. Icon shows only when active and clicking on a createbutton disables the movearound-function and hides the icon.
I have deactivated spacebars default functionality because if a button is marked and you press sapcebar the button is clicked. This causes toggle of movearound to not work.
This is a solution to Issue #4306
> Spacebar works correctly to toggle movearound

- DuggaSys/diagram.js
- DuggaSys/diagram_symbol.js
Added code in function draw in diagram_symbol.js. 
Created filled circle where you are able to resize the symbol. 
Solution for issue #4201
> Highlighting points when targeted, makes it easier to resize

- DuggaSys/sectioned.js
When editing a header that exists the box said New Item, this is changed so that the box says Edit Item.
> Issue solved, New Item is changed to Edit Item for a already created Header in sectioned #4446

- DuggaSys/sectioned.js
#4407 
Arrows toggle correctly when collapsing menus. This was fixed by rewriting the saveArrowIds() function.
The problem was probably caused by the structure of the elements being changed.
People who worked on this issue: @b16linra, @a14oliri
> #4407 - SectionEd: CollapsableMenu-Arrow-Icon no longer works 

- Shared/css/style.css
Issue discription:
When an admin is logged in at the courseed site the cogwheel for a course has a shadow, this should be removed.
Solution:
removed the box shadow for the trashcan and cogwheel icons
> #4428 remove the shadow around the cogwheel and trashcan icon

- DuggaSys/diagram_symbol.js
Changed the movePoints function so the line points dosn't get set to empty strings since some sybols share the same points, so that relations doesn't get removed whenever a line connected to it is removed.
This is a fix for Issue #4379
> G2-a16timsc-4379

- Shared/dugga.js
#4515 
Issue fixed by adding a function to escape-press-event-handler.
People who worked on this issue @a14oliri and @b16linra
> #4515 -  SectionEd: Yellow border not removed when pressing escape 

- DuggaSys/diagram_mouse.js
Fixed selection so that when several objects are selected, the last one clicked (without CTRL held in) will be selected and remove the selection from the other objects.
This is a fix for Issue #4528
> G2 c16carbe 4528

- DuggaSys/sectioned.js
Found one variabel that seems to be linked with the group functionality that was previously removed.
> Remaining "group functionality"

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
#4388 
Fixed by adding an ID to the dialogue-title and changing it depending on if you click to add a new or click to edit.
> #4388 - DuggaEd: Dialogue-box says "Edit" when creating new

- DuggaSys/sectioned.js
#4636
Fixed an issue where the action bubbles list was still visible even though the bubbles were hiden.
> #4636 - SectionEd: FAB-button bug

- DuggaSys/diagram.js
- DuggaSys/diagram_IOHandler.js
When we clear the diagram with clear diagram from the menu, we now clear the points array.
This is a partial fix for issue #4479.
We limit the JSON-files a bit more now.
> G2-b16petma-4479 Clear Diagram clears the point array

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
A button was added to the import diagram pop-up and the css for the pop-up was moved to style.css
This is a fix for issue #4668
> G2 a16timsc 4668

- DuggaSys/sectioned.php
#4445
Fixed an issue where the FAB button was covering the edit and delete buttons on some duggas.
> #4445 - SectionEd: Change the FAB "+"-buttons position

- Shared/css/style.css
#4667
Fixed an issue where the FAB button was hiding underneath a new hidden item.
> #4667 - SectionEd: FAB-button opacity issue

- DuggaSys/fileed.js
Implemented the already existing suffix "translator" function for the file size cells. It will now look like this:
This solves issue #4657
> G2 c16linst 4657

- DuggaSys/accessed.php
Changed access editor back button to redirect to section editor instead of course editor. Also checked the other sites with the back button but they seem to work as intended.
> Fixed back button redirection functionality

- DuggaSys/diagram_dialog.js
Added one more statement when you push enter to check if appearancedialog is open or not, it's done with a boolean value.
Solution is in #4725
> G2-b16ponpe-4725

- DuggaSys/duggaed.php
Simply changes the header to the deletion-confirmation window to match the same window in the Section Editor.
#4729
> #4729-DuggaED: Update confirmation-box

- install/SQL/testdata.sql
Issue #4525 
The vers makes the duggor appear in the "tests" window, and also makes it possible to edit the old example duggor without accidentally removing them. The changed deadline makes the deadline time show up in the dugga view so that it can be worked with easier.
> Reimplemented changes that somehow didn't get implemented in the merge

- DuggaSys/sectioned.js
- DuggaSys/sectionedservice.php
#4658 
We removed the second error message and created a new message with the PHP error code and message for this case(the problem was that the key for this moment is used in another table row). So the bug was not that the item couldnt be removed but that the alert was bad and shown twice. 
People who worked on this issue: @b16linra and @d15marwi.
> #4658 SectionEd: Unable to delete certain Headings

- DuggaSys/fileed.js
- DuggaSys/fileedservice.php
- Shared/SortableTableLibrary/sortableTable.js
Fixed sort functionality for cells with numbers. Added a zero to the beginning of the number (so that 2 becomes 02, 5 becomes 05 and so on) before sorting so that the sorting could work properly. Previously, it sorted like this: 1 12 17 18 2 20 24 etc. Removed it before rendering the cell so that it shows the original value to the user. This functionality exists in sortabletable. 
Removed column "File ID" as requested in the issue. 
This solves issue #4738
> G2 a16juleh c16linst 4738

- DuggaSys/diagram.js
This pullrequest fixes issue #4767.
You can now have spaces in the names since it no longer activates the move-canvas-function if a dialog menu is open.
> G2 c16carbe 4767

- install/SQL/testdata.sql
Most of the test courses has been removed from testdata.sql. The remaining courses is needed for proper testing because of the course_req table. To test this issue please do a clean install and check courseseed.php to see the remaining courses.
issue #4362
> Removed most of the test courses

- Shared/SortableTableLibrary/sortableTable.js
The sorting arrow is now implemented for the magic header.
This solves issue #4791
> G2 a16juleh c16linst 4791

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- Shared/css/style.css
- Shared/markdown.js
The issue is now fixed and works like it should, when the markdown pen is pressed a pop-up window  appears. The page behind the pop-up now has a shadowy background and is a bit darker than the file editor page. This issue was fixed by @a16adala.  
This is a fix for issue #4763
> G2-a16adala-4763

- DuggaSys/diagram.js
- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
I have made some filtering for detecting which lines to be removed when a symbol is removed. The problem for the issue was that points where removed that where used by lines and the line wasn't removed so when a new point was created at the index the line referenced the line was again able to be drawn.
Solution for issue #4783 
It also solves that points stays on the canvas when entities with connectors are removed.
> G2-b16petma-4783

- DuggaSys/diagram_mouse.js
- DuggaSys/diagram_symbol.js
Fixed the parts of resize() and adjust() functions that are for the UML object. 
The resize() function was altered in such a way that it can have a custom size (because the changes in adjust() affected initial custom sizes in such a way that it couldn't be done)
The adjust() function was altered so that no point can exceed its neighbors x and y coordinates.
It should be noted that this solution can be improved upon and probably should be heavily tested.
This is a solution for #4778
> G2 c16carbe 4778

- DuggaSys/fileed.js
- Shared/SortableTableLibrary/coursesyspw.php
- Shared/SortableTableLibrary/sortableTable.js
- Shared/SortableTableLibrary/sortableTableDemo_sortadvanced.html
- Shared/css/style.css
We have replaced the old search functionality from sortabletable into a new one that exists inside fileed.js. To enable the sorting, one should pass the "renderSortOptions" function into the creation of the table. If any special sorting needs to be specified, this can be done in the function "compare()". It now works to sort on all columns that should be sortable, and it is also easy to determine which columns that are not going to be sortable.
Everyone can now use the sorting by implementing the functions **renderSortOptions()** and **compare()**.
_**Example on how the compare function can be used:**_
This solves issue #4775
> G2 c16linst a16juleh 4775

- DuggaSys/diagram_symbol.js
This is a fix for issue #4826 
UML objects now resizes their size automatically depending on how many attributes and operations it has.
As such, resizing of height is no longer possible.
Resizing width is still possible because of potentially long attribute/operation names. Another issue could be created to fix this to be an automatic process that checks for the longest attribute/operation name and sets the width of the object to that.
> G2 c16carbe 4826

- DuggaSys/diagram.php
- DuggaSys/diagram_toolbox.js
- Shared/css/style.css
Added an option in the toolbar to switch between different modes to only see the buttons that belongs to that diagram type. You can choose between all symbols, ER symbols and UML symbols. 
Also centered all the buttons.
This is a fix for Issue #4831
> G2 a16rasja 4831

- DuggaSys/diagram_symbol.js
UML objects will now get an automatic size depending on the longest attribute/operation name.
This is a fix for issue #4868
> G2 c16carbe 4868

- DuggaSys/duggaed.js
- DuggaSys/sectioned.js
When creating a new dugga, you can now press 'enter' to submit/save the dugga. When prompt to delete dugga, the 'enter' button is disabled.
> #4704 - DuggaEd: Enter-key = Yes/Finalize

- DuggaSys/sectioned.js
I added the returned value from validate -name and -type to the keycode function. Now they're disabled when an invalid name is written or e.g. when test is selected and there are no tests present.
> #4914 - SectionEd: Saving an item by pressing "Enter" even if its not allowed

- Shared/loginbox.php
The forgot-password page now reverts back to the regular login page after you close the window.
> Fix for loginbox

- DuggaSys/sectioned.js
#4956 - a16thegu
Updated all sub-FAB in SectionEd (sectioned.js) to be like the solution in #4840, and changed the location of the Group Activity and Message buttons in the FAB to be in a incremental order.
> #4956 - SectionEd: Update generic code for FAB in sectioned.js

- Shared/dugga.js
#4971 - DuggaED: Error when closing windows with escape. 
The only line that needed to be effected was removing the line that called on showSaveButton(). The function showSaveButton is only used in sectioned. Therefore the function call should be inside that file. (In this case there is no need to call showSaveButton when pressing esc.)
> #4971 - DuggaED: Error when closing windows with escape.

- DuggaSys/sectioned.js
#4861 - a16thegu
Changes "New Item" to a sections respective original name when adding a new section to SectionEd via FAB.
> #4861 - SectionEd: Default title values on created items through the FAB list

- DuggaSys/diagram_mouse.js
You are not able to draw a line between ER objects and UML objects anymore.
This is a soulution for issue #4905
> G2-a16rasja-4905

- Shared/SortableTableLibrary/sortableTable.js
ToggleSort method in SortableTable now uses the "kind" parameter to decide if sort should be ascending or descending 
(Even number = ascending, Odd number = descending)
Solution for #4975
> G2-b16andka-4975

- DuggaSys/fileed.js
- DuggaSys/fileedservice.php
The extension and size column is displayed with a "-" in fileed.
Solution for #4990
> G2 b16andka 4990

- DuggaSys/accessed.js
Issue #4904 
Uses a similar function to the example, does not highlight the column, just the row
> Added row and cell highligtning for accessed page

- DuggaSys/resulted.js
- DuggaSys/resultedservice.php
Issue #4930 
The local value of gradeExpire was not updated whenever a new grade was set. For newly submitted duggas the value of gradeExpire was null, which makes the if statement on row 472 in "resulted.js" fail.
The local value is now updated with the value from the database whenever a grade is updated. While implementing this I made changes to update the local value of timesGraded aswell.
Both gradeExpire and timesGraded should now update correctly.
> Fixed bug when grading a newly submitted dugga

- DuggaSys/duggaed.js
#5038 - Fixed by creating a new function for opening the variant editor. This function only runs when clicking on the edit variant button.
People who worked on this issue: @b16linra and @a14oliri.
> #5038 - DuggaED: Saving dugga changes opens the variant editor.

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
#5027 - a16thegu
Generalized the previous "No Test"-dialog window, so the FAB chioces "Code" and "Link" also can use it to display it's error message, by just changing the error message text through an id with jQuery.
Added if-statments for kind 2 and 5 to validate if code examples or links exists in the database for that specific course. Code Examples has a hard codes index, which makes the statment different form the others.
Finally, added code to close the dialog window by pressing "Enter".
> #5027 - SectionED: With FAB, creating link and code items should not be possible when nothing is stored in files

- DuggaSys/duggaed.js
**#5033** _Removed minheight to make the table collapse in a better way when no variants are available._
> #5033 DuggaED: Styling for duggas without variants.

- Shared/css/style.css
#5055 - Fixed by adding a row of styling in styles.css that disables anti-aliasing in Firefox on macOS.
> #5055 - Font weight is different in Firefox on macOS

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
#5029 - @a16thegu
Removed the hard coded tooltip message in sectioned.php, so it can be added via jQuery instead - depending on what kind is validated.
Added else-statments to the isTypeValid() function so it can check if any links or code examples exist under Files. If not, a message will be displayd using jQuery for that specific kind/type.
Additional, I removed some breaklines and added spaces where it was needed where I was adding my functionality.
> #5029 - SectionED: With Add button, creating link and code items should not be possible when nothing is stored in files

- DuggaSys/diagram.js
Move copied objects down and right 10px in order to see the new objects
This is a fix for issue #5042
> G2 a16timsc 5042

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- Shared/css/style.css
- Shared/markdown.js
fixed issue #5054 it now works to see the file name in the editor header
> G2-b16nicbr-5054

- DuggaSys/diagram.js
- DuggaSys/diagram_symbol.js
Made that we only change one connector when we iterate over the symbols.
The solution was tested with a diagram that was bugged on previous version and changed to my branch and the flickering disappeared.
Solution for issue #5037
> G2-b16petma-5037

- DuggaSys/forms/attribute_appearance.php
- DuggaSys/forms/entity_appearance.php
- DuggaSys/forms/figure_appearance.php
- DuggaSys/forms/global_appearance.php
- DuggaSys/forms/line_appearance.php
- DuggaSys/forms/relation_appearance.php
Changed calling type for selectboxes from onclick to onchange. Onchange makes the changes appear immediately when selecting an option. Onclick didn't work on mac computers.
This is a soulution for issue #5088.
> G2-a16rasja-5088

- DuggaSys/sectioned.js
#4350 
@a15magkn
Removed the function participationList().
This is most likely a remnant of the old GroupEd that was removed in the issue #4188
> #4350 Part 4 - Check of code standard in HGustavs/LenaSYS/DuggaSYS/sectioned.js

- DuggaSys/duggaed.js
**Removed some unused code, disabled magic heading in the variant editor and also fixed sorting with null-values.**
> #5136 DuggaED: Fix magic heading in the dugga table and the variant table.

- DuggaSys/duggaed.js
#5166 - Removed the answer column from the variants editor.
According to the customer, it is a little uncertain where the answer related data is used, so the code has not been modified more than removing the column from the editor.
> #5166 - DuggaED: Remove answer column in variants

- DuggaSys/diagram.php
- DuggaSys/diagram_toolbox.js
When the user has changed the toolbar state and reloads the page it now remembers which toolbar the user have chosen (All, ER, UML) and switches to that toolbar immediately.
This is a soulution for issue #5161
> G2 a16rasja 5161

- Shared/css/style.css
There are no longer lines beside the menu items in the diagram menu.
This is a soulution for issue #5173
> G2 a16rasja 5173

- DuggaSys/resulted.js
#4332 This issue have been split into multiple issues, so don't close this issue after merge.
This merge handles only sorting order.
when sorting on a particular dugga all ungraded duggas should be at the top in order of submitted date and time.
**solution:**
Sorting on a dugga should now sort in the following order
1. submitted duggas that has not been graded yet (yellow background)
2. passed dugga (green background)
3. failed dugga (red background)
4. student has only viewed the dugga but not submitted anything (light purple background)
5. all other students that has not even visited the dugga (grey panel without buttons)
Sorting in the column Fname/Lname/SSN now sorts in the following order:
1. First name
2. Last name
3. SSN
> Added sorting to the table on the resulted page

- DuggaSys/resulted.js
- Shared/css/style.css
#5168 part of #4332 
Duggas submitted after the deadline should be separated from the duggas submitted before the deadline by using two distinct background colours.
The solution affects the table on the result page.
I had to change the test data to be able to test this, since all deadlines where prior to the submissions.
So i used the following MySql query to change the deadline so i could have both duggas before and after the deadline.
update quiz set deadline = '2017-01-01 23:59:59' where id = 10;
This will change the deadline for "Rapport" in the course "Webbutveckling - datorgrafik".
Then I also had to make a new submission for one of the students who had **NOT** done the "Rapport" dugga yet to be able to see the difference on submitted duggas. (yellow/oranage)
> Added a new background color for duggas that have been submitted after the deadline

- DuggaSys/sectioned.js
#4352 
@a15magkn
Declared some variables that were undelcared, because of the codestandard. Nad removed a function that never was used.
> #4352 Part 6 - Check of code standard in HGustavs/LenaSYS/DuggaSYS/sectioned.js

- Shared/SortableTableLibrary/sortableTable.js
The magicheader in sortableTable is no longer flickering when rendering the table.
Solution for #5196
> G2-b16andka-5196

- DuggaSys/accessed.js
#4992 
Fixed a bug when sorting on examiner when one examiner row is equal to null.
> Fixed access examiner sorting bug

- DuggaSys/diagram_symbol.js
Fixed so that UML will resize according to the name of the class if no operations/attributes exist (or if they are shorter than the classname)
This fixes issue #5222
> G2 c16carbe 5222

- DuggaSys/resulted.js
Issue #5200 
A couple of bugs have been found:
- It seems like the entire table is being sorted backwards. When the table is supposed to be sorted in ascending order it is actually sorted in descended order (and vice versa).
- It also seems like the different sections is being sorted backwards. In the first section for example; On-time, ungraded duggas is being sorted. Duggas here should be sorted from oldest to newest. Though, a newly submitted dugga is being sorted before older duggas. This should not happen.
**Solution:**
The sorting on duggas on the result page should be:
1. Ungraded duggas within deadline (Yellow)
2. Ungraded duggas that have been submitted to late (Orange)
3. Passed duggas (Green)
4. Failed duggas (Red)
5. Students that has only viewed the dugga but not submitted …
> A bugg fix that solves incorrect sorting of duggas on the result page

- DuggaSys/fileed.php
- Shared/css/style.css
Changed the ID that controlled the css for the fab-button Link and the link button inside the preview-window. Now they have seperate id's and will no longer be a problem for eachother
This is a fix for issue #5192
> G2 a16adala 5192

- DuggaSys/fileed.php
- Shared/css/style.css
The layout for the mobile view is changed. 
The codeblock is also fixed, if you want to create a codeblock you only get one box around the code, instead of two boxes.
---
This is a fix for issue #5149
> G2-a15setno-5149

- DuggaSys/sectioned.js
#5233 - Fixed the bug that caused the wrong arrow to be displayed in the statistics section.
> #5233 - SectionED: Icon bug in the statistics tab

- DuggaSys/diagram.js
We use the newly copied symbols for the next ctrl-v. This fixes that the symbols stacks.
Solution for issue #5183
> G2-b16petma-5183

- DuggaSys/fileed.php
- Shared/SortableTableLibrary/sortableTable.js
The text in the magic header does no longer jump around and stay at the correct position from the start. 
The magic header also had a small delay (somtimes) when scrolling fast, I managed to fix that bug aswell.
Solution for #5244
> G2 b16andka 5244

- DuggaSys/diagram.js
All attributes are following to the newly copied object. Changed how you copy the objects, instead of create entirely new object.
Solution for issue #5180
> G2-b16ponpe-5180

- DuggaSys/diagram.js
A copied object will now receive a middleDivider if it is of the type that uses a middleDivider instead of centerPoint (UML objects)
This solves issue #5181
> G2 c16carbe 5181

- DuggaSys/diagram_dialog.js
- DuggaSys/forms/global_appearance.php
The select boxes for global appearance has new default values. 
When a styling option is selected it changes the object immediately. 
When the user closes the appearance menu with the 'X' in the upper right it doesn't save the styling. 
This is a solution for issue #5245, and seems like issue #5140 is solved as well.
> G2 a16rasja 5245

- DuggaSys/resulted.js
- Shared/css/style.css
Issue #4229 
Remade the checkbox functionality and hiding of grading buttons from issue #4227 and #4228 now that sortabletable has been implemented.
Minimode now renders students in a single line mode where only the name of the student is shown. The change of height made in styles.css (to make the table work in firefox) was moved to an inline style in renderCell() to make it possible to change the height of cells when entering minimode.
> Minimode now renders students in a single line mode

- DuggaSys/diagram_mouse.js
When a symbol is created and then moving that object, the create button is unselected.
Solution for issue #5296
> G2-b16ponpe-5296

- DuggaSys/diagram.js
- DuggaSys/diagram_dialog.js
The global appearance menu is now draggable from the beginning.
Also removed so that login box isn't draggable when closing any of the appearance menus
This is a solution for issue #5295
> G2 a16rasja 5295

- Shared/css/style.css
#5324 - @a16thegu
Added "display: none;" on @media screens from 800px and under in the style.css, which hide the statistics-section on displays under 800px in width (like smartphones).
> #5324 - SectionED: Hide the statistics tab on mobile

- DuggaSys/diagram.php
Changed $noup to section because course showed the swimlane clock. The swimlane clock is now removed.
Solution for #5310
> G2-b16ponpe-5310

- DuggaSys/fileed.js
It is now possible to close the fab-list by clicking on the main fab button. This works on PC, MAC, Android and iOS versions earlier than 11.3. To make this possible, we had to change the existing code for the fab button quite a bit. 
This is a fix for issue #5259
> G2-c16jonha-b16andka-5259

- DuggaSys/contributionservice.php
#5107 
> It seems that "Events Performed" under project statistics for a user takes "Comment Creation" into account.
>
>Using the provided testdata we can see that created comments amounts to 138. Looking at the total amount of performed evens in the contribution list below we can see that 7 events have been performed. If we now look back to the table at the top we can see that "Events Performed" is at 145.
To test this navigate to a course and change the URL ending from "DuggaSys/*" to "DuggaSys/contribution.php" to navigate to the contribution page.
> Fixed event counter on contribution page

- Shared/SortableTableLibrary/sortableTable.js
Issue #5174 
Ask me if you need help with testing
I noticed the columnno variable is also not working as intended as arr doesn't get the column number. I believe group 2 might have worked on a fix for this that comes in the next merge. (It didn't work before my fix, its ok, i didn't break it)also the variable is named coldata, but looking at the examples its used as celldata.
> Celldata for inline editing now works as celldata in rendercell

- code_standard.md
#5340 
The code standard is updated because older browsers does not support "let" when declaring varibables. Therefore variables should be declared using var.
> Updated code standard - avoid let, use var when declaring variables

- DuggaSys/fileed.php
- Shared/css/style.css
The label, the markdown buttons and the textbox are now in line! They start in line with the textarea and the layout should also work on mobile view.
---
This is a fix for issue #5323.
> G2-a15setno-5323

- DuggaSys/diagram.js
- DuggaSys/diagram_figure.js
- DuggaSys/diagram_mouse.js
A path object can now be resized.
* Each point is drawn
* Each point is clickable/draggable
* Hitbox/bounding box is recalculated after dragging/clicking a point of a path-object.
This fixes issue #5381
> G2 c16carbe 5381

- DuggaSys/diagram_symbol.js
It now works to export ER Attributes to SVG as well
This is a fix for issue #5393
> G2 a16timsc 5393

- DuggaSys/diagram_symbol.js
makeShadow() is now called within the symbol-object itself, which fixes the shadows not being drawn.
`makeShadow();` -> `this.makeShadow();`
This fixes issue #5422
> G2 c16carbe 5422

- DuggaSys/diagram.js
* Path-objects will no longer be selected if other objects are in front of it.
This is a fix for issue #5427
> G2 c16carbe 5427

- DuggaSys/resulted.js
Issue #5220 
Data for first column was not added if there was no gradeable moments in a course, hence there was nothing to display.
The "Fname/Lname/SSN" column should now show data for each student/teacher even if the course has no gradeble moments.
> First column is now shown in courses without tests

- Shared/css/style.css
We managed to align the icons correctly by setting the text-align in their respective classes to center.
This is a fix for issue #5413
> G2-c16jonha-b16andka-5413

- DuggaSys/diagram_figure.js
A square object will now get selected properly when it is created. As such, a square path object will no longer get de-selected when you've resized it.
This is a fix for issue #5441
> G2 c16carbe 5441

- DuggaSys/sectioned.js
#5390 - SectionED: Scroll position doesn't save
#5391 - SectionED: Auto scroll to bottom of the page
These issues were solved by moving the function call of scrollToBottom so that it is only called when actually creating a new item. This also solved the functionality of auto scrolling to the last scroll position saved in local storage.
> #5390, #5391 - Scroll position

- DuggaSys/sectioned.js
#5320 
@a15magkn
Made so that the Statistics-text to the left of the screen is unselectable
> #5320 SectionED: Make the text on the statistics tab unselectable

- DuggaSys/diagram_dialog.js
- DuggaSys/diagram_mouse.js
You are now able to close the appearance menu when opening it with the change appearance button. 
Also fixed so that no exception is generated when opening the appearance menu without any object selected.
This is a solution for issue #5448.
> G2 a16rasja 5448

- DuggaSys/accessed.js
#5468 
The 2nd commit(4847975) was to clear the options each time before adding them again. For some reason returnedAccess is run twice when the page is loaded. Clearing all options before adding them resolved this. To clarify - the options are to select a responsible inside the popup-menu for creating a class.
> G1 issue 5468

- Shared/SortableTableLibrary/sortableTable.js
Issue #4377 
Fixed issue where new columns were not shown when visiting a a table where there was a record in local storage.
> column filters not found in localstorage are now shown by default

- DuggaSys/diagram.php
- Shared/css/style.css
The toolbar is now a little less tall due to the buttons inside create now are in two rows instead of one.
This is a fix for #5446
> G2 a16adala 5446

- DuggaSys/diagram_mouse.js
When deselecting objects by pressing an "empty space" in the canvas you will now get the message "no item selected" when pressing the change appearance button.
Also fixed so that when deselecting with ctrl pressed it now opens the appearance menu for one of the selected objects, not the one deselected.
this is a solution for issue #5474
> G2 a16rasja 5474

- DuggaSys/diagram.js
If no object is selected when you try to delete an object, we display the appearance menu to indicate no object is selected.
Solution for #5472
> G2-b16ponpe-5472

- DuggaSys/diagram_symbol.js
There is no longer a solid border around the text so that it better represents just simply where the text is rather than that you are typing inside a box.
This is a fix for #5488
> G2 a16adala 5488

- DuggaSys/diagram.php
Menu-items that are related, such as locking/deleting and various appearance menu items, are now grouped together in the drop-down menu.
This fixes issue #5491
> G2 c16carbe 5491

- DuggaSys/diagram.js
The dialog menu telling the user that no item is selected will no longer appear after deleting an item. It will only appear when no item is selected.
The logic for erasing objects was also re-written so that it only loops through selected_objects instead of the entire diagram.
This is a fix for issue #5513
> G2 c16carbe 5513

- DuggaSys/forms/figure_appearance.php
In the appearance menu for figures, the opacity slider will now update the opacity in realtime.
This is a fix for issue #5526
> G2 c16carbe 5526

- DuggaSys/fileed.js
- Shared/css/style.css
Added nowrap to filename element  to prevent long filename to take up too much space
Solution for #5539
> G2 b16andka 5539

- DuggaSys/fileed.php
- Shared/css/style.css
The margins for the save and close buttons are changed. They do not have the same top and bottom margin because of the rest of the layout, but they are now more centered. About the textarea in the markdown preview, @b16nicbr fixed it, but it is not a part of this issue anymore. But the textarea in the file editor window is bigger! See the screen shots below.
The markdown 
--
The file editor
--
This is a fix for issue #5456.
> G2-a15setno-5456

- DuggaSys/diagram.php
- Shared/css/style.css
Changed so the buttons inside draw now are in 2 columns as well since there are more functionality coming down the line.
This is a fix for issue #5517
> 2 columns for draw buttons

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- Shared/css/style.css
Issue #4902
- Changed font size of all text elements in the table.
- Added classes for mini and normal mode to remove some inline styling.
- Added margins to the sides and bottom of the table and modified/moved the code in resulted.php to get a layout more similar to filed.
- Changed margins of row counter and centered the text.
- Removed the class "gradeImg" from the grading images as this was a remnant from the old mini-mode.
Magic heading and changes of the header was already fixed in other issues. 
The buttons for "add user" and "import user" are no longer present but the search bar seems to have a proper placement when compared to filed.
> Fixed some styling in resulted

- DuggaSys/fileed.php
- DuggaSys/preview.php
- Shared/css/style.css
Fixes the alignment of the markdown icons, so that they go in a straight, (almost) centered line. Fix made by @b16andka 
I also fixed some last minute changes.
> Markdown icon fix

- DuggaSys/sectioned.js
#5577 - @a16thegu
Changed so the swimlanes height changes depending on how many test entries exist and not on how many tests exist in DuggaED.
> #5577 - SectionED: Swimlane height dosn't change when adding a new entry

- DuggaSys/diagram.php
- Shared/css/style.css
In the diagram toolbar, we forgot to change the line button so it looked like the other buttons. This is now fixed.
> Made the line button consistent with the others

- install/SQL/init_db.sql
Fixes issue [5650](https://github.com/HGustavs/LenaSYS/issues/5650)
Added teacher to the user_course table which eliminates the error at installation, this adds more test data.
Also implemented @b17carma 's solution for getting rid of the error messages when accessing courses.
Tested on a fresh LenaSYS installation in a Docker container, working.
> Added teacher column to user_course and groupKind column to listentries

- DuggaSys/diagram.php
The menu option was moved from the "View" category to "Align category as seen in the image: 
Fix #5763
> Snap to grid menu option moved to "Align" category - Fix for #5763

- Shared/css/style.css
Fxied issue #5761 
Changed the class in style.css at around row 4000.
It should affect the fab when left clicking and holding (you'll see some smaller buttons appear above it). On live (gruppc2019w16) they should all have a transparent background and be hard to click/tell what it is. But this should give them all differently colored backgrounds. Works on sectioned.php, in result(result is currently broken though) and all fab buttons that have extra buttons come up when you left click hold them (courseeed.php for example does not have this.
> Update style.css fixed fab-btn background color

- DuggaSys/diagram.js
- DuggaSys/diagram.php
The checkboxes are not specified in the html document but are instead added to the page from javascript in a setCheckbox method. This can be called on any element that needs a checkbox element.
> Add checkboxes to diagram menu - Fix for issue #5694

- install/install.php
Added the root password textfield as an exception for the function that checks if each textfield is filled before continuing the installation process. You can now complete the installation without entering a root password. Fix for #5720
> Changed textfield constraints for root password - Fix for #5720

- DuggaSys/diagram.php
- Shared/css/style.css
Issue #5804 and #5821 is fixed.
The menu bar won't float downwards anymore when rezising the window. Got help from @a17okaoz with this issue.
The menu bar won't be affected anymore when changing the direction of the toolbar. The problem was that the toolbar and the menu bar used the same span for the labels, which affected css.
> Fixed issue #5804 and #5821 (which was referenced in issue #5804)

- DuggaSys/diagram.php
- DuggaSys/diagram_figure.js
The problem behind the issue was that the program did not register that the user lifted the mouse key and instead believed it was still pressed when it wasnt. This reversed the order of execution in events which bugged out the square drawing logic. 
Solution: Added the onmouseup listener that calls the mouseupevt function to the body tag.
Fix for #5534
> Fixed the drawing squares bug - Fix for #5534

- DuggaSys/diagramservice.php
I've added an explanation for what the file does and what data it returns. I'm still a bit unsure on where this file is used and why the diagram needs it. It seems to serve about the same purpose as contributionservice.php.
> Added documentation to diagramservice.php - Fix for issue #5818

- DuggaSys/sectionedservice.php
- DuggaSys/showDugga.php
**This is a really ugly solution, but it works.**
For issue [#4193](https://github.com/HGustavs/LenaSYS/issues/4193)
First of all, I added a new array to the $duggor array. This is because `makeoptionsItem()` in dugga.js reads from this array to populate options in the edit item dialog in sectioned.php.
If the teacher creates a new dugga with type 'Test' this new item shows up as an option in the 'Link' dropdown.
Now, when a user clicks the dugga it should redirect to an iframe containing contribution.php. If the user leaves contribution.php, the iframe gets destroyed.
**Problem**
The $duggor array is filled with duggor, in real world the number could be high so I made the Contribution "dugga" have id 9999. This could be a problem.
**Note:** contribution.php is currently broken, so …
> Made a dugga that loads contribution.php in an iframe

- DuggaSys/duggaed.js
issue #5784 is fixed and the - (delete) button now properly deletes the row. Button only exists on rows past the first one and also fixed a bug where a new submission row was created extra in an accumulative way each time the variant editor was opened.
> Editing variants submission row fixex

- Shared/SortableTableLibrary/sortableTable.js
- Shared/dugga.js
- Shared/icons/external_link_open.svg
Any pdf submission should be able to open in a new tab using the new added open external button.
This is the second pull request for this, the first one is at #5738 Made a new one now that we have a new base branch. Currently on the master the resulted.php is broken due to some javascript so it might be a little bit hard to test but the icon also shows up and works the same way when looking back at a already submitted pdf (i.e submit a pdf, go back onto the dugga and see if the button is there next to download and if clicking it opens a new tab with the pdf in it.
> Update dugga open pdf new second fix

- DuggaSys/diagram.php
Fix for #5776 
Changed class for div to "drop-down-text-non-clickable", which is currently non-existent but might be useful in the future.
> Fix for #5776

- DuggaSys/resulted.js
- Shared/SortableTableLibrary/sortableTable.js
This is a solution that solves the sorting problem for the tables in access, test and  files tab on course front page. Instead of using 3 different compare functions i made one compare function that all sortingTables can use. The compare function is universal and can be used for more tables later on.
This solution works for the tabels at the pages stated above but do not work for the results table under the "Results tab" on the course front page.
My suggestion is that we take this solution and then adding the results table as an new issue and trying to solve that one with this solution.
> Tabel sorting fix for the access, test and files tab.

- DuggaSys/showdoc.php
For issue #1783 
This reads from the session variable if the course version is not included in the showdoc link.
> Added coursevers to GET if not already set.

- Shared/SortableTableLibrary/sortableTable.js
removed styling that was causing #5833
sortable tables should now work properly and the pen icon should work (no errors thrown in console)
> Removed styling on element in sortableTable.js

- DuggaSys/diagram.js
- Shared/css/style.css
Moved the toolbox downwards towards the center rather than it starting in the upper-left corner.
> Fix for issue: #5997 "Menu getting overwritten by the toolbox"

- DuggaSys/sectioned.js
Added functionality for enter on deletebutotnDisplay.
This is to solve issue #6053 to make it easier to delete items on sectioned.php.
Click trahscan on an object and hit enter to delete it instead of having to press yes.
> Update sectioned.js enter to delete section

- DuggaSys/duggaed.js
Fix for issue #6041 
The submitter is now required to pick a start date and deadline date.
I also added verification that deadline date is after start date.
Note: release date is allowed to be null because of this code in showDuggaservice:
`			if($today > $duggainfo['qrelease']  || is_null($duggainfo['qrelease'])){
$feedback=file_get_contents($fedbname);				
}`
> DuggaEd: Added verification for Start date and Deadline

- Shared/css/style.css
Issue #6083 is fixed.
Moved the menu a bit higher when hovering over a menu option.
> Fixed issue #6083

- DuggaSys/accessed.js
Undid the comment covering 2 functions to instead comment away the content of the functions. This avoids the uncaught reference error whenever the functions got called (were never removed and can't really be removed) and it avoids displaying an empty white box. This should fix issue #6037 and #6052 whilst keeping the fix on issue #5975
> Moved comment block in accessed.js

- DuggaSys/diagram.js
Fix for issue #6144 
Running a deselect function when loading a diagram as doing this when saving might interfere with the current state while working.
> Grupp a2019 w17#6144

- DuggaSys/diagram_objects.js
#6181
The lines between a weak entity and a relation should now be changed to 'forced' whenever the entity is set to be weak.
> lines between entity and relation to forced #6181

- Shared/css/style.css
Added "-webkit-appearance: none"  to input.submit-button inside style.css.
To test this one you need a iphone and use safari. 
Before:
After:
> Fix for issue #6214. for safari mobile. 

- DuggaSys/diagram_IOHandler.js
A simple fix which changed the file type for the export image menu option from .jpg to .png
#6246
> Changed image file from .jpg to .png - Fix for #6246

- DuggaSys/sectioned.js
#6211
The functions isTypeValid and isNameValid were used in if statements but were never created in the file, which caused errors. They are gone now and so are the errors.
This caused errors in the sectioned part of dugga.
> Removed functions that were never created

- DuggaSys/showDugga.php
- Shared/css/style.css
before
after
Moved a header which was hidden behind the absolute submission window so that you can escape the previewpopup. It might be a good idea to see if any other boxes gets messed up by the style.css change. the loginbox class is for some reason used for the previewwindow.
#6220
test site, log in and click the text submission to see the change:
https://c17alepe.webug.his.se:20002/DuggaSys/showDugga.php?did=74&cid=324&coursevers=12324&moment=2328&segment=2386&highscoremode=0&comment=UNK&deadline=2019-05-15%2007:15:00
NOTE TO ISSUE-MASTER: The branch i created has the wrong issuenumber. it says 6022 but it should be 6220. Let me know if this is a problem
> Grupp b2019 w18#6220

- DuggaSys/diagram.php
- Shared/css/style.css
Fixed issue #6015 
I changed the cursor icon to a pointer when hovering over the toolbox buttons. I could add a small visual effect aswell, but I feel that the pointer is clear enough to let the user know that they are hovering over a button.
> Fixed issue with clearer hover effects on toolbox buttons #6015

- DuggaSys/accessed.js
- DuggaSys/accessedservice.php
- Shared/css/style.css
- Shared/icons/DocumentDark.svg
For issue #5634 
This change adds a button to the Version cell of the access table if the user has made a submission in a version of the course other than the active version (i.e an old version).
The button itself is just the 'Document' icon with inverted colors, can be subject to change.
> Added a button for going back to a specific course version

- DuggaSys/resulted.php
before
after
#6268 
I moved the select so its right of the buttons. i also expanded the margin on the buttons for a more consistant look.
testsite: https://c17alepe.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> moved the 'filtrera efter'

- Shared/css/style.css
The move button has be adjusted a bit to the left to fit at the corner of the canvas.
#6264
> Fix for #6264 Changed style value for move button

- DuggaSys/diagram.js
#6354 
The line tool is only deselected when the line has been created, so that if you don't draw a line to an object then the line the tool will not be deselected and you can draw as it was intended. This behaviour can be changed though, depending on how we want it to work.
> Fix for issue #6354: Deselection of draw line

- DuggaSys/contribution.js
- DuggaSys/contributionservice.php
- Shared/css/style.css
Issue #6304 
How it looks on server:
Currently the graph only tracks comments, commits, and issues. This can be modified later on if more event types are needed. The activity boxes on the graph has different colors depending on the event type, and is multicolored if several different types are on the same hour.
When the user hovers over a box, information about the activities that hour are shown. User can also hover over the polygon to show information about the whole day.
The polygon is only drawn when there are three or more points of activity.
This can be hard to test since the database we use only has data for HGustavs and a97marbr, so the events are mainly comments. What I did to test this was:
- sqlite3 GHDataTest.db
- SELECT * FROM event WHERE author='HGustavs' AND kind IN …
> Created graph for daily github activity

- Shared/css/style.css
Issue: #6407
When the mouse cursor is not hovering over the zoom-buttons, the tooltip should disappear correctly now. And it's no longer possible to hover over the tooltip text the zoom-buttons hover effect generate.
> Fixed issue #6407: Zoom-buttons hover effect should not be able to be hovered

- DuggaSys/diagram.js
Issue: #6377 
Fixed the issue when hovering over a umlline and when trying to draw lines between entities it would show a move cursor. Now it shows the default cursor when these actions are being done.
> Fixed issue #6377: Move cursor was displayed when it should not be

- DuggaSys/diagram.js
Issue: #6377 and #6507
Fixed issue regarding wrong mouse cursor when trying to draw UML lines and when hovering over the points at the edge of the lines. Before it was a move cursor, now it should be a default cursor.
> Fixed issue #6377 and #6507: Move cursor displayed when it should not be

- DuggaSys/sectionedservice.php
- DuggaSys/showDugga.php
- DuggaSys/templates/contribution.html
- DuggaSys/templates/contribution.js
The previous implementation hard coded an option to the 'Link' select box with dugga id 9999, which will cause problems when the amount of duggas reach 9999. 
Previous pull: https://github.com/HGustavs/LenaSYS/pull/5805
Original issue: https://github.com/HGustavs/LenaSYS/issues/4193
This way is better and follows the already established logic of creating duggas. (Creating a test in duggaed with the contribution template)
> Changed loading of the contribution iframe to be less naive

- DuggaSys/diagram.php
- Shared/css/style.css
#6379 
added some styling to the zoombar.
Changed the handle and made it transparent when hovered.
Tried to make it so that only the handle was made transparent when hovered but failed with that approach. Can be made in a new issue in the future if it is requested
> fixed styling for zoom bar #6379

- Shared/css/style.css
Fixes #6638
They are now disappearing at the correct browser width. This problem originated because we put the menu in the navbar, the breakpoints were designed for when the menu was below it.
> Fixed breakpoints for hiding menuitems

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Fix for #6607. Also fixes some lines that were still accessing properties through the old variables. 
When reviewing, try modifying the properties (through the appearance config window) and see if any errors show up in the console.
> Fix for issue #6607: Remove redundant property variables

- DuggaSys/diagram.js
A previous fix prevented the used from resizing locked objects but merge commit 19802dd8 removed an important if-statement (diagram.js:2539). This PR re-adds it.
> Fix for issue #6622: Re:Stop resizing locked objects

- Shared/SortableTableLibrary/style.css
- Shared/css/style.css
From #c6cdb8 to #cccccc. Not as green anymore
Fixed #6639
Test site: https://a17alian.groupb.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursevers=97732
Before: 
After
> Color when hovering over sectioned list changed

- Shared/css/dugga.css
Fixes #6296 
The preview table still breaks when making the browser window small, but that was also true before this change.
> Made teacher feedback column stretch to remaining space

- DuggaSys/diagram.js
- DuggaSys/diagram.php
#6643
The resetToolbarPosition function has been removed from diagram.js
The drop-down-item div concerning reset toolbar has been removed from diagram.php
> resetToolbar removed

- DuggaSys/diagram.js
- DuggaSys/diagram.php
#6349 is an issue about preventing the menu to collapse after one of the items is clicked. Not all menus prevented. Just those that where decided trough discussion. There was a double undo and redo function so I kept just one. In case you wonder why so much code was deleted.
> Fix for #6349. Preventing collapsing when clicking on menu items

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
#6239
Okay, so objects "officially" have 3 points, bottomRight, topLeft and middle and then the 2 remaining bottomLeft and topRight doesn't really exist. The functionallity implemented only works when resizing the bottomRight and topLeft points. The other 2 corner points somehow introduces problems and doesn't seem to work the same, and after much testing i couldn't get it to work with them. I might have done something wrong but since they are different and aren't tied to acctual points i'm not entirely sure.
> Fix for issue #6239: Ability to lock proportions when resizing entities

- DuggaSys/diagram.js
- DuggaSys/diagram.php
By clicking "Toggle A4-Holes" you change the position of the holes of the A4 from left-right & upper-bottom (Horizontal and vertical). At the moment you click the menu item to shift sides. A future issue would be instead of a checkmark put an icon who describe which side the holes are at. I will write that issue when it's approved and merged.
#6414
> Positioning of A4 holes #6414

- DuggaSys/diagram.js
https://github.com/HGustavs/LenaSYS/issues/6271
Displaying virtual A4 now draws enough rows and columns of A4 sheets to fill entire canvas (positive coordinates) instead of just one.
> Fix for#6271: display multiple A4 sheets

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
fixes #6131
When deleting an item in sectioned you will now be able to select between yes and no with the left and right arrow keys and then press enter, previously enter was always yes.
In the issue it was suggested to cycle between yes and no with tab but that was buggy or didnt work so arrow keys were chosen instead.
Test site: https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732
> Keyboard shortcuts for deleting item

- Shared/css/style.css
https://github.com/HGustavs/LenaSYS/issues/6747
The code that disappeared during the merge has been re-added and the mode switching dialog has the correct styling again.
> Fix for #6747: mode switching dialog

- Shared/css/style.css
This was a lot simpler than I originally thought. I started a new branch and tried without javascript. One change in css and it was solved. The children of class checkbox-dugga is #eee on every odd line.
Solution for #6321
test site:
https://c17alepe.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
Note to Tim, everything related to this can be closed. This new solution is much cleaner and more consistant #6555 and my old PR #6721
> Solution for 6321

- DuggaSys/diagram_objects.js
> Fix for issue #6545: Undoing and redoing Draw Free tool doesn't work 

- DuggaSys/diagram.js
#6738 Switching tab or window now resets the pressed buttons. Buttons handled now are Ctrl and Shift. If you wish to add more it's just to put in what keys you wish to add. Very simple. Just check the code.
> Fix for #6738 Resetting key press when focus is lost

- Shared/css/style.css
https://github.com/HGustavs/LenaSYS/issues/6720
Placement of the tooltip text for when you hover over a button in the left toolbox has been changed to the top left corner of the canvas, as the previous placement doesn't work anymore with the new toolbox design.
Before:
After:
I tried to make the tooltip relative to each button but weird things happened to the buttons on hover. I can try to investigate further on this if this placement of the label is what we really wish for. Otherwise I think it looks good with my solution.
> #6720: Styling on toolbox hover label

- DuggaSys/diagram.js
#6419 Zoom focuses on mouse pointer now instead of origo. Zooming in and out should not lose the object the mouse pointer is on.
> Fix for #6419 Zooming relative to mouse coordinates

- DuggaSys/templates/clipping_masking_dugga.html
- DuggaSys/templates/curve-dugga.html
- DuggaSys/templates/html_css_dugga.html
- DuggaSys/templates/transforms-dugga.html
- DuggaSys/templates/transforms-dugga.js
- Shared/css/dugga.css
Fixes #6458 
Dugga templates affected:
- html_css_dugga
- transforms-dugga
- clipping_masking_dugga
- curve-dugga
These are the only ones I could find that were broken on smaller screens. There was also boxmodell but that dugga doesn't work without a variant which I couldn't find any examples for.
> Made some templates more mobile friendly

- DuggaSys/sectioned.php
In Edge some attributes seems to ignore padding in the svg.
Using margin instead of padding
#6741
> Fix Progressbar off grid #6741

- DuggaSys/diagram.php
- Shared/css/style.css
#6829 I'm not entirely sure about how the font is assigned here since i'm not that familiar with the font styling. I used a font that was implemented in `.markinglist` and it doesn't seem to be used anywhere but it works.
> Fix for issue #6829: Consistency suggestion with zoom buttons

- DuggaSys/diagram_objects.js
#6820 Function for putting in shadows on objects  exists here but the question is does it even work and should we keep it? Deleting dead code is easy in case supreme leader decides so.
> Fix for #6820 Remove shadows on free draw objects

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
#6784
```
// Generate ID for collapsing arrows
//var arrowID = item['entryname'].split(' ').join('').split(',').join('') + data.coursecode;
var arrowID = item['moment'];
```
IMO this doesn't contribute anything. If "item['lid'] is not obvious enough by it self, then I think that naming should be changed rather than adding a new variable.
> FIx: Wrong arrow changes in sectioned.php when expanding headings  #6784

- Shared/css/style.css
Issue #6824 Fixed. Now the zoom bar have the same styling in firefox and chrome
> Same styling in chrome and firefox

- DuggaSys/filereceive_dugga.php
Fix #6895 
Now possible to upload .rar files
Test with the Rapport template
> Added .rar files to allowed file extensions

- DuggaSys/contribution.js
- DuggaSys/contributionservice.php
- DuggaSys/templates/contribution.js
Fixes #6866 
Contribution will only throw an error if the timesheet table does not exist in the database. This simply handles the error by console logging a message saying that no such table exists.
You can simulate not having a timesheet table by changing row 537 in contributionservice.php:
`$query = $pdo->prepare('SELECT day, week, type, reference, comment FROM timesheet WHERE uid=:userid AND cid=:cid AND vers=:vers;');`
to:
`$query = $pdo->prepare('SELECT day, week, type, reference, comment FROM whatever WHERE uid=:userid AND cid=:cid AND vers=:vers;');`
> If no timesheet table exists in the database, contribution will load

- DuggaSys/diagram.php
#6882 
The toolbar labels are now removed and the buttons are ordered in the correct manner, as illustrated by a17vikab
Note that the 'draw square' button is removed since it will no longer be used
> Grupp a2019 w20 - Toolbar options in the wrong position #6882

- DuggaSys/diagram.php
- Shared/css/style.css
Issue: #6759 
Added a hotkey shortcut label to the delete option in the menu bar. Right now I have it as "Delete/Backspace" since you can delete an object with both hotkeys. But I can also change it to only "Delete" or maybe even "Del" if thats preferable. Let me know your opinion.
> Fixed issue #6759: Hotkey exists but not shown as a label in the menu bar

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
- Shared/css/style.css
Issue: #6224 
Old pull-request that did not make it into the last merge: #6702 
I created a new pull-request for the new branch I made since I ran out of time to fix the issue on the other branch before the last merge. Therefore when this pull-request is approved, we can probably close the other one.
I placed the tooltip in the bottom left tooltip box where it already shows the coordinates for the mouse pointer. The tooltip for the position of an object only shows up when developer mode is enabled by request and when an object is actually being hovered over. The tooltip does not work for free draw objects right now, a lot of issues appeared when I tried to implement that. Let me know if I should try and get that fixed.
> Fixed issue #6224: Tooltip for position of an entity (new branch)

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
I've tried to make the view options gray out correctly when disabled. I haven't fixed other issues like how you can still click on disabled options but that can be fixed in another issue or pull request. Because of that, the reviewer should ignore problems relating to clicking on disabled options. 
This PR makes the ER/UML options gray out when entering dev-mode and should make the A4 options gray out correctly.
> Fix for #6788: Gray out options correctly in view menu

- DuggaSys/codeviewer.js
- DuggaSys/codeviewer.php
Previously when changing font size for a document nothing happened when changing since the code did not exists. Added the code for it and it seems to be working.
You can test this by going in to the course "Packningsbyte på om606 med Bosse bildoktorn" and then the codeviewer dugga (or creating it yourself somewhere else.)
Small and big text
> Fixed changing font size in codeviewer  - Grupp c2019 w20 6925

- DuggaSys/contribution.js
Fixing issue #6973, commitranks are no longer hardcoded and get their amount value from the database.
> Adding db amount to interval

- DuggaSys/diagram.js
If you delete an object and add a new one it's not one with a duplicated name as it was before. It does not reuse numbers it only adds +1 to so there are no duplicates. This works on all objects.
_This is a partial fix of issue #6724 as all requirements are not done and couldn't solve the re-usage of deleted entities as it was complex._
> Removed acceptance of duplicates

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- Shared/css/dugga.css
Fixes #4959
Added a filter for filtering out duggas submitted after deadline in resluted. When clicking the cone icon, a filter called "Passed deadline" should appear. This filter should only show the orange duggas (late and pending)
Test site: https://a17alian.groupb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Filter for duggas sumbitted after deadline

- DuggaSys/diagram.php
- Shared/css/style.css
#6963 Tool tip for "Clear diagram" added according to the comment from the supreme leader.
> Fix for #6963 Shortcut for clear diagram

- DuggaSys/diagram.js
#6879
Removed the logic for disabling the 'draw line' functionality after a line had been drawn.
Now you can draw as many lines as you want.
> Removed logic for disabling 'draw line' after a line had been drawn #6879

- DuggaSys/codeviewer.js
- DuggaSys/codeviewer.php
- DuggaSys/codeviewerService.php
- Shared/css/style.css
Fixes #2277 
This PR adds a form when picking a template:
Which will update the boxes directly, eliminating the need to edit them separately.
Could be made prettier, but that's another issue maybe.
> Codeviewer: Added template options for faster workflow

- Shared/css/style.css
Made a fix for https://github.com/HGustavs/LenaSYS/issues/6142. The tooltips (in the fablist) next to the icons is now always shown. When you hover over the icons, the tooltips are 100% visible again. Solution shown below:
> Fix for #6142

- DuggaSys/diagram.js
#7040 remove creation of text object when double clicking. Additional: new Symbol(6) is changed to new Symbol(symbolKind.text); because the number 6 doesn't say anything.
> Fix for issue #7040 No more text when double click

- DuggaSys/diagram.js
Issue: #6933 
Added localStorage for storing if ER or UML mode is enabled, therefore when you refresh the page it should stay the toolbarstate mode that was enabled before refreshing the page. Instead of defaulting to ER mode every time.
If you go to F12, then the application tab and then to Local Storage you can see the toolbarState being stored there.
1 = ER mode
2 = UML mode
3 = DEV mode
> Fixed issue #6933: Added localStorage to toolbar mode

- DuggaSys/resulted.php
The ability to resize textarea has been removed. Fixes #7038
Before: 
After:
> Ladexport textarea fixed

- DuggaSys/diagram_objects.js
#6715 
Should now be fixed. The external background colors are now transparent and not connected to the inner entity/relation bodies.
> Background color for weak entities/relations fills the wrong frame #6715

- Shared/css/style.css
Issue #7081 Fixed. The position of the zoom buttons is fixed. They are centered. Addition to that solution the position of the range is also fixed
> Zoom buttons and range position

- DuggaSys/sectioned.php
- Shared/css/style.css
Fixes: #7082 and fixes #6755 (old w19merg issue, still not fixed) 
also removed 5px margin to make hamburger menu more aligned.
It should now be possible to navigate with hamburger menu and right-click to open the pages in an new tab. Just like the normal menu. 
Test site: https://a17alian.groupb.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732
> Hamburger menu navigation fixed

- DuggaSys/diagram.js
#7108 
Seems like the issue where the text boxes was given a new 'free draw' line was because of a displacement of the createFigure() method in the diagram.js file.
> Fixed text boxes #7108

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Issue: #6727 
Co-author: @a17jacsv 
All menu items are consistent with each other regarding mouse pointer and hovering options. When switching from developer mode you will switch to ER-mode.
> Fixed issue #6727: Not be able to enable menu-items that are disabled

- DuggaSys/diagram.js
Issue #7115 Fixed. The relation name is corect when copy paste
> Rekation name is correct when copy paste

- Shared/css/style.css
Fixes #7135 
The issue was that 'TopMenuStatic' overlayed the logout button. The reason it worked when the inspect window was open was that the menu moved down due to media queries.
> Added right margin to TopMenuStatic

- DuggaSys/diagram.js
#7105 
copied the properties array from the original object to solve this issue.
> Update diagram.js #7105

- Shared/dugga.js
Fixes #7092 
Should now work everywhere.
There is a comment in the event listener from 2015:
`//There is an issue with using this code, it generates errors that stop execution`
But I could not find any such cases, so I guess that comment is outdated.
> Made using escape key to close windows work

- DuggaSys/diagram.js
#7157
Added symbol attributes from the original to the copy. Fixes the issue where locked objects could not be copied.
> Update diagram.js #7157

- DuggaSys/codeviewer.js
- DuggaSys/codeviewerService.php
Fixes #7178 
Also trims the title, and makes sure it doesn't go over the max allowed characters (20).
Test by editing the title directly and then pressing enter.
> Codeviewer: Made title update when pressing enter

- DuggaSys/diagram.js
#7187 
The isLine attribute was the bad villain who messed with weak entities while they were shaken
> FIXED weak (copied) entities gets strong while they were shaken #7187

- DuggaSys/diagram_objects.js
Fix for issue #6504
Null pointer exception caused problems when having free draw objects and cardinality, simultaneously.
This is now, hopefully, fixed by adding this.corners() to the free draw class.
> Added corners function to free draw, Fix for issue #6504

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_forms.php
- Shared/css/style.css
#6905 
Instead of dealing with the hassle of having composite attributes separate to the "normal" attribute and changing to composite when drawing lines depending on which entities or attributes the attribute is already attached to, I have now entirely scrapped composite attributes and always allow them to be connected instead.
> Fix for issue #6905: Drawing lines between attributes should be allowed 

- DuggaSys/diagram.js
- DuggaSys/diagram_forms.php
- DuggaSys/diagram_objects.js
Previously one could set the cardinality for lines between attributes and for lines between entities and attributes. These should not have cardinalities so this PR removes the cardinality option for those cases. 
#6821
> Fix for #6821: Remove cardinality option for non entity-relation ER-lines

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
Issue: #6297 
**Co-author: @a17jacsv**
Added hotkey for all drop down options in the menu bar. Also fixed a class that contains all the styling for the hotkey labels to remove duplicate code in style.css. Added save and load hotkey labels in comment brackets even though the functions are not implemented yet. We choose the hotkeys we thought were appropriate and close to each other if they were similar in some way. Feedback on this would be appreciated.
> Fixed issue #6297: Map hotkeys to dropdown functions

- DuggaSys/diagram.js
- DuggaSys/diagram.php
**Issue: #7152** (related to issue: #6933 and #7089)
* When refreshing the page the chosen toolbar is loaded in from the local storage and works as it is expected to do.
* Fixed functions to remove duplicated code and stuff.
* Changed key binding to two separate key bindings to prevent duplicate switches.
**Co-author: @a16jenja**
> Fix: Saving what mode you're in doesn't quite work #7152

- DuggaSys/diagram.js
Fix for issue #7292
state is no longer saved after moving the canvas.
> State is no longer saved after moving the canvas, Fix for issue #7292

- DuggaSys/resulted.js
Fixes #7231 
Made it possible to have blankspaces when searching in the resulted view.
e.g markg: färgduggor1hp is now possible but before you needed to be exact with the searching like this:
markg:färduggor 1hp.
works on names to like "sv e n" or "l e i f"
link: https://a17oscno.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
edit: the aditional blankspaces in the code are a result of "auto indenting" in Atom if it is a problem then "sugest" a change to remove it and i will accept it.
> Grupp b2019 w21#7231

- DuggaSys/diagram_objects.js
https://github.com/HGustavs/LenaSYS/issues/7319
Fixed so that calculation of middleBreakPointX and middleBreakPointY is correct. Turns out I didn't correctly understand the use of Math.abs() when I first wrote the code.
Fixes this issue that happens when moving a class off screen on the Y axis.
> Fix for #7319: UML line code

- DuggaSys/filereceive_dugga.php
Fixes #7308 
The week value being inserted in the database should now be the course week, based on the start date of the course. If no start date is found it will be set to 04-01 of the current year.
Test by uploading data from the daily minutes dugga, and check if the week is correct in the contribution table.
> Changed timesheet week to course week

- DuggaSys/diagram.js
#7183 Snap to grid snaps the top left corner of the clicked object and only moves the others without snapping. This is according to the wishes of @a15tobli .
> Fix for #7183 Snap to grid works according to requirements

- DuggaSys/contribution.js
- DuggaSys/contribution.php
- Shared/css/style.css
This is a new suggestion for issue discussed in #6839. 
This soultion has scrapped the icons and continued with the more text based approach. 
From start when the page is first loaded it checks if a key in localstorage exists and either load a defualt value which will keep every contribution tab open or load from the already existing values from localstorage. This will provide the possibility to choose if you want to see all the content or hide some of them. 
Here is a image when you first load the page (with no existing localstorage key):
Closed some of the tabs by clicking on the text "Made 3 commit(s)" etc.. :
The solution supports the possibility to choose which div/label to keep open. This gives the opportunity to hide everything, keep some tabs for a specific week oppend or keep all …
> Suggestion for github contribution appearance

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
#7333
Fixed the shortcuts
**Changes:**
Name change: Add group to selected -> Group objects
Name change: Remove group from selected -> Ungroup objects
hotkey change: Reset view to origin: from shift + 0 to shift + O
**Removed shortcuts:**
_FILE_
Shift + S for save
Shift + 0 for load
Shift + i for import
_EDIT:_
shift + G for global appearnace
shift + H for change appearance
alt + 1 for add group to selected
alt + 2 for remove group from selected
shift + 0 removed from reset view to origin
_VIEW:_
shift + B for display all tools
shift +5, 6, 7 for toggling A4 properties
_ALIGN:_
shift + K for snap to grid
shift + , for horizontal center
shift + . for vertical center
_DISTRIBUTE:_
shift + z for Horizontal
shift + < for Vertical
_HELP:_
shift for lock object proportions (row removed entirely)
> Fixed shortcuts #7333

- DuggaSys/diagram_objects.js
> Fix for issue #7393: Creating freedraw by right clicking doesn't update the linewidth for the new object 

- DuggaSys/diagram.js
- DuggaSys/diagram_forms.php
#7312 
This issue had to do with trying to set cardinality options for lines that doesn't have cardinality, therefore the error message. I changed so that cardinality options and line direction options are only set for the lines that have these options.
> Fix for issue #7312: Error message when double clicking line 

- DuggaSys/codeviewer.js
Fixes #7402 
Hides  this button:
For boxes that are 'minimized'
> Hide copy button when box minimized

- DuggaSys/codeviewer.js
> Fixed tokenizer handling of backslash-characters in strings

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
#7222 
The issue does now appear to be solved. There may be combinations that we have not thought about so be thorough when testing to try and find the edge cases where this may fail.
However, none were found before making this pull-request so hopefully, this works fine.
All of these attributes can now be used in Global Appearance to set the settings for current objects, and the settings for future objects to be drawn:
_Font family
Font color
Text size
Fill color
Stroke color
Line thickness_
UML objects are intentionally excluded
> [Fixed] Change the Global Appearance Functionality #7222

- DuggaSys/codeviewer.js
Fixes #1818 
To test this you need a file containing strings. Upload a file with fileed, HTML for example, and edit some words to have double and single quotes.
Next, go to Example settings and add those words to the 'Important words'. This should work with all of these cases:
- "word" highlights "word"
- "word" highlights  'word'
- 'word' highlights "word"
- 'word' highlights 'word'
- word highlights "word"
- word highlights 'word'
> Made important word highlighting work with strings

- DuggaSys/diagram.js
Issue #7347 Fixed. Added the functionality to deselect the different buttons in the toolbox by pressing the escape key.
> Issue #7347 Deselect toolbox options

- DuggaSys/diagram.js
#7406 
Using shift+d or shift+m when inside developer mode will now switch to the mode that you were in before activating developer mode regardless of which mode you were in inside developer mode.
I also changed the spacing so that it fits the rest of the if statements above
> Fix for issue #7406: Moving "Developer mode --> ER --> UML" with one shortcut 

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Issue: #6634 
Related issue: #6726 
**Co-Author: @a17jacsv**
Removed old solution and disabled contextmenu when right-clicking on the canvas. It should work on both mac and pc now as we have tested it on a different kind. Removed some unnecessary code as well.
> Fixed issue #6634: Problem with selecting object after using right-click-move

- DuggaSys/contribution.js
Working with issue #7414
rank and groupRank is average of the ranks. so sum divided by 5 (hardcoded since it should always be 5). However sortaBleTable have some floating point issues and could use some extra rounding and fixing.
There is a rounding error but we are fairly certain that is because of floating points and would need to be dealt with in sortableTable, making some sort of param to set decimals and having it round in sortableTable instead of in the makeSum function.
Co-Authored-By: Robin Eskilsson <a17robes@users.noreply.github.com>
> Added sum to personal Rank

- DuggaSys/codeviewer.js
- DuggaSys/codeviewerService.php
- Shared/dugga.js
Fix #7381
Now throws this error:
> Added ajax error handling for codeviewer

- DuggaSys/codeviewer.js
- DuggaSys/codeviewer.php
- DuggaSys/codeviewerService.php
- DuggaSys/sectioned.js
Fixes #1009 
To do this: go to a code example, click the cog wheel, click remove. You should be redirected to the section page, and the code example should be gone.
This will delete everything from several tables with the exampleid in question, but I'm sure this can be done more elegantly if we add `ON DELETE CASCADE` to the `box`, `improw`, and `impwordlist `tables.
> Added way to remove examples

- DuggaSys/diagram.js
#7027 Text boxes are created with click only. No more drag and get an illusion of creating a custom sized text boxes.
> Fix for #7027 Fixed size for text boxes when creating them

- DuggaSys/diagram.js
> Fix for issue #7464: Dragging objects when only one is locked doesn't work correctly 

- DuggaSys/codeviewer.js
- Shared/css/whiteTheme.css
> Made sidebar sticky

- DuggaSys/contribution.js
- Shared/SortableTableLibrary/sortableTable.js
Fixes #6877 
Now possible to use 'hasFooter: true' in the sortable table constructor if a footer is wanted.
> Added hasFooter parameter to sortableTable

- DuggaSys/diagram.js
Issue #7029. Fixed so that the cursor no longer changes while hovering over the points for the objects on the canvas while drawLine is selected.
> #Issue 7029 Fixed cursor on hovering points when drawLine is selected

- DuggaSys/accessed.js
Fixes #6225 
This only works in access but could be copied and implemented in other areas.
> Made search case insensitive, and supported åäö

- DuggaSys/diagram.js
Issue #7470 Fixed so that the crosses are now removed when canceling the free draw
> Issue #7470 Remove crosses when pressing Esc in Dev mode

- DuggaSys/diagram.js
- DuggaSys/diagram.php
**Co-Author: @a16jenja** 
Issue: #7500
Disable menus that don't meet the requirements for use. 
Also, prevent all menu items to collapse when clicking at them.
As we see it the menu item "Global appearance" should be able to be clicked at even when no symbols are selected. The user should be in our opinion, be able to set all the customization before starting to draw the diagram. That's why we made no changes to it. Let us know your thoughts on this @a14oscna.
> Fix for #7500: Disable menus that don't meet the requirements for use

- DuggaSys/codeviewer.js
- Shared/css/codeviewer.css
Fixes #470 
Collapses and restores blocks (only works on { } blocks). Could maybe hide the buttons until the user hovers over the row if that is something we want.
> Added tree support for codeviewer

- DuggaSys/diagram.js
Previously the Shift+T shortcut only activated under the ER mode. Now it activates under every mode. 
Fix for #7599
> Fix for #7599. Enabled "Add text" shortcut for every mode in diagram

- DuggaSys/contribution.js
fixing #7609. tablebody didn't exists so would always default to false and not render the table. change it to tblbody which does exists so now the table should display at the bottom of the page again if there is timesheet data.
> timeSheetTable should now render with data

- DuggaSys/contribution.js
Fix for #7616, the sum can now be seen as the footer is back again!
> Added footer back to allrank

- DuggaSys/diagram.php
- Shared/css/style.css
Issue: #7610 
Changed arrows. This was the best option I could find that worked for all browsers and OS. Now it's more visible and user-friendly.
> Fix: #7610 Shortcuts barely visible

- DuggaSys/diagram.js
#7662 
Changed spacing as well
> Fix for issue #7662: Opening appearance dialog for text objects doesn't save the previous values 

- DuggaSys/codeviewer.js
Clicking minimize wouldn't hide the copy button, now does. Note that the minimize button only appears on template 1 and 2
> Fixed hiding of copy button when clicking minimize

- Shared/dugga.js
Fixes #7789.
Prevents message of the day from showing after administrator changed the message.
Before, the message relied on being one row as it would appear behind the header. On small screens, there is a big risk of the message being multiple rows making it show parts of it below the header.
Uses the height of element when button is clicked to force it outside the screen with the right amount of pixels.
Function returnedCourse in courseed.js will be called whenever a change is made in courseed, which will automatically show the message again even if hidden before. This is because same function is used to show the right things when site is loaded. This workaround prevents it from appearing.
> Prevented long MOTD to be half shown after change

- DuggaSys/courseed.js
- DuggaSys/courseed.php
- DuggaSys/courseedservice.php
Inserts the right value of read only to the database table settings based on the checkbox (0 -> unchecked, 1 -> checked). Before 0 was always inserted.
Made checkbox represent the previously made setting change by being checked (value in database 1) or unchecked (value in database 0) when settings popup is loaded.
-Test if the checkbox stays checked after page reload if saved as check and if it stays as unchecked if saved as unchecked. It is based on what is in the database so should not be a need to check in the database if it is correct there.
> G4 2020 w14 issue#7812

- Shared/database.php
Fixed so notice saying "MYSQL_VERSION already defined" in #7868 can not appear and break design by checking if global variable already defined or not and only defining it if it is not defined.
-Test if notice "MYSQL_VERSION not defined" can appear.
> G4-2020-W15-ISSUE#7868

- DuggaSys/resulted.php
Removed inline css for scroll on MarkCont-element. Now uses value from style.css (scroll: auto).
This makes the scrollbar only appear when scrolling is needed (before it would be displayed by default).
Solves #7448.
> Removed unnecessary scrollbar in ResultEditor.

- DuggaSys/filereceive.php
Now checks if the `fileinfo` extension is enabled by checking if the function exists, if it doesnt it uses the file type given on upload. This stops the application from breaking on a new system without the right `php.ini` settings.
> solution for fileinfo extension

- DuggaSys/courseed.js
Updated function for selecting course to also convert to swedish when selecting. Can be tested by editing courses on homepage and giving them names with the letters ÅÄÖåäö.
> Fixed so that swedish characters are loaded correctly, issue #7839

- DuggaSys/fileed.php
- Shared/css/style.css
- Shared/markdown.js
The solution retrieves the files corresponding with the course which the users is currently navigated to, these are shown in the menu. The files are retrieved from the database. 
Once selected the following text below will be created. The file path created point toward the location where all files are created(not working in our version), i.e. directly under lenaSYS in the directory courses. Is the courses directory each course get their own directory which are named according to the course id. The png file shown in the example below belongs to the course with the course id 2. Which can be seen in the file path.
> Added selection menu for course local image files in markdown editor - G1 2020 w15 #4744

- DuggaSys/diagram.js
Alignment menu should be grayed out as long as there is less than two objects selected and the same goes for the shortcuts. Requirements for the alignment is to have at least two objects selected. 
It should now be impossible to use the alignment and the distribute options when theres only one or no object selected. It should be accessible once you have selected at least two objects in the diagram
> G4 2020 w15 issue#7646

- DuggaSys/diagram.js
The state of the canvas is now saved when the distribute function is used.
Result of this is that the canvas should save the changes after distributing the objects and the user refreshes quickly after.
> State is now saved when distribute function is used

- DuggaSys/diagram.js
Drawing a UML-line changes uimode to "CreateUMLLine", but if the line is not drawn uimode is never changed back to "ChangeLine" and thus does not pass any checks until the button is pressed again and uimode is changed back. This was solved by simply adding the line "uimode = "CreateLine";" where the check occurs if the line is drawn to an empty spot. This enables you to draw a new line to another class.
> Solved issue#7664, UML-diagram line problem

- DuggaSys/diagram.php
- DuggaSys/diagram_IOHandler.js
A export option has been added to export the diagram in a4 format. The issue was assumed to be solved as HGustavs comment above mentions "Svg export with limit to certain page/coordinate combo". Solution does also download the appropriate oriantation(portrait, landscape) depending on what option has been selected in the view options(Display virtual A4 -> Toggle A4 oriantation).
This solution only downloads the first A4(top left) in the canvas since including more would break the A4 format and make the A4 format export pointless.
> An option has been added to download the diagram in A4 size

- DuggaSys/diagram.js
As of before fix, several lines could be drawn between the same attribute and the same relation. 
In diagram.php it should be impossible to draw multiple line between the same attribute and the same relation. This might be hard to test since the lines are placed in the same position. Before when the user drew multiple lines between the same relation and attribute the lines were lumped together. The picture below illustrates this.
Now it should look more like the picture below even when the user tries to add more lines.
> G4 2020 w15 issue#7647

- Shared/markdown.js
Changed a faulty regEx so it does not match with the characters '3' , '{' and '}'.
Co-Authored-By: a16vikva <a16vikva@users.noreply.github.com>
The screenshot shows the ordered list now working in markdown preview on the fileed.php page.
> Changed markdown.js

- DuggaSys/codeviewer.js
This issue has been solved by removing the ability to edit the title by clicking on it. The only way to edit box titles now are by using the "Edit Content"/"Edit Box Settings (The cogwheel button).
> Fixed Issue#7046

- DuggaSys/accessedservice.php
Added string replacers to change the HTML encoded letters back to the original latin letters "åäö" before updating the database.
> #7886 Fix problem were HTML encoded letters got into the database.

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Fixes #5920 
According to issue #5920 alignment with free drawn objects is broken. Comments mentions that an exception for path objects is probably the best solution here. This exception was implemented, aligning now should move all object accordingly while ignoring to move free draw objects.
Snap to grid was also broken on free draw objects, so a fix was made so that free draw object now also snaps to grid when moving it instead of breaking like before.
> Alignment with free draw objects fix

- DuggaSys/sectioned.js
You can no longer open the fab button menu when pressing on the background in mobile view. You have to press the "+" button.  
Closing#7871
> Fab button mobile view fix for ISSUE#7871

- Shared/loginbox.php
The exit button does now have a pointer-cursor on the alert for "Your session has timed out".
> Added the class cursorPointer to the exit button. #7923

- DuggaSys/filereceive.php
Made all the extensions lowercase, because the problem was that when they were uppercase the server did not accept them.
> Made it possible to upload PNG/GIF/JPG

- DuggaSys/diagram_forms.php
Adding labels allowed for styling of the text (adding margins). There is now more space between the different elements. The labels also help screen readers and allows you to click the text instead of the box to focus on the input-textbox.
> Fixes issue#7728, spacing in UML appearance menu

- DuggaSys/diagram.js
solves issue#7649
Savestate() is now only triggered when objects are actually moved by the align and distribute functions.
Test by using these functions while having console open. The "State is saved" log should only appear when objects are moved
Edit: v2 created since last commit was not branched from the latest version of the weekly branch.
> SaveState() is now only triggered when objects are actually moved when using align/distribute

- DuggaSys/diagram_objects.js
Aligning text left/right makes text go outside of the text box. When creating a textobject in diagram.php you should now be able to align the text left, center and right without the text going outside of the textbox. This should work for all font-sizes. 
What the issue forgot to mention is that text-alignment is affected by the zoom function. This issue should also be resolved. The text should not change position depended on the zoom.
Before: 
After:
> G4 2020 w15 issue#7653

- DuggaSys/diagram.js
If the appearance menu is closed with escape key you can now still delete objects with backspace or delete keys.
> Fixes issue 7847, closing appearance menu with escape then deleting objects with delete

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Made it so when an entity has a recursive relation with itself the lines appear on the sides instead of on the same edge of the relation. This should make cardinalities collide less.
Should look like this: 
It should work from all directions and when moving the objects around. 
Closes#6209
> Fixed lines between relations and entities issue#6209

- DuggaSys/diagram.js
When you close the menu to edit the appearance of an UML-element with the escape key, it is now possible to delete an object with the delete or backspace keys.
> Fixes issue 7847, closing apperance menu with escape locks delete and backspace

- DuggaSys/sectioned.js
- Shared/navheader.php
Old code that was lost reimplemented. There should be a button in the header for courses that look like this (Can only be seen as teacher):
The button should lead to an external teacher site for the course.
> Reimplemented old issue that disappeared in weekly merge #7784

- Shared/dugga.js
Fixes #7789.
Prevents message of the day from showing after administrator changed the message.
Before, the message relied on being one row as it would appear behind the header. On small screens, there is a big risk of the message being multiple rows making it show parts of it below the header.
Uses the height of element when button is clicked to force it outside the screen with the right amount of pixels.
Function returnedCourse in courseed.js will be called whenever a change is made in courseed, which will automatically show the message again even if hidden before. This is because same function is used to show the right things when site is loaded. This workaround prevents it from appearing.
> Fix for message of the day covered once after edit, issue #7789

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
Styling fixed for the input type="file" button. The button "Välj fil" now has the same styling as all the other buttons. When selecting a file the labeltext changes to the filename. 
Before:
After:
> Fix for styling in import-dialog issue#7618 

- DuggaSys/diagram.js
Chrome should also zoom in steps of 10% when scrolling in the diagram now.
> Changed it so chrome also zooms in steps of 10% #7614

- DuggaSys/diagram.js
Fixes #7679
Camera position and zoomValue is now saved in localstorage, and is used to restore the same camera position and zoom after refreshing the page.
> Camera position(including zoomValue) is saved and persists when refreshing page

- DuggaSys/codeviewer.php
- DuggaSys/courseed.php
- DuggaSys/sectioned.php
The issue https://github.com/HGustavs/LenaSYS/issues/7507 wanted a solution to prevent the alert being triggered even though the user is active on the site. 
To solve this the session cookies which holds the time when the alert is suppose to trigger instead now gets refreshed by the user navigating the site. Refreshes takes place when navigating to codeviewer.php, courseed.php, and sectioned.php.
> Implemented refreshing of session cookies when user is active - G1-2020-W16-#7507

- DuggaSys/diagram.js
Fixes #7675
Before when zooming, the A4 dashed lines when using "Display virtual A4" would be inconsistent and sometimes connect to a solid line. This fixes that issue by using the pixelsPerMillimeter value.
> A4 dashed in all zoom modes

- DuggaSys/resulted.php
By moving the div "titles" from outside the div "resultedFormContainer" to inside, the issue where the H1-tag "Result" dissapears is fixed and now follows the scroll.
> Fixed issue where "Result" does not follow the horizontal scroll

- DuggaSys/templates/dugga4.html
Changed justify-content: flex-end to center. To make the container to the center instead of being on the right.
Co-Authored-By: b18jonli <b18jonli@users.noreply.github.com>
> Changed justify-content to center. #7400

- DuggaSys/fileed.js
- DuggaSys/fileed.php
Fixed the fab buttons on the files page in mobile view so that they show up when you press the +. You also need to _only_ press the +, and not anywhere on the screen.
You can still **close** the fab buttons by clicking on the background but that is not an issue as it's usually how things are on mobile.
> Fixed the fab buttons on the "files" page in mobile view from issue #8072

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
There will no longer be a reference error in the console, and the "Deadlines" tab should also be working again. FabBtn should now be fully functional without errors.
> Fix for issue #7999 for the reference error, as well as the "Deadlines" tab

- Shared/css/style.css
Changed opacity for text beside buttons inside fab-button.
> Fixed Issue#7519

- Shared/dugga.js
In this issue they complained that the "expiremessagebox" was covered by "endsessionmessagebox" as seen below.
Now with the added code it looks like the GIF below instead which solves the "weird" boxes.
> Fixed issue for branch: G1-2020-W17-ISSUE#4048

- Shared/css/codeviewer.css
Fixed the mergin and the header of codeviewer in the mobile layout
> G1-2020-W17-ISSUE#8102

- Shared/css/style.css
Buttons now have a border with same color as the background color. When a button is selected and the background color change, the border will become visable.
Before: 
After:
> fix ISSUE#7147 New border when buttons selected

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Made a general function for submitting the appearance form to simulate enter click and button click. Only these two ways of closing the appearnce menu should save the state as of now. Removed old jQuery eventlistener and merged this check into the keyDownHandler vanilla JavaScript eventlistener.
> Fixes issue #7531

- DuggaSys/diagram_objects.js
**for Testers**
1. Open http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%237391/DuggaSys/diagram.php
2. places some ER symbols
test save states after refreshing the web page, this issue relates to save states so just move objects will trigger a save state. from my testing I could only trigger the error after refreshing a page, so I think this issue somewhat related to localstorage.
Link to Issue #7391
> Issue#7391 Solved

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Added functionality for menu item "Camera view" so uou can now enter camera mode without using keyboard shortcuts. Ready for testing
> G4 2020 w17 issue#8127

- Shared/css/style.css
Removed the fixed top position so the labels appear dynamically next to the buttons.
Before:
After:
> fix ISSUE#7559 position of button labels 

- DuggaSys/codeviewer.js
Fixed the bug with specific important words. Events will no longer be highlighted as important within document examples in codeviewer. 
Testing may be required since there is no popup redirecting to a google search when I click on an important word in a document example but when testing on a18wilis end this works. 
How to test: add for example "onclick" and "hello" (if your example contains the word hello) to the important word list. See issue #8094
> G1 2020 w17 issue#8094

- DuggaSys/showdoc.php
- Shared/markdown.js
Removed commented out code so that markdown would recognize that a table is created.
Alignment now works and it works together with lists (both unordered and ordered). It follows standard markdown syntax for tables.
> g1-2020-w17-issue#7955

- DuggaSys/diagram.js
Added an if-statement to check if snap to grid is on when the arrow keys are pressed, and added code to move the object along the grid instead of freely when using arrow keys and snap grid is on.
For testers: Place an object and activate snap to grid, then move it around with the arrow keys. The object should still snap to the grid and not move freely.
[Issue 6878](https://github.com/HGustavs/LenaSYS/issues/6878)
> Solves Issue 6878 - snap to grid with arrow keys

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_IOHandler.js
- Shared/css/style.css
The code of initialization functions were improved. The canvas in now created in markup inside of the container instead of from JavaScript. This makes it easy to also move all buttons that should be on top of canvas (moveButton, zoom, coordinates right now) inside of container to be positioned absolute relative to the container. Code that makes no difference to call in certain situations were removed and some functionality were moved to one place instead of unnecessary doing the same thing multiple times. A general function calling all initialization functions after document body finished loading was created instead of having all of the functions in HTML. This makes it easier to get an overview of what is called onload and to navigate to the different functions in JavaScript.
As a bonus …
> Fixes #8196 - improving code of initialization functions

- DuggaSys/accessed.js
- Shared/css/style.css
- Shared/navheader.php
Before when you hovered over the button the dropdown would close before you would reach it with the mouse.
> Dropdown behaving correctly now in results #8122

- DuggaSys/sectioned.js
It is now possible to close the "new course version" and "edit course version" windows with the **ESC** button.
These buttons:
And these windows:
> Close the "new course version" and "edit course version" windows with ESC button, fix for issue #7385

- DuggaSys/sectioned.js
To test: Create a message in a course, add a link, mouse over the warning triangle, it should say "Important message".
> Added mouseover text to warning triangle

- Shared/css/style.css
- Shared/navheader.php
Changed the right margin of menu icon so that there's a clearer difference to add clarity and separation.
Also made the icons slightly smaller.
> Changed the right margin of menu icon, fix for issue #7657

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Fixes #7560 
First and second object in appearance menu for UML-lines/relations now shows the connected objects names instead of "First object, Second object".
> Better explanations in options for UML line

- DuggaSys/diagram.js
Test if move button can be visible when not being in move mode by activating move mode, switching to a different diagram mode (UML, ER or DEV) and see if you will still be in move mode with the button visible (success) or if you will be in normal mode with the button visible (fail).
Also minimized related code that was repetetive to look much cleaner.
Link: http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%238200/DuggaSys/diagram.php
> Fixes #8200 - Move button active when not in move mode

- DuggaSys/accessed.php
- DuggaSys/duggaed.js
- DuggaSys/fileed.php
The headings in fileed, duggaed and accessed have been positoned to the left and had their names changed to be consistent with other headings' positioning and naming conventions.
Co-Authored-By: a18ismca<a18ismca@users.noreply.github.com>
> Inconsistensies with positioning and naming of certain headings fixed

- DuggaSys/fileed.php
The sub-heading on fileed has been changed from "Files" to "Edit files". Its position has been changed from center-align to left-align, with some margin to the left.
> Redesign of sub-heading on fileed page, fixes issue #8172

- DuggaSys/codeviewer.js
Windows can now be resized at all times(I expect) and no errors are thrown either. Error was caused by the AlignBoxesWidth function that tried to hide/show a Clipboard button even when the box didn't have one, which then caused the error and probihited the windows from resizing.
Now the code checks if the box is a codebox(has a Clipboard), before trying to hide/show the Clipboard.
> G1 2020 w17 issue#8128

- DuggaSys/codeviewer.js
Added relevant documentation to popup-windows for when users click on
highlighted HTML-events.
Test by uploading/editing a .html-file to contain a HTML-event (e.g. <div onclick="test">). Add a HTML-event to the important word list (Must be an event that exists within "HtmlEventArray" in codeviewer.js in order to work) and then click on the event. A popup should appear which displays a page containing information about the event.
Co-Authored-By: a18geoge <a18geoge@users.noreply.github.com>
> Added event-documentation to PopupDocumentation

- Shared/css/style.css
> The text is no longer cut off.

- DuggaSys/accessed.js
- Shared/SortableTableLibrary/sortableTable.js
- Removes error (fixes #8216 )
- Enter now updates group dropdown if pressed with dropdown checkboxes open
- Removed unnecessary code row in MouseUp function (should not change functionality)
> Removed error related to enter-keylistener in accessEd 

- DuggaSys/diagram.js
Fixed the problem of zoom value going back to 100% +- 10% on zoom in or out after the page has been refreshed. Zoom value and camera position is after a recent implementation stored in local storage and loaded on page refresh. The range slider for zoom did however not get the zoom value loaded from local storage which makes it be 100% as default while the zoom being shown on page refresh is loaded from local storage.
-Test if the zoom after page refresh works as expected. If the zoom was 50% when refreshing it should after page refresh be 50% and go to 40% on zoom out and 60%.
Link: http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%238254/DuggaSys/diagram.php
> Fixes #8254 - Set loaded value on zoom range on initialization

- DuggaSys/diagram.js
Deselects the active element when hovering another dropdown so it doesn't stay open, meaning you can't click one and hover another to have two open at the same time.
See issue for picture of overlap.
> No longer opens two dropdowns #8099

- Shared/dugga.js
First and foremost it solves issue #8203 
It also changes the variable `expireDate` in both functions `setExpireCookie` and `setExpireCookieLogOut` to a constant. Plus some minor changes to the comments.
To test this one change the following lines in `dugga.js` to the following: 
I had some minor issues testing this on my browser. You might have to:
- Clear the cache
- Restart the server
- Reinstall LenaSYS (after making changes to dugga.js)
> #8203 Fix - Update dugga.js

- Shared/css/style.css
This pull request adds padding to the enumeration column in both accessed and resulted. See issue #8146 for a more detailed explanation of what to look for.
> G2 2020 w17 #8146

- DuggaSys/duggaed.js
Adds functionality for toggling visibility and actions of FAB-button which means the user can now click "through" the FAB-button when it is in low visibility-mode (see screenshot). This currently only affects the Dugga Editor. 
**Note:** to test this you will need to add "&cid=2" (the 2 should be whichever course you're currently viewing). Otherwise the table content will not be loaded (this is being fixed with another pull request).
This is currently toggled using the Ctrl-button. Since Ctrl is used for many global actions (Copying, Pasting etc) it's possible the keyCode used should be changed to decrease confusion (currently the visibility is toggled when copying or pasting something on the page).
Tested in Chrome and Firefox during development. There is no info to the user that this is …
> added function for toggling visibility of FAB-button in Dugga Editor

- DuggaSys/diagram.js
Simple fix to prevent a mutation of a free-drawn object to occur. When the user is in mid-drawing and changes modes (for example create attribute) the drawing should be cancelled instead of creating a mutation. 
Before: 
After:
> fix issue#6429 prevent a mutation of a free-drawn object

- Shared/SortableTableLibrary/sortableTable.js
- Shared/css/style.css
The main problem was the poorly formatted text in the headings. It was fixed by removing some padding in style.css. 
On top of this we also lowered the line-height to make the table head look a bit cleaner and we also adjusted the max width to keep the th-elements consistent. 
This makes the ellipsis come in to use a bit sooner and removes some of the text in the th-elements.
But this is not supposed to be a problem since the teachers only need the beginning and the end of every dugga name. 
Co-Authored-By: b18fella <b18fella@users.noreply.github.com>
> Fixed table styling issues

- Shared/css/style.css
The coordinates element does now move to a more appropriate position on smaller screens to not be behind zoom element.
Link: http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%238169/DuggaSys/diagram.php
> Fixes #8169 - Move coordinates element on small screens

- Shared/css/codeviewer.css
Now it is no longer visible, like it should
> Solution for branch G1-2020-W17-ISSUE#8282

- Shared/css/template8.css
Height is now important, wont be affected by the other boxes.
> Solution for branch G1-2020-W17-ISSUE#8279

- DuggaSys/codeviewer.js
- Shared/css/codeviewer.css
This fix only removes the description when screens are resized to make sure min max and reset are still possible to be clicked.
To make the best possible solution a bigger rework of the menu should to be done by not using a table. This however looke better than overlapping and doesn't "destroy" the graphic in the same way as before.
Also removed some redundant css.
> G1 2020 w17 issue#8202
