HGustavs/LenaSYS

- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/7279
> Remove fixed height from loginBox close button

- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/7337
> Fix minor style.css syntax errors

- DuggaSys/diagram.js
- Shared/css/style.css
> Fix for issue #7268: Move-grid-button is placed wrong again 

- DuggaSys/diagram.js
- DuggaSys/diagram.php
> Toggle is now back in place, Fix for issue #7314

- Shared/SortableTableLibrary/sortableTable.js
> Fixed not being able to sort strings in accessed

- DuggaSys/diagram.js
#6712 Update mouse info before doing all the good stuff a click and double click performs.
> Fix for #6712 Prevent creation of objects in objects

- DuggaSys/contribution.js
Removed counter columns for two of the tables in contribution. Fixes issue: https://github.com/HGustavs/LenaSYS/issues/7306
> Fix for #7306

- DuggaSys/showDugga.php
- Shared/css/style.css
> Mobile: "Access denied"- text found

- DuggaSys/diagram.js
- DuggaSys/diagram.php
> Fix for #6991 Clicking dev tools no longer collapses the menu

- DuggaSys/diagram.js
> Revert "Fix for #6991 Clicking dev tools no longer collapses the menu"

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Fix for issue #7275
Merged mouse functionalities as well
> Can now end free draw with right click, Fix for issue #7275

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
#6521 
Added that new objects have the current line thickness and that the dialog shows an updated value.
> Fix for issue #6521: Global appearance menu should be updated with current line thickness 

- DuggaSys/diagram.php
#6991 Do not pass go. Do no collect $400. This one is tested already and works tested by @a17johpe
> Fix for #6991 Restoring merge hick up

- DuggaSys/diagram.js
#6991 Additional code for @a14oscna
> Additional fix for #6991

- DuggaSys/contribution.js
Fix for https://github.com/HGustavs/LenaSYS/issues/7390.
> Contribution: Removed counter on "contribTsTable"

- DuggaSys/diagram.js
#7362 No more toggle while the dialog is active and it's not possible to switch to the mod you are already in. This is a new pull request to replace #7369. Same code but different base.
> Fix for #7362 Switching modes bugs fixed

- DuggaSys/diagram.js
- Shared/css/style.css
**Co-Author: @a16jenja** 
Issue: #7015 Scale zoom-bar when minimizing the window
Issue: #7017 Make coordinates-bar scale in developer mode.
Removed coord-bar from user-mode.
Added media queries to zoombar & coord-bar (dev).
> Fix for: #7017  & #7015 

- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/7387
> Adjust loginBoxHeader X button padding

- Shared/css/style.css
**Co-Author: @a16jenja** 
Issue: #7413
> Fix #7413 Changed width of zoom label

- DuggaSys/contribution.js
handle issue #6455 and is related to this pullrequest #6873.
> Fix and update for a problem that was destroyed in the merge

- DuggaSys/accessed.js
- DuggaSys/accessed.php
- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
- DuggaSys/fileed.js
- DuggaSys/fileed.php
- Shared/css/style.css
Fixes  #6677
Taking reasulted as inspiration.
> Adding searchbars in mobile view

- DuggaSys/diagram.js
Fix for issue #7424, Seems to be related to hoisting.
> All targeted objects are now movable, Fix for Issue #7424

- DuggaSys/diagram.js
- DuggaSys/diagram_IOHandler.js
- DuggaSys/diagram_objects.js
Fix for issue #7181
Global object id is saved to localStorage and retrieved in correct order.
> Global object id added, Fix for issue #7181

- Shared/css/style.css
Fix for issue #7364, the zoom and coordinates bar have now swapped position.
> Change position of zoom and coordinates bar, Fix for issue #7364

- Shared/css/style.css
> Revert "Change position of zoom and coordinates bar, Fix for issue #7364"

- DuggaSys/diagram.js
- DuggaSys/diagram_IOHandler.js
- DuggaSys/diagram_objects.js
> Revert "Global object id added, Fix for issue #7181"

- DuggaSys/resulted.php
- Shared/css/style.css
Fixes #7378
Also changed some inline styling to external
> Improved mobile functionality on resulted

- DuggaSys/diagram.js
- DuggaSys/diagram_IOHandler.js
- DuggaSys/diagram_objects.js
> Revert "Revert "Global object id added, Fix for issue #7181""

- Shared/css/style.css
> Revert "Revert "Change position of zoom and coordinates bar, Fix for issue #7364""

- DuggaSys/diagram.js
#7411 This is spaghetti programming. All that surrounds the toolbar. Strong suggestion to refactor this and make it easier in the future. @a14oscna Should I write such issue?
> Fix for #7411 Show correct toolbar when switching

- DuggaSys/contribution.js
- DuggaSys/contribution.php
sovles issue #7134 and related to pullrequest #7202
> Fix and made some updates on the table that was destroyed in the merge.

- DuggaSys/duggaed.js
Fix for issue https://github.com/HGustavs/LenaSYS/issues/7441
> Fix capitalization of Last Modified in duggaed

- DuggaSys/contributionservice.php
> No errors in contribution when not logged in

- Shared/css/style.css
Fix for issue https://github.com/HGustavs/LenaSYS/issues/7452
> Add padding to contribheading

- DuggaSys/contribution.php
Fixes #7352 
Should now be impossible to directly navigate to contribution.php.
> Entering contribution.php directly will now redirect

- DuggaSys/resulted.js
Fixes #7376 where the searchbar broke, this should work now.
Testbranch: GruppB2019W22#7376
> Made searchbar compatible with examinatorfiltering

- DuggaSys/resulted.js
Fixes #7382 
It now works to sort on firstname again with the dropdown menu.
link: https://a17oscno.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Grupp b2019 w22#7382

- DuggaSys/diagram_objects.js
Fixed if statement in movepoints function, to accomodate umlLine.
Relevant to issue https://github.com/HGustavs/LenaSYS/issues/6904
> Fixed if statement to accommodate umllines

- DuggaSys/diagram_objects.js
> SetID added to path as well, Fix for issue #7465

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Fix for issue #7224
Change appearance and global appearance now gets its information from settings.properties, which is saved in localStorage.
> Change appearance fix, Fix for issue #7224

- DuggaSys/diagram.js
#6911 Commented a bunch of functions that where lacking comments
> Fix for #6911 Commenting of diagram.js

- README.md
coursesyspw.php is created by #5652
loglena4.db is created by #5789
Should now be easier for new students to get up and running with less steps to follow during the install.
Fixes #6484
> Remove instructions about coursesyspw.php and loglena4.db

- DuggaSys/diagram.js
Changed name on the toolbar when in DEV-mode to make it clearer for the user.
Issue: #7489 
**Co-Author: @a16jenja**
> Fix: #7489 - Nothing indicates that you are both in DEV and UML or ER mode

- DuggaSys/accessed.js
https://github.com/HGustavs/LenaSYS/pull/7348 fixed and updated
> Add filtering options for students and teachers to Access 

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_objects.js
#6912 diagram_objects.js several functions lack explanatory comments 
#7504 There are unused functions, varialble and eventlistners in diagram files 
I left out some of the draw functions since any comment i could come up with would just be redundant.
The functions i removed might have had some use i the future or alternative implementations but for now i have done as with previous unsued functions: removed them, and they can be retrieved in the git history if necessary.
> Fix for issue #6912 and #7504

- DuggaSys/diagram.js
> Fix for #7503 Possible to toggle mode with Shift + M while in dev mode

- Shared/css/blackTheme.css
- Shared/css/codeviewer.css
- Shared/css/colorblind.css
- Shared/css/whiteTheme.css
Fixes #7429.
Added line-height.
> Important word - no overlapping

- DuggaSys/contribution.js
> Contribution: Fix to only show timesheet table if there is data

- DuggaSys/fileed.js
> Search bar in fileed has background

- DuggaSys/contribution.js
Fix for issue https://github.com/HGustavs/LenaSYS/issues/7307
It should now show the missing chart in the charts tab.
> Show week based chart in charts view in contribution

- DuggaSys/codeviewer.js
Revisited #7274 fix for #7198 on new branch.
> Codeviewer: Fix on reset button after maximize

- DuggaSys/diagram.js
- DuggaSys/diagram_forms.php
- DuggaSys/diagram_objects.js
Fix for issue #7498
Settings.properties.symbolColor changed to fillColor to minimize confusion.
Should solve issue #7502 as well.
> Global appearance fill color fix, Fix for issue #7498

- DuggaSys/diagram.js
- DuggaSys/diagram_forms.php
#7510 clickEnterOnDialogMenu(ev) triggered SaveState() on every key press. Instead of triggering on every key press it'snow moved to be triggered by the OK button in dialog box for this.
> Fix for #7510 Any keyPress triggered a SaveState() and it's fixed now

- DuggaSys/codeviewer.js
> Fixed maximize error on certain templates

- DuggaSys/diagram.js
> Check if lastSelected is set rather than larger than -1, Fix for issue #7542

- DuggaSys/diagram_objects.js
Issue: #7484 
**Co-Author: @a17jacsv**
Fixed scaling on text inside UML classes when zooming in and out.
> Fix for issue #7484: Text in UML-boxes does not scale when zooming

- DuggaSys/duggaed.js
> Removed the footer from test table.

- install/install.php
> Added display of current owner of lenasys dir

- Shared/css/style.css
#7359 Added margins to last element of each week to avoid overlapping elements.
> PR for issue #7359

- DuggaSys/diagram.js
Fix for issue #7554
Should also solve free draw appearance
> LastSelected now used properly, Fix for issue #7554

- Shared/css/style.css
test link: https://a16hiwah.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732
before
efter
>  wrong cursor on stop lights have been fixed

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- DuggaSys/resultedconstants.php
- DuggaSys/resultedservice.php
- Shared/css/dugga.css
- Shared/dugga.js
Fixes: #7289
When clicking the ladExport button in resulted, the text "Last exported: " should appear in the popup preview next to a working copy to clipboard icon. When clicking the copy to clipboard icon, the text in the textarea should be copied and the "Last exported " date should  be updated. 
Test site: https://a17alian.groupb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
> Added a copy to clipboard and mark as exported icon to ladexport

- DuggaSys/showdoc.php
Fix for issue https://github.com/HGustavs/LenaSYS/issues/7563
> Add space to bummer message

- DuggaSys/accessed.js
https://github.com/HGustavs/LenaSYS/issues/7568
Moved the code creating the Toggle All button into the setup function.
> Fixed Toggle All button bug

- DuggaSys/codeviewer.js
- Shared/css/codeviewer.css
https://github.com/HGustavs/LenaSYS/issues/7401 minimize now works for template 1 and 2. I am not sure about the rest, cant seem to get the values right. But should not be harder than adding the maximize templates and fiddling with the values
> Code viewer minimize button added 

- DuggaSys/codeviewer.js
Were not sure if this was merged into the correct branch so i fixed it. It is the same solution as pr #7339
> Merged this issue in to our active branch. (W22). 

- DuggaSys/contribution.js
- DuggaSys/contribution.php
Fix for issue #7549
Also fixed an issue with the groups. Now all groups are set on the parent div in the .php file and not in the .js.
Also added headings for some of the charts.
> Fixed the order of tables and chars on the contribution page.

- DuggaSys/diagram.js
Changed eraseObject function to accomodate for umlLine tool. Now filters independently of symbolkind on object. Fix for https://github.com/HGustavs/LenaSYS/issues/7487
> Changed eraseObject function for umllines

- Shared/css/style.css
Testing each merge from a working point in repo history. First merge testing if it works.
> Fixing merge issue #6522

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- DuggaSys/resultedconstants.php
- DuggaSys/resultedservice.php
- Shared/css/dugga.css
- Shared/dugga.js
> Merging #7290 into test branch

- DuggaSys/diagram.js
Fix for issue #7562
Global appearance should be possible to change even with empty diagram
> Global appearance now works all the time, Fix for issue #7562

- DuggaSys/resulted.js
> Revert "Merging into test branch"

- DuggaSys/resulted.js
Reverts HGustavs/LenaSYS#7588
I dont even know :D
> Revert "Revert "Merging into test branch""

- Shared/css/style.css
> Fixed position of dropdown containers

- Shared/css/style.css
https://github.com/HGustavs/LenaSYS/issues/7571
> Fixed dialog close cursor

- DuggaSys/filereceive.php
Commented out code that printed arrays for debugging
Fixes #7065 
Testsite : https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/fileed.php?cid=2&coursevers=97732
> Removed code from screen after uploading link

- DuggaSys/diagram.js
fixed missing event parameters instances
https://github.com/HGustavs/LenaSYS/issues/7581
> fixed missing event parameters, Fix for issue #7581

- DuggaSys/diagram.js
> Fix for issue #7608: Uml line appearance should display the correct line type 

- DuggaSys/codeviewer.js
> Fixed error message when no copy button exist

- DuggaSys/fileed.js
Fixed https://github.com/HGustavs/LenaSYS/issues/7600!
Tooltips for edit and delete buttons implemented
https://gyazo.com/a5494cf3a8ec079fc8c64f06ceaf256d
> FileED tooltips implemented

- DuggaSys/duggaed.js
https://github.com/HGustavs/LenaSYS/issues/7603
> Added tool tips to buttons in DuggaEd

- DuggaSys/codeviewer.js
There was a bug when no files were chosen in codeviewer that stopped execution, this will fix it
> Fixed bug when no files were chosen

- DuggaSys/contribution.js
> allRanktable is now sortable.

- DuggaSys/contribution.php
> Added 12px left-margin to every table in contribution.

- DuggaSys/diagram.js
fix for issue https://github.com/HGustavs/LenaSYS/issues/7606
Made a function for unpressing all the tool buttons, and placed function before every mode switch.
> added resetToolButtonsPressed function

- DuggaSys/diagram_objects.js
> Fix for issue #7642: The relation lines doesn't scale well with zoom 

- DuggaSys/fileed.php
> added search bar to fileed for mobile

- Shared/css/style.css
- Shared/navheader.php
Issue #7345 
Changed so that the hover over navbuttons doesn't instantly disappear when moving mouse.
> Grupp b2019 w22#7345

- Shared/css/whiteTheme.css
https://github.com/HGustavs/LenaSYS/issues/7654
> Fixed codeborder line-height

- DuggaSys/contribution.js
- Shared/css/style.css
> Tooltips for contribution filter buttons

- DuggaSys/diagram.js
- DuggaSys/diagram_forms.php
- DuggaSys/diagram_objects.js
> ChangeApperance for text, fix for issue#7628

- DuggaSys/codeviewer.js
- Shared/css/codeviewer.css
https://github.com/HGustavs/LenaSYS/issues/7613
> Codeviewer copy animations fix

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Fab button works on both mobile and desktop
> #7636 fab buttons

- DuggaSys/resulted.php
"Inget" ändras till "none" i edit student results på LenaSYS.
> Issue #7747 - resulted.php modified

- DuggaSys/fileed.php
- DuggaSys/preview.php
- DuggaSys/showdoc.php
- Shared/markdown.js
https://github.com/HGustavs/LenaSYS/issues/7783
Added youtube embedding in markdown.
> G1 2020 W14#7783

- Shared/css/style.css
https://github.com/HGustavs/LenaSYS/issues/5456
> Assigned same values save-close-button for FE and MD 

- DuggaSys/codeviewer.js
Jakob och Mario new update (final)
> G1 2020 w14 issue#7434

- DuggaSys/courseedservice.php
Added a PDO transaction for all queries inside of option 'CPYVRS' so that all or none of them are executed. Also fixed indentation.
> Added PDO transaction for option 'CPYVRS'

- DuggaSys/courseedservice.php
> Revert "Added PDO transaction for option 'CPYVRS'"

- DuggaSys/diagram.php
- Shared/css/style.css
- Shared/navheader.php
It is now possible to navigate through the menu bar in the diagram page using tab(diagram.php). Also the login button is now reachable using tab as-well. Test by simply hitting tab until you reach the menu "File , Edit, View.. etc".
> Using tab key to navigate the menu bar(in diagram)

- DuggaSys/codeviewer.js
Mario och Jakob newly added code to codeviewer.js
> Fixed hotdog menu function for mobileview

- DuggaSys/courseed.js
- DuggaSys/courseed.php
Koden är uppdateras så att det inte ger felmeddelande när en ny kurs läggs till och editcourse valideras utan att en input måste göras.
> #7250 -updated

- DuggaSys/courseed.js
- DuggaSys/courseed.php
Former merge into master reverted, now merge into weekly group.
> G4 2020 w15 issue#7250 2

- DuggaSys/resulted.js
Removed if statment that manipulated pnr.
> #6401 Made a change to fulfill GDPR

- DuggaSys/codeviewer.js
- DuggaSys/codeviewer.php
Fixed link and header coloring. Fixed title tags and "World".
> G1 issue #7836

- DuggaSys/accessed.js
- Shared/css/style.css
Re-commit for this week. If-statement Terms flipped, Button class added. Css added to new button class
> Colors on new/oldbuttons changed

- DuggaSys/codeviewer.js
In codeviewer.js, merged dehighlight function with highlightfunction regarding HTML and op. Replaced jQuery with JavaScript in the affected functions where possible.
Tested by hovering the mouse cursor over tags and the added important words.
Attaching screenshot to illustrate what it looks like.
> G1 2020 w15 issue#1666

- DuggaSys/accessed.js
And if it is, closes the cell editing interface.
> Changed mouseUp function to check for if a click is outside editpopover

- DuggaSys/resulted.php
- Shared/css/dugga.css
Co-Authored-By: a18sebka <a18sebka@users.noreply.github.com>
> Change the size of toggleGrade and moved more to center. #7463

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
For testers:
Open http://localhost/lenasys/DuggaSys/diagram.php.
Open dropdown menu view
change to UML then place some UML objects and make some relationships and test the zoom function
Link to Issue: https://github.com/HGustavs/LenaSYS/issues/7635
Closes#7635
> G4 2020 w15 issue#7635

- DuggaSys/resulted.php
- Shared/css/style.css
Co-Authored-By: b18alegu <b18alegu@users.noreply.github.com>
> #7864 Changed inline style to stylesheet class references.

- Shared/SortableTableLibrary/sortableTable.js
> Removed onclick function from counter elements in sortableTable

- Shared/css/style.css
Adjusted icons to be centered in navheader. Also left adjusted a dropdown.
> Adjusted icons in navheader - G3 2020 #7793

- DuggaSys/diagram_objects.js
> Revert "G4 2020 w15 issue#7635"

- DuggaSys/diagram_objects.js
Followup on pull request https://github.com/HGustavs/LenaSYS/pull/7911
For testers:
Open http://localhost/lenasys/DuggaSys/diagram.php.
Open dropdown menu view
change to UML then place some UML objects and make some relationships and test the zoom function
Link to Issue: #7635
Closes#7635
> G4-2020-W15-ISSUE#7635 Solved

- DuggaSys/courseed.js
- DuggaSys/courseed.php
> Revert "Revert "#7250 -updated""

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- Shared/css/style.css
Co-Authored-By: a18sebka <a18sebka@users.noreply.github.com>
> #7629 Fixed a from clarity issue.

- DuggaSys/sectioned.js
För att testa:
Logga in som admin.
Gå till till exempel Webbutveckling - datorgrafik.
Hitta ett moment (de raderna med lila bakgrund).
Försök ändra grade system.
Det ska inte gå att byta till U-3-4-5 och få undefined.
> Removed the option to set the grade to U-3-4-5

- DuggaSys/accessed.js
- DuggaSys/resulted.js
- Shared/navheader.php
Added two functions to accessed.js and resulted.js, "hoverSearch()" and "leaveSearch()".
Added onmouseover and onmouseleave to navheader.php, also added a div that contains the text of the dropdown.
> #7540 Tooltip added to searchbar when hovering

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
Created a new "div" under the header that holds courseDropdown and two buttons in mobile view.
> #7865 Fix icon placement in mobile view

- DuggaSys/resulted.php
class='cursorPointer' added to resultet.php.
> #7949 Added pointer-cursor to close button.

- DuggaSys/sectioned.js
Changed display type of inputwrapper-gradesystem from "initial" to "block" to make it match in padding to the other <selects>.
> Changed display type of inputwrapper-gradesystem

- DuggaSys/accessed.js
Test:
1. open accessed
2. click on group dropdown
3. open edit for username/firstname/lastname
4. click outside cell to close
> Removed incorrect else

- DuggaSys/accessed.js
- Shared/css/style.css
- Shared/css/template4.css
- Shared/dugga.js
- Shared/icons/desc_black.svg
Reverts HGustavs/LenaSYS#7877
On hold since this issue is within the field of responsibillity of group 2
> Revert "G4 2020 w14 issue#7769"

- DuggaSys/accessed.js
Fixes one of the issues presented in #5599.  A new issue will be created for the remaining bug.
> G2 2020 w15 #5599

- DuggaSys/codeviewer.js
changed cid to courseid because fileed is looking for courseid when a file is uploaded
> Fixed ability to upload files from a course

- DuggaSys/fileed.js
- DuggaSys/fileedservice.php
- Shared/dugga.js
Implemented functionality for deleting files from the server, previously it would only delete it from the database.
> G3 2020#7388

- DuggaSys/codeviewer.js
- DuggaSys/codeviewer.php
- DuggaSys/fileed.js
- DuggaSys/filereceive.php
Added the fileed.js script to codeviewer.php so you can use the fileed function to edit and save the files. Added the window for editing to the codeviewer.php from fileed.php.
> Made it possible to edit files from codeviewer.

- DuggaSys/sectioned.js
Left some space between the groupicon and the text.
> G3 2020 issue#7741

- DuggaSys/fileed.js
- DuggaSys/fileedservice.php
- Shared/dugga.js
> Revert "G3 2020#7388"

- DuggaSys/fileed.js
- DuggaSys/fileedservice.php
Fixed deleting files again after a reverted commit.
> Fixed deleting files

- DuggaSys/codeviewer.js
Fixed the bug with CodeViewer that wrong documentation was being linked in some cases, e.g. HTML keywords linking to php.net and vice versa. Also fixed that when viewing documents, clicking words that have been added to the important word list links to a google search. 
Tidied up code, changed code to adhere to the code standard  and added/fixed comments.
Co-Authored-By: a18wilis <a18wilis@users.noreply.github.com>
> Fixed G1-2020-W15-ISSUE#7933

- DuggaSys/diagram.js
fixed issue #7680 by always putting lines at the bottom of the object stack
> fixed issue #7680

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Fixes #6217 and #7249.
Edit course version= Validates version name : 2 capital letters(not åäö) and 2 numbers. Validates start and end date: end date, end date is not before start date.
New course version=Validates version name : 2 capital letters(not åäö) and 2 numbers. Validates start and end date: end date, end date is not before start date.  Validates version ID : Only numbers and amount of numbers is between 3-6.
Edit Item= Validates section name: Only letters(not åäö) and space. Deadline: Deadline is between start date and end date of the version.
> #7249-fixed

- DuggaSys/diagram.js
> G4 2020 w15 issue#7908

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Accidental commit with private account but changes were reverted and done once again with the correct account
> G4 2020 w15 issue#5994

- DuggaSys/diagram.js
> Revert "Fixes issue 7847, closing appearance menu with escape then deleting objects with delete"

- DuggaSys/diagram_forms.php
> Revert "Fixes issue#7728, spacing in UML appearance menu"

- DuggaSys/courseed.js
- DuggaSys/courseed.php
#7888 error message now says Only letters ( not åäö). Now allows space.
> #7888-fixed

- DuggaSys/codeviewer.php
- DuggaSys/courseed.php
- DuggaSys/sectioned.php
- Shared/dugga.js
While the user is a guest they will get a cookie with their id as value for one hour: 
At login the cookie gets removed:
> Implemented guest user cookies so that guest id persist for one hour  - G1 2020 w15 #1490

- DuggaSys/resulted.js
Modified the ajaxcall in setup(). ResultEditor should now display results.
> changed cid to courseid in ajaxcall

- DuggaSys/resulted.js
Fixes issue #7997. Grading now works as expected, both by using the table interface and clicking the fist to open the grading window for a specific submission.
> replaced cid with courseid in all querystring[]-statements

- DuggaSys/accessedservice.php
> Revert "#7886 Fix problem were HTML encoded letters got into the database."

- DuggaSys/resulted.php
Co-Authored-By: a18sebka <a18sebka@users.noreply.github.com>
> Added the class cursorPointer to the grade button. #7975

- DuggaSys/showdoc.php
- Shared/basic.php
> Revert "Improved indentation for the files showdoc.php and basic.php"

- DuggaSys/showdoc.php
> Revert "G4 2020 w15"

- DuggaSys/courseed.js
- DuggaSys/courseed.php
- DuggaSys/courseedservice.php
Fixed so correct setting will be saved to database and checkbox will be checked or unchecked depending on the previous setting in database on page load.
> Fixed read only checkbox, issue #7812

- DuggaSys/diagram.php
- Shared/css/style.css
Fixes #6021 
Code from previous solution went missing after weekly-merge. This commit adds back missing code.
> Fixed navigation through menu with tab

- DuggaSys/diagram.js
> G4 2020 w16 issue#8012

- DuggaSys/diagram_objects.js
have fixt so when two lines meet it will be a sort of line jump icon, works only in er ain't the prettiest in all angles. someone has removed merged lines so it is a non issue. Closes #6005
> issue 6005

- Shared/css/style.css
**For testers**
1. open this address. http://group4.webug.his.se:20001/G4-2020-W16-ISSUE%235780/DuggaSys/diagram.php in firefox
2. test the input elements of type "range"
one of these elements can be found by using the "Draw Free" tool in ER mode
Link to original Issue #5780
> Reimplemented solution for new HTML structure

- DuggaSys/codeviewer.js
Fixed unique color for every tag.
> G1 issue #8010

- DuggaSys/codeviewer.js
- DuggaSys/codeviewer.php
Worked with d17marle and a18jakme
> Fixed issue  branch G1 2020 w16 issue#8008 

- DuggaSys/sectioned.js
sectioned.js is now updated and = is removed. It is now possible to create a new course version.
> #8009-fixed

- DuggaSys/courseedservice.php
previous PR https://github.com/HGustavs/LenaSYS/pull/7854
> Added PDO transaction to bundle the queries when using option 'CPYVRS'

- DuggaSys/resulted.js
> Changed string "Passed Deadline" to "Late submissions" in resulted.js

- DuggaSys/resulted.js
Added teacher id to local-storage so you can keep the examiner filter when page is refreshed.
Changed the if statement from last branch G2-2020-W15-#7520 so it doesnt call updateTable().
@a18oscte
> #7520 Added teacher id to local-storage

- Shared/css/style.css
Changed border-left to border-bottom in .feedback-list caption also made border 1 pixel instead of 2.
Solves #8007
> Changed border-left to border-bottom

- DuggaSys/resulted.php
Re-update after failed merging the last week. Related to issue #7747.
> resulted.php updated by changing inget to none again

- DuggaSys/fileed.php
Now it's merged with weekly branch (W16)
> G3 2020#7918

- DuggaSys/courseed.js
- DuggaSys/courseed.php
courseed.php is now updated again now calls functions in courseed.js.
#7888 error message now says Only letters ( not åäö). Now allows space.
> #7888 fixed

- Shared/css/style.css
- Shared/loginbox.php
Alert about "Your session has timed out." got pointer-cursor on exit button. Removed class=´cursorPointer´from loginbox and changed cursor from default to pointer in style.css
> Change cursor to pointer on alert. #7923

- DuggaSys/resulted.js
Added support for multiple search values.
> G2 2020 w16 #6244

- DuggaSys/accessed.js
- Shared/SortableTableLibrary/sortableTable.js
Fixes #6068.
Should improve performance as well as make the table work correctly.
> Removed duplication of accessed table

- DuggaSys/codeviewer.js
- Shared/css/codeviewer.css
Highlighted words with strings in codeviewer should now work.
If there is a string withing a string, single quotes should be used.
Special characters after/before a word such as "," or "!" should work and not be marked as important.
> G1 2020 w16 issue#7669

- Shared/css/style.css
Changed two values so that the padding got removed.
> G1-2020-W16-ISSUE#5591

- Shared/css/codeviewer.css
hide the warning when in mobile layout
> G1-2020-W17-ISSUE#7898

- DuggaSys/templates/dugga4.html
> Changed justify-content (again)

- DuggaSys/diagram.php
Zoom and Coordinate bars now have fixed positions, ready for testing
> Fixed positions of Zoom and Coordinate bars - issue#7421

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Added option to disable shortcuts. Ready for testing
> G4 2020 w17 issue#6995

- Shared/database.php
Check if notice of MYSQL_VERSION already defined comes up when entering a course when being logged in.
Link: http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%237868/DuggaSys/courseed.php
> Fixes issue #7868

- DuggaSys/codeviewer.js
Added funcitonality to display a CSS tutorial when clicking on an important word that exists within the array "cssArray" in codeviewer.js. Also replaced "php" with "multi" within onclick-events related to popupDocumentation, since the onclick-events showing php-documention no longer **only** shows php-documentation but rather multiple types of documentation.
Test by adding a word that exists within a .css-file (e.g. "background) to the important word list and then click on it. A popup should appear displaying "CSS Tutorial" from W3Schools.
Co-Authored-By: a18geoge <a18geoge@users.noreply.github.com>
> Added CSS-documentation to popupDocumentation

- Shared/css/codeviewer.css
Fixed margin problem in codeviewer so the first row is visible.
> G1-2020-W17-ISSUE#8144

- DuggaSys/diagram_objects.js
Took its time but it now works as intended with clipping
> Reimplemented functionality

- DuggaSys/diagram.js
added minimum distance before enabling drag and click
> added minimum distance before activating drag and click

- DuggaSys/diagram.php
- DuggaSys/diagram_objects.js
- Shared/css/style.css
A function called "flash" has been implemented which shows a danger/success message on screen.
This function is now used to show a flash message to the user if he/she tries to make a free draw object with less than 3 points(makes two points then right-clicks).
This function can further be used to show any type of message which may be useful to the user.
> On screen message handling

- DuggaSys/accessed.js
- Removed unnecessary global variable "expanded"
- Better show/close logic for group dropdowns
- Dropdowns now updates visually
Fixes #8082
> Updated group dropdowns in accessed table

- Shared/navheader.php
Test if notice Undefined offset: 1 can appear. Be logged in and choose courses that do not have versions.
Link: http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%238138/DuggaSys/courseed.php
> Fixes #8138

- Shared/navheader.php
yoyo its your g4-crew avoiding disaster @ weekly. @a18jenro @a18lukto
> G4 2020 w17 issue#8138

- DuggaSys/codeviewer.php
By getting the timestamp, css and js files in codeviewer.php should new be reloaded if they are saved. For the CSS this works in a single array because they are all in the same directory, the JS files should be placed similiarly to get this to work, currently only the jQuery files are used as an array.
To get this to work everywhere, moving js files or buildings function to search in many directories should be done.
> G1 2020 w17 issue#7760

- DuggaSys/ace.js
- DuggaSys/fileed.js
- DuggaSys/fileed.php
- Shared/css/style.css
Go to files and open up a non txt file to see changes. 
Before:
After:
> Implemented ace editor in file view - G1-2020-W17-#2297

- Shared/dugga.js
Increased duration from 1 hours to 2 hours until login session expires. also increased 15 minute warning to 1 hour and 45 minutes
> Increased Duration until session expire and makes user logout

- DuggaSys/resulted.js
Added so when you only type one letter it searches for names/lastnames that starts with that character. If more than one character is entered, it checks if the characters is contained in the name/lastname, username, teacher and ssn.
Co-Authored-By: b18fella <b18fella@users.noreply.github.com>
> Updated search so you can search for name with one letter.

- DuggaSys/downloadzip.php
- DuggaSys/filereceive.php
- Shared/navheader.php
You are now able to download files that are version independent to you course as well as the files to the specific version of the course you are in at the moment.  the already uploaded files are in non of those categories and will not be downloaded as of right now. But all new files will be uploaded appropriately. closes #7765
> G4 2020 W17 issue#7765

- Shared/navheader.php
> Added tooltip for dropdown #7661

- Shared/css/style.css
Added padding for fab-icon in "Show files".
Co-Authored-By: b18jenli <b18jenli@users.noreply.github.com>
> #8040 Change the padding of the icons

- DuggaSys/fileed.js
Now, even when filtering, the backgroudn color of files in the table alternates.
> G3 2020#8126

- DuggaSys/diagram_objects.js
Solves #6864
Before fix there was a small gap between lines connecting to ER-relations(due to ER-relations pointy edge). This was fixed using a square lineCap.
> Lines to ER-relation now connect - Issue#6864

- DuggaSys/duggaed.js
This fixes the DuggaEditor. It was previously empty even when it shouldn't be and it was not possible to add new duggas/tests (it gave an error message, shown in linked issue).
Solves #8171
> updated all querystrings to courseid from cid in duggaed.js

- DuggaSys/diagram.js
Implemented an eventlistener listening for clicks on the appearance container.
Test if it is possible to close the appearance form by clicking outside of it and also close the form in every other possible way; ESC, "X", ENTER to see if any errors occur.
Link: http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%238080-NEW/DuggaSys/diagram.php
> Fixes issue #8080

- Shared/css/codeviewer.css
- Shared/css/style.css
- Shared/css/template3.css
Fixed the issue with the heading placement and the code field that cut off in shader programming.
> G1-2020-W17-ISSUE#8223

- Shared/SortableTableLibrary/sortableTable.js
The issue with wide columns was fixed by implementing a max-width as well as an ellipsis to the th-element. The "white-space: nowrap;" was also removed. 
However the problem is not really solved in a good way. Hence there will be a new issue created.
> Resulted: Fixed issue by limiting the size of the th-element.

- DuggaSys/resulted.php
The heading was replaced to far left instead of being centered. Also, the title was changed to increase comprehension of the site.
> Update in resulted.php - modification of heading and it's title

- Shared/css/codeviewer.css
Fixed buttons and the mirgin in template 9 and 10
Template 9: 
Template 10
> G1-2020-W17-ISSUE#8250

- Shared/css/codeviewer.css
> Revert "G1-2020-W17-ISSUE#8250"

- DuggaSys/codeviewer.js
Maximize button works for every template, except for template 9 since that template doesn't currently have a maximize button.
Also made sure to update alignBoxesWidth to make it more dynamic.
Made some updates to resizeBoxes for template 5 as well.
> Maximize button now works with every template

- DuggaSys/accessed.js
- Shared/SortableTableLibrary/sortableTable.js
> Accessed table dropdown menus now properly updates the sortableTable

- DuggaSys/resulted.js
Added two conditions to the if-statement on row 213 to enable "showStudents" and "showTeachers" filters when opening resulted.php.
Stored the enabled filters to localstorage.
> #7598 Added conditions to if-statement and enabled the desired filters.

- DuggaSys/courseed.js
- DuggaSys/courseed.php
- Shared/css/style.css
Validation for course code. A message appears if the types course code is used by another course. This will prevent unnecessary ajax calls to server as well. For editing of courses a solution was implemented to still be able to save the course with the same course as it previously had without it getting blocked by validation of codes courses already have. 
Validation was reworked to be more general and code was cleaned up a bit.
Test if all validation works as expected.
- Should be possible to have multiple words in coursename.
- Dash can be in between two words like in Webbutveckling - datorgrafik only.
- When validating course codes it has to follow the format two letters, three digits, one letter. Example: 'IT108G'.
- A message should appear in real time when typing if course code is …
> Fixes issue #8011

- DuggaSys/diagram_IOHandler.js
Solves #6913
Read through and commented all functions in IOHandler.js with hopefully understandeable/usefull explanations.
> Added explanatory comments to IOHandler.js

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
- Simplified code for dev coordinates and zoom. 
- Made dev coordinates more consistent and easy to read.
- Positioned elements that should appear on top of the canvas relative to the canvas container making placement of them easier. This should also fix the move button issue #7621 while also making the positioning better for dev and zoom.
- Improved structure for toolbars styling slightly to prevent an issue where the dropdown labels appear inside the canvas and make it easier to make changes in the future.
Test if mouse coordinates works as expected in dev mode. Test if object coorindates works when hovering. Test so move button and all other elements on the canvas are positioned correctly. Test so the toolbars works as expected.
Link: …
> Fixes #8091

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_objects.js
Now you can select a text and select if its a comment or not and if it is a comment it will be hidden if the view->'Hide comment' button are pressed.
Closing #6487
> G4 2020 w17 issue#6487

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
To test, go into any course as an admin and try to change the deadline of something that is not a test, for example a message. There should be no option to change a deadline.
> Removed deadlines from everythign except tests.

- DuggaSys/diagram.js
- Shared/css/style.css
When in mobile view the coordinate box for developer mode takes up a large part of the screen and has been hidden in mobile view.
> No longer shows developer coordinates in mobile view, issue #7423

- DuggaSys/diagram.js
Solves #7491 and #7673
Solution properly deletes UML-line points when line is deleted which solves atleast these two issues mentioned above.
> Properly delete UML-lines

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
It seems like it only were to remove all off the [0] and the [ ] surrounding the parameters of this.cardinality. Everything seems to work great. There will probably be weird bugs thanks to this change but i could not find any in my 10 minutes testing 
Closing #8086
> Issue #8086

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
**For Testers**
open http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%237583/DuggaSys/diagram.php
play around with global appearance font-size setting. See if you can get the Attribute box to overlap with operation box or Vice versa with a UML class object
Closing #7583
> G4-2020-W17-ISSUE#7583

- DuggaSys/accessedservice.php
Made a if statement that changes the update value to NULL if the user selects "none" in the Examiner filter.
> #8077 Added if statement to change the update value to NULL.

- DuggaSys/resulted.js
Solves Issue where previous feedback table was visible without any previous feedback
> G2 2020 w17 #8160

- Shared/css/style.css
- Shared/navheader.php
New design for search bar.
Before:
After:
> G3 2020#8041 is solved

- Shared/css/style.css
Removed blue outlining on zoom buttons, undo and redo buttons. Also added active element to the buttons with the same yellow background as the other buttons to add consistency. 
Link to test: 
http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%238303/DuggaSys/diagram.php
Before:
After:
> fix issue#8303 consistency on remaining buttons.

- install/SQL/testdata.sql
Added students to groups, added examiner entries for students and reformatted the group-strings in the testdata to mirror the accessEd data.
I mostly added testdata for courses 1 and 2 (Webbprogrammering & Webbutveckling - datorgrafik) since these are the ones complete enough to use when testing.
> Updated testdata for accessEd

- DuggaSys/showDugga.php
For testing follow the guide in https://github.com/HGustavs/LenaSYS/pull/8224 . BUT instead of running services open a Dugga. 
co authored with @a18jakme
> Added logging for dugga page loads - G1-2020-W17-ISSUE#8230

- DuggaSys/codeviewer.js
Added better funcionality for the "reset" button. Now places all the boxes to their original position when clicking on the button as seen below
> Fixed solution for G1 2020 w17 issue#8210

- DuggaSys/sectionedservice.php
- Shared/basic.php
Logging for adding a new item in Section.php. Logging works through the "+" button and the shortcut. A new EventType (14) is added and a description on type of the new item.
For testing follow guide in https://github.com/HGustavs/LenaSYS/pull/8224
co authored with @b17carbr
> Logging for adding a new item in Section

- Shared/css/style.css
Removed the extra bar and some buttons for the mobile view.
> Buttons in mobile view

- DuggaSys/diagram.js
Should now be possible to move around the canvas in mobile view. Mobile view can struggle to update some times but refreshing the page should fix this, or alternatively using a real phone to test.
> Touch support for moving around on the canvas, issue #8320

- DuggaSys/diagram.php
- DuggaSys/diagram_IOHandler.js
- Shared/css/dugga.css
- Shared/css/style.css
#6315 Is now able to print. Print is under File in the menu. Canvas is bigger when printing and normal after.
http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%236315-2/DuggaSys/diagram.php
> G4 2020 w17 issue#6315

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_IOHandler.js
- Shared/css/style.css
I wish to merge my changes to the diagram. I have not made enough changes to close any issues but I do have a stable  build whit added features such as the ability to change paper size and to have a page number printed to the bottom right corner of the page.   working on ISSUE #7935 so it will be under this name on the test server.
> midway merge 

- Shared/navheader.php
With this fix the ` $cid` variable in `navheader.php` should no longer be out of scope.
> Variable cid is no longer out of scope.

- Shared/css/style.css
Changes made to sorting and filtering icons in the resultEditor to position them more in the middle.
> G3 2020 w17 #8147

- DuggaSys/fileed.php
- DuggaSys/filereceive.php
The errors from filereceive.php is now displayed in fileed.php with some styling.
> G3 2020 issue#6590 Error message in fileed from filereceive

- Shared/navheader.php
The strange looking icons in the navheader now look normal again. 
Went from this: 
To this:
> Icon in "Edit student results" no longer strange, fix for issue #8335

- DuggaSys/codeviewer.js
Reduced the amount of jQuery, fixed intendation and declarations within the "returned" function. 
Test by using the "before"/"after" buttons and changing titles in the edit example section. Check functionality regarding changing the examples to and from code, document and preview.
> Updated function "returned" to better fit with the code standard.

- DuggaSys/courseedservice.php
- Shared/basic.php
Result from creating or editing courses:
How to test:
co authored with @a18jakme
> Logging for create course and edit course - G1-2020-W17-ISSUE#8319

- DuggaSys/codeviewer.js
The fourth window will now be resized as well when pushing down the second and third window.
<a href="https://gyazo.com/2f6f613599f91d710ecae35413fe8c72"><img src="https://i.gyazo.com/2f6f613599f91d710ecae35413fe8c72.gif" alt="Image from Gyazo" width="1918"/></a>
> Issue #8305 - Template 9 rezizing height not working properly - Now fixed

- DuggaSys/templates/dugga3.html
<a href="https://gyazo.com/5cd11b2991a4c55692bbbc751c08c7c1"><img src="https://i.gyazo.com/5cd11b2991a4c55692bbbc751c08c7c1.gif" alt="Image from Gyazo" width="1280"/></a>
> called function onlick was wrong and is now fixed.

- DuggaSys/diagram.js
**For testers**
1. open this page http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%238236v2/DuggaSys/diagram.php
2. create a cardinality from ER-entity object and a ER-relationship object. (draw a line and set a cardinality value). do this also for uml to uml classes.
3. open the console and type the following "console.log(diagram)" and have a look so the following conditions are true
a object where the line started from a ER-entity object should result in the targeted object receiving the value **true** in it's cardinality[0].isCorrectSide directory
a object where the line started from a ER-relationship object should result in the targeted object receiving the value **false** in it's cardinality[0].isCorrectSide directory
a UML to a UML class should result in the line connecting the …
> G4 2020 w18 issue#8236 Cardinality.isCorrectside Solved

- Shared/css/style.css
- Shared/dugga.js
- Shared/logoutbox.php
Made some changes to the design of the log out box to make it match the log in box better.
It went from this:
To this:
> Changed design of log out box, fix for issue #8399

- Shared/navheader.php
The "Download all files" button has now been moved to only be visible if browsing fileed.php. We also fixed the search button so it doesnt mess up the layouting by being part of the search inputs table column, it now has its own column and aligns properly in the navbar.
> Fixed download button

- DuggaSys/resulted.js
> Added "undefined"-check in resulted.js

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Fullscreen mode added. 
When testing this, go to http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%238066/DuggaSys/diagram.php and navigate to View > Fullscreen. Look for any broken elements. To exit, press Escape.
> Solves issue#8066

- Shared/css/codeviewer.css
- Shared/css/template1.css
- Shared/css/template2.css
- Shared/css/template3.css
- Shared/css/template4.css
- Shared/css/template5.css
- Shared/css/template6.css
- Shared/css/template7.css
- Shared/css/template8.css
- Shared/css/template9.css
> Solution for branch G1-2020-W18-ISSUE#8372

- DuggaSys/templates/html_css_dugga.html
By adding id="feedbackBox" to the feedback-container class the error was solved in "Random css dugga". Before the style pointed at null.
> Removed error on "Random css dugga" by adding an id. #8369

- DuggaSys/codeviewer.js
Reduced the amount of jQuery within the "updateExample" function.
Test by navigating to codeviewer.php and by clicking the "EditExample" button (the big cogwheel in the top section), change the titles and the play link.
> G1 2020 w18 issue#8417

- DuggaSys/codeviewer.js
- Shared/css/template9.css
Made new function for template 9 maximize buttons.
> Solution for branch G1-2020-W18-ISSUE#8372 

- DuggaSys/diagram.js
> Revert "G4 2020 w18 issue#8236 Cardinality.isCorrectside Solved"

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
for tester
1. open this url http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%237361/DuggaSys/diagram.php
2. draw some lines between er elements and places cardinalitys.
3. move the elements around and try to make it so the cardinality overlaps with the line
Closing #7361
> G4 2020 w18 issue#7361

- DuggaSys/downloadzip.php
- Shared/navheader.php
Fixed file downloading for a specific version of a course.
@a18lukto Maybe create a label for file downloading because there is now a `downloadzip.php` file which handles file downloading from the server.
To test: Login as brom, go to the file editor, click the download button. (the course youre downloading from should have course local files, otherwise it will give an error)
> G3 2020#8411

- DuggaSys/filereceive_dugga.php
- DuggaSys/showDuggaservice.php
- Shared/basic.php
Logging for save and upload a file in dugga.
Upload file dugga - Logs a userid and a description with filename and filetype
Save dugga - Logs a userid and a description with courseid, duggaid, moment and an answer.
For testing:
co author @b17carbr 
When upload a file, there is an issue with a "bummer" message. However, the log still works and the file is getting uploaded.
> Logging for save and upload in showDugga

- DuggaSys/accessedservice.php
- Shared/basic.php
Logging when a user reset password.
userid - who did the reset on the account
description - on which account
For testing:
co author @b17carbr
> Logging for reset password in accessed

- DuggaSys/diagram.js
Default paper size set to A4. To test this, go to http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%238478/DuggaSys/diagram.php and navigate to View > Paper size...
> Solves issue#8478

- DuggaSys/resulted.js
- DuggaSys/resultedservice.php
> Resulted redirects users with no access

- DuggaSys/diagram.js
- DuggaSys/diagram.php
The scrollbar that previously appeared in fullscreen is now gone. 
Also removed code related to the position of the zoombar, since this will automatically be resolved in another issue
> Solves issue#8436

- DuggaSys/codeviewer.js
Reduced jQuery within the function "changeDirectory". 
Test by navigating to codeviewer.php and by clicking the "Edit Content" button(s) (the smaller cogwheels) and check functionality regarding changing the kind of document and what wordlists and which files are possible to choose from.
> Updated codeviewer.js - G1-2020-W18-ISSUE#8455

- DuggaSys/codeviewer.js
> Solution for branch G1-2020-W18-ISSUE#8458

- DuggaSys/diagram.js
Now page number will only appear if an object is on that page. lines can only trigger one page but i do think that is enough.
> G4 2020 w18 issue#6371

- DuggaSys/resulted.php
included basic.php to get the function to get the value to the variable
> #8423 defined cid variable

- DuggaSys/diagram.js
- DuggaSys/diagram.php
It is now possible to navigate to Help-> Generate example ER/UML diagram to generate example diagrams. [Issue 6790](https://github.com/HGustavs/LenaSYS/issues/6790)
> Solves #6790, Adds example diagrams

- DuggaSys/codeviewer.js
Updated function "addTemplatebox" within codeviewer.js to better fit the code standard by reducing the amount of jQuery.
Test by navigating to codeviewer.php and by clicking the "Edit Content" button(s) (the smaller cogwheels) and check functionality regarding changing the examples.
> Updated function "addTemplatebox within codeviewer.js - G1-2020-W18-ISSUE##8476

- DuggaSys/fileed.php
- Shared/navheader.php
Checks whether the kind and filename global variables exist before using them. No the notice message: "Notice: Undefined index: kind in /var/www/group3/G3-2020-W17/DuggaSys/fileed.php on line 337", is no longer printed on the website when in browsing files.
It used to be shown below all files.
> G3 2020#8352

- Shared/navheader.php
Switched out the filter icon and removed the 35px margin-left it had.
It went from this:
To this:
> Switched filter icon, fix for issue #8166

- DuggaSys/diagram.js
It should now be possible to move objects while in mobile view. (It might be necessary to reload the page after swapping to mobile view.)
Also created separate event functions that fire for touch events. Previously the touch events fired mouse event functions.
> Now possible to move objects in mobile view, #8321

- DuggaSys/codeviewer.js
Unnecessary code for box3wrapper removed solved the lagging purple bar.
<a href="https://gyazo.com/29cb5f35e141527ea9adf7e068b872c1"><img src="https://i.gyazo.com/29cb5f35e141527ea9adf7e068b872c1.gif" alt="Image from Gyazo" width="1168"/></a>
> Lagging purple bar fixed

- DuggaSys/fileed.js
Added functionality that checks if a user has write-access when entering fileed.php.
If the user has write-access, they will be able to view the page. If not they will be redirected to courseed.php.
Test by visiting fileed.php as a logged in user with write-access (e.g. brom) and as a non-logged in user. Users should be redirected to courseed.php when not logged in.
> Added functionality that checks if a user has write-access when entering fileed.php.

- DuggaSys/codeviewer.js
Updated function "toggleClass" within codeviewer.js to better fit the code standard.
Test by reducing the window size to a width smaller than 1100 and using the menus on top of the example windows.
> Updated function "toggleClass" within codeviewer.js - G1-2020-W18-ISSUE#8500

- DuggaSys/accessed.php
- DuggaSys/duggaed.js
Solves #8518 
We have changed headers in Access Editor and Dugga Editor to conform to the same format as in Result Editor and File Editor.
Co-authored by c14jonfr <c14jonfr@student.his.se>
> G2 2020 w18 #8518

- Shared/markdown.js
Changed two lines of regex code, and Atom removed some empty spaces after code. 
Changes made for issue #8300 
Part of issue #2648
> Made the plus sign work as an unordered list sign.

- DuggaSys/duggaed.js
If the user dont have write access, the user gets send to the startpage.
> #8517 Added if statement to see if the user have write access.

- DuggaSys/duggaed.php
- DuggaSys/templates/3d-dugga.html
- DuggaSys/templates/boxmodell.html
- DuggaSys/templates/dugga5.html
- DuggaSys/templates/feedback_dugga.html
- DuggaSys/templates/html_css_dugga.html
- DuggaSys/templates/html_css_dugga_light.html
Deleted all empty inline style tags in:
- duggaed.php
- html_css_dugga.html
- html_css_dugga_light.ht
- 3d_dugga.html
- boxmodell.html
- dugga5.html
-  feedback_dugga.html
> Deleted all empty inline style tags. #8370

- DuggaSys/resulted.js
See discussion in #8501, removes "korf/fist" - element from moments
> Added check to if-statements to remove error #8287

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- Shared/SortableTableLibrary/sortableTable.js
Now one can press F11, F12, resize the browser window and sort the columns, and the filtering will remain correct.
> G3 2020#8107

- DuggaSys/resulted.js
Added a for loop to connect duggor with its sub-duggor.
Made a variable to save the placeholder grade. 0 if  a sub-dugga has been handed in and Null if no sub-dugga has been handed in.
Made changes to when how many times a dugga has been marked and time when submitted.
> #8287 Fixed issue were duggas was unasigned still when a sub-dugga has been handed in.

- DuggaSys/fileed.js
- DuggaSys/fileed.php
- DuggaSys/fileedservice.php
- DuggaSys/filereceive.php
- Shared/navheader.php
- Shared/sessions.php
Updated access levels for the `fileed.php` file. We have updated the database with 3 users for testing purposes.
Dont forget to take a look at the code as the **supervisor** role hasnt fully been implemented just yet and weve just implemented simple checking for future functionality.
brom = **superuser**
teacher2 = **supervisor**
teacher3 = **write access**
teacher4 = **studentteacher**
In case anyone has reinstalled the database for their branch you might have to set these yourself.
For testing use the course `Webbprogrammering` as thats the only course weve set the permissions for in the database. (If they have been wiped you can choose whatever course you want)
> G3 2020#8397

- DuggaSys/analytic.js
- DuggaSys/analytic.php
- DuggaSys/analyticService.php
Migrated the files from version 0.85 for analytic over the current version. 
The following files where migrated:
This will give access to the analytic page:
Most of the functionally is not working at this time. This will be corrected and additional funtctionallity will be added.
> Migrated over old analytic - G1-2020-W18-ISSUE#8559

- DuggaSys/resulted.js
- DuggaSys/resultedservice.php
Solves #6563.
Note: To test this you will need to have at least one group assignment, with submissions and have students assigned to different groups. Currently this only supports being assigned to one group at a time (it won't give up totally, but it only works properly if students are assigned to one group at a time).
Step by step guide, make sure you're logged in as a user with permission to do these things, I suggest using "Toddler" (skip this is you already have a group assignment set up, as far as I know there is no group assignments in testdata):
1. Create a test in the test editor (aka dugga editor). Press the yellow FAB in the lower right corner. Name to your own liking, I suggest "Gruppuppgift" or something similar, set deadlines etc. Make sure to set the template to …
> G2 2020 w18 #6563 user can now grade all students in a group with one click (for group assignments)

- DuggaSys/resulted.js
removed width variable, and animation. added if-statement that changes visibility depening on current state
> #8521 removed animation on toggleGrade box

- DuggaSys/resulted.php
Fixes #8365 
Might not be possible to test locally, since the problem seems to only appear when connecting to a remote server.
> Added meta info to set "notranslate"

- Shared/css/dugga.css
- Shared/dugga.js
Updated email pop in receipt box to better fit window, solves #8544
> G2 2020 w18 #8544

- DuggaSys/resulted.js
The sorting of Fname/Lname with the use of the checkboxes is still wrong however, but is a separate issue. 
(Ignore the merge commit in the history, the merged branch is already in G2-2020-W18)
> Resulted sorting checkboxes are now properly updated when sorting

- DuggaSys/codeviewer.js
Result:
[![Image from Gyazo](https://i.gyazo.com/3ba6391d1d708a6de17563d209bbeba6.gif)](https://gyazo.com/3ba6391d1d708a6de17563d209bbeba6)
> Solution for branch G1-2020-W18-ISSUE#8511

- DuggaSys/diagram.js
Should now be possible to draw lines between objects in mobile view. If testing on computer remember to refresh the page after swapping to mobile view.
> Implemented touch support for drawing lines, issue #8322

- DuggaSys/courseedservice.php
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Also removed unnecessary `console.log();` and fixed a problem with an error message when exciding 50 letters when editing MOTD.
> #8526 Added MOTD to “New Course Version” window.

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
motds design fits in better now and is placed under the navbar now.
> G3 2020 #8522

- DuggaSys/courseedservice.php
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Updated with the working weekly branch
> #8526 - MOTD added to "New Course Version"

- Shared/dugga.js
New pull request to fix merge issues
> Redirected the logout to the main page

- DuggaSys/duggaed.js
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
"New code" option is no longer added when you click the FabButton.
> G3 2020 w18#8266

- install/install.php
Tested installing project on my Windows laptop, and saw that I missed a + earlier.
My bad. 🙃 
Issue #7787
> Added missing + to current owner Windows fix, line 76.

- DuggaSys/codeviewer.js
- Shared/css/codeviewer.css
- Shared/css/template1.css
- Shared/css/template2.css
Minimize now works for mobile view, see GIF below. Take note that only template 1 and template 2 has minimize button!
> Solution for branch G1-2020-W18-ISSUE#8571

- Shared/dugga.js
When failing to login the guest cookie now remains.
> Solved guest cookie disappearing when login fail - G1-2020-W18-ISSUE#8596

- DuggaSys/analyticService.php
- DuggaSys/filereceive.php
- DuggaSys/filereceive_dugga.php
Average duration for a service (in milliseconds) is shown. 
The numbers need to be looked at more closely in a new issue.
> "Service Speed" now shows data which is average duration for a service.

- DuggaSys/resulted.js
The error only appeared when testing remotely, but now it is fixed.
(fr) Fixes #8568
> Removed error from test server 

- Shared/loginlogout.php
Username now shows up in log on the username that fails.
> G1 2020 issue#8597

- install/install.php
> Added php-tags and changed the message to display group owner

- DuggaSys/fileed.js
- Shared/navheader.php
The old branch is replaced with a new one because there was some problems with merging into the weekly-branch
> #8381 branch is replaced

- DuggaSys/fileed.js
- Shared/navheader.php
The old branch is replaced with a new one because there were some problems with merging into the weekly-branch.
> G3 2020#8437 branch is replaced

- Shared/css/style.css
Width fixed for text and centered buttons.
> Fix for buttons in analytics

- DuggaSys/analytic.js
- DuggaSys/analytic.php
- DuggaSys/analyticService.php
- DuggaSys/fileedservice.php
- DuggaSys/filereceive.php
- Shared/basic.php
Created new analytic service call to display information regarding editing or creation of files. Used the service to display information in analytic.php via the new functionally "file information". Also added logging for file editing because it was not present before. 
How to test:
Create and edit a file in fileed, then go to analytic.php and click file information button. Information should be shown there
> Added analytic service call for file information and displayed it, +FileEdit logging - G1-2020-W19-ISSUE#2179

- DuggaSys/diagram.js
Now, the canvas resizes in fullscreen when resizing window
> Canvas follows window size

- DuggaSys/diagram_objects.js
Implementation ready for review.  A link to the issue corresponding this pull request:
https://github.com/HGustavs/LenaSYS/issues/7036
> G4 2020 w19 issue#7036

- DuggaSys/diagram.js
Should now be possible to resize objects in mobile view by dragging the points of objects. resizing should not work on locked objects.
> Touch support for resizing objects, issue #8449

- DuggaSys/codeviewer.js
Test by changing templates on codeviewer.php. All templates should be able to be applied without any problems.
> Updated "changetemplate" to better fit the code standard

- DuggaSys/codeviewer.js
Updated function "updateContent" within codeviewer.js to better fit the code standard. 
Test by going to codeviewer.php and navigating to the "Edit Content" window by pressing the small cogwheels and edit the examples in different ways (title, wordlist, file etc), edit the examples through the "Edit file" (the small pencil) icon. Check if for example the different exampleid's give the corresponding examples and titles (e.g. by changing the number in the URL, LenaSYS/DuggaSys/codeviewer.php?exampleid=1&courseid=1&cvers=2013 where exampleid would be changed to =2).
> Updated function "updateContent" within codeviewer.js - G1-2020-W19-ISSUE#8679

- install/install.php
Structured the code so its easier to see what's what. Also indented the code to follow the standard.
Have checked so no conflicts arises with other groups.
> G4 2020 w19 issue#8716

- DuggaSys/resulted.js
> Fixes sorting by Fname/Lname using checkboxes in ResultEd

- install/install.php
Reverts HGustavs/LenaSYS#8747
Clicked wrong, revert.
> Revert "Fixed permission text for Windows/Linux/OSX #8000"

- install/install.php
Changed the recomended settings from 777 to 060, to provide maximum security.
I can't reproduce the modal on installer. But pretty certain it works as intended ..
> Changed 777 to 060. Fixes #7900

- Shared/navheader.php
Deleted 2 comments.
`$("#cookiemsg").css("display", "none");`, seem to be fixed by the code at 250-255.
> Removed 2 comments

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- DuggaSys/diagram_objects.js
The code for creating, storing and moving cardinality was reworked to be more efficient, less redundant and work correctly. Redundant information was stored before that was not relevant to the cardinality, this has been minimized a lot. This will help save space in localStorage and make the code more efficient and easy to understand.
Cardinality did not work propertly for UML before. The second cardinality could be undefined when a cardinality was chosen for the first side but not the second. The second cardinality would not show if the first did not show. The selected option would be empty instead of "None" when choosing "None" for both ER and UML. All of these problems have been solved.
It should be impossible to set ER cardinality for Entity -> Attribute and Relation -> Attribute …
> Fixes #8512 - Cardinality for UML and ER not working properly

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Removed old branch & pull request and migrated solution here. Shouldn't affect existing code as previous solution did
> Toolbar in fullscreen - solves issue #8435

- DuggaSys/codeviewer.js
The errors with the button hiding and not showing the description tag is now fixed.
Maximize:[![Image from Gyazo](https://i.gyazo.com/0e5710e94fd1ff6ad0899812600e64eb.gif)](https://gyazo.com/0e5710e94fd1ff6ad0899812600e64eb)
Minimize: [![Image from Gyazo](https://i.gyazo.com/ef19c3bc568b562b8d4d60c88fd7c319.gif)](https://gyazo.com/ef19c3bc568b562b8d4d60c88fd7c319)
Reset:[![Image from Gyazo](https://i.gyazo.com/9f9e5d92e6ef8fc924b8d18c0ea16189.gif)](https://gyazo.com/9f9e5d92e6ef8fc924b8d18c0ea16189)
> Solution for branch G1-2020-W19-ISSUE#8574

- DuggaSys/sectioned.php
Changed the location of the errormessages for date and MOTD so they are now placed correctly.
> Errormessages are no longer in the wrong place.

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
**Changed what EventType to retrieve data from, from ServiceClientStart to ServiceServerStart.**
<a href="https://gyazo.com/33cb47a836c7df9f7a5a0ffd3aa90058"><img src="https://i.gyazo.com/33cb47a836c7df9f7a5a0ffd3aa90058.gif" alt="Image from Gyazo" width="1914"/></a>
> Fixed Analytics osPercentage()

- DuggaSys/codeviewer.js
**Template 6 working as expected:**
<a href="https://gyazo.com/aa5464d8203986b8ccb866055154ca37"><img src="https://i.gyazo.com/aa5464d8203986b8ccb866055154ca37.gif" alt="Image from Gyazo" width="1918"/></a>
**This issue also includes template 7, which as shown below functions properly now as well:**
<a href="https://gyazo.com/e98f2b85384812718af42557ef615236"><img src="https://i.gyazo.com/e98f2b85384812718af42557ef615236.gif" alt="Image from Gyazo" width="1918"/></a>
> Maximize function on box 4 now works properly - Template 6

- DuggaSys/diagram.js
Now possible to add text to the canvas in mobile view. The text can be edited via the change appearance menu.
> Can now create text in mobile view, issue #8672

- DuggaSys/diagram.js
[Issue 8600](https://github.com/HGustavs/LenaSYS/issues/8600) It is now possible to click Help->Generate example UML-diagram to get an UML-diagram drawn on the canvas. If an object is moved the line does not follow, this is a known issue [Issue 8622](https://github.com/HGustavs/LenaSYS/issues/8622)
> Fixes issue 8600, Fixed broken cardinality

- DuggaSys/showDugga.php
- Shared/css/dugga.css
- Shared/css/style.css
- Shared/dugga.js
> Cleaned up the locks and functions of the receipt popup #8657

- DuggaSys/codeviewer.js
> Revert "G1-2020-W19-ISSUE#8593"

- Shared/css/style.css
Added position:relative; to #submitButtonTable to make the Save/Reset button to be shown.
Co-Authored-By: b18fella <b18fella@users.noreply.github.com>
> Added position:relative; to #submitButtonTable. #8756

- DuggaSys/codeviewer.js
Updated function "resizeBoxes" to better fit the code standard.
Test by changing sizes of different sections within all available templates. Every template should have existing resizing functionality and these should not generate any errors.
> G1 2020 w19 issue#8711

- DuggaSys/codeviewer.js
> Revert "G1 2020 w19 issue#8711"

- DuggaSys/sectioned.php
Now MOTD in editCourseVersion will get validated directly and will not give the error "You have entered incorrect information" when it has not been altered.
> G3 2020 issue#8723 Now MOTD will not give any errors when not changed

- DuggaSys/analytic.js
resetAnalyticsChart();
Function to reset graphic chart in analytic is now used when click on file information.
> Reset graphic in file information

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Cleaned dead code for SectionED booth the js and php file.
> G3 2020 #8525

- DuggaSys/codeviewer.js
The functions are not currently used, if the need for something similar arrives the functions would have to look very different anyway. This is due to new additions and the fact that the old functions do not follow code standard. All currently active dropdowns should still work. All menus should work as well.
> Removed unused functions

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
Added chart that displays the disk usage that is in use on the server via analytics.
> Memory usage in analytics - G1 2020 w19 #8803

- DuggaSys/resulted.js
Modified the if statement to fix certain rendering issues
Co-authored-by: b18fella <b18fella@users.noreply.github.com>
> Solved issue #8632

- DuggaSys/duggaed.php
- Shared/css/style.css
See issue #8786 to see what is altered in this pull request.
> G2 2020 w19 #8786

- DuggaSys/duggaed.js
Solves #8516.
duggaed.js now has a compare function. 
I took the compare function from fileed.js and modified it a bit to make it as non complicated and easy to understand as I could. 
The sorting works with åäö characters as well as null, see screenshots. Null values are always placed at the bottom (the only instance in the testdata this occurs is in the Startdate column, I'm not sure "real" data would ever include null values but I added handling for it just in case).
**Note:** when testing this you will get a console error about markdownPen.svg not being found. This has nothing to do with the compare function and is solved by another issue/pull request.
> G2 2020 w19 #8516 added compare function to duggaed.js

- DuggaSys/duggaed.js
- Shared/dugga.js
A small maintenance fix changing all `let` declarations to `var` in the files concerned in this pull request. See issue #8831 for further details.
> G2 2020 w19 8831

- DuggaSys/resulted.js
> ResultEd now properly restores sorting by first and last name post-reload

- install/install.php
060 wasnt good, changed to 664
> 060 made catastrophe, changed to 664, should be enough.

- DuggaSys/analytic.js
The datepicker in file information now filter out which period of time the information comes from. 
Result:
[![Image from Gyazo](https://i.gyazo.com/df2be5d49b07a040654c7534b23fb6ec.png)](https://gyazo.com/df2be5d49b07a040654c7534b23fb6ec)
[![Image from Gyazo](https://i.gyazo.com/9600427658a2902feb46d2756f6ea1de.png)](https://gyazo.com/9600427658a2902feb46d2756f6ea1de)
> Solution for branch G1-2020-W19-ISSUE#8727

- DuggaSys/analytic.js
- DuggaSys/analytic.php
- DuggaSys/analyticService.php
Added RAM usage to the analytics page. Also added support to display more than 1 chart per page since this was not possible before.
> Added RAM Usage on Analytics - G1 2020 w19 issue#8801

- DuggaSys/diagram.js
To make freedrawing objects less confusing on mobile devices the last made point is marked when drawing the object.
> Now marks the last made point in freedraw for mobile ,issue #8758

- DuggaSys/analytic.js
Added cookie to make the fileinfo page remember what file has been selected.
> Added cookie to keep track of the current file being viewed

- DuggaSys/analytic.js
Fixed canvas not clearing when changing service. #8886
> Fixed canvas not clearing #8886

- DuggaSys/analytic.js
Added cookie to keep track of the last item selected in the list. See issue: #8907
> Added cookie to keep track of the last selected item in service usage #8907

- DuggaSys/analytic.js
File information tab now shows showDugga by default instead of nothing.
> Added so showDugga is shown by default - G1-2020-W20-ISSUE#8901

- DuggaSys/accessedservice.php
- DuggaSys/codeviewer.php
- DuggaSys/courseedservice.php
- DuggaSys/downloadzip.php
- DuggaSys/fileedservice.php
- DuggaSys/filereceive.php
- DuggaSys/filereceive_dugga.php
- DuggaSys/sectionedservice.php
- DuggaSys/showDuggaservice.php
- Shared/basic.php
- Shared/loginlogout.php
- Shared/resetpw.php
Added attribute username to the LogUserEntries table. Then Modified LogUserEvent function to Insert the username into the db correctly. Both of which are shown in the pictures below. 
Now all places where logUserEvent is used had to also pass the username to the function. So all places where logUserEvent is called had to be changed. These includes the eventTypes:
* ResetPW
* DuggaRead(will be triggered by reading codeviewer example)
* AddCourse
* AddCourseVers
* EditCourse
* DownloadAllCourseVers
* EditFile (Global, course, and course vers)
* DuggaFileupload
* AddFile (Global, course, and course vers)
* SectionItems
* EditCourseVers
* LoginSuccess
* LoginFail
* Logout
* RequestNewPW
* CheckSecQuestion
___ 
How to test:
Open the …
> Added username to logUser logging - G1-2020-W20-ISSUE#8900

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
- Shared/basic.php
Shows who is online, including guests on the general stats page in analytics
> Currently online users - G1 2020 w20 issue#8692

- Shared/navheader.php
Added button to visit analytics, and a back button if the user does not like the home button.
This button is only shown in courseed.
> Button to visit analytics - issue#8877

- DuggaSys/diagram.js
- DuggaSys/exampleER.txt
- DuggaSys/exampleUML.txt
Examples are now generated by importing a .txt file located in DuggaSYS. This gave much simpler and cleaner code, as well as works better.
[Issue 8622](https://github.com/HGustavs/LenaSYS/issues/8622)
To test this:
Go to help and try generating both UML and ER diagrams. Check the console for any errors, since I got an error but someone else did not get this error. It still works, but if an error occurs it would probably be worth looking into someday.
> Fixes issue 8622, generating examples not working properly

- Shared/navheader.php
The errors that used to show up due to the function not being defined has been fixed.
Co-Authored-By: a18felen <a18felen@users.noreply.github.com>
> Fixed errors

- DuggaSys/diagram.js
- Shared/css/style.css
Need to test drop-down menu "View layer" in Diagram.php. 
* changing layer while the drop-down menu is active should work now. 
* also improved styling so it should be visible if a layer is active while hovering over it 
Link http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%238884/DuggaSys/diagram.php
> G4 2020 w20 issue#8884

- Shared/css/codeviewer.css
- Shared/css/style.css
- Shared/css/template1.css
- Shared/css/template10.css
- Shared/css/template2.css
- Shared/css/template3.css
- Shared/css/template4.css
- Shared/css/template5.css
- Shared/css/template6.css
- Shared/css/template7.css
- Shared/css/template8.css
- Shared/css/template9.css
Every template now becomes mobileview as soon as the width is under 800px.
Result:
[![Image from Gyazo](https://i.gyazo.com/ed73c274b87719b354f8f2907753e7c0.gif)](https://gyazo.com/ed73c274b87719b354f8f2907753e7c0)
> Solution for branch G1-2020-W19-ISSUE#8845

- DuggaSys/analytic.php
- Shared/css/analytics.css
- Shared/css/style.css
Fixed button width.
Before:
After:
> Fixed buttons in analytics - G1 2020 w20 issue#8915

- install/install.php
Further division/revision of installer-code to make it possible to abstract the js-logic out.
Test so installer works.
> Progress on #3698

- DuggaSys/sectioned.js
The new version from updateVersion or createVersion is now added to the database. The url is updated with the new version and this refreshes the page.
To test this : create a new course and create a new version for this course.
http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%238991-2/
> G4 2020 w20 issue#8991

- install/install.php
> Revert "Progress on #3698"

- install/install.php
These changes were pushed wrong! Correcting
> G4 2020 w20 issue#3698

- DuggaSys/codeviewer.js
Added mimizieButton and its functionality to all templates. For templates 6, 7 and 9 some liberties were taken considering the interaction of the stacking since I wanted to avoid too complicated code. Changes are however possible so feel free to give feedback. Test by simply changing templates on a code example and pressing the minimizeButton on everything. Make sure to test different combinations of minimizing.
> G1-2020-W20-ISSUE#8840

- DuggaSys/resulted.js
The last exported date does now work as it's supposed.
By solving this issue, at least one more issue surfaced. Those issues will be made into separate issues because they were too big to handle in this issue alone.
> Solved the bug where the last exported date would say "undefined".

- DuggaSys/analytic.php
- Shared/css/analytics.css
- Shared/navheader.php
> Icons to replace buttons in analytics - G1 2020 w20 issue#8977

- Shared/css/style.css
Now there is a 20px margin between the radio buttons and the table.
> G3 2020 w20#8812

- install/install.php
For tester: run the installer and verify that the below popup once again show when finished.
MySQL root user: galvaniseradapa
> Renamed post-install modal and fixed #8999

- DuggaSys/sectioned.js
> Null checking

- DuggaSys/analytic.php
Fixed a php error where cookies were set after the header had been loaded then it turned out there was a second error with loading header. So we moved the including of navheader after code had ran.
This can be tested by going into analytics as superuser and as guest. only superuser should have access to the page.
> G3 2020#8902

- Shared/icons/announcement_icon.svg
- Shared/navheader.php
Added a new icon for the 'announcement' feature.
> Added Icon for 'Announcements' | Fix for issue #8701

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
Now the top fabbutton will follow the course header instead of floating on the screen
> TopFabButton follow course header#8921

- Shared/basic.php
This PR is not part of an issue, this just forces the developers to fix PHP errors since an annoying alert will show up if one is present.
> Added alert based error reporting

- DuggaSys/analytic.php
- Shared/basic.php
This PR Fixes headers already sent in analytics
> Fixed PHP errors in analytics #9035

- DuggaSys/analytic.js
- DuggaSys/analytic.php
- Shared/css/analytics.css
> Page names in analytics #9001

- DuggaSys/diagram.js
- Shared/css/style.css
Improvements done to "Write to layer" drop-down menu
* You should now be able to change "Write to layer" without deselecting the current layer.
* Changing layer in "Write to layer" should activate that layer in "view layer"
* Creating a new layer should not deselect the current layer.
* Never having a layer active in "Write to layer" should not be possible anymore
If you have any feedback or suggestions for how we can improve "Write to layer" feel free to comment.
Link to page http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%238887/DuggaSys/diagram.php
> Fixes to Diagram layer drop-down menu | G4 2020 w20 issue#8887 

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Done, while solving this issue i stumbled upon another issue where the hover would also break when the origo and origin of the map weren't aligned so i got that fixed. There should have been a separate issue for the "origo alignment" but since there was none and it would be a quick solve, i simply solved it within this one too.
> G4 2020 w20 issue#8475

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
Rulers can now be generated and toggled and is resized with the canvas. The toggle information is saved in localStorage so they will be shown or hidden depending the state before page refresh. Making a pull request for this before finishing this week and will implement the rest next week. Test so the ruler is generated properly and resized with the canvas. Test to refresh page to see so state is kept.
Functionality left to implement for rulers:
- Lines for mouse x and y position
- Lines for selected objects points
- Adapt to camera
- Adapt to zoom
I could possible divide #5943 into these 4 sub-issues.
Link: http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%235943-NEW/DuggaSys/diagram.php
> Good start for #5943 - Rulers can be generated

- install/install.php
Pull-request to get latest updates.
> Renamed post-install modal and fixed the issue.

- Shared/css/style.css
now the buttons are in the right place and not moved a bit to the right
> G3 2020 issue#9022 Now submit-buttons are in the right position

- DuggaSys/diagram.php
#8683 Styling for Import diagram is now updated. The container and button is now bigger to make sure the text fits.
http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%238683-2/DuggaSys/diagram.php
> #8683 Fixed

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
Before this change the percentage in the piecharts were not showing correctly on the test server
> Fixes Diskusage Percentage #9018

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
- Shared/navheader.php
Online users are no longer shown in the general stats tab, and now has their own tab.
> Separate tab for online users in analytics #9002

- DuggaSys/diagram.js
- Shared/css/style.css
Rulers do now adapt to camera. Test so this works when moving the camera.
Link: http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239060/DuggaSys/diagram.php
> Fixes #9060 - Rulers adapt to camera

- DuggaSys/analytic.js
- Shared/navheader.php
Added button to user information in analytic, now everyone can navigate to it.
> Added navbutton for user information in analytic - G1-2020-W20-ISSUE#9079

- install/install_entry.js
> Added windows-text

- DuggaSys/analytic.js
This PR will remember the last page the user was on in analytics. When refreshing the page, the user returns to the page that they were last on.
> Cookie to remember last page in analytics #9000

- install/install_entry.js
For tester: Checkout installer at http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%238972/install/ and see that the issue is solved.
> Removed the redundant string-part - FIXES #8972

- DuggaSys/accessed.js
- Shared/dugga.js
> Updated AccessEd to allow cells to be empty

- DuggaSys/analytic.js
Added a cookie to remember the last selected user in User Information.
> Cookie to remember last selected user #9098

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Link: http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%238885/DuggaSys/diagram.php
Test layer delete function, should be able to delete layers now
> Added delete functionality for diagram layer system | G4 2020 w20 issue#8885

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
> LenaSys Installation Size #9112

- DuggaSys/accessed.js
Fixes #8936 
The accessEd table is still buggy, but this pull request together with #8949 and #8941 should fix most of them.
> Examiner options are now updated when users gets/loses teacher access

- Shared/css/style.css
Changed top:-24px to -4px and left:-18px to -100px. So that it doesn't hide the textinput.
> Moved the positioning off .tooltipDuggatext #9115

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
The user can no longer type quotation marks in the section-name while editing a dugga. Our solotuion validates both name and date correctly when updating an item in sectioned. The user gets an errormessage and an alert if something is wrong.
> G3 2020 issue#9021 validation for quotation marks.

- Shared/css/style.css
- Shared/navheader.php
The analytics button scales down with the home button when you minimize the window / go into mobile view. Before it just disappeared. Have also scaled it down so they match.
This icon:
It's on the course page so not inside a course.
> Analytics icon doesn't disappear upon minimized window | Fix for issue # 9030

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
> Total users in general stats #9108

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Reworked code that handled switching between modes (ER/UML/Developer) so it follows a more logical flow. Before, operations happened all over the place and it wasn't clear exactly what some of the function's scope were. Now it should make more sense. It has the exact same functionality with less than half the original code.
For testing, make sure nothing breaks when switching between modes: http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%237446/DuggaSys/diagram.php
*Now updated after weekly branch changes*
> Updated: solves issue#7446

- DuggaSys/diagram.js
- DuggaSys/diagram.php
- Shared/css/style.css
The mouse position is now shown on the rulers with a line. The line is little thicker to make it more visible and do not reach the text to not obscure it. Test so these lines work and are at the right position at all times.
Link: http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239062/DuggaSys/diagram.php
> Fixes #9062 - Show mouse positions on rulers

- DuggaSys/diagram.js
Link: http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%238890/DuggaSys/diagram.php
*Needs Testing*
* User should not be able to create more then ten layers
* Having created ten layers and attempting to reload the page should not result in a unidentified layer
> Fix bug related to unidentified layer in diagram menu |G4 2020 w20 issue#8890

- DuggaSys/resulted.php
- Shared/css/style.css
The language has been changed from swedish to english in these places shown below.
> Issue #8968: Changed language from swedish to english

- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
- Shared/css/style.css
Added a placeholder to input name in Duggaed.php. Changed color to initial for making the color to the same as the other placeholders. Made string empty in duggaed.js.
> Added a placeholder to input Name in Duggaed. #8993

- DuggaSys/accessed.js
The current table in accessed is a bit buggy, so while testing one option is to rebase this branch onto `G2-2020-W20-#8909` which fixes some of it **but be very careful not to push the rebase to the branch**.
Another option is to look at the difference between this branch and `G2-2020-W20`, to see i there are any additional bugs present. 
In any case the error shown in #8942 should be gone, and the table should be able to sort by examiner.
> Fixed examiner-sorting to be alphabetical

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
> Full user list #9116

- install/CSS/install_style.css
- install/install.php
For tester: Go to http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%238311/install/ and run the installer, On the test-data page there should be an option to select "Include demo-course". Tick the box and run the installer. Verify that the democourse is there when you open the branch course-ed.
> Added checkbox for demo-course FIXES #8311

- DuggaSys/accessed.js
- Shared/css/style.css
- Shared/dugga.js
Added iterations to check if an examiner, class, version and access is set or not. "If" sets an id so it could be styled and print out all options. "else" prints out all options. Also an iteration for when an option is empty it will be styled. _See img 1._
_img 1 - Examiner_
Co-Authored-By: b18jonli b18jonli@users.noreply.github.com
> Clarified which options are selected in Accessed. #9135

- DuggaSys/sectioned.js
- Shared/css/style.css
- Added margin so the announcement box is consistent with rest of the content of the page.
- Announcement box does not disappear on delete
> #9181 is solved

- install/install.php
For tester: run installer at http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%238764-2/install/ and check that after install is finished it shows 100% not 105% or 111%
mysqlrootpassword: galvaniseradapa
> Changed a value FIXED #8764

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Deadline will now be validated and when editing sectionitems that doesnt use deadline it will not be validated or shown.
> fixed deadline check if not used. ISSUE#9195

- DuggaSys/duggaed.js
Co-Authored-By: c14jonfr <c14jonfr@users.noreply.github.com>
> Added validateDuggaName() when a dugga is selected. #9104

- code_standard.md
Updates `code_standard.md` to reflect the preferences of the customer in the following discussion https://github.com/HGustavs/LenaSYS/issues/8831.
> G2 2020 w20 #9147

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
- Shared/navheader.php
> Course specific disk usage #9111

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
All pages are now added, with the exception that they are not all connected to the dropdown yet. Before connecting them additional work needs to be made on each one of the pages, this will take some time and therefore it's better suited for a separate issue. I will make the issue once this pull request is merged.
> Added all the pages to page information - G1-2020-W20-ISSUE#9077

- Shared/basic.php
This PR changes the filename to another number to make sure that we do not run an outdated sqlite database
> SQLite database versioning #9220

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
On analitycs page information the names of the courses should now be visible in the table.
> G1 2020 w20 issue#8906-2

- DuggaSys/resulted.js
- DuggaSys/resulted.php
- Shared/css/style.css
Solved the specified issues in issue #8851, it should now be possible to filter by only pending and late submission simultaneously, in normal mode and mini mode.
Also made some styling changes to the mini mode as well as the legend list.
(The legend list was not supposed to be adjusted here. Can be removed if it creates any conflicts). 
Co-Authored-By: a18viksa <a18viksa@users.noreply.github.com>
> Resulted:G2 2020 w20 #8851

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
Now youre able to create a new course verision without the validation immediately giving an error for the version id.
> G3 2020#9252

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
> Top OS / Top Browser #9177

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
> Top Page #9105

- Shared/basic.php
> Fixed error handling exclusion on service files #9253

- DuggaSys/codeviewer.php
> Fixes errors output by codeviwer #9258

- DuggaSys/filereceive.php
Username and userid as argument in every logUserEvent
> Username and userid

- Shared/basic.php
Not G2-issue/fix, but we want this in our branch without having to wait for a new weekly merge.
> Fix for error handling in *service.php files

- DuggaSys/sectioned.js
When editing an course-version it will now work and the information will be updated.
> Now edit-course-version work | issue #9277

- DuggaSys/codeviewer.js
Updated function "resizeBoxes" to better fit the code standard.
Test by changing sizes of different sections within all available templates. Every template should have existing resizing functionality and these should not generate any errors. Make sure to try several resizing configurations in different orders (e.g first resize height of a specific box before resizing the width of all boxes). Make sure to test by resizing in different orders in templates 6,7,9.
> G1 2020 w21 issue#8711 

- DuggaSys/analytic.js
> Fixed last seen to work in Safari and Firefox #9206

- install/install_defer.js
Now one should be able to click the spacebar and fill all values on the "Write over?" page in the installer.
For tester: Go to http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%239248/install/ and run the installer. When on "Write-over?"-page click the spacebar to fill all values. Approve if this works!
> Extended algorithm for focusTheRightBox() FIXES issue#9248

- install/install.php
- install/install_defer.js
For tester: run the installer at http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%239325/ and check so there are no uncaught errors.
> Added if-checks for functions to avoid errors FIXES #9325

- DuggaSys/sectioned.js
- Shared/SQL/init_db.sql
- Shared/announcementService.php
- Shared/css/style.css
- Shared/navheader.php
- Shared/retrieveAnnouncements.php
- Shared/retrieveUserid.php
- Shared/updateviewedAnnouncementCards.php
- if you edit an announcement then the announcement is marked as 'edited' at the bottom of the announcement card
> G3 2020#9053 is solved

- DuggaSys/sectioned.js
- Shared/SQL/init_db.sql
- Shared/announcementService.php
- Shared/css/style.css
- Shared/navheader.php
- Shared/retrieveAnnouncements.php
- Shared/retrieveUserid.php
- Shared/updateviewedAnnouncementCards.php
- See the commits related to this pull requests
> G3 2020#8864 notification works... kind of

- Shared/css/analytics.css
- Shared/navheader.php
There are now comments for the icons and the title for html tags has been removed as they became redundant.
Should look like this:
> G1 2020 w21 issue#9120

- Shared/css/analytics.css
This is just a finetune after merge, doesn't change how the issue was fixed only changed some margins and timer on transition.
> Finetuned margins and added a short transition (Issue already merged once)

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Solves #6261
Made it possible to move the middle divider of UML-class objects
http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%236261/DuggaSys/diagram.php
> It is now possible to move the middle divider of UML-classes

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
> Fastest and Slowest service #9341

- Shared/navheader.php
In chrome, perhaps other browsers as well, the neavheader search bar won't be autofilled with some text anymore. For me it was always autocompleted with my username a18jenro. So one always had to remove that search to actually see any results.
This was fixed not only for fileed, but all places where the navheader searchbar is used.
> G3 2020#8815

- DuggaSys/analytic.js
- Shared/basic.php
Test by selecting "events" in the dropdown for a user that have events. The name describing the event type should be visible in the table.
> G1 2020 w21 issue#9099

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
Top viewed dugga and example is now shown in general stats.
Dugga ID and Example ID with number of hits.
> Top viewed Dugga and Example

- DuggaSys/fileed.js
- DuggaSys/fileed.php
I removed comments.
The code that I found to be dead was commented.
Such that the next time someone decides to do a cleanup, they too can just remove the commented code. If some code turns out to be important anyway, then it can just be uncommented.
> G3 2020#8524

- install/install.php
- install/install_defer.js
Couldn't find any weird scoping. Fixed two comments in install.php and an uncaught error in defer.js
Run installer at http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%239250-3/install/ and check for uncaught errors. If none, approve!
> G4 2020 w21 issue#9250 3

- DuggaSys/diagram.js
Test Layer function for any bugs. There there is no new functionality just improved the code structure
Link:http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%238891/DuggaSys/diagram.php
> Improve Layer Code and add comments - Solves Issue 8891

- Shared/css/codeviewer.css
- Shared/css/style.css
Changed the media qureies css to make the navbar better looking in the mobile view.
Result: [![Image from Gyazo](https://i.gyazo.com/c3aaa986b226d96a0e90c059729e52fa.png)](https://gyazo.com/c3aaa986b226d96a0e90c059729e52fa)
> Solution for branch G1-2020-W19-ISSUE#9300

- DuggaSys/analytic.js
> Fixed a logic issue in barcharts

- DuggaSys/diagram.js
- DuggaSys/diagram_IOHandler.js
Closes#9149 Test this by changing a keybind and then refresh the page, if the keybind doesn't reset back to it's default the code works.
> G4 2020 w21 issue#9149 keybinds now stored in localstorage

- Shared/navheader.php
> Updated tooltip to OS Percentage #9406

- DuggaSys/codeviewer.js
<a href="https://gyazo.com/10d70f3ab666e76ba561fdfa6aa9c04b"><img src="https://i.gyazo.com/10d70f3ab666e76ba561fdfa6aa9c04b.gif" alt="Image from Gyazo" width="1918"/></a>
> Template 8 no longer gives a fixed top to box 3 when resizing the width

- Shared/SQL/init_db.sql
> #9295 Changed all the letters in userDuggaFeedback table to lowercase.

- DuggaSys/sectioned.js
> #9347 Made it only possible to add feedback on duggor.

- DuggaSys/sectioned.php
Removed dead code that had returned somehow.
> Removed dead code #8525

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
> Filesize added to dropdown #9342

- DuggaSys/diagram.js
- DuggaSys/diagram_objects.js
Solves Issue #9379 
We should now be able to lock objects again. Should also work for different layers where locked object are stored as lock when changing between layers
Test link: http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%239379/DuggaSys/diagram.php
> Fix locked functionality - Solves Issue 9379

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
New pull request after changes have been requested on last one (https://github.com/HGustavs/LenaSYS/pull/9235) since it's needed on the newest branch.
> Updated from pull request 9235 (G1-2020-W20-ISSUE#8802)

- DuggaSys/accessed.js
> Added missing check for 'access' when sorting

- DuggaSys/duggaed.js
To test: login, go to for example Webbutveckling - datorgrafik, go to "Show tests" (duggaed), observe that the search function still works but that it does not try to autofill the search bar or give suggestions.
> G3 2020#9398

- DuggaSys/sectioned.js
- Shared/SQL/init_db.sql
- Shared/announcementBox.php
- Shared/announcementService.php
- Shared/css/style.css
- Shared/retrieveAnnouncements.php
- Shared/retrieveuser_course.php
- Shared/retrievevers.php
- Shared/updateAnnouncement.php
- Shared/updateviewedAnnouncementCards.php
- to distinguish the students first you have select a course then the course-version field will be enabled after you select a course-version then you can select the students in that course and course-version that you want to send the announcements to.
> G3 2020#9242 is solved

- DuggaSys/diagram.js
User should not be able to delete all layers anymore, also fix bug related to no layer being active in "Write to layer" drop-down after delete call.
Link :http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%239312/DuggaSys/diagram.php
> Fix so user can't delete all layers anymore - Solves Issue 9312

- DuggaSys/duggaed.js
- Shared/navheader.php
The search bar and search button icon should all have the same vertical and horizontal positions in these tabs:
> Changed the navheader to be more consistent

- DuggaSys/sectioned.js
- Shared/announcementBox.php
- Shared/css/style.css
- You can select and de-select all the recipients at once
> G3 2020#9383 is solved

- DuggaSys/filereceive.php
- Shared/basic.php
You no longer get errormessages while uploading certain files in fileed.
> G3 2020 issue#9321

- DuggaSys/sectioned.js
You need to login in to "keree" to test this issue, you can change the MOTD with the "brom" account to check that it shows the right message
> Now students can see MOTD #9262

- DuggaSys/showDugga.php
- DuggaSys/testDugga.php
> Changed align center to left. #9456

- DuggaSys/sectioned.js
- the announcement form will not submit till you all the newly implemented fields are filled
> G3 2020#9385

- DuggaSys/analytic.js
> Number of times event has been preformed #9407

- DuggaSys/accessed.js
> Added check for missing parentElement

- DuggaSys/sectionedservice.php
> #9255 if statement; feedbackenabled to 0 if feedbackenabled isnt 1

- Shared/SortableTableLibrary/style.css
Removed the duplicate navheader style in sortableTable.css
> G2 2020 w21 #9443 (Remove duplicated style in CSS)

- DuggaSys/templates/clipping_masking_dugga.html
- DuggaSys/templates/clipping_masking_dugga.js
- Shared/css/dugga.css
Now it looks much better than before. But it looks a bit strange when you scale. But I intend to put a new issue on and fix it on the next weeklybranch.
> Change infobox and fixed layout on Random clipping dugga. #9472

- Shared/navheader.php
- Announcement icon is only visible if you are logged in
> #9394 is solved

- DuggaSys/resulted.js
> #9279 fixed filtering so it removed ppl outside of the criteria

- DuggaSys/diagram.js
Link: http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%239380/DuggaSys/diagram.php
*Needs testing*
*test developer mode crosses should be restricted to layers now
Issue link #9380
> Fix cross dots in developer mode -Solves Issue 9380

- DuggaSys/analytic.php
Non superusers get redirect to duggaeed.
> Fixed redirect for non superusers in analytics #9484

- DuggaSys/analytic.php
> Fixed logout button in analytics #9485

- DuggaSys/sectioned.js
- Shared/SQL/init_db.sql
- Shared/announcementBox.php
- Shared/css/style.css
- Shared/retrieveuser_course.php
- Students who have completed the course is distinguished from the students who haven't
- And you can multicast announcements to finished and non-finished students.
> G3 2020#8862 is solved

- DuggaSys/sectioned.js
It now work to change a course-version, the link will work
> G3 2020#9473 fix

- DuggaSys/diagram.js
- DuggaSys/diagram.php
The selected mode now doesn't change when refreshing page. To test, navigate to http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%239271/DuggaSys/diagram.php and try to break something by switching between modes and refreshing page
> solves issue#9271

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
Added a section that displays the name of the most recently edited file in LenaSYS, along with the time it was edited.
Test by editing a file in the fileed-section and then observing the general stats section of analytic after the edit has been made. The new section should look like the following image:
> Added section in general stats that displays most recently edited file.

- Shared/SQL/init_db.sql
- install/install.php
Komment – [text] */
AUTO_INCREMENT			SERIAL
DATETIME 				TIMESTAMP WITHOUT TIME ZONE
TINYINT(x)				SMALLINT
decimal(x,y)				NUMERIC(x, y)
Removed CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
> Changed some syntax

- DuggaSys/diagram.js
Error removed when pressing delete and no object is selected
Try it: http://group4.webug.his.se:20001/G4-2020-W22-ISSUE%239501/DuggaSys/diagram.php
> solves issue#9501

- Shared/SQL/init_db.sql
- install/install.php
init_db has now been adapted to postgres and runs correctly
> Sql migration issue#9504

- DuggaSys/fileed.php
- Shared/css/style.css
The buttons now doesnt move out of the windows when resizing.
Result: [![Image from Gyazo](https://i.gyazo.com/debf6f9529896a449585dcdf6bc44aa3.gif)](https://gyazo.com/debf6f9529896a449585dcdf6bc44aa3)
> Solution for branch G1-2020-W19-ISSUE#9446

- DuggaSys/analytic.js
There should now be an option for loginFail in the dropdown. When selected it should display a table and a counter for LoginFail events.
> G1-2020-W22-ISSUE#9338

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
Biggest course in general stats
> Biggest Course #9468

- DuggaSys/fileed.php
This should now refresh css and js files everytime the php is loaded.
> Timestamp now added to css and JS files to auto-refresh in fileed.php

- DuggaSys/sectioned.js
- Shared/css/style.css
- multiselect of recipients works without holding down the ctrl key
!OBS:
the update function did not work before, I had to fix that problem prior to solve this issue, that's why I didn't create an separate issue for that.
> G3 2020#9477 good news

- Shared/basic.php
courseid and coursevers will always be the first elements in the json output, this will make writing queries a lot easier since they have a fixed position, compared to what they could have when only referencing the refer that could have them at a random position.
> Added logging of URL Parameters

- DuggaSys/resulted.js
> G2 2020 w21 #9498 Added Descriptive comments

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
Added what courses user partake in user information.
> Added what courses user partake in - G1-2020-W22-ISSUE#9356

- DuggaSys/fileed.php
Sessions will start before loading basic now.
> Fileed userhistory #9624

- DuggaSys/analyticService.php
> Service speed will no longer show null values #9629

- DuggaSys/resulted.js
Kept the "Unassigned" moments as "Unassigned" in the different filters
> #9427 fixed incosistencies between different filters

- DuggaSys/resulted.php
- Shared/css/style.css
...and also added some description of the code that we have done for better comprehension.
Solves issue #9523 
> Issue #9523: Changed some names in the legend in resultEd and added code.

- DuggaSys/analytic.js
> Time will now be converted from UTC to CET for newest file #9635

- DuggaSys/analyticService.php
> Fastest service in general stats will now only show services #9638

- Shared/css/codeviewer.css
> Important rows now have same line height as normal rows

- DuggaSys/diagram_objects.js
Test url: http://group4.webug.his.se:20001/G4-2020-W22-ISSUE%238087/DuggaSys/diagram.php
Test for UML jump line when two uml lines intersects
Issue #8087
> Added Jump Line for UML lines | G4 2020 W22 issue#8087

- DuggaSys/analytic.js
> FileEvents now works even when no data is available

- Shared/calendar.php
Logging for downloading calendar is now working for userhistory.
> Added userhistory logging to calendar #9659

- DuggaSys/analytic.js
- DuggaSys/codeviewer.php
- Shared/css/analytics.css
- Shared/css/markdown.css
Solved template issues by changing priority, also changed some misspelling which didn't need another issue.
> Solved template 3 issue and one spelling error.

- DuggaSys/analytic.js
> Fixed timestamp in user history events

- DuggaSys/analytic.js
> Login Fails is no longer off by two hours in user information #9692

- DuggaSys/analytic.js
> FileEvents no longer off by two hours #9694

- DuggaSys/analytic.js
> User Information showDugga no longer off by two hours #9695

- DuggaSys/analytic.js
TimeStamp now the same as computers time.
> G1-2020-W22-ISSUE#9700

- DuggaSys/analytic.js
Made the timeStamp be the same as the computers time.
> G1-2020-W22-ISSUE#9697

- DuggaSys/diagram.js
Link: http://group4.webug.his.se:20001/G4-2020-W22-ISSUE%239996/DuggaSys/diagram.php
Test deleting layers for the error described in issue #9666 
Issue #9666
> G4 2020 w22 issue#9666

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
Added a 'scroll to top' function in sectioned.php. 
The arrow appears when you scroll down 200px on the page in sectioned.php. It has a hover effect that displays a tooltip and change in opacity. When you click the arrow it brings up back up to the top of the page.
Some courses aren't long enough for a user to scroll down to where the arrow appears. The course "demo-course" is long enough, tip for the tester. Or just add more items until the page gets longer.
> Scroll to top function | Fix for issue #9564

- DuggaSys/analytic.js
Selected item in user information will now be saved on page refresh and on user change.
See:
> Selected item in user information #9704

- DuggaSys/codeviewer.js
Replaced JQuery functionality with native Javascript equivalent and fixed incorrect indentation according to the standard.
Test by checking if the minimizing functionality still works on every box in every template, as it should work without any problems just like before the update.
> minimizeBoxes now better fits the code standard

- Shared/css/style.css
> #9714 created a hover effect on "Reset-PW" buttons

- DuggaSys/sectioned.js
> #9710 Changed From N/A to Anonymous when username data is unavailable

- DuggaSys/accessed.js
Solves issue #9346 
The columns that can have a value of null or in other way not filled in value now displays the word "None" in a muted grey colour.
To test go to datorgrafik course and click the padlock in the navbar while logged in as a super user.
> Issue #9346: Made certain columns display none

- DuggaSys/codeviewer.js
You should now be able to add new imp rows and click save to keep them.
> Added rows should now save and shown as important

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
This PR only has code refractions
> Refraction of Cvers and CID to not use splits #9736

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
Added duggaed, profile and accessed to user information in analytic.
> Solution for branch G1-2020-W19-ISSUE#9679

- DuggaSys/analytic.js
- DuggaSys/analyticService.php
> Calendar subscriptions in user information #9712

- DuggaSys/accessed.php
Fixes issue #9562 and tiny bit of refactorization as well...
> Moved add and import buttons

- DuggaSys/accessed.js
- Shared/SortableTableLibrary/sortableTable.js
Fixes #9675 
To make it easier to review the first commit contains all code changes and the second commit contains comments.
> Only opens dropdown menu-arrow with dropdown menu

- DuggaSys/sectioned.js
Just a minor fix to #9719 and should not cause any merge conflicts. 
Now it says "Submission" instead of "Submition" and "Feedback" instead of "feedback".
> Fixed spelling mistakes in sectioned

- DuggaSys/sectioned.js
Studentteachers and supervisor can now see the course-version dropdown and select different versions. 
test with:
Studentteacher: Got 'ST' access for all courses.
mofre
Supervisor: Got SV access for all courses.
ryrey
Password is ‘password’.
> Added the course-version dropdown to studentteacher and supervisor

- Shared/css/style.css
- Now you can't resize the textarea
> G3 2020#9610 is solved:

- DuggaSys/showDugga.php
- Shared/dugga.js
Solves #9671 fixed some style issues:
Co-Authored-By: c14jonfr c14jonfr@users.noreply.github.com
> G2 2020 w22 #9671

- DuggaSys/duggaed.php
- DuggaSys/showdoc.php
- install/courses/2/minimikrav_m2.md
Fixes #9521
Requires reinstallation to add the file to the system.
> Added new file for 'Rapport inlämning'

- DuggaSys/resulted.php
Solves issue #9744 
Minor styling is also included.
> Issue #9744: Translated from swedish to english in the last option of ladExport

- DuggaSys/templates/dugga3.js
There only reason why it didnt show up was because the student had handed in the dugga without answers.
> #9646 Created if statement to prevent feedback textbox not showing up.

- DuggaSys/analytic.js
- DuggaSys/analytic.php
- DuggaSys/codeviewer.php
- Shared/css/blackTheme.css
Adden dark mode to the **analytic** and **codeviewer** pages, since those are the pages that Group 1 are in control of. Part of issue #7761
> Added dark mode to analytic and codeviewer. #7761

- DuggaSys/diagram.js
Test Link: http://group4.webug.his.se:20001/G4-2020-W22-ISSUE%239381/DuggaSys/diagram.php
*Needs Testing*
Test so objects in hidden layers cannot be moved.
test having object within different layers stack on-top of each other if there any issues selecting objects.
Issue #9381
> Solves Issue 9381

- GPL2.txt
One new line added for issue #9775
> Added new line for issue #9775

- DuggaSys/diagram.css
Disabled text selection when moving entities.
> Disabled text selection #9811

- DuggaSys/diagram.css
- Shared/css/style.css
Fixed by adding position and z index to diagram-header
> entities overlapping header

- DuggaSys/diagram.js
Solved ISSUE#9830.
Other features were also introduced which were required in order to solve the bug without creating something that would break in the future. I also added some additional comments were I saw fit.
List of changes:
* Objects will no longer freak out when placed on top of each other
* Selection of several objects at once
* De-selecting options
* Selected objects will change in colour (beta feature, should be fixed within its own issue)
* Introduced global variable for indicating when the mouse has been dragged more than a set amount from start X/Y
> Group3 2021 #9830

- DuggaSys/sectioned.php
- Shared/css/style.css
Removed the assingment pane and css related to it
modified style.css and sectioned.php
saved statisticslist swimlanes as comment since a furture issue needed it
> G2 2021 w14 issue#9783

- DuggaSys/sectioned.php
- Shared/css/style.css
> Revert "G2 2021 w14 issue#9783"

- DuggaSys/diagram.css
Added z index: -10 to the line overlay layer.
> Group3 2021 #9791 - Fixed diagram line overlay layer

- DuggaSys/showDugga.php
- DuggaSys/templates/3d-dugga.js
- DuggaSys/templates/bit-dugga.js
- DuggaSys/templates/boxmodell.js
- DuggaSys/templates/clipping_masking_dugga.js
- DuggaSys/templates/color-dugga.js
- DuggaSys/templates/curve-dugga.js
- DuggaSys/templates/daily-minutes.js
- DuggaSys/templates/dugga1.js
- DuggaSys/templates/dugga2.js
- DuggaSys/templates/dugga3.js
- DuggaSys/templates/dugga4.js
- DuggaSys/templates/dugga5.js
- DuggaSys/templates/feedback_dugga.js
- DuggaSys/templates/generic_dugga_file_receive.js
- DuggaSys/templates/hashGenerator.js
- DuggaSys/templates/html_css_dugga.js
- DuggaSys/templates/html_css_dugga_light.js
- DuggaSys/templates/placeholder_dugga.js
- DuggaSys/templates/shapes-dugga.js
- DuggaSys/templates/transforms-dugga.js
when clicking save a random number is generated that gets hashed and transformed from decimal to hex.
> added hash

- DuggaSys/sectioned.js
- Shared/css/style.css
Remove the variable grade and replaced the if-else statements controlling the color of the lightbulb with a static greybulb.
Also remove the unused styles for the bulbs in style.css
Co-Authored-By: b19wilfo <62884368+b19wilfo@users.noreply.github.com>
> Removed color from bulbs

- DuggaSys/showDugga.php
- Shared/dugga.js
URL and password is now shown in the dialog
> Added URL and password to dialog

- DuggaSys/diagram.js
Fixed by adding a key detection function  to the entities so that grouping is more easier
> Grouping of objects with keypress

- DuggaSys/sectioned.js
Add scroll to courses longer than 10 weeks
> G2-2021-W14-ISSUE#9873

- DuggaSys/diagram.js
Removed/fixed issue where lines didn't fully extend to the corresponding boxes.
> Updated diagram lines

- DuggaSys/diagram.js
- DuggaSys/diagram.php
There is now a way to create elements on the canvas based on with mode you're in. The buttons still needs to be styled but this could be another issue to be created.
> Group3 2021 #9818

- DuggaSys/diagram.js
when selecting elements in diagram, box-marker appears around selected elements.
> Creates box-markers around selected elements

- DuggaSys/diagram.js
Updated the selection function to work with CTRL and ALT
> ISSUE#9883 Updated selection method

- DuggaSys/diagram.css
- DuggaSys/diagram.php
Fixed mouse pointer when hovering over mouse mode buttons, also for the "+" sign.
> Mouse pointer

- DuggaSys/showDugga.php
- Shared/dugga.js
removed random url and added the hash instead, also removed the "Hash:" from receipt since it already is displayed in the url.
Also changed the hash from base16 to base64 (youtube style)
> added hash to url

- DuggaSys/resulted.php
- DuggaSys/showDugga.php
- Shared/dugga.js
Students can't download submitted assignments. They can only see file name, date and file extension. 
Teachers (Super users) have access to the download functionality, either by clicking the pdf link or by pressing the download button. A boolean flag determines whether the download should be enabled or not, depending on the active user if they are teacher or student. 
However, Zip submissions are unmodified. This is a seperately issue #9782.
> G1-2021-w15-#9795

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
Ruler pointers and "bars" has been added to the diagram.
This pull request resolves #9835
> Added ruler to the diagram - Issue 9835

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Added a button in the side bar menu to toggle into draw lines mode which enables you to create lines from an entity to another.
> Added functionality to create lines between entities

- DuggaSys/diagram.js
Added the same functionality to the "cmd" key for Mac users as the "ctrl" key have for the Windows users. Issue #9900
> Added the "cmd" as alternative key for control.

- DuggaSys/diagram.js
Added a function to delete one or more selected entities includeing connected lines withthe delete key. 
This resolves issue #9860
> Added delete functionality for delete key

- DuggaSys/sectioned.js
Update to sectioned.js with template literals on long lines to increase readability.
> Template literals on sectioned.js

- DuggaSys/diagram.css
- DuggaSys/diagram.js
> Made the elements selection box dashed

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
> Merged main into #9848 branch and fixed bugs

- sh/index.php
Moved index.php closer to root
> Changed location of index.php

- DuggaSys/resulted.php
- DuggaSys/showDugga.php
- DuggaSys/templates/generic_dugga_file_receive.js
Removed the upload buttons for teachers (superusers).
> G1 2021 w15 #9903

- Shared/dugga.js
Replaced the if-statements to alwats show a static white lightbulb in the navbar and set the message to "Dugga".
Co-Authored-By: b19wilfo <62884368+b19wilfo@users.noreply.github.com>
> Update dugga.js to only show whitelight

- DuggaSys/accessed.js
Co-Authored-By: a18willi <81558529+a18willi@users.noreply.github.com>
> Made the validateSSN function compatible with "samordningsnummer" Issue #9765

- .htaccess
- sh/index.php
> G1 2021 w15 #9954

- DuggaSys/diagram.css
- DuggaSys/diagram.js
Added nodes to the selected marking, this resolves #9917 .
> Added nodes to selected entity

- DuggaSys/sectioned.js
Changed textcolor in swimlanes for when deadlines are not updated to current year.
Also changed year of deadline to give a guesstimated timeframe.
> G2 2021 w15 issue#9874

- DuggaSys/accessed.js
Changed current string based system with template literals where the a row of code exceeded 80-100 characters.
Only changed where it increased the readability of the code.
> Replaced string based sytem with template literals

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
Co-Authored-By: Hamlet Magnusson Millqvist <81571224+a19hammi@users.noreply.github.com>
Co-Authored-By: a19phith <62882844+a19phith@users.noreply.github.com>
> Can now change element names #9872

- DuggaSys/diagram.js
Added the cancel functionality by pressing the escape button
> Group3 2021 w15 #9945

- Shared/dugga.js
Quick fix to add a missing bracket in dugga.js that broke execution
> fix- G1-2021-W15-#9865

- DuggaSys/diagram.css
#9971 fixed by adding some value to top in diagram.css
> Options menu covers the ruler

- DuggaSys/showDugga.php
- Shared/dugga.js
created function in dugga.js that enablet setting the value of a variable that represents the dugga title, this function is called in showdugga.php since this file has access to the dugga title
> updated dugga.js and  showdugga.php

- DuggaSys/showDugga.php
- Shared/dugga.js
PDF's/zip can no longer be downloaded from feedback preview by students
Co-Authored-By: a13zanal <62987694+a13zanal@users.noreply.github.com>
> Final commit

- DuggaSys/diagram.js
These shortcuts are just a placeholder until we decide on the actual design, but the functionality should be there.
> Group3 2021 w15 #9963

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
> Grid function #9973

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
Reverts HGustavs/LenaSYS#9992, accidental click, no review yet...
> Revert "Grid function #9973"

- DuggaSys/accessed.js
- DuggaSys/accessed.php
Added and modified validations for all options except ssn and email, removed 'Ny' as option since no explanation of what it was for could be given
> Validation in 'create user' form issue#9753

- DuggaSys/resulted.js
Updated export popup window to stay fixed in one position while scrolling.
Coauthor- @a19danla
> Updated export popup window

- DuggaSys/diagram.php
@a19frelu 
second pull request
> Grid function

- DuggaSys/diagram.php
Added code that was accidently removed when this functionality was conflict resolved.
> Fix - code added for mwheel zoom #10003

- DuggaSys/diagram.js
Removed booleans from ER elements and added states. Now we will use state: weak instead of isWeak: true. 
Added drop down in option menu and with the drop down you can change states of ER elements.
> Issue-#9946

- DuggaSys/accessed.php
- DuggaSys/courseed.js
- DuggaSys/duggaed.js
- DuggaSys/duggaed.php
- DuggaSys/fileed.js
- DuggaSys/resulted.php
- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/dugga.js
- Shared/navheader.php
Alt tags for most visible icons/images.
> G1 2021 #9825

- DuggaSys/diagram.js
Reverts HGustavs/LenaSYS#10001
> Revert "Issue-#9946"

- DuggaSys/diagram.js
Changed the cursor depending on which mouse mode the user is currently in.
I suggest we create an issue that implements custom made icons for the cursor for the user interaction. Mainly to make it more clear in which mode the user is currently in.
> Changed cursor icon depending on hotkey selection #9998

- .htaccess
- sh/query.php
Tested with different document roots.
But make sure it works if your root isn't: localhost/LenaSYS/
> G1 2021 w15 #10012

- Shared/css/style.css
Changed fonts of the boxes "Start date" and "End date" to match the remaining boxes in sectioned.
> Update fonts in sectioned Issue#9413

- DuggaSys/showDuggaservice.php
- Shared/dugga.js
Assignement is now stored to database when save is clicked.
Co-authors: @B18mohah and @a16erilj
> G1 2021 10023

- install/SQL/testdata.sql
> G1 2021 w15 #10011

- DuggaSys/diagram.js
Added enums for states in ER elements. By clicking on an element you can change the state in the option menu. 
Use branch Group3-2021-W15-#9946
> Issue #9946 created drop down in option menu

- DuggaSys/diagram.css
Now it should work since curly bracket has been added.
> Curly bracket added

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
> "Fixed" Enable grid function

- DuggaSys/diagram.js
Fixed the resizing issue with the ruler.
> Fixed ruler resize - Issue #10018

- DuggaSys/diagram.css
Fixed by replacing z-index: 10 to z-index: -10
> "Fixed" - marker goes over the ruler and yellow button

- DuggaSys/diagram.js
Co-Authored-By: a18nadma <49141885+a18nadma@users.noreply.github.com>
> Fixed: Center / Left alignment of text in diagram #9792

- DuggaSys/showDugga.php
- Shared/css/style.css
updated layout of receipt box by moving elements and styling
> updated html in showdugga.php and css in style.css

- DuggaSys/diagram.js
Now weak entities will have double border as the other weak elements.
> Fixed weak entities

- DuggaSys/diagram.css
- DuggaSys/diagram.js
Fixed a text underline when the attribute "key" is chosen to indicate that it is in fact, a key attribute.
> Fixed Key Attribute Underline

- DuggaSys/showDugga.php
- Shared/dugga.js
- sh/index.php
sets the hash variable depending on url parameter
> update dugga.js, showdugga.php, index.php

- DuggaSys/diagram.js
Changed the magic numbers to enums. Also removed an unused element-type NO_SELECTED
> Changed magic-numbers to enums

- DuggaSys/diagram.css
Since the default mouse mode is pointer we auto set the cursor to pointer at start
> Added a default mouse cursor on load

- DuggaSys/diagram.js
Moved function call (generateContextProperties) from updatepos to updateSections
> Moved function call from updatepos to updateSections

- DuggaSys/diagram.js
Fixed by adding a new varible who represent the entity's state and then add a select attribute to the drop down list
> "Fixed" save the dropdown properties

- Shared/navheader.php
Deleted margin to avoid gaps between the icons!.
> Inconsistent spacing between icons in the Navheader

- DuggaSys/showDugga.php
- DuggaSys/showDuggaservice.php
- Shared/dugga.js
- sh/index.php
Saved assigments are now related to hash. To save without being logged in, see issue #10017.
> G1 2021 #9910

- DuggaSys/showDugga.php
- DuggaSys/showDuggaservice.php
- Shared/dugga.js
- sh/index.php
Removed login requirements to save dugga.
> G1 2021 #10017

- DuggaSys/showDugga.php
- Shared/dugga.js
Fetch password to the corresponding hash in showDugga.js and use it in a function in dugga.js that changes the password value
As the hash is not currently present in the url, you can manually add it when testing.
> Update showDugga.php and dugga.js

- DuggaSys/sectioned.js
Removed the if-else statements that were removed in issue#9863 but somehow never merged into the groups masterbranch.
> Removed unused code

- DuggaSys/contribution.js
Added template literals on contribution.js
Co-author: @a19danla
> G2 2021 w16 issue#9827

- DuggaSys/showDugga.php
- Shared/dugga.js
Removed the ability to send email after saving an assignment. Also removed the function from dugga.js. We also took the freedom to remove some old unnecessary outcommented code.
> G1 2021 #10101

- DuggaSys/showDugga.php
Assignments without variants no longer saves to localstorage
Co-author
b18jacha
e15marol
> Assignments localstorage

- DuggaSys/sectioned.js
Fixed a syntax error on line 1584
> Fixed syntax erros

- Shared/dugga.js
Updated generateHash()-function so that it does not always start with a “1”. As well as make every combination, of 6-8 character, for the hash possible
> G1 2021 #10039

- DuggaSys/diagram.js
You can now use ctrl and alt to select multiple lines and deselect lines.
> Now possible to select multiple lines #10111

- DuggaSys/diagram.js
- DuggaSys/diagram.php
Now when you are in entity creation mode, you have a ghost element following your cursor.
> Added ghost elements when you are adding Entities ISSUE#10082

- DuggaSys/diagram.js
Removed unused parameters from functions "updateSelection", "onMouseModeDisabled" and "onMouseModeEnabled".
> Removed unused parameters

- DuggaSys/showDugga.php
- Shared/dugga.js
Using a hash you now get a pop-up screen asking for the password. Functionality to check the password is not implement, the box is just closed and no content displayed. 
Closes #9858
> G1 2021 w16 #9858 rebase

- DuggaSys/diagram.js
OK, on a bit more serious note. data[] should ONLY contain finished and constructed elements, and not data that is NOT supposed to exist!!!
fixes #10135
> Issue #10135: Ghost busted from data

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
Added an new function to display messages in the diagram, this includes success messages and error messages.
> Added an message promp and errors-messages to lines.

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
Created an new toolbar
Moved mousemodes from options to the new toolbar.
Moved zoom in / out from options to the new toolbar.
This solution was made with @a19aleda and resolves #9986.
> Created an new toolbar, moved mousemode and zoom to it.

- Shared/dugga.js
Notice all changes been commented out. This enables later repurpose of functionality when canvas integration is done.
> Issue #10138 - "Remove teacher feedback part of student submission"

- DuggaSys/sectionedservice.php
Updated sectionedservice.php to no longer use the "tabs" column in the table "listentries".
Fixes #9870
> G2 2021 w16 issue#9870

- DuggaSys/diagram.css
- DuggaSys/diagram.php
Inverted the zoom buttons and added some css.
> Fixed zoom button placing

- DuggaSys/sectioned.js
Set motd before if-statement so that's it's displayed for everybody not just student teachers and those with write-access
Co-Authored-By: @b18phika
> MOTD now shows for all users, not only superusers. Issue#8551

- DuggaSys/sectioned.js
- DuggaSys/sectioned.php
- Shared/css/style.css
Removed statiscsList that was on the left side. 
removed PHP, JS, and css code.
> G2 2021 w16 issue#9783

- DuggaSys/templates/generic_dugga_file_receive.js
Removed the login-lock.
Removed the variable "score" from both the global section and from the saveClick() function, since it was never used when saving the dugga.
> G1 2021 #10142

- DuggaSys/diagram.css
- DuggaSys/diagram.php
Added an ID to the div that was overlapping and then added styling
> Fixed overlapping div in option-menu

- DuggaSys/templates/daily-minutes.js
Deleted login-lock and score from daily-minutes.js
> Deleted login-lock and score, issue #10144

- DuggaSys/templates/group-assignment.js
Removed login-lock and score from group-Assignment.js
> Removed login-lock and score #10145

- DuggaSys/diagram.css
- DuggaSys/diagram.php
- Shared/icons/diagram_zoomin.svg
- Shared/icons/diagram_zoomout.svg
Replaced the button types with custom made svg images that should better represent the functionality.
> Added appropriate svg images

- DuggaSys/diagram.css
- DuggaSys/diagram.js
- DuggaSys/diagram.php
Tooltips have been added to the buttons modes.
> Group3 2021 w16 #10061
