HGustavs/LenaSYS

DuggaSys/diagram.js
Fixes #7910
A fix for the error described in issue #7910 where drawing a line from UML class to UML class after an attempt to draw a line from UML class to line or UML class to other symbol different from UML class (which does not draw a line) has been done.
=> Fix for problem with draw line in diagram

DuggaSys/diagram.js
Before changes in global appearance menu only were applied if there were symbols drawn. This is now fixed to always apply even when nothing is drawn to the canvas.
Test to change global appearance for every property without having any objects drawn on the canvas. Then draw a common symbol that has all the properties in the global appearance (entity, attribute, relation). 
Link: http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%238067/DuggaSys/diagram.php
=> Fixes #8067 - Global appearance now affects when no symbols drawn

DuggaSys/fileed.js, DuggaSys/fileed.php
Solved two issues in one PR.
1. ISSUE: https://github.com/HGustavs/LenaSYS/issues/8110
When filtering files using global, local etc, no console error is created.
2. ISSUE: Hovering over the search bar causes errors. For example:
Uncaught ReferenceError: hoverSearch is not defined...
This has now been solved and a little example div is shown:
=> Fixed console errors that occur when filtering files and hovering the search bar

DuggaSys/fileed.php, Shared/icons/dummy_icon.svg
There is now a new icon for add "dummy empty files" fab button in fileed.
=> New dummy icon for "dummy empty files", fixes issue #7856

DuggaSys/diagram.js
Test if it is possible to change appearance for all types of objects without any errors. UML should resize back to minimum required height when appearance form is submitted. 
The problem before was that a function was executed on an object that the function was not intended for, which would break the object.
Link: http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%238314/DuggaSys/diagram.php
=> Fixes #8314 - Proper check to prevent action on wrong objects

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagram_IOHandler.js
It is now possible to navigate the dropdown menu and press enter instead of clicking on dropdown items. [Issue#8248](https://github.com/HGustavs/LenaSYS/issues/8248)
=> Fixes issue#8248, ability to use enter instead of click in dropdown menu

DuggaSys/templates/3d-dugga.js, DuggaSys/templates/XMLAPI_report1_file_receive.js, DuggaSys/templates/bit-dugga.js, DuggaSys/templates/boxmodell.js, DuggaSys/templates/color-dugga.js, DuggaSys/templates/curve-dugga.js, DuggaSys/templates/dugga1.js, DuggaSys/templates/dugga2.js, DuggaSys/templates/dugga3.js, DuggaSys/templates/dugga4.js, DuggaSys/templates/dugga5.js, DuggaSys/templates/feedback_dugga.js, DuggaSys/templates/generic_dugga_file_receive.js, DuggaSys/templates/group-assignment.js, DuggaSys/templates/html_css_dugga.js, DuggaSys/templates/html_css_dugga_light.js, DuggaSys/templates/shapes-dugga.js
Deleted the row $("#duggaStats").draggable({ handle:'.loginBoxheader'}); from all dugga stats. So it is not possible to drag or move the box anymore. According to @HGustavs, the possibility of iterating with draggable would be completely removed.
=> Deleted the draggable interaction on dugga stats. #8206

DuggaSys/contributionservice.php, DuggaSys/diagramservice.php, DuggaSys/highscoreservice.php
Result from using the service: 
How to test:
Run services mentioned in the pull request:
then look up the result in table:
co authored with @a18jakme
=> Added basic service logging for diagramservice and highscoreservice.php - G1-2020-W17-ISSUE#8213

Shared/css/style.css, Shared/css/template6.css, Shared/css/template7.css, Shared/css/template9.css
The templates that had double scrollbars on some boxes have now been fixed.
Template 6:
Template 7:
Template 8:
Template 9:
=> Double scrollbars solved

DuggaSys/filereceive.php, Shared/basic.php
When adding course local, version local, and global files logging is now in place.
The result from using either of these will show up like this in the sqlite db:
How to test:
co authored with @a18jakme
=> Added logging when adding new files in fileed - G1-2020-W17-#8264

DuggaSys/diagram_objects.js
A recent fix changed the linecap to square with the intention of connecting er entities to relations in a better looking way. This broke the derived lines (dashed line) making it impossible to see it was a derived line when the line thickness is over the smallest size. This is now fixed by changing the linecap for derived lines to "butt" which is the standard linecap, and still keeping the previously chosen linecap for other types of lines.
Test to draw derived lines and change the global line thickness to see so the dashes line is always visible.
Link: http://group4.webug.his.se:20001/G4-2020-W17-ISSUE%238313/DuggaSys/diagram.php
=> Fixes #8313 - Change derived linecap to prevent covering dashes

Shared/css/style.css
Solves #8323. 
Set z-index for #submitButtonTable to 500, meaning the cookie message (z-index 1000) will be displayed on top of it. This should not break anything else but please look through the different duggas during testing.
=> G2 2020 w17 #8323 cookie message can now be closed in Random CSS Dugga

DuggaSys/resulted.js
In this pull request, it is easier to see which attributes belongs to which ssn. Before, only the header (Personnummer, namn) had been separated from each other correctly. With @a17pioja. See example below:
Before:
After:
=> Changed csv-delimiter to "," instead of ";"

DuggaSys/templates/html_css_dugga.html
Change the max-width from 400px to 350px. Changed in random css dugga. Because it was not given enough space for "duggaInfoBox". To test you must use mobile mode from inspect.
=> Change the max-width from 400px to 350px. #7276

DuggaSys/codeviewer.js
Minimalized JQuery within the function "editImpWords" and replaced it with vanilla JavaScript where appropriate.
Test by first adding an important word to the word list and the saving it. It should work precisely as it did before the changes. Same goes for removing a word from the important word list. Both of these functions should work with no problems occuring.
=> Updated editImpWords to better fit with the code standard.

Shared/css/style.css
Changed the CSS to make all selects in AccessED fill the cell. Added padding to span tags only in the table to try to avoid the optical illusion.
This issue also solves issue #8317.
=> #8316 Changed the CSS to change the width of all selects in AccessED.

DuggaSys/diagram.js
All functions executed when enter was pressed from anywhere, without focus on the correct dropdown item. This fixes this so the correct onclick function executes when focus is on a dropdown item. 
-Test to tab through the dropdown items and execute the functionality by enter on the focused one.
=> Fixes #8344 - Tab enter now works only when focusing on defined classes

DuggaSys/diagram.js
According to [Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arity) the arity function is no longer compatible with most browsers. The arity function has therefore been changed to length. 
This will be hard to test since the functionality should be unchanged. Test to make sure creating an entity still works as intended. 
Link to test: http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%238257/DuggaSys/diagram.php
=> fix issue#8257 Changed arity to length 

DuggaSys/diagram.js
The appearance menu was always closed before when the user clicked outside the appearance menu. It could be mouseup inside of the appearance menu while mouseup happened outside of the appearance menu. This resulted in it getting closed when the user didn't want it closed. For example this could happen when highlighting text in an input and accidentally moving the mouse outside of the appearance menu releasing it there.
This pull request fixes the problem. 
- Test to do mousedown and mouseup outside the appearance menu. This should close it.
- Test to do mousedown over a select or an input and then do not release the mouse button until you are outside the appearance menu. This should not close it.
- Test to do mousedown outside of the appearance menu and do mouseup inside the appearance …
=> Fixes #8388 - Appearance menu closes on mousedown inside then mouseup outside

DuggaSys/codeviewer.js
**Minimalized JQuery within displayEditExample**
Replaced JQuery functionality within displayEditExample with equivalent functionaity using native JavaScript. Also fixed indentation of the function in order to fit better with the code-standard.
Test by clicking on "EditExample" (the big cogwheel) on codeviewer.php and checking if the following functions still work as indended:
- Change of Section Title
- Change of Title
- Change of Before-file
- Change of After-file
- Change of Play-Link
=> Updated "displayEditExample" to better fit with the code standard

DuggaSys/codeviewer.js
Reduced jQuery functionality within highlightKeyword. 
Test by navigating to codeviewer.php and either moving the mouse cursor over one of the default added keywords or by clicking the "EditExample" button (the big cogwheel in the top section) and adding an important word and doing the same.
=> Reduced jQuery within highlightKeyword

DuggaSys/courseedservice.php, DuggaSys/sectionedservice.php, Shared/basic.php
When editing a existing course version or creating a new logging of these events will take place.
The result from doing the above will result in: 
--- 
How to test: 
=> Added logging when creating or editing course version - G1-2020-W18-ISSUE#8364

DuggaSys/diagram.js
Distribute and help dropdowns in the diagram still overlapped after the fix, this should make the deselect work properly for them too. Original issue #8099.
=> Fix so that active labels are also cleared, #8340

DuggaSys/diagram_objects.js
When user selects the comment box of a text object the object gets a dashed border. This way the user knows if the text is a comment or not without having to check.
How it should look like:
Link to test: http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%238265/DuggaSys/diagram.php
=> fix issue#8265 Make it easier to see if a text are a comment

DuggaSys/diagram.js
This adds auto focus functionality to the appearance menu when it opens. This makes it easy to start typing or selecting directly with the keyboard instead of having to manually select the input with the mouse first. It is also easy to tab through the inputs in the form as the first option in the loaded form will always be auto focused.
The name input will be automatically selected for entities, relations, attributes, and UML classes (where they exist).
The type attribute will be automatically selected for all types of lines since that is the first and most important option for lines.
The textarea will be selected for text objects.
The fill color option will be selected for free drawn objects.
Test so all of the conditions above works as intended.
Link: …
=> FIxes #8427 - Auto focus in appearance menu

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagram_objects.js
This will solve so objects turn red if they are located in the middle on two separate pages, in this issue you can also change size on the page. This should work with any paper configuration and any object (not line or freedraw)
=> G4 2020 w18 issue#7935

DuggaSys/diagram.js
Fixes #6491 
Before lines would jump to the wrong side of an entity when resized below minimum(se picture in actual issue). This should not be the case with this fix.
=> G4 2020 w18 issue#6491

DuggaSys/fileed.js, DuggaSys/fileedservice.php
Fixed so that trash button only shows up for people with write access instead of everyone that had access to the page could see it even student teachers.
To this on the server a user with super user is needed to even access the fileed.php and then the user needs to have write access.
Currently no user has both so updating the database for teacher3 would be the best solution because teacher3 has write access on most courses but not super user and give teacher3 super user.
Then just use brom who lacks write access to not see the trash buttons and then teacher3 who does too see the trash buttons.
=> Only people with write access can see trash button

DuggaSys/diagram.js, DuggaSys/diagram_objects.js
Solves #7543
When exporting diagram to SVG the UML lines should now be displayed, and in hopefully all cases be displayed exactly how they appear in the diagram.
When testing, please be sure to clear localstorage first!
=> Exporting as SVG now handles UMl lines

Shared/navheader.php
There is no longer a typeerror when you go to a course while being logged in as "teacher1". This is thanks to an if-statement that checks login and if the user has writeacces it enables the dropdown.
=> Removed typeerror when accessing course as teacher1

DuggaSys/codeviewer.js
Updated the function "displayEditContent" to better fit the code standard by replacing JQuery functions with native JavaScript equivalent where appropriate. Also fixed the indentation of the function to fit the code standard by moving the opening bracket one line further down.
Test by going to codeviewer.php and pressing any "Edit box settings"-button that exists (The small cogwheels on the different panels). Check if all functionality of these boxes works as intended (e.g. changing of file, kind of document, title). I recommend to check multiple panels within multiple templates in order to ensure that full functionality still exists after these changes.
=> G1 2020 w18 issue#8408

Shared/css/style.css
The header still shrinks a little when not in "mini mode", this is to allow "mini mode" to be less wide than "normal mode". 
I can alter the css min-width to make the tables of "mini mode" and "normal mode" the same width (meaning it will never shrink) if that is preferable.
=> Added min-width to resultTable th element to minimise the shrinking

DuggaSys/downloadzip.php, Shared/basic.php
When downloading all contents from a course verse:
The result in the sqlite db will be:
---
How to test: 
=> Added logging when downloading all contents from course vers - G1-2020-W18-ISSUE#8433

DuggaSys/codeviewer.js
Updated function "editImpRows" to better fit the code standard. This was made by replacing most JQuery functionality with native JavaScript where appropriate.
Test by editing a panel on the codeviewer-interface (any template works). Try specifying a some important rows (e.g rows 2-4) and press "Save". The page should update and highlight the important rows. Now try to unmark the rows as important (done by selecting said important rows and pressing on the "-" button in the editor) to check if it's still possible to remove important rows.
=> G1 2020 w18 issue#8453

DuggaSys/codeviewer.php, DuggaSys/courseedservice.php, DuggaSys/filereceive.php, DuggaSys/sectionedservice.php, Shared/loginlogout.php, Shared/resetpw.php
All logging using logUserEvent now instead use userid. These change can be seen in the userLogEntries table.
Previously:
After:
These changes encompasses:
* Editing/creating courses in courseed:
* Adding items in sectioned 
* Adding files in fileed 
* Login/Logout/LoginFail
* Reseting passowrd
* Viewing examples in codeviewer 
---
How to test: 
=> Changed all current logUserEvent to log userid instead of username - G1-2020-W18-ISSUE#8337

DuggaSys/diagram.js
Before fix it was impossible to select attributes, entities, relations, classes and lines while Create Line tool was selected. Now you should be able to select all of the options above while the Create Line tool is active. 
Before fix you could create a recursive line to classes by clicking on them. Now you have to drag the mouse on the class to create a recursive line instead.
Link to test: http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%235679/DuggaSys/diagram.php
First test:
Connect Attributes, relations and entities with lines and while the line tool is still active try to select all of them, including the lines themselves. 
Before:
After: 
Second test:
In UML-mode create two classes and connect them with a line. While the line tool is still active try to select the classes and the …
=> fix issue#5679 Selection of entities while line tool is chosen

DuggaSys/diagram.js, DuggaSys/diagram_objects.js
Fixes #6977
A solution which makes it possible for ER-lines to be copied and pasted, while keeping correct connections to it's copied objects.
Note: UML-lines ar more difficult to deal with due to breakpoints, and currently UML-classes can't even be copied. So this should be made to a separate issue.
=> Solution for copying ER-lines when copy-pasting. issue#6977

Shared/css/style.css
=> Added underline and hover effect on back to login - G1-2020-W18-ISSUE#7395

DuggaSys/resulted.js, Shared/css/style.css, Shared/icons/not_announced_icon.svg
In this pull request, we have changed the background color of the empty slots so that each empty spot has the same color. Then, we added the text "N/A", indicating that there is no data available in the spot, or that the same user is not assigned to the dugga concerned. 
This fixes #8406 
With @a17pioja.
=> Filled empty slots in the table of resultEd - Issue #8406

Shared/css/dugga.css, Shared/dugga.js
Changed so when you click the link for Zip/Rar files you download it immediately instead of opening a preview with a download link.
Changed the CSS to make the link look more in place.
=> #8341 Removed preview window for Zip/Rar files.

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagram_objects.js, Shared/css/style.css
This is a big rework for issue #7677 so it should be tested thoroughly.
Before, it was difficult changing appearance of different types of objects simultaneously. It only worked decently when the selected objects all had the exact same properties that should be affected. It was impossible to change the names of objects to different things at the same time, they would all get the same name. The same goes for textareas, all would get the exact same text. I imagine these as being properties that should be different. The appearance form would before only show the inputs that should be shown for the previously selected object and ignore all the other selected objects needs. This was not a good way to handle it.
In this rework all types that have the exact same properties in common are grouped …
=> Fixes #7677 - Changing appearance of different types of objects simultaneously

DuggaSys/filereceive.php
Fixed the issue where course local files where put inside of versionIndependence folder instead of their course folder where they are supposed to go. versionIndependence is ment to be for version independent files which are put  inside of /course/courseid/version.
=> Fixed so that course local files go where they are supposed to go

DuggaSys/codeviewer.js
Removed unnecessary JQuery functionality and replaced it with native JavaScript equivalent code. Also fixed formatting of the functions to also fit the code standard better.
Test by clicking on the buttons displayed in the image below
Pressing both of them should redirect to the previous and next issue. Verify that this is working. Then, press and hold each of the buttons. A dropdown list should appear named "Backw" when holding the backwards button, and "Forw" for the forward button. Check if the options in the list are highlighted when hovered over and also check if the options redirect to their respectrive examples (can be done by testing only one of the options).
=> G1 2020 w18 issue#8493

DuggaSys/diagram.js, DuggaSys/diagram.php, Shared/css/style.css
Adjusted text to appear inside drop-down menu and added keyboard command for fullscreen. To test, simply open View in menus to confirm text is alligned (see screenshot in issue for reference), and hit Shift+f11 to verify the shortcut is working. 
http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%238481/
=> solves issue#8481

DuggaSys/sectioned.js, errorpages/403.php, errorpages/404.php
When creating a new item of type link in sectioned, all choices corresponding with the choice 
---===######===--- in the dropdown menu will now redirect to error page 403. 
How to test:
Create a link, the default link choice in the dropdown should be: 
Now when clicking the link. 
You should be redirected to 403 error page:
=> Replaced the link corresponding with the ---===######===--- dropdown choice - G1-2020-W18-ISSUE#1796

DuggaSys/fileed.js
In fileed, you should be able to press "ctrl" to make the FAB-button transparent and be able to click through it, this was you can click the buttons in the table behind it.
=> Added functionality to press CTRL to toggle fab button clickable

DuggaSys/codeviewer.js
Updated functions "openTemplateWindow" and "closeTemplateWindow" within codeviewer.js to better fit the code standard by replacing jQuery.
Test by clicking the "Choose Template" icon (next to the play button) to bring up the template window and then by closing it.
=> Updated functions "openTemplateWindow" and "closeTemplateWindow" within codeviewer.js - G1-2020-W18-ISSUE#8554

DuggaSys/diagram.js
This pull request will make it possible to correctly copy and paste path symbols. Before paths were treated like symbols which would create a dummy symbol wasting memory.
- Test to create several paths, select them, copy them and paste them.
- Create other type of objects, select them at the same time as paths and copy and paste everything.
Link: http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%238513/DuggaSys/diagram.php
=> Fixes #8513 - Copy path objects

Shared/css/style.css
Added border-left: 2px solid #dbd0d8; and border-right: 2px solid #dbd0d8; on resultTable td in resulted for consistency.
=> Added left and right border in Resulteds table. #8533

Shared/css/style.css
Added text-align:center styling to the first column in Resulted, Duggaed, Fileed and Accessed.
=> Added text-align:center to the first column. #8529

DuggaSys/diagram_objects.js
Before fix when selecting a comment the black border overlapps with the selection's orange border. The comment border should not be visible when selected. 
Link to test: http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%238585/DuggaSys/diagram.php
Create a textobject and select the comment-box. Now try to hover and select the textobject. If the black border is not visible it is working as intended.  
Before:
After:
=> fix issue#8585 Remove comment-border when selected

DuggaSys/diagram_objects.js
Qucik fix to center textobject vertically
Test to see if it is centered with all fontsizes and fontfamilies
Link to test: http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%238552/DuggaSys/diagram.php
Before:
After:
=> fix issue#8552 Center textobject vertically

DuggaSys/diagram.js, DuggaSys/diagram.php, Shared/css/style.css
Added popup message when entering fullscreen with a message on how to exit. Prepared for future additions, such as how to add/hide toolbar. Enter fullscreen by going View > Fullscreen to test this. The shortcut Shift+F11 is solved with another issue and will not work here.
=> solves issue#8434

DuggaSys/diagram.js
The appearance form can be submitted with enter. This did intentionally not work when a textarea was part of the form before. The reason for this is that it should be possible to use enter in a textarea. It would still be good to be able to submit the form with enter when the active element is not the textarea. This pull request fixes this for issue #8464.
- Test to submit the appearance form with enter when not having a textarea as the active element.
- Test to use enter in all different types of textarea to see so the appearance form does not submit.
- Test to select many different types of objects and open the appearance menu to get the new grouped collapsible structure to see if it also works here.
Link: http://group4.webug.his.se:20001/G4-2020-W18-ISSUE%238464/DuggaSys/diagram.php
=> Fixes #8464 - Submit appearance form with enter when textarea is part of the form

DuggaSys/fileed.js
Changed incorrect variable "writeaccess" to "access" within fileed.js
Test by navigating to fileed.php as a non-logged in user and as a logged in user with access (Toddler/brom). The following results are to be expected:
Non-logged in user: Redirected to courseed.php.
Logged in user with access: Ability to view and use fileed.php.
=> Changed writeaccess to access in fileed-authorizer

DuggaSys/templates/bit-dugga.js, DuggaSys/templates/color-dugga.js, DuggaSys/templates/dugga1.js, DuggaSys/templates/dugga2.js
Changed the width of the hexadecimal input box on color dugga and bit dugga.
- Usually the width is much lower now which make it look more nimble
- Minimum width was set higher though since it looks really stupid when the width is too small
To the this login as `Toddler`, use password `Kong` and go to the webbutveckling course and take a look on the relevant duggor.
=> G2 2020 w18 #8425

DuggaSys/sectioned.js, DuggaSys/sectioned.php
Removed the warning that course names may not include åäö, when clearly they can include them.
=> Removed warning regarding åäö

DuggaSys/codeviewer.js
Updated functions "closeEditContent" within codeviewer.js to better fit the code standard by replacing jQuery.
Test by going to codeviewer.php and navigating to the "Edit Content" window by pressing the small cogwheels and by closing the window, there should be no changes in the example window and the window should simply close. Next test by checking if it is possible to edit the example by going to "Edit File" (the pencil icons on top of the examples) and saving the changes.
=> Updated function "closeEditContent" within codeviewer.js - G1-2020-W18-ISSUE#8601

DuggaSys/codeviewer.js
Test by going to codeviewer.php and clicking the "Edit File" button on any of the content boxes. An iFrame element should appear when clicking on the button. The iFrame element should also close by clicking the cross in the upper right corner. This should work for all boxes within all templates so be sure to test multiple boxes across several templates in order to ensure that the functionality remains.
=> Replaced JQuery with native JavaScript where appropriate and fixed indentation in functions "showIframe" and "hideIframe".

DuggaSys/templates/bit-dugga.js, DuggaSys/templates/color-dugga.js, DuggaSys/templates/dugga1.js, DuggaSys/templates/dugga2.js
The only thing "top" does is disconnect the hexadecimal panel from the accordion. Although it positions the panel in a good way. Now it works like it should, but the panel is placed a bit lower than before. 
This fixes the problems with the accordion in "Färgdugga 1" and "Färgdugga 2" as well.
=> ShowDugga: Removed "top" to fix problem with panel

DuggaSys/templates/dugga1.html, DuggaSys/templates/dugga2.html
By removing the absolute position the buttons behave like they should. Now they automatically move if the upper box is bigger. 
Henrik wrote this comment on the issue: "if the upper box is bigger it should automatically displace buttons unless something is awry". By removing the absolute position the buttons moves if something pushes them down. Like the hexadecimal panel does. 
**Note:** To test this correctly you must go to dugga1.js or dugga2.js and remove "top+" from line 286 (line 227 in dugga2.js). If you don't it will look really weird. This is not a problem because that issue has already been fixed. Check pull request #8609.
=> ShowDugga: Removed "position: absolute" to fix the buttons

DuggaSys/diagram.js
The comma always appeared after the last object, so even when having only one object there was a comma at the end, and typing after the comma would result in nothing changing. Now the comma will never appear after the last object. This affects name input, UML operations textarea, UML attributes textarea, free text textarea.
- Test to select a few objects at the same time making multiple names appear in the name input separated by commas. Make sure no comma appears after the last object name. Test to edit the different names separated by commas.
- Test to select several UML classes and edit the attributes and operations separated by comma followed by new line. Make sure it affects the correct object.
- Test the same as for UML for text objects.
- Test to select many different types of …
=> Fixes #8557 - Comma separation should not be after last object

DuggaSys/analyticService.php
Replaced EventType::ServiceClientStart with EventTypes::ServiceServerStart. No logging in place for ServiceClientStart.
=> Solved browser percent not showing up in analytic - G1-2020-W19-ISSEU#8583

DuggaSys/diagramservice.php, DuggaSys/fileedservice.php
diagramservice reads GitHub activity data. In this situation we cant take out that data which means the log becomes null.
Test this by upload a file in fileed.php:
Navigate to the analytic.php/Service speed.
=> fileedservice AVG duration is now shown. Remove diagramservice log.

DuggaSys/analyticService.php
Now possible to see diagram which showcases usage in different places, see screenshots below!
=> Now possible to see logs in "Service Usage" G1-2020-W19-ISSUE#8573

Shared/navheader.php
Removed the extra course version dropdown that did not work and only showed for people with write access. The error that this was supposed fix in issue #7802 no longer remains but should be tested by the reviewer just to make sure.
=> The extra course version dropdown is now removed

DuggaSys/diagram.js
Fixes #8503
Now recursive UML-lines are also handled correctly when copy-pasting them.
=> Fixes recursive UML-lines when copy and pasting

DuggaSys/diagram.js
Fixes #8615
Figuretype was not changed back after free-draw function was used. Now UML-lines should not be affected by this.
Test by drawing a free-draw object, then drawing a UML-line. Before the line would create points but be invisible. Now it should display correctly.
=> Fix for lines turning invisible after free-draw

DuggaSys/diagram.js
A useless point was created every time a line was copied before. This is now fixed. The centerPoint of all lines were removed since it is redundant and causing problems with the copySymbol function. A special case was also developed for ER lines connecting to attributes. ER lines are connecting to the attribute's centerPoint and is therefore reusing the centerPoint of the attribute instead of having a unique point reference for its bottomRight key. A special case was needed to prevent a useless point from being created when an er line is copied together with a connected attribute. If a ER line is copied on its own or together with a relation or entity this point should still be created.
- Test to create lines of all types. This includes UML lines (do not test recursive UML line as this …
=> Fixes #8591- No longer creating useless points when copying lines

DuggaSys/analytic.js, DuggaSys/analyticService.php
When a service is called with a serviceStart but no serviceEnd its shown in service crashes on analytic.php. 
Show a Date it's still a problem, this need to be solved in another issue. 
How to test:
comment out a ServiceServerEnd event.
=> Service crashes data now shown

DuggaSys/analytic.js
Added file selection option through a dropdown menu. Did not managed to get date picking to work correctly like the issue request. Will create seperate issue for that specifically.
Additonally removal function of  previously requested tables will be added in a separate issue. In the picture below you can see an example of this issue. The table for the previous request remains. 
How to test:
Edit or create files in fileed, the navigate to analytic.php where the logging result will be presented under the file information tab.
=> Added file selection option to file information tab in analytic - G1-2020-W19-ISSUE#8673

DuggaSys/templates/bit-dugga.js, DuggaSys/templates/color-dugga.js, DuggaSys/templates/dugga1.js, DuggaSys/templates/dugga2.js
Solves #8572.
User can now close the hexadecimal input box by:
1. clicking the "parent" element (the div/button for opening the hexadecimal input box that was used to open the input box)
2. clicking somewhere on the screen that is not one of the "parent" elements
3. selecting a value in the hexadecimal input box (this was default behaviour before my changes)
If the user opens the hexadecimal input box with one div/button and clicks another, the input box will be moved accordingly (this was also default behaviour before my changes).
These changes apply to the Biträkningsduggas and Färgduggas.
I would argue these changes make the duggas feel much more responsive.
=> G2 2020 w19 #8572

install/install.php
The installer now show the right permission settings depending on o/s of system running the installer. I checked my permissions on Windows and couldnt find any special. So for Windows-systems the permission text are now disabled.
=> Fixed permission text for Windows/Linux/OSX #8000

Shared/css/style.css, Shared/dugga.js, Shared/logoutbox.php
Fix so that you can now close the logout popup window by pressing 'x' without having to press 'cancel' first.
Before this fix, you couldn't press the red 'X' button to close the window the FIRST time you opened the log out box. You had to press the 'cancel' button first, then open the logout box AGAIN and press 'X'. The second time you press 'X', it works. 
I've fixed it so that you can press 'X' the first time you open the logout box and it closes like it's supposed to do.
Press here:
This box:
=> Fixing the X button | Fix for issue #8626

DuggaSys/diagram.js
Should now be possible to freedraw on mobile. It works in the same way as for non-mobiles. Click to add points to the figure and click the first point to finish the figure.
=> Implemented freedraw for mobile, issue#8674

DuggaSys/diagram.js
Before it worked fine to manually select each object by CTRL clicking on them one by one. It also worked fine to use the keyboard shortcut CTRL+A to select all objects when no objects are already selected. However, when some objects were already manually selected and the CTRL+A shortcut was used to select all objects, all objects will be added to selected_objects on top of the ones that were already manually selected. This caused problems for multiple things. This is now fixed.
Copying and pasting after redo and undo was a problem before. It was not be possible to copy the selected object after undoing directly and all the objects that were selected when copying would not be selected again after paste and undo. It would be good to fix this since it would make it easier to just copy and …
=> Fixes #8508 - Duplicate objects in selected_objects array

Shared/icons/HomeShadow.svg, Shared/icons/UpShadow.svg, Shared/navheader.php
Fixed so there is now a box-shadow effect on the 'home' and 'back' icons (see image for reference)
=> Fixing shadows over 'home' and 'back' icons | Fix for issue #8703

DuggaSys/accessed.js, Shared/css/style.css, Shared/dugga.js, Shared/icons/desc_black.svg
Solves #7769.
Most of this was made by @a18petha and @g18marma. 
The rest are modifications to their code (for the most part) to make it compatible with our changes to accessed.js (the bulk of their code was written almost a month ago).
The dropdowns in the Access Editor no longer uses select-elements (using these can result in bad performance since they are operator system specific).
For now all the dropdowns except the group dropdowns are opened by hovering them. This should/will most likely be changed. There are also some styling "issues", like some dropdowns not being wide enough (in my opinion). That should be a separate issue. This issue is only concerned with updating dropdowns to a more efficient solution and to get those working properly.
=> G2 2020 w19 #7769 updated accessed dropdowns to a div-based solution

DuggaSys/templates/dugga1.html, DuggaSys/templates/dugga2.html
The first idea was to adjust the code for the top positioning in dugga1.js and dugga2.js, but with javascript I couldn't get the top position to always be -35px. By just adding "top:-35px" to the div containing the hexadecimal values the problem was solved. 
Now it looks like it should and everything feels more connected. 
This fixes the issues in both the "biträkningsduggor" and the "färgduggor".
=> ShowDugga: Added inline styling to position the panel

DuggaSys/resulted.js, DuggaSys/resulted.php
- Change name on Add button to Add phrase. To clarify what it adds.
- Added a clearbutton.
- Added a function that set the text to "" in the textarea with id="responseArea".
=> Change name to Add phrase and added a clearbutton. #6919

DuggaSys/duggaed.js
This solves issue #8710. The `renderCell`-function has been trimmed and is now easier to follow and works in a more consistent way.
I have also changed the "Start date", "Deadline" and "Result dates" to show "N/A" inside its cells instead of null and also lessened the precision on the timestamps to exclude seconds.
When testing:
- Compare it to another branch.
- It should behave exactly the same except the changes to the three columns stated above.
- Using **Webbutveckling - datorgrafik** while testing is recommended.
- Don't forget to test the **Variant Editor** too (Clink on the pen icon)
The indentation of the `setup`-function was corrected as well...
=> G2 2020 w19 #8710

DuggaSys/codeviewer.js
Updated function "closeEditExample" within codeviewer.js to better fit the code standard by replacing jQuery. 
Test by going to codeviewer.php and navigating to the "Edit Example" window by pressing the big cogwheel in the top menu ("Example Settings") and by closing the window. There should be no changes in the example window and the window should simply close.
=> Updated function "closeEditExample" within codeviewer.js - G1-2020-W19-ISSUE#8738

DuggaSys/sectioned.php, Shared/calendar.php
Added ability to get all deadlines in the form of iCal, this can be used to in your phone to see deadlines. 
The example screenshot shows how it looks on mobile:  
Example on how it looks on a computer:
=> iCAL Calendar for mobile and desktop G1 2020 w19 #7892

DuggaSys/analytic.js
Added function that delete tables in analytic.js and used the function to remove tables that remained from previous request in the file information tab. 
Before:
Only the selected table is suppose to be displayed.
After: 
When selecting a new file the result is:
=> Added function to delete tables in analytic.js - G1-2020-W19-ISSUE#8732

DuggaSys/diagram.js
Before a dummy point was created when drawing a line from a freedraw-object to a ER-object. This was due to freedraw-objects not being handled in the "okToMakeLine" function.
This also fixed a error only visible in the console when drawing a line to a freedraw-object.
Test by drawing lines from and to free-drawobjects. No errors should occur and no dummy-points should be created.
=> Solves issue #8765 - Dummy point created when line is drawn from path-object

DuggaSys/diagram.js
The visibility and size of virtual paper is now stored in localStorage. If the user displays virtual paper it should still be visible when the page is updated. The same thing applies for paper size. 
**Test this**: Select Display Virtual Paper and change paper size to something else than the default A4. Update the page and check if the paper is still visible and has the same size you selected. 
Another way to check if the values have been stored in localStorage is to enter the browsers inspect mode: Inspect -> Application -> Local Storage. Make sure the virtualPaper and paperSize are stored.
Link to test: http://group4.webug.his.se:20001/G4-2020-W19-ISSUE%238488/DuggaSys/diagram.php
=> fix issue#8488 localStorage for virtual paper display and virtual paper size

DuggaSys/diagram.js
Before, it was possible to remove separators. This would cause errors as an attempt to access an index in an array based on separator was made and when the separator no longer exist, this will cause problems. This solution makes it impossible to remove a separator to help the user. Removing a separator can easily happen and a mistake should not matter. Now the user can be more careless when working with multiple objects at the same time in the appearance menu. This affects text inputs and textareas where the user can freely enter information.
- Create many types of objects; entities, relations, attributes, UML classes and free text. And several of each. Select all of the objects at the same time and open the apperance menu. In the name input there should be many names separated by ~. Try …
=> Fixes #8681- Separation should take the possibility of removing a separator into account

DuggaSys/diagram.js
The "Please draw more lines!" popup should not appear when the user rightclicks in Draw Text mode. 
Test this: Enter Draw Text mode and rightclick on the canvas. If the popup does not appear the issue is fixed. 
Link to test: http://group4.webug.his.se:20001/G4-2020-W19-ISSUE%238629/DuggaSys/diagram.php
Before: 
After:
=> fix issue#8629 Popup only appears in Draw Free mode

DuggaSys/codeviewer.js
The functions are not currently used, if the need for something similar arrives the functions would have to look very different anyway. This is due to new additions and the fact that the old functions do not follow code standard. All currently active dropdowns should still work. All manus should work as well.
=> G1-2020-W19-ISSUE#8593

DuggaSys/templates/dugga4.html, DuggaSys/templates/dugga4.js, Shared/css/style.css
Solves #8761.
Transformationsduggor should now be more useable on small screens (<1050px wide). Before this change the content would overflow horizontally. When the screen is small enough the content will now be displayed in a column fashion and the horizontal scroll should be no more.
I also replaced the instructions window with an accordion (the one used in for example bitduggas and färgduggas) for consistency. The transformationsdugga uses an accordion for feedback anyway. This is always displayed on the top of the page which made positioning everything else easier.
**Note:** during development this was tested in both Chrome and Firefox Dev Tools. They did not behave the same way when resizing (for example the canvas would become very small when resizing somewhere below 1000px width in …
=> G2 2020 w19 #8761 Transformationsduggas should now be more useable on smaller screens

Shared/css/style.css
I fixed the styling of the MOTD banner button inside a course so that it matches with the one on the home page.
This is what the button on the home page looks like:
<a href="https://gyazo.com/518fc5b4c5d91ea00bb364a798fae51d"><img src="https://i.gyazo.com/518fc5b4c5d91ea00bb364a798fae51d.gif" alt="Image from Gyazo" width="156"/></a>
This is what the old styling looked like that doesn't match the home page:
<a href="https://gyazo.com/0ff7fd151bcea54641c4c93acf914d83"><img src="https://i.gyazo.com/0ff7fd151bcea54641c4c93acf914d83.gif" alt="Image from Gyazo" width="92"/></a>
This is what the new styling looks like to match the home page:
<a href="https://gyazo.com/987cb93d3e012588d78258a6ead12409"><img src="https://i.gyazo.com/987cb93d3e012588d78258a6ead12409.gif" alt="Image from Gyazo" …
=> Changed styling on 'x' button in MOTD banner | Fix for issue #8781

DuggaSys/sectioned.js
It is no longer possible to create a new course version with a version ID that already exists **for the selected course**. 
You can, however, create a version with an ID that exists in **another** course, but not in the same course. I.e. you can have the course version with ID "1337" in both IT118G and DV12G but you can't have **two** course versions with the ID "1337" in  IT118G.
In "**Webbprogrammering DV12G**" there is a course version by the id "1337". So when we try to add a new course version with the same ID, we get a warning and we are unable to create it.
-----
In "**Webbutveckling datorgrafik IT118G**" we have a course version with the ID "1337", which also exists in "Webbprogrammering DV12G". This is allowed because they are two different courses with different course ID's.
=> You can no longer create a new course version with an existing version ID | Fix for issue #8771

DuggaSys/sectioned.js
Now the correct versionname is shown in edit course version if there are several versions with the same version ID.
=> Saved the correct version name when there are several with the same vers

DuggaSys/analytic.js
Removed client start and end to show service event date.
[![Image from Gyazo](https://i.gyazo.com/d6042884ffd23cf366591db25a0884e1.png)](https://gyazo.com/d6042884ffd23cf366591db25a0884e1)
When testing remove or comment out this line in service to make the service crash. [![Image from Gyazo](https://i.gyazo.com/492406dfb152284ec5b5f8c32a467d59.png)](https://gyazo.com/492406dfb152284ec5b5f8c32a467d59)
=> Solution for branch G1-2020-W19-ISSUE#8667

DuggaSys/diagram.js
Before fix when navigating in developer mode the central crosshair gets positioned behind objects that are drawn onto the canvas. After fix the crosshair should always be in front of all the other objects which means that it will always be visible. 
**Test this:** Enter developer mode and draw a couple of different objects like enteties, attributes and classes. Drag the crosshair over the objects by rightclicking and dragging the mouse. If the crosshair is visible when positioned on the object the issue is fixed. 
**Link to test:** http://group4.webug.his.se:20001/G4-2020-W19-ISSUE%238787/DuggaSys/diagram.php
**Before:** 
**After:**
=> fix issue#8787 crosshair in developer mode moved to front

DuggaSys/resulted.js, Shared/css/style.css
Now "N/A" can be seen in both "Only pending" and "Late submissions". 
Fixed sizing issue with the left navbar when scrolling right in the table. 
Also fixed the same issue in "Mini mode". 
The only thing that's missing is the implementation of "Unassigned" on moments in "Only pending" and "Late submissions".
=> Fixed styling issues in resulted 

DuggaSys/analytic.php
Ported over filetime logic from codeviewer to analtytics to make development go faster and stop webbrowesers from caching css and javascript.
=> G1 2020 w19 #8824

DuggaSys/analytic.js, DuggaSys/analytic.php, DuggaSys/analyticService.php
Added page information to analytic for Showdugga and codeviewer page with information about total page hits and additional information how those hits are divided among different courses. This can be seen in the picture below. 
More pages are suppose to be track but currently we lack the logging for all of them. Additionally the issue linked with this pull request request additional features besides page hit but without any clear explanation on what those features should be. 
THIS requires us creating additional issues with what pages should be track and what features should be added to page information.
=> Added page information to analytic - G1-2020-W19-ISSUE#2178

DuggaSys/accessed.js, Shared/css/style.css
Solves #8830.
Dropdowns in Access Editor now open/close on click instead of hover according to issue suggestions. 
There are still some styling issues with the dropdowns, a separate issue should/will be opened for this. This pull request only fixes behavioural issues for the dropdowns.
=> G2 2020 w19 #8830 Accessed dropdowns now open/close on click instead of hover

DuggaSys/resulted.js, DuggaSys/resulted.php, Shared/css/style.css
The last export date is stored in localStorage and the date in the localStorage is then shown under the LadExport button as shown below. Also added so that the last export date is shown in the footer of the popup.
The way to test this is to click on the "LadExport" button and then close the popup. Then you can see the date under the button and in the localStorage.
=> #5617 Added a way to see the date and time an export last was executed.

DuggaSys/resultedservice.php
Fixes #7755, it still requires two clicks, but should only count as graded once.
=> Resetting grade no longer counts as a "time graded"

DuggaSys/diagram.js
Dragging a loose line end into a object will now connect them if connection between objects is valid.
Line should not connect if connection is invalid(example: two lines between same ER-attributes).
Note for tester:
Loose line is easiest created by copy-pasting a ER-line. You can then drag one of the lines endpoints inside a object, and it should connect if connection is valid.
Also note that it only works for ER-lines for now. This is due to copying and pasting UML-lines not working correctly as of now, and therefore these lines are not handled yet.
=> Solves #8553 - Solution for connecting loose ER-lines to objects

DuggaSys/diagram.js
This does not create new functionality, but it makes the code for the appearance menu much easier to follow and reuse since the code is divided into smaller reusable functions. This will come in handy for fixing future appearance menu issues. Comments were added to all appearance menu functions as well.
- Test so all appearance menu functions work like before. Select many types of objects and several of each object at the same time and change properties to make sure functionality was not affected.
Link: http://group4.webug.his.se:20001/G4-2020-W19-ISSUE%238852/DuggaSys/diagram.php
=> Fixes #8852 - Appearance menu code: Separate long functions into separate functions

DuggaSys/diagram.js
Solves issue #8856
Using a flash message on screen the user now gets feedback on why line could not be created.
Tester:
Try to draw all different types of incorrect lines to see if appropriate error message shows up. Also try drawing correct lines to make sure we don't show en error by mistake.
http://group4.webug.his.se:20001/G4-2020-W19-ISSUE%238856/DuggaSys/diagram.php
=> User feedback when incorrect line is attempted

DuggaSys/analytic.js
Added default colors to piecharts to make the visibility better if a weird random color is assigned. A set of colors has been defined, if we exceed this number, we will fallback to the old random color system.
=> Added fixed colors to piecharts - G1 2020 w19 issue#8868

DuggaSys/diagram.js, DuggaSys/diagram.php
This makes the line direction select for UML follow changing names in the name input.
This gif shows what you should test:
Link: http://group4.webug.his.se:20001/G4-2020-W19-ISSUE%238510/DuggaSys/diagram.php
=> Fixes #8510 - Object names in line direction select change according to name input

DuggaSys/analytic.php
When entering analytic.php the season cookies should now be refreshed.
=> Added seassion cookie to analytic.php - G1-2020-W20-ISSUE#8881

DuggaSys/diagram.js
Now error messages works when connecting loose lines as well.
Also fixed so error message now shows up when trying to connect multiple lines between two ER-attributes which realized i missed before.
Tester:
http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%238932/DuggaSys/diagram.php
Loose lines is easiest created by copy-pasting a ER-line, then drag endpoints to different combinations of objects to see if on-screen error handling works properly.
=> Further work on error message handling to user

DuggaSys/diagram.js, DuggaSys/diagram_objects.js
The longestStr variable should update correctly now, taking all string into account and not just the name of the UML class. This should prevent the class from shrinking below the length of the longest string
=> Added correct updating of longestStr to UML resizing ISSUE#8594

DuggaSys/codeviewer.php, DuggaSys/showDugga.php, Shared/basic.php
Added userid to page load logging for showDugga and codeviewer pages. This required the attribute userid to be added to table creation along with modifications to the logging function to also include the userid when inserting log data into the db. 
Before:
After:
How to test:
inspect the tables previously mention, these will lack userid. Then remove the log dir located in htcdos, now navigate to a codeviewer or a dugga. Reopen the db file. The tables will now include the userid.
=> Added userid to showDugga and codeviewer page load logging - G1-2020-W20-ISSUE#8882

DuggaSys/duggaed.js
Solves #8908.
Added .toLowerCase() to the values being compared, which means all strings are handled as all lowercase. The Dugga Editor table should now sort properly regardless of character casing.
=> Sorting in Dugga Editor should now sort uppercase and lowercase characters properly

DuggaSys/diagram.js
removed the resize function from submitAppearance form to prevent custom sized UML classes from resizing when the appearance or content of it is changed. Closes#8556
=> Resizing function in submitAppearanceFrom removed ISSUE#8556

Shared/css/style.css
Updating styling for 'x' button on MOTD banner inside a course again.
It now looks like this:
<a href="https://gyazo.com/e437cb47037297867fbdc89e2ab9cb93"><img src="https://i.gyazo.com/e437cb47037297867fbdc89e2ab9cb93.gif" alt="Image from Gyazo" width="88"/></a>
Which matches the 'home' page MOTD button that looks like this:
<a href="https://gyazo.com/ef9eafeb781d04685067517ce06706f8"><img src="https://i.gyazo.com/ef9eafeb781d04685067517ce06706f8.gif" alt="Image from Gyazo" width="128"/></a>
=> Updating styling for 'x' button on MOTD banner | Fix for issue #8781

DuggaSys/resulted.js, DuggaSys/resulted.php, Shared/css/style.css
Element describing the various icons and colours has been added. The element can be shown/hidden by interacting with the "?" button. The purpose of this implementation is optimization for mobile devices as well as full size monitors. Names has been to an extend modified.
To access: Log in as super user -> go to E.g. datorgrafik course -> click the paper & pen icon.
with @a17pioja
=> G2 2020 w20 #8534

DuggaSys/diagram_objects.js
The primary and partial key line position for attributes should now be correctly placed when changing text size or when zooming the canvas. 
**Test this:** Create an attribute and enter its appearance menu. Select Primary key as Attribute type. Switch between all the different text sizes and make sure the line under the text is never positioned on the text. Also try to zoom in and out and make sure the line doesn't change position. Try the same with  Partial key as Attribute Type. 
**Link to test:**  http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%238971/DuggaSys/diagram.php
Before:
After:
=> fix issue#8971 Primary and Partial key lines consistent with text size and zoom

DuggaSys/analyticService.php, Shared/loginlogout.php
Having logging for 10 fails seems a bit to much, reduced to 3 fails to make it easier to spot bruteforce.
=> Max login fails changed from 10 to 3 #9006

DuggaSys/diagram_objects.js
Fixes #9048
Recursive UML-lines should now also be possible to hover.
For tester:
http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239048/DuggaSys/diagram.php
-Simply create a recursive UML-line and try to hover it.
=> Recursive lines can now be hovered

DuggaSys/diagram.js
Now copying lines from/to attributes should not result in a error. See Linked issue for more detail.
=> Fix for issue #8983

DuggaSys/analytic.js, DuggaSys/analytic.php, DuggaSys/analyticService.php, DuggaSys/codeviewer.php, DuggaSys/showDugga.php, Shared/basic.php
Added user information tab to analytic which present information of selected users. The information includes page loads for various parts of lenaSyS and users events. 
___ 
How to test:
Before testing remove the log dir located in htcdocs, the tables have been modified so a fresh db is required.
=> Added user information to analytic - G1-2020-W20-ISSUE#8850

DuggaSys/diagram.js
The issue was solved by removing two uneccessary lines of code that made the diagrams load twice, causing the error. The error should no longer appear in the console when generating example diagrams.
Tester: go to help-generate example ER/UML-diagram and check the console for errors.
=> Solves issue#9072, error in console when generating example diagrams

DuggaSys/diagram.js
The flash "Please draw more lines!" should not appear anymore while in normal mode. It should also be impossible to create a mutation when moving the camera in mid-drawing. 
**Test this:** Select Draw Free mode and move around the canvas by holding down rightmouse button and dragging the mouse. Draw free mode should automatically change to normal mode. Now try to rightclick on the canvas. If the flash does not appear on top of the screen the issue is fixed. 
**Test this:** Select Draw Free mode and start to draw two different points. Instead of drawing a third point try to move around the canvas by holding down rightmouse button and dragging the mouse. The drawing should be deleted instead of creating a mutation. 
**Link to test:** …
=> fix issue#8903 fix flash and mutation in FreeDraw

install/install.php
The permissions-modal (popup at start) now only shows if permissions are not sat.
To tester: navigate to http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%237419-FRESH/install/ and open the installer. The permissions-modal should show right away. Follow the instructions (i.e: run the sudo chgrp/chown commands in putty on testserver). Then try running the installer again, now the modal shouldnt show.
=> G4 W20 Fixes #7419

DuggaSys/resultedservice.php, Shared/basic.php
A log occurs when a teacher pass(green) or fail(red) a dugga.
Logging which teacher who marked dugga and a timestamp:
Logging description with corse, duggaID, mark(1=fail, 2=pass) and which user who did the dugga.
Logging when a student does a submit of a dugga is already implemented with eventtype DuggaFileupload.
=> Logging when a teacher mark a dugga

DuggaSys/diagram.js
Fixes #9066 
Special case has been created for when both objects connected to a line is attributes. When this is the case we do not create new points. See linked issue for better detail of what is being solved here.
Test by connecting two attributes with a line, then copying and pasting them. May also be worth connecting other combinations of objects to make sure nothing else broke.
http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239066/DuggaSys/diagram.php
=> Fix for #9066

DuggaSys/diagram.js
It should now be possible to add and remove points to/from existing freedraw objects. 
**To add points:** Double-click on a line where the point should be added. The freedraw object needs to be selected for this to work.
**To remove points:** Select a freedraw object and hover a point and press delete. If no points are hovered the object will just be deleted.
=> Now possible to add and remove points to/from freedraw objects, issue#6891

install/install.php
The enter-key functionality only works if `modal.style.display = 'none'` so now this value is set if the modal isn't shown.
For tester: checkout the branch G4-2020-W20-ISSUE#8987-2 on windows and see so you can move forward with the installer by pressing enter-key.
=> Initialize permissionModal to none FIXED #8987

DuggaSys/diagram.js
Added localStorage to Hide Comment option. If the user hide comments they should still be hidden when the page is updated. 
**Test this:** Create a text object, load its appearance menu and select the comment checkbox. Now select Hide Comments from the toolbar. View -> Hide Comments. Now that the comment is hidden try to update the page and make sure that the comment is still hidden. 
Another way to check if the value has been stored in localStorage is to enter the browsers inspect mode: Inspect -> Application -> Local Storage. Make sure the hideComment is stored.
**Link to test:** http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239103/DuggaSys/diagram.php
=> fix issue#9103 localStorage for Hide comment

DuggaSys/diagram.js, Shared/css/style.css
The rulers do now adapt to the zoom. The spacing increases instead of the values changing which is the intended functionality. I made some special cases for smaller zoom values since a bigger value difference is needed between each big step to prevent cramped text and lines. Seems to be working well.
- Test to activate the rulers, move around and zoom a lot to test every possible zoom value so the rulers show the right values and so text and lines never gets cramped.
Link: http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239061/DuggaSys/diagram.php###
=> Fixes #9061- Rulers adapt to zoom

Shared/css/style.css
Solves #9070.
Changed some styling to Access Editor dropdowns. 
They now open at the bottom of the clicked cell and spans the whole width of the cell, similar to the group dropdowns. This ensures the cell is not covered by the dropdown like what would sometimes happen before. Since there is no way to see what option is selected in the dropdown I feel like this is a good thing, although I think it would be good to also show what value is selected in the dropdown itself. But that should be it's own, separate issue.
=> G2 2020 w20 #9070 access dropdowns should now look/behave more consistently

DuggaSys/sectioned.js
When creating a new course-version you will get sent to the new version. This will only work when choosing Copy content from None
=> Changed to changeCourseVersURL from changeURL | Issue #8874

DuggaSys/fileed.js, DuggaSys/fileedservice.php
To test:
Try to delete a file. It should forbid you from doing that with an alert.
Then, go into the code example where that file is used and remove it from there.
Then try to delete the file, it should work.
For example:
If you want to delete the file HTML_Ex1.html in webbprogrammering,
then you must go to the code example "HTML 5 Example 1", then edit the box with HTML_Ex1.html in it, choose a new file there such that HTML_Ex1.html is not in use. Then it can be deleted.
This issue was solved with so many commits due to testing on the server which did not work the way I wanted it to.
=> G3 2020#7478

DuggaSys/diagram.js
The fix to ISSUE#8856 created flashes if invalid line realtionsships were attempted to be created. The problem is that these flashes shows up when the user selects different objects with the line tool selected. This is displayed in the GIF below
The flashes should only appear if the user tries to make a line (by dragging the mouse), not when selecting (by clicking).
**Test this:** Create a bunch of different objects, attributes, entities, relations, etc. Select the Create Line tool and try select the different objects. The flashes should NOT appear when clicking on them. Now try to create invalid relations by  dragging the mouse to the same or between two invalid objects. The flashes should appear as usual. 
**Link to test:** http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239125/DuggaS …
=> fix issue#9125 Drag required for flash to appear

DuggaSys/analytic.js, DuggaSys/analyticService.php
Reworked page retrieve of all necessary db data from a single function, that is pageInformation() located in analyticService. This was not part of the issue but had to be done to get it to work properly. The part which was added for the linked issue is the the table presenting an overall view of all pages hit information. Not all pages have been added due to that being a separate issue https://github.com/HGustavs/LenaSYS/issues/9077 .
=> Reworked page information and added table with hits for each page - G1-2020-W20-ISSUE#9106

DuggaSys/duggaedservice.php
Solves #9113.
Added decoding in duggaedservice.php for qname.
Tested with å/ä/ö/Å/Ä/Ö characters. Not sure how it handles other characters like ß for example. I felt that it was not needed since I doubt such characters will ever be used, unlike åäö. But feel free to look into it if you'd like.
Screenshot shows the dugganame "ööö" after the fix. Before the decoding this would be written out as `"&ouml;&ouml;&ouml;"`.
=> åäö characters in name are now displayed correctly in Edit dugga window

Shared/css/style.css
Solves #8922.
The canvas element now scales properly for smaller screen sizes on both Chrome and Firefox.
Screenshot is from Firefox Dev Tools. See linked issue for a "before" picture.
The Save/Reset buttons are not properly positioned. This should be handled/solved separately.
Please test this using at least both Chrome and Firefox (and resizing the window/using dev tool mobile tool functionality), but feel free to try it in other browers as well.
=> Canvas element in Transformationsduggas should now scale properly on both Chrome and Firefox

DuggaSys/diagram.js, DuggaSys/diagram_objects.js
Removing lines from attributes now also deletes appropriate connection from connectorTop.
Function "removePointFromConnector" had to be modified to achieve this since more information was needed to delete correct connection when many lines can share the same startpoint due to how attributes work.
Tester:
Make connections to and from an ER-attribute and play around with deleting and adding connections while console logging the attribute. Also make sure that connection references the correct line in all situations.
http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239185/DuggaSys/diagram.php
=> Solution for clearing attributes connectorTop

Shared/css/style.css
Updating the styling for the border-right for tabs indentation. The pixels were off for some reason after the merge. 
This is how it looked before:
This is how it looks now:
=> Updating the style for tabs | Fix for issue #9169

DuggaSys/sectioned.js
The issue was that coursename never existed when entering codeviewer so when returning it did not know what the coursename is
Now when returning from a dugga or codeviewer with the button in navheader the cid, coursename and coursevers are all there. The issue was that coursename was not there when returning from a codeviewer.
Co-Authored-By: Emil <b18emigu@users.noreply.github.com>
=> Fixed the issue where coursename is gone when returning from coideviewer

Shared/navheader.php
Before this fix, the "back" icon in the navheader only had a shadow-hover effect on the **sectioned.php** page and not on all the other pages that the icon existed on.
This fix makes it so that the "back" icon has a shadow-hover effect on all the other pages it exists on as well. These pages include:
- resulted.php
- duggaed.php
- fileed.php
- accessed.php
Image for clarification:
The applied hover effect on the "back" icon:
<a href="https://gyazo.com/0f2e8c0f911a0a022e1888e313ded251"><img src="https://i.gyazo.com/0f2e8c0f911a0a022e1888e313ded251.gif" alt="Image from Gyazo" width="138"/></a>
=> Put shadow on "back" icon | Fix for issue #9197

Shared/resetpw.php
Removed the redundant code. To test download sqlite and open the database after attempting to reset your password, event 12 is the event created by the request barrier(if the reset request failed because of a invalid username etc) and 13 is a log entry for security question entires after a valid username was entered. I didn't manage to find a valid username in my install after several attempts so I'm not sure how the solution works in there but the code looks the same in both spots.
=> G4 2020 w20 issue#7360

DuggaSys/accessed.js, DuggaSys/accessed.php, Shared/css/style.css
To test this pull request create a new user and input invalid personal identification number and a warning should appear on the bottom. The following criterion should be checked:
1. Format is expected to be `######-####` or `########-####`
2. Year cannot be in the future
3. Only correct dates should be ok. 1997 was not a leap year so 29th of February that year should give an error. For example `970229-1313`.
4. The last digit of an SSN is a control digit. Make sure it doesn't give an error when you enter yours.
=> G2 2020 w20 #8935

DuggaSys/sectioned.js
When closing the MOTD the top fab button will no longer get another position then intended
=> Fixed MOTD close button not moving top fab button#9173

DuggaSys/diagram.js
**Link to test:** http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239196/DuggaSys/diagram.php
Before fix there were flashes when creating incorrect relations between all object except for text objects. Now there should flashes for when trying to create lines to/from text objects. 
**Test this:** Create a couple of different object including a text object, select the "Create Line" tool and try to create relations with the text object by dragging the mouse to or from the text object. 
Before: 
After: 
Before fix the Savestate would trigger everytime the user selected different objects with the "Create Line" tool selected. After fix this should not happen anymore.
**Test this:**  Create a couple of different objects, then open the web browser's insepect mode and view the local storage. …
=> fix issue#9196 Text object flash / Savestate issue solved

install/install.php
For tester: Go to http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%236922-2/install/ and run the install.php. Verify that on the "Write-Over" page there is an option to run as transaction.
Verify that the installer works with and without the option ticked. In the log at the last page there is different outputs, "Initialization of database complete as a transaction completed". "Initialization of database complete." respectively.
=> Added an option to run init as transaction. FIXES issue#6922

DuggaSys/diagram.js, DuggaSys/diagram_IOHandler.js
We should now be able to write a generate example diagram to a given layer. select a layer and see if the diagram is created within that layer. Before this fix the example diagrams where always written to layer one.
Link: http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239170/DuggaSys/diagram.php
=> Fix Generate example writes to active layer - Issue 9170

DuggaSys/diagram.js
Link: http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239159/DuggaSys/diagram.php
*Needs testing*
*Activating a layer with drop-down menu "Write to layer" results in selected layer being added to drop-down menu "View layer". it's important that this layers is still active in "View layer" after a page refresh
Note layer one will always be active after a page reload as this was intended design during construction of layer functionality. This was done just to avoid so the diagram never would start up without a viewing layer being active. perhaps this should be change but its not important for this pull-request.
=> Solve issue 9159 | Diagram Layers

DuggaSys/diagram.js, Shared/css/style.css
Link http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239144/DuggaSys/diagram.php
*Needs testing*
*Font colors should be white while element is active in drop-down menu "view layer" and "write to layer"
*Creating diagram objects within a layer should result in having different board-colors depending on which layer the object was created in.
=> Fix colors for diagram layers | G4 2020 W20 issue #9144

install/install.php
Removed the  function connectLogDB() and the call that called this function. The reason being as Elias stated in the issue the database are created as soon as its needed from another file. So to have it in installer is redudant and possible even bad.
For tester: Just run the installer http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239189/install/ and check that it works
sql-root-password: galvaniseradapa
=> Removed connectLogDB #9189

Shared/dugga.js
If readonly is active on the server, students won't be able to submit duggas, an error will be shown instead.
[Issue 8218](https://github.com/HGustavs/LenaSYS/issues/8218)
Tester: login as a teacher and click the cog next to LenaSYS Course Organization System in courseed. Check the read only box and save. Then log in as a student and try to submit answers to a dugga. It should not work, and an error should be displayed in the console.
There seemed to be some inconsistensies whether checking the box works or not, sometimes I had to go back and check it again. This is most likely not caused by my solution. But keep that in mind if a student is still allowed to submit a dugga, log in as a teacher and check the readonly box again.
=> Solves issue#8218, read-only functionality

DuggaSys/diagram.js, DuggaSys/diagram_objects.js, Shared/css/style.css
The rulers do now show the points for the selected objects. Test to select one and multiple objects to see so all points show up at all times when the objects are selected. Try to move around the selected objects and the lines should follow on the rulers. Move camera and test zoom. 
I know one problem which I will solve in a new issue after weekly merge since I want to get this into the weekly branch. That problem is that connected lines to a selected ER entity that are not selected also show up on the rulers. This is due to previously faulty functions not returning the correct values. The intention is to fix these functions in a new issue to also prevent this problem.
Link: http://group4.webug.his.se:20001/G4-2020-W20-ISSUE%239063/DuggaSys/diagram.php
=> Fixes #9063 - Rulers showing selected object point coordinates

DuggaSys/diagram.js
To test this, select different modes (View > ER/UML/Dev) and refresh the page. The orange crosses on objects should now only show if Dev is selected.
=> Crosses now only shows if developer mode is active after refresh (solves 9207)

DuggaSys/analytic.js, DuggaSys/analyticService.php
Now logged data is presented again in page information:
=> Resolved data not showing up on page information - G1-2020-W21-ISSUE#9266

Shared/css/style.css
Putting a tasteful box shadow on MOTD banners to make them look less one-dimensional.
=> Putting box shadow on MOTD banners | Fix for issue #9194

DuggaSys/diagram.js
Undo in the diagram broke during weekly merge and should now work properly.
=> Fix to not being able to undo properly

DuggaSys/diagram_objects.js
Before fix the Left and Right text alignment options would not position the text correctly. This is clear when typing long and/or short strings. After fix Left and Right text alignment options should position the text in a correct position regardless of the length of the text. 
**Test this:** Create a text object and change the Text alignment option to left and right. Make sure the text is properly aligned. Also try different text sizes, font families, text lengths and zoom positions. 
**Link to test:** http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%239284/DuggaSys/diagram.php
**Before:**
**After:**
=> fix issue#9284 Text alignment independent of string size

DuggaSys/diagram.js, DuggaSys/diagram_objects.js, Shared/css/style.css
This removes many previous functions that did not work as expected. Some of them returned the wrong values. Some functions were also quite unreadable so a few were simplified a lot making it possible to easily understand them. This makes it easy for future development to implement new functionality around it.
The fix for all of these functions also fixed what I originally created the issue for. When selecting ER entities that have lines connected, the line points also showed on the rulers even though they were not selected. Test this. 
Since I reworked quite a few functions. Also test the diagram generally. Especially line connections to different types of objects, especially attributes and try to delete the line. Also try to delete an object that a line is connected to. All lines should …
=> Fixes #9233 - unwanted line coordinates show on ruler when ER entity selected

DuggaSys/analyticService.php
All pages now retrieves data from userHistory. This can be seen by navigating to analyticService.php and going through the function pageInformation(). 
How to test:
Check the queries in pageInfromation() that they retrieve FROM userHistory like in the picture below and make sure that the page information tab on analytic is functional.
=> All pages on page information now retrives data from userHistory - G1-2020-W21-ISSUE#9306

DuggaSys/diagram.js, DuggaSys/diagram.php
A new drop down element has been implemented under the exsisting shortcut ones. This resets the values of every keybind to the initial ones when you first open the diagram. Test by rebinding and then reseting, the key before the rebind should be the actual bound key. Closes#9150
=> Reset shortcuts implemented ISSUE#9150

DuggaSys/duggaed.js
Solves #9249. 
Added a check for qid. If qid != "UNK", validateDuggaName is run when a dugga is selected in the Dugga Editor which means new duggas (where qid === "UNK") will not have their name validated right away (only onChange).
=> #9249 now only runs validateDuggaName on selection for existing duggas

DuggaSys/sectioned.js
The items "code examples" and "links" now follow the vertical line and do not break it. 
You can indentate (push) tabs to the right to create a workflow if you want a certain code example or link to belong to a certain sub-test or similar things.
The borders (the black lines) are a little bit off-centered but there's a pre-existing separate issue for that and it's not created by this pull request.
=> Tabs indentation for code examples and links | Fix for issue #9192

Shared/css/style.css
The only solution I found to center the icons in the fab buttons was to make the title text slightly smaller. This centers the fab buttons. It now looks like this:
Before it looked like this:
=> Fixing the fab button icons placements | Fix for issue #9216

DuggaSys/sectioned.js
Now when editing a course version you will no longer get the resetMOTDCookieForCurrentCourse error
=> Solved resetMOTDCookieForCurrentCourse #9211

install/install.php
Added $completeQuery to scope outside try-clause so we can access it from catch-clause.
For tester: run installer at http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%239324/install/install.php 
when prompted for root login use:
username: uselessroot
password: galvaniseradapa
Verify that the below undefined variable is not there.
=> Added $completeQuery to broader scope FIXES issue#9324

install/install.php
Problem:
Because root doesn't have access it cant create stuff. And error was undefinied.
Solution:
Now $errors is definied properly.
**For tester:** 
Go to http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%239247/install/ and run the installer. When prompted for root-credentials use:
username: uselessroot
password: galvaniseradapa
Verify that no error-message for undefined $errors are printed.
=> Defined global error where needed FIXES issue#9247

Shared/css/style.css
The spacerRight border stylings for 'end tabs' were off again. Hopefully they stay the way they're supposed to this time. 
This is what it looked like before the fix:
This is what it looks like after the fix:
=> Updating the styling for borders | Fix for issue #9264

DuggaSys/diagram.js
Fix so that when a freedraw object is double clicked, the appearance form is opened as it is supposed to. Also made it a little easier to double click lines accurately.
**To test:** Create a freedraw object and double click in the middle of the object. The appearance form should appear.
=> Fix so that appearanceform is opened for freedraw objects, issue #9359

Shared/css/style.css
Blue border now aligns with drop-down menu
Before: 
After:
=> Drop-down menu in diagram fixed (issue#9267)

DuggaSys/codeviewer.js
Replaced JQuery with native JavaScript equivalent functionality and fixed incorrect indentation. Test by pressing any "reset boxes" button on a template. Do this on all templates except template 10 (which doesn't have a reset-button) to ensure that the reset functionality still exists.
=> Updated function "resetBoxes" to better fit the code standard.

DuggaSys/diagram.js, DuggaSys/diagram_IOHandler.js, DuggaSys/diagram_objects.js
Test this by turning on dev mode and delete a couple of symbols. There shouldn't be any red crosses at origo
=> G4 2020 w21 issue#9355 Empty points are no longer drawn in origo.

DuggaSys/diagram.js, DuggaSys/diagram_objects.js
You can no longer move or click hidden comments, and the cursor does not change when hovering over them.
[Issue 9208](https://github.com/HGustavs/LenaSYS/issues/9208)
Tester: Create a textbox in the diagram, double click it and check the "comment" checkbox. Then go to view->hide comments. The comment should no longer be visible, it should not be movable, clickable, and the cursor should not change when hovering over where the hidden comment.
=> Solves issue 9208, hidden comments no longer movable or clickable

DuggaSys/analytic.js, DuggaSys/analyticService.php
All files names are now present in the dropdown list even if they don't have entries in the log db.
=> Added all file names to file information - G1-2020-W21-ISSUE#9119

DuggaSys/analytic.js, DuggaSys/analyticService.php
Number of service crashes is now shown in general stats table.
=> Service crashes shown

DuggaSys/resulted.js, DuggaSys/resulted.php, DuggaSys/resultedservice.php, Shared/SortableTableLibrary/sortableTable.js, Shared/css/style.css
This solves issue #9014.
You can now choose to only export grades that are unexported, and choose to export all the grades. 
This is what pops up if you choose to export only unexported grades when there are no unexported grades.
This is an example of what pops up if you choose to export only unexported grades when there are unexported grades available.
This is an example of what pops up if you choose to export all the grades.
There are some issues that have been discovered when solving this issue. New issues will be opened for those.
If anything is unclear, feel free to ask.
Co-Authored-By: a18eripi <a18eripi@users.noreply.github.com>
=> #9014 Added export functions.

Shared/css/style.css
The resize,minimize and maximize buttons is now removed from the mobile view. 
Result:[![Image from Gyazo](https://i.gyazo.com/ab02ea14650c5a5235e2adb1bb25a7fe.png)](https://gyazo.com/ab02ea14650c5a5235e2adb1bb25a7fe)
=> Solution for branch G1-2020-W19-ISSUE#9299

DuggaSys/resulted.js, DuggaSys/resulted.php
It's now possible to click on the legend to close it. Also changed to `onmouseover` to make it more fluid but if the reviewers prefer `onclick` it can always be changed back. 
**But**, if you use `onclick` instead of `onmouseover` you can't close the legend by clicking on the question mark.
=> G2 2020 w21 #9335: Made it easier to close the legend 

Shared/css/style.css
Deleted unused styling of color that was overwritten. The group agreed that the text should be black instead of purple, for clarity.
=> Deleted unused styling of color. #9269

DuggaSys/templates/kryss.js
Solves #9391.
Frågedugga should now display submission info (dugga not submitted, dugga submitted, dugga passed/failed etc.) in the navheader identical to how other duggas do.
=> G2 2020 w21 #9391 Frågadugga now has submission info in navheader

DuggaSys/duggaed.js
Solves #9281.
Last Modified is now included in the switch cases that gets their seconds cut off in renderCell. See screenshot.
'Before' screenshot can be found in linked issue.
=> #9281 Last Modified date now correctly gets seconds cut off when rendering to table

DuggaSys/analytic.js, Shared/basic.php
Removed AJAX call and made it with a local array instead. This removes any complications and the need to connect to other sources.
Once again the events table should show evendescription and the name of the event
=> G1-2020-W21-ISSUE#9099-V2

DuggaSys/diagram.js
Deleting freedraw objects together with other objects was not working properly. Should now be possible to delete them together. Deleting them with the menu option was not working either. 
**To test:** Try to delete freedraw objects together with other objects in different ways. Also try to delete them with the menu option.
=> Fixes so that path objects can be deleted correctly, issue #9360

DuggaSys/diagram_objects.js
**Problem 1:** Before fix when changing font size in global appearance to something other than tiny the UML's min width didn't fit with the longest string anymore.
After fix this should be solved. All the font sizes should fit with the UML boxes, and it should be impossible to resize the boxes smaller than the text. 
**Problem 2:** Before fix the min width of the UML box didn't look at the longest string. It looked at the string with most characters. This is illustrated in the GIF below.
After fix this should not be a problem anymore. The minWidth should be limited by the longest string,
**Link to test:** http://group4.webug.his.se:20001/G4-2020-W21-ISSUE%239376/DuggaSys/diagram.php
**Test this:** Create a UML-class and change the font size in global appearance to small, medium and large. …
=> fix issue#9376 UML text size problem solved

DuggaSys/diagram.js
Shift resize now works and keep proportions, test this by shift resizing a symbol using top left or bottom right points. Closing#9375
=> G4 2020 w21 issue#9375 fixed shift resize

DuggaSys/diagram.js
SaveState is no longer called everytime you hit 'delete', only when an object/point actually is removed.
To test, watch for console output "State is saved" as you delete objects and as you hit delete when nothing is selected.
=> SaveStated called only when deleting objects (solves 9187)

DuggaSys/sectionedservice.php
giving the link to new code-example the name of section-name and exampleid, so it is no longer set as "null".
=> Fixed the issue with new code added link being set to"null"

DuggaSys/sectioned.js
Adding tabs indentation for itemKind 6 and 7 (group activity and message). 
Now when you add items 'group activity' and 'message' they won't break the vertical line and can be indented the same way tests (duggas) can.
This is how it looked before:
This is how it looks after this fix:
=> Adding tabs for itemKind 'group activity' and 'message' | Fix for issue #9400

DuggaSys/sectioned.php, Shared/css/style.css
The top tab button is now styled to have a larger space from the start of the drop-down and the button itself.
This is how it looked before:
This is how it looks after this fix:
(the button is only green because it's selected)
=> Styling the top fab button | Fix for issue #9419

Shared/css/analytics.css
Canvas element scale in height.
Changed the position of the piechart slightly to the left to better fit with the table.
Before:
After:
=> Piechart scale

Shared/css/style.css
Fixed the media query to response to resize before the markdown collapses. 
result:[![Image from Gyazo](https://i.gyazo.com/5f6b04b497a801c395290febb4c3f5e1.gif)](https://gyazo.com/5f6b04b497a801c395290febb4c3f5e1)
=> Solution for branch G1-2020-W19-ISSUE#9444

DuggaSys/sectioned.js
This error should not be visible anymore 
Removed the styling that didn't work and was not needed as ST/SV users should be able to see the navheader.
Test with these two users
Studentteacher: Got 'ST' access for all courses.
mofre
Supervisor: Got SV access for all courses.
ryrey
Password is ‘password’.
=> G3 2020#9260 | Removed styling that caused the error

DuggaSys/showDuggaservice.php, DuggaSys/templates/kryss.js
**Note: https://github.com/HGustavs/LenaSYS/pull/9363 should be merged before this (this branch is branched from that issuebranch).**
Solves #9436.
Changed a faulty if-statement inside a loop in showDuggaservice.php. This loop sets the value of $param which should contain dugga parameters for the correct variant, but because of this faulty if/loop it would loop through all the variants for the Frågedugga and $param would consequently always contain parameters for the last variant. With the if-statements fixed the correct parameters should be saved in $param.
Screenshot one. This is the same user used as an example in linked issue. The variant is 17. Now shows the correct question, where as before it did not.
Screenshot two. Shows all the available variants. Here you can see that the …
=> G2 2020 w21 #9436 Frågedugga will now show the correct variant 

DuggaSys/templates/kryss.js
Solves #9357. 
String inputSplit[i] was split on wrong characters causing question/answer options to render as 'undefined' (see linked issue for screenshot). Corrected this and now the dugga should render properly.
=> G2 2020 w21 #9357 Frågedugga should now render properly

DuggaSys/analytic.js, DuggaSys/analyticService.php
The newest file now is shown in the general stats table along with the timestamp when it was created.
=> Added most recent created file to general stats - G1-2020-W21-ISSUE#9448

DuggaSys/analytic.js, DuggaSys/analyticService.php, Shared/loginlogout.php
Added new section to the table containing data logged when someone tries to password guess. This section contains the guest ID (if one is set) of the client that's trying to login.
Test by making 3 consecutive login fails using the same username (thus forcing a password guess log). Then view the password guessing section of the analytic page and observe the guest ID that's been logged.
=> Logging now also includes eventual guest IDs.

DuggaSys/templates/kryss.js, Shared/css/dugga.css
**Note: #9363 should be merged before this (this branch is branched from that issuebranch).**
Solves #9440.
Updates styling in dugga.css. Changed display to inline-flex and centered the number with justify-content and align-items. Removed text-align.
=> G2 2020 w21 #9440 Frågedugga quiz number is now centered properly

DuggaSys/duggaed.php
This pull request removes unnecessary button from the Dugga editor according to the specifications in issue #9410.
The following changes has been made:
=> G2 2020 w21 #9410

DuggaSys/resulted.js, DuggaSys/resultedservice.php
This solves #9421. This also solves a bug from #9014. 
The last exported date is not stored in local storage anymore. Instead, it's taken from the database. This does so that you can't take away the last exported date by removing the local storage item, and it'll always load the newest date when opening ResultEd.php
Co-authored-by: a18eripi <a18eripi@users.noreply.github.com>
=> #9421 Last exported date does now come from the database instead of local storage.

DuggaSys/accessed.js, DuggaSys/accessed.php
Pull request to solve issue #9133, upgrading the email verifier.
When this email verifier has been developed, the example emails on [this Microsoft page](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format) has been used. After this pull request all invalid examples on that page shows as invalid plus the bottom two, though I'd argue that doesn't really matter since we can expect LenaSYS users to only have latin characters in their email anyway.
Screenshot of the [Microsoft](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format) page
=> G2 2020 w21 #9133

Shared/css/style.css
Added 10px margin-left to give the headings more space to the left.
=> Headings are now placed more to the right 

DuggaSys/analytic.js
There should now be a new option in the dropdown for fileEvents that should display fileEvents (surprise). FileEvents should also be removed from the 'normal' events table. 
Picture 1: Normal events without any fileEvents
Picture 2: New dropdown containing only fileEvents in a table
=> G1-2020-W21-ISSUE#9367

DuggaSys/diagram_objects.js
Before fix the size of the line jump changed while zooming in and out. The size should now be compatible with the zoom value of the diagram. 
**Test this:** Create a line jump by intersecting two different lines in a ER-diagram. Zoom in and out and make sure the size of the line jump stays the same. 
**Link to test:** http://group4.webug.his.se:20001/G4-2020-W22-ISSUE%239509/DuggaSys/diagram.php
**Before:** 
**After:**
=> fix issue#9509 line jump zoom compatibility

DuggaSys/codeviewer.js, DuggaSys/sectioned.js
Code examples in mixed ordering:
Going from **HTML5 Example 1** to **HTML5 Example 3**:
<a href="https://gyazo.com/8b3dce32cbaa75fe0c2d79b6aaa11204"><img src="https://i.gyazo.com/8b3dce32cbaa75fe0c2d79b6aaa11204.gif" alt="Image from Gyazo" width="1920"/></a>
=> Codeviewer should now take the ordering of code examples into consideration

DuggaSys/fileed.php, Shared/css/markdown.css
Using one scrollbar in markdown preview.
=> Use one scrollbar

DuggaSys/analytic.js
The percentage values in the table will now always have 2 decimals.
Controll by looking at the column containing the percentage values in the table.
closes #9508
=> G1-2020-W22-ISSUE#9508

DuggaSys/analytic.js
Every 4th text-entry to the piechart now resets the Y value and increases the X value for the next four textentries, which makes them appear at the same height but further to the right. This makes it possible to include more than four textentries to the piechart and it also aligns them nicely.
The expected layout of the textentries can be seen in the image below:
=> Piecharts now create a new column after every 4th text-entry.

DuggaSys/analytic.js, DuggaSys/analyticService.php
All pages now appear in page information dropdown, they are all connected to their respective log db query in analyticService.php. The queries needs to be modified to show useful information for each page, this needs to be set done in another issue.
=> Added all pages to page information dropdown - G1-2020-W22-ISSUE#9305

DuggaSys/fileed.php, Shared/css/style.css
The issues existed in accessed, fileed and duggaed and now the search-bar should look like this in mobile view:
Also added the tooltip box (the one with the "?") to fileed.
=> G3 2020#9464 Search bar in mobile-view looks better

DuggaSys/diagram.js
Fix so that resizing ER and UML objects doesn't lose focus when trying to resize below the minimum size. There is a GIF in the issue showing how it broke before.
=> Fix so that resize dosn't lose focus, issue #8740

DuggaSys/diagram.js, DuggaSys/diagram.php, Shared/css/style.css
Rulers do now work in full screen mode. The full screen state is now also pushed to local storage so when refreshing in full screen mode, full screen mode will be active after refresh. The toolbars have been taken into consideration. The toolbars will be moved in full screen mode when the rulers are active.
- Test to activate full screen mode. Active rulers and see if they work in full screen mode and have the right values (easy way to check is if 0 is at the origo line).
- Test to activate the toolbar (t) while in full screen mode. Try to use the toolbar both when having rulers off and on. When rulers are on the toolbar should be positioned under and to the side of the rulers. When no rulers are active the toolbar should be aligned to the screen edges like before. 
- Test to refresh the …
=> Fixes #9593 - Rulers now work in fullscreen mode

DuggaSys/templates/kryss.js
Solves #9533.
The Check Answers-button was obsolete and has been removed. checkQuizAnswer-function was also removed. Below is a screenshot showing what the "new" Frågedugga looks like (without the Check Answers-button).
=> G2 2020 w22 #9533 removed Check Answers-button 

DuggaSys/templates/clipping_masking_dugga.html, Shared/css/dugga.css
- Moved some inline styling. 
- Added shadows to make a card feeling.
- Cleaned up some code.
- Added a paragraph to the "Rityta ".
- Added a media query to make it more mobile-friendly.
=> Fixed layout in Random clipping dugga. #9522

DuggaSys/resultedservice.php
Solved the bug where the no unexported popup would appear when opening the ResultEd page.
The only problem found when testing on localhost is that the export date in the popup takes a long time to popup if you export a lot of grades when only exporting unexported grades. This might mean that something in the code needs to be refined so it runs faster. But that's a future issue in that case.
Co-authored-by: a18eripi <a18eripi@users.noreply.github.com>
=> #9518 Solved bug from #9014.

DuggaSys/diagram.js, DuggaSys/diagram.php, Shared/css/style.css
A speed slider and a button to reset the diagram timeline has been implemented. All of the extra timeline controls are now under a "+" button which on click will animate the rest of the control buttons to show. This was a way to save space. When resetting the timeline, the timeline should have 0 colored steps and be empty. The speed slider can go from 0,1 meaning 0,1 seconds per state change to 3 seconds per state change right now and changes by 0,1 for each step. It should be possible to interact with all the controls without stopping the animation.
=> Fixes #9613 - speed slider and reset button to diagram timeline

Shared/css/style.css
The boxes now doenst move out of the windows when resizing
result:
=> Solution for branch G1-2020-W19-ISSUE#9546

Shared/css/markdown.css
preview textfield now wrap
Together with pull request https://github.com/HGustavs/LenaSYS/pull/9529 a scrollbar will appear on the "mdtarget" element instead of "fieldset" element.
=> markdown preview textfield does not break

DuggaSys/diagram.js
There is now a part in the timeline representing the empty diagram. Test so all diagram parts works and loads the correct state and the first one loads the empty diagram. I also made it impossible to select or attempt to create objects while the animation is running to prevent possible errors.
Link: http://group4.webug.his.se:20001/G4-2020-W22-ISSUE%239622/DuggaSys/diagram.php
=> Fixes #9622 - Timeline part for empty diagram and more

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagram_IOHandler.js, Shared/css/style.css, Shared/icons/fullscreen.svg
You can test by loading any example diagram (Help -> Generate example diagrams) or by creating your own diagrams. Or do both.
The original issue #3744 was about adding animation support for the diagram. I took it one step further, also creating a timeline making it possible to manually go to any available diagram state. In my opinion this is even more useful. I made sure the timeline works in all scenarios; when rulers are active, when full screen is active, when rulers and full screen mode are active at the same time. **Test** all of these scenarios.
The timeline gives good response for which states that were included, will no longer be included after clicking a hovered part on the timeline and which states that were not included, but will be included after clicking a part. **Test** so …
=> Fixes #3744 - Added timeline for diagram states and animation support

DuggaSys/sectionedservice.php
Users with studentteacher and supervisor access can now see hidden items(duggas, headings, codes).
test with:
Studentteacher: Got 'ST' access for all courses.
mofre
Supervisor: Got SV access for all courses.
ryrey
Password is ‘password’.
=> Gave studentteacher access to see hidden items || issue #9461

DuggaSys/analytic.js
The table headings and the dropdown should now still be visible. Test by removing logs and then look at the page.
Closes #9619
=> G1-2020-W22-ISSUE#9619

Shared/navheader.php
Only superUsers(brom) can see the "create new course version" button in the navheader now:
When logged in as ex teacher3 or mofre you should not see the button.
=> Only superUsers can se the new-version button

DuggaSys/diagram.js, Shared/css/style.css
Guidelines can now be created by dragging from the rulers. Before guidelines could only be created by menu-items.
=> Fixes #9667 - Guidelines can be created by dragging from the rulers

DuggaSys/analytic.js
A counter has been added on top of the tables contaning user page loads. The counter contains the current selected user, page and the amount of times said user has loaded that page. 
There's an issue with the counter which appears when the selected user is changed, which causes the counter to break. This is fixed by changing the selected file aswell. This bug may become a future issue.
=> Added page load counter to user information pages

DuggaSys/showDuggaservice.php, DuggaSys/templates/kryss.js, Shared/dugga.js
Solves #9516.
User answers and correct answers for the specific dugga variant the user was assigned to should now be displayed properly. Works for both single-question variants as well as variants with several questions. See screenshots.
Screenshot one. Example of submission from a variant with one question with a correct answer.
Screenshot two. Example of submission from a variant with two questions with one correct answer and one incorrect answer.
Screenshot three. Example of how a dugga with more than one question looks. Not necessarily related to the solved issue but I'll include it just to show that the process works all the way from opening the Frågedugga to submitting and opening the submission in the Result Editor.
=> G2 2020 w22 #9516 Frågedugga results should now be handled properly in Result Editor

DuggaSys/diagram.js
The guidelines were always stuck at the same position before. Now they are moved together with the ruler value they were positioned at. This should work when zooming and moving the camera. It should also work to refresh the page and the guidelines should be correctly positioned.
=> Fixes #9668 - Guidelines now stays at the ruler value when moving and zooming

DuggaSys/analytic.js
Unidentified username was caused by the variable for retrieving username being incorrectly spelled. 
Before:
After:
=> Fixed incorrect naming of variable to retrieve username - G1-2020-W22-ISSUE#9676

DuggaSys/filereceive.php
When logging editing or creation of course local files duplicates will appear in the file information dropdown, this is now solved.
Before:
After:
How to test: 
Edit or create a course local file in fileed, now navigate file information and check whether there are two mentions of the same file. There should only be one now.
=> Fixed duplicate of files in file information dropdown - G1-2020-W22-ISSUE#9621

DuggaSys/analytic.js
Now files edited or created shows the correct timestamp. 
Before:
After:
=> Corrected the timestamp displayed for files in File Information tab - G1-2020-W22-ISSUE#9682

DuggaSys/analytic.js, DuggaSys/analyticService.php
Information from resulted.php and fileed.php  with number of hits, userId, username and timestamp is now shown on the "user information" page. 
Maybe there is more information to show, but for now its like this.
resulted:
fileed:
=> Analytic: User information - Resulted and fileed information shown in user information 

DuggaSys/analytic.js
The timestamps are no longer off by 2 hours.
=> Time is now correct in courseed section of User Information

DuggaSys/diagram_objects.js
Before fix the points for free drawn objects were too small when zoomed in and too big when zoomed out. 
The size of the points should now change dynamically with the zoom value of the diagram like the points for all the other objects. 
**Test this:** Create a free drawn objects. Zoom in and out and make sure the size of the points is neither too small when zoomed in or too big when zoomed out. Create another kind of object to compare the point sizes. They should be the same.  
**Link to test:** http://group4.webug.his.se:20001/G4-2020-W22-ISSUE%239620/DuggaSys/diagram.php
**Before:** 
**After:**
=> fix issue#9620 Free draw point size change with zoom

DuggaSys/diagram.js, DuggaSys/diagram.php, Shared/css/style.css
It is now possible to create guidelines. There is a new Guidelines menu-item that is a side-dropdown with everything related to guidelines. It is possible to create horizontal and vertical guidelines here. Guidelines can also be created by dragging it out from one of the rulers. These menu-items will always create the guideline in the middle of the canvas to begin with, they can then be moved around. The guidelines should always follow the ruler value they were positioned at, when zooming, when moving the camera and after refreshing the page. They should only be visible when the rulers are activated. It is possible to delete one guideline at a time by dragging it outside of the canvas container area. All guidelines can be deleted at once by the menu-item in the side-dropdown for …
=> Fixes #9315 - Implements ruler guidelines

DuggaSys/duggaed.php
Solves #9550.
Duggas/Variants should now be styled using the dugga.css file (as well as style.css, which was already linked before).
This fixes the styling for a few previews, like the Biträkningsdugga and Färgdugga but not for others (Quiz/Frågedugga & HTML CSS Testdugga/html_css_dugga, maybe more). The issues related to these duggas are caused by something else and separate issues should be opened for these.
=> G2 2020 w22 #9550 added stylesheet link (dugga.css) to duggaed.php

DuggaSys/showDuggaservice.php, DuggaSys/templates/kryss.js, Shared/dugga.js
Solves #9566.
**Note: This is branched from https://github.com/HGustavs/LenaSYS/tree/G2-2020-W22-%239516 since it relies on the changes made there to work.**
Removed saveResultQuiz and replaced it with saveDuggaResult, which the other duggas use.
As the linked issue describes this adds a few things "for free", such as this window upon saving:
Before no window would be shown, the only visual feedback given to the user/student was the navheader being updated (the stoplight and timestamp for submission would update). As with the other duggas the Feedback-area of the window would only be show if feedback is enabled for this dugga. Opening feedback from the Section/Course Editor works exactly the same as for all the other duggas.
=> G2 2020 w22 #9566 Quiz/Frågedugga now uses saveDuggaResult instead of it's own saveQuizResult

DuggaSys/templates/html_css_dugga.html, Shared/css/dugga.css
- Moved inline styling to dugga.css. 
- Added media query for smaller plattforms. 
- Removed all tables, tr and td for the content and added div to them. 
- Fixed styling on buttons in #input-col. See img 1 & 2
- Fixed some styling on the preview-col. 
img 1 - After
img 2 - Before
=> Added media query for smaller plattforms.

DuggaSys/sectioned.js
Now StudentTeacher/Supervisor users can see the trashcan icon on items in sectioned and delete the items.
test with:
Studentteacher: Got 'ST' access for all courses.
mofre
Supervisor: Got SV access for all courses.
ryrey
Password is ‘password’.
=> G3 2020 #9645 | StudentTeacher/Supervisor delete items

DuggaSys/fileed.php
The search function didn't work as intened in fileed in mobile-view below 530px when using the mobile search-bar. We got this error:
This is now fixed and you no longer get an error and the search-function works correctly.
=> G3 2020#9594 fixed error in fileed when using mobile search-bar.

DuggaSys/diagram.js
Before fix the objects that were positioned on the virtual paper's line were inconsitent. Sometimes they would get a red outline, sometimes they wouldn't. Also objects that weren't positioned on the virtual paper's line would sometimes get a red outline. This was especially noticeable when zooming. 
After fix this shoud not be a problem anymore. The red outline on objects should only appear when they are positioned on the virtual paper's line. 
**Test this:** Enable Display Virtual paper, create a couple of objects and place some of them on the papers line and some of them next to the line. Only the objects that are placed on the line should have a red outline. Try to zoom in and out and make sure the colors stay correct and consistent with the positioning of the objects. 
**Link to …
=> fix issue#9684 red outline glitch

DuggaSys/diagram.js, DuggaSys/diagram.php, Shared/css/style.css
According to issue #6888 local styling appearance should be removed from from double-clicking to not encourage random colors and styling on objects. 
I did not think it was a good idea to separate the styling options in the appearance menu from the double click appearance menu functionality. It would in my opinion require too many steps to select an item and navigate to the menu-item for advanced settings. I think everything should be accessible from the normal appearance menu.
To not encourage styling on the objects, sub collapsibles will now be generated for these advanced settings. The sub collapsible will only be created if the main collapsible will not only contain advanced properties (can happen when selecting many different objects at the same time as the form groups are divided to …
=> Fixes #6888 - Sub-collapsible for styling

DuggaSys/resultedservice.php
Solves #9575.
Issue was caused by a select query which would select too many students (all students in a specific group, regardless of whether they had made a submission or not). Updated this to only select students who have made submissions and are in the same group as the student you're trying to grade (this only applies to group assignments, no "normal" duggas are affected).
Before this fix it would still update the database correctly, because it wouldn't be able to update/grade students who haven't made a submission, but the GUI was still updated as if they were graded. Hence why a refresh would show a correct table.
Since it would select way too many students it would take a long time to update. After this fix it updates a lot quicker (with small groups, if a group has 20+ members …
=> G2 2020 w22 #9575 Group assignment grading should now update table properly

DuggaSys/accessed.js, Shared/css/style.css
Solves #9735. 
reset-pw is now a class instead of an id.
new-user class should now be applied to new users (but it's a bit unclear how to create/add new users at the moment, something seems to have broken at some point). The styling is applied properly, at least (can be tested by manually adding the class new-user to one of the buttons in Developer Tools).
=> G2 2020 w22 #9735 

DuggaSys/templates/clipping_masking_dugga.html, Shared/css/dugga.css
Fixed styling on #toolbox, #drawingarea, #clippingInfoBox2 and moved inline styling to dugga.css.
=> Fixed styling

DuggaSys/accessed.js
Solves #9673.
Added a new "None"-option for each group dropdown. Made a few small modifications to the updateAndCloseGroupDropdowns so it would handle the new option properly. The changes do not affect anything in a negative manner as they were originally implemented to handle multiple group assignments (this is no longer possible, a user can only belong to 1 or 0 groups at once) so they were obsolete anyway.
=> G2 2020 w22 #9673 added new "None"-option for group dropdowns

DuggaSys/diagram_objects.js
Before, performance heavy functions were used to attempt forcing line type from entities to relations to forced if entity type was Weak and change to normal when entity type was normal.
These functions worked before we started developing during the project. They have not been working for months now though for some reason, they were still used though, wasting important performance. I rewrote these performance heavy long functions, reducing them from 160 to 20 lines. Now the old functionality is working in them again. 
According to customer however, nothing should be forced in the diagram since the functions could force wrong things in many situations. So I just fixed the functions to work like they previously did in a much simpler way and commented out the only place they were used at to …
=> Clears up #8387 - Do not force line type change

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagram_objects.js, Shared/css/style.css
Global appearance menu is now structured in collapsibles so it is clear what objects will be affected by the change. I also made UML and lines be affected by the global appearance menu changes. Almost nothing in global appearance menu affected UML before, now everything does. I also added the advanced properties that are available in the global appearance menu to the local appearance menus so it is possible to style these things on individual objects as well. I also added back the line color change on hover which did not happen anymore after the issue to change line color for when an object is over the paper lines was implemented.
Link: http://group4.webug.his.se:20001/G4-2020-W22-ISSUE%239733/DuggaSys/diagram.php
=> Fixes #9733 - Global appearance menu structure

DuggaSys/diagram.js
Global appearance menu is now mode specific. Create objects of all types. Switch to ER toolbar mode. Open the global appearance menu. Only the objects in the ER toolbar should be mentioned in the collapsibles. When changing some input only the objects available in the ER toolbar should be changed. Test the same when being in UML toolbar mode and when being in Dev display all tools.
Link: http://group4.webug.his.se:20001/G4-2020-W22-ISSUE%237645/DuggaSys/diagram.php
There is just one problem that could possibly be fixed next year; all objects use the same base settings when being created. So when changing global appearance settings in UML mode, only objects active in the toolbar will be changed. But when creating a new object that is not in the UML toolbar, they will still have the new …
=> Fixes #7645 - Global appearance menu is mode specific

DuggaSys/diagram.css, DuggaSys/diagram.php
Fixed a proper cursor type for Zoom in/out buttons in the options panel and a pointer cursor when hovering "Options".
Also disabled user-select for the "Zoom" title in the box.
=> Group3 2021 #9829 - Fixed Proper Cursor Type

DuggaSys/diagram.js
Fixed an issue where new elements had the same name. Each element is now created with the correct name respectively.
fixes #9889
=> Fix: Correct name on new elements - #9889

DuggaSys/diagram.js
"cmd" key combined with backspace on Mac is now the same as the delete button on Windows.
=> Cmd(Mac) + backspace = delete element

DuggaSys/diagram.js, DuggaSys/diagram.php
Fixed so it's now possible to zoom in the diagram with the mouse-wheel and with ctrl+ or ctrl-.
Ctrl+ and ctrl- however interferes with the browser functionality with the same commands. I included it anyway since it was specifically asked to be implemented. A bigger function for handling all zoom-events have not been added as requested, since we already have two functions that handle this (zoomin and zoomout) and changing it could cause unnecessary problems.
=> Fix - zoom with mousewheel and ctrl-keys, issue #9932

DuggaSys/accessed.js, DuggaSys/accessed_removedColumn.txt
Commented out the access column in the function returnedAccess in the accessed.js file. Created a text file called accessed_removedColumn.txt which describes what columns aren't used anymore by the accessed.js file.
=> Removing access category and group assignment from access editor

DuggaSys/diagram.js
Fixed the issue when using backspace in the textbox would cause the whole element to be unintentionally deleted
=> Bugfix when using backspace #9979

DuggaSys/diagram.js
Very simple solution. This should prevent it from happening.
=> Bug fix: Deselecting a non-selected element while holding alt

Shared/basic.php
Removed urldecode from the getOP function, which purpose is to trun +sign into a blankspace.
Co-Authored-By: b19wilfo <62884368+b19wilfo@users.noreply.github.com>
=> Allow + sign to be use in name

DuggaSys/showDugga.php
insertParam was not defined, so we added it above in showdugga.
Co-authors: e15marol & b18jacha
=> insertParam

DuggaSys/diagram.js
Solves #9995, due to an already existing variable movingObject the solution was easy.
=> Fixed if-statement

DuggaSys/diagram.js
Added a selection for checking active element for the key-listeners, if an input, textarea, select is active, none of the key-listeners is now active.
This solves #10026.
=> Added selection for checking if an input is active - ISSUE 10026

DuggaSys/diagram.js
The ruler is drawn while panning the container. Instead of when the panning has completed
=> The ruler now live-updating

DuggaSys/diagram.js
The drawElement function is now using its parameter variable canvasContext in all instances inside the function.
=> Changed function variables #10072

DuggaSys/diagram.js
Removed the posibility to create an edge between the same kind. Exception for the "ERAttr" kind.
This resolves  #10080.
=> Removed the posibility to create an edge between the same kind - ISSUE #10080

DuggaSys/diagram.js
Implemented functionality for clicking lines.
Note: Since the "double lines" are stored as two separate lines individually they are also treated as such when clicking on them. Future functionality could be added to make sure they share the same ID and thus treated as the "same" line.
=> Now possible to select lines #9975

sh/index.php
The url shortener now takes you to the latest version of a course by typing in sh/"coursename". Use underscore instead of blank spaces in coursenames.
For example to get to "Datorns grunder" put /sh/Datorns_grunder in the url. This will take you to the latest version of the course.
=> Fixed redirection to latest courseversion from short url. Issue#9806

DuggaSys/diagram.js
Moved the getContext intro the drawElement function instead to set it through parameter to the function, because the function only uses one context.
=> Moving getContext

DuggaSys/diagram.js
Added a check for maximun number of edges between elements and check the following requirments:
```
- Only one edge can be drawn between two attributes
- Only one edge can be drawn between an entity and an attribute
- Only one edge can be drawn between a relationship and an attribute
- Only two edges can be drawn between an entity and a relationship
```
=> Added maximun number of edges between elements

DuggaSys/diagram.php
Removed diagram_IOHandler.js from diagram.php. This removes the error when loading the page.
=> Solved error in diagram_IOHandler.js

DuggaSys/accessed.js, DuggaSys/accessed.php
We've looked into the purpose of the CID and Term field in the "Add-user"-form. The Ny-field seemed to have already been removed in issue #9753. CID didn't seem to have a purpose so we've removed it along with it's validation and tooltip function. The Term-field as it currently stands is saved in the class-column in the User-table in the database. We have not modified the Term-field.
=> Removed CID from "Add user"-form. Issue#10093

DuggaSys/diagram.js
Fixed by adding a function to only delete selected lines with delte key or backspace key
@a19matma 
#10125
=> "Fixed" Remove specific lines with delete or backspace

DuggaSys/diagram.js
The selected lines no longer deselects while holding down ctrl and clicking on the background.
=> Holding ctrl while clicking background fixed

DuggaSys/diagram.js
By calling enable grid in the onload function, the grid is now being drawn as default.
=> Grid is now enabled by default

DuggaSys/accessed.js, DuggaSys/accessed.php
Removed SSN and PID completely. Term is still used because the data entered in Term gets saved in the class-column in the user-table. We don't know if this has any functionality but we haven't removed it because  it may break something.
=> Removed SSN and PID from "Create user"-form. Issue#10149

DuggaSys/resultedservice.php
Made small change to the if statement on line 260.  The if-statement now checks if usergroups has the value null instead of "none".
Co-author: @a18willi
=> Checks if usergroups has the value null instead of "none" Issue#9752

DuggaSys/diagram.css
Removed pointer event from toolTipText to fix the hover and removed an not hover styling in css because it is not needed due to if not hover the element will go back to default styling.
=> Removed pointer event from toolTipText to fix the hover.

Shared/css/style.css
Make fab button items horizontal in mobile landscape mode, to prevent overflow.
Co-author: @a18willi
=> Fix fab button overflow in mobile landscape issue#10179

DuggaSys/diagram.css
fixed by replace top 130px to 0 px, could not remove top attribute at all because it affects the height of the panel
=> "Fixed" Make options side panel extend to the top

Shared/css/style.css
Updated style.css so that the correct open/close-button for the swimlanes in the course-view is showing by default.
=> Swimlanes now hide after clicking the arrow once. Issue#10185

DuggaSys/diagram.js, DuggaSys/diagram.php
The context is now cleared when switching to line creation mode.
=> Previously selected items cleared when switching to line creation mode

DuggaSys/sectioned.js
Fixed wierd string that broke arrow functionality.
Co-Authored-By: @b18phika
=> Arrow on moments in sectioned now always shows Issue#10191

DuggaSys/diagram.js
When using the box selection you can now de-select by holding down alt and selecting multiple elements.
=> Fixed removing elements when holding down ALT with box selection

DuggaSys/diagram.js
It's now possible to change the line from Normal to Double or vice versa in the options panel after selecting a line.
Side note: 
Warning text when selecting more than one element doesn't work correctly on mouse-down when switching from selecting an entity to a line. Further investigation required.
=> You can now change line properties in the options panel #10305

DuggaSys/diagram.js
When you select an element and re-name it or change the state you can now also save by clicking "Enter"
=> Change element name and state with Enter

DuggaSys/diagram.js
The shortcuts that need to work when caps lock is on are now doing that regardless if the letter is upper or lower case.
=> Enabled shortcuts when caps lock is on

DuggaSys/diagram.js
Now when pressing escape from any other mode we always return to the "pointer" mode.
=> Escape key returns to pointer state

DuggaSys/diagram.js
Now when pasting in elements, the selected elements gets deselected, and the created elements gets added to context.
=> Clear context on paste and add the new Elements to context

DuggaSys/diagram.js
You can no longer right click an element when in edge creation mode to create lines.
=> Disabled right click when in edge creation

DuggaSys/diagram.js
Changed so the flag "ELEMENT_AND_LINE_CREATED" does not have the canAppendTo, this coused the problems described in the issue. Also changed some parameters for the displayMessages to the recent added enums.
=> Fixed error with pasting elements on each other

DuggaSys/diagram.js
This means the cursor style will be pointer when page is loaded
=> Added setCursorStyle to getData

DuggaSys/diagram.js
Now the lines between the objects and its attributes and relations will not be crossing each other, wich will make a more sleek look to the diagram.
Implemented the code from the solution of week 16 branch with the  branch of week 17 to be able to merge it with the week 17 main branch.
Issue #10092 
close #10092
=> Avoiding line crossing on most frequently used browsers. Issue  #10092

DuggaSys/diagram.js
The input field is now defocused and a message is displayed upon hitting "enter". i.e saved.
=> Defocus and display upon enter

DuggaSys/sectioned.js
Replaced all mentions of "feedbacks" with "feedback". Note that there are several css classes named with "feedbacks" but we have not touched these as to not cause any unexpected errors(no refactoring rule).
Co-author: @b18phika
=> Fixed typo. Issue#10418

DuggaSys/sectioned.js
OBS! In order to see the redline be drawn, you have to look at an active assingment, example -> go to demo course -> log in as teacher -> change startdate for course to earlier than current date, save. Then the redline should be showing at the correct place.
OBS nr 2, (could be a problem to change starting date using firefox).
=> Fixed course year guesstimation and redline drawing

DuggaSys/diagram.js
A success-message has been added when creating a new line between two elements.
=> Success message when creating new lines

DuggaSys/diagram.js
Update displayMessage to use the passed functions instead of context
=> Update displayMessage to use the passed functions instead of context

DuggaSys/diagram.js, DuggaSys/diagram.php
fixed by creating keybinding to the key s. Now works on W18 version
=> "fixed" "Snap To Grid" button needs a keybinding

DuggaSys/diagram.js
Now the cardinality is better positioned when moving around elements and stays in place when zooming.
=> Fixed cardinality zoom and position

DuggaSys/diagram.js
The "Escape" key now detects if anything is selected and deselects  it/them, then returns to the mouseMode it is currently in. If "Escape" is pressed again with nothing selected we return to the default mouse mode.
=> Fixed "deselect all" functionality

DuggaSys/diagram.js
Made so we don't look for lines if an element has been clicked.
=> Fix so lines don't get selected behind elements.

DuggaSys/diagram.js
fixed issue 10540 - Selecting an element without holding down ctrl should deselect any selected line(s)
=> fixed an issue where selecting an element doesnt not deselect any selected lines 

DuggaSys/sectioned.js
Swimlanes should now properly hide in all browsers when there are no tests or moments in a course. Swimlanes should now also stay hidden when clicking the close/open swimlanes button multiple times. 
Note: A new branch has been used after the merge. All changes in branch G2-2021-W17-ISSUE#10403 should therefore be disregarded.
=> Swimlanes now properly hides when there are no "duggor". Issue#10403

DuggaSys/diagram.js
This means that the lines DO NOT cross each other with the most commonly used browsers.
=> Crossing lines issue. Final update to HG version.

DuggaSys/diagram.js
Added if statement so the extra step is no longer happening when fully zoomed in.
=> Fixed zoom position when fully zoomed

DuggaSys/diagram.js
Added if-statement to check if ctrl is pressed before clearing contextLine
=> Only clear contextLine if ctrl is not pressed when clicking the container

Shared/css/style.css
Moved the bottom fab-button and "back to top" button 40px to the left so they wont cover the edit-buttons.
Co-authored-by: b19wilfo
=> Moved the bottom buttons

DuggaSys/sectioned.js
We were tasked with changing the lightbulb icons, there are multiple different icons that could  be used, look in the comments for alternatives and make a change request for the best looking one (unless the current one is best).
1 (current)
2
3
4
=> G2 2021 w18 issue#10558 -> changed lightbulb icons

DuggaSys/showDugga.php, Shared/dugga.js
To test this change:
- Make sure the receipt dialog popup appears whenever you try to save a dugga/submission.
- Also check if it works when you use a URL with hash & password access.
=> Receiptbox - Remove the receipt numbers when saving a dugga #10592

DuggaSys/diagram.js
Added preventdefault() to stop the webpage from getting magnified when zooming in the diagram.
Fixed so this both works when zooming with ctrl+mwheel as well as with ctrl+"+" and ctrl+"-" on the numpad.
=> Fix: Only the diagram is magnified when zooming

DuggaSys/diagram.js
The IDs of the lines in the svgbacklayer should now remain unmodified after the determineLineSelect() is called.
=> Fix: backlayer-lineIDs value copy.

Shared/dugga.js
To test:
- Make sure every Dugga have their corresponding title once entering the dugga.
- Force the variable duggaTitle to have a faulty value, for example: _duggaTitle = "";_ or _duggaTitle = 0;_ in dugga.js, row 2009. The dugga title should then be "untitled Dugga".
=> Change the title of assignments #10629

DuggaSys/diagram.js
Moved the assignment of null to ghostelement variable to only trigger if there is nothing in the context or contextLine array.
=> Fix bug where ghostelement got removed when pressing esc

DuggaSys/diagram.css, DuggaSys/diagram.php
Now there is a grey background in the corner of the ruler
=> Added div with background on the ruler

Shared/dugga.js
Since assignments are only going to be accessed through canvas in the future and not through direct urls, there should be no issues for the fix we did, in that it stores the url in local storage when you open the assignment and redirects to it if you cannot enter the correct hash or wish not to (e.g. closing the popup window).
To test this, either access a dugga through your local installation of lenasys or through the following link: http://canvas.webug.his.se/courses/1/assignments/5 and use the admin account.
If you're having issues loading the iframes, simply open up the HTML editor inside canvas and change the address to where you have your lenasys installation folder.
Co-Authored-By: b18jacha 62884577+b18jacha@users.noreply.github.com
=> G1 2021 w19 #10720

DuggaSys/diagram.js
Change back the name of a element at escape pressed, if you have not saved the value
=> Change back name of element at escape pressed

DuggaSys/showDuggaservice.php
Changed debug to error_log.
For testing:
Go to a saved Url when you are logged in as a teacher and if you don't receive an alert with the text "Error reading course visibility" it should work as we planned. :)
=> No more error pop-window  #10695

sh/index.php
Fixed so that you are redirected to 404 page when there is no match for assignment or course. So also if you try to go directly to inde.php file you should see the error page.
=> sh/index.php now redirects to 404 error page when no match is found #10779

DuggaSys/diagram.js
Right-click should not trigger any events in the diagram now.
=> Right-click trigger disabled

DuggaSys/diagram.js
The toggle A4 button now has a shortcut
and the tooltip now also displays this shortcut when hovering.
=> Fixed A4 tooltip and keybind

DuggaSys/fileed.php
The fab-button no longers cover the pencil button.
=> Added a margin for the "fab"-button in fileed. Issue#10795

DuggaSys/sectioned.js
Please take into account that there is a bug that removes duggas from the swimlane and adds a new, empty line in the bottom.
But other than this, the autoscrolling takes you to the dugga with deadline closest to the current date. If several duggas has same deadline date you should get scrolled to the one highest up in the list.
Co-author: @a19kimgr
=> Autoscroll to relevant swimlane#10756

DuggaSys/templates/clipping_masking_dugga.js, DuggaSys/templates/dugga1.js, DuggaSys/templates/dugga2.js, DuggaSys/templates/dugga3.js, DuggaSys/templates/dugga4.js, DuggaSys/templates/generic_dugga_file_receive.js, DuggaSys/templates/html_css_dugga.js, DuggaSys/templates/kryss.js, Shared/dugga.js
**Edited since last review!**
recursiveAjax() is now replaced with a method clearing the localstorage for that dugga, then refreshing the browser. This results in a new hash being generated and stored to the localstorage. 
Also, a student gets notified whenever he/she tries to save an already saved dugga.
To try this:
- Clear local storage, enter a dugga and press 'Save' and everything should work. Now press 'Save' again. This time a popup should appear and alert that you already have a save made on this dugga.
- Next up, don't clear the local storage, exit & enter the same dugga again. Press 'Save'. The same popup should be visable.
- **Load** an already existing dugga with URL and Password. Change something on the dugga and press 'Save'. Again, the popup should appear. 
- Make sure the …
=> Make handle hash great again #10830

DuggaSys/diagram.css, DuggaSys/diagram.js, DuggaSys/diagram.php
Added replay-mode
- By pressing reply button the tool-bar, fab button and the options panel gets hidden.
- If the user presses play from the current state and forward the diagram will be displayed.
- The delay between changes is editable.
- If the replay is on last state, if press play the replay will begin from the beginning.
- When the user is exiting the replay-mode, the diagram will be restored to the state before entering.
=> Diagram: Replay-mode

DuggaSys/diagram.js
Fix error when timelimit try to check an object.
=> Fix: timelimit append on object

DuggaSys/resulted.js
Added a url to the a-tag for the hash in the "Edit student results" table.
OBS. Currently, sh / index.php? A = HASH is broken, so you will not be able to get to the right page. Just check that the url is correct when you press the hash on "Edit student results".
=> Hash in resulted.php redirect to the corresponding submission #10851

DuggaSys/sectioned.js
The dropdown menu in mobile vers should disappear if user clicks outside of it
Co-Authored-By: a19samke <62887067+a19samke@users.noreply.github.com>
=> Click to close burgermenu

Shared/css/style.css
@a18danli 
The swimlane is centered now  when its width is under 400 px.
=> Make swimlane centered

DuggaSys/diagram.js
Saving the copy-data to localstorage now instead of saving to a local array.
Also removed default cardinality "MANY"-attribute when a new line is added in addLine(). This is because when elements are pasted, the line-cardinality should be the same as the copied elements line (if a line exists that is).
=> Saving both copied elements and lines to localstorage

DuggaSys/resulted.php
The reason I can remove the accessibility checks "if (isSuperUser...)" is because the functionality of resulted.php have been changed. As a teacher, we no longer preview a dugga directly in resulted.php. We only enter it as a showDugga.php link. The same if statements are already implemented on showDugga.php.
To try this:
- Log in as teacher.
- Enter resulted.php ("edit student results" icon).
- Copy URL.
- Logout.
- Paste and enter the copied URL.
- Open console, make sure no SyntaxError occurs.
=> "Minor error is thrown, noticed when reviewed issue #10954" - #10986

DuggaSys/diagram.js
Previous lines are now deselected when copy-pasting all elements at once
=> Lines are now deselected on copy paste

DuggaSys/diagram.js
Double clicking on the container now hides the option panel
=> Double click on container hides options panel

DuggaSys/diagram.js
Now added  a zoomfact calculation to the dash array so it now has a fixed number of "lines"
=> "Fixed" Weak key underlines not scaling with zoom

DuggaSys/diagram.js
Fixed so there are no more white-spaces on lines between elements.
Should work on both normal lines and double lines.
=> Removed white-spaces on lines drawn between elements.

DuggaSys/resulted.js
The sortable table in resulted is now fixed so it can handle null values when sorting on a column. 
To test this you have to add a row in the database to the useranswer table with null values (if you do not have null values already)
E.g. INSERT INTO userAnswer (aid,cid,quiz,variant,moment,grade,uid,useranswer,submitted,marked,vers,creator,score,timesGraded,timeUsed,totalTimeUsed,stepsUsed,totalStepsUsed,feedback,gradeExpire,gradeLastExported,seen_status,hash,password, timesSubmitted, timesAccessed) 
VALUES ('235','2','1','3','2002',NULL,NULL,NULL,'2015-01-15 09:12:51',NULL,'97732',NULL,NULL,0,NULL,'0',NULL,'0',NULL,NULL,NULL,'0','E_X-FUTy','yMp0cdW',NULL,NULL);
=> Added handling of null values to sortable table

DuggaSys/diagram.js
Changes to the label text are now added to the state machine and can be undone/redone.
=> Added label changes to the state machine

DuggaSys/diagram.js
Elements are no longer completely black when pasted
=> Fixed default colors for pasted elements

DuggaSys/resulted.js, Shared/SortableTableLibrary/sortableTable.js
In sortableTable.js it is decided when these other tables should be displayed, but since they don´t seem to work as they should. I removed it and as a result the tables are no longer displayed in mobile mode.
For testing:
Log in as a teacher and go to "Edit student results" in mobile mode. Everything looks as it should (no extra table) when you drag to the right of the table to see more.
=> Table not displaying the rows correctly in Mobile browsers #11172

DuggaSys/diagram.js
The stateMachine does not save the copied and pasted elements in an array in one StateChange anymore, instead many states are created with the same timestamp.
=> Fixed the designflaw

DuggaSys/diagram.css
fixed by just replacing the pixel value from 120 px to 0 px on the "bottom" attribute
=> "Fixed" Options panel should be the same height as the diagram.

Shared/css/style.css
In issue #11214 the message of the day was overlapping with the top bar. The margin top has now been adjusted so they're no longer overlapping.
=> in the #motdArea there was a margin-top with -16px that is now changed to 16px

DuggaSys/diagram.js
Updated the generateContextProperties() function to not return wasDblClicked at the start as it was always true in case of a double click, no matter where it happened, preventing the second click from acting as a single click.
=> Fixed incorrect double click not counting as a single click and preventing properties from appearing.

Shared/css/blackTheme.css, Shared/css/codeviewer.css, Shared/css/style.css, Shared/css/whiteTheme.css
Code added so that the number and icons on the pages in codewiver do not become highligted /selectable.
=> Added code that only highligt/selects text in codviewer.

DuggaSys/diagram.php
The function for zoom reset already existed, but there was no button for it in the diagram. Made a new button and used the fullscreen svg icon that best matched the request (youtube full screen button).
=> Reset button was missing from diagram

DuggaSys/diagram.js
Issue #11184 
Updated the drawLine() function in diagram.js which handles the positioning of the white background behind the text. Implemented a way to get the width of the text through the use of canvasContext.  The width is then used to position and scale the background accordingly.
=> Fixed malpositioned background for labels

DuggaSys/diagram.js
Swaps the start element and destination element, if the start element is a relation. Fixes spacing when adding multiple lines and fixes cardinality placement.
=> Fixed incorrect positioning of cardinality variable in diagram relations.

DuggaSys/codeviewer.js
The issue is not present in the current version, however for correctness sake the change is made today.
=> Copyclipboard should never have a style of 'block'

DuggaSys/duggaed.php
Changing padding to margin removes the "hidden rectangle" that used to cover other functionalities.
=> Changed padding to margin

DuggaSys/diagram.js
Scroll will now zoom in and out and remain at the current mouse pointer coordinates. It still has some issues that occur if user moves the mouse in between zooms but it corrects itself after one zoom event. This is testable by opening any diagram and scrolling in and out, it should now remain at the same position.
What currently isn't working as intended as mentioned is alternating between move > zoom-in and move > zoom-out. However, the original issue is that when selecting a box and zooming in, the cursor moves away from the box that isn't updating it's position. Instead of updating the element position, the mouse should remain at the same place. 
If any future developer solves the issue of alternating between zoom and move, it should solve the issue about the element moving away from …
=> Scroll zoom in/out function is now mostly fixed #11058

DuggaSys/diagram.js
Enabled the posibility to select/deselect multiple elements when pressing "ctrl"+"mouse1". The issue concerned "box selection mode" but now works for all mouse modes.
=> Select/deselect evolved. issue#11455

DuggaSys/diagram.js
Changes made in function "boxSelect_update()" in diagram.js. If marked entities were already marked, They stay in the array "previousContext" instead of being added to the array "markedEntities", which fixes the odd behaviour of the issue.
=> Fixed issue #11506

DuggaSys/diagram.js
An error message will appear when trying to create a line from a element to itself.
3) Click the line tool or "6" on the keyboard
4) Create a line from a entity with itself and/or create a line from a attribute with itself, and an error message should appear
=> Error message when creating a line on the same element #11479

Shared/css/style.css
Changed transition in fab-btn-list when window is <= 600px in height. The text now doesn't overlap and is obliquely downwards instead of upwards. Also moved the fab-button so the text will always be visible.
Test this by logging in as mestr, navigate to "show files" and hover over the fab button (the yellow large round one). Then make the window smaller and hover over it again.
=> Updated fab in style.css

DuggaSys/codeviewer.js
Fixed the problem by removing the "alignBoxesWidth" call in the resize for box2 and the event that is handled in box1.
Testing is done in javascript example 2 which uses template4 (two small boxes on top of one large box). Try to resize the boxes and see if the bug remains.
=> fixed resize problem template 4

DuggaSys/fileed.js
Error was in **fileDownload()** in **fileed.js**, it set the download attribute to the filename, but as it defaults to a .txt if you only put the name in the download attribute you wont get the correct file type.
This can be fixed by removing the filename from the download attribute and leaving it blank to just indicate that the anchor tag should download. By just indicating that the anchor tag should download it will default to the filename in the filesystem which has the file type preserved together with the filename.
Illustration of how the generation was fixed below:
The generated anchor tag for mdTest.md from the code above will be the following:
**Before** : `<a href="../courses/global/mdTest.md" download="mdTest">mdTest.md</a>`
**After** : `<a href="../courses/global/mdTest.md" …
=> Fixed anchor tag download to default to filename+extension instead of only filename

DuggaSys/codeviewer.js, Shared/css/style.css
Removed boxid in displayEditExample() because it does not change an individual window-box, but rather the whole example. Removed an fault in displayEditExample() that causes an error to occur when using template 10
=> Removed faulty code #11476

Shared/css/style.css
Fixed issue#11494 by matching opacity and max-width for both .dateField in style.css.
=> Dugga deadlines are now displayed the same for all screen widths.

DuggaSys/fileed.js, DuggaSys/filereceive.php
Added two elements to allow .json files to be added to the filelink table in the database.
Further allowance of file types into the database should most likely be done via allowing file extensions in these two tables.
PS: Uploaded global files can be found in the filelink table in the phpmyadmin database.
=> Added support for uploading .json files

DuggaSys/resulted.js
Now when pressing one of the buttons in the result editor, the other dropdown will be closed, meaing that the two will no longer be open at the same time. 
Testing: Enter course as superuser/teacher -> Press button "Edit student results" (paper with pencil) -> Attempt opening both dropdowns by pressing both buttons.
=> Hide dropdownmenu when pressing the other button #11633

DuggaSys/resulted.js
added .toString() to line 333 in resulted.js to make it sure it's a string that is compared to the search term. 
Testing: Enter course as superuser/teacher -> Press button "Edit student results" (paper with pencil) -> Attempt searching. (Note: ALL things can be searched for, including dates published and hashes.)
=> Searching in the result editor now works #11606

DuggaSys/contribution.js
Fixed the error that happened on mouse over by changing the syntax of line 189 and 190 in contribution.js
=> Fixed error on mouseover in weekly bar chart

DuggaSys/contribution.js
Updated renderCommits to take into account that the data may not have the same year as the current year(2022). Instead made it so it checks if the commit happened the same year as the first date in data. Also added some text to show the user the interval date for the commit tree.
=> Updated renderCommits in contribution.js

DuggaSys/sectioned.js
Now if screen width is 430 or below, the exact time of upload will not be shown. When the width is above, the time will be shown.
To test: Enter a course with available duggas, open inspect view, push the "phoneview button" ![image](https://user-images.githubusercontent.com/102599327/163977679-a59c4690-15c3-49c4-89a1-948d71ed15bb.png), check the different widths (remember to update the page).
=> Minor layout changes depending on screen width #11646

DuggaSys/diagram.js
Problem was that "selecting element" trigger on mouse down event, and "selecting line" on mouse up event. The changes made prevents "selecting line", if an element has been clicked in "edge_creation mode".
=> Fixed clicking elements in line creation mode #11183

DuggaSys/diagram.css, DuggaSys/diagram.js, DuggaSys/diagram.php
Moved icons (Toggle grid, toggle snap to grid, toggle ruler, toggle A4 template) into options panel and changed them into buttons. 
Changed css for options panel and buttons to make it more presentable.
=> Moved icons into options panel and changed them into buttons in diagram dugga #11540

DuggaSys/diagram.js
Removed the square around the delete button, now there is only an X.
3) Click or box select any element/s
4) Click cross icon in the right upper corner of the selection box and the elements selected should get deleted
=> Removed the square around the delete button #11387

DuggaSys/duggaed.js, DuggaSys/duggaed.php
Removed function returnedSection() as I was using it to test whichever was best between that and returnedFile(). Furthermore, the dropdown now only lists json files. You can test this by uploading a global or local .json file then edit the variant of a dugga in the same course. Also added some comments describing what they do and where.
=> cleaned up test functions and now the dropdown box lists only json files

DuggaSys/diagram.js
To mark the selection of elements (not lines) a dashed box is visible for each marked object. The implementation is found in "diagram.js" -> "function drawSelectionBox(str)".
=> Box around selected element: #11396

DuggaSys/diagram.js
This is for issue #11342:
With this pull-request, there are three fixes:
**1. The zoom-buttons will now allow you to zoom towards/from the center of the screen, regardless of the position of the diagram.** 
The previous implementation was zooming towards a constant coordinate based on half the width and height of the screen (the "window" that the diagram is in), regardless of the position of the diagram. 
Consider the following example:
The size of the diagram screen is 1000 * 800.
the range of coordinates of the diagram that is currently visible is x: -1200 to 0 & y: -950 to 0.
With the old implementation, the screen would zoom towards x: 1000 / 2, y: 800 / 2, a coordinate that is not even visible on screen (because the length and height of the screen are constants, as long as you don't …
=> G1 2022 w3 #11342

DuggaSys/codeviewer.php, Shared/css/style.css
Added an event that runs when the button is clicked that offsets the button slightly, giving the user visual feedback that the button has been clicked.
Also removed the name of the Dropdown menu.
For testing:
1: In codeviewer when pressing the backwards/forwards buttons the button should offset slightly indicating it has been clicked.
2: When holding the button the dropdownmenue should not have a name.
=> Added an actionevent to the nav buttons and removed dropdown menu name.

DuggaSys/codeviewer.js
Added new clauses that check for boxW being 100( boxW > 98).
For testing:
1: Go into javascript example 1.
2: Open the inspect elements box(Ctrl+Shift+i).
3:Drag the inspect elements box so that the hamburger menue appears
4:Click the hamburger menue and pick JavaScript_Exx1.html (or Ex1.js)
5:The description box should not be hidden.
=> Added another clause that blocks this behaviour.

DuggaSys/codeviewer.js, Shared/css/style.css
Previously the edit button used the reset button class and was therefore hidden in template 10 along with the resize button where no resize capabilities should exist.
=> Gave a unique class to edit button #11536

DuggaSys/contribution.js, DuggaSys/contribution.php, Shared/dugga.js, Shared/resetpw.php
Its on its good way to be completed but it is not completed as of yet, the changes made however will only affect contribution.php if you arent logged in and shouldnt break other parts of the system.
Changed resetpw.php to handle more states of "user creation"
contribution.js changed to add UI functionality for this special case of contribution login.
dugga.js changed to add functionality of special cases to login-change-password case when you are in the pending/revoked states.
One quite special thing which might cause problems for other parts of the system can be how i handled the column requestedpasswordchange in the user table; at the moment it is a tinyint when i assume it should have been a boolean, however because it is a tinyint this allows me to store **more** …
=> Adding functionality for creating new users from git login and password popup for contribution.php #11416

Shared/css/style.css
Fixed the issue with not being able to keep fab-btn up when hovering. The issue appears to be a a miscalculation. the fab-btn got a margin of 30 but the fab-btn-list got a margin increase of 35 which meant there probably was a gap of 5 pixels which would count as no longer hovering over the element thus hiding the option.
Related to this issue 
https://github.com/HGustavs/LenaSYS/commit/ce8e8a92e0f705285ce4ff79f46c1e3edef378e8
The problem is because of this change
=> Fixed fab-btn not staying up when hovering

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/duggaed.js, DuggaSys/duggaed.php, DuggaSys/templates/diagram_dugga.html, DuggaSys/templates/diagram_dugga.js, Shared/dugga.js
changed diagram.js mainly in showDiagramTypes(), diagram.php, duggaed.php, duggaed.js mainly in createJSONString(formData) and diagram_dugga.js. added checkboxes to the duggaed interface and added that the diagram types changes depending on what checkboxes was checked when creating the dugga variant.
test by:
-logging in as toddler
-go to demo courses 
-click show test 
-click the pen on the same line as Diagram Dugga 
-select an enabled existing variant by pressing the cogwheel on the same line
-change the checkboxes to select the types allowed
-press update
-log out
-go to diagram dugga
-look at the availible entitys
-repeat to test different types
=> fix for issue #11643 Teachers should be able to select which type of diagram the student are able to draw in diagram dugga's.

DuggaSys/contribution.js
Code was mixing up " and `, leading to variables being included in the string.
=> Repaired broken string generation

DuggaSys/contribution.js, DuggaSys/contribution.php
Solution for https://github.com/HGustavs/LenaSYS/issues/11786 and submission of https://github.com/HGustavs/LenaSYS/pull/11798
Changed from a position: sticky to absolute which means that the webpage won't lengthen when hovering over a commit link. The position is then changed to where the user is on the webpage when hovering over a commit link.
=> Made the commitDiv function better

Shared/css/codeviewer.css
Changed the position to static from absolute.
This makes it so that the textwrapper will take up all the space available to it instead of taking up all the space it needs to display the text.
For testing: 
1: Go into "Javascript example 1" (Or any example that has a significant amount of text in it.)
2:Go into inspector(Ctrl+Shift+i).
3: Activate select element(Ctrl+Shift+C)
4: When checking the "Normtextwrapper" it should cover the entire box.
5: When selecting text you should be able to do it far away from the text.
=> CHanged the position of the textbox to static.

Shared/css/style.css
Updated the distance between the FAB icon (yellow icon with a + inside at the bottom of the page) and the content that is displayed when hovering over FAB.
**For testing:**
1. Switch to the group branch.
2. Login as stei
3. Go to: [this_link](http://project-g2.webug.his.se/DuggaSys/sectioned.php?courseid=1&coursename=Webbprogrammering&coursevers=45656)
4. Try to create a new example with the yellow icon at the bottom of the page.
5. Repeat the process with the branch: G2-2022-W4-#11727
6. See if the items disapear when you try to hover over them. If not, the bug is fixed.
=> G2-2022-24-#11727

DuggaSys/contribution.js
Creating a multi-level dropdown menu was too complicated and I was unable to find a solution in time, so I made a quick fix instead where the course dropdown is hidden until a year is selected.
To test:
1. Go to http://127.0.0.1/LenaSYS/DuggaSys/contribution.php
2. Verify that there is no visible "Choose Course" button (to the right of "Choose Year")
3. Select a year in the "Choose Year" dropdown menu
4. Verify that the "Choose Course" dropdown menu is now visible
=> Hide course dropdown menu until a year is selected

DuggaSys/contribution.js
Fixed the onclick function for the `rankTable` and the `ghContribTable`. The previous version used the same `renderSortOptions` as `myTable` which meant that the function was trying to sort on the wrong table. Also had to add the `compare` function which is called to sort the table by `sortableTable.js` since it was missing from `contribution.js`. The compare works for sorting ints and strings but not for arrays so i added the functionality of handling those arrays to the compare function.
Sorting `rankTable` by Kind 
Sorting `rankTable` by Number 
Sorting `ghContribTable` by GitHub Contributions
=> Fixed onclick function in contribution.php

DuggaSys/diagram.js
Issue: #11549
Changed the opacity of the ghost element from 0.5 to 0. In other words, the ghost element is still there, but it is invisible. The "ghost lines" should still be visible. It seems to me that the ghost elements are not only visible features but also have a functional purpose. I didn't find any other solution without breaking parts of the system.
Test by selecting one of each element and see if the ghost appears before placing it. Only the lines should be visible when attaching it to the first object.
=> Solution for issue #11549

DuggaSys/diagram.js
Move multiple objects by pressing down mouse inside selection box or an element inside the selection box. Works for 
the mousemodes: "POINTER" and "SELECTION_BOX".
All changes were made to "diagram.js" in the following methods: "mdown()", "ddown()", "mup()", "drawSelectionBox()".
=> Fixed issue #11667. Moving elements inside "selection box"

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/duggaed.js, DuggaSys/duggaed.php, DuggaSys/templates/diagram_dugga.html, DuggaSys/templates/diagram_dugga.js
changed diagram_dugga.
Student version
Teacher version
test by:
-logging in as toddler
-go to demo courses
-click show test
-click the pen on the same line as Diagram Dugga
-select an enabled existing variant by pressing the cogwheel on the same line
-change the checkboxes to select the types allowed
-press update
-log out
-go to diagram dugga
-look at the availible entitys
-log in as teacher and look at the icons for entitys and relations
-repeat to test different types
=> fix for issue #11748 Check if possible to create default toolbar in diagram dugga to show teachers when they are logged in.

DuggaSys/duggaed.js, DuggaSys/duggaed.php
The dropdown box for selecting json diagrams is now hidden when the selected dugga is not of diagram type as per stated in issue #11614 ,
=> Dropdown boxes are now hidden when selected dugga is not diagram #11614

Shared/css/style.css
Removed the top margin from the message of the day so no more white space is visible above the message of the day banner. #11799
=> Removed the top margin from the message of the day

DuggaSys/diagram.js
If line label is clicked, the entire line is selected on mouse up.
=> Select line if label is clicked #11813

DuggaSys/sectioned.js
All duggor now have a button that will open the link in a new tab but Github and Youtube links will always open in new tab if you directly clicked on the dugga row. Also changed the Show Canvas Link button to no longer just show "This is a test link" but now it displays the link for the dugga.
=> Github and Youtube links now open in new tab and all objects have new tab button #11229

DuggaSys/diagram.js, DuggaSys/diagram.php
Issue: #11233
Sub-issue: #11744 
I have added a new button (that is currently using the same icon as another button) in the diagram toolbar. This button toggles the generation of the ER-table. If it is toggled ON, "Properties" in the option panel will display the ER-Table for the current diagram. 
The ER-Table is generated by a single function that returns the entire ER-Table in the form of a string. Therefore, it is safe to call the function wherever it is needed, as long as the code in the function is not edited.
This pull request DOES NOT feature:
* Recognition of keys
* Recognition of foreign keys (through relations)
* Removal of parent attribute (if an attribute has other attributes connected to it)
* Recognition of strong/weak elements
How to test:
1. Press the Options side-panel. …
=> Foundation for dynamic/automatic ER-Table generation

DuggaSys/codeviewer.php, DuggaSys/duggaed.php, DuggaSys/fileed.php, DuggaSys/resulted.php, DuggaSys/sectioned.js, DuggaSys/sectioned.php
Added titles and placeholders to inputs missing them. Used lighthouse dev tool in order to audit webpages and fixed forms that were missing labels. For input types checkbox and dates i used titles so when the user hovers over the input they get a description of it, for input types text i used placeholder to display text if the input is empty. For resulted.php it was possible to use the label element since they were already in place but in other places it would have been difficult to do so without altering the look of the webpage significantly.
There is most certainly inputs still missing labels on some webpages. I did not fix forms on webpages such as the showdugga.php pages. I also noticed other issues in the lighthouse tool but i did not alter them since they are not a part of this …
=> Added labels to input elements missing them

DuggaSys/duggaed.js, DuggaSys/duggaed.php, Shared/css/style.css
Added code so that the button does not flex-wrap and so that the row doesn't overflow. I also made the "Answer" box smaller alongside margin corrections on correct elements so that the elements would fit properly on smaller screens.
Compare with #11728.
=> Added code so that the button does not flex-wrap and so that the window is appropriate for smaller screens.

DuggaSys/diagram.js
Added so that the labels can be detached and that the label gets updated continuously. Missing is that it follows the line when not close to center and that it is still possible to drag the label to close to the ends of the line.
worked in diagram.js mainly in updateLabelPos(),drawLine(),calculateLabelDisplacement() and displaceFromLine().
https://user-images.githubusercontent.com/81320323/165539893-757f45fe-106c-4194-abf7-5ac571153f99.mp4
Test by adding a label to a line and moving it.
=> improvement for isssue #11155 Select & Move labels in diagram

DuggaSys/diagram.js
Changed redirect camera to center so the zoomfactor is set appropriate to the size of the diagram. #11822
3) Change the size of the diagram and click Redirect camera to center.
=> Redirect camera to center changed

DuggaSys/sectioned.js, DuggaSys/sectioned.php, DuggaSys/sectionedservice.php, Shared/SQL/init_db.sql, Shared/css/style.css
Added a simple design (subject to change in the future)
Added functionality to take the values of the design and input it into the database
Added functionality so that when the page loads the database values is used in the settings menu for each dugga
Added a column for the table quiz in the database
This is a simple implementation of the functionality to store and fetch relative deadlines. The relative deadlines does nothing as of right now and the design and value of the relative deadlines are subject to change. It is implemented in such a way that the relative deadlines can be stored as we choose to and up until the point where we translate these deadlines into real dates can the design be changed freely without interfering with the functionality of storing them in the database.
To …
=> Simple design and functionality for relative deadlines

DuggaSys/contribution.js
The wrong userid was used for the ajax which meant that instead of getting the current user the ajax was sending the option selected in <select id="userid> button which is  "select Git user". 
Also fixed a problem with the "showing activities for period" string displaying undefined dates if the user hadn't selected any dates for a user. (issue recreation: refresh page -> select HGustavs -> the hourly activites string will look as shown below without the fix)
=> Fixed broken show selected dates in contribution

DuggaSys/contribution.js
Updated the compare function so that when  the column is number the value of a and b will be parsed as integers. This should fix the problem of the sort being incorrect on the web-server since they were treated as strings previously.
=> Changed how number is sorted in contribution on the web-server

Shared/dugga.js
Refreshing or leaving a dugga would warn the user that any unsaved changes may be lost even if no changes had been made. This message should now only appear if the user has clicked any of the dugga buttons at least once.
To test:
1. Open any dugga in the demo course.
2. Before clicking anything, refresh the page. There should not be a confirm message.
3. Click any button related to the dugga, then refresh the page. There should now be a confirm message.
4. Try other buttons unrelated to the dugga. There shouldn't be a confirm message when refreshing.
=> Added a check to only create an alert box if the user has clicked a button

DuggaSys/sectioned.js
Commit 1: Fixed the incorrect syntax for creating class names and some steps to solve this issue.
Commit 2: Made it so that the checkbox for the section and moment kinds also adds all the elements under them to the hideItemList. Still need to fix the visual for this problem since there is no indication that the sub elements are selected.
Website + console view of solution.
Selecting and unselecting items.
The incorrect class syntax:
The syntax fix: (There is an empty space afterwards because the value hideState is null when not hidden. When hidden it will be something like class="section hidden")
=> G3 2022 w5 #11956

DuggaSys/contribution.js
- Fixed the issue of the side bar changing to display:none; when pressing escape by changing the style.display to "inline-block". 
- Made it possible to open and close the side bar using escape. 
- Also made it possible to open account request by clicking the hide-accountRequest-pane instead of only the span.
- And made it so clicking on anything not belonging to accountRequest-pane will close the menu
=> added more account request bar click functionality

DuggaSys/duggaed.js
When viewing variants in localhost they're no longer listed as undefined
=> Variant status are no longer "Undefined"

Shared/SortableTableLibrary/sortableTable.js, Shared/css/style.css
Fixed the issue of columns changing sizes when searching by hiding filtered columns rather than removing them. Fixed a subsequent issue caused by this change that alternates the row colors with javascript code directly rather than using code in style.css. This appears to work well for duggaed.php, fileed.php, and resulted.php, but further testing may be necessary to prevent unintended bugs.
To test:
1. Go to any table that can be filtered by typing in the search bar (ex. duggaed.php)
2. Enter a search term. The column sizes should remain the same when the table updates. Note that the table width itself may change size if a scroll bar appears/disappears in the browser window as a result of the change in size of the table. This could be a separate issue but may be unavoidable.
3. Look at …
=> Made columns sizes remain consistent when searching. Changed code related to the alternating row colors.

DuggaSys/duggaed.js
Added the functionality to search in columns other than qname and quizFile. It should now work for columns `"did(index)", "Name", "Template", "Deadline", "Result date", "Last modified"`. It might also work for `"Autograde", "Gradesystem" and "Startdate"` but i couldn't test it because the values in those rows were null on the page i tested. When searching it looks for all matches in any of the columns so it can match the term "dugga" with both the name and template column. It also possible for search for multiple terms using "&&" for example `"dugga&&html"`.
Code is taken from `function rowFilter(row) {` in **filled.js.**
=> Made it possible to search multiple columns

install/SQL/testingCourseData.sql, install/install.php
The installing script of is LenaSYS now working on Mac while running it from Safari or Firefox. The problem will probably remain while using Chrome though.
For testing: 
Run the install script on Safari, Chrome and Firefox on MacOS and see if this error message will occur when navigating to the tesing course:
https://user-images.githubusercontent.com/102605031/166209902-40dc38f7-cc92-4a2b-8962-1c8285077795.png 
Issue:
https://github.com/HGustavs/LenaSYS/issues/11875
=> Including the new testing-page while installing locally only works on windows machines #11875

DuggaSys/codeviewer.js, Shared/navheader.php
The navigation header recognizes write access. And fileedButton is only updated if it exists.
=> Fixed navheader access #12011

Shared/css/blackTheme.css, Shared/css/whiteTheme.css
The "announcementBoxOverlay" ID had no dark mode styling. Therefore, id was added to both whiteTheme.css and blackTheme.css and changed to the correct color.
=> Added an ID in both whiteTheme.css and blackTheme.css files.

Shared/css/style.css
Should a box overflow it will now be hidden instead of adding a scrollbar to the div2 container.
For testing:
1: Php example2 should no longer have a scrollbar on the div2 container.
=> Added overflow handler to div2 container.

Shared/css/style.css
The background color has a grayer shade than the other fields, as it should not be touched by developers / teachers.
=> Added a new background color

DuggaSys/duggaed.js, DuggaSys/duggaed.php, DuggaSys/showDugga.php
possible fix for the file fetching problem in issue #11920
changed the string split to fetching from an array with key.This branch is based of the presentation branch. Changed in showdugga.php at rows 73-79 and duggaed.js.
For testing:
- Start by uploading a diagram file if you haven't before.
- to upload a file:
- - log in as toddler
- - go to demo courses
- - click the electrical plug in the nav bar
- - press the yellow plus and select where you want your file (anywhere should work)
- - select your file
- - if you don't have a diagram json file:
- - 1. go to diagram dugga and change the diagram
- - 2. open options 
- - 3. click export
- - click the upload button
- change the diagram file of the currently enabled variant.
- to change variants:
- - log in as toddler 
- - go to demo …
=> possible fix for the file fetching problem

DuggaSys/codeviewer.js
There were two instances of the template resizing. this caused the bug.
For testing:
1: enter the codeviewer.
2: enter codeexample "Javascript example 1"
3: The box in the bottom right should no longer have an opacity style applied to it.
=> Removed duplicate event.

DuggaSys/diagram.js
Changed cursor to "grab" for Pointer mousemode.
Changed cursor to "default" for Edge_creation mousemode.
Cursor switches to "pointer" when mouse hovers over elements and lines in all mousemodes.
Cursor switches to "pointer" when mouse hovers over selection box and delete button for Pointer and Selection_box mousemodes.
Cursor switches from "grab" to "grabbing" when moving the canvas for Pointer mousemode.
=> Updated cursor style with responsive behavior in diagram.js #12001

Shared/css/blackTheme.css, Shared/css/whiteTheme.css
The "announcementBoxOverlay" ID had no dark mode styling. Therefore, id was added to both whiteTheme.css and blackTheme.css and changed to the correct color.
(Pull request was re-made as it was commited into master and reverted.)
=> Added an ID in white and black Theme.css file.

DuggaSys/contribution.js, DuggaSys/contribution.php, DuggaSys/contributionservice.php, Shared/dugga.js, Shared/sessions.php
We will have to further work on also handling a teacher login on contribution.php but we also have to further work on what is loaded for every git user, the current logged in git user is stored in the session variables : 
Please check 
for how we check if the git user is logged in
the contributionservice.php has a new function for logging git users in differing from the normal login.
----------------------- Testing -----------------
Test this by trying to log in with for example "proci" and password "password"  on conttribution.php
to logout the feature is not yet implemented so you will have to type in console git_logout() to logout the git user
information might not load correctly if you are logged in yet as only the login has been fixed and not what is associated with that git login
=> Log in for git users is now somewhat implemented/the groundwork is laid

DuggaSys/templates/curve-dugga.js, DuggaSys/templates/daily-minutes.js, DuggaSys/templates/dugga1.js, DuggaSys/templates/dugga2.js, DuggaSys/templates/dugga3.js, DuggaSys/templates/duggaTest.js, DuggaSys/templates/feedback_dugga.js, DuggaSys/templates/group-assignment.js, DuggaSys/templates/html_css_dugga.js, DuggaSys/templates/html_css_dugga_light.js, DuggaSys/templates/kryss.js, DuggaSys/templates/placeholder_dugga.js, Shared/dugga.js
DuggaTitle was missing or invalid in the as an argument when calling the funciton displayDuggaStatus(), from the dugga some of the dugga templates in their returnedDugga() function.
This still only works aslong as the dugga is loaded correctly since it requires data from an json file coming from an AJAX thing.
To test open a dugga while not logged in, not in demo course. Dugga Title Should now appear at the top if the dugga was loaded correctly.
=> duggaTitle argument missing or invalid.

DuggaSys/diagram.js
To test this you go to edge creation and draw a line between objects. No box with delete button should appear when objects are selected. Switch between other modes to see the difference.
=> Removed delete button from edge creation. Issue #12104

DuggaSys/contribution.js, DuggaSys/contributionservice.php
Fixed so you can log in with the users from the "USER" table and not only "git_users" table
Added so if you exist on the "USER" table but dont have superuser status youre not allowed to login, this can be changed so all users on the "USER" table are allowed to log in with more priviliges than a normal git-student user. This is how it looks if you attempt to log in with a non super user
If you now try to log in with a user that exists on the "git_user" table youre allowed to but your stored session variables dont get stored in the same variables as a teacher/super/one who logged in with someone who exists on the "user" table. The rest of the contribution file will need to take this into account for what is shown; Following is an example of where the user who logged in with the "git_user" …
=> Implemented teacher & user login for contribution.

DuggaSys/duggaed.js
When testing variants on local webserver, they're always "Undefined". It works fine on the production but can prove troublesome when testing variants locally. Now they're "Enabled" and Disabled"
=> Variants are no longer Undefined by default on localhost

DuggaSys/diagram.js
Now you can close the options menu even if an element isn't selected. 
Also enabled the ability to double click the canvas in pointer mouse mode to show the option menu.
To test: Try opening and closing the option menu in different mouse modes; with one, many and zero selected elements.
Also open and close the option menu by double clicking the canvas in pointer mouse mode.
=> Fixed option pane issue #12127

DuggaSys/duggaed.js
- #12179
Added code so duggor and dugga variants can be deleted by pressing enter when the delete confirmation-box is visible, in "Edit dugga".
1. Log in as a teacher
2. Go to "Edit dugga"
3. Press diagram dugga (or any dugga, code works for all of them.)
4. Create a dugga in "Variants for:  Diagram Dugga" if there isn't already one present.
5. Press delete by clicking on the bin
6. When the delete confirmation box appears, `**use the ENTER key!**`. 
7. Make sure the variant or dugga got deleted.
=> Allowed for duggor and dugga variants to be deleted by pressing enter #12179

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/templates/diagram_dugga.js
Added a button in diagram.php and a function in diagram.js.
Test by creating an error in the diagram and turning on/off error checking by pressing the button.
- Fix for issue #12238
=> Fix for issue #12238 Create a button for turning on off the error checking

DuggaSys/duggaed.php
This pull request contains:
- #12181
- Set a minimum height on uploaded diagram window so it doesn't shrink when adding more submisson types leading to less  frustration when scrolling.
- Also removed the margin that was between "Diagram types allowed" and "Submission types".
Test by:
1. Log in as teacher
2. Go to "Edit dugga"
3. Click the pen on Diagram dugga 
4. Add submission types by pressing the (+)-button
5. Make sure that uploaded diagrams window doesn't shrink. 
6. Make sure there is no margin between "Diagram types allowed" and "Submission types".
*Note that it does make a little "jump" when the first submission type is added, the reason for that is the scroll being added to the side.
=> Fixed so "Uploaded diagram"-window doesn't shrink anymore so scrolling isn't as frustrating #12181

DuggaSys/duggaed.js, DuggaSys/duggaed.php, Shared/dugga.js
#12201 
- Made adjustment to the feature that creates dropdowns so an empty option is shown. Since this solution is global and can be used by other dropdowns as well, if the if-statement is correct, we named it "Nothing selected" instead of something related to an empty canvas or demo data.
- Before what was shown in the dropdown was added in "diagram_File":"", which caused issues when we named the empty option "Nothing selected". This was solved by adding a value which for "Nothing selected" is empty and for the JSON files is the file name. 
**How to check solution**
Go to Edit dugga and select the diagram. There try to switch between options in the dropdown and check so that it updates as it should in the parameter section. 
There might still be an issue with what …
=> Empty dropdown option in "Add diagram to dugga". #12201

DuggaSys/diagram.css
Made it so messages will not hide behind pasted elements. #12196 
3) "Copy"(ctrl + c) any element/s
4) "Paste"(ctrl + v) anywhere on the screen
5) Drag the pasted element/s towards the message in the down left corner of the diagram (if the elements are behind the message, it is correct)
=> Pasted elements do not cover messages

DuggaSys/diagram.js
Now when UML relations are double clicked the options menu will show.
To test: Try double clicking UML relations, both disjuct and overlapping, try the other elments to.
=> Double click UMLRelations fixed #12203

Shared/css/style.css
- Added a margin at the top of the submitButtonTable to increase the distance between the buttons and the diagram dugga iframe as Henrik requested.
Result should look as the image below.
**Notice:** Solution had to be implemented in style.css which affects the whole LenaSYS page.  Therefore I've also checked multiple other dugga pages to see how the change affected these pages and my conclusion is that the change is so minimal that it doesn't affect them in a bad.
=> Move load, save and load dugga button further down on page. #12143

DuggaSys/contribution.js
Changed it so that empty lines of code no longer show in the list. Instead empty lines are counted and the total amount is displayed at the end of the section.
Before
After
=> Updated commitDiv to not show empty lines

DuggaSys/sectioned.js
All headers (and other items) should now delete properly. Changed the behavior slightly so that all items are deleted at the same time, and the timer refreshes every time an item is set to be deleted. This means that if you press the delete button on one item, wait 50 seconds, then press to delete another, the timer will be reset back to 60 seconds. After 60 seconds, both the items are deleted at the same time.
To test:
1. Create a couple of headers.
2. Delete as many as you want.
3. 60 seconds after the last item was set to be deleted, all items should delete. The table will briefly reload when this happens. However, there is no message. You can see when this happens by looking in the console log.
4. Only the headers you set to delete should be gone. The deleted headers should still be …
=> Prevented deleted headers from reappearing

DuggaSys/diagram.php, Shared/icons/diagram_errorCheck.svg
- #12241
- Note for the tester: this branch name is 12241**a**. Don't forget the "a".
=> Created and added an icon for the new error check functionality and changed the title #12241

DuggaSys/sectioned.js
Added an if-statement to skip headers with style.display set to "none".
To test:
1. Go to Demo Course
2. Create a new header
3. Delete the header
4. Click the checkbox on the top of the table to select all
5. All checkboxes down to the next visible header should be selected. Any deleted (hidden) headers should be skipped.
=> Checkboxes should now skip invisible headers

DuggaSys/diagram.js
Related to main-issue #11744 
and sub-issue #12158 
The user can now edit the type of keys on attributes. Note, the previously type namned 'key' is now split into two categories and are called 'candidate' and 'primary'. If an attribute is primary, only the primary keys will have underlines in the ER-table. If no primary keys are present all candidate keys are underlined instead. 
Also note that multiple primary keys and / or candidate keys can exist on the same attribute, this it to allow the user to learn by misstakes and not stop possible misstakes.
To test:
- Try adding more primary keys to an entity. Check if only primary keys are underlined in ER-table.
- Try adding more candidate keys to an entity and one or more primary keys. Check that only the primary key is underlined in the …
=> Added ability to choose between candidate and primary keys #12158

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagramkeybinds.md
- #12277
**Make sure that you have pressed inside the diagram iframe first**
1. **Hover over the functionalities "Replay mode" and "ER-table". Make sure that the keybinds are present.**
2. **Try the replay keybind by pressing "r". Make sure that the replay mode is enabled/disabled.** 
3. **Try the ER-toggle button by pressing "e".** 
- Make sure that an ER-entity is **selected** and the option panel open. 
- Note: that the option panel doesn't automatically open since you won't be able to toggle between the table and the other functions if that were the case.
=> Created working keybinds for two functionalities #12277

DuggaSys/contributionservice.php
If/when we need to look at contributions data other than the late spring course 2019 this will now be much easier. On line 63 and 64 are two strings that represent the start date and end date of our data collection. When we want another course date we just need to edit these two strings and all sql queries will change search dates accordingly.
=> Made all dates dynamic rather than static in the contributionsservice.php file

DuggaSys/diagram.css
Issue #12140  (Please note that I missed # in the branch name when you switch to the branch). 
- Added so that the minimized option panel can be clicked anywhere to view the option panel.
- Adjusted the tooltip so that it still is aligned as it should.
In the diagram dugga check if it works to open/close the option panel by clicking anywhere on the marked part in the image below.
In my test, this still worked when resizing the page using the browser zoom.
=> Option panel open and close functionality #12140

DuggaSys/sectioned.js
both when logged in as teacher and as guest the buttons dont show up on headers/moments anymore.
=> Buttons nolonger created on headers

Shared/navheader.php
Removed an onclick function that was called twice. Tested on Chrome and Firefox and seems to work as intended.
=> Removed one onclick that was called twice

Shared/loginbox.php
Added dark mode background & text on "Forgot password?" page.
The yellow text on white background while hovering will be fixed once the hovering color has been adjusted globally in dark mode.
=> Dark mode on forgot password page.

DuggaSys/sectioned.js, DuggaSys/sectioned.php
Before when you edited the current course it showed an error in "version name" even though it was correct according to the standards. This is fixed for both when you add new courses and when you edit existing courses.
=> Fixed error in "Edit course" version name #12202

DuggaSys/sectioned.js, Shared/dugga.js, Shared/navheader.php
As per the issue, the MOTD button should be removed.
The botton is refered to as messagedialog. Any mentons of this button has been removed.
For testing:
1:Enter the webprogrammering course.
2: The message of the day banner should be there.
3: Pressing x on the banner should close it and no MOTD buttons should appear in the navbar.
=> Removed the MOTD button and any mentions of it.

DuggaSys/sectioned.js, Shared/css/style.css, Shared/icons/collapse_icon.svg, Shared/navheader.php
When resizing the window, to very small the icons seem to move around a bit. To solve this I added home, return and darkmode to the teacher burger menu when the screen is smaller than 320px in witdth. The problem is that you need to a teacher to have access to this menu. I therefor added a new burger menu that contains home, return and darkmode. This only appear if you are not a teacher and the screensize is less then 320 px.
**For testing:**
**1.**  Log in as stei and navigate to webbprogrammering.
**2.**  Open the inspect window (ctrl+shift+i) and make the inspect window very small.
**3.**  Open the hamburger menu which should now contain the home, return and and darkmode functions.
**4.**  Next, log out and see if another hamburger menu should appear. 
It should look like this:
=> Added home, return and darkmode to burger menu.

DuggaSys/diagram.js, DuggaSys/duggaed.php, DuggaSys/templates/diagram_dugga.js
Added so the techer can choose if the error checking button is shown.
For testing:
When logged in as teacher, no variant is selected, no variant exists or error check button is deaktivated it should look like below
if error check button is deactivated it should look like below
- #12239
=> Fix for issue #12239 Hide the button to turn on of error checking when error checking is not allowed

DuggaSys/diagram.js, DuggaSys/diagram.php, DuggaSys/diagramkeybinds.md
This pull request contains:
- Added the keybind "h" for _help_ to the error check functionality 
(and corrected some errors in diagramkeybinds.md and added a comment in the code).
- #12360
1. Press on the _Ssn_ attribute attached to the _Employee_ ER-entity
2. Open the option panel
3. Change the variant from "candidate" to "weakKey" and press save.
4. Press "h"
5. Make sure the boxes turn red/not red- enabled/disabled
=> Created a working keybind for the new error check functionality #12360

DuggaSys/templates/diagram_dugga.html
**To make it easier have a duplicated tab opened of the g1-project webserver with and without the branch to preview the changes more clearly.**
- Fixed so the arrow doesn't overlap the scrollbar
- Arrow flips when description is opened/closed.
- Animation is smoother as the arrow now follows the open/close animation of the description.
- Before the arrow scrolled outside of the screen when zoomed in/out but is now positioned absloute in one position in the middle.
1. Make sure that the arrow doesn't overlap the scrollbar:
2. Make sure that the arrow flips when opened/closed.
3. When opening and closing make sure that the arrow doesn't jump from one place to another but rather follows along the animation when opening and closing the description.
4. Zoom in/out (outside the diagram, making …
=> Fixed the arrow functionality in diagram dugga #12316

DuggaSys/diagram.js, DuggaSys/diagram.php
Now it is clear how to export a diagram with or without history. It was asked that a teacher should be able to do this, so that the student shouldn't be able to replay the teachers progress.
To make this functionality more obvious we changed the names under the export button in the options menu.
To test this you can make changes to a diagram; save with and without history; upload those diagrams and see the difference when using replay.
=> Teacher history not visible in replay for student: #12145.

DuggaSys/showDugga.php, DuggaSys/templates/diagram_dugga.js
Added some exception handlings so it won't try to fetch any files for default variants. This wouldn't have been a problem on the production, I suspect, but proved difficult for testing. Now when opening any dugga regardless of variant parameters, it should not give an error for undefined variables.
=> User no longer gets prompted to press OK multiple times when opening dugga

DuggaSys/diagram.js
Problem was a typo how ERRelations are drawn in function drawElement().
To test: Draw a line from different elements, ERRelations shouldn't turn black anymore...
=> ERRelations no longer turn black in EDGE_CREATION #12391

Shared/css/blackTheme.css
The background color in darkmode for codeviewer text and textwrapper are now the same shade.
Testing:
1) Enter Webbprogrammering
2) Open any code example
3) Enter darkmode
The codeviewer should look like this:
And not like this:
=> Fixed consistent darkmode background color #12386

Shared/css/style.css, Shared/navheader.php
"access" div box is now the correct size and burger menu is now displayed in other browser widths.
Testing:
1) Logged in as stei
2) Enter Demo-Course
3) When resizing the window width the icons in the navheader should not go outside of the navheader and appear under it.
=> Fixed navheader and burgermenu ranges #12420

Shared/navheader.php
The removal of this was not included in the week 7 merge. Removing it again.
For testing:
1: Enter a course.
2: The message of the day should still pop up but there should not be a button.
=> Removed MessageOfTheDAyButton

Shared/icons/Home.svg
made the house / home button bigger in the global navigation bar, changes were made in the original file to match the other icon implementations.
Testing:
Go to any page where the global navigation bar can be seen.
Home button looked like this before:
Should on this branch be larger and look something like this:
=> made the home button bigger in original file to match the implementation of the other icons

DuggaSys/codeviewer.js
The preview window is now fetched directly from fileed and display as a single window instead of being a iframe window of the fileed page.
Testing:
3) Open PHP Example 1
4) Click on "Edit file"
5) The preview window from fileed should be displayed as a single window
6) The preview window should behave like other windows
7) The other windows should also behave the same as before
=> Preview window is now shown as a single window #11605

DuggaSys/diagram.js
#12462
**What has been made**
- Fixed typo error which caused outer line on normal attributes and multivalued attribute to look thinner.
- Removed stroke from element values as the value is no longer in use. (Might cause programmers confusion in the future if it stayed).
- Changed black stroke colour to websafe dark colour. 
- Changed so that errorReset doesn't use by default a black, but instead gets stroke colour from the variable list.  
- Fixed so that the weak key also changes to white when multiple objects are selected. Also fixed so that it changes back when unselected. 
Open the diagram and make sure you have an attribute with a weak key. For example Name in image below:
Then select this attribute together with at least one more attribute. The dashed underline …
=> Colours not working properly for all elements. #12462

DuggaSys/codeviewer.js
The appearance of the zooming buttons now behave intuitive.
The Zoom In & zoom out buttons now grey out when they are no longer clickable. 
Pressing the opposite button of a greyed out one will make the other clickable. 
The reset button will make both buttons press-able again.
**This issue can be tested by:**
1. Open a code example, preferably one with files ready.
e.g Webbprogrammering -> JavaScript Example 2.
2. Pressing the zoom in button will make the text larger up until the max font size has been reached.
3. Whenever the max font size has been reached the zoom in button now gets greyed out.
4. Press the opposite zoom button, Zoom in button is now clickable.
5. Max zoom again.
6. Press reset button and the button gets clickable again.
7. Repeat steps 2-6 for the Zoom out button.
=> Greyed out zooming buttons when no longer clickable. 

DuggaSys/showDugga.php, DuggaSys/templates/diagram_dugga.js
Added proper error handling for variables regarding fetching of diagram .json files, instruction files and general error information. By adding any type of variant to a diagram dugga, there should be no error message popup, and if the .json file is undeclared, should load in the standard demo-data as a diagram.
To Test:
1. open diagram dugga.
Note: To completely test, all combinations of variant params should be checked. However, this would take a long time and could instead be done with two tests, one where each field contains something, and one where all fields are empty.
=> Fixed multiple variables generating error alerts when opening diagram dugga #12458

DuggaSys/diagram.js
Added exception so lines can be drawn between two UMLEntities.
To Test: Try to draw lines between two UMLEntities - This should be possible. 
Also try to draw lines between other elements of the same kind - This should not be possible, except for ERAttributes.
=> Lines between UMLEntities #12481

DuggaSys/diagram.js, DuggaSys/diagram.php
The error check field gets hidden when error checking is turned of. #12409 
3) Turn off error checking with a teacher through dugga variants
4) Check if the error checking field disappears when error checking is turned off.
=> The error check field gets hidden

DuggaSys/templates/diagram_dugga.html
- #12408
- In this pull request i changed the appearance of the instruction-panel so it follows the standard look as the "General information"-panel.
Open: <img width="282" alt="before1" src="https://user-images.githubusercontent.com/81613484/168049852-9534b126-9f1d-46da-b3b4-9cf995686e18.png"> Closed: <img width="151" alt="before2" src="https://user-images.githubusercontent.com/81613484/168049861-4f9e7a4b-a24b-4c2d-897f-26d66aa1524c.png">
Open: <img width="189" alt="after1" src="https://user-images.githubusercontent.com/81613484/168049881-10a25dda-8e69-4b66-bbf6-e9e5b5053cf7.png"> Closed:  <img width="105" alt="after2" src="https://user-images.githubusercontent.com/81613484/168049891-7c415ac8-6302-437d-a6c0-ba4e4e9ec0a5.png">
- Make sure the description is hidden/visible after pressing …
=> Fixed so that the instructions-panel follows the standard #12408

DuggaSys/duggaed.js, DuggaSys/duggaed.php
Instead of having to manually enter the filename, they can now select them from a dropdown based on whichever file extension they want
=> Teacher can now select instruction and information files from a dropdown box

DuggaSys/diagram.css, DuggaSys/diagram.php
Issue #12423
- Used already existing ID for tooltip in the options panel to give different styling for it.
- Corrected the changed styling that caused the issue after the weekly merge for tooltip in the toolbar.
Hover over the toolbar and options panel to see that the tooltip is positioned correctly. 
**What it should look like**
=> Tool tip not positioned correctly #12423

DuggaSys/contribution_loginbox.js, DuggaSys/contribution_loginbox_service.php
Added so you are blocked from logging in when you are pending or revoked.
relates to issue https://github.com/HGustavs/LenaSYS/issues/12503
when status_Account is 101
when status_Account is 102
------------------------------Testing----------------------------------
Make sure you cant login with a pending/revoked user, test by manually changing account_status to 101 and or 102 in git_user table
=> Added block from logging in when git_user is pending or revoked

DuggaSys/templates/bit-dugga.html, DuggaSys/templates/color-dugga.html, DuggaSys/templates/dugga1.html, DuggaSys/templates/duggaTest.html
Made the popover the same as the version used for dugga2. This fixes the issue of certain buttons being unclickable because the submitButtonTable was over them.
=> Fixed popover buttons not being clickable

DuggaSys/courseedservice.php
@a20vicad If you press the cog wheel next to a course on the main page (courseed.php) and mark visibility as deleted the course will now be scrubbed from memory and removed from the main page. All duggas, code examples, etc will also be scrubbed from memory if they belonged to that course. Because of the amount of information and work (including grades) that can be deleted very easily with three mousse clicks this seams kind of dangerous. Especially since every logged in user currently has editing privileges on courses. But the customers did specify that they wanted everything to be quick and easy for the user.
To test switch to my branch and  make a course in the main page then delete it whit the method above.
Warning I had a lot off memory leak problems when implementing this. Currently …
=> G3 2022 w7 #000001

DuggaSys/diagram.js
The diagram no longer jumps when clicked in container.
=> Elements in diagram "jumps" when started up and pressing a button #12535

DuggaSys/diagram.js
- #12580 
- Added code so that color selector dosen't remain open and closes simulatenously as options panel
- Make sure you're on branch 12580b, don't forget the "b"!
***Make sure you're on branch #12580b, don't forget the "b"!***
1. Select an entity in the diagram
2. Open the options panel
3. Press the color selection option (do not press a color)
4. Close the option panel 
5. Make sure that the color selector closes as well.
=> fixed bug so that the color selector closes simultaneously as the option panel #12580b

DuggaSys/diagram.php
#12549
Updated so that it says UML class instead of UML entity
Just hover over the entity/class button and check that the tooltip text is correct for the UML class.
=> Rename UML-Entity to "UML Class" #12549

DuggaSys/diagram.js
- #12574 
- The color selector had different titles when selecting one- vs multiple objects. Changed so that both titles now say "Color" to give it a more consistent look.
1. Go to diagram dugga
2. Select one object 
3. Open the option panel, make sure the color alternatives title says _"Color"_.
4. Now select multiple objects and open the option panel, , make sure the color alternatives title says _"Color"_ instead of _"BG Color"_.
should **not** look like this:
=> Changed the title for a more consistent look #12574

DuggaSys/diagram.js
Lines now connect to the center of the inheritance element. 
To test: Draw lines to and from inheritance; zoom in and out; check that there is no whitespace between line and element.
=> Fixed lines for UMLRelations #12545

DuggaSys/sectioned.js, Shared/css/codeviewer.css, Shared/css/style.css, Shared/navheader.php
Gave navheader table a fixed table-layout to prevent the navbar to go outside the window. Quite a few problems occured when doing that shift that had to be taken care of.
Testing:
1) Enter Webbprogrammering
2) Open JavaScript Example 1
The navbar should not break when resizing the window width.
3) Login as teacher acount stei
The navbar should not break when resizing the window width.
=> Made the navheader table-layout fixed #12287

Shared/navheader.php
Solution was to add the attribute `target` with value `_blank`.
Testing:
1. Log in as Stei (password is "password")
2. Go to course "Webbprogrammering"
3. Click the button which has been circled in the screenshot below
Before: Link opened in the same window
After: Link should open in new browser tab keeping the previous tab next to it
=> Page needs to open in new external tab

sh/index.php
#12495 
Removed &embed from header in index.php which determined url. Now simply redirects to page normally.
=> Changed redirect when loading dugga via hash so nav-bar still shows #12495

Shared/css/style.css
Height of logged in button is 30px in mobile view instead of 50px.
**For Testing:**
1. Be logged in and enter mobile view. 
2. Check whether the height of the login button is larger than the height of the nav bar.
It should look like this:
=> Height of logged in button is  now 30px in mobile view. 

DuggaSys/showDugga.php, DuggaSys/templates/diagram_dugga.html
- #12476
- "General information" and "Instructions-panel" are hidden if they are empty and there is no file to read from.
1. Log in as a teacher.
2. Go to "Edit dugga" and press the pen on diagram dugga.
3.  Create 4 new duggas:
>a) One where both "File link" fields are empty on "Instruction file" and "General information file".
>b) One where both "File link" fields are filled on "Instruction file" and "General information file" (just scribble anything).
>c) One where only "Instruction file" "File link"-field is filled (again just write some characters).
>d) One where only "General information" "File-link" field is filled (again just write some characters).
4. Enable one at a time to test all four scenarios.
5.  When one of the duggas are enabled log out and go to diagram dugga as a …
=> "General information" and/or "Instructions" only show if a file is available #12476

DuggaSys/diagram.php
Testning:
- go to diagram dugga.
- Click on a double line and type <&# 60 ; Include>> or something else then include.
- After that, all the brackets shall be visible with the text.
=> fixed "angel-brackets" with a esc method issue #12095

DuggaSys/diagram.css
Hover over some tool for more than 1200 ms to make the tooltip visible. Before this implementation the tooltip popped up instantly.
=> Delay for tooltip instructions. Issue #12520.

DuggaSys/sectioned.js, DuggaSys/sectioned.php
The relative deadline calculates a deadline from the course start up until the amount of time you pick. So if the course starts at 2020-05-01 and you pick 2 weeks as the relative deadline then this dugga will have its deadline set to 2020-05-01 plus 14 days. This is, in general, what relative deadlines do.
The relative deadlines are chosen through the menu that appears when you press the cogwheel(logged in as a teacher) on a dugga or quiz. You'll then have the option to choose a time, a amount, and a type to store in the database for this particular dugga.
- Time = Hour and minute of the day
- Amount = Amount of the type
- Type = Days, Weeks or Months
Currently, what happens behind the scenes is that you'll have the option to choose absolute deadlines(as it was before) if you want by …
=> Implementing relative deadlines

DuggaSys/contribution.js
indentation matches now with accounts
before:
after;
testing, 
check different accounts statuses. 
1) create account in contribution (proci works)
2) logg in to contribution as teacher (eg stei)
3) check account sidebar, make sure all match correctly
4) change new account _account_status_ (from 101 to 0 and 102) and notice button changes
=> fixed indentation and matches with actual info

sh/index.php
Reverts HGustavs/LenaSYS#12698
Do not work as intended, perhaps it is due to another problem with the hash that has arisen. To asure not getting more trouble with that earlier trouble this will be reverted. The image tells what happend after this merge when trying to load from hash. There were no 404 before this merge.
=> Revert "Made it so loading diagram from hash doesn't remove nav-bar"

DuggaSys/diagram.js
#12358 
Apperently there is a problem where the ER-table generation does not work on newly created entities.
What has been done:
- Updated the default for entities, relations and attributes by adding a normal state.
What can be tested:
- Place new entities and new attributes and see if they appear in the table. 
At the moment:
How it should look:
=> Potential patch for problem with ER table

DuggaSys/diagram.js
It should not be possible to draw lines between UML- and ER-elements, thus this functionality is now restricted. To test this, simply try to draw a line between these types and notice the error message in the bottom left corner.
=> Lines between UML- and ER-elements: Issue #12142.js

DuggaSys/diagram.js
Fixed the problem where after the ruler has been toggled off and on pressing escape hides the ruler while the ruler is still active. #11885 
3) Open "Options" (Yellow bar to the left of the diagram)
4) Click "Ruler" x2
5) Press ESC/Escape on the keyboard (The ruler souldn't disappear)
=> Fixed pressing escape disabling ruler

DuggaSys/duggaed.js
Put updateInstuction and Updateinfromation in setVariant to get info from left field. It now works as intended.
=> The dropdowns for filelink and gfilelink does not change to the selected variant when changed before. #12610 

DuggaSys/codeviewer.js, DuggaSys/codeviewerService.php
The save button in the edit window saves changes made to the content in the file being edited.
Testing:
3) Open JavaScript Example 1
4) Click edit on the "JavaScript_Ex1.html" box
5) Make any change in the markdown
6) Click save
7) The changes made in the markdown should be displayed in the "JavaScript_Ex1.html" box
=> Fixed saving changes made in the edit window #12687

Shared/css/style.css, Shared/css/template1.css, Shared/css/template2.css, Shared/css/template3.css, Shared/css/template4.css, Shared/css/template5.css, Shared/css/template6.css, Shared/css/template7.css, Shared/css/template8.css, Shared/css/template9.css
Larger mobile devices such as an ipad är will now be in mobile view.
Added a clease where the orientation is portrait.
(portrait meaning the widht(px) of the screen is smaller than the height(px) of the screen.)
For testing:
1: Press ctrl+shift+i
2: Press ctrl+shift+m
(might be different for apple users)
3:Change your view to the ipad air(Or any large device where the widht of the screen is smaller than the height.).
4: Enter an example.
5: The example should be shown in mobile view(Where the boxes are all stacked ontop of eachother).
=> Mobile view for larger mobile devices.

Shared/css/style.css
Removed space in header.
For testing: 
1. Log in as teacher
2. Enter course Webbprogrammering
3. Look at the header and the space between the course bar and the back button is no longer there. 
5. Make the window smaller & the burger menu will appear with appropriate spacing.
=> Removed space in header.

Shared/css/codeviewer.css, Shared/css/style.css
Made the code lines numbers background inherit from `.codeborder` through removing redundant css line.
Testing (follow the same steps both for light and dark mode:
1. Go to course Webbprogrammering
2. Click any of the code examples
3. Open inspect and click the select tool
4. Select the code bar 
5. Find the class `codeborder` in inspect
6. Change color of class codeborder to any color
Before:
- before changing color
- after changing color
After: All lines should get the color chosen except the ones that were marked with another color since before
- before changing color
- after changing color
=> made the code lines numbers background inherit from .codeborder

DuggaSys/codeviewer.js, Shared/css/style.css
Lines are now copied using another function instead, as the old version did not work well when selecting specific elements in a class.
=> You can now copy only important code

Shared/css/blackTheme.css, Shared/css/style.css
Code lines should inherit color from .box since the background should follow if the background color changes. Solved by setting background-color: transparent and through removad or redundant css code lines.
Testing (repeat the same teps for light and dark theme):
1. Go to course Webbprogrammering
2. Open inspect
3. Click the select tool
4. Select a code line 
5. Find element .box in the css style
6. Change the background color to any color
Before: not all elements were affected by the color change.
After: every codeviewer element (description and code)  on the page shuold get the the same background color.
=> made code lines inherit background color from .box

DuggaSys/sectioned.js
I made it so all elements listed as deleted will be hidden once more after moving a element. Be aware that I have not been able to test this as I have discovered a weird bug on my machine that makes me unable to se the sectioned.php pages in localhost. I don't know why but it seams to date back several merges. I can se sectioned.php on branch G3-2022-#merge4. But whilst I have not been able to test my solution I believe it should work.
To test switch to my branch and try to run secioned.php as a superuser and delete a element. Then move another element and check that my element does not disappear.
=> I have Probably fixed the problem with deleted elements being unhidden after moving another element.

DuggaSys/sectioned.js, Shared/dugga.js
Fixed an issue that prevented the edit box from showing up when pressing tab to navigate to the cog wheel and then pressing enter on the selected item. 
There is now also highlighting when pressing enter to save the new changes made whilst editing a section on sectioned.php. 
To test this simply go in to any course(Logged in) and press the cog wheel. Then you need to edit the name. Press enter and watch if the "edited section" is highlighted.
=> Added highlighting to enter press

DuggaSys/duggaedservice.php
Made it so deleting a variant also deletes all stored user answers that correlates to said variant.
=> It's now possible to delete variants with assigned user answers #12638

DuggaSys/codeviewer.js
Windows new line characters (\r\n) in course files are no longer represented as double new lines in the codeviewer (\r and \n).
Testing:
1) Enter Webbprogrammering
2) Open JavaScript Example 1
Before:
After:
=> Fix windows new lines in the codeviewer #12777

DuggaSys/courseed.js, DuggaSys/courseed.php
How to test:
1. Go to the first page 
2. click on the cogwheel beside the heading 
3. Tab in the new view 
4. Close the window and click on a cogwheel beside de courses 
5. Tab in the new view
The issue is solved if you can tab directly when you open the new view
=> Added focus() to use tab function when you click and open cogwheel
